# import data

In [1]:
import pandas as pd
import numpy as np

# Set option to display all columns
pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_parquet("outputs_new/dedupe_data_out.parquet")
data

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last
0,crossref::10.21467/preprints.48,AIJR Preprints,crossref,10.21467/preprints.48,https://doi.org/10.21467/preprints.48,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,"Bird’s Eye View on the Diagnosis, Treatment, &...","Panchalingala, Sai Bhargavi",None,None,None,None,,,,,false,None,None,None,None,parent,2020-05-03,2020.0,2020,None,parent,None,None,None,None,None,None
1,crossref::10.21467/preprints.43,AIJR Preprints,crossref,10.21467/preprints.43,https://doi.org/10.21467/preprints.43,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Doxycycline and Minocycline Drugs as a Treatme...,"Mostafa, Mohamed",None,None,None,None,,,,,false,None,None,None,None,parent,2020-04-25,2020.0,2020,None,parent,None,None,mohamed_mostafa,doxycycline and minocycline drugs as a treatme...,mostafa|m,None
2,crossref::10.21467/preprints.39,AIJR Preprints,crossref,10.21467/preprints.39,https://doi.org/10.21467/preprints.39,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,A Genetic Perspective of 2019-nCoV in Relation...,"Dasgupta, Rimjhim",None,None,None,None,,,,,false,None,None,None,None,parent,2020-04-16,2020.0,2020,None,parent,None,None,dasgupta_rimjhim,a genetic perspective of 2019 ncov in relation...,dasgupta|r,None
3,crossref::10.21467/preprints.38,AIJR Preprints,crossref,10.21467/preprints.38,https://doi.org/10.21467/preprints.38,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Marine Algae as a Natural Source for Antiviral...,"Musale, Amar S; G., Raja Krishna Kumar; Sapre,...",None,None,None,None,,,,,false,None,None,None,None,parent,2020-04-15,2020.0,2020,None,parent,None,None,None,None,None,None
4,crossref::10.21467/preprints.36,AIJR Preprints,crossref,10.21467/preprints.36,https://doi.org/10.21467/preprints.36,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Possible Prevention of COVID 19 by Using Linol...,"Subhash, Venkata; G, Raja Krishna Kumar; Sapre...",None,None,None,None,,,,,false,None,None,None,None,parent,2020-04-15,2020.0,2020,None,parent,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7911896,openalex::W999325625,viXra,openalex,None,None,https://vixra.org/pdf/1409.0090v1.pdf,preprint,None,Three Objections to Modern Physics,Lubomir Vlcek,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-09-01,2014.0,2014,None,parent,None,None,lubomir_vlcek,three objections to modern physics,vlcek|l,None
7911897,openalex::W999460032,viXra,openalex,None,None,https://vixra.org/abs/1112.0094,preprint,None,Particle Mass Ratios,DT Froedge,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2011-12-01,2011.0,2011,None,parent,None,None,dt_froedge,particle mass ratios,froedge|d,None
7911898,openalex::W99967155,viXra,openalex,None,None,https://vixra.org/pdf/1406.0019v1.pdf,preprint,None,Quantum FFF Theory Proposals for Some Unsolved...,Leo Vuyk,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-06-01,2014.0,2014,None,parent,None,None,leo_vuyk,quantum fff theory proposals for some unsolved...,vuyk|l,None
7911899,openalex::W999790414,viXra,openalex,None,None,https://vixra.org/pdf/1306.0105v3.pdf,preprint,None,Investigation of the Formalism of Particle Dyn...,Chi-Yi Chen,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2013-06-01,2013.0,2013,None,parent,None,None,chen_chi_yi,investigation of the formalism of particle dyn...,chen|c,None
7911900,openalex::W999805801,viXra,openalex,None,None,https://vixra.org/pdf/1412.0197v3.pdf,preprint,None,Electromagnetic Energy and Electromagnetic For...,Yu.A. Spirichev,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-12-01,2014.0,2014,None,parent,None,None,a_spirichev_yu,electromagnetic energy and electromagnetic for...,spirichev|y,None

In [3]:
data.columns

Index(['record_id', 'server_name', 'backend', 'doi', 'doi_url',
       'landing_page_url', 'type_backend_raw', 'subtype_backend_raw', 'title',
       'authors_flat', 'institutions_flat', 'countries_flat', 'relations_json',
       'version_label', 'is_version_of', 'is_preprint_of', 'has_preprint',
       'has_review', 'has_published_version', 'published_version_ids_json',
       'version_of_ids_json', 'update_to_json', 'raw_relationships_json',
       'records_hierarchy', 'date_first_seen', 'publication_year',
       'publication_year_first_seen', 'raw_dates', 'records_hierarchy_backup',
       'parent_record_id', 'dup_group_id', 'authors_fp_tokenbag',
       'title_clean_v2', 'authors_fp_last_initial', 'authors_fp_last'],
      dtype='object')

In [4]:
data['is_version_of'] = data['is_version_of'].replace('', np.nan)

relation_ship_count = data['is_version_of'].value_counts()
relation_ship_count

is_version_of
10.2139/ssrn.2721313                                                                                  152
10.5281/zenodo.16899882                                                                                73
10.5281/zenodo.15408957                                                                                50
10.5281/zenodo.16944712                                                                                29
10.5281/zenodo.15571875                                                                                22
                                                                                                     ...
10.20944/preprints202209.0202.v2                                                                        1
10.20944/preprints202012.0703.v1;10.20944/preprints202012.0703.v2;10.20944/preprints202012.0703.v3      1
10.20944/preprints202012.0703.v1;10.20944/preprints202012.0703.v2;10.20944/preprints202012.0703.v4      1
10.20944/preprints202012.0703.v1;10.20944/preprints202012.0703.v3;10.20944/preprints202012.0703.v4      1
10.20944/preprints202212.0117.v1                                                                        1
Name: count, Length: 79895, dtype: int64

In [5]:
# Columns to duplicate
cols_to_duplicate = ['records_hierarchy', 'parent_record_id','dup_group_id']

# Duplicate the columns with new names
data[['records_hierarchy_dedupe_backup', 'parent_record_id_dedupe_backup', 'dup_group_id_dedupe_backup']] = data[cols_to_duplicate].copy()

data.columns

Index(['record_id', 'server_name', 'backend', 'doi', 'doi_url',
       'landing_page_url', 'type_backend_raw', 'subtype_backend_raw', 'title',
       'authors_flat', 'institutions_flat', 'countries_flat', 'relations_json',
       'version_label', 'is_version_of', 'is_preprint_of', 'has_preprint',
       'has_review', 'has_published_version', 'published_version_ids_json',
       'version_of_ids_json', 'update_to_json', 'raw_relationships_json',
       'records_hierarchy', 'date_first_seen', 'publication_year',
       'publication_year_first_seen', 'raw_dates', 'records_hierarchy_backup',
       'parent_record_id', 'dup_group_id', 'authors_fp_tokenbag',
       'title_clean_v2', 'authors_fp_last_initial', 'authors_fp_last',
       'records_hierarchy_dedupe_backup', 'parent_record_id_dedupe_backup',
       'dup_group_id_dedupe_backup'],
      dtype='object')

In [6]:
bad_values = {"others", "part_of", "comment", "review"}

mask = ~data["records_hierarchy_backup"].astype(str).str.contains(
    r"\b(" + "|".join(bad_values) + r")\b",
    case=False,
    regex=True
)

data_clean = data[mask].copy()

/tmp/ipykernel_5490/2399585284.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = ~data["records_hierarchy_backup"].astype(str).str.contains(

In [7]:
data_clean['records_hierarchy'].unique()

array(['parent', 'parent - duplicate (SSRN)',
       'parent - duplicate (AfricArXiv)',
       'parent - duplicate (AMRC Open Research)',
       'parent - duplicate (Open Science Framework)',
       'parent - duplicate (APSA Preprints)',
       'parent - duplicate (medRxiv)',
       'parent - duplicate (ResearchGate)', 'parent - duplicate (arXiv)',
       'parent - duplicate (SocArXiv)',
       'parent - duplicate (PREPRINTS.RU)',
       'parent - duplicate (MediArXiv)',
       'parent - duplicate (ARPHA Preprints)',
       'parent - duplicate (Research Square)',
       'parent - duplicate (Authorea Inc.)',
       'parent - duplicate (bioRxiv)', 'parent - duplicate (Zenodo)',
       'parent - duplicate (ART-Dok)', 'parent - duplicate (HAL)',
       'parent - duplicate (Social Science Open Access Repository)',
       'parent - duplicate (Humanities Commons CORE)',
       'parent - duplicate (Advance)',
       'parent - duplicate (AgEcon Search)',
       'parent - duplicate (Preprints.org)',
       'parent - duplicate (PsyArXiv)', 'parent - duplicate (EdArXiv)',
       'parent - duplicate (Cambridge Open Engage)',
       'parent - duplicate (TechRxiv)',
       'parent - duplicate (Thesis Commons)',
       'parent - duplicate (RePEc: Research Papers in Economics)',
       'parent - duplicate (EconStor Preprints)',
       'parent - duplicate (Munich Personal RePEc Archive)',
       'parent - duplicate (Organic Eprints)',
       'parent - duplicate (National Bureau of Economic Research)',
       'parent - duplicate (AgriRxiv)', 'parent - duplicate (MetaArXiv)',
       'parent - duplicate (VeriXiv)', 'parent - duplicate (INA-Rxiv)',
       'parent - duplicate (Earth and Space Science Open Archive)',
       'parent - duplicate (Arabixiv)',
       'parent - duplicate (LIS Scholarship Archive)',
       'parent - duplicate (PeerJ Preprints)',
       'parent - duplicate (ChemRxiv)', 'parent - duplicate (EcoEvoRxiv)',
       'parent - duplicate (ScienceOpen Preprints)',
       'parent - duplicate (JMIR Preprints)',
       'parent - duplicate (engrXiv)', 'parent - duplicate (EarthArXiv)',
       'parent - duplicate (Qeios)', 'parent - duplicate (eLife)',
       'parent - duplicate (Wellcome Open Research)',
       'parent - duplicate (F1000Research)',
       'parent - duplicate (EGUsphere)',
       'parent - duplicate (ResearchHub)',
       'parent - duplicate (BioHackrXiv)',
       'parent - duplicate (BodoArXiv)',
       'parent - duplicate (CERN document server)',
       'parent - duplicate (IndiaRxiv)',
       'parent - duplicate (Beilstein Archives)',
       'parent - duplicate (CoP)', 'parent - duplicate (CogPrints)',
       'parent - duplicate (Covid-19 Preprints)',
       'parent - duplicate (CrimRxiv)',
       'parent - duplicate (Law Archive)',
       'parent - duplicate (CrossAsia-Repository)',
       'parent - duplicate (DSpace@MIT)',
       'parent - duplicate (IACR Cryptology ePrint Archive)',
       'parent - duplicate (Digital Access to Scholarship at Harvard (DASH) (Harvard University))',
       'parent - duplicate (E-LIS Repository)',
       'parent - duplicate (ECSarXiv)',
       'parent - duplicate (EasyChair preprint)',
       'parent - duplicate (LSE Research Online Documents on Economics)',
       'parent - duplicate (Frenxiv)', 'parent - duplicate (MarXiv)',
       'parent - duplicate (Electron Colloquium Comput Complex)',
       'parent - duplicate (Encyclopedia)',
       'parent - duplicate (EnerarXiv)',
       'parent - duplicate (Nature Precedings)',
       'parent - duplicate (viXra)',
       'parent - duplicate (Open Research Africa)',
       'parent - duplicate (FocUS Archive)',
       'parent - duplicate (Gates Open Research)',
       'parent - duplicate (PhilSci-Archive)',
       'parent - duplicate (HRB Open Research)',
       'parent - duplicate (NutriXiv)', 'parent - duplicate (SportRxiv)',
       'parent - duplicate (searchRxiv)', 'parent - duplicate (Jxiv)',
       'parent - duplicate (Keldysh Institute Preprints)',
       'parent - duplicate (LatArXiv)',
       'parent - duplicate (MNI Open Research)',
       'parent - duplicate (MindRxiv)',
       'parent - duplicate (NewAddictionsX)',
       'parent - duplicate (Open Research Europe)',
       'parent - duplicate (AIJR Preprints)',
       'parent - duplicate (PaleorXiv)',
       'parent - duplicate (Oroboros Instruments)',
       'parent - duplicate (SciELO Preprints)',
       'parent - duplicate (Prepublicaciones OpenCiencia)',
       'parent - duplicate (PropylaeumDok)',
       'parent - duplicate (UCL Open Environment)',
       'parent - duplicate (UnisaRxiv)', 'parent - duplicate (prepare@u)',
       'parent - duplicate (SAE Mobilus®)',
       'parent - duplicate (Therapoid)'], dtype=object)

In [8]:
data_clean['records_hierarchy_backup'].value_counts().head(60)

records_hierarchy_backup
parent                              7771465
version                              102316
publish_version                       12888
mirror (AgEcon Search)                 6607
mirror (arXiv)                         6419
child                                  2061
mirror (ResearchGate)                   827
correction                              354
mirror (Zenodo)                         191
mirror (bioRxiv)                         29
mirror (SSRN)                            23
mirror (Open Science Framework)          21
mirror (Humanities Commons CORE)         16
parent_duplicate                          4
mirror (AfricArXiv)                       2
mirror (Research Square)                  2
mirror (EarthArXiv)                       2
mirror (TechRxiv)                         1
mirror (eLife)                            1
mirror (Oroboros Instruments)             1
mirror (medRxiv)                          1
mirror (Law Archive)                      1
mirror (Thesis Commons)                   1
mirror (SocArXiv)                         1
mirror (AgriRxiv)                         1
Name: count, dtype: int64

In [9]:
len(data_clean["server_name"].value_counts())

109

# extract_has_version_dois

In [10]:
import pandas as pd
import json

VERSION_RELATION_TYPES = {
    # "HasPart",
    "IsIdenticalTo",
    # "IsSupplementedBy",
    # "IsSupplementTo",
    "IsNewVersionOf",
    "IsVersionOf",
    # "IsPartOf",
    "IsPreviousVersionOf",
    "HasVersion",
}

# Pre-build the quick string pre-check
VERSION_RELATION_PATTERNS = tuple(f'"{r}"' for r in VERSION_RELATION_TYPES)


def extract_has_version_dois(relations_json_value):
    """
    Extract DOIs whose relationType is any of VERSION_RELATION_TYPES from relations_json.
    Returns semicolon-joined string or None.
    """
    if pd.isna(relations_json_value) or not relations_json_value:
        return None

    # Quick pre-check: skip JSON parsing if none of the patterns are present
    if not any(pattern in relations_json_value for pattern in VERSION_RELATION_PATTERNS):
        return None

    try:
        relations = json.loads(relations_json_value)
        dois = [
            r["relatedIdentifier"]
            for r in relations
            if isinstance(r, dict)
            and r.get("relationType") in VERSION_RELATION_TYPES
            and r.get("relatedIdentifierType") == "DOI"
            and r.get("relatedIdentifier")
        ]
        return ";".join(dois) if dois else None
    except (json.JSONDecodeError, TypeError):
        return None


def apply_extract_has_version(df, col="relations_json", new_col="has_version_dois", chunksize=500_000):
    """
    Apply extraction in chunks to manage memory on large DataFrames.
    Adds `new_col` to df in-place.
    """
    results = []
    total = len(df)

    for start in range(0, total, chunksize):
        end = min(start + chunksize, total)
        chunk = df[col].iloc[start:end]
        results.append(chunk.map(extract_has_version_dois))
        print(f"Processed {end:,} / {total:,} rows", end="\r")

    df[new_col] = pd.concat(results)
    print(f"\nDone. Non-null values: {df[new_col].notna().sum():,}")
    return df


# Usage
# df = apply_extract_has_version(df)

In [11]:
data_clean_isversionof = apply_extract_has_version(data_clean)
data_clean_isversionof

Processed 7,905,699 / 7,905,699 rows
Done. Non-null values: 1,476,586

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
0,crossref::10.21467/preprints.48,AIJR Preprints,crossref,10.21467/preprints.48,https://doi.org/10.21467/preprints.48,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,"Bird’s Eye View on the Diagnosis, Treatment, &...","Panchalingala, Sai Bhargavi",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-05-03,2020.0,2020,None,parent,None,None,None,None,None,None,parent,None,None,None
1,crossref::10.21467/preprints.43,AIJR Preprints,crossref,10.21467/preprints.43,https://doi.org/10.21467/preprints.43,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Doxycycline and Minocycline Drugs as a Treatme...,"Mostafa, Mohamed",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-25,2020.0,2020,None,parent,None,None,mohamed_mostafa,doxycycline and minocycline drugs as a treatme...,mostafa|m,None,parent,None,None,None
2,crossref::10.21467/preprints.39,AIJR Preprints,crossref,10.21467/preprints.39,https://doi.org/10.21467/preprints.39,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,A Genetic Perspective of 2019-nCoV in Relation...,"Dasgupta, Rimjhim",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-16,2020.0,2020,None,parent,None,None,dasgupta_rimjhim,a genetic perspective of 2019 ncov in relation...,dasgupta|r,None,parent,None,None,None
3,crossref::10.21467/preprints.38,AIJR Preprints,crossref,10.21467/preprints.38,https://doi.org/10.21467/preprints.38,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Marine Algae as a Natural Source for Antiviral...,"Musale, Amar S; G., Raja Krishna Kumar; Sapre,...",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-15,2020.0,2020,None,parent,None,None,None,None,None,None,parent,None,None,None
4,crossref::10.21467/preprints.36,AIJR Preprints,crossref,10.21467/preprints.36,https://doi.org/10.21467/preprints.36,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Possible Prevention of COVID 19 by Using Linol...,"Subhash, Venkata; G, Raja Krishna Kumar; Sapre...",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-15,2020.0,2020,None,parent,None,None,None,None,None,None,parent,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7911896,openalex::W999325625,viXra,openalex,None,None,https://vixra.org/pdf/1409.0090v1.pdf,preprint,None,Three Objections to Modern Physics,Lubomir Vlcek,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-09-01,2014.0,2014,None,parent,None,None,lubomir_vlcek,three objections to modern physics,vlcek|l,None,parent,None,None,None
7911897,openalex::W999460032,viXra,openalex,None,None,https://vixra.org/abs/1112.0094,preprint,None,Particle Mass Ratios,DT Froedge,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2011-12-01,2011.0,2011,None,parent,None,None,dt_froedge,particle mass ratios,froedge|d,None,parent,None,None,None
7911898,openalex::W99967155,viXra,openalex,None,None,https://vixra.org/pdf/1406.0019v1.pdf,preprint,None,Quantum FFF Theory Proposals for Some Unsolved...,Leo Vuyk,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-06-01,2014.0,2014,None,parent,None,None,leo_vuyk,quantum fff theory proposals for some unsolved...,vuyk|l,None,parent,None,None,None
7911899,openalex::W999790414,viXra,openalex,None,None,https://vixra.org/pdf/1306.0105v3.pdf,preprint,None,Investigation of the Formalism of Particle Dyn...,Chi-Yi Chen,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2013-06-01,2013.0,2013,None,parent,None,None,chen_chi_yi,investigation of the formalism of particle dyn...,chen|c,None,parent,None,None,None
7911900,openalex::W999805801,viXra,openalex,None,None,https://vixra.org/pdf/1412.0197v3.pdf,preprint,None,Electromagnetic Energy and Electromagnetic For...,Yu.A. Spirichev,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-12-01,2014.0,2014,None,parent,None,None,a_spirichev_yu,electromagnetic energy and electromagnetic for...,spirichev|y,None,parent,None,None,None

In [12]:
def has_relations_but_no_has_version(relations_json_value):
    """
    Returns True if the cell has {"relatedIdentifier" patterns 
    but none with relationType == 'HasVersion'.
    """
    if pd.isna(relations_json_value) or not relations_json_value:
        return False
    
    if '"relatedIdentifier"' not in relations_json_value:
        return False
    
    # Has relatedIdentifier but no HasVersion at all
    return '"HasVersion"' not in relations_json_value


# --- Get the subset of rows matching this condition ---
mask = data_clean_isversionof["relations_json"].map(has_relations_but_no_has_version)
df_no_has_version = data_clean_isversionof[mask]

print(f"Rows with relatedIdentifier but no HasVersion: {mask.sum():,}")
print(f"Out of rows with any relatedIdentifier: {data_clean_isversionof['relations_json'].str.contains('relatedIdentifier', na=False).sum():,}")

Rows with relatedIdentifier but no HasVersion: 1,401,165
Out of rows with any relatedIdentifier: 1,480,296

In [13]:
import pandas as pd
import json
from collections import Counter

def get_all_relation_types(df, col="relations_json", chunksize=500_000):
    """
    Extract and count all distinct relationType values across the entire DataFrame.
    Returns a sorted DataFrame with relationType and their counts.
    """
    relation_type_counter = Counter()
    total = len(df)

    for start in range(0, total, chunksize):
        end = min(start + chunksize, total)
        chunk = data_clean_isversionof[col].iloc[start:end].dropna()

        for val in chunk:
            if '"relationType"' not in val:
                continue
            try:
                relations = json.loads(val)
                for r in relations:
                    if isinstance(r, dict) and r.get("relationType"):
                        relation_type_counter[r["relationType"]] += 1
            except (json.JSONDecodeError, TypeError):
                pass

        print(f"Processed {end:,} / {total:,} rows", end="\r")

    print("\nDone.")

    result = pd.DataFrame(
        relation_type_counter.most_common(),
        columns=["relationType", "count"]
    )
    result["count"] = result["count"].astype(int)
    result["percentage"] = (result["count"] / result["count"].sum() * 100).round(2)

    return result


# Usage
relation_types_df = get_all_relation_types(data_clean_isversionof)
print(relation_types_df.to_string(index=False))

Processed 7,905,699 / 7,905,699 rows
Done.
       relationType   count  percentage
        IsVersionOf 1394754       88.19
         HasVersion  111412        7.04
     IsSupplementTo   13772        0.87
           IsPartOf   10960        0.69
              Cites   10106        0.64
     IsNewVersionOf    7516        0.48
         References    6913        0.44
   IsSupplementedBy    5471        0.35
          Continues    5092        0.32
      IsDerivedFrom    2901        0.18
IsPreviousVersionOf    2404        0.15
     IsReferencedBy    1517        0.10
      IsContinuedBy    1211        0.08
      IsIdenticalTo    1071        0.07
            HasPart     821        0.05
      IsDescribedBy     756        0.05
          IsCitedBy     708        0.04
      IsPublishedIn     640        0.04
          Describes     584        0.04
         IsSourceOf     582        0.04
        HasMetadata     529        0.03
    IsVariantFormOf     382        0.02
     IsDocumentedBy     283        0.02
          Documents     171        0.01
   IsOriginalFormOf     141        0.01
          Obsoletes     141        0.01
           Requires     136        0.01
       IsCompiledBy     122        0.01
      IsObsoletedBy     111        0.01
           Compiles     106        0.01
            Reviews      72        0.00
      IsMetadataFor      70        0.00
       IsReviewedBy      61        0.00
       IsRequiredBy      49        0.00

In [14]:
pattern = '"HasVersion"'

mask = data_clean_isversionof['relations_json'].str.contains(pattern, regex=False, na=False)
result2 = data_clean_isversionof[mask]
result2

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
223589,datacite::10.17181/y2gch-sv478,CERN document server,datacite,10.17181/y2gch-sv478,https://doi.org/10.17181/y2gch-sv478,https://repository.cern/doi/10.17181/y2gch-sv478,Text,Technical note,Recovery of bremsstrahlung photons in a FCC-ee...,"Perez, Emmanuel; Selvaggi, Michele",CERN,None,"[{""relatedIdentifier"": ""10.17181/87nyk-0rg63"",...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent - duplicate (CERN document server),2023-08-01,2023.0,2023,"[{""date"": ""2023-08-01"", ""dateType"": ""Issued""}]",parent,datacite::10.17181/87nyk-0rg63,4143106710772787967,emmanuel_perez;michele_selvaggi,recovery of bremsstrahlung photons in a fcc ee...,None,None,parent - duplicate (CERN document server),datacite::10.17181/87nyk-0rg63,4143106710772787967,10.17181/87nyk-0rg63
223590,datacite::10.17181/2gfvb-1rw11,CERN document server,datacite,10.17181/2gfvb-1rw11,https://doi.org/10.17181/2gfvb-1rw11,https://repository.cern/doi/10.17181/2gfvb-1rw11,Text,Technical note,A selection of benchmark studies at FCC-ee,The FCC PED Coordination group,None,None,"[{""relatedIdentifier"": ""10.17181/r7xwv-3s961"",...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,11853318414248413722,coordination_fcc_group_ped_the,a selection of benchmark studies at fcc ee,group|t,None,parent,None,11853318414248413722,10.17181/r7xwv-3s961
223592,datacite::10.17181/5m6et-4k782,CERN document server,datacite,10.17181/5m6et-4k782,https://doi.org/10.17181/5m6et-4k782,https://repository.cern/doi/10.17181/5m6et-4k782,Preprint,,FCC-ee Detector requirements: geometric accept...,"Blondel, Alain; Dam, Mogens","LPNHE, Paris-Sorbonne, FRANCE; Niels Bohr Isti...",None,"[{""relatedIdentifier"": ""10.17181/v47k3-arh69"",...",V2- 5 September 2023,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2023-08-14,2023.0,2023,"[{""date"": ""2023-09-05"", ""dateType"": ""Issued""}]",parent,None,9605108797428949011,alain_blondel;dam_mogens,fcc ee detector requirements geometric accepta...,None,None,parent,None,9605108797428949011,10.17181/v47k3-arh69;10.17181/f1fs5-0jr59
223596,datacite::10.17181/0gb45-t5f55,CERN document server,datacite,10.17181/0gb45-t5f55,https://doi.org/10.17181/0gb45-t5f55,https://repository.cern/doi/10.17181/0gb45-t5f55,Text,,Accelerator and physics requirements for the c...,"Aßmann, Ralph; Bauche, Jeremie; Barber, Desmon...",DESY; CERN; University of Geneva; Istituto Naz...,None,"[{""relatedIdentifier"": ""10.17181/zb0qc-acj59"",...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2023-08-16,2023.0,2023,"[{""date"": ""2023-08-16"", ""dateType"": ""Issued""}]",parent,None,86457416207560753,alain_blondel;andrea_ciarma;angeles_faus_golfe...,accelerator and physics requirements for the c...,None,None,parent,None,86457416207560753,10.17181/zb0qc-acj59
223598,datacite::10.17181/224fq-qtf30,CERN document server,datacite,10.17181/224fq-qtf30,https://doi.org/10.17181/224fq-qtf30,https://repository.cern/doi/10.17181/224fq-qtf30,Text,Technical note,Particle Physics considerations for the FCC-ee...,"Blondel, Alain; Grojean, Christophe; Janot, Pa...","LPNHE Paris and Université de Genève; DESY, Ha...",None,"[{""relatedIdentifier"": ""10.17181/qttzk-wpe74"",...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2023-08-18,2023.0,2023,"[{""date"": ""2023-08-18"", ""dateType"": ""Issued""}]",parent,None,16853275075220311313,alain_blondel;christophe_grojean;guy_wilkinson...,particle physics considerations for the fcc ee...,blondel|a;grojean|c;janot|p;wilkinson|g,None,parent,None,16853275075220311313,10.17181/qttzk-wpe74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4549197,datacite::10.5281/zenodo.5464508,Zenodo,datacite,10.5281/zenodo.5464508,https://doi.org/10.5281/zenodo.5464508,https://zenodo.org/record/5464508,Text,Preprint,Measuring trust in automated driving using a m...,"Clement, Philipp; Danzinger, Herbert; Veledar,...",AVL List GmbH; University of Graz; Graz Univer...,None,"[{""relatedIdentifier"": ""10.5281/zenodo.5464509...",PREPRINT,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2021-09-06,2021.0,2021,"[{""date"": ""2021-09-06"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.5464509,16841712529322977442,arno_eichberger;clemens_koenczoel;clement_phil...,measuring trust in automated driving using a m...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.5464509,16841712529322977442,10.5281/zenodo.5464509
4549199,datacite::10.5281/zenodo.5477448,Zenodo,datacite,10.5281/zenodo.5477448,https://doi.org/10.5281/zenodo.5477448,https://zenodo.org/record/5477448,Text,Preprint,Spin ½ and Matrices,"Ruggeri, Francesco R.",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.5477449...",1,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2021-09-06,2021.0,2021,"[{""date"": ""2021-09-06"", ""dateType"": ""Issued""}]",parent,None,None,francesco_r_ruggeri,spin 1 2 and matrices,ruggeri|f,ruggeri,parent,None,None,10.5281/zenodo.5477449
4549201,datacite::10.5281/zenodo.5482410,Zenodo,datacite,10.5281/zenodo.5482410,https://doi.org/10.5281/zenodo.5482410,https://zenodo.org/record/5482410,Text,Preprint,"Wormholes Do Not Exist, They are Mathematical ...","Haug, Espen",Norwegian University of Life Sciences,None,"[{""relatedIdentifier"": ""10.5281/zenodo.5482411...",2,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2021-09-07,2021.0,2021,"[{""date"": ""2021-09-07"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.5482411,1018103201769658577,espen_haug,wormholes do not exist they are mathematical a...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.5482411,1018103201769658577,10.5281/zenodo.5482411
4549203,datacite::10.5281/zenodo.5482851,Zenodo,datacite,10.5281/zenodo.5482851,https://doi.org/10.5281/zenodo.5482851,https://zenodo.org/record/5482851,Text,Preprint,Towards a Global Public Repository of Communit...,"Samuel, Robyn M.; Meyer, Raissa; Buttigieg, Pi...","School of Ocean and Earth Science, University ...",None,"[{""relatedIdentifier"": ""10.5281/zenodo.5482852...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2021-09-07,2021.0,2021,"[{""date"": ""2021-09-07"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.5482852,17691485959976298526,alison_watts;buttigieg_luigi_pier;christina_pa...,towards a global public repository of communit...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.5482852,17691485959976298526,10.5281/zenodo.5482852
4549205,datacite::10.5281/zenodo.5493584,Zenodo,datacite,10.5281/zenodo.5493584,https://doi.org/10.5281/zenodo.5493584,https://zenodo.org/record/5493584,Text,Preprint,"Data from paper ""Targeted Search for Weak Sate...","Prabu, Steve; Hancock, Paul; Zhang, Xiang; Tin...",Curtin University; CSIRO,None,"[{""relatedIdentifier"": ""10.5281/zenodo.5493585...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2021-09-08,2021.0,2021,"[{""date"": ""2021-09-08"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.5493585,5498235216209304411,hancock_paul;prabu_steve;steven_tingay;xiang_z...,data from paper targeted search for weak satel...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.5493585,5498235216209304411,10.5281/zenodo.5493585

In [15]:
pattern = '"relatedIdentifier"'

mask = data_clean_isversionof['relations_json'].str.contains(pattern, regex=False, na=False)
result = data_clean_isversionof[mask]
result

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
223569,datacite::10.17181/cern.5m67.mtcg,CERN document server,datacite,10.17181/cern.5m67.mtcg,https://doi.org/10.17181/cern.5m67.mtcg,https://repository.cern/doi/10.17181/CERN.5M67...,Text,Thesis,Pushing SUSY's boundaries,"Besjes, Geert Jan",NIKHEF Amsterdam; Nijmegen U IMAPP,None,"[{""relatedIdentifier"": ""978-94-6259-545-3"", ""r...",None,NaN,10.17181/3nhw7-23q32,,,true,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2015-01-21,2015.0,2015,"[{""date"": ""2015-05-15"", ""dateType"": ""Issued""}]",parent,None,14994520479402268836,besjes_geert_jan,pushing susy s boundaries,None,None,parent,None,14994520479402268836,10.17181/3nhw7-23q32
223570,datacite::10.17181/cern.k7md.n3vz,CERN document server,datacite,10.17181/cern.k7md.n3vz,https://doi.org/10.17181/cern.k7md.n3vz,https://repository.cern/doi/10.17181/CERN.K7MD...,Text,Thesis,A Silicon Strip Detector for the Phase II High...,"García-Argos, Carlos",Valencia U,None,"[{""relatedIdentifier"": ""10.17181/f704t-8kc16"",...",None,NaN,10.17181/f704t-8kc16,,,true,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent - duplicate (arXiv),2015-01-28,2015.0,2015,"[{""date"": ""2015-05-15"", ""dateType"": ""Issued""}]",parent,datacite::10.48550/arxiv.1501.02903,2386049772774676724,argos_carlos_garcia,a silicon strip detector for the phase ii high...,None,None,parent - duplicate (arXiv),datacite::10.48550/arxiv.1501.02903,2386049772774676724,10.17181/f704t-8kc16
223571,datacite::10.17181/cern.l5n9.2gcs,CERN document server,datacite,10.17181/cern.l5n9.2gcs,https://doi.org/10.17181/cern.l5n9.2gcs,https://repository.cern/doi/10.17181/CERN.L5N9...,Text,Thesis,A Distributed Monitoring and Control System fo...,"Rossel, Ralf Erik",Mainz U,None,"[{""relatedIdentifier"": ""10.17181/16k78-yx461"",...",None,NaN,10.17181/16k78-yx461,,,true,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2015-11-09,2015.0,2015,"[{""date"": ""2015-11-09"", ""dateType"": ""Issued""}]",parent,None,13169882856165365376,erik_ralf_rossel,a distributed monitoring and control system fo...,rossel|r,None,parent,None,13169882856165365376,10.17181/16k78-yx461
223572,datacite::10.17181/cern.0hnz.7z6x,CERN document server,datacite,10.17181/cern.0hnz.7z6x,https://doi.org/10.17181/cern.0hnz.7z6x,https://repository.cern/doi/10.17181/CERN.0HNZ...,Text,Thesis,An all-solid state laser system for the laser ...,"Rothe, Sebastian",Mainz U Inst Kernphys,None,"[{""relatedIdentifier"": ""10.17181/za31q-phx67"",...",None,NaN,10.17181/za31q-phx67,,,true,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2013-02-25,2013.0,2013,"[{""date"": ""2013-02-25"", ""dateType"": ""Issued""}]",parent,None,10706844190754784103,rothe_sebastian,an all solid state laser system for the laser ...,rothe|s,None,parent,None,10706844190754784103,10.17181/za31q-phx67
223573,datacite::10.17181/cern.r8qg.wacq,CERN document server,datacite,10.17181/cern.r8qg.wacq,https://doi.org/10.17181/cern.r8qg.wacq,https://repository.cern/doi/10.17181/CERN.R8QG...,Text,Thesis,Improving the Selectivity of the ISOLDE Resona...,"Fink, Daniel Andreas",Heidelberg U,None,"[{""relatedIdentifier"": ""10.17181/t4eej-q2647"",...",None,NaN,10.17181/t4eej-q2647,,,true,None,None,None,"{""client"": {""data"": {""id"": ""cern.cds"", ""type"":...",parent,2014-04-30,2014.0,2014,"[{""date"": ""2014-04-30"", ""dateType"": ""Issued""}]",parent,None,8595515513845681595,andreas_daniel_fink,improving the selectivity of the isolde resona...,fink|d,None,parent,None,8595515513845681595,10.17181/t4eej-q2647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7469989,datacite::10.48550/arxiv.2505.11244,arXiv,datacite,10.48550/arxiv.2505.11244,https://doi.org/10.48550/arxiv.2505.11244,https://arxiv.org/abs/2505.11244,Text,Article,A Review of Tools and Techniques for Optimizat...,"Sharma, Aasish Kumar; Kunkel, Julian",None,None,"[{""relatedIdentifier"": ""10.1177/tobeassigned"",...",1,NaN,10.1177/tobeassigned,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2025-05-16,2025.0,2025,"[{""date"": ""2025-05-16T13:38:23Z"", ""dateInforma...",parent,None,None,aasish_kumar_sharma;julian_kunkel,a review of tools and techniques for optimizat...,kunkel|j;sharma|a,None,parent,None,None,10.1177/tobeassigned
7469990,datacite::10.48550/arxiv.2505.11272,arXiv,datacite,10.48550/arxiv.2505.11272,https://doi.org/10.48550/arxiv.2505.11272,https://arxiv.org/abs/2505.11272,Text,Article,Resistivity of non-Galilean invariant two dime...,"Kovalev, V. M.; Entin, M. V.; Kvon, Z. D.; Lev...",None,None,"[{""relatedIdentifier"": ""10.1103/physrevlett.13...",1,NaN,10.1103/physrevlett.134.196303,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2025-05-16,2025.0,2025,"[{""date"": ""2025-05-16T14:05:30Z"", ""dateInforma...",parent,None,None,None,None,None,None,parent,None,None,10.1103/physrevlett.134.196303
7469991,datacite::10.48550/arxiv.2505.11372,arXiv,datacite,10.48550/arxiv.2505.11372,https://doi.org/10.48550/arxiv.2505.11372,https://arxiv.org/abs/2505.11372,Text,Article,Increasing delay as a strategy to prove stability,"AlSharawi, Ziyad; Cánovas, Jose S.",None,None,"[{""relatedIdentifier"": ""10.1080/10236198.2025....",1,NaN,10.1080/10236198.2025.2508263,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2025-05-16,2025.0,2025,"[{""date"": ""2025-05-16T15:35:13Z"", ""dateInforma...",parent,None,None,alsharawi_ziyad;canovas_jose_s,increasing delay as a strategy to prove stability,alsharawi|z;canovas|j,None,parent,None,None,10.1080/10236198.2025.2508263
7469992,datacite::10.48550/arxiv.2505.11408,arXiv,datacite,10.48550/arxiv.2505.11408,https://doi.org/10.48550/arxiv.2505.11408,https://arxiv.org/abs/2505.11408,Text,Article,Acceleration Potential and Density Profile of ...,"Istomin, A. Yu.; Kniazev, F. A.; Beskin, V. S.",None,None,"[{""relatedIdentifier"": ""10.1134/s1063772925701...",1,NaN,10.1134/s1063772925701264,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2025-05-16,2025.0,2025,"[{""date"": ""2025-05-16T16:17:03Z"", ""dateInforma...",parent,None,None,a_f_kniazev;a_istomin_yu;beskin_s_v,acceleration potential and density profile of ...,beskin|v;istomin|a;kniazev|f,None,parent,None,None,10.1134/s1063772925701264
7469994,datacite::10.48550/arxiv.2505.11498,arXiv,datacite,10.48550/arxiv.2505.11498,https://doi.org/10.48550/arxiv.2505.11498,https://arxiv.org/abs/2505.11498,Text,Article,Evolution of granular salty ice analogs for Eu...,"Ottersberg, Rafael; Pommerol, Antoine; Stöckli...",None,None,"[{""relatedIdentifier"": ""10.1016/j.icarus.2025....",1,NaN,10.1016/j.icarus.2025.116590,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2025-05-16,2025.0,2025,"[{""date"": ""2025-05-16T17:59:54Z"", ""dateInforma...",parent,None,None,None,None,None,None,parent,None,None,10.1016/j.icarus.2025.116590

In [16]:
nothas_version_dois = result[result['has_version_dois'].isna()]
nothas_version_dois

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
280771,datacite::10.48796/20220501-000,CrossAsia-Repository,datacite,10.48796/20220501-000,https://doi.org/10.48796/20220501-000,https://repository.crossasia.org/receive/cross...,Text,article,Locating Dashi 大食 in Song Dynasty Sources,"Kurz, Johannes",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2022-05-10,2022.0,2022,"[{""date"": ""2022"", ""dateType"": ""Issued""}]",parent,None,None,johannes_kurz,locating dashi 大食 in song dynasty sources,kurz|j,None,parent,None,None,None
280772,datacite::10.48796/20220508-000,CrossAsia-Repository,datacite,10.48796/20220508-000,https://doi.org/10.48796/20220508-000,https://repository.crossasia.org/receive/cross...,Text,collection,Yanagita Kunio and Japanese Folklore Studies i...,:None,None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,none,yanagita kunio and japanese folklore studies i...,,None,parent,None,None,None
280773,datacite::10.48796/20220508-001,CrossAsia-Repository,datacite,10.48796/20220508-001,https://doi.org/10.48796/20220508-001,https://repository.crossasia.org/receive/cross...,Text,chapter,Introduction: Yanagita Kunio in Global Perspec...,"Morse, Ronald",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,None,introduction yanagita kunio in global perspective,morse|r,None,parent,None,None,None
280774,datacite::10.48796/20220508-002,CrossAsia-Repository,datacite,10.48796/20220508-002,https://doi.org/10.48796/20220508-002,https://repository.crossasia.org/receive/cross...,Text,chapter,Brief Outline of Yanagita Kunio’s Life,"Morse, Ronald; Göhlert, Christian",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,christian_gohlert;morse_ronald,brief outline of yanagita kunio s life,gohlert|c;morse|r,None,parent,None,None,None
280775,datacite::10.48796/20220508-003,CrossAsia-Repository,datacite,10.48796/20220508-003,https://doi.org/10.48796/20220508-003,https://repository.crossasia.org/receive/cross...,Text,chapter,Yōkai and Yanagita Kunio: A View from the 21st...,"Foster, Michael",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,None,yokai and yanagita kunio a view from the 21st ...,foster|m,None,parent,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4541677,datacite::10.5281/zenodo.400639,Zenodo,datacite,10.5281/zenodo.400639,https://doi.org/10.5281/zenodo.400639,https://zenodo.org/record/400639,Text,Preprint,Mathematical Proof Of A Feasible Warp Drive An...,Baruah Gautam Narayan,None,None,"[{""relatedIdentifier"": ""doi 10.5281/zenodo.345...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2017-03-18,2017.0,2017,"[{""date"": ""2017-03-18"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.400637,2244344397505640975,baruah_gautam_narayan,mathematical proof of a feasible warp drive an...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.400637,2244344397505640975,None
4541678,datacite::10.5281/zenodo.400652,Zenodo,datacite,10.5281/zenodo.400652,https://doi.org/10.5281/zenodo.400652,https://zenodo.org/record/400652,Text,Preprint,Mathematical Proof Of A Feasible Warp Drive An...,Baruah Gautam Narayan,None,None,"[{""relatedIdentifier"": ""doi 10.5281/zenodo.345...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2017-03-18,2017.0,2017,"[{""date"": ""2017-03-18"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.221108,6099717425929547452,baruah_gautam_narayan,mathematical proof of a feasible warp drive an...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.221108,6099717425929547452,None
4541694,datacite::10.5281/zenodo.570042,Zenodo,datacite,10.5281/zenodo.570042,https://doi.org/10.5281/zenodo.570042,https://zenodo.org/record/570042,Text,Preprint,La Bilancia E La Spada: Scienza Di Stato E Val...,Pievatolo Maria Chiara,None,None,"[{""relatedIdentifier"": ""urn:nbn:it:unipi-20250...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2017-04-30,2017.0,2017,"[{""date"": ""2017-04-30"", ""dateType"": ""Issued""}]",parent,None,None,chiara_maria_pievatolo,la bilancia e la spada scienza di stato e valu...,chiara|p,None,parent,None,None,None
4541701,datacite::10.5281/zenodo.573579,Zenodo,datacite,10.5281/zenodo.573579,https://doi.org/10.5281/zenodo.573579,https://zenodo.org/record/573579,Text,Preprint,Connected Health In Multiple Sclerosis: A Mobi...,"Giunti, Guido; Caulfield, Brian; Guisado-Ferna...",Salumedia Tecnologias; University College Dublin,None,"[{""relatedIdentifier"": ""arXiv:1705.03227"", ""re...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (arXiv),2017-05-10,2017.0,2017,"[{""date"": ""2017-05-10"", ""dateType"": ""Issued""}]",parent,datacite::10.48550/arxiv.1705.03227,relaxed::A1_tokenbag_exact::63245,brian_caulfield;estafania_fernandez_guisado;gi...,connected health in multiple sclerosis a mobil...,None,None,parent - duplicate (arXiv),datacite::10.48550/arxiv.1705.03227,relaxed::A1_tokenbag_exact::63245,None
4541702,datacite::10.5281/zenodo.573639,Zenodo,datacite,10.5281/zenodo.573639,https://doi.org/10.5281/zenodo.573639,https://zenodo.org/record/573639,Text,Preprint,Detecting Gamification In Breast Cancer Apps: ...,"Giunti, Guido; Giunta, Diego H.; Hors-Fraile, ...",Salumedia Tecnologias; Hospital Italiano de Bu...,None,"[{""relatedIdentifier"": ""arXiv:1705.03228"", ""re...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (arXiv),2017-05-10,2017.0,2017,"[{""date"": ""2017-05-10"", ""dateType"": ""Issued""}]",parent,datacite::10.48550/arxiv.1705.03228,10993758934354772358,diana_karoseviciute;diego_giunta_h;fraile_hors...,detecting gamification in breast cancer apps a...,None,None,parent - duplicate (arXiv),datacite::10.48550/arxiv.1705.03228,10993758934354772358,None

In [17]:
nothas_version_dois[nothas_version_dois['is_version_of'].notna()]

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
4427835,datacite::10.5281/zenodo.15490327,Zenodo,datacite,10.5281/zenodo.15490327,https://doi.org/10.5281/zenodo.15490327,https://zenodo.org/doi/10.5281/zenodo.15490327,Preprint,,The Riemann Hypothesis and Its Proof: Abstract...,"Artykbayev, Marat Dzhanybekovich",Independent Researcher,None,"[{""relatedIdentifier"": ""10.5281/зенодо.1548870...",v1 (English),10.5281/зенодо.15488700,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (SSRN),2025-03-31,2025.0,2025,"[{""date"": ""2025-03-31"", ""dateType"": ""Issued""},...",parent,crossref::10.2139/ssrn.5326951,1744535453716478300,artykbayev_dzhanybekovich_marat,the riemann hypothesis and its proof abstracti...,None,None,parent - duplicate (SSRN),crossref::10.2139/ssrn.5326951,1744535453716478300,None
4434777,datacite::10.5281/zenodo.15676365,Zenodo,datacite,10.5281/zenodo.15676365,https://doi.org/10.5281/zenodo.15676365,https://zenodo.org/doi/10.5281/zenodo.15676365,Preprint,,Energy-Density Gravity: A Scalar-Potential Toy...,"Gavant, D. S.",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1393599...",None,10.5281/zenodo.13935996,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-06-16,2025.0,2025,"[{""date"": ""2025-06-16"", ""dateType"": ""Issued""},...",parent,None,None,d_gavant_s,energy density gravity a scalar potential toy ...,gavant|d,None,parent,None,None,None
4480603,datacite::10.5281/zenodo.17328746,Zenodo,datacite,10.5281/zenodo.17328746,https://doi.org/10.5281/zenodo.17328746,https://zenodo.org/doi/10.5281/zenodo.17328746,Preprint,,FEDI 2.1: Fion-Enhanced Distributed Intelligen...,"Chomiuk, Paweł Krzysztof",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1722048...",None,10.5281/zenodo.17220485,,,10.5281/zenodo.17428408,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-10-11,2025.0,2025,"[{""date"": ""2025-10-11"", ""dateType"": ""Issued""}]",parent,None,None,chomiuk_krzysztof_paweł,fedi 2 1 fion enhanced distributed intelligenc...,chomiuk|p,None,parent,None,None,None
4483851,datacite::10.5281/zenodo.17381002,Zenodo,datacite,10.5281/zenodo.17381002,https://doi.org/10.5281/zenodo.17381002,https://zenodo.org/doi/10.5281/zenodo.17381002,Preprint,,Hidden Mixture-of-Experts: Emergent Bipolar Ro...,"Choi, Seungho",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1735534...",v1.0.0,10.5281/zenodo.17355345,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-10-17,2025.0,2025,"[{""date"": ""2025-10-17"", ""dateType"": ""Issued""}]",parent,None,None,choi_seungho,hidden mixture of experts emergent bipolar rou...,choi|s,None,parent,None,None,None
4488782,datacite::10.5281/zenodo.17451331,Zenodo,datacite,10.5281/zenodo.17451331,https://doi.org/10.5281/zenodo.17451331,https://zenodo.org/doi/10.5281/zenodo.17451331,Preprint,,Deterministic Three-Frequency Prefilter (D3FP),"Cárdenas Campos, Héctor",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1527762...",1.0,10.5281/zenodo.15277629,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-10-26,2025.0,2025,"[{""date"": ""2025-10-26"", ""dateType"": ""Issued""}]",parent,None,None,campos_cardenas_hector,deterministic three frequency prefilter d3fp,cardenas|h,None,parent,None,None,None
4488788,datacite::10.5281/zenodo.17451376,Zenodo,datacite,10.5281/zenodo.17451376,https://doi.org/10.5281/zenodo.17451376,https://zenodo.org/doi/10.5281/zenodo.17451376,Preprint,,Deterministic Three-Frequency PRIMES Prefilter,"Cárdenas Campos, Héctor",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1527762...",1.0,10.5281/zenodo.15277629,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-10-26,2025.0,2025,"[{""date"": ""2025-10-26"", ""dateType"": ""Issued""}]",parent,None,None,campos_cardenas_hector,deterministic three frequency primes prefilter,cardenas|h,None,parent,None,None,None
4488796,datacite::10.5281/zenodo.17451420,Zenodo,datacite,10.5281/zenodo.17451420,https://doi.org/10.5281/zenodo.17451420,https://zenodo.org/doi/10.5281/zenodo.17451420,Preprint,,Deterministic Three-Frequency Prime Prefilter,"Cárdenas Campos, Héctor",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1527762...",1.0,10.5281/zenodo.15277629,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-10-26,2025.0,2025,"[{""date"": ""2025-10-26"", ""dateType"": ""Issued""}]",parent,None,None,campos_cardenas_hector,deterministic three frequency prime prefilter,cardenas|h,None,parent,None,None,None
4489073,datacite::10.5281/zenodo.17454344,Zenodo,datacite,10.5281/zenodo.17454344,https://doi.org/10.5281/zenodo.17454344,https://zenodo.org/doi/10.5281/zenodo.17454344,Preprint,,"The Fionic Theory of Consciousness, Cognition,...","Chomiuk, Paweł Krzysztof",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1745372...",None,10.5281/zenodo.17453722,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2025-10-27,2025.0,2025,"[{""date"": ""2025-10-27"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.17453721,324985474322091992,chomiuk_krzysztof_paweł,the fionic theory of consciousness cognition a...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.17453721,324985474322091992,None
4493191,datacite::10.5281/zenodo.17514467,Zenodo,datacite,10.5281/zenodo.17514467,https://doi.org/10.5281/zenodo.17514467,https://zenodo.org/doi/10.5281/zenodo.17514467,Preprint,,Influence of Thermal and Populational Variable...,"Gracidas Reyes, Eduardo; Diaz-Arango, Gerardo",Universidad de las Américas Puebla; Universida...,None,"[{""relatedIdentifier"": ""10.1371/journal.pone.0...",0.1,10.5281/zenodo.16888053,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-09-01,2025.0,2025,"[{""date"": ""2025-09-01"", ""dateType"": ""Issued""},...",parent,None,relaxed::A1_tokenbag_exact::45506,arango_diaz_gerardo;eduardo_gracidas_reyes,influence of thermal and populational variable...,None,None,parent,None,relaxed::A1_tokenbag_exact::45506,None
4534271,datacite::10.5281/zenodo.18040655,Zenodo,datacite,10.5281/zenodo.18040655,https://doi.org/10.5281/zenodo.18040655,https://zenodo.org/doi/10.5281/zenodo.18040655,Preprint,,Memory of the Universe: Rheological Signatures...,"Zeleny, Tomáš",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1800462...",None,10.5281/zenodo.18004625,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-12-23,2025.0,2025,"[{""date"": ""2025-12-24"", ""dateType"": ""Issued""},...",parent,None,None,tomas_zeleny,memory of the universe rheological signatures ...,zeleny|t,None,parent,None,None,None

In [18]:
result['backend'].value_counts()

backend
datacite    1480179
Name: count, dtype: int64

In [19]:
has_version_dois_isna = result[result['has_version_dois'].isna()]
has_version_dois_isna

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
280771,datacite::10.48796/20220501-000,CrossAsia-Repository,datacite,10.48796/20220501-000,https://doi.org/10.48796/20220501-000,https://repository.crossasia.org/receive/cross...,Text,article,Locating Dashi 大食 in Song Dynasty Sources,"Kurz, Johannes",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2022-05-10,2022.0,2022,"[{""date"": ""2022"", ""dateType"": ""Issued""}]",parent,None,None,johannes_kurz,locating dashi 大食 in song dynasty sources,kurz|j,None,parent,None,None,None
280772,datacite::10.48796/20220508-000,CrossAsia-Repository,datacite,10.48796/20220508-000,https://doi.org/10.48796/20220508-000,https://repository.crossasia.org/receive/cross...,Text,collection,Yanagita Kunio and Japanese Folklore Studies i...,:None,None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,none,yanagita kunio and japanese folklore studies i...,,None,parent,None,None,None
280773,datacite::10.48796/20220508-001,CrossAsia-Repository,datacite,10.48796/20220508-001,https://doi.org/10.48796/20220508-001,https://repository.crossasia.org/receive/cross...,Text,chapter,Introduction: Yanagita Kunio in Global Perspec...,"Morse, Ronald",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,None,introduction yanagita kunio in global perspective,morse|r,None,parent,None,None,None
280774,datacite::10.48796/20220508-002,CrossAsia-Repository,datacite,10.48796/20220508-002,https://doi.org/10.48796/20220508-002,https://repository.crossasia.org/receive/cross...,Text,chapter,Brief Outline of Yanagita Kunio’s Life,"Morse, Ronald; Göhlert, Christian",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,christian_gohlert;morse_ronald,brief outline of yanagita kunio s life,gohlert|c;morse|r,None,parent,None,None,None
280775,datacite::10.48796/20220508-003,CrossAsia-Repository,datacite,10.48796/20220508-003,https://doi.org/10.48796/20220508-003,https://repository.crossasia.org/receive/cross...,Text,chapter,Yōkai and Yanagita Kunio: A View from the 21st...,"Foster, Michael",None,None,"[{""relatedIdentifier"": ""https://repository.cro...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...",parent,2021-01-01,2021.0,2021,"[{""date"": ""2021"", ""dateType"": ""Issued""}]",parent,None,None,None,yokai and yanagita kunio a view from the 21st ...,foster|m,None,parent,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4541677,datacite::10.5281/zenodo.400639,Zenodo,datacite,10.5281/zenodo.400639,https://doi.org/10.5281/zenodo.400639,https://zenodo.org/record/400639,Text,Preprint,Mathematical Proof Of A Feasible Warp Drive An...,Baruah Gautam Narayan,None,None,"[{""relatedIdentifier"": ""doi 10.5281/zenodo.345...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2017-03-18,2017.0,2017,"[{""date"": ""2017-03-18"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.400637,2244344397505640975,baruah_gautam_narayan,mathematical proof of a feasible warp drive an...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.400637,2244344397505640975,None
4541678,datacite::10.5281/zenodo.400652,Zenodo,datacite,10.5281/zenodo.400652,https://doi.org/10.5281/zenodo.400652,https://zenodo.org/record/400652,Text,Preprint,Mathematical Proof Of A Feasible Warp Drive An...,Baruah Gautam Narayan,None,None,"[{""relatedIdentifier"": ""doi 10.5281/zenodo.345...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (Zenodo),2017-03-18,2017.0,2017,"[{""date"": ""2017-03-18"", ""dateType"": ""Issued""}]",parent,datacite::10.5281/zenodo.221108,6099717425929547452,baruah_gautam_narayan,mathematical proof of a feasible warp drive an...,None,None,parent - duplicate (Zenodo),datacite::10.5281/zenodo.221108,6099717425929547452,None
4541694,datacite::10.5281/zenodo.570042,Zenodo,datacite,10.5281/zenodo.570042,https://doi.org/10.5281/zenodo.570042,https://zenodo.org/record/570042,Text,Preprint,La Bilancia E La Spada: Scienza Di Stato E Val...,Pievatolo Maria Chiara,None,None,"[{""relatedIdentifier"": ""urn:nbn:it:unipi-20250...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2017-04-30,2017.0,2017,"[{""date"": ""2017-04-30"", ""dateType"": ""Issued""}]",parent,None,None,chiara_maria_pievatolo,la bilancia e la spada scienza di stato e valu...,chiara|p,None,parent,None,None,None
4541701,datacite::10.5281/zenodo.573579,Zenodo,datacite,10.5281/zenodo.573579,https://doi.org/10.5281/zenodo.573579,https://zenodo.org/record/573579,Text,Preprint,Connected Health In Multiple Sclerosis: A Mobi...,"Giunti, Guido; Caulfield, Brian; Guisado-Ferna...",Salumedia Tecnologias; University College Dublin,None,"[{""relatedIdentifier"": ""arXiv:1705.03227"", ""re...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (arXiv),2017-05-10,2017.0,2017,"[{""date"": ""2017-05-10"", ""dateType"": ""Issued""}]",parent,datacite::10.48550/arxiv.1705.03227,relaxed::A1_tokenbag_exact::63245,brian_caulfield;estafania_fernandez_guisado;gi...,connected health in multiple sclerosis a mobil...,None,None,parent - duplicate (arXiv),datacite::10.48550/arxiv.1705.03227,relaxed::A1_tokenbag_exact::63245,None
4541702,datacite::10.5281/zenodo.573639,Zenodo,datacite,10.5281/zenodo.573639,https://doi.org/10.5281/zenodo.573639,https://zenodo.org/record/573639,Text,Preprint,Detecting Gamification In Breast Cancer Apps: ...,"Giunti, Guido; Giunta, Diego H.; Hors-Fraile, ...",Salumedia Tecnologias; Hospital Italiano de Bu...,None,"[{""relatedIdentifier"": ""arXiv:1705.03228"", ""re...",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent - duplicate (arXiv),2017-05-10,2017.0,2017,"[{""date"": ""2017-05-10"", ""dateType"": ""Issued""}]",parent,datacite::10.48550/arxiv.1705.03228,10993758934354772358,diana_karoseviciute;diego_giunta_h;fraile_hors...,detecting gamification in breast cancer apps a...,None,None,parent - duplicate (arXiv),datacite::10.48550/arxiv.1705.03228,10993758934354772358,None

In [20]:
has_version_dois_isna['server_name'].value_counts()

server_name
Open Science Framework    2335
CrossAsia-Repository       479
Zenodo                     269
PsyArXiv                   219
EarthArXiv                 102
MarXiv                      80
engrXiv                     43
Arabixiv                    25
PaleorXiv                   24
Thesis Commons               8
MindRxiv                     8
AgriRxiv                     1
Name: count, dtype: int64

In [21]:
get_all_relation_types(has_version_dois_isna)

Processed 3,593 / 3,593 rows
Done.

Empty DataFrame
Columns: [relationType, count, percentage]
Index: []

In [22]:
pattern = '"IsPreviousVersionOf"'

mask = has_version_dois_isna['relations_json'].str.contains(pattern, regex=False, na=False)
result3 = has_version_dois_isna[mask]
result3

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
1789219,datacite::10.17605/osf.io/8crzu,Open Science Framework,datacite,10.17605/osf.io/8crzu,https://doi.org/10.17605/osf.io/8crzu,https://doi.org/10.31234/osf.io/8crzu,Text,Preprint,Predicting Ideological Prejudice,"Brandt, Mark",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (PsyArXiv),2016-11-01,2016.0,2016,"[{""date"": ""2016-12-30T12:49:27.409000+00:00"", ...",parent,crossref::10.31234/osf.io/8crzu,14199177091707795996,brandt_mark,predicting ideological prejudice,brandt|m,None,parent - duplicate (PsyArXiv),crossref::10.31234/osf.io/8crzu,14199177091707795996,None
1789222,datacite::10.17605/osf.io/utnnu,Open Science Framework,datacite,10.17605/osf.io/utnnu,https://doi.org/10.17605/osf.io/utnnu,https://doi.org/10.31224/osf.io/utnnu,Text,Preprint,Low-cost methodology for skin strain measureme...,"Lin, Bevin; Moerman, Kevin; McMahan, Connor; P...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2016-11-09,2016.0,2016,"[{""date"": ""2017-04-28T19:07:01.047270+00:00"", ...",parent,None,relaxed::A1_tokenbag_exact::18557,bevin_lin;connor_mcmahan;herr_hugh;kenneth_pas...,low cost methodology for skin strain measureme...,None,None,parent,None,relaxed::A1_tokenbag_exact::18557,None
1789224,datacite::10.17605/osf.io/aypws,Open Science Framework,datacite,10.17605/osf.io/aypws,https://doi.org/10.17605/osf.io/aypws,https://doi.org/10.31234/osf.io/aypws,Text,Preprint,The effects of winning and losing on perceived...,"Rubin, Mark",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (PsyArXiv),2017-05-31,2017.0,2017,"[{""date"": ""2017-05-31T16:09:33.823815+00:00"", ...",parent,crossref::10.31234/osf.io/aypws,7729529042595144458,mark_rubin,the effects of winning and losing on perceived...,None,None,parent - duplicate (PsyArXiv),crossref::10.31234/osf.io/aypws,7729529042595144458,None
1789230,datacite::10.17605/osf.io/tjk9y,Open Science Framework,datacite,10.17605/osf.io/tjk9y,https://doi.org/10.17605/osf.io/tjk9y,https://doi.org/10.31234/osf.io/tjk9y,Text,Preprint,The relationship between the need for closure ...,"Rubin, Mark",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (PsyArXiv),2017-05-31,2017.0,2017,"[{""date"": ""2017-05-31T16:09:57.539164+00:00"", ...",parent,crossref::10.31234/osf.io/tjk9y,6355195737513386506,mark_rubin,the relationship between the need for closure ...,None,None,parent - duplicate (PsyArXiv),crossref::10.31234/osf.io/tjk9y,6355195737513386506,None
1789231,datacite::10.17605/osf.io/tvbgf,Open Science Framework,datacite,10.17605/osf.io/tvbgf,https://doi.org/10.17605/osf.io/tvbgf,https://doi.org/10.31234/osf.io/tvbgf,Text,Preprint,A cross-sectional investigation of parenting s...,"Rubin, Mark",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (PsyArXiv),2017-05-31,2017.0,2017,"[{""date"": ""2017-05-31T16:09:54.559051+00:00"", ...",parent,crossref::10.31234/osf.io/tvbgf,7549943593415132084,mark_rubin,a cross sectional investigation of parenting s...,None,None,parent - duplicate (PsyArXiv),crossref::10.31234/osf.io/tvbgf,7549943593415132084,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1797483,datacite::10.17605/osf.io/r5mga,PsyArXiv,datacite,10.17605/osf.io/r5mga,https://doi.org/10.17605/osf.io/r5mga,https://psyarxiv.com/r5mga/,Text,Preprint,Empirically investigating the concept of lying,"Wiegmann, Alex; Rutschmann, Ronja; Willemsen, ...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-29,2018.0,2018,"[{""date"": ""2018-06-29T12:55:11.076720+00:00"", ...",parent,None,8529968580530660375,alex_wiegmann;pascale_willemsen;ronja_rutschmann,empirically investigating the concept of lying,None,None,parent,None,8529968580530660375,None
1797497,datacite::10.17605/osf.io/29qp6,Open Science Framework,datacite,10.17605/osf.io/29qp6,https://doi.org/10.17605/osf.io/29qp6,https://osf.io/29qp6/,Text,Preprint,EXAMINING THE RELEVANCE OF JOB SATISFACTION ON...,"Syahrir, Hj.",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (Open Science Framework),2018-06-30,2018.0,2018,"[{""date"": ""2018-06-30T03:28:26.057983+00:00"", ...",parent,crossref::10.31219/osf.io/29qp6,11848005325480586822,hj_syahrir,examining the relevance of job satisfaction on...,syahrir|h,None,parent - duplicate (Open Science Framework),crossref::10.31219/osf.io/29qp6,11848005325480586822,None
1797498,datacite::10.17605/osf.io/djv8y,Open Science Framework,datacite,10.17605/osf.io/djv8y,https://doi.org/10.17605/osf.io/djv8y,https://osf.io/djv8y/,Text,Preprint,STILL MOTIVATED TO IMPROVE PERFORMANCE? A STUD...,"Abdurrahman, Ahmad",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (Open Science Framework),2018-06-30,2018.0,2018,"[{""date"": ""2018-06-30T04:28:24.060534+00:00"", ...",parent,crossref::10.31219/osf.io/djv8y,8818916254800012530,abdurrahman_ahmad,still motivated to improve performance a study...,abdurrahman|a,None,parent - duplicate (Open Science Framework),crossref::10.31219/osf.io/djv8y,8818916254800012530,None
1797499,datacite::10.17605/osf.io/349ja,Open Science Framework,datacite,10.17605/osf.io/349ja,https://doi.org/10.17605/osf.io/349ja,https://osf.io/349ja/,Text,Preprint,HRM PRACTICES AND ITS IMPACT ON EMPLOYEE PERFO...,", Ridwan",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (Open Science Framework),2018-06-30,2018.0,2018,"[{""date"": ""2018-06-30T04:37:08.549093+00:00"", ...",parent,crossref::10.31219/osf.io/349ja,7111439308487034371,ridwan,hrm practices and its impact on employee perfo...,None,None,parent - duplicate (Open Science Framework),crossref::10.31219/osf.io/349ja,7111439308487034371,None
4480767,datacite::10.5281/zenodo.17330008,Zenodo,datacite,10.5281/zenodo.17330008,https://doi.org/10.5281/zenodo.17330008,https://zenodo.org/doi/10.5281/zenodo.17330008,Preprint,,Triadic Fixpoint v3 — Algebraic and Physical F...,"Omezzolli, Roberto",Indipendent,None,"[{""relatedIdentifier"": ""https://zenodo.org/rec...",v3 – Algebraic and Physical Foundations,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-10-12,2025.0,2025,"[{""date"": ""2025-10-12"", ""dateType"": ""Issued""},...",parent,None,None,omezzolli_roberto,triadic fixpoint v3 algebraic and physical fou...,omezzolli|r,None,parent,None,None,None

In [23]:
result3.tail(60)

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
1797198,datacite::10.17605/osf.io/7rmu6,PsyArXiv,datacite,10.17605/osf.io/7rmu6,https://doi.org/10.17605/osf.io/7rmu6,https://psyarxiv.com/7rmu6/,Text,Preprint,An Investigation of the Divergences and Conver...,"jami, parvaneh; Mansouri, Behzad; Thoma, Steph...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-10,2018.0,2018,"[{""date"": ""2018-06-10T21:45:53.869738+00:00"", ...",parent,None,relaxed::A1_tokenbag_exact::19586,behzad_mansouri;han_hyemin;jami_parvaneh;steph...,an investigation of the divergences and conver...,None,None,parent,None,relaxed::A1_tokenbag_exact::19586,None
1797209,datacite::10.17605/osf.io/42rza,PsyArXiv,datacite,10.17605/osf.io/42rza,https://doi.org/10.17605/osf.io/42rza,https://psyarxiv.com/42rza/,Text,Preprint,With great data comes great (theoretical) oppo...,"Frank, Michael",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-11,2018.0,2018,"[{""date"": ""2018-06-11T21:09:22.623224+00:00"", ...",parent,None,8149411324577153602,frank_michael,with great data comes great theoretical opport...,frank|m,None,parent,None,8149411324577153602,None
1797214,datacite::10.17605/osf.io/3fu2a,PsyArXiv,datacite,10.17605/osf.io/3fu2a,https://doi.org/10.17605/osf.io/3fu2a,https://psyarxiv.com/3fu2a/,Text,Preprint,Essentialist Beliefs and Social Distance towar...,"Agadullina, Elena; Lovakov, Andrey; Malysheva,...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-12,2018.0,2018,"[{""date"": ""2018-06-12T12:16:05.424100+00:00"", ...",parent,None,10835013044646619781,agadullina_elena;andrey_lovakov;malysheva_natalia,essentialist beliefs and social distance towar...,None,None,parent,None,10835013044646619781,None
1797227,datacite::10.17605/osf.io/jgp3m,EarthArXiv,datacite,10.17605/osf.io/jgp3m,https://doi.org/10.17605/osf.io/jgp3m,https://eartharxiv.org/jgp3m/,Text,Preprint,Is the Earth Lazy? A review of work minimizati...,"Cooke, Michele; Madden, Elizabeth",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (EarthArXiv),2018-06-13,2018.0,2018,"[{""date"": ""2018-06-13T02:58:30.933280+00:00"", ...",parent,crossref::10.31223/osf.io/jgp3m,7317120953095148458,cooke_michele;elizabeth_madden,is the earth lazy a review of work minimizatio...,None,None,parent - duplicate (EarthArXiv),crossref::10.31223/osf.io/jgp3m,7317120953095148458,None
1797233,datacite::10.17605/osf.io/uvfsr,PsyArXiv,datacite,10.17605/osf.io/uvfsr,https://doi.org/10.17605/osf.io/uvfsr,https://psyarxiv.com/uvfsr/,Text,Preprint,Time in causal structure learning,"Bramley, Neil; Gerstenberg, Tobias; Mayrhofer,...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-13,2018.0,2018,"[{""date"": ""2018-06-13T18:36:01.252737+00:00"", ...",parent,None,relaxed::A1_tokenbag_exact::19595,bramley_neil;david_lagnado;gerstenberg_tobias;...,time in causal structure learning,None,None,parent,None,relaxed::A1_tokenbag_exact::19595,None
1797241,datacite::10.17605/osf.io/8b73v,engrXiv,datacite,10.17605/osf.io/8b73v,https://doi.org/10.17605/osf.io/8b73v,https://engrxiv.org/8b73v/,Text,Preprint,"""Thus, I had to go with what I had"": A Multipl...","McComb, Christopher; Menold, Jessica; Berdanie...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-14,2018.0,2018,"[{""date"": ""2018-06-14T13:19:28.757224+00:00"", ...",parent,None,12143966257048467297,berdanier_catherine;christopher_mccomb;emma_ho...,thus i had to go with what i had a multiple me...,None,None,parent,None,12143966257048467297,None
1797242,datacite::10.17605/osf.io/qw2gh,PsyArXiv,datacite,10.17605/osf.io/qw2gh,https://doi.org/10.17605/osf.io/qw2gh,https://psyarxiv.com/qw2gh/,Text,Preprint,"Treatment, Medication, and Behavioral Beliefs ...","Hagger, Martin",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-14,2018.0,2018,"[{""date"": ""2018-06-14T14:11:53.296286+00:00"", ...",parent,None,7491714752272196220,hagger_martin,treatment medication and behavioral beliefs as...,hagger|m,None,parent,None,7491714752272196220,None
1797243,datacite::10.17605/osf.io/d8rfy,PsyArXiv,datacite,10.17605/osf.io/d8rfy,https://doi.org/10.17605/osf.io/d8rfy,https://psyarxiv.com/d8rfy/,Text,Preprint,Winners and losers - communicating the potenti...,"Brick, Cameron; Skylark, William; Freeman, Ale...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-14,2018.0,2018,"[{""date"": ""2018-06-14T14:30:41.550856+00:00"", ...",parent,None,relaxed::A1_tokenbag_exact::19598,alexandra_freeman;brick_cameron;marteau_theres...,winners and losers communicating the potential...,None,None,parent,None,relaxed::A1_tokenbag_exact::19598,None
1797247,datacite::10.17605/osf.io/qgaj5,EarthArXiv,datacite,10.17605/osf.io/qgaj5,https://doi.org/10.17605/osf.io/qgaj5,https://eartharxiv.org/qgaj5/,Text,Preprint,A fossiliferous spherule-rich bed at the Creta...,"Witts, James; Landman, Neil; Garb, Matthew; Bo...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (EarthArXiv),2018-06-14,2018.0,2018,"[{""date"": ""2018-06-16T04:23:22.411064+00:00"", ...",parent,crossref::10.31223/osf.io/qgaj5,4054228053267077598,boas_caitlin;cochran_j;edwards_lucy;ekaterina_...,a fossiliferous spherule rich bed at the creta...,None,None,parent - duplicate (EarthArXiv),crossref::10.31223/osf.io/qgaj5,4054228053267077598,None
1797248,datacite::10.17605/osf.io/b9m84,MarXiv,datacite,10.17605/osf.io/b9m84,https://doi.org/10.17605/osf.io/b9m84,https://marxiv.org/b9m84/,Text,Preprint,The Philippines context for marine tenure and ...,"Pomeroy, Robert; Courtney, Catherine",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-14,2018.0,2018,"[{""date"": ""2018-06-14T22:08:41.518360+00:00"", ...",parent,crossref::10.31230/osf.io/b9m84,relaxed::A1_tokenbag_exact::16051,catherine_courtney;pomeroy_robert,the philippines context for marine tenure and ...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/b9m84,relaxed::A1_tokenbag_exact::16051,None
1797264,datacite::10.17605/osf.io/52tdf,MindRxiv,datacite,10.17605/osf.io/52tdf,https://doi.org/10.17605/osf.io/52tdf,https://mindrxiv.org/52tdf/,Text,Preprint,Insight meditation and telomere biology: The e...,"Conklin, Quinn; King, Brandon; Zanesco, Anthon...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MindRxiv),2018-06-16,2018.0,2018,"[{""date"": ""2018-06-16T17:06:28.193169+00:00"", ...",parent,crossref::10.31231/osf.io/52tdf,relaxed::A1_tokenbag_exact::16114,alvarez_lopez_maria;anahita_hamidi;anthony_zan...,insight meditation and telomere biology the ef...,None,None,parent - duplicate (MindRxiv),crossref::10.31231/osf.io/52tdf,relaxed::A1_tokenbag_exact::16114,None
1797290,datacite::10.17605/osf.io/ewb68,MarXiv,datacite,10.17605/osf.io/ewb68,https://doi.org/10.17605/osf.io/ewb68,https://marxiv.org/ewb68/,Text,Preprint,Clarifying some assumptions of coastal managem...,"Bombana, Briana; Ariza, Eduard",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-19,2018.0,2018,"[{""date"": ""2018-06-19T17:47:36.632484+00:00"", ...",parent,crossref::10.31230/osf.io/ewb68,6643220939953781943,ariza_eduard;bombana_briana,clarifying some assumptions of coastal managem...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/ewb68,6643220939953781943,None
1797294,datacite::10.17605/osf.io/bzywv,MarXiv,datacite,10.17605/osf.io/bzywv,https://doi.org/10.17605/osf.io/bzywv,https://marxiv.org/bzywv/,Text,Preprint,Ice over troubled waters: Navigating the North...,"Panikkar, Bindu; Lemmond, Benjamin; Else, Bren...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-19,2018.0,2018,"[{""date"": ""2018-06-19T20:21:45.897497+00:00"", ...",parent,crossref::10.31230/osf.io/bzywv,6386185577395458263,benjamin_lemmond;bindu_panikkar;brent_else;mar...,ice over troubled waters navigating the northw...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/bzywv,6386185577395458263,None
1797295,datacite::10.17605/osf.io/947ae,MarXiv,datacite,10.17605/osf.io/947ae,https://doi.org/10.17605/osf.io/947ae,https://marxiv.org/947ae/,Text,Preprint,Mercury Biomagnification Through a Coral Reef ...,"Rumbold, Darren; Lienhardt, Christopher; Parso...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-19,2018.0,2018,"[{""date"": ""2018-06-19T20:34:05.540981+00:00"", ...",parent,crossref::10.31230/osf.io/947ae,14289484070736187829,christopher_lienhardt;darren_rumbold;michael_p...,mercury biomagnification through a coral reef ...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/947ae,14289484070736187829,None
1797296,datacite::10.17605/osf.io/yz97p,MarXiv,datacite,10.17605/osf.io/yz97p,https://doi.org/10.17605/osf.io/yz97p,https://marxiv.org/yz97p/,Text,Preprint,Mercury biomagnification through food webs alo...,"Rumbold, Darren; Lange, Ted; Richards, Doug; D...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-19,2018.0,2018,"[{""date"": ""2018-06-19T20:40:36.580650+00:00"", ...",parent,crossref::10.31230/osf.io/yz97p,relaxed::A1_tokenbag_exact::16053,darren_rumbold;delpizzo_gina;doug_richards;has...,mercury biomagnification through food webs alo...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/yz97p,relaxed::A1_tokenbag_exact::16053,None
1797315,datacite::10.17605/osf.io/7dkhs,PsyArXiv,datacite,10.17605/osf.io/7dkhs,https://doi.org/10.17605/osf.io/7dkhs,https://psyarxiv.com/7dkhs/,Text,Preprint,The Personality Context of Adolescent Gambling...,"Reardon, Kathleen; Wang, Meggie; Tackett, Jenn...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-20,2018.0,2018,"[{""date"": ""2018-06-20T22:32:00.242096+00:00"", ...",parent,None,relaxed::A1_tokenbag_exact::19607,clayton_neighbors;jennifer_tackett;kathleen_re...,the personality context of adolescent gambling...,None,None,parent,None,relaxed::A1_tokenbag_exact::19607,None
1797316,datacite::10.17605/osf.io/8c2ks,MarXiv,datacite,10.17605/osf.io/8c2ks,https://doi.org/10.17605/osf.io/8c2ks,https://marxiv.org/8c2ks/,Text,Preprint,Major threats of pollution and climate change ...,"Lu, Yonglong; Yuan, Jingjing",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-20,2018.0,2018,"[{""date"": ""2018-06-20T22:48:48.999796+00:00"", ...",parent,crossref::10.31230/osf.io/8c2ks,6208755677271324050,jingjing_yuan;lu_yonglong,major threats of pollution and climate change ...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/8c2ks,6208755677271324050,None
1797322,datacite::10.17605/osf.io/n6wjd,MarXiv,datacite,10.17605/osf.io/n6wjd,https://doi.org/10.17605/osf.io/n6wjd,https://marxiv.org/n6wjd/,Text,Preprint,State of the plate: Assessing present and futu...,"Teneva, Lida; Schemmel, Eva; Kittinger, John",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-21,2018.0,2018,"[{""date"": ""2018-06-21T15:52:35.464481+00:00"", ...",parent,crossref::10.31230/osf.io/n6wjd,relaxed::A1_tokenbag_exact::16046,eva_schemmel;john_kittinger;lida_teneva,state of the plate assessing present and futur...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/n6wjd,relaxed::A1_tokenbag_exact::16046,None
1797324,datacite::10.17605/osf.io/2rctj,MarXiv,datacite,10.17605/osf.io/2rctj,https://doi.org/10.17605/osf.io/2rctj,https://marxiv.org/2rctj/,Text,Preprint,Reef vision: A citizen science program for mon...,"Florisson, James; Tweedley, James; Walker, Tim...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-21,2018.0,2018,"[{""date"": ""2018-06-21T16:16:39.447494+00:00"", ...",parent,crossref::10.31230/osf.io/2rctj,relaxed::A1_tokenbag_exact::16050,chaplin_jennifer;florisson_james;james_tweedle...,reef vision a citizen science program for moni...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/2rctj,relaxed::A1_tokenbag_exact::16050,None
1797325,datacite::10.17605/osf.io/x2jft,MarXiv,datacite,10.17605/osf.io/x2jft,https://doi.org/10.17605/osf.io/x2jft,https://marxiv.org/x2jft/,Text,Preprint,Trophic transfer of microplastics and mixed co...,"Carbery, Maddison; O'Connor, Wayne; Thavamani,...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-21,2018.0,2018,"[{""date"": ""2018-06-21T20:07:30.210423+00:00"", ...",parent,crossref::10.31230/osf.io/x2jft,16017149976655087433,carbery_maddison;connor_o_wayne;palanisami_tha...,trophic transfer of microplastics and mixed co...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/x2jft,16017149976655087433,None
1797326,datacite::10.17605/osf.io/qgcxj,PsyArXiv,datacite,10.17605/osf.io/qgcxj,https://doi.org/10.17605/osf.io/qgcxj,https://psyarxiv.com/qgcxj/,Text,Preprint,The Need for Self-Control in Achievement Tests...,"Lindner, Christoph; Nagy, Gabriel; Retelsdorf,...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-21,2018.0,2018,"[{""date"": ""2018-06-21T21:46:02.297679+00:00"", ...",parent,None,15377926100702288702,christoph_lindner;gabriel_nagy;jan_retelsdorf,the need for self control in achievement tests...,None,None,parent,None,15377926100702288702,None
1797332,datacite::10.17605/osf.io/cm68n,MarXiv,datacite,10.17605/osf.io/cm68n,https://doi.org/10.17605/osf.io/cm68n,https://marxiv.org/cm68n/,Text,Preprint,Gestión de playas urbanas: un análisis compa...,"Bombana, Briana; Polette, Marcus; Scalone, Daniel",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-22,2018.0,2018,"[{""date"": ""2018-06-22T16:24:08.305043+00:00"", ...",parent,crossref::10.31230/osf.io/cm68n,relaxed::A1_tokenbag_exact::16052,bombana_briana;daniel_scalone;marcus_polette,gestion de playas urbanas un analisis comparat...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/cm68n,relaxed::A1_tokenbag_exact::16052,None
1797338,datacite::10.17605/osf.io/x4fb7,MarXiv,datacite,10.17605/osf.io/x4fb7,https://doi.org/10.17605/osf.io/x4fb7,https://marxiv.org/x4fb7/,Text,Preprint,Fishers’ participation in small-scale fisherie...,"Semitiel-García, María; Noguera-Méndez, Pedro",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-22,2018.0,2018,"[{""date"": ""2018-06-22T18:32:15.567476+00:00"", ...",parent,crossref::10.31230/osf.io/x4fb7,4508312528506938120,garcia_maria_semitiel;mendez_noguera_pedro,fishers participation in small scale fisheries...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/x4fb7,4508312528506938120,None
1797342,datacite::10.17605/osf.io/5dua6,MarXiv,datacite,10.17605/osf.io/5dua6,https://doi.org/10.17605/osf.io/5dua6,https://marxiv.org/5dua6/,Text,Preprint,Using people's perceptions of ecosystem servic...,"Elwell, Tammy; Gelcich, Stefan; Gaines, Steven...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent - duplicate (MarXiv),2018-06-22,2018.0,2018,"[{""date"": ""2018-06-22T22:43:23.625418+00:00"", ...",parent,crossref::10.31230/osf.io/5dua6,relaxed::A1_tokenbag_exact::16054,carr_david_lopez;elwell_tammy;gaines_steven;ge...,using people s perceptions of ecosystem servic...,None,None,parent - duplicate (MarXiv),crossref::10.31230/osf.io/5dua6,relaxed::A1_tokenbag_exact::16054,None
1797347,datacite::10.17605/osf.io/2s8rv,PsyArXiv,datacite,10.17605/osf.io/2s8rv,https://doi.org/10.17605/osf.io/2s8rv,https://psyarxiv.com/2s8rv/,Text,Preprint,Do computer games jeopardize educational outco...,"Gnambs, Timo; Stasielowicz, Lukasz; Wolter, Il...",None,None,"[{""relatedIdentifier"": ""https://dx.doi.org/10....",None,NaN,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cos.osf"", ""type"": ...",parent,2018-06-23,2018.0,2018,"[{""date"": ""2018-06-23T12:39:54.551624+00:00"", ...",parent,None,6375251174364923464,appel_markus;gnambs_timo;ilka_wolter;lukasz_st...,do computer games jeopardize educational outco...,None,None,parent,None,6375251174364923464,None

In [24]:
osfdf = result3[result3['server_name']=='Open Science Framework']#.sample(60)

In [25]:
pattern = 'osf.io/preprints/'

mask = osfdf['landing_page_url'].str.contains(pattern, regex=False, na=False)
osfdfs = osfdf[mask]
osfdfs

Empty DataFrame
Columns: [record_id, server_name, backend, doi, doi_url, landing_page_url, type_backend_raw, subtype_backend_raw, title, authors_flat, institutions_flat, countries_flat, relations_json, version_label, is_version_of, is_preprint_of, has_preprint, has_review, has_published_version, published_version_ids_json, version_of_ids_json, update_to_json, raw_relationships_json, records_hierarchy, date_first_seen, publication_year, publication_year_first_seen, raw_dates, records_hierarchy_backup, parent_record_id, dup_group_id, authors_fp_tokenbag, title_clean_v2, authors_fp_last_initial, authors_fp_last, records_hierarchy_dedupe_backup, parent_record_id_dedupe_backup, dup_group_id_dedupe_backup, has_version_dois]
Index: []

In [26]:
record_ex = data_clean_isversionof[data_clean_isversionof['record_id']=='datacite::10.5281/zenodo.15050897']
record_ex

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
4414186,datacite::10.5281/zenodo.15050897,Zenodo,datacite,10.5281/zenodo.15050897,https://doi.org/10.5281/zenodo.15050897,https://zenodo.org/doi/10.5281/zenodo.15050897,Preprint,,The Indeterminacy Space as the Foundation of S...,"Paruzel, Katarzyna Anna",None,None,"[{""relatedIdentifier"": ""10.5281/zenodo.1505347...",None,10.5281/zenodo.15053474;10.5281/zenodo.1505352...,,,,false,None,None,None,"{""client"": {""data"": {""id"": ""cern.zenodo"", ""typ...",parent,2025-02-26,2025.0,2025,"[{""date"": ""2025-02-26"", ""dateType"": ""Issued""},...",parent,None,2507215253830421560,anna_katarzyna_paruzel,the indeterminacy space as the foundation of s...,paruzel|k,None,parent,None,2507215253830421560,10.5281/zenodo.16944639;10.5281/zenodo.15050898

In [27]:
data_clean_isversionof[data_clean_isversionof['has_version_dois'].isna()]

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
0,crossref::10.21467/preprints.48,AIJR Preprints,crossref,10.21467/preprints.48,https://doi.org/10.21467/preprints.48,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,"Bird’s Eye View on the Diagnosis, Treatment, &...","Panchalingala, Sai Bhargavi",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-05-03,2020.0,2020,None,parent,None,None,None,None,None,None,parent,None,None,None
1,crossref::10.21467/preprints.43,AIJR Preprints,crossref,10.21467/preprints.43,https://doi.org/10.21467/preprints.43,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Doxycycline and Minocycline Drugs as a Treatme...,"Mostafa, Mohamed",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-25,2020.0,2020,None,parent,None,None,mohamed_mostafa,doxycycline and minocycline drugs as a treatme...,mostafa|m,None,parent,None,None,None
2,crossref::10.21467/preprints.39,AIJR Preprints,crossref,10.21467/preprints.39,https://doi.org/10.21467/preprints.39,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,A Genetic Perspective of 2019-nCoV in Relation...,"Dasgupta, Rimjhim",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-16,2020.0,2020,None,parent,None,None,dasgupta_rimjhim,a genetic perspective of 2019 ncov in relation...,dasgupta|r,None,parent,None,None,None
3,crossref::10.21467/preprints.38,AIJR Preprints,crossref,10.21467/preprints.38,https://doi.org/10.21467/preprints.38,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Marine Algae as a Natural Source for Antiviral...,"Musale, Amar S; G., Raja Krishna Kumar; Sapre,...",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-15,2020.0,2020,None,parent,None,None,None,None,None,None,parent,None,None,None
4,crossref::10.21467/preprints.36,AIJR Preprints,crossref,10.21467/preprints.36,https://doi.org/10.21467/preprints.36,https://preprints.aijr.org/index.php/ap/prepri...,posted-content,preprint,Possible Prevention of COVID 19 by Using Linol...,"Subhash, Venkata; G, Raja Krishna Kumar; Sapre...",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2020-04-15,2020.0,2020,None,parent,None,None,None,None,None,None,parent,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7911896,openalex::W999325625,viXra,openalex,None,None,https://vixra.org/pdf/1409.0090v1.pdf,preprint,None,Three Objections to Modern Physics,Lubomir Vlcek,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-09-01,2014.0,2014,None,parent,None,None,lubomir_vlcek,three objections to modern physics,vlcek|l,None,parent,None,None,None
7911897,openalex::W999460032,viXra,openalex,None,None,https://vixra.org/abs/1112.0094,preprint,None,Particle Mass Ratios,DT Froedge,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2011-12-01,2011.0,2011,None,parent,None,None,dt_froedge,particle mass ratios,froedge|d,None,parent,None,None,None
7911898,openalex::W99967155,viXra,openalex,None,None,https://vixra.org/pdf/1406.0019v1.pdf,preprint,None,Quantum FFF Theory Proposals for Some Unsolved...,Leo Vuyk,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-06-01,2014.0,2014,None,parent,None,None,leo_vuyk,quantum fff theory proposals for some unsolved...,vuyk|l,None,parent,None,None,None
7911899,openalex::W999790414,viXra,openalex,None,None,https://vixra.org/pdf/1306.0105v3.pdf,preprint,None,Investigation of the Formalism of Particle Dyn...,Chi-Yi Chen,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2013-06-01,2013.0,2013,None,parent,None,None,chen_chi_yi,investigation of the formalism of particle dyn...,chen|c,None,parent,None,None,None
7911900,openalex::W999805801,viXra,openalex,None,None,https://vixra.org/pdf/1412.0197v3.pdf,preprint,None,Electromagnetic Energy and Electromagnetic For...,Yu.A. Spirichev,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-12-01,2014.0,2014,None,parent,None,None,a_spirichev_yu,electromagnetic energy and electromagnetic for...,spirichev|y,None,parent,None,None,None

## apply the modifications in is_version_of columns

In [28]:
pattern = '"relatedIdentifier"'

mask = data_clean_isversionof["relations_json"].str.contains(pattern, na=False)

data_clean_isversionof.loc[mask, "is_version_of"] = data_clean_isversionof.loc[mask, "has_version_dois"]

print(f"Rows updated: {mask.sum():,}")
print(f"Non-null is_version_of after update: {data_clean_isversionof['is_version_of'].notna().sum():,}")

Rows updated: 1,480,179
Non-null is_version_of after update: 1,553,399

In [29]:
data_clean_isversionof = data_clean_isversionof.sort_values(by='record_id')

# function

In [30]:
import time
import pandas as pd
import numpy as np
from typing import Dict, Any, Optional

# ------------------------------------------------------------
# Union-Find (Disjoint Set Union) for fast connected-components
# ------------------------------------------------------------
class _UnionFind:
    __slots__ = ("parent", "size")

    def __init__(self, n: int):
        self.parent = np.arange(n, dtype=np.int32)
        self.size = np.ones(n, dtype=np.int32)

    def find(self, x: int) -> int:
        parent = self.parent
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(self, a: int, b: int) -> bool:
        pa = self.find(a)
        pb = self.find(b)
        if pa == pb:
            return False
        # union by size
        if self.size[pa] < self.size[pb]:
            pa, pb = pb, pa
        self.parent[pb] = pa
        self.size[pa] += self.size[pb]
        return True


def unify_groups_by_version_links(
    df: pd.DataFrame,
    *,
    # core cols
    record_id_col: str = "record_id",
    doi_col: str = "doi",
    is_version_of_col: str = "is_version_of",

    # output cols
    hierarchy_col: str = "records_hierarchy",
    parent_id_col: str = "parent_record_id",
    group_id_col: str = "dup_group_id",

    # parent choice
    date_col: Optional[str] = "date_first_seen",      # if None, will use record_id numeric fallback only
    choose_parent: str = "oldest",                    # "oldest" | "newest"

    # how safe to overwrite
    # - "unlabeled_only": only rows with NA hierarchy are eligible
    # - "parent_only": only rows currently labeled "parent" are eligible
    # - "any": any row is eligible
    overwrite_mode: str = "unlabeled_only",

    # labeling
    label_duplicate_suffix: str = "version-link",     # becomes "parent - duplicate (version-link)"

    # performance
    chunk_size: int = 300_000,                        # only affects the union loop; tune for RAM/CPU
    min_component_size: int = 2,                      # ignore components of size < 2
) -> tuple[pd.DataFrame, Dict[str, Any]]:
    """
    Unify clusters using explicit version relationships (is_version_of) as a HIGH-CONFIDENCE step.

    How it works (fast + robust):
      1) For rows that have either a DOI or an is_version_of list, build a graph where:
         - each row is a node
         - edges exist when two rows share any DOI in their version-set (self DOI + is_version_of DOIs)
      2) Compute connected components via Union-Find (near O(N)).
      3) For each component (size>=2), choose ONE parent (oldest/newest by date, tie-break by record_id numeric).
      4) Update:
         - hierarchy_col: "parent" for parent, "parent - duplicate (version-link)" for others
         - parent_id_col: parent record_id for duplicates
         - group_id_col: stable id "version::<root_record_id>" (can be merged later with other stages)

    Safe overwrite:
      - overwrite_mode controls WHICH rows get updated (eligible), but parents are chosen using all rows in component.

    Returns:
      (df, metrics)
    """

    t0 = time.perf_counter()
    metrics: Dict[str, Any] = {
        "n_rows_df": int(len(df)),
        "n_rows_with_any_version_signal": 0,
        "n_rows_considered_in_graph": 0,
        "n_edges_unions_attempted": 0,
        "n_unions_done": 0,
        "n_components_total": 0,
        "n_components_size_ge_2": 0,
        "n_rows_in_components_size_ge_2": 0,
        "n_rows_eligible_to_update": 0,
        "n_rows_updated": 0,
        "n_parents_set": 0,
        "n_children_set": 0,
        "runtime_s": 0.0,
    }

    # -----------------------------
    # Basic column checks / setup
    # -----------------------------
    for c in (hierarchy_col, parent_id_col, group_id_col):
        if c not in df.columns:
            df[c] = pd.NA

    if record_id_col not in df.columns:
        raise ValueError(f"Missing required column: {record_id_col}")
    if doi_col not in df.columns:
        raise ValueError(f"Missing required column: {doi_col}")
    if is_version_of_col not in df.columns:
        raise ValueError(f"Missing required column: {is_version_of_col}")

    if choose_parent not in {"oldest", "newest"}:
        raise ValueError("choose_parent must be 'oldest' or 'newest'")
    if overwrite_mode not in {"unlabeled_only", "parent_only", "any"}:
        raise ValueError("overwrite_mode must be 'unlabeled_only' | 'parent_only' | 'any'")

    # eligibility mask (safe overwrite)
    h = df[hierarchy_col]
    if overwrite_mode == "any":
        eligible_mask = pd.Series(True, index=df.index)
    elif overwrite_mode == "unlabeled_only":
        eligible_mask = h.isna()
    else:  # parent_only
        eligible_mask = h.astype("string").str.strip().str.lower().eq("parent")

    metrics["n_rows_eligible_to_update"] = int(eligible_mask.sum())

    # ------------------------------------------------------------
    # Build the subset to include in the VERSION graph
    # (We include rows that have DOI OR is_version_of list,
    #  because some rows might have missing doi but have version list.)
    # ------------------------------------------------------------
    doi_s = df[doi_col].astype("string").fillna("").str.strip()
    v_s = df[is_version_of_col].astype("string").fillna("").str.strip()

    has_signal = (doi_s != "") | (v_s != "")
    metrics["n_rows_with_any_version_signal"] = int(has_signal.sum())

    idx = df.index[has_signal].to_numpy()
    if idx.size == 0:
        metrics["runtime_s"] = time.perf_counter() - t0
        return df, metrics

    # Compact indexing for Union-Find arrays
    # local_i: 0..k-1 corresponds to df index idx[local_i]
    k = idx.size
    metrics["n_rows_considered_in_graph"] = int(k)

    # For parent selection: precompute helpers on this subset
    rid = df.loc[idx, record_id_col].astype("string").fillna("")
    # numeric fallback from record_id: extract digits
    rid_num = pd.to_numeric(rid.str.extract(r"(\d+)")[0], errors="coerce")

    if date_col and date_col in df.columns:
        dt = pd.to_datetime(df.loc[idx, date_col], errors="coerce")
    else:
        dt = pd.Series(pd.NaT, index=idx)

    # union-find structure
    uf = _UnionFind(k)

    # ------------------------------------------------------------
    # Union phase: stream through rows and connect by shared DOIs
    # Using a dict: doi -> first_local_index_seen
    # ------------------------------------------------------------
    doi_to_rep: Dict[str, int] = {}

    def _iter_version_set(self_doi: str, is_version_of_str: str):
        """
        Yield DOIs in (self DOI + is_version_of list).
        Designed to be cheap: split ';' only.
        """
        if self_doi:
            yield self_doi
        if is_version_of_str:
            # common case: "doi1;doi2;doi3"
            for part in is_version_of_str.split(";"):
                d = part.strip()
                if d:
                    yield d

    # Process in chunks for cache friendliness (still single pass)
    unions_attempted = 0
    unions_done = 0

    # Pre-pull arrays for speed
    doi_arr = doi_s.loc[idx].to_numpy(dtype=object)
    v_arr = v_s.loc[idx].to_numpy(dtype=object)

    for start in range(0, k, chunk_size):
        end = min(k, start + chunk_size)
        for local_i in range(start, end):
            sd = doi_arr[local_i]
            sv = v_arr[local_i]
            # build edges for this row: union with representative of each doi token
            first_rep = None
            for d in _iter_version_set(sd, sv):
                rep = doi_to_rep.get(d)
                if rep is None:
                    doi_to_rep[d] = local_i
                    if first_rep is None:
                        first_rep = local_i
                else:
                    unions_attempted += 1
                    if uf.union(local_i, rep):
                        unions_done += 1

    metrics["n_edges_unions_attempted"] = int(unions_attempted)
    metrics["n_unions_done"] = int(unions_done)

    # ------------------------------------------------------------
    # Build components: root -> list of local indices
    # ------------------------------------------------------------
    roots = np.empty(k, dtype=np.int32)
    for i in range(k):
        roots[i] = uf.find(i)

    # group by root using pandas (fast enough); avoid Python dict of lists for k large
    comp_df = pd.DataFrame({"root": roots, "local_i": np.arange(k, dtype=np.int32)})
    comp_sizes = comp_df["root"].value_counts()
    metrics["n_components_total"] = int(comp_sizes.shape[0])

    big_roots = comp_sizes[comp_sizes >= min_component_size].index.to_numpy(dtype=np.int32)
    metrics["n_components_size_ge_2"] = int(big_roots.size)
    if big_roots.size == 0:
        metrics["runtime_s"] = time.perf_counter() - t0
        return df, metrics

    # Filter to only components we will act on
    comp_big = comp_df[comp_df["root"].isin(big_roots)].copy()
    metrics["n_rows_in_components_size_ge_2"] = int(len(comp_big))

    # ------------------------------------------------------------
    # Parent selection per component
    # Parent = oldest/newest dt, tie-break by record_id numeric (rid_num)
    # ------------------------------------------------------------
    # Map local_i -> df index
    df_index_for_local = idx  # numpy array length k

    # Create selection frame with sortable keys
    # Note: dt index is df idx; align via local index mapping
    sel_idx = df_index_for_local[comp_big["local_i"].to_numpy()]
    sel = pd.DataFrame({
        "root": comp_big["root"].to_numpy(),
        "df_idx": sel_idx,
        "record_id": df.loc[sel_idx, record_id_col].astype("string").to_numpy(),
        "dt": dt.loc[sel_idx].to_numpy(),
        "rid_num": rid_num.loc[sel_idx].to_numpy(),
    })

    # Sort for parent picking
    asc_dt = True if choose_parent == "oldest" else False
    asc_rn = True if choose_parent == "oldest" else False

    # When dt is NaT, push to end for "oldest" and to start for "newest"
    # pandas sort_values uses na_position; we’ll handle by two sorts:
    na_pos = "last" if choose_parent == "oldest" else "first"

    sel_sorted = sel.sort_values(
        by=["root", "dt", "rid_num"],
        ascending=[True, asc_dt, asc_rn],
        na_position=na_pos,
        kind="mergesort",  # stable
    )

    # parent per root = first row per root
    parents = sel_sorted.groupby("root", sort=False).head(1)[["root", "df_idx", "record_id"]].rename(
        columns={"df_idx": "parent_df_idx", "record_id": "parent_record_id"}
    )

    parent_map_idx = parents.set_index("root")["parent_df_idx"]
    parent_map_rid = parents.set_index("root")["parent_record_id"]

    # ------------------------------------------------------------
    # Apply updates safely (only eligible rows)
    # ------------------------------------------------------------
    # Create per-row root for ALL rows in big components (same as sel_idx rows)
    sel["parent_df_idx"] = sel["root"].map(parent_map_idx).to_numpy()
    sel["parent_record_id"] = sel["root"].map(parent_map_rid).to_numpy()

    # Determine which df rows in these components are eligible to update
    sel["eligible"] = eligible_mask.loc[sel["df_idx"]].to_numpy()

    # Update parents/children among eligible rows only
    is_parent_row = sel["df_idx"].to_numpy() == sel["parent_df_idx"].to_numpy()
    eligible_parent = sel["eligible"].to_numpy() & is_parent_row
    eligible_child = sel["eligible"].to_numpy() & (~is_parent_row)

    parent_idxs = sel.loc[eligible_parent, "df_idx"].to_numpy()
    child_idxs  = sel.loc[eligible_child, "df_idx"].to_numpy()

    # Group id strategy:
    # - stable and readable: "version::<parent_record_id>"
    # This is perfect for later merging with other stages.
    #gid = "version::" + sel["parent_record_id"].astype("string")
    gid = sel["parent_record_id"].astype("string")

    # Apply
    if parent_idxs.size:
        df.loc[parent_idxs, hierarchy_col] = "parent"
        df.loc[parent_idxs, parent_id_col] = pd.NA
        df.loc[parent_idxs, group_id_col] = gid.loc[sel["df_idx"].isin(parent_idxs)].to_numpy()
    if child_idxs.size:
        df.loc[child_idxs, hierarchy_col] = f"parent - duplicate ({label_duplicate_suffix})"
        df.loc[child_idxs, parent_id_col] = sel.loc[sel["df_idx"].isin(child_idxs), "parent_record_id"].to_numpy()
        df.loc[child_idxs, group_id_col] = gid.loc[sel["df_idx"].isin(child_idxs)].to_numpy()

    metrics["n_rows_updated"] = int(parent_idxs.size + child_idxs.size)
    metrics["n_parents_set"] = int(parent_idxs.size)
    metrics["n_children_set"] = int(child_idxs.size)

    metrics["runtime_s"] = time.perf_counter() - t0
    return df, metrics


# ------------------------------------------------------------
# Example usage
# ------------------------------------------------------------
# df2, m = unify_groups_by_version_links(
#     data_out,
#     overwrite_mode="unlabeled_only",   # safest: only fill missing
#     choose_parent="oldest",
#     date_col="date_first_seen",
#     chunk_size=300_000,
# )
# print(m)

In [31]:
data_out, metric = unify_groups_by_version_links(
    data_clean_isversionof,
    overwrite_mode="any",   
    choose_parent="oldest",
    date_col="date_first_seen",
    chunk_size=300_000,
)
print(metric)

{'n_rows_df': 7905699, 'n_rows_with_any_version_signal': 6281118, 'n_rows_considered_in_graph': 6281118, 'n_edges_unions_attempted': 398342, 'n_unions_done': 189511, 'n_components_total': 6091607, 'n_components_size_ge_2': 132374, 'n_rows_in_components_size_ge_2': 321885, 'n_rows_eligible_to_update': 7905699, 'n_rows_updated': 321885, 'n_parents_set': 132374, 'n_children_set': 189511, 'runtime_s': 32.883286376}

# save

In [33]:
from pathlib import Path
import json
import pandas as pd

OUT_DIR = Path("outputs_new")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Save metrics
with open(OUT_DIR / "dedupe_metrics_version_links.json", "w") as f:
    json.dump(metric, f, indent=2)

#pd.DataFrame(metric).to_csv(OUT_DIR / "dedupe_metrics_version_links.csv", index=False)

# Save dataset
data_out.to_parquet(OUT_DIR / "dedupe_data_out_version_links.parquet", index=False)

print("✅ All files saved to outputs/")

✅ All files saved to outputs/

In [34]:
data_out['records_hierarchy'].value_counts()

records_hierarchy
parent                                  7332296
parent - duplicate (version-link)        189511
parent - duplicate (SSRN)                112595
parent - duplicate (arXiv)                59662
parent - duplicate (Research Square)      40015
                                         ...
parent - duplicate (LatArXiv)                 2
parent - duplicate (SAE Mobilus®)             2
parent - duplicate (Encyclopedia)             1
parent - duplicate (Therapoid)                1
parent - duplicate (BioHackrXiv)              1
Name: count, Length: 103, dtype: int64

In [35]:
data_out

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
344247,crossref::10.1002/essoar.10500000.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500000.1,https://doi.org/10.1002/essoar.10500000.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Long-term monitoring of land surface phenologi...,"Tsutsumida, Narumasa",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2018-05-24,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None
344248,crossref::10.1002/essoar.10500002.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500002.1,https://doi.org/10.1002/essoar.10500002.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Impact of spatial scale for phenological indic...,"Tsutsumida, Narumasa; Kaduk, Jörg",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2018-05-27,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None
344243,crossref::10.1002/essoar.10500004.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500004.1,https://doi.org/10.1002/essoar.10500004.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Observations of Low Latitude Red Aurora in Mex...,"Gonzalez-Esparza, J. Americo; Cuevas-Cardona, ...",Universidad Autónoma del Estado de Hidalgo,None,"{""is-preprint-of"": [{""asserted-by"": ""subject"",...",None,NaN,10.1029/2018sw001995,,,true,None,None,None,None,parent,2018-05-28,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None
344269,crossref::10.1002/essoar.10500007.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500007.1,https://doi.org/10.1002/essoar.10500007.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Pipeline oil fire detection with MODIS active ...,"Ogungbuyi, Michael Gbenga; Martinez, Peter; Ec...",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2018-05-30,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None
344264,crossref::10.1002/essoar.10500009.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500009.1,https://doi.org/10.1002/essoar.10500009.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Land Product Validation of MODIS Derived FPAR ...,"Sharp, Iain; Sanchez-Azofeifa, Arturo; Musilek...",None,None,None,None,NaN,,,,false,None,None,None,None,parent,2018-06-05,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2193176,openalex::W999921877,RePEc: Research Papers in Economics,openalex,None,None,https://steconomice.uoradea.ro/anale/volume/20...,preprint,None,IDE sous l'influence du degré de l'intégration...,Simona-Gabriela Serbu Masca,Babeș-Bolyai University,RO,None,None,None,None,None,None,None,None,None,None,None,parent,2008-01-01,2008.0,2008,None,parent,None,None,gabriela_masca_serbu_simona,ide sous l influence du degre de l integration...,masca|s,None,parent,None,None,None
868914,openalex::W999947037,HAL,openalex,None,None,https://hal.science/hal-01922484,preprint,None,Building realistic potential patients queries ...,Lorraine Goeuriot; Wendy W. Chapman; Gareth Jf...,Laboratoire d'Informatique de Grenoble; Dublin...,FR; IE,None,None,None,None,None,None,None,None,None,None,None,parent,2014-01-01,2014.0,2014,None,parent,None,None,None,None,None,None,parent,None,None,None
2099883,openalex::W999974616,RePEc: Research Papers in Economics,openalex,None,None,https://EconPapers.repec.org/RePEc:cde:cdewps:19,preprint,None,Debt Financing with Limited Liability and Quan...,Krishnendu Ghosh Dastidar,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,1994-08-01,1994.0,1994,None,parent,None,None,dastidar_ghosh_krishnendu,debt financing with limited liability and quan...,dastidar|k,None,parent,None,None,None
868068,openalex::W999989114,HAL,openalex,None,None,https://hal.science/hal-01268467,preprint,None,Sustainable orchards' redesign: at the crossro...,Servane Penvern; Sylvaine Simon; Stéphane Bell...,Institut National de Recherche pour l'Agricult...,FR,None,None,None,None,None,None,None,None,None,None,None,parent,2012-07-01,2012.0,2012,None,parent,None,None,None,None,None,None,parent,None,None,None
2226731,openalex::W999989584,RePEc: Research Papers in Economics,openalex,None,None,http://thred.devecon.org/papers/2014/2014-018_...,preprint,None,When warm glow burns: Motivational (mis)alloca...,Gani Aldashev; Esteban Jaimovich; Thierry Verdier,University of Namur; University of Surrey; Éco...,BE; GB; BI; FR,None,None,None,None,None,None,None,None,None,None,None,parent,2015-02-01,2015.0,2015,None,parent,None,None,aldashev_gani;esteban_jaimovich;thierry_verdier,when warm glow burns motivational mis allocati...,aldashev|g;jaimovich|e;verdier|t,None,parent,None,None,None

In [36]:
# to check records_hierarchy

In [37]:
pattern = "10.26434/chemrxiv.13102877"


mask = data_out['doi'].str.contains(pattern, regex=False, na=False)
result = data_out[mask]
print(len(result))
result

32

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois
235547,crossref::10.26434/chemrxiv.13102877.v1,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v1,https://doi.org/10.26434/chemrxiv.13102877.v1,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD): ...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v2;10.26434/chemrxi...,,,,false,None,None,None,None,parent,2020-10-23,2020.0,2020,None,parent,<NA>,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add pro...,datta|s,None,parent,None,16854196709595633026,None
235900,crossref::10.26434/chemrxiv.13102877.v10,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v10,https://doi.org/10.26434/chemrxiv.13102877.v10,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-12-03,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
235949,crossref::10.26434/chemrxiv.13102877.v11,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v11,https://doi.org/10.26434/chemrxiv.13102877.v11,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-12-04,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
235995,crossref::10.26434/chemrxiv.13102877.v12,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v12,https://doi.org/10.26434/chemrxiv.13102877.v12,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-12-07,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236036,crossref::10.26434/chemrxiv.13102877.v13,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v13,https://doi.org/10.26434/chemrxiv.13102877.v13,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-12-10,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236086,crossref::10.26434/chemrxiv.13102877.v14,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v14,https://doi.org/10.26434/chemrxiv.13102877.v14,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-12-22,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236145,crossref::10.26434/chemrxiv.13102877.v15,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v15,https://doi.org/10.26434/chemrxiv.13102877.v15,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-12-30,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236162,crossref::10.26434/chemrxiv.13102877.v16,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v16,https://doi.org/10.26434/chemrxiv.13102877.v16,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-01-04,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236171,crossref::10.26434/chemrxiv.13102877.v17,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v17,https://doi.org/10.26434/chemrxiv.13102877.v17,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-01-05,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236176,crossref::10.26434/chemrxiv.13102877.v18,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v18,https://doi.org/10.26434/chemrxiv.13102877.v18,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-01-08,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236174,crossref::10.26434/chemrxiv.13102877.v19,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v19,https://doi.org/10.26434/chemrxiv.13102877.v19,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-01-12,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
235577,crossref::10.26434/chemrxiv.13102877.v2,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v2,https://doi.org/10.26434/chemrxiv.13102877.v2,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD): ...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-10-27,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add pro...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v1,16854196709595633026,None
236175,crossref::10.26434/chemrxiv.13102877.v20,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v20,https://doi.org/10.26434/chemrxiv.13102877.v20,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-01-13,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236180,crossref::10.26434/chemrxiv.13102877.v21,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v21,https://doi.org/10.26434/chemrxiv.13102877.v21,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-01-20,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236182,crossref::10.26434/chemrxiv.13102877.v22,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v22,https://doi.org/10.26434/chemrxiv.13102877.v22,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-01-27,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236183,crossref::10.26434/chemrxiv.13102877.v23,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v23,https://doi.org/10.26434/chemrxiv.13102877.v23,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-02-01,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236188,crossref::10.26434/chemrxiv.13102877.v24,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v24,https://doi.org/10.26434/chemrxiv.13102877.v24,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-02-03,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236189,crossref::10.26434/chemrxiv.13102877.v25,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v25,https://doi.org/10.26434/chemrxiv.13102877.v25,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-02-04,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236191,crossref::10.26434/chemrxiv.13102877.v26,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v26,https://doi.org/10.26434/chemrxiv.13102877.v26,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-02-18,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236192,crossref::10.26434/chemrxiv.13102877.v27,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v27,https://doi.org/10.26434/chemrxiv.13102877.v27,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-02-22,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236193,crossref::10.26434/chemrxiv.13102877.v28,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v28,https://doi.org/10.26434/chemrxiv.13102877.v28,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-03-01,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236194,crossref::10.26434/chemrxiv.13102877.v29,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v29,https://doi.org/10.26434/chemrxiv.13102877.v29,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-03-03,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
235604,crossref::10.26434/chemrxiv.13102877.v3,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v3,https://doi.org/10.26434/chemrxiv.13102877.v3,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2020-11-06,2020.0,2020,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,datta|s,None,parent,None,15378799223749550050,None
236195,crossref::10.26434/chemrxiv.13102877.v30,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v30,https://doi.org/10.26434/chemrxiv.13102877.v30,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD) i...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-03-08,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add is ...,None,None,parent - duplicate (ChemRxiv),crossref::10.26434/chemrxiv.13102877.v3,15378799223749550050,None
236198,crossref::10.26434/chemrxiv.13102877.v31,ChemRxiv,crossref,10.26434/chemrxiv.13102877.v31,https://doi.org/10.26434/chemrxiv.13102877.v31,https://chemrxiv.org/engage/chemrxiv/article-d...,posted-content,preprint,Aptamers for Detection and Diagnostics (ADD): ...,"Datta, Shoumen",MIT,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.26434/chemrxiv.13102877.v1;10.26434/chemrxi...,,,,false,None,None,None,None,parent - duplicate (version-link),2021-03-15,2021.0,2021,None,parent,crossref::10.26434/chemrxiv.13102877.v1,crossref::10.26434/chemrxiv.13102877.v1,datta_shoumen,aptamers for detection and diagnostics add can...,datta|s,None,parent,None,15120014104423475792,None

In [38]:
result['dup_group_id'].value_counts()

dup_group_id
crossref::10.26434/chemrxiv.13102877.v1    32
Name: count, dtype: int64

In [39]:
result['parent_record_id'].value_counts()

parent_record_id
crossref::10.26434/chemrxiv.13102877.v1    31
Name: count, dtype: int64

In [40]:
result['records_hierarchy'].value_counts()

records_hierarchy
parent - duplicate (version-link)    31
parent                                1
Name: count, dtype: int64