In [1]:
import pandas as pd
# Set option to display all columns
pd.set_option('display.max_columns', None)

# import data

In [2]:
data = pd.read_pickle("outputs_new/dedupe_data_group_merge.pkl")
data

,record_id,server_name,backend,doi,doi_url,landing_page_url,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year_first_seen,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
0,crossref::10.21467/preprints.48,AIJR Preprints,crossref,10.21467/preprints.48,https://doi.org/10.21467/preprints.48,https://preprints.aijr.org/index.php/ap/prepri...,"Bird’s Eye View on the Diagnosis, Treatment, &...","Panchalingala, Sai Bhargavi",None,None,None,None,None,,,,false,None,None,None,None,parent,2020-05-03,2020,parent,None,None,None,None,None,None,parent,None,None,parent,None,None
1,crossref::10.21467/preprints.43,AIJR Preprints,crossref,10.21467/preprints.43,https://doi.org/10.21467/preprints.43,https://preprints.aijr.org/index.php/ap/prepri...,Doxycycline and Minocycline Drugs as a Treatme...,"Mostafa, Mohamed",None,None,None,None,None,,,,false,None,None,None,None,parent,2020-04-25,2020,parent,None,None,mohamed_mostafa,doxycycline and minocycline drugs as a treatme...,mostafa|m,None,parent,None,None,parent,None,None
2,crossref::10.21467/preprints.39,AIJR Preprints,crossref,10.21467/preprints.39,https://doi.org/10.21467/preprints.39,https://preprints.aijr.org/index.php/ap/prepri...,A Genetic Perspective of 2019-nCoV in Relation...,"Dasgupta, Rimjhim",None,None,None,None,None,,,,false,None,None,None,None,parent,2020-04-16,2020,parent,None,None,dasgupta_rimjhim,a genetic perspective of 2019 ncov in relation...,dasgupta|r,None,parent,None,None,parent,None,None
3,crossref::10.21467/preprints.38,AIJR Preprints,crossref,10.21467/preprints.38,https://doi.org/10.21467/preprints.38,https://preprints.aijr.org/index.php/ap/prepri...,Marine Algae as a Natural Source for Antiviral...,"Musale, Amar S; G., Raja Krishna Kumar; Sapre,...",None,None,None,None,None,,,,false,None,None,None,None,parent,2020-04-15,2020,parent,None,None,None,None,None,None,parent,None,None,parent,None,None
4,crossref::10.21467/preprints.36,AIJR Preprints,crossref,10.21467/preprints.36,https://doi.org/10.21467/preprints.36,https://preprints.aijr.org/index.php/ap/prepri...,Possible Prevention of COVID 19 by Using Linol...,"Subhash, Venkata; G, Raja Krishna Kumar; Sapre...",None,None,None,None,None,,,,false,None,None,None,None,parent,2020-04-15,2020,parent,None,None,None,None,None,None,parent,None,None,parent,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8087413,openalex::W999325625,viXra,openalex,None,None,https://vixra.org/pdf/1409.0090v1.pdf,Three Objections to Modern Physics,Lubomir Vlcek,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-09-01,2014,parent,None,None,lubomir_vlcek,three objections to modern physics,vlcek|l,None,parent,None,None,parent,None,None
8087414,openalex::W999460032,viXra,openalex,None,None,https://vixra.org/abs/1112.0094,Particle Mass Ratios,DT Froedge,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2011-12-01,2011,parent,None,None,dt_froedge,particle mass ratios,froedge|d,None,parent,None,None,parent,None,None
8087415,openalex::W99967155,viXra,openalex,None,None,https://vixra.org/pdf/1406.0019v1.pdf,Quantum FFF Theory Proposals for Some Unsolved...,Leo Vuyk,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-06-01,2014,parent,None,None,leo_vuyk,quantum fff theory proposals for some unsolved...,vuyk|l,None,parent,None,None,parent,None,None
8087416,openalex::W999790414,viXra,openalex,None,None,https://vixra.org/pdf/1306.0105v3.pdf,Investigation of the Formalism of Particle Dyn...,Chi-Yi Chen,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2013-06-01,2013,parent,None,None,chen_chi_yi,investigation of the formalism of particle dyn...,chen|c,None,parent,None,None,parent,None,None
8087417,openalex::W999805801,viXra,openalex,None,None,https://vixra.org/pdf/1412.0197v3.pdf,Electromagnetic Energy and Electromagnetic For...,Yu.A. Spirichev,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2014-12-01,2014,parent,None,None,a_spirichev_yu,electromagnetic energy and electromagnetic for...,spirichev|y,None,parent,None,None,parent,None,None

In [3]:
data.published_version_ids_json.value_counts()

Series([], Name: count, dtype: int64)

In [4]:
data.records_hierarchy.value_counts()

records_hierarchy
parent                                            7469084
parent - duplicate (SSRN)                          135609
parent - duplicate (Zenodo)                         98768
parent - duplicate (arXiv)                          85011
parent - duplicate (Research Square)                59934
                                                   ...
parent - duplicate (SAE Mobilus®)                       1
parent - duplicate (Therapoid)                          1
parent - duplicate (WikiJournal of Humanities)          1
parent - duplicate (WikiJournal of Science)             1
parent - duplicate (searchRxiv)                         1
Name: count, Length: 110, dtype: int64

In [5]:
data.update_to_json.value_counts()

update_to_json
[{"DOI": "10.12688/aasopenres.13349.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2022, 6, 27]], "date-time": "2022-06-27T00:00:00Z", "timestamp": 1656288000000}}]                                                                                                                                                                                                                                       2
[{"DOI": "10.12688/gatesopenres.13204.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2021, 10, 18]], "date-time": "2021-10-18T00:00:00Z", "timestamp": 1634515200000}}]                                                                                                                                                                                                                                    1
[{"DOI": "10.12688/gatesopenres.14642.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2024, 1, 18]], "date-time": "2024-01-18T00:00:00Z", "timestamp": 1705536000000}}]                                                                                                                                                                                                                                     1
[{"DOI": "10.12688/gatesopenres.13221.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2021, 3, 24]], "date-time": "2021-03-24T00:00:00Z", "timestamp": 1616544000000}}]                                                                                                                                                                                                                                     1
[{"DOI": "10.12688/gatesopenres.14499.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2024, 2, 5]], "date-time": "2024-02-05T00:00:00Z", "timestamp": 1707091200000}}]                                                                                                                                                                                                                                      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ..
[{"DOI": "10.12688/f1000research.131306.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2023, 8, 29]], "date-time": "2023-08-29T00:00:00Z", "timestamp": 1693267200000}}, {"DOI": "10.12688/f1000research.131306.2", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2023, 8, 29]], "date-time": "2023-08-29T00:00:00Z", "timestamp": 1693267200000}}]    1
[{"DOI": "10.12688/f1000research.131306.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2023, 5, 16]], "date-time": "2023-05-16T00:00:00Z", "timestamp": 1684195200000}}]                                                                                                                                                                                                                                   1
[{"DOI": "10.12688/f1000research.12301.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2017, 12, 8]], "date-time": "2017-12-08T00:00:00Z", "timestamp": 1512691200000}}]                                                                                                                                                                                                                                    1
[{"DOI": "10.12688/f1000research.12802.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2017, 12, 22]], "date-time": "2017-12-22T00:00:00Z", "timestamp": 1513900800000}}]                                                                                                                                                                                                                                   1
[{"DOI": "10.12688/f1000research.127990.1", "label": "New version", "source": "publisher", "type": "new_version", "updated": {"date-parts": [[2023, 5, 16]], "date-time": "2023-05-16T00:00:00Z", "timestamp": 1684195200000}}]                                                                                                                                                                                                                                   1
Name: count, Length: 8898, dtype: int64

# build parent_index and long_full file

In [6]:
import os
import json
import duckdb
import pandas as pd

def build_parent_index_and_long_full_duckdb(
    df: pd.DataFrame,
    *,
    out_dir: str = "outputs",
    record_id_col: str = "record_id",
    server_col: str = "server_name",
    doi_col: str = "doi",
    url_col: str = "landing_page_url",
    title_col: str = "title",
    authors_col: str = "authors_flat",
    date_col: str = "date_first_seen",
    year_col: str = "publication_year_first_seen",
    group_id_col: str = "dup_group_id",
    # outputs
    long_full_name: str = "dedupe_clusters_long_full.parquet",
    parent_index_name: str = "parent_version_index_full.parquet",
    metrics_name: str = "dedupe_full_metrics.json",
):
    """
    Rules:
      - singleton rows: parent = itself
      - clustered rows: parent = oldest in cluster (date_col ASC, tie record_id ASC)
      - group id for full universe: dup_group_id_full = COALESCE(dup_group_id, record_id)

    Outputs (in out_dir):
      - dedupe_clusters_long_full.parquet  (ALL rows, includes parent_record_id_selected, is_parent_selected, group_size)
      - parent_version_index_full.parquet  (ONE row per group, with parent info + members lists)
      - dedupe_full_metrics.json
    """
    os.makedirs(out_dir, exist_ok=True)
    con = duckdb.connect(database=":memory:")
    con.execute("PRAGMA threads=8;")          # tune if needed
    con.execute("PRAGMA memory_limit='16GB';")# tune if needed

    # Register dataframe
    con.register("df_in", df)

    # -------------
    # 0) Build a stable "full" group id (clusters + singletons)
    # -------------
    # Note: we compute parent per group using window functions.
    # Parent selection: MIN_BY(record_id, sort_key) doesn't exist in DuckDB,
    # but we can do FIRST_VALUE over an ordered window.
    con.execute(f"""
        CREATE OR REPLACE TEMP VIEW base AS
        SELECT
            *,
            COALESCE(CAST({group_id_col} AS VARCHAR), CAST({record_id_col} AS VARCHAR)) AS dup_group_id_full,
            TRY_CAST({date_col} AS TIMESTAMP) AS dt,
            TRY_CAST({record_id_col} AS BIGINT) AS rid_num,
            NULLIF(TRIM(CAST({doi_col} AS VARCHAR)), '') AS doi_clean,
            NULLIF(TRIM(CAST({server_col} AS VARCHAR)), '') AS server_clean
        FROM df_in
    """)

    # -------------
    # 1) Create long_full (ALL rows)
    #    parent_record_id_selected = oldest record_id within dup_group_id_full
    # -------------
    con.execute(f"""
        CREATE OR REPLACE TEMP VIEW long_full AS
        SELECT
            -- keep original columns
            b.*,

            -- selected parent per group
            FIRST_VALUE(CAST({record_id_col} AS VARCHAR)) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_record_id_selected,

            -- parent metadata (from the chosen parent row)
            FIRST_VALUE(CAST({server_col} AS VARCHAR)) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_server_name_selected,

            FIRST_VALUE(CAST({doi_col} AS VARCHAR)) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_doi_selected,


            -- add ------------
            FIRST_VALUE(CAST({url_col} AS VARCHAR)) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_url_selected,
            
            FIRST_VALUE(CAST({title_col} AS VARCHAR)) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_title_selected,
            
            FIRST_VALUE(CAST({authors_col} AS VARCHAR)) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_authors_selected,

            -- ---------
    

            FIRST_VALUE(dt) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_date_selected,

            FIRST_VALUE(CAST({year_col} AS VARCHAR)) OVER (
                PARTITION BY dup_group_id_full
                ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
            ) AS parent_year_selected,

            -- is this row the selected parent?
            CASE
              WHEN CAST({record_id_col} AS VARCHAR) =
                   FIRST_VALUE(CAST({record_id_col} AS VARCHAR)) OVER (
                      PARTITION BY dup_group_id_full
                      ORDER BY dt ASC NULLS LAST, CAST({record_id_col} AS VARCHAR) ASC
                   )
              THEN TRUE ELSE FALSE
            END AS is_parent_selected,

            COUNT(*) OVER (PARTITION BY dup_group_id_full) AS group_size
        FROM base b
    """)

    # Export full long table
    long_path = os.path.join(out_dir, long_full_name)
    con.execute(f"COPY long_full TO '{long_path}' (FORMAT 'parquet');")

    # -------------
    # 2) Build parent_version_index_full (ONE row per group)
    #    Includes lists (record_ids, dois, servers with counts), first/last version dates, etc.
    # -------------
    # a) servers with counts as "ServerA (12); ServerB (3)"
    con.execute(f"""
        CREATE OR REPLACE TEMP VIEW servers_counts AS
        SELECT
            dup_group_id_full,
            CAST({server_col} AS VARCHAR) AS server_name,
            COUNT(*) AS n
        FROM long_full
        GROUP BY 1, 2
    """)

    con.execute("""
        CREATE OR REPLACE TEMP VIEW servers_counts_str AS
        SELECT
            dup_group_id_full,
            STRING_AGG(server_name || ' (' || CAST(n AS VARCHAR) || ')', '; ' ORDER BY n DESC, server_name ASC) AS servers_with_counts
        FROM servers_counts
        GROUP BY 1
    """)

    # b) most recent version server(s): if multiple on same max date → join with ';'
    con.execute("""
        CREATE OR REPLACE TEMP VIEW max_dt AS
        SELECT dup_group_id_full, MAX(dt) AS max_dt
        FROM long_full
        GROUP BY 1
    """)

    con.execute(f"""
        CREATE OR REPLACE TEMP VIEW most_recent_servers AS
        SELECT
            l.dup_group_id_full,
            STRING_AGG(DISTINCT CAST(l.{server_col} AS VARCHAR), '; ' ORDER BY CAST(l.{server_col} AS VARCHAR))
              AS most_recent_server_names
        FROM long_full l
        JOIN max_dt m
          ON l.dup_group_id_full = m.dup_group_id_full
         AND l.dt = m.max_dt
        GROUP BY 1
    """)

    # c) parent index
    parent_path = os.path.join(out_dir, parent_index_name)
    con.execute(f"""
        COPY (
            SELECT
                l.dup_group_id_full,

                l.parent_record_id_selected AS parent_record_id,
                l.parent_server_name_selected AS parent_server_name,
                l.parent_doi_selected       AS parent_doi,
                l.parent_url_selected       AS parent_url,
                l.parent_title_selected     AS parent_title,
                l.parent_authors_selected   AS parent_authors,
                l.parent_date_selected      AS parent_date_first_seen,
                l.parent_year_selected      AS parent_year_first_seen,

                STRING_AGG(DISTINCT CAST(l.{record_id_col} AS VARCHAR), '; '
                           ORDER BY CAST(l.{record_id_col} AS VARCHAR)) AS version_record_ids,

                -- cleaned DOI list (sorted, skips null/empty)
                STRING_AGG(l.doi_clean, '; ' ORDER BY l.doi_clean)
                    FILTER (WHERE l.doi_clean IS NOT NULL) AS version_dois,

                s.servers_with_counts,

                MAX(l.group_size) AS total_versions,
                MIN(l.dt) AS first_version_date,
                MAX(l.dt) AS last_version_date,

                mr.most_recent_server_names AS most_recent_version_servers

            FROM long_full l
            LEFT JOIN servers_counts_str s USING(dup_group_id_full)
            LEFT JOIN most_recent_servers mr USING(dup_group_id_full)
            GROUP BY
                l.dup_group_id_full,
                l.parent_record_id_selected,
                l.parent_server_name_selected,
                l.parent_doi_selected,
                l.parent_url_selected,
                l.parent_title_selected,
                l.parent_authors_selected,
                l.parent_date_selected,
                l.parent_year_selected,
                s.servers_with_counts,
                mr.most_recent_server_names
        )
        TO '{parent_path}' (FORMAT 'parquet');
    """)


    # -------------
    # 3) Metrics
    # -------------
    total_rows = con.execute("SELECT COUNT(*) FROM base").fetchone()[0]
    clustered_rows = con.execute(f"SELECT COUNT(*) FROM base WHERE {group_id_col} IS NOT NULL").fetchone()[0]
    singleton_rows = total_rows - clustered_rows

    clusters = con.execute(f"SELECT COUNT(DISTINCT CAST({group_id_col} AS VARCHAR)) FROM base WHERE {group_id_col} IS NOT NULL").fetchone()[0]
    groups_full = con.execute("SELECT COUNT(DISTINCT dup_group_id_full) FROM base").fetchone()[0]

    # sanity checks
    long_rows = con.execute("SELECT COUNT(*) FROM long_full").fetchone()[0]
    parent_rows = con.execute("SELECT COUNT(DISTINCT dup_group_id_full) FROM long_full").fetchone()[0]

    metrics = {
        "total_rows": int(total_rows),
        "clustered_rows_has_dup_group_id": int(clustered_rows),
        "singleton_rows_no_dup_group_id": int(singleton_rows),
        "clusters_distinct_dup_group_id": int(clusters),
        "groups_full_clusters_plus_singletons": int(groups_full),
        "long_full_rows_written": int(long_rows),
        "parent_index_rows_written": int(parent_rows),
    }

    # write metrics json
    metrics_path = os.path.join(out_dir, metrics_name)
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    return {
        "long_full_path": long_path,
        "parent_index_path": parent_path,
        "metrics_path": metrics_path,
        "metrics": metrics,
    }

In [7]:
result = build_parent_index_and_long_full_duckdb(
    df=data,          # or data_out after unify steps
    out_dir="outputs_new/parent",
    group_id_col="dup_group_id",  # or "dup_group_id_merged" if you renamed it
    date_col="date_first_seen",
)

result["metrics"]

{'total_rows': 8087418,
 'clustered_rows_has_dup_group_id': 1114453,
 'singleton_rows_no_dup_group_id': 6972965,
 'clusters_distinct_dup_group_id': 496119,
 'groups_full_clusters_plus_singletons': 7469084,
 'long_full_rows_written': 8087418,
 'parent_index_rows_written': 7469084}

In [8]:
result

{'long_full_path': 'outputs_new/parent/dedupe_clusters_long_full.parquet',
 'parent_index_path': 'outputs_new/parent/parent_version_index_full.parquet',
 'metrics_path': 'outputs_new/parent/dedupe_full_metrics.json',
 'metrics': {'total_rows': 8087418,
  'clustered_rows_has_dup_group_id': 1114453,
  'singleton_rows_no_dup_group_id': 6972965,
  'clusters_distinct_dup_group_id': 496119,
  'groups_full_clusters_plus_singletons': 7469084,
  'long_full_rows_written': 8087418,
  'parent_index_rows_written': 7469084}}

In [9]:
import duckdb

con = duckdb.connect()

long_path = "outputs_new/parent/dedupe_clusters_long_full.parquet"
parent_path = "outputs_new/parent/parent_version_index_full.parquet"

In [10]:
long_path

'outputs_new/parent/dedupe_clusters_long_full.parquet'

In [11]:
parent_path

'outputs_new/parent/parent_version_index_full.parquet'

In [12]:
juan = con.sql(f"""
SELECT *
FROM '{parent_path}'
WHERE total_versions > 1
ORDER BY RANDOM()
LIMIT 10
""").df()

juan#.shape[0]

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers
0,crossref::10.1101/2020.11.04.368571,crossref::10.1101/2020.11.04.368571,bioRxiv,10.1101/2020.11.04.368571,http://biorxiv.org/lookup/doi/10.1101/2020.11....,Temporal pattern and synergy influence activit...,"Miningou Zobon, Nadiatou T.; Jędrzejewska-Szme...",2020-11-04,2020,crossref::10.1101/2020.11.04.368571; crossref:...,10.1101/2020.11.04.368571; 10.7554/elife.64644,bioRxiv (1); eLife (1),2,2020-11-04,2021-08-10,eLife
1,datacite::10.5281/zenodo.16884622,datacite::10.5281/zenodo.16884621,Zenodo,10.5281/zenodo.16884621,https://zenodo.org/doi/10.5281/zenodo.16884621,Emergent Yang–Mills Kinetics from Block–Holono...,"HilLokk, Axun",2025-08-16,2025,datacite::10.5281/zenodo.16884621; datacite::1...,10.5281/zenodo.16884621; 10.5281/zenodo.16884622,Zenodo (2),2,2025-08-16,2025-08-16,Zenodo
2,datacite::10.17613/9f8v-ef80,datacite::10.17613/9f8v-ef80,Humanities Commons CORE,10.17613/9f8v-ef80,https://hcommons.org/deposits/item/hc:59021/,“Runenoefeningen. De Oudgermanistiek in Leidse...,"Porck, Thijs",2023-08-22,2023,datacite::10.17613/26dap-06s05; datacite::10.1...,10.17613/26dap-06s05; 10.17613/9f8v-ef80,Humanities Commons CORE (2),2,2023-08-22,2024-07-19,Humanities Commons CORE
3,datacite::10.17613/7hzs-5h31,datacite::10.17613/7hzs-5h31,Humanities Commons CORE,10.17613/7hzs-5h31,https://works.hcommons.org/doi/10.17613/7hzs-5h31,Callable Range Accrual Note,"Xiao, Tim",2021-09-20,2021,datacite::10.17613/74dax-mgp47; datacite::10.1...,10.17613/74dax-mgp47; 10.17613/7hzs-5h31,Humanities Commons CORE (2),2,2021-09-20,2024-07-19,Humanities Commons CORE
4,crossref::10.2139/ssrn.5325713,crossref::10.2139/ssrn.5325713,SSRN,10.2139/ssrn.5325713,https://www.ssrn.com/abstract=5325713,Immune Response to Co-Administration of Bovine...,"Palphramand, Kate L.; Anderson, Paul; Bellamy...",2025-01-01,2025,crossref::10.1101/2025.02.12.637632; crossref:...,10.1101/2025.02.12.637632; 10.2139/ssrn.5325713,SSRN (1); bioRxiv (1),2,2025-01-01,2025-02-15,bioRxiv
5,openalex::W3121130150,openalex::W3121130150,RePEc: Research Papers in Economics,None,None,Equivalence of ten different methods for valui...,Pablo Fernández,2003-01-01,2003,crossref::10.2139/ssrn.367161; openalex::W3121...,10.2139/ssrn.367161,RePEc: Research Papers in Economics (1); SSRN (1),2,2003-01-01,2004-05-06,SSRN
6,openalex::W2288614251,openalex::W2288614251,EconStor Preprints,10.1007/s10273-015-1784-0,http://hdl.handle.net/10419/111310,Kopfpauschale beerdigt: Gesetzliche Krankenver...,Jürgen Wasem,2015-01-01,2015,openalex::W2288614251; openalex::W2409575597; ...,10.1007/s10273-015-1784-0; 10.1007/s10273-015-...,EconStor Preprints (3),3,2015-01-01,2015-01-01,EconStor Preprints
7,crossref::10.2139/ssrn.4080961,crossref::10.2139/ssrn.4080961,SSRN,10.2139/ssrn.4080961,https://www.ssrn.com/abstract=4080961,Dislocation Density Transients and Saturation ...,"Warwick, Andrew Ralph; Thomas, Rhys; Boleining...",2022-01-01,2022,crossref::10.2139/ssrn.4080961; datacite::10.4...,10.2139/ssrn.4080961; 10.48550/arxiv.2304.03084,SSRN (1); arXiv (1),2,2022-01-01,2023-04-07,arXiv
8,crossref::10.26434/chemrxiv-2022-07q8z,crossref::10.26434/chemrxiv-2022-07q8z,ChemRxiv,10.26434/chemrxiv-2022-07q8z,https://chemrxiv.org/engage/chemrxiv/article-d...,Understanding Nonlinear Composition Dependency...,"Suzuki, Nozomu",2022-04-13,2022,crossref::10.26434/chemrxiv-2022-07q8z; crossr...,10.26434/chemrxiv-2022-07q8z; 10.26434/chemrxi...,ChemRxiv (4),4,2022-04-13,2022-07-12,ChemRxiv
9,datacite::10.22004/ag.econ.156126,datacite::10.22004/ag.econ.156126,AgEcon Search,10.22004/ag.econ.156126,https://ageconsearch.umn.edu/record/156126,Agroecologia e Agricultura Familiar na Região ...,"Assis, Renato Linhares De; Romeiro, Ademar Rib...",2019-08-24,2019,datacite::10.22004/ag.econ.156126; datacite::1...,10.22004/ag.econ.156126; 10.22004/ag.econ.341961,AgEcon Search (2),2,2019-08-24,2024-04-24,AgEcon Search

# exploration

In [13]:
len(long_path)

52

In [14]:
len(parent_path)

52

In [15]:
juan = con.sql(f"""
SELECT *
FROM '{parent_path}'
WHERE total_versions > 1
ORDER BY RANDOM()
LIMIT 10
""").df()

juan#.shape[0]

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers
0,crossref::10.31235/osf.io/msndr,crossref::10.31235/osf.io/msndr,SocArXiv,10.31235/osf.io/msndr,https://osf.io/msndr_v1,Conversation Analysis Tool as an Effective Mea...,"Kokhan, Roksoliana; Matsevko-Bekerska, Lidiia;...",2021-01-13,2021,crossref::10.2139/ssrn.3764282; crossref::10.3...,10.2139/ssrn.3764282; 10.31235/osf.io/msndr,SSRN (1); SocArXiv (1),2,2021-01-13,2021-03-09,SSRN
1,crossref::10.31234/osf.io/rb3g4,crossref::10.31234/osf.io/rb3g4,PsyArXiv,10.31234/osf.io/rb3g4,https://osf.io/rb3g4_v1,"Urgent, Hurry up!!! Perceived Time Pressure Af...","Urry, Heather L.; Plonski, Paul E.; Patel, Prs...",2025-01-15,2025,crossref::10.31234/osf.io/rb3g4; crossref::10....,10.31234/osf.io/rb3g4; 10.31234/osf.io/rb3g4_v...,PsyArXiv (4),4,2025-01-15,2025-11-07,PsyArXiv
2,crossref::10.31227/osf.io/8q264,crossref::10.31227/osf.io/8q264,INA-Rxiv,10.31227/osf.io/8q264,https://osf.io/8q264_v1,Efektivitas Peran ASEAN dalam Mengatasi Masala...,"Zulfikar, Achmad",2017-12-05,2017,crossref::10.31227/osf.io/8q264; datacite::10....,10.17605/osf.io/8q264; 10.31227/osf.io/8q264,INA-Rxiv (1); Open Science Framework (1),2,2017-12-05,2017-12-05,INA-Rxiv; Open Science Framework
3,crossref::10.2139/ssrn.3196761,crossref::10.2139/ssrn.3196761,SSRN,10.2139/ssrn.3196761,https://www.ssrn.com/abstract=3196761,The Micro and Macro of Managerial Beliefs,"Barrero, Jose Maria",2018-06-25,2018,crossref::10.2139/ssrn.3196761; crossref::10.3...,10.2139/ssrn.3196761; 10.31235/osf.io/fctsb,SSRN (1); SocArXiv (1),2,2018-06-25,2020-04-15,SocArXiv
4,crossref::10.2139/ssrn.3670493,crossref::10.2139/ssrn.3670493,SSRN,10.2139/ssrn.3670493,https://www.ssrn.com/abstract=3670493,Taking it to the Limit: Effects of Increased S...,"Black, Sandra; Denning, Jeffrey; Dettling, Lis...",2020-08-10,2020,crossref::10.2139/ssrn.3670493; crossref::10.2...,10.2139/ssrn.3670493; 10.2139/ssrn.4331400,SSRN (2),2,2020-08-10,2023-01-20,SSRN
5,crossref::10.2139/ssrn.5174591,crossref::10.2139/ssrn.5174591,SSRN,10.2139/ssrn.5174591,https://www.ssrn.com/abstract=5174591,Analyzing the Successful Incompetent to Be Exe...,"Su, I-An; Blume, John H.; Ceci, Stephen J",2025-01-01,2025,crossref::10.20944/preprints202501.2261.v1; cr...,10.20944/preprints202501.2261.v1; 10.2139/ssrn...,Preprints.org (1); SSRN (1),2,2025-01-01,2025-01-30,Preprints.org
6,crossref::10.32388/6rz1dg,crossref::10.32388/6rz1dg,Qeios,10.32388/6rz1dg,https://www.qeios.com/read/6RZ1DG,The stinger is used as a defense tool (Insecta...,"Marchiori, Carlos Henrique",2024-03-21,2024,crossref::10.32388/6rz1dg; crossref::10.32388/...,10.32388/6rz1dg; 10.32388/6rz1dg.2,Qeios (2),2,2024-03-21,2024-03-27,Qeios
7,datacite::10.5281/zenodo.17737785,datacite::10.5281/zenodo.17737785,Zenodo,10.5281/zenodo.17737785,https://zenodo.org/doi/10.5281/zenodo.17737785,The Law of the Reactive Universe: A Universal ...,"Avetisova, Yulia",2025-11-27,2025,datacite::10.5281/zenodo.17737785; datacite::1...,10.5281/zenodo.17737785; 10.5281/zenodo.17737786,Zenodo (2),2,2025-11-27,2025-11-27,Zenodo
8,crossref::10.20944/preprints202405.1883.v1,crossref::10.20944/preprints202405.1883.v1,Preprints.org,10.20944/preprints202405.1883.v1,https://www.preprints.org/manuscript/202405.18...,PAE: LLM-based Product Attribute Extraction fo...,"Sinha, Apurva; Gujral, Ekta",2024-05-29,2024,crossref::10.20944/preprints202405.1883.v1; da...,10.20944/preprints202405.1883.v1; 10.48550/arx...,Preprints.org (1); arXiv (1),2,2024-05-29,2024-05-29,Preprints.org; arXiv
9,openalex::W2139950087,openalex::W2139950087,RePEc: Research Papers in Economics,10.22004/ag.econ.19298,https://ageconsearch.umn.edu/bitstream/19298/1...,Three-Dimensional Efficient Portfolio Frontier...,Hikaru Hanawa Peterson; Bryan W. Schurle; Mich...,2005-01-01,2005,datacite::10.22004/ag.econ.19298; openalex::W2...,10.22004/ag.econ.19298; 10.22004/ag.econ.19298,AgEcon Search (1); RePEc: Research Papers in E...,2,2005-01-01,2019-08-24,AgEcon Search

In [16]:
juan = con.sql(f"""
SELECT *
FROM '{parent_path}'
WHERE total_versions > 1
ORDER BY RANDOM()
LIMIT 10
""").df()

juan#.shape[0]

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers
0,crossref::10.21203/rs.3.rs-34753/v1,crossref::10.21203/rs.3.rs-34753/v1,Research Square,10.21203/rs.3.rs-34753/v1,https://www.researchsquare.com/article/rs-3475...,Identification of infrasonic and seismic compo...,"Kurokawa, Aika K.; Ichihara, Mie",2020-06-16,2020,crossref::10.21203/rs.3.rs-34753/v1; crossref:...,10.21203/rs.3.rs-34753/v1; 10.21203/rs.3.rs-34...,Research Square (2),2,2020-06-16,2020-09-04,Research Square
1,crossref::10.21203/rs.3.rs-22551/v1,crossref::10.21203/rs.3.rs-22551/v1,Research Square,10.21203/rs.3.rs-22551/v1,https://www.researchsquare.com/article/rs-2255...,Measurement of CSF core Alzheimer Disease biom...,"Bellomo, Giovanni; Cataldi, Samuela; Paciotti,...",2020-04-15,2020,crossref::10.21203/rs.3.rs-22551/v1; crossref:...,10.21203/rs.3.rs-22551/v1; 10.21203/rs.3.rs-22...,Research Square (2),2,2020-04-15,2020-07-02,Research Square
2,crossref::10.2139/ssrn.3073777,crossref::10.2139/ssrn.3073777,SSRN,10.2139/ssrn.3073777,https://www.ssrn.com/abstract=3073777,Size-Related Premiums,"de Oliveira Souza, Thiago",2017-11-21,2017,crossref::10.2139/ssrn.3073777; crossref::10.2...,10.2139/ssrn.3073777; 10.2139/ssrn.3165423,SSRN (2),2,2017-11-21,2018-05-05,SSRN
3,crossref::10.22541/au.165400023.33520194/v1,crossref::10.22541/au.165400023.33520194/v1,Authorea Inc.,10.22541/au.165400023.33520194/v1,https://www.authorea.com/users/486147/articles...,Prescribing trends in older patients with mult...,"McCarthy, Caroline; Flood, Michelle; Clyne, Ba...",2022-05-31,2022,crossref::10.22541/au.165400023.33520194/v1; c...,10.22541/au.165400023.33520194/v1; 10.22541/au...,Authorea Inc. (2),2,2022-05-31,2022-07-27,Authorea Inc.
4,openalex::W4298289113,openalex::W4298289113,HAL,None,https://hal.science/hal-01011151,Procédé de préparation d'une couche mince à hé...,Guillaume Wantz; Lionel Derue; Olivier J. Daut...,2012-09-21,2012,openalex::W4296279076; openalex::W4298289113,None,HAL (2),2,2012-09-21,2013-01-01,HAL
5,datacite::10.5281/zenodo.17990822,datacite::10.5281/zenodo.17990821,Zenodo,10.5281/zenodo.17990821,https://zenodo.org/doi/10.5281/zenodo.17990821,PARKINSON LANCET.docx,"Choi, Il Woong",2025-12-19,2025,datacite::10.5281/zenodo.17990821; datacite::1...,10.5281/zenodo.17990821; 10.5281/zenodo.17990822,Zenodo (2),2,2025-12-19,2025-12-19,Zenodo
6,crossref::10.2139/ssrn.4448251,crossref::10.2139/ssrn.4448251,SSRN,10.2139/ssrn.4448251,https://www.ssrn.com/abstract=4448251,Judging Nudging: Understanding the Welfare Eff...,"List, John A.; Rodemeier, Matthias; Roy, Sutan...",2023-05-16,2023,crossref::10.2139/ssrn.4448251; crossref::10.2...,10.2139/ssrn.4448251; 10.2139/ssrn.4450082,SSRN (2),2,2023-05-16,2023-05-18,SSRN
7,openalex::W3192651026,openalex::W3192651026,HAL,None,https://hal.science/hal-03417907,(Se) Trans-Former par le travail,Najoua Mohib; Solveig Fernagu,2021-07-01,2021,openalex::W3192651026; openalex::W3208110594,None,HAL (2),2,2021-07-01,2021-11-04,HAL
8,crossref::10.21203/rs.3.rs-30090/v1,crossref::10.21203/rs.3.rs-30090/v1,Research Square,10.21203/rs.3.rs-30090/v1,https://www.researchsquare.com/article/rs-3009...,Homocysteine During the Third Trimester is a R...,"Chen, Sha; Shen, Hong; Cheng, Weiwei; Zhao, Xu...",2020-05-21,2020,crossref::10.21203/rs.3.rs-30090/v1; crossref:...,10.21203/rs.3.rs-30090/v1; 10.21203/rs.3.rs-30...,Research Square (2),2,2020-05-21,2020-09-02,Research Square
9,crossref::10.21203/rs.3.rs-690329/v1,crossref::10.21203/rs.3.rs-690329/v1,Research Square,10.21203/rs.3.rs-690329/v1,https://www.researchsquare.com/article/rs-6903...,A techno-economic and financial analysis of a ...,"Shivakumar, Abhishek; Kruitwagen, Lucas; Weins...",2021-07-08,2021,crossref::10.21203/rs.3.rs-690329/v1; crossref...,10.21203/rs.3.rs-690329/v1; 10.21203/rs.3.rs-6...,Research Square (2),2,2021-07-08,2021-07-13,Research Square

In [17]:
juan.iloc[8]

dup_group_id_full                            crossref::10.21203/rs.3.rs-30090/v1
parent_record_id                             crossref::10.21203/rs.3.rs-30090/v1
parent_server_name                                               Research Square
parent_doi                                             10.21203/rs.3.rs-30090/v1
parent_url                     https://www.researchsquare.com/article/rs-3009...
parent_title                   Homocysteine During the Third Trimester is a R...
parent_authors                 Chen, Sha; Shen, Hong; Cheng, Weiwei; Zhao, Xu...
parent_date_first_seen                                       2020-05-21 00:00:00
parent_year_first_seen                                                      2020
version_record_ids             crossref::10.21203/rs.3.rs-30090/v1; crossref:...
version_dois                   10.21203/rs.3.rs-30090/v1; 10.21203/rs.3.rs-30...
servers_with_counts                                          Research Square (2)
total_versions                                                                 2
first_version_date                                           2020-05-21 00:00:00
last_version_date                                            2020-09-02 00:00:00
most_recent_version_servers                                      Research Square
Name: 8, dtype: object

In [18]:
juan.servers_with_counts[8]

'Research Square (2)'

## to look at

- same preprint posted to two servers same day (like RS, posted automatically)
- same preprint at datacite and crossref (moved over from one agency to the other?)

In [19]:
juan.iloc[0].version_record_ids

'crossref::10.21203/rs.3.rs-34753/v1; crossref::10.21203/rs.3.rs-34753/v2'

In [20]:
long_path_df = con.sql(f"""
SELECT *
FROM '{long_path}'
ORDER BY RANDOM()
LIMIT 100000
""").df()

In [21]:
long_path_df

,record_id,server_name,backend,doi,doi_url,landing_page_url,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year_first_seen,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup,dup_group_id_full,dt,rid_num,doi_clean,server_clean,parent_record_id_selected,parent_server_name_selected,parent_doi_selected,parent_url_selected,parent_title_selected,parent_authors_selected,parent_date_selected,parent_year_selected,is_parent_selected,group_size
0,datacite::10.48550/arxiv.2406.01775,arXiv,datacite,10.48550/arxiv.2406.01775,https://doi.org/10.48550/arxiv.2406.01775,https://arxiv.org/abs/2406.01775,OLoRA: Orthonormal Low-Rank Adaptation of Larg...,"Büyükakyüz, Kerim",None,None,[],2,None,,,,false,<NA>,<NA>,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2024-06-05,2024,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,datacite::10.48550/arxiv.2406.01775,2024-06-05,<NA>,10.48550/arxiv.2406.01775,arXiv,datacite::10.48550/arxiv.2406.01775,arXiv,10.48550/arxiv.2406.01775,https://arxiv.org/abs/2406.01775,OLoRA: Orthonormal Low-Rank Adaptation of Larg...,"Büyükakyüz, Kerim",2024-06-05,2024,True,1
1,openalex::W2276419592,EconStor Preprints,openalex,None,None,http://hdl.handle.net/10419/198167,THE ROLE OF THE ENERGY COMMUNITY WITHIN THE EU...,Victoria Musteaţă,None,None,None,None,None,None,None,None,None,<NA>,<NA>,None,None,parent,2012-06-01,2012,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,openalex::W2276419592,2012-06-01,<NA>,None,EconStor Preprints,openalex::W2276419592,EconStor Preprints,None,http://hdl.handle.net/10419/198167,THE ROLE OF THE ENERGY COMMUNITY WITHIN THE EU...,Victoria Musteaţă,2012-06-01,2012,True,1
2,crossref::10.1101/2023.02.24.23286400,medRxiv,crossref,10.1101/2023.02.24.23286400,https://doi.org/10.1101/2023.02.24.23286400,http://medrxiv.org/lookup/doi/10.1101/2023.02....,Use of cfDNA and exovesicle-DNA for the molecu...,"Lozano, Noelia; Samblas, Mercedes Gomez; Calab...",None,None,None,None,None,,,,false,<NA>,<NA>,None,None,parent,2023-02-26,2023,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,crossref::10.1101/2023.02.24.23286400,2023-02-26,<NA>,10.1101/2023.02.24.23286400,medRxiv,crossref::10.1101/2023.02.24.23286400,medRxiv,10.1101/2023.02.24.23286400,http://medrxiv.org/lookup/doi/10.1101/2023.02....,Use of cfDNA and exovesicle-DNA for the molecu...,"Lozano, Noelia; Samblas, Mercedes Gomez; Calab...",2023-02-26,2023,True,1
3,openalex::W148058745,RePEc: Research Papers in Economics,openalex,None,None,https://econpapers.repec.org/RePEc:cdp:diam06:074,ECONOMIA E REDE URBANA DO CENTRO-OESTE MINEIRO,Pedro Amaral; Luciana Luz; Rodrigo Simões,None,None,None,None,None,None,None,None,None,<NA>,<NA>,None,None,parent,2006-01-01,2006,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,openalex::W148058745,2006-01-01,<NA>,None,RePEc: Research Papers in Economics,openalex::W148058745,RePEc: Research Papers in Economics,None,https://econpapers.repec.org/RePEc:cdp:diam06:074,ECONOMIA E REDE URBANA DO CENTRO-OESTE MINEIRO,Pedro Amaral; Luciana Luz; Rodrigo Simões,2006-01-01,2006,True,1
4,crossref::10.2139/ssrn.4924826,SSRN,crossref,10.2139/ssrn.4924826,https://doi.org/10.2139/ssrn.4924826,https://www.ssrn.com/abstract=4924826,Mortality and Predictors of Mortality Among Co...,"Kimani, Teresia Njoki; Mutono, Nyamai; Makori...",None,None,None,None,None,,,,false,<NA>,<NA>,None,None,parent,2024-01-01,2024,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,crossref::10.2139/ssrn.4924826,2024-01-01,<NA>,10.2139/ssrn.4924826,SSRN,crossref::10.2139/ssrn.4924826,SSRN,10.2139/ssrn.4924826,https://www.ssrn.com/abstract=4924826,Mortality and Predictors of Mortality Among Co...,"Kimani, Teresia Njoki; Mutono, Nyamai; Makori...",2024-01-01,2024,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,datacite::10.48550/arxiv.1407.1233,arXiv,datacite,10.48550/arxiv.1407.1233,https://doi.org/10.48550/arxiv.1407.1233,https://arxiv.org/abs/1407.1233,Optimal alignments of longest common subsequen...,"Lember, Jüri; Matzinger, Heinrich; Vollmer, Anna",None,None,"[{""relatedIdentifier"": ""10.3150/13-bej522"", ""r...",1,None,10.3150/13-bej522,,,true,<NA>,<NA>,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2022-03-09,2022,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,datacite::10.48550/arxiv.1407.1233,2022-03-09,<NA>,10.48550/arxiv.1407.1233,arXiv,datacite::10.48550/arxiv.1407.1233,arXiv,10.48550/arxiv.1407.1233,https://arxiv.org/abs/1407.1233,Optimal alignments of longest common subsequen...,"Lember, Jüri; Matzinger, Heinrich; Vollmer, Anna",2022-03-09,2022,True,1
99996,crossref::10.2139/ssrn.5902827,SSRN,crossref,10.2139/ssrn.5902827,https://doi.org/10.2139/ssrn.5902827,https://www.ssrn.com/abstract=5902827,Pollen Vector Dynamics in a Cave Ecosystem und...,"SOLAK-AMET, Omer; TOSUNOGLU, Aycan",None,None,None,None,None,,,,false,<NA>,<NA>,None,None,parent,2025-01-01,2025,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,crossref::10.2139/ssrn.5902827,2025-01-01,<NA>,10.2139/ssrn.5902827,SSRN,crossref::10.2139/ssrn.5902827,SSRN,10.2139/ssrn.5902827,https://www.ssrn.com/abstract=5902827,Pollen Vector Dynamics in a Cave Ecosystem und...,"SOLAK-AMET, Omer; TOSUNOGLU, Aycan",2025-01-01,2025,True,1
99997,openalex::W4287560572,HAL,openalex,None,None,https://hal.science/hal-03106353,A la recherche d'un courant humaniste traversa...,Emmanuel Cordelier,Centre de droit des affaires,None,None,None,None,None,None,None,None,<NA>,<NA>,None,None,parent,2020-12-01,2020,parent,None,None,cordelier_emmanuel,a la recherche d un courant humaniste traversa...,cordelier|e,None,parent,None,None,parent,None,None,openalex::W4287560572,2020-12-01,<NA>,None,HAL,openalex::W4287560572,HAL,None,https://hal.science/hal-03106353,A la recherche d'un courant humaniste traversa...,Emmanuel Cordelier,2020-12-01,2020,True,1
99998,datacite::10.48550/arxiv.2507.03513,arXiv,datacite,10.48550/arxiv.2507.03513,https://doi.org/10.48550/arxiv.2507.03513,https://arxiv.org/abs/2507.03513,Magnetocalorics of singlet ground state induce...,"Thalmeier, Peter",None,None,"[{""relatedIdentifier"": ""10.1103/frrj-wxfg"", ""r...",2,None,10.1103/frrj-wxfg,,,true,<NA>,<NA>,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2025-07-08,2025,parent,None,None,peter_thalmeier,magnetocalorics of singlet ground state induce...,thalmeier|p,None,parent,None,None,parent,None,None,datacite::10.48550/arxiv.2507.03513,2025-07-08,<NA>,10.48550/arxiv.2507.03513,arXiv,datacite::10.48550/arxiv.2507.03513,arXiv,10.48550/arxiv.2507.03513,https://arxiv.org/abs/2507.03513,Magnetocalorics of singlet ground state induce...,"Thalmeier, Peter",2025-07-08,2025,True,1
99999,datacite::10.48550/arxiv.1406.5609,arXiv,datacite,10.48550/arxiv.1406.5609,https://doi.org/10.48550/arxiv.1406.5609,https://arxiv.org/abs/1406.5609,Cohomological invariants of algebraic groups a...,"Semenov, Nikita",None,None,[],2,None,,,,false,<NA>,<NA>,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2022-03-09,2022,parent,None,None,nikita_semenov,cohomological invariants of algebraic groups a...,semenov|n,None,parent,None,None,parent,None,None,datacite::10.48550/arxiv.1406.5609,2022-03-09,<NA>,10.48550/arxiv.1406.5609,arXiv,datacite::10.48550/arxiv.1406.5609,arXiv,10.48550/arxiv.1406.5609,https://arxiv.org/abs/1406.5609,Cohomological invariants of algebraic groups a...,"Semenov, Nikita",2022-03-09,2022,True,1

In [22]:
long_path_df.update_to_json[31]

In [23]:
long_path_df.published_version_ids_json.value_counts()

Series([], Name: count, dtype: Int64)

In [24]:
juan = con.sql(f"""
SELECT dup_group_id_full, server_name, COUNT(*) AS n
FROM '{long_path}'
GROUP BY 1, 2
ORDER BY n DESC
LIMIT 1000
""").df()

juan.groupby('server_name').size().nlargest(100)

server_name
Zenodo                                  537
AgEcon Search                           138
Preprints.org                            52
ResearchGate                             50
Open Science Framework                   32
SSRN                                     22
Cambridge Open Engage                    20
Qeios                                    18
PsyArXiv                                 15
INA-Rxiv                                 13
ChemRxiv                                 13
Research Square                          12
Humanities Commons CORE                   9
Thesis Commons                            8
HAL                                       7
Authorea Inc.                             7
TechRxiv                                  7
Covid-19 Preprints                        6
arXiv                                     5
RePEc: Research Papers in Economics       4
Nature Precedings                         3
UCL Open Environment                      2
ResearchHub                               2
Earth and Space Science Open Archive      2
APSA Preprints                            2
SocArXiv                                  2
PeerJ Preprints                           2
ART-Dok                                   1
Advance                                   1
AfricArXiv                                1
Law Archive                               1
Organic Eprints                           1
EconStor Preprints                        1
CrossAsia-Repository                      1
CERN document server                      1
F1000Research                             1
PropylaeumDok                             1
dtype: int64

In [25]:
con.sql(f"""
SELECT *
FROM '{long_path}'
WHERE dup_group_id_full IN (
    SELECT DISTINCT dup_group_id_full
    FROM '{long_path}'
    ORDER BY RANDOM()
    LIMIT 5
)
""").df()

,record_id,server_name,backend,doi,doi_url,landing_page_url,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year_first_seen,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup,dup_group_id_full,dt,rid_num,doi_clean,server_clean,parent_record_id_selected,parent_server_name_selected,parent_doi_selected,parent_url_selected,parent_title_selected,parent_authors_selected,parent_date_selected,parent_year_selected,is_parent_selected,group_size
0,datacite::10.48550/arxiv.1410.7823,arXiv,datacite,10.48550/arxiv.1410.7823,https://doi.org/10.48550/arxiv.1410.7823,https://arxiv.org/abs/1410.7823,Crossed products by Hilbert pro-C*-bimodules v...,"Joiţa, Maria",None,None,[],2,None,,,,false,<NA>,<NA>,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2022-03-09,2022,parent,None,None,joita_maria,crossed products by hilbert pro c bimodules ve...,joita|m,None,parent,None,None,parent,None,None,datacite::10.48550/arxiv.1410.7823,2022-03-09,<NA>,10.48550/arxiv.1410.7823,arXiv,datacite::10.48550/arxiv.1410.7823,arXiv,10.48550/arxiv.1410.7823,https://arxiv.org/abs/1410.7823,Crossed products by Hilbert pro-C*-bimodules v...,"Joiţa, Maria",2022-03-09,2022,True,1
1,datacite::10.48550/arxiv.1908.03147,arXiv,datacite,10.48550/arxiv.1908.03147,https://doi.org/10.48550/arxiv.1908.03147,https://arxiv.org/abs/1908.03147,Wasserstein stability of porous medium-type eq...,"De Ponti, Nicolò; Muratori, Matteo; Orrieri, C...",None,None,[],2,None,,,,false,<NA>,<NA>,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2022-02-27,2022,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,datacite::10.48550/arxiv.1908.03147,2022-02-27,<NA>,10.48550/arxiv.1908.03147,arXiv,datacite::10.48550/arxiv.1908.03147,arXiv,10.48550/arxiv.1908.03147,https://arxiv.org/abs/1908.03147,Wasserstein stability of porous medium-type eq...,"De Ponti, Nicolò; Muratori, Matteo; Orrieri, C...",2022-02-27,2022,True,1
2,datacite::10.48550/arxiv.2211.17035,arXiv,datacite,10.48550/arxiv.2211.17035,https://doi.org/10.48550/arxiv.2211.17035,https://arxiv.org/abs/2211.17035,Radial velocity confirmation of a hot super-Ne...,"Knudstrup, E.; Gandolfi, D.; Nowak, G.; Persso...",None,None,"[{""relatedIdentifier"": ""10.1093/mnras/stac3684...",1,None,10.1093/mnras/stac3684,,,true,<NA>,<NA>,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2022-12-02,2022,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,datacite::10.48550/arxiv.2211.17035,2022-12-02,<NA>,10.48550/arxiv.2211.17035,arXiv,datacite::10.48550/arxiv.2211.17035,arXiv,10.48550/arxiv.2211.17035,https://arxiv.org/abs/2211.17035,Radial velocity confirmation of a hot super-Ne...,"Knudstrup, E.; Gandolfi, D.; Nowak, G.; Persso...",2022-12-02,2022,True,1
3,crossref::10.32388/irhamh,Qeios,crossref,10.32388/irhamh,https://doi.org/10.32388/irhamh,https://www.qeios.com/read/definition/69288,Glottic Cancer pT0 TNM Finding v6 and v7,National Cancer Institute,None,None,None,None,None,,,,false,<NA>,<NA>,None,None,parent,2020-02-07,2020,parent,None,None,cancer_institute_national,glottic cancer pt0 tnm finding v6 and v7,institute|n,None,parent,None,None,parent,None,None,crossref::10.32388/irhamh,2020-02-07,<NA>,10.32388/irhamh,Qeios,crossref::10.32388/irhamh,Qeios,10.32388/irhamh,https://www.qeios.com/read/definition/69288,Glottic Cancer pT0 TNM Finding v6 and v7,National Cancer Institute,2020-02-07,2020,True,1
4,crossref::10.2139/ssrn.2714428,SSRN,crossref,10.2139/ssrn.2714428,https://doi.org/10.2139/ssrn.2714428,http://www.ssrn.com/abstract=2714428,The Impact of Board Internationalization on Ea...,"Hooghiemstra, Reggy; Hermes, Niels; Oxelheim, ...",None,None,None,None,None,,,,false,<NA>,<NA>,None,None,parent,2016-01-14,2016,parent,None,None,None,None,None,None,parent,None,None,parent,None,None,crossref::10.2139/ssrn.2714428,2016-01-14,<NA>,10.2139/ssrn.2714428,SSRN,crossref::10.2139/ssrn.2714428,SSRN,10.2139/ssrn.2714428,http://www.ssrn.com/abstract=2714428,The Impact of Board Internationalization on Ea...,"Hooghiemstra, Reggy; Hermes, Niels; Oxelheim, ...",2016-01-14,2016,True,1