In [1]:
import pandas as pd
# Set option to display all columns
pd.set_option('display.max_columns', None)

# import data

In [2]:
data = pd.read_pickle("outputs_new/dedupe_data_group_merge.pkl")
data

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
0,crossref::10.1002/essoar.10500000.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500000.1,https://doi.org/10.1002/essoar.10500000.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Long-term monitoring of land surface phenologi...,"Tsutsumida, Narumasa",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-05-24,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
1,crossref::10.1002/essoar.10500002.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500002.1,https://doi.org/10.1002/essoar.10500002.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Impact of spatial scale for phenological indic...,"Tsutsumida, Narumasa; Kaduk, Jörg",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-05-27,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
2,crossref::10.1002/essoar.10500004.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500004.1,https://doi.org/10.1002/essoar.10500004.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Observations of Low Latitude Red Aurora in Mex...,"Gonzalez-Esparza, J. Americo; Cuevas-Cardona, ...",Universidad Autónoma del Estado de Hidalgo,None,"{""is-preprint-of"": [{""asserted-by"": ""subject"",...",None,None,10.1029/2018sw001995,,,true,None,None,None,None,parent,2018-05-28,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
3,crossref::10.1002/essoar.10500007.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500007.1,https://doi.org/10.1002/essoar.10500007.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Pipeline oil fire detection with MODIS active ...,"Ogungbuyi, Michael Gbenga; Martinez, Peter; Ec...",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-05-30,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
4,crossref::10.1002/essoar.10500009.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500009.1,https://doi.org/10.1002/essoar.10500009.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Land Product Validation of MODIS Derived FPAR ...,"Sharp, Iain; Sanchez-Azofeifa, Arturo; Musilek...",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-06-05,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7905694,openalex::W999921877,RePEc: Research Papers in Economics,openalex,None,None,https://steconomice.uoradea.ro/anale/volume/20...,preprint,None,IDE sous l'influence du degré de l'intégration...,Simona-Gabriela Serbu Masca,Babeș-Bolyai University,RO,None,None,None,None,None,None,None,None,None,None,None,parent,2008-01-01,2008.0,2008,None,parent,None,None,gabriela_masca_serbu_simona,ide sous l influence du degre de l integration...,masca|s,None,parent,None,None,None,parent,None,None
7905695,openalex::W999947037,HAL,openalex,None,None,https://hal.science/hal-01922484,preprint,None,Building realistic potential patients queries ...,Lorraine Goeuriot; Wendy W. Chapman; Gareth Jf...,Laboratoire d'Informatique de Grenoble; Dublin...,FR; IE,None,None,None,None,None,None,None,None,None,None,None,parent,2014-01-01,2014.0,2014,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
7905696,openalex::W999974616,RePEc: Research Papers in Economics,openalex,None,None,https://EconPapers.repec.org/RePEc:cde:cdewps:19,preprint,None,Debt Financing with Limited Liability and Quan...,Krishnendu Ghosh Dastidar,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,1994-08-01,1994.0,1994,None,parent,None,None,dastidar_ghosh_krishnendu,debt financing with limited liability and quan...,dastidar|k,None,parent,None,None,None,parent,None,None
7905697,openalex::W999989114,HAL,openalex,None,None,https://hal.science/hal-01268467,preprint,None,Sustainable orchards' redesign: at the crossro...,Servane Penvern; Sylvaine Simon; Stéphane Bell...,Institut National de Recherche pour l'Agricult...,FR,None,None,None,None,None,None,None,None,None,None,None,parent,2012-07-01,2012.0,2012,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
7905698,openalex::W999989584,RePEc: Research Papers in Economics,openalex,None,None,http://thred.devecon.org/papers/2014/2014-018_...,preprint,None,When warm glow burns: Motivational (mis)alloca...,Gani Aldashev; Esteban Jaimovich; Thierry Verdier,University of Namur; University of Surrey; Éco...,BE; GB; BI; FR,None,None,None,None,None,None,None,None,None,None,None,parent,2015-02-01,2015.0,2015,None,parent,None,None,aldashev_gani;esteban_jaimovich;thierry_verdier,when warm glow burns motivational mis allocati...,aldashev|g;jaimovich|e;verdier|t,None,parent,None,None,None,parent,None,None

In [3]:
data['records_hierarchy'].value_counts()

records_hierarchy
parent                                                     7332492
parent - duplicate (SSRN)                                   127847
parent - duplicate (Zenodo)                                  98478
parent - duplicate (Research Square)                         59677
parent - duplicate (arXiv)                                   54767
                                                            ...
parent - duplicate (Sciencepaper Online)                         2
parent - duplicate (CoP)                                         1
parent - duplicate (Therapoid)                                   1
parent - duplicate (Prepublicaciones OpenCiencia)                1
parent - duplicate (Electron Colloquium Comput Complex)          1
Name: count, Length: 105, dtype: int64

In [4]:
data[data['dup_group_id'].isna()]

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
0,crossref::10.1002/essoar.10500000.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500000.1,https://doi.org/10.1002/essoar.10500000.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Long-term monitoring of land surface phenologi...,"Tsutsumida, Narumasa",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-05-24,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
1,crossref::10.1002/essoar.10500002.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500002.1,https://doi.org/10.1002/essoar.10500002.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Impact of spatial scale for phenological indic...,"Tsutsumida, Narumasa; Kaduk, Jörg",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-05-27,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
2,crossref::10.1002/essoar.10500004.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500004.1,https://doi.org/10.1002/essoar.10500004.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Observations of Low Latitude Red Aurora in Mex...,"Gonzalez-Esparza, J. Americo; Cuevas-Cardona, ...",Universidad Autónoma del Estado de Hidalgo,None,"{""is-preprint-of"": [{""asserted-by"": ""subject"",...",None,None,10.1029/2018sw001995,,,true,None,None,None,None,parent,2018-05-28,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
3,crossref::10.1002/essoar.10500007.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500007.1,https://doi.org/10.1002/essoar.10500007.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Pipeline oil fire detection with MODIS active ...,"Ogungbuyi, Michael Gbenga; Martinez, Peter; Ec...",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-05-30,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
4,crossref::10.1002/essoar.10500009.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500009.1,https://doi.org/10.1002/essoar.10500009.1,https://essopenarchive.org/doi/full/10.1002/es...,posted-content,preprint,Land Product Validation of MODIS Derived FPAR ...,"Sharp, Iain; Sanchez-Azofeifa, Arturo; Musilek...",None,None,None,None,None,,,,false,None,None,None,None,parent,2018-06-05,2018.0,2018,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7905694,openalex::W999921877,RePEc: Research Papers in Economics,openalex,None,None,https://steconomice.uoradea.ro/anale/volume/20...,preprint,None,IDE sous l'influence du degré de l'intégration...,Simona-Gabriela Serbu Masca,Babeș-Bolyai University,RO,None,None,None,None,None,None,None,None,None,None,None,parent,2008-01-01,2008.0,2008,None,parent,None,None,gabriela_masca_serbu_simona,ide sous l influence du degre de l integration...,masca|s,None,parent,None,None,None,parent,None,None
7905695,openalex::W999947037,HAL,openalex,None,None,https://hal.science/hal-01922484,preprint,None,Building realistic potential patients queries ...,Lorraine Goeuriot; Wendy W. Chapman; Gareth Jf...,Laboratoire d'Informatique de Grenoble; Dublin...,FR; IE,None,None,None,None,None,None,None,None,None,None,None,parent,2014-01-01,2014.0,2014,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
7905696,openalex::W999974616,RePEc: Research Papers in Economics,openalex,None,None,https://EconPapers.repec.org/RePEc:cde:cdewps:19,preprint,None,Debt Financing with Limited Liability and Quan...,Krishnendu Ghosh Dastidar,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,1994-08-01,1994.0,1994,None,parent,None,None,dastidar_ghosh_krishnendu,debt financing with limited liability and quan...,dastidar|k,None,parent,None,None,None,parent,None,None
7905697,openalex::W999989114,HAL,openalex,None,None,https://hal.science/hal-01268467,preprint,None,Sustainable orchards' redesign: at the crossro...,Servane Penvern; Sylvaine Simon; Stéphane Bell...,Institut National de Recherche pour l'Agricult...,FR,None,None,None,None,None,None,None,None,None,None,None,parent,2012-07-01,2012.0,2012,None,parent,None,None,None,None,None,None,parent,None,None,None,parent,None,None
7905698,openalex::W999989584,RePEc: Research Papers in Economics,openalex,None,None,http://thred.devecon.org/papers/2014/2014-018_...,preprint,None,When warm glow burns: Motivational (mis)alloca...,Gani Aldashev; Esteban Jaimovich; Thierry Verdier,University of Namur; University of Surrey; Éco...,BE; GB; BI; FR,None,None,None,None,None,None,None,None,None,None,None,parent,2015-02-01,2015.0,2015,None,parent,None,None,aldashev_gani;esteban_jaimovich;thierry_verdier,when warm glow burns motivational mis allocati...,aldashev|g;jaimovich|e;verdier|t,None,parent,None,None,None,parent,None,None

In [5]:
data["dup_group_id"] = (
    data["dup_group_id"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
    .fillna(data["record_id"])
)

In [6]:
data[data['dup_group_id'].isna()]

Empty DataFrame
Columns: [record_id, server_name, backend, doi, doi_url, landing_page_url, type_backend_raw, subtype_backend_raw, title, authors_flat, institutions_flat, countries_flat, relations_json, version_label, is_version_of, is_preprint_of, has_preprint, has_review, has_published_version, published_version_ids_json, version_of_ids_json, update_to_json, raw_relationships_json, records_hierarchy, date_first_seen, publication_year, publication_year_first_seen, raw_dates, records_hierarchy_backup, parent_record_id, dup_group_id, authors_fp_tokenbag, title_clean_v2, authors_fp_last_initial, authors_fp_last, records_hierarchy_dedupe_backup, parent_record_id_dedupe_backup, dup_group_id_dedupe_backup, has_version_dois, records_hierarchy_unify_version_backup, parent_record_id_unify_version_backup, dup_group_id_unify_version_backup]
Index: []

In [7]:
data['has_published_version'].value_counts()

has_published_version
false    4360810
true     1854806
Name: count, dtype: int64

In [8]:
data['published_version_ids_json'].value_counts()

Series([], Name: count, dtype: int64)

In [9]:
data['is_preprint_of'].value_counts()

is_preprint_of
                              4360810
10.5281/zenodo.17226274           410
10.5281/zenodo.15583046           384
10.31237/osf.io/yr86k             373
10.5281/zenodo.15832876           293
                               ...
10.1007/jhep12(2011)067             1
10.1515/rose.2011.021               1
10.1103/physrevd.85.014035          1
10.1017/s174392131200508x           1
10.1007/s00233-011-9370-2           1
Name: count, Length: 1773519, dtype: int64

In [10]:
data['is_version_of'].value_counts()

is_version_of
10.5281/zenodo.17226274           410
10.5281/zenodo.15583046           384
10.5281/zenodo.15832876           293
10.5281/zenodo.15164567           252
10.5281/zenodo.6784019            221
                                 ...
10.1093/mnras/stw1307               1
10.1051/0004-6361/201628569         1
10.1007/jhep07(2016)097             1
10.1103/physrevd.94.083514          1
10.17265/2159-5291/2015.02.002      1
Name: count, Length: 1512803, dtype: int64

# Build the 3 core files for preprint tracker

In [11]:
from __future__ import annotations

from pathlib import Path
from typing import Optional, Tuple, Dict
import pandas as pd
import numpy as np


def generate_tracker_files_from_dedupe_v2(
    df: pd.DataFrame,
    out_dir: str | Path = "outputs/tracker_data",
    *,
    # core cols
    server_col: str = "server_name",
    record_id_col: str = "record_id",
    group_id_col: str = "dup_group_id",
    hierarchy_col: str = "records_hierarchy",
    date_col: str = "date_first_seen",
    year_col: str = "publication_year_first_seen",
    has_published_col: str = "has_published_version",
    source_col: Optional[str] = None,

    # outputs
    write_csv: bool = True,
    write_xlsx: bool = False,
    return_frames: bool = True,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, Dict]:
    """
    Build tracker files from a deduped long table.

    Outputs:
      1) summary.csv
      2) yearly.csv                  -> wide, compatible with current app
      3) yearly_long_enriched.csv    -> new enriched yearly table
      4) clusters_summary.csv
      5) build_metrics.json

    Important modeling choices:
      - n_records: raw harvested row count
      - n_unique: unique dup_group_id count per server participation
      - n_is_version_of: unique clusters with cluster_size > 1 per server participation
      - n_published: unique clusters with any published version per server participation
      - yearly counts: computed from *parent rows only* to avoid double counting versions
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    required = [server_col, record_id_col, group_id_col]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    work = df.copy()

    # ---------------------------------------------------------
    # 0) Clean basics
    # ---------------------------------------------------------
    work[server_col] = work[server_col].astype("string").fillna("").str.strip()
    work[group_id_col] = work[group_id_col].astype("string").fillna("").str.strip()
    work[record_id_col] = work[record_id_col].astype("string").fillna("").str.strip()

    work = work[(work[server_col] != "") & (work[group_id_col] != "")].copy()

    # normalize published flag
    if has_published_col in work.columns:
        hp_raw = work[has_published_col]

        hp_norm = (
            hp_raw.astype("string")
            .str.strip()
            .str.lower()
            .map({
                "true": True, "false": False,
                "1": True, "0": False,
                "yes": True, "no": False,
                "y": True, "n": False
            })
        )

        # fallback for already boolean/numeric columns
        if hp_norm.notna().sum() == 0:
            hp_num = pd.to_numeric(hp_raw, errors="coerce")
            hp_norm = hp_num.map({1: True, 0: False})

        work[has_published_col] = hp_norm.fillna(False).astype(bool)
    else:
        work[has_published_col] = False

    # parse date
    if date_col in work.columns:
        work[date_col] = pd.to_datetime(work[date_col], errors="coerce")
    else:
        work[date_col] = pd.NaT

    # parse year
    if year_col in work.columns:
        y = pd.to_numeric(work[year_col], errors="coerce")
        work[year_col] = y.where((y >= 1000) & (y <= 3000)).round().astype("Int64")
    else:
        work[year_col] = pd.NA

    # ---------------------------------------------------------
    # 1) Build cluster-level summaries
    # ---------------------------------------------------------
    cluster_size = work.groupby(group_id_col, as_index=True).size().rename("cluster_size")
    n_servers = work.groupby(group_id_col)[server_col].nunique().rename("n_servers")
    cluster_has_published = work.groupby(group_id_col)[has_published_col].any().rename("cluster_has_published")

    # determine cluster parent
    if hierarchy_col in work.columns:
        h = work[hierarchy_col].astype("string").fillna("").str.lower().str.strip()
        is_parent = h.eq("parent")
    else:
        is_parent = pd.Series(False, index=work.index)

    parents = work[is_parent].copy()

    if parents.empty:
        tmp = work.sort_values(
            [group_id_col, date_col, record_id_col],
            ascending=[True, True, True],
            na_position="last"
        )
        parents = tmp.groupby(group_id_col, sort=False).head(1).copy()
    else:
        parents = parents.sort_values(
            [group_id_col, date_col, record_id_col],
            ascending=[True, True, True],
            na_position="last"
        )
        parents = parents.groupby(group_id_col, sort=False).head(1).copy()

    clusters_summary = (
        parents[[group_id_col, record_id_col, server_col, date_col, year_col]]
        .rename(columns={
            record_id_col: "parent_record_id",
            server_col: "parent_server_name",
            date_col: "parent_date_first_seen",
            year_col: "parent_year_first_seen",
        })
        .set_index(group_id_col)
        .join(cluster_size)
        .join(n_servers)
        .join(cluster_has_published)
        .reset_index()
    )

    clusters_summary["has_versions"] = clusters_summary["cluster_size"] > 1
    clusters_summary["is_cross_server"] = clusters_summary["n_servers"] > 1

    # ---------------------------------------------------------
    # 2) Summary per server
    # ---------------------------------------------------------
    n_records = work.groupby(server_col)[record_id_col].count().rename("n_records")
    n_unique = work.groupby(server_col)[group_id_col].nunique().rename("n_unique")

    version_clusters = set(
        clusters_summary.loc[clusters_summary["has_versions"], group_id_col].astype(str)
    )
    published_clusters = set(
        clusters_summary.loc[clusters_summary["cluster_has_published"], group_id_col].astype(str)
    )

    n_is_version_of = (
        work[work[group_id_col].isin(version_clusters)]
        .groupby(server_col)[group_id_col].nunique()
        .rename("n_is_version_of")
    )

    n_published = (
        work[work[group_id_col].isin(published_clusters)]
        .groupby(server_col)[group_id_col].nunique()
        .rename("n_published")
    )

    summary = (
        pd.concat([n_records, n_unique, n_is_version_of, n_published], axis=1)
        .fillna(0)
        .reset_index()
        .rename(columns={server_col: "server_name"})
    )

    for c in ["n_records", "n_unique", "n_is_version_of", "n_published"]:
        summary[c] = pd.to_numeric(summary[c], errors="coerce").fillna(0).astype(int)

    summary["pct_published"] = np.where(
        summary["n_unique"] > 0,
        (summary["n_published"] / summary["n_unique"]) * 100.0,
        np.nan,
    )

    if source_col and source_col in df.columns:
        tmp = df[[server_col, source_col]].copy()
        tmp[server_col] = tmp[server_col].astype("string").fillna("").str.strip()
        tmp[source_col] = tmp[source_col].astype("string").fillna("").str.strip()

        mode_source = (
            tmp.groupby(server_col)[source_col]
            .agg(lambda x: x.value_counts().index[0] if len(x.dropna()) else "")
            .rename("source")
            .reset_index()
            .rename(columns={server_col: "server_name"})
        )
        summary = summary.merge(mode_source, on="server_name", how="left")

    summary["collection_date"] = pd.Timestamp.utcnow().date().isoformat()

    # ---------------------------------------------------------
    # 3) Enriched yearly_long from parent clusters only
    # ---------------------------------------------------------
    parents_for_yearly = clusters_summary.copy()
    parents_for_yearly = parents_for_yearly.dropna(subset=["parent_year_first_seen"]).copy()
    parents_for_yearly["parent_year_first_seen"] = parents_for_yearly["parent_year_first_seen"].astype("Int64")

    # add numeric yearly aggregators
    parents_for_yearly["count_preprints"] = 1
    parents_for_yearly["count_unique_clusters"] = 1
    parents_for_yearly["count_versioned"] = parents_for_yearly["has_versions"].fillna(False).astype(int)
    parents_for_yearly["count_published"] = parents_for_yearly["cluster_has_published"].fillna(False).astype(int)
    parents_for_yearly["count_cross_server"] = parents_for_yearly["is_cross_server"].fillna(False).astype(int)

    parents_for_yearly["count_single_version"] = (~parents_for_yearly["has_versions"].fillna(False)).astype(int)
    parents_for_yearly["count_not_published"] = (~parents_for_yearly["cluster_has_published"].fillna(False)).astype(int)
    parents_for_yearly["count_not_cross_server"] = (~parents_for_yearly["is_cross_server"].fillna(False)).astype(int)

    yearly_long_enriched = (
        parents_for_yearly
        .groupby(["parent_server_name", "parent_year_first_seen"], as_index=False)
        .agg(
            count_preprints=("count_preprints", "sum"),
            count_unique_clusters=("count_unique_clusters", "sum"),
            count_versioned=("count_versioned", "sum"),
            count_published=("count_published", "sum"),
            count_cross_server=("count_cross_server", "sum"),
            count_single_version=("count_single_version", "sum"),
            count_not_published=("count_not_published", "sum"),
            count_not_cross_server=("count_not_cross_server", "sum"),
        )
        .rename(columns={
            "parent_server_name": "server_name",
            "parent_year_first_seen": "year",
        })
        .sort_values(["server_name", "year"])
        .reset_index(drop=True)
    )

    # ---------------------------------------------------------
    # 4) Wide yearly file for backward compatibility
    #     uses count_preprints only
    # ---------------------------------------------------------
    yearly_wide = (
        yearly_long_enriched
        .pivot_table(
            index="server_name",
            columns="year",
            values="count_preprints",
            aggfunc="sum",
            fill_value=0
        )
        .reset_index()
    )
    yearly_wide.columns = [str(c) for c in yearly_wide.columns]

    # ---------------------------------------------------------
    # 5) Add quick recent indicators into summary
    # ---------------------------------------------------------
    def _merge_year_metric(summary_df: pd.DataFrame, yl: pd.DataFrame, metric_col: str, prefix: str):
        tmp = (
            yl.pivot_table(
                index="server_name",
                columns="year",
                values=metric_col,
                aggfunc="sum",
                fill_value=0
            )
            .reset_index()
        )
        tmp.columns = [str(c) for c in tmp.columns]

        for yr in ["2024", "2025"]:
            new_col = f"{prefix}_{yr}"
            if yr in tmp.columns:
                summary_df = summary_df.merge(
                    tmp[["server_name", yr]].rename(columns={yr: new_col}),
                    on="server_name",
                    how="left"
                )
            else:
                summary_df[new_col] = 0
        return summary_df

    summary = _merge_year_metric(summary, yearly_long_enriched, "count_preprints", "count")
    summary = _merge_year_metric(summary, yearly_long_enriched, "count_versioned", "versioned")
    summary = _merge_year_metric(summary, yearly_long_enriched, "count_published", "published")

    for c in [
        "count_2024", "count_2025",
        "versioned_2024", "versioned_2025",
        "published_2024", "published_2025"
    ]:
        if c in summary.columns:
            summary[c] = pd.to_numeric(summary[c], errors="coerce").fillna(0).astype(int)

    # ---------------------------------------------------------
    # 6) Metrics / QA
    # ---------------------------------------------------------
    metrics = {
        "rows_in_input": int(len(df)),
        "rows_used": int(len(work)),
        "n_servers": int(work[server_col].nunique()),
        "n_clusters": int(clusters_summary[group_id_col].nunique()),
        "clusters_with_versions": int(clusters_summary["has_versions"].sum()),
        "clusters_with_published": int(clusters_summary["cluster_has_published"].sum()),
        "cross_server_clusters": int(clusters_summary["is_cross_server"].sum()),
        "year_min": int(yearly_long_enriched["year"].min()) if len(yearly_long_enriched) else None,
        "year_max": int(yearly_long_enriched["year"].max()) if len(yearly_long_enriched) else None,
        "out_dir": str(out_dir),
    }

    # ---------------------------------------------------------
    # 7) Write files
    # ---------------------------------------------------------
    if write_csv:
        summary.to_csv(out_dir / "summary.csv", index=False)
        yearly_wide.to_csv(out_dir / "yearly.csv", index=False)  # compatible with current app
        yearly_long_enriched.to_csv(out_dir / "yearly_long_enriched.csv", index=False)
        clusters_summary.to_csv(out_dir / "clusters_summary.csv", index=False)
        pd.DataFrame([metrics]).to_json(out_dir / "build_metrics.json", orient="records", indent=2)

    if write_xlsx:
        with pd.ExcelWriter(out_dir / "tracker_outputs.xlsx", engine="openpyxl") as xw:
            summary.to_excel(xw, sheet_name="summary", index=False)
            yearly_wide.to_excel(xw, sheet_name="yearly_wide", index=False)
            yearly_long_enriched.to_excel(xw, sheet_name="yearly_long_enriched", index=False)
            clusters_summary.to_excel(xw, sheet_name="clusters_summary", index=False)
            pd.DataFrame([metrics]).to_excel(xw, sheet_name="metrics", index=False)

    if return_frames:
        return summary, yearly_wide, yearly_long_enriched, clusters_summary, metrics

    return summary, yearly_wide, yearly_long_enriched, clusters_summary, metrics

In [12]:
summary_df, yearly_wide_df, yearly_long_enriched_df, clusters_df, build_metrics = (
    generate_tracker_files_from_dedupe_v2(
        data,
        out_dir="outputs_new/tracker_data",
        write_csv=True,
        write_xlsx=False,
    )
)

print(build_metrics)

/tmp/ipykernel_18712/3141905390.py:85: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  work[has_published_col] = hp_norm.fillna(False).astype(bool)

{'rows_in_input': 7905699, 'rows_used': 7905699, 'n_servers': 109, 'n_clusters': 7332492, 'clusters_with_versions': 458635, 'clusters_with_published': 1764748, 'cross_server_clusters': 179373, 'year_min': 1990, 'year_max': 2025, 'out_dir': 'outputs_new/tracker_data'}

# exploration

In [13]:
data_version = data[data['records_hierarchy']=='version']
data_version

Empty DataFrame
Columns: [record_id, server_name, backend, doi, doi_url, landing_page_url, type_backend_raw, subtype_backend_raw, title, authors_flat, institutions_flat, countries_flat, relations_json, version_label, is_version_of, is_preprint_of, has_preprint, has_review, has_published_version, published_version_ids_json, version_of_ids_json, update_to_json, raw_relationships_json, records_hierarchy, date_first_seen, publication_year, publication_year_first_seen, raw_dates, records_hierarchy_backup, parent_record_id, dup_group_id, authors_fp_tokenbag, title_clean_v2, authors_fp_last_initial, authors_fp_last, records_hierarchy_dedupe_backup, parent_record_id_dedupe_backup, dup_group_id_dedupe_backup, has_version_dois, records_hierarchy_unify_version_backup, parent_record_id_unify_version_backup, dup_group_id_unify_version_backup]
Index: []

In [14]:
data_version[data_version['records_hierarchy']=='parent']

Empty DataFrame
Columns: [record_id, server_name, backend, doi, doi_url, landing_page_url, type_backend_raw, subtype_backend_raw, title, authors_flat, institutions_flat, countries_flat, relations_json, version_label, is_version_of, is_preprint_of, has_preprint, has_review, has_published_version, published_version_ids_json, version_of_ids_json, update_to_json, raw_relationships_json, records_hierarchy, date_first_seen, publication_year, publication_year_first_seen, raw_dates, records_hierarchy_backup, parent_record_id, dup_group_id, authors_fp_tokenbag, title_clean_v2, authors_fp_last_initial, authors_fp_last, records_hierarchy_dedupe_backup, parent_record_id_dedupe_backup, dup_group_id_dedupe_backup, has_version_dois, records_hierarchy_unify_version_backup, parent_record_id_unify_version_backup, dup_group_id_unify_version_backup]
Index: []

In [15]:
pattern = "Evaluation of ML methods for online use in th"


mask = data['title'].str.contains(pattern, regex=False, na=False)
result = data[mask]
print(len(result))
result

0

Empty DataFrame
Columns: [record_id, server_name, backend, doi, doi_url, landing_page_url, type_backend_raw, subtype_backend_raw, title, authors_flat, institutions_flat, countries_flat, relations_json, version_label, is_version_of, is_preprint_of, has_preprint, has_review, has_published_version, published_version_ids_json, version_of_ids_json, update_to_json, raw_relationships_json, records_hierarchy, date_first_seen, publication_year, publication_year_first_seen, raw_dates, records_hierarchy_backup, parent_record_id, dup_group_id, authors_fp_tokenbag, title_clean_v2, authors_fp_last_initial, authors_fp_last, records_hierarchy_dedupe_backup, parent_record_id_dedupe_backup, dup_group_id_dedupe_backup, has_version_dois, records_hierarchy_unify_version_backup, parent_record_id_unify_version_backup, dup_group_id_unify_version_backup]
Index: []

In [16]:
pattern = "Exploring the Relationship of Enrollmen"


mask = data['title'].str.contains(pattern, regex=False, na=False)
result = data[mask]
print(len(result))
result

3

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
1410197,crossref::10.2139/ssrn.3757559,SSRN,crossref,10.2139/ssrn.3757559,https://doi.org/10.2139/ssrn.3757559,https://www.ssrn.com/abstract=3757559,journal-article,None,Exploring the Relationship of Enrollment in ID...,"Collier, Daniel; Fitzpatrick, Dan; Marsicano, ...",None,None,None,None,None,,,,false,None,None,None,None,parent - duplicate (SSRN),2020-01-01,2020.0,2020,None,parent,crossref::10.33774/apsa-2019-nd8n2,crossref::10.33774/apsa-2019-nd8n2,christopher_marsicano;collier_daniel;dan_fitzp...,exploring the relationship of enrollment in id...,collier|d;fitzpatrick|d;marsicano|c,None,parent - duplicate (APSA Preprints),crossref::10.33774/apsa-2019-nd8n2,fuzzy::last_initial::collier|d;fitzpatrick|d;m...,None,parent - duplicate (APSA Preprints),crossref::10.33774/apsa-2019-nd8n2,fuzzy::last_initial::collier|d;fitzpatrick|d;m...
2658802,crossref::10.33774/apsa-2019-nd8n2,APSA Preprints,crossref,10.33774/apsa-2019-nd8n2,https://doi.org/10.33774/apsa-2019-nd8n2,https://preprints.apsanet.org/engage/apsa/arti...,posted-content,preprint,Exploring the Relationship of Enrollment in In...,"Collier, Daniel A.; Fitzpatrick, Dan; Marsican...",W.E. Upjohn Institute for Employment Research;...,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.33774/apsa-2019-nd8n2-v2,,,,false,None,None,None,None,parent,2019-10-04,2019.0,2019,None,version,<NA>,crossref::10.33774/apsa-2019-nd8n2,a_collier_daniel;christopher_marsicano_r;dan_f...,exploring the relationship of enrollment in in...,collier|d;fitzpatrick|d;marsicano|c,None,parent,None,10655472821248023217,None,parent,None,crossref::10.33774/apsa-2019-nd8n2
2658803,crossref::10.33774/apsa-2019-nd8n2-v2,APSA Preprints,crossref,10.33774/apsa-2019-nd8n2-v2,https://doi.org/10.33774/apsa-2019-nd8n2-v2,https://preprints.apsanet.org/engage/apsa/arti...,posted-content,preprint,Exploring the Relationship of Enrollment in In...,"Collier, Daniel A.; Fitzpatrick, Dan; Marsican...",W.E. Upjohn Institute for Employment Research;...,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.33774/apsa-2019-nd8n2,,,,false,None,None,None,None,parent - duplicate (APSA Preprints),2020-04-06,2020.0,2020,None,version,crossref::10.33774/apsa-2019-nd8n2,crossref::10.33774/apsa-2019-nd8n2,a_collier_daniel;christopher_marsicano_r;dan_f...,exploring the relationship of enrollment in in...,None,None,parent - duplicate (APSA Preprints),crossref::10.33774/apsa-2019-nd8n2,10655472821248023217,None,parent - duplicate (version-link),crossref::10.33774/apsa-2019-nd8n2,crossref::10.33774/apsa-2019-nd8n2

In [17]:
result[['record_id','server_name','records_hierarchy','parent_record_id','dup_group_id','date_first_seen',]]

,record_id,server_name,records_hierarchy,parent_record_id,dup_group_id,date_first_seen
1410197,crossref::10.2139/ssrn.3757559,SSRN,parent - duplicate (SSRN),crossref::10.33774/apsa-2019-nd8n2,crossref::10.33774/apsa-2019-nd8n2,2020-01-01
2658802,crossref::10.33774/apsa-2019-nd8n2,APSA Preprints,parent,<NA>,crossref::10.33774/apsa-2019-nd8n2,2019-10-04
2658803,crossref::10.33774/apsa-2019-nd8n2-v2,APSA Preprints,parent - duplicate (APSA Preprints),crossref::10.33774/apsa-2019-nd8n2,crossref::10.33774/apsa-2019-nd8n2,2020-04-06

In [18]:
pattern = "Ethnic Autonomy"


mask = data['title'].str.contains(pattern, regex=False, na=False)
result = data[mask]
print(len(result))
result

5

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
1064218,crossref::10.2139/ssrn.1634570,SSRN,crossref,10.2139/ssrn.1634570,https://doi.org/10.2139/ssrn.1634570,http://www.ssrn.com/abstract=1634570,journal-article,None,"Culture, Development, and Regional Ethnic Auto...","Zheng, George G.",None,None,None,None,None,,,,false,None,None,None,None,parent,2010-07-05,2010.0,2010,None,parent,None,crossref::10.2139/ssrn.1634570,None,culture development and regional ethnic autono...,zheng|g,None,parent,None,None,None,parent,None,None
1968932,crossref::10.2139/ssrn.5071920,SSRN,crossref,10.2139/ssrn.5071920,https://doi.org/10.2139/ssrn.5071920,https://www.ssrn.com/abstract=5071920,posted-content,preprint,Federalism vs. Centralization: Ethnic Autonomy...,"AYAZ, MUHAMMAD; Fahad, Ujala",None,None,None,None,None,,,,false,None,None,None,None,parent,2025-01-01,2025.0,2025,None,parent,None,crossref::10.2139/ssrn.5071920,None,None,None,None,parent,None,None,None,parent,None,None
2658744,crossref::10.33774/apsa-2019-25rz9,APSA Preprints,crossref,10.33774/apsa-2019-25rz9,https://doi.org/10.33774/apsa-2019-25rz9,https://preprints.apsanet.org/engage/apsa/arti...,posted-content,preprint,Ethnic Autonomy,"Sasaki, Yu",Waseda University,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.33774/apsa-2019-25rz9-v2;10.33774/apsa-2019...,,,,false,None,None,None,None,parent,2019-09-19,2019.0,2019,None,version,<NA>,crossref::10.33774/apsa-2019-25rz9,sasaki_yu,ethnic autonomy,sasaki|y,sasaki,parent,None,None,None,parent,None,crossref::10.33774/apsa-2019-25rz9
2658745,crossref::10.33774/apsa-2019-25rz9-v2,APSA Preprints,crossref,10.33774/apsa-2019-25rz9-v2,https://doi.org/10.33774/apsa-2019-25rz9-v2,https://preprints.apsanet.org/engage/apsa/arti...,posted-content,preprint,Ethnic Autonomy,"Sasaki, Yu",Waseda University,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.33774/apsa-2019-25rz9;10.33774/apsa-2019-25...,,,,false,None,None,None,None,parent - duplicate (APSA Preprints),2020-01-31,2020.0,2020,None,version,crossref::10.33774/apsa-2019-25rz9,crossref::10.33774/apsa-2019-25rz9,sasaki_yu,ethnic autonomy,sasaki|y,sasaki,parent,None,None,None,parent - duplicate (version-link),crossref::10.33774/apsa-2019-25rz9,crossref::10.33774/apsa-2019-25rz9
2658746,crossref::10.33774/apsa-2019-25rz9-v3,APSA Preprints,crossref,10.33774/apsa-2019-25rz9-v3,https://doi.org/10.33774/apsa-2019-25rz9-v3,https://preprints.apsanet.org/engage/apsa/arti...,posted-content,preprint,Ethnic Autonomy,"Sasaki, Yu",Kanazawa University,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",None,10.33774/apsa-2019-25rz9;10.33774/apsa-2019-25...,,,,false,None,None,None,None,parent - duplicate (APSA Preprints),2020-12-03,2020.0,2020,None,version,crossref::10.33774/apsa-2019-25rz9,crossref::10.33774/apsa-2019-25rz9,sasaki_yu,ethnic autonomy,sasaki|y,sasaki,parent,None,None,None,parent - duplicate (version-link),crossref::10.33774/apsa-2019-25rz9,crossref::10.33774/apsa-2019-25rz9

In [19]:
pattern = "datacite::10.48550/arxiv.1009.5069"


mask = data['dup_group_id'].str.contains(pattern, regex=False, na=False)
result = data[mask]
print(len(result))
result

1

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
3341778,datacite::10.48550/arxiv.1009.5069,arXiv,datacite,10.48550/arxiv.1009.5069,https://doi.org/10.48550/arxiv.1009.5069,https://arxiv.org/abs/1009.5069,Text,Article,Search for Quark Contact Interactions in Dijet...,ATLAS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1016/j.physletb.201...",1,10.1016/j.physletb.2010.10.021,10.1016/j.physletb.2010.10.021,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2010-09-26,2010.0,2010,"[{""date"": ""2010-09-26T07:51:50Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.1009.5069,atlas_collaboration,search for quark contact interactions in dijet...,collaboration|a,None,parent,None,None,10.1016/j.physletb.2010.10.021,parent,None,None

In [20]:
pattern = "datacite::10.48550/arxiv.1010.0203"


mask = data['dup_group_id'].str.contains(pattern, regex=False, na=False)
result = data[mask]
print(len(result))
result

1

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
3343144,datacite::10.48550/arxiv.1010.0203,arXiv,datacite,10.48550/arxiv.1010.0203,https://doi.org/10.48550/arxiv.1010.0203,https://arxiv.org/abs/1010.0203,Text,Article,Search for Dijet Resonances in 7 TeV pp Collis...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1103/physrevlett.10...",2,10.1103/physrevlett.105.211801;10.1103/physrev...,10.1103/physrevlett.105.211801;10.1103/physrev...,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2010-10-01,2010.0,2010,"[{""date"": ""2010-10-01T16:49:31Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.1010.0203,cms_collaboration,search for dijet resonances in 7 tev pp collis...,collaboration|c,None,parent,None,None,10.1103/physrevlett.105.211801;10.1103/physrev...,parent,None,None

In [21]:
pattern = "Search for a heavy resonance decaying into"


mask = data['title'].str.contains(pattern, regex=False, na=False)
result = data[mask]
print(len(result))
result

6

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
4080524,datacite::10.48550/arxiv.1803.03838,arXiv,datacite,10.48550/arxiv.1803.03838,https://doi.org/10.48550/arxiv.1803.03838,https://arxiv.org/abs/1803.03838,Text,Article,Search for a heavy resonance decaying into a Z...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep07(2018)07...",2,10.1007/jhep07(2018)075,10.1007/jhep07(2018)075,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2018-03-10,2018.0,2018,"[{""date"": ""2018-03-10T16:50:09Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.1803.03838,cms_collaboration,search for a heavy resonance decaying into a z...,collaboration|c,None,parent,None,None,10.1007/jhep07(2018)075,parent,None,None
4086779,datacite::10.48550/arxiv.1803.10093,arXiv,datacite,10.48550/arxiv.1803.10093,https://doi.org/10.48550/arxiv.1803.10093,https://arxiv.org/abs/1803.10093,Text,Article,Search for a heavy resonance decaying into a Z...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep09(2018)10...",2,10.1007/jhep09(2018)101,10.1007/jhep09(2018)101,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2018-03-27,2018.0,2018,"[{""date"": ""2018-03-27T14:08:11Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.1803.10093,cms_collaboration,search for a heavy resonance decaying into a z...,collaboration|c,None,parent,None,None,10.1007/jhep09(2018)101,parent,None,None
4690871,datacite::10.48550/arxiv.2111.10216,arXiv,datacite,10.48550/arxiv.2111.10216,https://doi.org/10.48550/arxiv.2111.10216,https://arxiv.org/abs/2111.10216,Text,Article,Search for a heavy resonance decaying into a t...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep04(2022)04...",2,10.1007/jhep04(2022)048,10.1007/jhep04(2022)048,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2021-11-19,2021.0,2021,"[{""date"": ""2021-11-19T13:43:07Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.2111.10216,cms_collaboration,search for a heavy resonance decaying into a t...,collaboration|c,None,parent,None,None,10.1007/jhep04(2022)048,parent,None,None
5309160,datacite::10.48550/arxiv.2411.00202,arXiv,datacite,10.48550/arxiv.2411.00202,https://doi.org/10.48550/arxiv.2411.00202,https://arxiv.org/abs/2411.00202,Text,Article,Search for a heavy resonance decaying into a Z...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep02(2025)08...",2,10.1007/jhep02(2025)089,10.1007/jhep02(2025)089,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2024-10-31,2024.0,2024,"[{""date"": ""2024-10-31T20:48:24Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.2411.00202,cms_collaboration,search for a heavy resonance decaying into a z...,collaboration|c,None,parent,None,None,10.1007/jhep02(2025)089,parent,None,None
5823561,datacite::10.48550/arxiv.hep-ex/0606018,arXiv,datacite,10.48550/arxiv.hep-ex/0606018,https://doi.org/10.48550/arxiv.hep-ex/0606018,https://arxiv.org/abs/hep-ex/0606018,Text,Article,Search for a heavy resonance decaying into a Z...,"D0 Collaboration; Abazov, V. M.",None,None,"[{""relatedIdentifier"": ""10.1103/physrevd.74.01...",1,10.1103/physrevd.74.011104,10.1103/physrevd.74.011104,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2006-06-08,2006.0,2006,"[{""date"": ""2006-06-08T12:56:23Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.hep-ex/0606018,abazov_m_v;collaboration_d0,search for a heavy resonance decaying into a z...,abazov|v;collaboration|d,None,parent,None,None,10.1103/physrevd.74.011104,parent,None,None
6760738,openalex::W2921909056,DSpace@MIT,openalex,None,None,http://hdl.handle.net/1721.1/117537,article,None,Search for a heavy resonance decaying into a Z...,Daniel Robert Abercrombie; Brandon Leigh Allen...,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2018-07-01,2018.0,2018,None,parent,None,openalex::W2921909056,None,None,None,None,parent,None,None,None,parent,None,None

In [22]:
pattern = "Search for a heavy resonance decaying into"


mask = data['title'].str.contains(pattern, regex=False, na=False)
result = data[mask]
print(len(result))
result

6

,record_id,server_name,backend,doi,doi_url,landing_page_url,type_backend_raw,subtype_backend_raw,title,authors_flat,institutions_flat,countries_flat,relations_json,version_label,is_version_of,is_preprint_of,has_preprint,has_review,has_published_version,published_version_ids_json,version_of_ids_json,update_to_json,raw_relationships_json,records_hierarchy,date_first_seen,publication_year,publication_year_first_seen,raw_dates,records_hierarchy_backup,parent_record_id,dup_group_id,authors_fp_tokenbag,title_clean_v2,authors_fp_last_initial,authors_fp_last,records_hierarchy_dedupe_backup,parent_record_id_dedupe_backup,dup_group_id_dedupe_backup,has_version_dois,records_hierarchy_unify_version_backup,parent_record_id_unify_version_backup,dup_group_id_unify_version_backup
4080524,datacite::10.48550/arxiv.1803.03838,arXiv,datacite,10.48550/arxiv.1803.03838,https://doi.org/10.48550/arxiv.1803.03838,https://arxiv.org/abs/1803.03838,Text,Article,Search for a heavy resonance decaying into a Z...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep07(2018)07...",2,10.1007/jhep07(2018)075,10.1007/jhep07(2018)075,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2018-03-10,2018.0,2018,"[{""date"": ""2018-03-10T16:50:09Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.1803.03838,cms_collaboration,search for a heavy resonance decaying into a z...,collaboration|c,None,parent,None,None,10.1007/jhep07(2018)075,parent,None,None
4086779,datacite::10.48550/arxiv.1803.10093,arXiv,datacite,10.48550/arxiv.1803.10093,https://doi.org/10.48550/arxiv.1803.10093,https://arxiv.org/abs/1803.10093,Text,Article,Search for a heavy resonance decaying into a Z...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep09(2018)10...",2,10.1007/jhep09(2018)101,10.1007/jhep09(2018)101,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2018-03-27,2018.0,2018,"[{""date"": ""2018-03-27T14:08:11Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.1803.10093,cms_collaboration,search for a heavy resonance decaying into a z...,collaboration|c,None,parent,None,None,10.1007/jhep09(2018)101,parent,None,None
4690871,datacite::10.48550/arxiv.2111.10216,arXiv,datacite,10.48550/arxiv.2111.10216,https://doi.org/10.48550/arxiv.2111.10216,https://arxiv.org/abs/2111.10216,Text,Article,Search for a heavy resonance decaying into a t...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep04(2022)04...",2,10.1007/jhep04(2022)048,10.1007/jhep04(2022)048,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2021-11-19,2021.0,2021,"[{""date"": ""2021-11-19T13:43:07Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.2111.10216,cms_collaboration,search for a heavy resonance decaying into a t...,collaboration|c,None,parent,None,None,10.1007/jhep04(2022)048,parent,None,None
5309160,datacite::10.48550/arxiv.2411.00202,arXiv,datacite,10.48550/arxiv.2411.00202,https://doi.org/10.48550/arxiv.2411.00202,https://arxiv.org/abs/2411.00202,Text,Article,Search for a heavy resonance decaying into a Z...,CMS Collaboration,None,None,"[{""relatedIdentifier"": ""10.1007/jhep02(2025)08...",2,10.1007/jhep02(2025)089,10.1007/jhep02(2025)089,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2024-10-31,2024.0,2024,"[{""date"": ""2024-10-31T20:48:24Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.2411.00202,cms_collaboration,search for a heavy resonance decaying into a z...,collaboration|c,None,parent,None,None,10.1007/jhep02(2025)089,parent,None,None
5823561,datacite::10.48550/arxiv.hep-ex/0606018,arXiv,datacite,10.48550/arxiv.hep-ex/0606018,https://doi.org/10.48550/arxiv.hep-ex/0606018,https://arxiv.org/abs/hep-ex/0606018,Text,Article,Search for a heavy resonance decaying into a Z...,"D0 Collaboration; Abazov, V. M.",None,None,"[{""relatedIdentifier"": ""10.1103/physrevd.74.01...",1,10.1103/physrevd.74.011104,10.1103/physrevd.74.011104,,,true,None,None,None,"{""client"": {""data"": {""id"": ""arxiv.content"", ""t...",parent,2006-06-08,2006.0,2006,"[{""date"": ""2006-06-08T12:56:23Z"", ""dateInforma...",parent,None,datacite::10.48550/arxiv.hep-ex/0606018,abazov_m_v;collaboration_d0,search for a heavy resonance decaying into a z...,abazov|v;collaboration|d,None,parent,None,None,10.1103/physrevd.74.011104,parent,None,None
6760738,openalex::W2921909056,DSpace@MIT,openalex,None,None,http://hdl.handle.net/1721.1/117537,article,None,Search for a heavy resonance decaying into a Z...,Daniel Robert Abercrombie; Brandon Leigh Allen...,None,None,None,None,None,None,None,None,None,None,None,None,None,parent,2018-07-01,2018.0,2018,None,parent,None,openalex::W2921909056,None,None,None,None,parent,None,None,None,parent,None,None

In [23]:
result['title'].value_counts()

title
Search for a heavy resonance decaying into a Z boson and a vector boson in the $ν\overlineν\mathrm{q}\overline{\mathrm{q}}$ final state                                                                             1
Search for a heavy resonance decaying into a Z boson and a Z or W boson in 2$\ell$2q final states at $\sqrt{s}=$ 13 TeV                                                                                             1
Search for a heavy resonance decaying into a top quark and a W boson in the lepton+jets final state at $\sqrt{s} = $13 TeV                                                                                          1
Search for a heavy resonance decaying into a Z and a Higgs boson in events with an energetic jet and two electrons, two muons, or missing transverse momentum in proton-proton collisions at $\sqrt{s}$ = 13 TeV    1
Search for a heavy resonance decaying into a Z+jet final state in p-pbar collisions at sqrt(s) = 1.96 TeV using the D0 detector                                                                                     1
Search for a heavy resonance decaying into a Z boson and a vector boson in the vv qq final state                                                                                                                    1
Name: count, dtype: int64