# functions

In [1]:
import pandas as pd
import glob
import os
# Set option to display all columns
pd.set_option('display.max_columns', None)

In [2]:
import pandas as pd
import numpy as np
from urllib.parse import urlparse
import re
import unicodedata

DOI_CORE_RE = re.compile(r"(10\.\d{4,9}/\S+)", re.IGNORECASE)

def _normalize_doi_raw(x: str) -> str | None:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return None
    s = str(x).strip()
    s = unicodedata.normalize("NFKC", s).lower()
    m = DOI_CORE_RE.search(s)  # extract from URL/“doi:” etc.
    if m:
        return m.group(1)
    if s.startswith("10.") and "/" in s:
        return s
    return None

def clean_preprint_fields(df: pd.DataFrame, *, numeric_keep: int = 2, add_bucket: bool = True) -> pd.DataFrame:
    """Clean + enrich preprint fields.
    - Builds doi_prefix_first_token
    - If first token is purely numeric, keeps only its first `numeric_keep` digits
    - Optionally adds a bucketing column for grouping
    """
    df = df.drop_duplicates().copy()

    # # --- gold_server_name
    # df["gold_server_name"] = (
    #     df.get("institution_name")
    #       .fillna(df.get("group_title"))
    #       .fillna(df.get("publisher"))
    # )

    # --- Normalize DOI
    if "doi" in df.columns:
        df["doi_lc"] = df["doi"].map(_normalize_doi_raw)
    elif "parent_doi" in df.columns:
        df["doi_lc"] = df["parent_doi"].map(_normalize_doi_raw)
    else:
        df["doi_lc"] = pd.Series(pd.NA, index=df.index, dtype="object")

    # --- prefix as given
    if "prefix" in df.columns:
        df["prefix_lc"] = df["prefix"].astype(str).str.strip().str.lower()
        df.loc[df["prefix_lc"].isin(["", "nan", "none"]), "prefix_lc"] = pd.NA
    else:
        df["prefix_lc"] = pd.Series(pd.NA, index=df.index, dtype="object")

    # --- Extract prefix/suffix from normalized DOI
    doi_parts = df["doi_lc"].str.extract(r"^(10\.\d{4,9})/(.+)$")
    df["doi_prefix_from_text"] = doi_parts[0]
    df["doi_suffix"] = doi_parts[1]
    df["prefix_lc"] = df["prefix_lc"].where(df["prefix_lc"].notna(), df["doi_prefix_from_text"])

    # --- Build first segment of suffix
    starts_with_letter = df["doi_suffix"].str.match(r"^[a-z]", na=False)

    # letters-case: take only leading letters/hyphens; stop before digits or separators
    first_seg_letters = df["doi_suffix"].str.extract(
        r"^([a-z\-]+)(?=\d|[.\-_/:]|$)", expand=False
    )

    # default-case: first chunk before separators (keeps digits)
    first_seg_default = df["doi_suffix"].str.split(r"[.\-_/:\s]", n=1, regex=True).str[0]

    first_seg = pd.Series(
        np.where(starts_with_letter, first_seg_letters, first_seg_default),
        index=df.index,
        dtype="object"
    )

    # fallback: permissive token if still NA
    need_fallback = first_seg.isna() & df["doi_suffix"].notna()
    first_seg.loc[need_fallback] = df.loc[need_fallback, "doi_suffix"].str.extract(r"^([a-z0-9\-]+)", expand=False)

    # --- NEW: compress purely numeric first tokens to first `numeric_keep` digits
    if numeric_keep and numeric_keep > 0:
        numeric_only = first_seg.str.fullmatch(r"\d+", na=False)
        first_seg.loc[numeric_only] = first_seg.loc[numeric_only].str[:numeric_keep]

    # --- Assemble final token
    df["doi_prefix_first_token"] = pd.Series(pd.NA, index=df.index, dtype="object")
    ok = df["prefix_lc"].notna() & first_seg.notna() & (first_seg.astype(str) != "")
    df.loc[ok, "doi_prefix_first_token"] = df.loc[ok, "prefix_lc"].astype(str) + "/" + first_seg.loc[ok].astype(str)

    # --- Optional bucket for grouping/plots (mirrors the compressed numeric rule)
    if add_bucket:
        df["doi_prefix_bucket_2d"] = df["doi_prefix_first_token"]

    # --- Domains
    def domain_and_first_path(u):
        try:
            parsed = urlparse(str(u).lower())
            host = parsed.netloc
            if host.startswith("www."):
                host = host[4:]
            parts = re.split(r"[/=]", parsed.path)
            first_part = parts[1] if len(parts) > 1 and parts[1] else None
            return f"{host}/{first_part}" if host and first_part else (host or None)
        except Exception:
            return None

    if "landing_page_url" in df.columns:
        df["primary_domain"] = df["landing_page_url"].apply(lambda u: urlparse(str(u)).netloc.lower().replace("www.", "") if pd.notna(u) else None)
        df["primary_domain_extend"] = df["landing_page_url"].apply(domain_and_first_path)
    elif "parent_url" in df.columns:
        df["primary_domain"] = df["parent_url"].apply(lambda u: urlparse(str(u)).netloc.lower().replace("www.", "") if pd.notna(u) else None)
        df["primary_domain_extend"] = df["parent_url"].apply(domain_and_first_path)
    else:
        df["primary_domain"] = pd.Series(pd.NA, index=df.index, dtype="object")
        df["primary_domain_extend"] = pd.Series(pd.NA, index=df.index, dtype="object")

    # --- Dates → year
    if "posted_date" in df.columns:
        df["posted_date"] = pd.to_datetime(df["posted_date"], errors="coerce")
        df["year"] = df["posted_date"].dt.year

    return df

# # ----- usage
# df = clean_preprint_fields(df, numeric_keep=2, add_bucket=True)
# print(df.shape)

In [3]:
import pandas as pd
import glob
import os

def get_server_data(server_name, base_path=r"/mnt/c/SCHOLCOMMLAB/APPs/preprint-harvester/data/by_server/"):
    """
    Loads, cleans, and summarizes server metadata with clear visual formatting.
    """
    
    # 1. CONSTRUCTION & LOADING
    folder_path = os.path.join(base_path, server_name)
    parquet_files = glob.glob(os.path.join(folder_path, "*.parquet"))
    
    if not parquet_files:
        print(f"\n[!] ERROR: No parquet files found for '{server_name}'")
        print(f"    Path searched: {folder_path}\n")
        return None, None

    raw_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)
    raw_df = raw_df.drop_duplicates('record_id')
    
    # 2. STATUS HEADER
    print("\n" + "="*50)
    print(f" SERVER ANALYSIS: {server_name.upper()}")
    print("="*50)
    print(f"  > Files found:    {len(parquet_files)}")
    print(f"  > Raw records:    {len(raw_df)}")
    
    
    # 3. CLEANING STEP
    df = clean_preprint_fields(raw_df, numeric_keep=2, add_bucket=True)
    print(f"  > Cleaned shape:  {df.shape}")
    print(f"  > Unique DOIs:    {df['doi'].nunique()}")
    print("-" * 50)


    # 4. SUMMARY GENERATION
    cols_to_summarize = [
        "doi_prefix_first_token", "primary_domain", "prefix", "member_id", 
        "publisher", "container_title", "institution_name", "group_title", 
        "issn", "type_backend_raw", "subtype_backend_raw"
    ]
    
    summary = {}
    
    for col in cols_to_summarize:
        if col in df.columns:
            # Store the data
            summary[col] = df[col].value_counts(dropna=False)
            
            # Print with plenty of space
            print(f"\nTOP VALUES FOR: {col.upper()}")
            print("-" * 30)
            print(summary[col].head(10))
            print("\n")
        else:
            summary[col] = "Column not found"
            print(f"\n[!] Column '{col}' not found in DataFrame.\n")

    print("="*50)
    print(f" END OF SUMMARY FOR {server_name.upper()}")
    print("="*50 + "\n")

    return df, summary

# ----- Execution example
# elife_df, elife_summary = get_server_data("eLife")

In [4]:
import pandas as pd
import os

def analyze_parent_data(server_name, parent_df):
    """
    Filters the consolidated parent DataFrame for a specific server 
    and provides a summary of versioning and metadata.
    """
    
    # 1. FILTERING
    # Filter first to minimize memory usage during cleaning
    df_filtered = parent_df[parent_df['parent_server_name'] == server_name].copy()
    
    # Check if empty BEFORE running cleaning logic
    if df_filtered.empty:
        print(f"\n" + "!"*60)
        print(f" [!] ERROR: No records found for '{server_name}'")
        print(f" Check if the name matches 'parent_server_name' exactly.")
        print("!"*60 + "\n")
        return None, None

    # 2. CLEANING
    # Running cleaning on the filtered subset
    df = clean_preprint_fields(df_filtered, numeric_keep=2, add_bucket=True)
    
    # 3. STATUS HEADER
    print("\n" + "="*65)
    print(f" CONSOLIDATED ANALYSIS: {server_name.upper()}")
    print("="*65)
    print(f"  > Total Parent Groups:     {len(df):,}")
    print(f"  > Total Versions Found:    {int(df['total_versions'].sum()):,}")
    print(f"  > Unique Parent DOIs:      {df['parent_doi'].nunique():,}")
    print("-" * 65)

    # 4. VERSIONING SUMMARY
    print(f"\n VERSIONING DISTRIBUTION for {server_name}:")
    print("-" * 35)
    v_counts = df['total_versions'].value_counts().sort_index()
    for version_num, count in v_counts.items():
        print(f"  {int(version_num)} version(s):".ljust(20) + f"{count:,} groups")
    
    print(f"\n  Average versions per parent: {df['total_versions'].mean():.2f}")

    # 5. CROSS-SERVER MAPPING
    print(f"\n MOST RECENT DESTINATIONS (Migration):")
    print("-" * 35)
    destinations = df['most_recent_version_servers'].value_counts().head(10)
    print(destinations.to_string())

    # 6. METADATA SUMMARY
    cols_to_summarize = [
        "doi_prefix_first_token", "primary_domain"] # "servers_with_counts", "parent_year_first_seen", 
    summary = {}
    
    for col in cols_to_summarize:
        if col in df.columns:
            summary[col] = df[col].value_counts(dropna=False)
            print(f"\n TOP VALUES FOR: {col.upper()}")
            print("-" * 35)
            print(summary[col].head(10).to_string())
            print("\n")

    print("="*65)
    print(f" COMPLETED: {server_name.upper()}")
    print("="*65 + "\n")

    return df, summary

# ----- Execution Example
# parent_path = "outputs_new/parent/parent_version_index_full.parquet"
# full_parent_df = pd.read_parquet(parent_path)

# elife_parent_df, elife_parent_summary = analyze_parent_data("eLife", full_parent_df)

# Load parent data

In [5]:
# ----- Execution Example
# 1. Load the big file once
long_path = "outputs_new/parent/dedupe_clusters_long_full.parquet"
parent_path = "outputs_new/parent/parent_version_index_full.parquet"

full_parent_df = pd.read_parquet(parent_path)
full_dataset_df = pd.read_parquet(long_path)
# 2. Analyze a specific server within that file
# arxiv_parent_df, arxiv_parent_summary = analyze_parent_data("arXiv", full_parent_df)
# advance_parent_df, advance_parent_summary = analyze_parent_data("Advance", full_parent_df)

# Advance

In [6]:
Advance_df, Advance_summary = get_server_data("Advance")

==================================================
 SERVER ANALYSIS: ADVANCE
==================================================
  > Files found:    1
  > Raw records:    4401
  > Cleaned shape:  (4401, 90)
  > Unique DOIs:    4401
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31124/advance    4401
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
advance.sagepub.com    4392
authorea.com              7
techrxiv.org              2
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31124    4401
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
179    4401
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
SAGE Publications    4401
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    4401
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None              2222
Advance           2177
Authorea, Inc.       2
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None         3632
Preprints     769
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    4401
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    4401
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    4399
other          2
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ADVANCE
==================================================

In [7]:
Advance_df

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.31124/advance.7037639,Advance,crossref,10.31124/advance.7037639,10.31124/advance.7037639,https://doi.org/10.31124/advance.7037639,https://advance.sagepub.com/articles/The_Priva...,https://advance.sagepub.com/articles/The_Priva...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,The Privatization of Security and the Emergenc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2022-03-30,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;This study interrogates the p...,This study interrogates the participation of p...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Chinwokwu, Eke; Igbo, Emmanuel",None,None,"[{""affiliation"": [], ""family"": ""Chinwokwu"", ""g...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7037639"", ""URL"": ""ht...",10.31124/advance.7037639,10.31124,10.31124,advance.7037639,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
1,crossref::10.31124/advance.7038500,Advance,crossref,10.31124/advance.7038500,10.31124/advance.7038500,https://doi.org/10.31124/advance.7038500,https://advance.sagepub.com/articles/Unmet_nee...,https://advance.sagepub.com/articles/Unmet_nee...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Unmet needs of ageing transgender and non-bina...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>An view of literature on transgender a...,An view of literature on transgender and non-b...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038500"", ""URL"": ""ht...",10.31124/advance.7038500,10.31124,10.31124,advance.7038500,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
2,crossref::10.31124/advance.7038500.v1,Advance,crossref,10.31124/advance.7038500.v1,10.31124/advance.7038500.v1,https://doi.org/10.31124/advance.7038500.v1,https://advance.sagepub.com/articles/Unmet_nee...,https://advance.sagepub.com/articles/Unmet_nee...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Unmet needs of ageing transgender and non-bina...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>An view of literature on transgender a...,An view of literature on transgender and non-b...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038500.v1"", ""URL"": ...",10.31124/advance.7038500.v1,10.31124,10.31124,advance.7038500.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
3,crossref::10.31124/advance.7038503,Advance,crossref,10.31124/advance.7038503,10.31124/advance.7038503,https://doi.org/10.31124/advance.7038503,https://advance.sagepub.com/articles/A_TROG_ma...,https://advance.sagepub.com/articles/A_TROG_ma...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A TROG masked.docUsing T.R.O.G to improve psyc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A discussion on language from a theore...,A discussion on language from a theoretical pe...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038503"", ""URL"": ""ht...",10.31124/advance.7038503,10.31124,10.31124,advance.7038503,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
4,crossref::10.31124/advance.7038503.v1,Advance,crossref,10.31124/advance.7038503.v1,10.31124/advance.7038503.v1,https://doi.org/10.31124/advance.7038503.v1,https://advance.sagepub.com/articles/A_TROG_ma...,https://advance.sagepub.com/articles/A_TROG_ma...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A TROG masked.docUsing T.R.O.G to improve psyc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A discussion on language from a theore...,A discussion on language from a theoretical pe...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038503.v1"", ""URL"": ...",10.31124/advance.7038503.v1,10.31124,10.31124,advance.7038503.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4396,crossref::10.31124/advance.175033210.03003372/v2,Advance,crossref,10.31124/advance.175033210.03003372/v2,10.31124/advance.175033210.03003372/v2,https://doi.org/10.31124/advance.175033210.030...,https://advance.sagepub.com/users/835416/artic...,https://advance.sagepub.com/users/835416/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,When Language Dances: Micromovement in Experim...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-11-17,2025-11-17,2025-11-17,2025-11-17,None,2025-11-17,None,2025-11-17,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"PhD, Richard Wainwright,",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-0555-6...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,10.31124/advance.175033210.03003372/v1,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.175033210.03003372/v...",10.31124/advance.175033210.03003372/v2,10.31124,10.31124,advance.175033210.03003372/v2,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4397,crossref::10.31124/advance.175630073.36585408/v2,Advance,crossref,10.31124/advance.175630073.36585408/v2,10.31124/advance.175630073.36585408/v2,https://doi.org/10.31124/advance.175630073.365...,https://advance.sagepub.com/users/945637/artic...,https://advance.sagepub.com/users/945637/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Psychedelic Rejuvenation Hypothesis: A Framewo...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-11-17,2025-11-17,2025-11-17,2025-11-17,None,2025-11-17,None,2025-11-17,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Montgomery, Tony; Grant, DeMond M.",None,None,"[{""ORCID"": ""https://orcid.org/0009-0000-6154-1...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,10.31124/advance.175630073.36585408/v1,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.175630073.36585408/v...",10.31124/advance.175630073.36585408/v2,10.31124,10.31124,advance.175630073.36585408/v2,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4398,crossref::10.31124/advance.176488150.02208323/v1,Advance,crossref,10.31124/advance.176488150.02208323/v1,10.31124/advance.176488150.02208323/v1,https://doi.org/10.31124/advance.176488150.022...,https://advance.sagepub.com/users/906882/artic...,https://advance.sagepub.com/users/906882/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Hurting Diversity: Diversification of Militant...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-04,2025-12-04,2025-12-04,2025-12-04,None,2025-12-04,None,2025-12-04,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Kirisci, Mustafa; Kocaman, Ibrahim; Albayrak, ...",Desales University; Embry-Riddle Aeronautical ...,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8563-2...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.176488150.02208323/v...",10.31124/advance.176488150.02208323/v1,10.31124,10.31124,advance.176488150.02208323/v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4399,crossref::10.31124/advance.176488150.08867006/v1,Advance,crossref,10.31124/advance.176488150.08867006/v1,10.31124/advance.176488150.08867006/v1,https://doi.org/10.31124/advance.176488150.088...,https://advance.sagepub.com/users/930259/artic...,https://advance.sagepub.com/users/930259/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Ethiopia's Political Transition and Reform und...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-04,2025-12-04,2025-12-04,2025-12-04,None,2025-12-04,None,2025-12-04,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Gebre, Abiyot Geneme",University of Kiel Institute of Social Sciences,None,"[{""ORCID"": ""https://orcid.org/0009-0008-6632-5...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.176488150.08867006/v...",10.31124/advance.176488150.08867006/v1,10.31124,10.31124,advance.176488150.08867006/v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4400,crossref::10.31124/advance.176488150.05947609/v1,Advance,crossref,10.31124/advance.176488150.05947609/v1,10.31124/advance.176488150.05947609/v1,https://doi.org/10.31124/advance.176488150.059...,https://advance.sagepub.com/users/914903/artic...,https://advance.sagepub.com/users/914903/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,External Support and Armed Groups’ Behavior: T...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-04,2025-12-04,2025-12-04,2025-12-04,None,2025-12-04,None,2025-12-04,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Youssef, Abboud Maksy",University of Geneva,None,"[{""ORCID"": ""https://orcid.org/0000-0002-7298-1...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.176488150.05947609/v...",10.31124/advance.176488150.05947609/v1,10.31124,10.31124,advance.176488150.05947609/v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users

In [8]:
Advance_df.columns

Index(['record_id', 'server_name', 'backend', 'source_work_id', 'doi',
       'doi_url', 'landing_page_url', 'url_best', 'prefix', 'member_id',
       'client_id', 'provider_id', 'source_registry', 'publisher',
       'container_title', 'institution_name', 'group_title', 'issn', 'title',
       'original_title', 'short_title', 'subtitle', 'language',
       'type_backend_raw', 'subtype_backend_raw', 'type_canonical',
       'is_paratext', 'is_preprint_candidate', 'date_created', 'date_posted',
       'date_deposited', 'date_indexed', 'date_updated', 'date_issued',
       'date_registered', 'date_published', 'date_published_online',
       'publication_year', 'date_published_source', 'date_posted_source',
       'is_oa', 'oa_status', 'license', 'license_url_best', 'abstract_raw',
       'abstract_text', 'links_json_best', 'fulltext_pdf_url', 'authors_flat',
       'institutions_flat', 'countries_flat', 'authors_json',
       'contributors_json', 'editors_json', 'funders_json', 'funders_flat',
       'funders_count', 'subjects_json', 'concepts_json', 'topics_json',
       'cited_by_count', 'cited_by_count_datacite', 'cited_by_count_openalex',
       'is_referenced_by_count_crossref', 'reference_count', 'references_json',
       'relations_json', 'has_preprint', 'is_preprint_of',
       'has_published_version', 'published_version_ids_json', 'is_version_of',
       'version_of_ids_json', 'version_label', 'has_review', 'update_to_json',
       'parent_doi', 'update_policy', 'rule_tokens', 'rule_row_id',
       'raw_relationships_json', 'raw_json', 'doi_lc', 'prefix_lc',
       'doi_prefix_from_text', 'doi_suffix', 'doi_prefix_first_token',
       'doi_prefix_bucket_2d', 'primary_domain', 'primary_domain_extend'],
      dtype='object')

In [9]:
df=Advance_df.copy()

In [10]:
df[df['primary_domain']=='authorea.com']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
3980,crossref::10.31124/advance.172975247.76617035/v1,Advance,crossref,10.31124/advance.172975247.76617035/v1,10.31124/advance.172975247.76617035/v1,https://doi.org/10.31124/advance.172975247.766...,https://www.authorea.com/users/749101/articles...,https://www.authorea.com/users/749101/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,The Relationships between the Perception of Ph...,None,None,None,None,posted-content,preprint,preprint,None,True,2024-10-24,2024-10-24,2024-10-24,2024-10-25,None,2024-10-24,None,2024-10-24,None,2024,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Perlman, Amotz",0,None,"[{""affiliation"": [{""name"": ""0""}], ""family"": ""P...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.172975247.76617035/v...",10.31124/advance.172975247.76617035/v1,10.31124,10.31124,advance.172975247.76617035/v1,10.31124/advance,10.31124/advance,authorea.com,authorea.com/users
3987,crossref::10.31124/advance.173086931.17011759/v1,Advance,crossref,10.31124/advance.173086931.17011759/v1,10.31124/advance.173086931.17011759/v1,https://doi.org/10.31124/advance.173086931.170...,https://www.authorea.com/users/811231/articles...,https://www.authorea.com/users/811231/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Segment-Level Traffic Volume Estimation Incorp...,None,None,None,None,posted-content,preprint,preprint,None,True,2024-11-06,2024-11-06,2024-11-06,2025-05-14,None,2024-11-06,None,2024-11-06,None,2024,issued_date,posted_date,None,None,None,None,None,None,None,None,"Morshed, Syed Ahnaf; Amine, Kamar; Hadi, Mohammed",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3193-3...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.173086931.17011759/v...",10.31124/advance.173086931.17011759/v1,10.31124,10.31124,advance.173086931.17011759/v1,10.31124/advance,10.31124/advance,authorea.com,authorea.com/users
4029,crossref::10.31124/advance.173873930.08099093/v1,Advance,crossref,10.31124/advance.173873930.08099093/v1,10.31124/advance.173873930.08099093/v1,https://doi.org/10.31124/advance.173873930.080...,https://www.authorea.com/users/887234/articles...,https://www.authorea.com/users/887234/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Defining Martial Law: Introducing the EmPower ...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-02-21,2025-02-05,2025-02-21,2025-02-21,None,2025-02-05,None,2025-02-05,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Stewart, Anya",University of California Davis,None,"[{""ORCID"": ""https://orcid.org/0009-0001-3564-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.173873930.08099093/v...",10.31124/advance.173873930.08099093/v1,10.31124,10.31124,advance.173873930.08099093/v1,10.31124/advance,10.31124/advance,authorea.com,authorea.com/users
4030,crossref::10.31124/advance.173883835.54601691/v1,Advance,crossref,10.31124/advance.173883835.54601691/v1,10.31124/advance.173883835.54601691/v1,https://doi.org/10.31124/advance.173883835.546...,https://www.authorea.com/users/887921/articles...,https://www.authorea.com/users/887921/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,The Role of Rebel Committees in Shaping Peace ...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-02-21,2025-02-06,2025-02-21,2025-02-21,None,2025-02-06,None,2025-02-06,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Jimale, Abdinasir",Binghamton University,None,"[{""ORCID"": ""https://orcid.org/0009-0002-0199-5...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.173883835.54601691/v...",10.31124/advance.173883835.54601691/v1,10.31124,10.31124,advance.173883835.54601691/v1,10.31124/advance,10.31124/advance,authorea.com,authorea.com/users
4031,crossref::10.31124/advance.173892076.63256740/v1,Advance,crossref,10.31124/advance.173892076.63256740/v1,10.31124/advance.173892076.63256740/v1,https://doi.org/10.31124/advance.173892076.632...,https://www.authorea.com/users/887924/articles...,https://www.authorea.com/users/887924/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Inside the Iron Curtain: Socio-Political Facto...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-02-21,2025-02-07,2025-02-21,2025-02-21,None,2025-02-07,None,2025-02-07,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Kim, Taekbin",Korea Institute for National Unification,None,"[{""ORCID"": ""https://orcid.org/0000-0002-1216-6...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.173892076.63256740/v...",10.31124/advance.173892076.63256740/v1,10.31124,10.31124,advance.173892076.63256740/v1,10.31124/advance,10.31124/advance,authorea.com,authorea.com/users
4032,crossref::10.31124/advance.173952912.28451956/v1,Advance,crossref,10.31124/advance.173952912.28451956/v1,10.31124/advance.173952912.28451956/v1,https://doi.org/10.31124/advance.173952912.284...,https://www.authorea.com/users/891821/articles...,https://www.authorea.com/users/891821/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Coup-Proofing in the Shadow of External Securi...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-02-21,2025-02-14,2025-02-21,2025-02-21,None,2025-02-14,None,2025-02-14,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Jin, Hwalmin",Chonnam National University,None,"[{""ORCID"": ""https://orcid.org/0000-0002-7750-6...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.173952912.28451956/v...",10.31124/advance.173952912.28451956/v1,10.31124,10.31124,advance.173952912.28451956/v1,10.31124/advance,10.31124/advance,authorea.com,authorea.com/users
4033,crossref::10.31124/advance.173883514.46750785/v1,Advance,crossref,10.31124/advance.173883514.46750785/v1,10.31124/advance.173883514.46750785/v1,https://doi.org/10.31124/advance.173883514.467...,https://www.authorea.com/users/887505/articles...,https://www.authorea.com/users/887505/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Recognition Conflicts in Bolivia after Land Ti...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-02-21,2025-02-06,2025-02-21,2025-02-21,None,2025-02-06,None,2025-02-06,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Fontana, Lorenza",University of Turin,None,"[{""ORCID"": ""https://orcid.org/0000-0001-9983-8...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.173883514.46750785/v...",10.31124/advance.173883514.46750785/v1,10.31124,10.31124,advance.173883514.46750785/v1,10.31124/advance,10.31124/advance,authorea.com,authorea.com/users

In [11]:
df[df['primary_domain']=='authorea.com']['doi'].tolist()

['10.31124/advance.172975247.76617035/v1',
 '10.31124/advance.173086931.17011759/v1',
 '10.31124/advance.173873930.08099093/v1',
 '10.31124/advance.173883835.54601691/v1',
 '10.31124/advance.173892076.63256740/v1',
 '10.31124/advance.173952912.28451956/v1',
 '10.31124/advance.173883514.46750785/v1']

In [12]:
df[df['primary_domain']=='techrxiv.org']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
3821,crossref::10.31124/advance.171330081.13982256/v1,Advance,crossref,10.31124/advance.171330081.13982256/v1,10.31124/advance.171330081.13982256/v1,https://doi.org/10.31124/advance.171330081.139...,https://www.techrxiv.org/users/678900/articles...,https://www.techrxiv.org/users/678900/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Test document,None,None,None,None,posted-content,preprint,preprint,None,True,2024-04-16,2024-04-16,2024-04-16,2025-05-14,None,2024-04-16,None,2024-04-16,None,2024,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Meyer, Carol Anne",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2443-2...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.171330081.13982256/v...",10.31124/advance.171330081.13982256/v1,10.31124,10.31124,advance.171330081.13982256/v1,10.31124/advance,10.31124/advance,techrxiv.org,techrxiv.org/users
3822,crossref::10.31124/advance.171330568.89328065/v1,Advance,crossref,10.31124/advance.171330568.89328065/v1,10.31124/advance.171330568.89328065/v1,https://doi.org/10.31124/advance.171330568.893...,https://www.techrxiv.org/users/678900/articles...,https://www.techrxiv.org/users/678900/articles...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,This is a test preprint,None,None,None,None,posted-content,preprint,preprint,None,True,2024-04-16,2024-04-16,2024-04-16,2025-05-14,None,2024-04-16,None,2024-04-16,None,2024,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,"<jats:p id=""p1"">This is the Abstract of my tes...",This is the Abstract of my test submission,None,None,"Meyer, Carol Anne",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2443-2...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.171330568.89328065/v...",10.31124/advance.171330568.89328065/v1,10.31124,10.31124,advance.171330568.89328065/v1,10.31124/advance,10.31124/advance,techrxiv.org,techrxiv.org/users

In [13]:
df[df['primary_domain']=='techrxiv.org']['doi'].tolist()

['10.31124/advance.171330081.13982256/v1',
 '10.31124/advance.171330568.89328065/v1']

In [14]:
df[df['institution_name']=='Authorea, Inc.']['doi'].tolist()

['10.31124/advance.24454624.v1', '10.31124/advance.170921771.12975902/v1']

In [15]:
df[df['institution_name'].isna()]

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.31124/advance.7037639,Advance,crossref,10.31124/advance.7037639,10.31124/advance.7037639,https://doi.org/10.31124/advance.7037639,https://advance.sagepub.com/articles/The_Priva...,https://advance.sagepub.com/articles/The_Priva...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,The Privatization of Security and the Emergenc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2022-03-30,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;This study interrogates the p...,This study interrogates the participation of p...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Chinwokwu, Eke; Igbo, Emmanuel",None,None,"[{""affiliation"": [], ""family"": ""Chinwokwu"", ""g...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7037639"", ""URL"": ""ht...",10.31124/advance.7037639,10.31124,10.31124,advance.7037639,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
1,crossref::10.31124/advance.7038500,Advance,crossref,10.31124/advance.7038500,10.31124/advance.7038500,https://doi.org/10.31124/advance.7038500,https://advance.sagepub.com/articles/Unmet_nee...,https://advance.sagepub.com/articles/Unmet_nee...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Unmet needs of ageing transgender and non-bina...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>An view of literature on transgender a...,An view of literature on transgender and non-b...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038500"", ""URL"": ""ht...",10.31124/advance.7038500,10.31124,10.31124,advance.7038500,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
2,crossref::10.31124/advance.7038500.v1,Advance,crossref,10.31124/advance.7038500.v1,10.31124/advance.7038500.v1,https://doi.org/10.31124/advance.7038500.v1,https://advance.sagepub.com/articles/Unmet_nee...,https://advance.sagepub.com/articles/Unmet_nee...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Unmet needs of ageing transgender and non-bina...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>An view of literature on transgender a...,An view of literature on transgender and non-b...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038500.v1"", ""URL"": ...",10.31124/advance.7038500.v1,10.31124,10.31124,advance.7038500.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
3,crossref::10.31124/advance.7038503,Advance,crossref,10.31124/advance.7038503,10.31124/advance.7038503,https://doi.org/10.31124/advance.7038503,https://advance.sagepub.com/articles/A_TROG_ma...,https://advance.sagepub.com/articles/A_TROG_ma...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A TROG masked.docUsing T.R.O.G to improve psyc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A discussion on language from a theore...,A discussion on language from a theoretical pe...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038503"", ""URL"": ""ht...",10.31124/advance.7038503,10.31124,10.31124,advance.7038503,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
4,crossref::10.31124/advance.7038503.v1,Advance,crossref,10.31124/advance.7038503.v1,10.31124/advance.7038503.v1,https://doi.org/10.31124/advance.7038503.v1,https://advance.sagepub.com/articles/A_TROG_ma...,https://advance.sagepub.com/articles/A_TROG_ma...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A TROG masked.docUsing T.R.O.G to improve psyc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A discussion on language from a theore...,A discussion on language from a theoretical pe...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038503.v1"", ""URL"": ...",10.31124/advance.7038503.v1,10.31124,10.31124,advance.7038503.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3628,crossref::10.31124/advance.9943040.v1,Advance,crossref,10.31124/advance.9943040.v1,10.31124/advance.9943040.v1,https://doi.org/10.31124/advance.9943040.v1,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Psychiatry and Psychotherapy. The Principle of...,None,None,None,None,posted-content,preprint,preprint,None,True,2019-10-07,2019-10-07,2024-02-22,2024-02-23,None,2019-10-07,None,2019-10-07,None,2019,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by-nc/4.0/,https://creativecommons.org/licenses/by-nc/4.0/,<jats:p>&lt;p&gt; This report considers the d...,This report considers the differences between ...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Chistyakov, Maxim",None,None,"[{""affiliation"": [], ""family"": ""Chistyakov"", ""...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.9943040.v1"", ""URL"": ...",10.31124/advance.9943040.v1,10.31124,10.31124,advance.9943040.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
3629,crossref::10.31124/advance.9933305.v1,Advance,crossref,10.31124/advance.9933305.v1,10.31124/advance.9933305.v1,https://doi.org/10.31124/advance.9933305.v1,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Roma seminomadic tradition between social incl...,None,None,None,None,posted-content,preprint,preprint,None,True,2019-10-04,2019-10-04,2024-02-22,2024-02-23,None,2019-10-04,None,2019-10-04,None,2019,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,"<jats:p>In this research, we try to connect so...","In this research, we try to connect sociology ...","[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Valjarević, Aleksandar; Petrović, Jasmina; Mar...",None,None,"[{""affiliation"": [], ""family"": ""Valjarević"", ""...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.9933305.v1"", ""URL"": ...",10.31124/advance.9933305.v1,10.31124,10.31124,advance.9933305.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
3630,crossref::10.31124/advance.9958760.v1,Advance,crossref,10.31124/advance.9958760.v1,10.31124/advance.9958760.v1,https://doi.org/10.31124/advance.9958760.v1,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Deciding on the timing of early public childca...,None,None,None,None,posted-content,preprint,preprint,None,True,2019-10-14,2019-10-14,2024-02-22,2024-02-23,None,2019-10-14,None,2019-10-14,None,2019,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by-nd/4.0/,https://creativecommons.org/licenses/by-nd/4.0/,<jats:p>This study investigates some of the me...,This study investigates some of the mechanisms...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Steinberg, Hannah; Kleinert, Corinna",None,None,"[{""affiliation"": [], ""family"": ""Steinberg"", ""g...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.9958760.v1"", ""URL"": ...",10.31124/advance.9958760.v1,10.31124,10.31124,advance.9958760.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
3631,crossref::10.31124/advance.9963995.v1,Advance,crossref,10.31124/advance.9963995.v1,10.31124/advance.9963995.v1,https://doi.org/10.31124/advance.9963995.v1,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,QUANTITATIVE EFFECTS OF AUDITORY STIMULATION A...,None,None,None,None,posted-content,preprint,preprint,None,True,2019-11-04,2019-11-04,2024-02-22,2024-02-23,None,2019-11-04,None,2019-11-04,None,2019,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;Objectives&lt;/p&gt;\n\n&lt;p...,Objectives To determine the quantitative effec...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"de Vandeul, marine; Vion-Dury, Jean; Grapperon...",None,None,"[{""affiliation"": [], ""family"": ""de Vandeul"", ""...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.9963995.v1"", ""URL"": ...",10.31124/advance.9963995.v1,10.31124,10.31124,advance.9963995.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
3632,crossref::10.31124/advance.9978302.v1,Advance,crossref,10.31124/advance.9978302.v1,10.31124/advance.9978302.v1,https://doi.org/10.31124/advance.9978302.v1,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Academic Dishonesty among Iranian Students.docx,None,None,None,None,posted-content,preprint,preprint,None,True,2019-11-05,2019-11-05,2024-02-22,2024-02-23,None,2019-11-05,None,2019-11-05,None,2019,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;Recent years have witnessed a...,Recent years have witnessed a growth in academ...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Shahghasemi, Ehsan; Shirzadi Fard, Maysam",None,None,"[{""affiliation"": [], ""family"": ""Shahghasemi"", ...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.9978302.v1"", ""URL"": ...",10.31124/advance.9978302.v1,10.31124,10.31124,advance.9978302.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi

In [16]:
df[df['institution_name'].isna()]['landing_page_url'].tolist()

['https://advance.sagepub.com/articles/The_Privatization_of_Security_and_the_Emergence_of_Private_Security_Companies_in_Crime_Control_in_Nigeria_docx/7037639',
 'https://advance.sagepub.com/articles/Unmet_needs_of_ageing_transgender_and_non-binary_population_An_Overview/7038500',
 'https://advance.sagepub.com/articles/Unmet_needs_of_ageing_transgender_and_non-binary_population_An_Overview/7038500/1',
 'https://advance.sagepub.com/articles/A_TROG_masked_docUsing_T_R_O_G_to_improve_psychotherapy_engagement_when_working_with_Mild_Learning_Disability_Populations/7038503',
 'https://advance.sagepub.com/articles/A_TROG_masked_docUsing_T_R_O_G_to_improve_psychotherapy_engagement_when_working_with_Mild_Learning_Disability_Populations/7038503/1',
 'https://advance.sagepub.com/articles/Are_We_There_Yet_Understanding_Cultural_Issues_and_Making_them_Central_in_Psychology_and_Psychiatry/7038506/1',
 'https://advance.sagepub.com/articles/Are_We_There_Yet_Understanding_Cultural_Issues_and_Making_them_Central_in_Psychology_and_Psychiatry/7038506',
 'https://advance.sagepub.com/articles/review_article_on_literary_archeology_docx/7037660',
 'https://advance.sagepub.com/articles/Advertising_Mortgages_in_the_United_Kingdom_docx/7038554',
 'https://advance.sagepub.com/articles/Call_to_Redefine_Human-Robot_Interaction_From_Social_Robots_to_Gun_Shooting_Humanoids/7039502',
 'https://advance.sagepub.com/articles/Individual_differences_play_an_important_role_in_explaining_human_sexuality_and_its_impact_Upon_Ageing_Successfully/7038512',
 'https://advance.sagepub.com/articles/Individual_differences_play_an_important_role_in_explaining_human_sexuality_and_its_impact_Upon_Ageing_Successfully/7038512/1',
 'https://advance.sagepub.com/articles/A_Snapshot_of_Psycho-social_issues_in_Camp_Living_A_Sri_Lankan_landslide_May_2016_in_the_Kegalle_District_/7038497',
 'https://advance.sagepub.com/articles/A_Snapshot_of_Psycho-social_issues_in_Camp_Living_A_Sri_Lankan_landslide_May_2016_in_the_Kegalle_District_/7038497/1',
 'https://advance.sagepub.com/articles/Ageing_Saudi_Population_in_the_Facebook_Era/7106336',
 'https://advance.sagepub.com/articles/Amir_Forouharfar-_7_JULY_2018-An_Epistemological_Criticism_of_Social_Entrepreneurship-Is_Social_Entrepreneurship_a_Sound_Knowledge_docx/7091927',
 'https://advance.sagepub.com/articles/Amir_Forouharfar-_7_JULY_2018-An_Epistemological_Criticism_of_Social_Entrepreneurship-Is_Social_Entrepreneurship_a_Sound_Knowledge_docx/7091927/1',
 'https://advance.sagepub.com/articles/Green_Spaces_in_the_Context_of_Spatial_Urban_Development_Interrogating_the_Case_of_Federal_Capital_City_of_Nigeria/7105229',
 'https://advance.sagepub.com/articles/Home_ownership_in_Saudi_Arabia_Spatial_Dimensions/7106306',
 'https://advance.sagepub.com/articles/The_Effect_of_Exposure_to_See_the_Sound_Visual_Phonics_STS_VP_in_First_Grade_Literacy_Instruction_on_Academic_Assessment_in_Second_Grade/7127906',
 'https://advance.sagepub.com/articles/Offensive_but_not_so_offensive_Fostering_Ethical_and_Socially_Responsible_Marketing_in_Undergraduate_Marketing_Students/7203266',
 'https://advance.sagepub.com/articles/Examining_Consumer-Brand_Relationships_in_the_UK_Energy_Sector_A_Social_Media_Perspective/7203260',
 'https://advance.sagepub.com/articles/Female_Sexual_Functioning_Self-genital_Image_and_Sexual_Anxiety_Mediating_Role_of_Awareness_the_Moment/7214759',
 'https://advance.sagepub.com/articles/manuscript_pdf/7246865',
 'https://advance.sagepub.com/articles/Prospects_of_Liquefied_Gases_in_Bangladesh_Economy_as_a_move_towards_Fuel_Diversification/7227653',
 'https://advance.sagepub.com/articles/Two-Lines_A_Valid_Alternative_to_the_Invalid_Testing_of_U-Shaped_Relationships_with_Quadratic_Regressions/7222010',
 'https://advance.sagepub.com/articles/A_duality_in_recursion_to_analyse_digital_society/7228325',
 'https://advance.sagepub.com/articles/Neo-Dualism_Formal-Informal-Agriculture_Interactions_in_India/7222031',
 'https://advance.sagepub.com/articles/One_of_the_simplest_ways_to_explain_the_Matthew_effect_in_science_/7218629',
 'https://advance.sagepub.com/articles/Understanding_Flamboyancy_of_Globalization_through_Higher_Educational_Economics_Limkokwing_Integrated_Model_on_Economics_LIME_/7221956',
 'https://advance.sagepub.com/articles/Moderating_Role_of_Demographic_Characteristics_in_Breast_Cancer_Awareness_and_the_Behavioural_Disposition_of_Women_in_Ogun_State_Nigeria/7221722',
 'https://advance.sagepub.com/articles/A_New_Research_Agenda_for_Project_Management_Communication_Theory/7234031',
 'https://advance.sagepub.com/articles/Striving_for_relevance_in_a_competitive_market_The_case_of_Leeds_Becket_University_s_brand_identity/7203275',
 'https://advance.sagepub.com/articles/UK_Universities_Corporate_Visual_Identities/7203269',
 'https://advance.sagepub.com/articles/Fractal_Network_Security_Theory_A_Dynamic_Theory_to_Better_Explain_and_Predict_Information_System_Network_Security_Risks/7235498',
 'https://advance.sagepub.com/articles/Normative_Political_Science_-_as_Constituted_by_the_Formal_Axiology_of_Robert_S_Hartman_and_David_Easton_s_Concept_of_the_Political_System/7293638',
 'https://advance.sagepub.com/articles/The_Social_Construction_of_Organizational_Learning_Examining_The_Epistemology_of_Master_Degree_Curricula/7218545',
 'https://advance.sagepub.com/articles/Emotional_Facial_Processing_Does_Cognitive_Load_Make_a_Difference_/7295918',
 'https://advance.sagepub.com/articles/Who_knows_where_the_time_goes_/7294664',
 'https://advance.sagepub.com/articles/Factors_Associated_with_Belief_in_Conspiracies_about_HIV_AIDS_among_HIV-Positive_African-American_Patients/7291883',
 'https://advance.sagepub.com/articles/Understanding_the_Adjustment_Needs_of_International_Graduate_Students/7300316',
 'https://advance.sagepub.com/articles/Leadership_Styles_and_Organizational_Agility_Relationship_in_Science_Parks_An_Industry_4_0_Perspective/7291055',
 'https://advance.sagepub.com/articles/Security_Threats_and_Risk_Management_for_Online_Transactions_an_evaluation_of_a_business_project_in_Samoa/7256468',
 'https://advance.sagepub.com/articles/HR_a_Profit_Center/7304177',
 'https://advance.sagepub.com/articles/Effective_Placements_for_Students_with_Disabilities/7304183',
 'https://advance.sagepub.com/articles/Exploration_of_Psychodynamics_Of_Substance_Users_by_Thematic_Apperception_Test/7235966',
 'https://advance.sagepub.com/articles/How_a_transformational_Collective_Benefit_Mindset_experience_prompted_parents_raising_children_with_disability_to_launch_a_peer_network/7312796',
 'https://advance.sagepub.com/articles/Developing_Open_Business_Models_in_Existing_and_New_Businesses_in_the_FMCG_Industry/7325069',
 'https://advance.sagepub.com/articles/North_East_India_s_Tryst_with_Rubber-_A_Saga_of_Missing_Innovation/7325153',
 'https://advance.sagepub.com/articles/Labels_and_beyond_Mapping_the_ways_national_Danish_news_brands_signal_commercial_intent_to_users_in_their_online_editorial-looking_adverts/7327178',
 'https://advance.sagepub.com/articles/Hate_Speech_Twitter_and_2019_Election_Analysis_of_Tweeting_Habits_of_Selected_Politicians_in_Kaduna_State/7325756',
 'https://advance.sagepub.com/articles/Correlates_of_Caesarean_Section_Deliveries_Evidence_from_Indonesia/7331384',
 'https://advance.sagepub.com/articles/In_the_absence_of_values_and_ideologies_Party-switching_in_Nigeria_is_inevitable_/7339136',
 'https://advance.sagepub.com/articles/Bipolar_A_creative_nonfiction_story_about_mental_health_and_education/7238024',
 'https://advance.sagepub.com/articles/Edutocracy_The_new_West_Indian_plantocracy_/7359473',
 'https://advance.sagepub.com/articles/Earmarks_Motivation_for_the_U_S_Congress_Continued_Use_of_Omnibus_Appropriations_Bills_in_the_Budget_Process/7361252',
 'https://advance.sagepub.com/articles/An_Association_Rule_General_Analytic_System_ARGAS_for_hypothesis_testing_and_data_mining_applications/7336763',
 'https://advance.sagepub.com/articles/Psychodynamic_Theory_and_Therapy_of_Male_Pedophilia_The_Role_of_Object_Relations_Structural_Conflicts_and_Narcissism/7330934',
 'https://advance.sagepub.com/articles/The_Effect_of_Aerobic_Training_and_Vitamin_D_Supplements_on_the_Neurocognitive_Functions_of_Elderly_Women_with_Sleep_Disorders/7370024',
 'https://advance.sagepub.com/articles/The_Refugee_Experience_of_Social_Cohesion_in_Asif_Currimbhoy_s_The_Refugee/7371044',
 'https://advance.sagepub.com/articles/An_Axiomatic_Approach_to_Justice_as_Fairness/7379624',
 'https://advance.sagepub.com/articles/The_Corporate_War_Dead_Swed_et_al_2018_Armed_Forces_Society_pdf/7290098',
 'https://advance.sagepub.com/articles/Renewable_Energy_in_Australia_Policy_Regulation_and_Institutions/7367153',
 'https://advance.sagepub.com/articles/Numeration_of_Value/7379711',
 'https://advance.sagepub.com/articles/Assessment_of_Emotional_Management_ability_a_Rasch_Model_Analysis_of_the_brief_Situational_Test_of_Emotional_Management_STEM-B_/7371086',
 'https://advance.sagepub.com/articles/Development_and_Validation_of_the_Multidimensional_Scale_of_Turnover_Reasons/7367135',
 'https://advance.sagepub.com/articles/Teacher_Retention_Why_They_Stay/7403942',
 'https://advance.sagepub.com/articles/Analyzing_Dependent_Variables_with_Multiple_Surrogates_in_Accounting_Research/7409417',
 'https://advance.sagepub.com/articles/Teacher_Evaluation_Rationale_Issues_and_General_Principles/7415189',
 'https://advance.sagepub.com/articles/Complex_Adaptive_Leadership_for_Organization_and_Human_Development/7370426',
 'https://advance.sagepub.com/articles/Deprivation_of_Freedom_Deprivation_of_Dignity_Understanding_Incarceration_Violence/7290107',
 'https://advance.sagepub.com/articles/Feminist_perspective_in_Foreign_Policy_A_way_to_women_s_visibility_and_participation_in_public_sphere/7327037',
 'https://advance.sagepub.com/articles/Not_my_reality/7427906',
 'https://advance.sagepub.com/articles/The_effective_of_task_based_lanmguage_teaching_on_reading_for_advanced_learners_in_Cyprus/7381886',
 'https://advance.sagepub.com/articles/Improving_financial_access_to_rural_business_An_impact_evaluation_of_Mexico_s_credit_guarantee_programs/7293926',
 'https://advance.sagepub.com/articles/Stakeholder_Analysis_as_a_Tool_for_Systems_Approach_Research_in_HRD/7433933',
 'https://advance.sagepub.com/articles/EXPLOITING_POSITIVE_RISK_THROUGH_ORGANIZATIONAL_CULTURE_AND_PROACTIVE_IDENTIFICATION/7450829',
 'https://advance.sagepub.com/articles/The_effects_of_Oil_Price_Shock_on_the_Indian_Economy_A_Study/7440323',
 'https://advance.sagepub.com/articles/Fiscal_Policy_and_Economic_Growth_in_Oil-based_economies_The_case_of_Libya/7440674',
 'https://advance.sagepub.com/articles/Social_C_apital_and_Women_s_Entrepreneurship/7451009',
 'https://advance.sagepub.com/articles/Peer_Effects_Civic_Learning_and_Youth_Civic_Engagement/7450973',
 'https://advance.sagepub.com/articles/Validation_of_the_Speeded_Cloze-Elide_Test_as_an_Overall_Measure_of_Proficiency_in_English_as_a_Foreign_Language/7295651',
 'https://advance.sagepub.com/articles/Validation_of_the_Speeded_Cloze-Elide_Test_as_an_Overall_Measure_of_Proficiency_in_English_as_a_Foreign_Language/7295651/1',
 'https://advance.sagepub.com/articles/GSM_BASED_AGROBOT_WITH_AUTOMATIC_SUN_TRACKING_SOLAR_PANEL/7473173',
 'https://advance.sagepub.com/articles/MIgrations_in_the_modern_world_and_their_implications_for_security_policy_of_the_Transatlantic_community_/7460993',
 'https://advance.sagepub.com/articles/Setting_a_Strong_Foundation_for_Music_Students_within_Jackson_Public_Schools_docx/7461773',
 'https://advance.sagepub.com/articles/The_Ecological_System_of_Innovation_A_New_Architectural_Framework_for_a_Functional_Evidence-Based_Platform_for_Science_and_Innovation_Policy/7367138',
 'https://advance.sagepub.com/articles/Improving_NHS_investigation_of_patient_safety_incidents/7504265',
 'https://advance.sagepub.com/articles/Digital_Piety_in_Bangladesh_A_Psychosocial_Analysis/7542908',
 'https://advance.sagepub.com/articles/Digital_Public_Sphere_of_Bangladesh_Religious_Confrontation_and_Domination/7569038',
 'https://advance.sagepub.com/articles/Digital_Media_in_Electoral_Participation_A_Study_of_Bangladesh_Election_2018/7580270',
 'https://advance.sagepub.com/articles/Brand_Guideline/7582217',
 'https://advance.sagepub.com/articles/The_Connection_of_Sexual_Harassment_with_Life_Satisfaction_The_Mediating_Role_of_Educational_Involvement/7611359',
 'https://advance.sagepub.com/articles/Inclusion_for_Special_Education_in_Northern_Ireland/7610927',
 'https://advance.sagepub.com/articles/Translators_Agency_in_the_Translation_Network_of_Chinese_Literature/7619006',
 'https://advance.sagepub.com/articles/A_Multidimensional_Practical_Approach_to_Corporate_Social_Responsibility_A_Conceptual_Framework/7621922',
 'https://advance.sagepub.com/articles/Together_we_Can_Collective_Organization_of_Artists_in_Beijing/7376105',
 'https://advance.sagepub.com/articles/DEVELOPMENT_AND_EVALUATION_OF_DoCtor_WoRM_S_MODULE_IN_IMPROVING_MULTIPLICATION_SKILLS_AMONG_YEAR_FOUR_LOW_ACHIEVERS/7609058',
 'https://advance.sagepub.com/articles/ANALYSIS_OF_WELFARE_IN_INDONESIA_CASE_STUDY_IN_2008-2017/7445900',
 'https://advance.sagepub.com/articles/Emerging_adults_family_relationships_in_the_21st_century_A_systematic_review/7608989',
 'https://advance.sagepub.com/articles/On_equity_disadvantage_and_non-nativeness_as_a_red_herring/7692536',
 'https://advance.sagepub.com/articles/Father_Figure_and_Relationship_with_Mother_of_Individual_Who_Experiences_Possession_Disorder/7440803',
 'https://advance.sagepub.com/articles/Psychometric_Evaluation_of_the_Mating_Intelligence_Scale_in_Iran/7528775',
 'https://advance.sagepub.com/articles/Human_Rights_in_the_Big_Data_World/7729277',
 'https://advance.sagepub.com/articles/The_case_for_short_observations/7718435',
 'https://advance.sagepub.com/articles/A_Listening_Guide_Analysis_of_Eastern-Western_Women_s_Sexual-Self_Concept/7749638',
 'https://advance.sagepub.com/articles/What_constitutes_the_democratic_quality_of_elections_Evidence_from_Nigeria/7751117',
 'https://advance.sagepub.com/articles/I_Shall_Not_Be_Prey_Instilling_Perceived_Self-Efficacy_Through_Personal_Security_Training/7749641',
 'https://advance.sagepub.com/articles/Transportation_habits_of_students_at_UCOL_An_assessment_of_carbon_footprint/7749671',
 'https://advance.sagepub.com/articles/Preventing_Policy_Capture_and_Promoting_the_Public_Interest_in_Policy_Making_-_Lessons_for_Botswana/7751885',
 'https://advance.sagepub.com/articles/Impact_of_Social_and_Environmental_Practices_on_SME_Business_Performance/7749695',
 'https://advance.sagepub.com/articles/IMPACT_OF_INTELLIGENCE_AND_ANTHROPOLOGICAL_CHARACTERISTICS_IN_GYMNASTICS_PERFORMANCE/7756217',
 'https://advance.sagepub.com/articles/Growth_Limits_A_Conceptual_Analysis_for_Sustainable_Development_in_Nigeria/7762049',
 'https://advance.sagepub.com/articles/Psychometric_Properties_of_Self-Regulating_Climate_Questionnaire_Comparison_of_Self-Regulatory_Climate_in_Gifted_and_Public_Schools/7762715',
 'https://advance.sagepub.com/articles/Exploring_Quota_Identity_Processes_From_Ascription_to_Avowal/7762763',
 'https://advance.sagepub.com/articles/The_Collision_Impact_Integration_and_Globalization_of_Eastern_and_Western_Sports_Culture/7762787',
 'https://advance.sagepub.com/articles/Children_in_Foster_Care_Looked_After_Children_and_Education_A_Review_of_the_Literature_in_the_UK/7764425',
 'https://advance.sagepub.com/articles/Self-leadership_Training_Review/7771175',
 'https://advance.sagepub.com/articles/The_Making_of_a_Model_Teacher_Education_for_Looked_After_Children/7764464',
 'https://advance.sagepub.com/articles/Integration_and_Development_of_Generic_Competencies_into_Malaysian_Higher_Education_Context_Review_of_the_Literature/7763687',
 'https://advance.sagepub.com/articles/The_Effect_of_The_Using_of_Computer_Games_On_Academic_Success_In_Teaching_English_To_8th_Grade_Students/7775678',
 'https://advance.sagepub.com/articles/The_meaning_of_bereavement_following_spousal_loss_-_a_qualitative_study_of_the_experiences_of_older_adults/7750991',
 'https://advance.sagepub.com/articles/Likert_Scale_Misuse_of_Mid-Point_Anchor/7765463',
 'https://advance.sagepub.com/articles/A_Conceptual_Framework_of_the_Relationship_between_Team_Trust_and_Loyalty_toward_the_Sponsor_s_Brand_The_Mediating_Role_of_Team_Identification/7756211',
 'https://advance.sagepub.com/articles/Understanding_Marginalized_Students_Identities_Work_and_Their_Learning_Experiences_in_English_Language_Arts_Classrooms/7808876',
 'https://advance.sagepub.com/articles/Inter-Governmental_Fiscal_Transfers_in_the_Presence_of_Revenue_Uncertainty_The_Case_of_Goods_and_Services_Tax_GST_in_India/7790120',
 'https://advance.sagepub.com/articles/Route_88_Bike_Caf_From_Planning_to_Operations_and_Entrepreneurial_Finance/7796846',
 'https://advance.sagepub.com/articles/Forward_linkages_for_integrated_farming_practices_A_case_study_of_Konyoka_Multi-Purpose_Organic_Agriculture_Farm_Society_of_Biswanath_district_of_Assam_India/7803809',
 'https://advance.sagepub.com/articles/The_Measurement_Of_The_Level_Of_Compassion_Of_Nurses_In_Operating_Room/7797569',
 'https://advance.sagepub.com/articles/Real_Options_Connecting_Theory_to_Data_Modeling_Actively_Traded_Philippine_Universal_Banks/7823195',
 'https://advance.sagepub.com/articles/The_American_Citizen_who_plays_Tennis_Analysis_of_the_Highest-Paid_Female_Athletes_over_ten_years_period/7825109',
 'https://advance.sagepub.com/articles/The_Personal_is_the_Political_in_Tara_a_play_by_Mahesh_Dattan/7824770',
 'https://advance.sagepub.com/articles/Entrepreneurial_opportunity_decisions_under_uncertainty_Conceptualizing_the_complementing_role_of_personal_and_cognitive_abilities/7291277',
 'https://advance.sagepub.com/articles/Characterizing_Financial_Literacy_in_light_of_Primary_and_Secondary_School_Syllabus_in_Tanzania/7854923',
 'https://advance.sagepub.com/articles/Oriental_Approach_An_Enquiry_of_S_L_Bhyrappa_s_Scion/7823636',
 'https://advance.sagepub.com/articles/Student_engagement_research_2010-2018_continuity_and_emergence/7871984',
 'https://advance.sagepub.com/articles/The_Case_of_Mileva_Mari_Was_Einstein_s_First_Wife_His_Secret_Collaborator_/7873304',
 'https://advance.sagepub.com/articles/Human_Resource_Development_and_Executive_Leadership_Succession_Planning_in_Nonprofits/7910552',
 'https://advance.sagepub.com/articles/Enhancing_economic_subsistence_diversification_activities_and_labor_intensification_as_economic_setback_mitigation_in_upland_agriculture_communities/7915238',
 'https://advance.sagepub.com/articles/Rights_through_Resistance_What_lies_beyond_Legalism_for_the_LGBT_Movement_/7938464',
 'https://advance.sagepub.com/articles/Rights_through_Resistance_What_lies_beyond_Legalism_for_the_LGBT_Movement_/7938464/1',
 'https://advance.sagepub.com/articles/Reinventing_Governance_from_Centralisation_to_Decentralisation_The_need_for_a_new_direction_for_Ghana_s_local_government_system/7926995',
 'https://advance.sagepub.com/articles/Screenwriting_Empathy_and_Multi-cultural_ethics/7791296',
 'https://advance.sagepub.com/articles/Empirical_evidence_of_a_long-run_relationship_between_agriculture_and_manufacturing_industry_output_in_Nigeria/7952954',
 'https://advance.sagepub.com/articles/The_effect_of_community_pharmacist_education_and_training_on_medication_dispensing_and_counselling/7769456',
 'https://advance.sagepub.com/articles/Measuring_the_efficacy_and_quality_of_a_professional_development_training_on_prejudice_reduction_and_reflective_practice_Transforming_the_delivery_of_change_through_collective_insight_and_informed_action_/7794263',
 'https://advance.sagepub.com/articles/Evaluating_Cross-Country_Policy_Learning_in_Public_Administration_The_Case_of_Qatar-Singapore_Partnership_in_Regional_Training_Centre_for_Public_Administration_RTCPA_/7963694',

In [17]:
df[df['institution_name']=='Advance']['landing_page_url'].tolist()

['https://advance.sagepub.com/articles/preprint/Stress_Scale_in_the_Context_of_Online_Learning_among_Junior_High_School_Students_ages_11-17_Development_Validity_and_Reliability/15020103',
 'https://advance.sagepub.com/articles/preprint/Gifted_Programming_Identification_Procedures_A_Hidden_Curriculum/15040629',
 'https://advance.sagepub.com/articles/preprint/Gendered_Justice_The_Impact_of_Gender_on_Criminal_Justice_Policies_and_Legislation_throughout_the_United_Kingdom/15042804',
 'https://advance.sagepub.com/articles/preprint/Maximization_of_Female_Contribution_in_Global_Workforce/15043020',
 'https://advance.sagepub.com/articles/preprint/_Only_I_have_to_help_myself_Indian_Migrant_Workers_Plight_During_COVID-19_Lockdown/15047967',
 'https://advance.sagepub.com/articles/preprint/_Only_I_have_to_help_myself_Indian_Migrant_Workers_Plight_During_COVID-19_Lockdown/15047967/1',
 'https://advance.sagepub.com/articles/preprint/Changes_in_General_and_Specific_Teacher_Self-Efficacy_Related_to_Professional_Development_Follow-up_Assignment_and_Career_Stage/15016746',
 'https://advance.sagepub.com/articles/preprint/Ethical_Concerns_in_Clinical_Psychology_A_Brief_Account_of_Challenges_in_Pakistan/15052239',
 'https://advance.sagepub.com/articles/preprint/The_Inference_of_Transparency_in_Effective_Team_Management_In_the_IT_Industry/15021138',
 'https://advance.sagepub.com/articles/preprint/Who_Benefit_from_What_Media_Examining_Knowledge_Gap_Hypothesis_on_Environmental_Knowledge_In_China/15070947',
 'https://advance.sagepub.com/articles/preprint/The_Socio-economic_Implications_of_COVID-19_A_Mini_Systematic_Review/15059940',
 'https://advance.sagepub.com/articles/preprint/The_Socio-economic_Implications_of_COVID-19_A_Mini_Systematic_Review/15059940/1',
 'https://advance.sagepub.com/articles/preprint/Analyzing_Media_Dependency_During_Crisis_A_case_of_COVID-19_in_Malaysia/15105678',
 'https://advance.sagepub.com/articles/preprint/The_devil_in_the_number_Rethinking_Garrett_Hardin_s_The_tragedy_of_the_commons_and_global_overpopulation_crisis/12795017',
 'https://advance.sagepub.com/articles/preprint/Video_versus_in_person_hearings_Determining_witness_credibility/15094164',
 'https://advance.sagepub.com/articles/preprint/The_Value_Relevance_of_Financial_Metrics_to_Publicly_Listed_Firms_Evidence_from_Large-_Mid-_and_Small-Cap_Firms_Listed_in_NYSE_and_NSDAQ/15110391',
 'https://advance.sagepub.com/articles/preprint/Artificial_Intelligence_as_the_New_Realm_for_Online_Advertising/15139863',
 'https://advance.sagepub.com/articles/preprint/Worry_perceived_discrimination_lifestyle_changes_and_protective_factors_among_recovering_patients_of_COVID-19_A_mental_health_intervention_based_study_in_Delhi_India/15149538',
 'https://advance.sagepub.com/articles/preprint/The_connection_of_committing_and_experiencing_cyber-bullying_peer_violence_with_depression_anxiety_and_stress_in_high_school_students/15155820',
 'https://advance.sagepub.com/articles/preprint/FINANCIAL_LITERACY_AND_CONSUMER_FINANCIAL_WELL-BEING_IN_GHANA_ANY_NEXUS_WITH_MARCO-ECONOMIC_STABILITY_/15168984',
 'https://advance.sagepub.com/articles/preprint/PSYCHOLOGICAL_HELP_PREFERENCES_TEST_AND_MOTIVATION_OF_UKRAINIAN_VETERANS_WITH_THE_USE_OF_DESIGNED_TEST_NAMED_10_Questions_from_Voronin_AND_ZEIGARNIK_EFFECT_/15172761',
 'https://advance.sagepub.com/articles/preprint/_Securing_the_Music_Industry_Talent_Pipeline_An_Analysis_of_the_Dimensions_and_Conceptual_Policy_Context/14854338',
 'https://advance.sagepub.com/articles/preprint/Visual_Analysis_of_Twitter_Data_to_Support_Decision-Making_in_Law_Enforcement_An_Analytical_Study_of_COVID-19/15015882',
 'https://advance.sagepub.com/articles/preprint/A_Social-Ecological_Analysis_of_Barriers_to_Sports_and_Physical_Activity_for_Female_University_Students_in_China/15982128',
 'https://advance.sagepub.com/articles/preprint/Implementation_of_solid_waste_management_policies_in_Kenya_challenges_and_opportunities/16437345',
 'https://advance.sagepub.com/articles/preprint/Gender_Equity_Women_Education_and_National_Development_in_Nigeria/16438317',
 'https://advance.sagepub.com/articles/preprint/Food_Aid_in_the_Form_of_Food_for_Education_-_A_Critical_Analysis_between_the_Food_for_Schooling_Programme_and_the_School_Feeding_Programme_in_Maslow_s_and_Dependency_Theorist_s_Perspectives/16441911',
 'https://advance.sagepub.com/articles/preprint/Effect_of_Groundwater_Stress_on_Farmers_Livelihood_Assets_Evidence_from_Northwestern_Region_of_Bangladesh/16457931',
 'https://advance.sagepub.com/articles/preprint/The_Negation_of_Impossibility/11473305',
 'https://advance.sagepub.com/articles/preprint/Denton_s_Temporal_Disaggregation_Methods_with_the_Application_of_Bangladesh_s_Annual_Gross_Domestic_Product_for_Quarterly_Benchmarking_and_Forecasting/16437096',
 'https://advance.sagepub.com/articles/preprint/Socio-Political_Imaginings_of_the_Kolkata_Maidan/16445814',
 'https://advance.sagepub.com/articles/preprint/Teaching_with_Digital_Technology_and_the_Impact_on_Pedagogical_Changes/16528959',
 'https://advance.sagepub.com/articles/preprint/Economic_Policies_to_Curb_Global_Warming_-_A_Case_of_Papua_New_Guinea/16529130',
 'https://advance.sagepub.com/articles/preprint/The_Intersectional_Nature_of_Educational_Inequality_in_the_Global_South_-_A_Case_of_Papua_New_Guinea/16529157',
 'https://advance.sagepub.com/articles/preprint/The_effect_of_practicing_skills_with_different_coordination_requirements_on_the_executive_functions_of_9_to_10_year_old_girls/16529595',
 'https://advance.sagepub.com/articles/preprint/Developing_Hospitality_Travel_and_Tourism_Industry_through_University_Curriculum_Assessed_Internship_Programs_and_Part-Time_Work_Schemes_/16534239',
 'https://advance.sagepub.com/articles/preprint/Towards_the_Development_of_a_Caribbean-Centric_Social_Work_Perspective_Imperatives_for_Social_Work_in_the_English-speaking_Caribbean/16539690',
 'https://advance.sagepub.com/articles/preprint/Resource_Allocation_Modalities/16557798',
 'https://advance.sagepub.com/articles/preprint/Exploring_the_Climate_In_Action_in_Turkey_Using_Human_Values_Theory_on_Energy_Policymakers/16558161',
 'https://advance.sagepub.com/articles/preprint/Intersectional_Identities_School_Resources_and_Law_Enforcement_A_Study_of_Discipline_Disparity_in_Public_High_Schools/16559433',
 'https://advance.sagepub.com/articles/preprint/Looking_Back_at_the_Pandemic_Onset_Twitter_Chatter_Reflects_Changes_in_Alcohol_Themes/16556427',
 'https://advance.sagepub.com/articles/preprint/Technology_and_Reading_The_Effects_of_CALL_Glossing/12407699',
 'https://advance.sagepub.com/articles/preprint/Missing_values_in_exploratory_factor_analysis_A_best_of_all_possible_worlds_approach_to_imputation_for_incomplete_survey_data/13570598',
 'https://advance.sagepub.com/articles/preprint/Improving_the_training_of_air_traffic_controllers_Opinions_from_instructors_in_Singapore/16575023',
 'https://advance.sagepub.com/articles/preprint/Explaining_Presidential_Approval_1993-2020_An_Examination_of_the_Clinton_Bush_Obama_and_Trump_Presidencies/16575062',
 'https://advance.sagepub.com/articles/preprint/Mixing_the_implicit_A_Linear_Mixed-Effects_Models_approach_for_a_Rasch_analysis_of_the_Implicit_Association_Test_and_the_Single_Category_Implicit_Association_Test/16592579',
 'https://advance.sagepub.com/articles/preprint/Internal_Conflict_Displacement_Galore_in_the_Horn_of_Africa_Ethiopia_on_the_Radar/16601102',
 'https://advance.sagepub.com/articles/preprint/Feasibility_of_integrating_mental_health_screening_into_youth_HIV_Care_in_a_Low-Middle_Income_Country_Setting/16602212',
 'https://advance.sagepub.com/articles/preprint/Scientific_reports_6-2021_docx/16575311',
 'https://advance.sagepub.com/articles/preprint/Teachers_Efficacy_Knowledge_and_Professional_Development_in_the_Implementation_of_Character_Education/16625665',
 'https://advance.sagepub.com/articles/preprint/Vicious_Cycle_of_Economic_Growth_Pm2_5_and_COVID-19_Case_of_G7_Countries/12937019',
 'https://advance.sagepub.com/articles/preprint/Social_Capital_Participation_in_Public-Private_Partnership_Projects_in_China_Do_Government_Credit_Risks_Matter_/16640365',
 'https://advance.sagepub.com/articles/preprint/A_novel_technique_of_detecting_DIF_in_items_using_z-score_based_on_IRT_model/16577309',
 'https://advance.sagepub.com/articles/preprint/Third_Cold_War_What_to_Beware_How_to_Resolve/16610401',
 'https://advance.sagepub.com/articles/preprint/Countering_Islamic_State_And_Al_Qaeda_s_Ideological_Doctrines/16654822',
 'https://advance.sagepub.com/articles/preprint/A_Critical_History_of_Public_Rational_Inflation_Expectations_Rethinking_its_Foundations/16669366',
 'https://advance.sagepub.com/articles/preprint/USING_CRITICAL_GEOPOLITICAL_RESEARCH_TO_ANALYZE_AND_UNDERSTAND_THE_ISRAELI_OCCUPATION_OF_PALESTINE/16635850',
 'https://advance.sagepub.com/articles/preprint/Implicit_social_cognition_through_years_The_Implicit_Association_Test_at_age_21/11914416',
 'https://advance.sagepub.com/articles/preprint/A_Muse_Mashup_Dabrowski_s_TPD_and_an_Eisner-esque_Approach_to_Gifted_Education/16686148',
 'https://advance.sagepub.com/articles/preprint/Factors_Affecting_Students_Dropout_Rate_During_COVID-19/16728967',
 'https://advance.sagepub.com/articles/preprint/Imagining_a_Writing_Centre_for_Meeting_Student_Needs/16747831',
 'https://advance.sagepub.com/articles/preprint/Consequences_of_Choice_Exploring_Successful_and_Unsuccessful_Decision-Making_Attributes_in_UK_Homicide_Investigations/16755595',
 'https://advance.sagepub.com/articles/preprint/Alternative_Basic_Education_teaching_and_learning_of_adults_through_virtual_means_in_Peru/16776178',
 'https://advance.sagepub.com/articles/preprint/Global_Travel_Restriction_s_Effect_on_The_Number_of_Deaths_from_COVID_-_19_An_Analysis_on_Global_COVID-19_Data/16679731',
 'https://advance.sagepub.com/articles/preprint/Determinative_Factors_of_Customer_Satisfaction_with_Local_Government_Offices_Counter_Services_On-site_Survey_Examining_Service_Quality_at_Higashihiroshima_City_Hall/16644808',
 'https://advance.sagepub.com/articles/preprint/The_Emergence_of_Multilingual_Education_in_India_Issues_Related_to_Media_of_Instruction_in_Border_Areas_of_Telangana_Schools/16744165',
 'https://advance.sagepub.com/articles/preprint/Duke_of_Edinburgh_International_Award_Accomplishment_and_Academic_Achievement_A_Two_Year_Study_in_a_Malaysian_International_School/14931597',
 'https://advance.sagepub.com/articles/preprint/Upliftment_of_Societal_Lockdown_by_Indian_Government_amid_CoVID-19_crisis_Boon_for_some_and_Bane_for_others/14806377',
 'https://advance.sagepub.com/articles/preprint/Preprint_pdf/16835335',
 'https://advance.sagepub.com/articles/preprint/Exploring_the_use_of_continuous_assessment_in_the_context_of_outcome-based_education_in_Malawian_primary_schools/16803178',
 'https://advance.sagepub.com/articles/preprint/_I_will_show_the_man_pepper_Factors_underlying_Male_Spousal_Abuse_in_Lagos_Metropolis/16830772',
 'https://advance.sagepub.com/articles/preprint/The_Role_of_Authenticity_in_Developing_Successful_Leadership_Practices_A_Review_of_Literature/16826749',
 'https://advance.sagepub.com/articles/preprint/The_Bridges_of_Ideas_Transnational_Network_of_the_Book_Program_for_Eastern_Europe_1956-1990/16802677',
 'https://advance.sagepub.com/articles/preprint/Food_security_where_is_thy_fifth_dimension_A_comparative_analysis_of_the_four_dimensions_food_security_framework_from_the_lens_of_West_African_smallholder_farmers/16661446',
 'https://advance.sagepub.com/articles/preprint/The_Moderating_Role_of_Institutional_Quality_in_Developed_Countries_on_the_Strategic_Asset_Seeking_SAS_Inward_FDI_from_China_A_De-globalization_Perspective/16863616',
 'https://advance.sagepub.com/articles/preprint/Organizational_use_of_Social_Media_and_its_impacts_on_Politics_Evidence_from_Pakistan/16862542',
 'https://advance.sagepub.com/articles/preprint/Simulated_Computer_Adaptive_Testing_Administration_with_Remote_Proctoring_for_Offsite_Assessment_in_Mathematics/16866289',
 'https://advance.sagepub.com/articles/preprint/Sustainable_Leadership_A_Phenomenological_Study_of_CEO_Wellbeing/16685545',
 'https://advance.sagepub.com/articles/preprint/Insights_into_the_impact_of_the_pandemic_on_early_career_researchers_the_case_of_remote_teaching/16870627',
 'https://advance.sagepub.com/articles/preprint/Developmental_competencies_temperament_parenting_practices_and_psychosocial_adversities_in_internalizing_disorders/16836700',
 'https://advance.sagepub.com/articles/preprint/Understanding_Sexual_and_Gender-Based_Violence_through_an_Adolescent_Lens-_Qualitative_Findings_from_New_Delhi_India/16902772',
 'https://advance.sagepub.com/articles/preprint/Covid-19_Prevention_Level_and_Determinants_of_Knowledge_Attitude_and_Practice_toward_WHO_Recommended_Covid-19_Prevention_Measures_Among_Harar_Population_Eastern_Ethiopia_A_Community-Based_Cross-Sectional_Study/16803607',
 'https://advance.sagepub.com/articles/preprint/THE_EFFECTS_OF_SERVICE_QUALITY_ON_CUSTOMER_SATISFACTION_IN_HIGHER_LEARNING_INSTITUTIONS_IN_TANZANIA_/16906636',
 'https://advance.sagepub.com/articles/preprint/Spain_1935_A_lost_opportunity/16855000',
 'https://advance.sagepub.com/articles/preprint/PESTLE_ANALYSIS_OF_ORGANIZED_RETAILING_IN_INDIA/16653532',
 'https://advance.sagepub.com/articles/preprint/Understanding_Peacebuilding_and_State_Building_Post-Conflict_African_Challenge/13580504/1',
 'https://advance.sagepub.com/articles/preprint/Understanding_Peacebuilding_and_State_Building_Post-Conflict_African_Challenge/13580504',
 'https://advance.sagepub.com/articles/preprint/Understanding_Peacebuilding_and_State_Building_Post-Conflict_African_Challenges/13586033',
 'https://advance.sagepub.com/articles/preprint/Organisational_restructuring_of_Indian_Railways/12152124',
 'https://advance.sagepub.com/articles/preprint/The_Up-scaling_Organization_Structure_Design_an_Axioms_Based_Concept/16988176',
 'https://advance.sagepub.com/articles/preprint/RELATIONSHIP_BEHAVIOR_PATTERNS_IN_IMPROVING_EDUCATIONAL_SERVICES-_ROBBINS_ORGANIZATIONAL_BEHAVIOR_PERSPECTIVE/17004781',
 'https://advance.sagepub.com/articles/preprint/Evaluation_of_MirMe_Online_Assessment_for_21st_Century_Skills_Situational_Intelligence_SQ_and_online_psychometric_assessment_of_21st_century_skills/16988389',
 'https://advance.sagepub.com/articles/preprint/International_Clout_in_the_Political_Salience_of_Traditional_Leadership_in_South_Africa/17009369',
 'https://advance.sagepub.com/articles/preprint/Integrating_Community_Participation_with_Interpretative_Phenomenological_Analysis_Reflections_on_Engaging_the_Autism_Community/14346908',
 'https://advance.sagepub.com/articles/preprint/Issue-Driven_Progress_in_Business_Ethics_When_the_Responsibility_to_Protect_Values_Requires_Companies_to_Introduce_New_Norms/14983848',
 'https://advance.sagepub.com/articles/preprint/American_Attitudes_toward_COVID-19_More_Trumpism_than_Partisanship/14481879',
 'https://advance.sagepub.com/articles/preprint/Reflections_on_trauma_A_phenomenological_qualitative_secondary_analysis_of_archived_interviews_about_adolescent_experiences_during_the_1970_Kent_State_student_shootings/13477755',
 'https://advance.sagepub.com/articles/preprint/Gender_and_feminist_considerations_in_Artificial_Intelligence_from_a_developing-world_perspective_with_India_as_a_case_study/17054936',
 'https://advance.sagepub.com/articles/preprint/Towards_Small_Business_Excellence_The_Role_of_Talent_Management_Organizational_Culture_and_Synergized_Innovative_Climate_Synergized_Innovative_Climate/16896208',
 'https://advance.sagepub.com/articles/preprint/Knowledge_Levels_of_Teachers_with_Refugee_Students_in_Their_Class_Related_to_Classroom_Management/14579748',
 'https://advance.sagepub.com/articles/preprint/Sub-Saharan_Africa_s_Biomedical_Journal_Coverage_in_Scholarly_Databases_A_comparison_of_Web_of_Science_Scopus_EMBASE_PubMed_African_Index_Medicus_and_AfricanJournals_Online/17082719',
 'https://advance.sagepub.com/articles/preprint/Bourdieu_and_the_quest_for_intercultural_transformations/13047995',
 'https://advance.sagepub.com/articles/preprint/Development_and_Validation_of_the_Aesthetic_Competence_Scale/17075180',
 'https://advance.sagepub.com/articles/preprint/The_Nexus_between_Bad_Governance_Ungoverned_Spaces_and_Terrorism_Analysing_the_Boko_Haram_Insurgency_in_the_Lake_Chad_Basin_through_the_lenses_of_the_Social_Contract_Theory/17078045',
 'https://advance.sagepub.com/articles/preprint/PANCASILA_DEMOCRACY_VERSUS_DIRECT_DEMOCRACY_A_REVIEW_OF_THE_CONCEPT_OF_CIVIL_SOCIETY/17085155',
 'https://advance.sagepub.com/articles/preprint/Between-school_inequalities_in_access_to_STEM_curricula_in_a_marketized_education_system_The_case_of_Australia/17099393',
 'https://advance.sagepub.com/articles/preprint/Neither_a_Conscript_Army_nor_an_All-Volunteer_Force_Emerging_recruiting_models/14131766',
 'https://advance.sagepub.com/articles/preprint/Can_conservatism_make_women_more_vulnerable_to_violence_/13960661',
 'https://advance.sagepub.com/articles/preprint/Adolescents_Lockdown-Induced_Coping_Experiences_ALICE_study_A_qualitative_exploration_of_early_adolescents_experiences_of_lockdown_and_reintegration/14046032',
 'https://advance.sagepub.com/articles/preprint/Social_well-being_at_school_Development_and_validation_of_a_scale_for_Primary_Education_students/11708949',
 'https://advance.sagepub.com/articles/preprint/Quality_of_life_and_psychosocial_risk_in_migrant_workers_from_the_Region_of_Maule_Chile_/16755688',
 'https://advance.sagepub.com/articles/preprint/COVID-19_Infodemic_A_New_Historicist_Analysis_of_Atwood_s_Oryx_and_Crake/17085539',
 'https://advance.sagepub.com/articles/preprint/Group_Self-Evalulation_Primes_for_Autonomous_Motivation_in_Collaborative_Learning/17105573',
 'https://advance.sagepub.com/articles/preprint/Employment_and_Innovation_in_U_S_Media_Industries_2004-2018/17124584',
 'https://advance.sagepub.com/articles/preprint/SOCIAL_IMPACT_INVESTMENT_IN_LATIN_AMERICA_THE_ROLE_OFGOVERNMENT/17124545',
 'https://advance.sagepub.com/articles/preprint/COVID-19_Pandemic_Recession_Policy_Response_and_Recovery_A_Canadian_Perspective/17089034',
 'https://advance.sagepub.com/articles/preprint/The_Prefrontal-Hippocampal_Comparator_Volition_and_Episodic_Memory/14384822',
 'https://advance.sagepub.com/articles/preprint/Assessment_of_Government_and_NGOs_Joint_Efforts_and_Role_in_Drought_Mitigation_Program_The_Case_of_East_Guji_Zone_Drought_Vulnerable_Areas/14074196',
 'https://advance.sagepub.com/articles/preprint/Feelings_of_Culpability_Just_Following_Orders_versus_Making_the_Decision_Oneself/14110007',
 'https://advance.sagepub.com/articles/preprint/Negative_Emotions_in_the_Field_A_Narrative_Analysis_of_EFL_Researchers_Experience/8231204',
 'https://advance.sagepub.com/articles/preprint/Trust_Transparency_and_Transnational_lessons_from_Covid_19/12923207',
 'https://advance.sagepub.com/articles/preprint/Does_Digital_Inclusive_Finance_Promote_Commercial_Insurance_Participation_--_An_Empirical_Study_Based_on_the_Digital_Inclusive_Finance_Index_and_China_Family_Panel_Studies_Data/17206895',
 'https://advance.sagepub.com/articles/preprint/Development_and_validation_of_the_Digital_Addiction_Scale_for_Teenagers_DAST_/13503156',
 'https://advance.sagepub.com/articles/preprint/Gender_Inequality_in_Nigeria_Economy/17258441',
 'https://advance.sagepub.com/articles/preprint/Mental_health_burden_of_high_school_students_1_5_years_after_the_beginning_of_the_COVID-19_pandemic_in_Austria/17260130',
 'https://advance.sagepub.com/articles/preprint/Medical_Pluralism_in_East_and_West_Europe_A_Comparison_of_People_Visiting_Alternative_Traditional_Folk_Healthcare_Practitioners/17090900',
 'https://advance.sagepub.com/articles/preprint/Theory_Model_for_the_Integration/17282009',
 'https://advance.sagepub.com/articles/preprint/Integrative_literature_review_of_the_financial_fragility_hypothesis_proposed_by_Minsky/17263079',

In [18]:
df['doi'].sort_values().head(60)#.tolist()

354        10.31124/advance.10005662
1779    10.31124/advance.10005662.v1
1780    10.31124/advance.10005662.v2
340        10.31124/advance.10005884
1781    10.31124/advance.10005884.v1
346        10.31124/advance.10007411
1782    10.31124/advance.10007411.v1
342        10.31124/advance.10010381
1783    10.31124/advance.10010381.v1
343        10.31124/advance.10012031
1785    10.31124/advance.10012031.v1
355        10.31124/advance.10026860
1784    10.31124/advance.10026860.v1
390        10.31124/advance.10048160
1768    10.31124/advance.10048160.v1
1787    10.31124/advance.10048160.v2
1786    10.31124/advance.10048160.v3
3715    10.31124/advance.10048160.v4
653        10.31124/advance.10050131
1789    10.31124/advance.10050131.v1
345        10.31124/advance.10050497
1788    10.31124/advance.10050497.v1
347        10.31124/advance.10055363
1790    10.31124/advance.10055363.v1
344        10.31124/advance.10055399
1791    10.31124/advance.10055399.v1
348        10.31124/advance.10096058
1792    10.31124/advance.10096058.v1
350        10.31124/advance.10245443
1793    10.31124/advance.10245443.v1
351        10.31124/advance.10247993
1796    10.31124/advance.10247993.v1
353        10.31124/advance.10260344
1794    10.31124/advance.10260344.v1
360        10.31124/advance.10279670
1795    10.31124/advance.10279670.v1
1798    10.31124/advance.10279670.v2
359        10.31124/advance.10315454
1797    10.31124/advance.10315454.v1
361        10.31124/advance.10605683
1800    10.31124/advance.10605683.v1
363        10.31124/advance.11106194
1801    10.31124/advance.11106194.v1
366        10.31124/advance.11289362
1799    10.31124/advance.11289362.v1
372        10.31124/advance.11298800
1802    10.31124/advance.11298800.v1
1009       10.31124/advance.11300885
1803    10.31124/advance.11300885.v1
364        10.31124/advance.11302673
1804    10.31124/advance.11302673.v1
375        10.31124/advance.11304956
1805    10.31124/advance.11304956.v1
1808    10.31124/advance.11304956.v2
695        10.31124/advance.11350199
1807    10.31124/advance.11350199.v1
371        10.31124/advance.11354120
1806    10.31124/advance.11354120.v1
376        10.31124/advance.11368469
1810    10.31124/advance.11368469.v1
Name: doi, dtype: object

In [19]:
df[df['subtype_backend_raw']=='other']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
12,crossref::10.31124/advance.7038497,Advance,crossref,10.31124/advance.7038497,10.31124/advance.7038497,https://doi.org/10.31124/advance.7038497,https://advance.sagepub.com/articles/A_Snapsho...,https://advance.sagepub.com/articles/A_Snapsho...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A Snapshot of Psycho-social issues in Camp Liv...,None,None,None,None,posted-content,other,other,None,True,2018-09-06,2018-09-06,2018-09-06,2025-02-21,None,2018-09-06,None,2018-09-06,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>Using survey data to measure the impac...,Using survey data to measure the impact of a d...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038497"", ""URL"": ""ht...",10.31124/advance.7038497,10.31124,10.31124,advance.7038497,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
13,crossref::10.31124/advance.7038497.v1,Advance,crossref,10.31124/advance.7038497.v1,10.31124/advance.7038497.v1,https://doi.org/10.31124/advance.7038497.v1,https://advance.sagepub.com/articles/A_Snapsho...,https://advance.sagepub.com/articles/A_Snapsho...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A Snapshot of Psycho-social issues in Camp Liv...,None,None,None,None,posted-content,other,other,None,True,2018-09-06,2018-09-06,2018-09-06,2025-02-21,None,2018-09-06,None,2018-09-06,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>Using survey data to measure the impac...,Using survey data to measure the impact of a d...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038497.v1"", ""URL"": ...",10.31124/advance.7038497.v1,10.31124,10.31124,advance.7038497.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles

In [20]:
df[df['subtype_backend_raw']=='other']['doi'].tolist()

['10.31124/advance.7038497', '10.31124/advance.7038497.v1']

## observation

it seems like their create the new doi with versions patterns and the old records without version patterns are not available on the main page

In [21]:
df['doi'].sort_values().head(60)#.tolist()

354        10.31124/advance.10005662
1779    10.31124/advance.10005662.v1
1780    10.31124/advance.10005662.v2
340        10.31124/advance.10005884
1781    10.31124/advance.10005884.v1
346        10.31124/advance.10007411
1782    10.31124/advance.10007411.v1
342        10.31124/advance.10010381
1783    10.31124/advance.10010381.v1
343        10.31124/advance.10012031
1785    10.31124/advance.10012031.v1
355        10.31124/advance.10026860
1784    10.31124/advance.10026860.v1
390        10.31124/advance.10048160
1768    10.31124/advance.10048160.v1
1787    10.31124/advance.10048160.v2
1786    10.31124/advance.10048160.v3
3715    10.31124/advance.10048160.v4
653        10.31124/advance.10050131
1789    10.31124/advance.10050131.v1
345        10.31124/advance.10050497
1788    10.31124/advance.10050497.v1
347        10.31124/advance.10055363
1790    10.31124/advance.10055363.v1
344        10.31124/advance.10055399
1791    10.31124/advance.10055399.v1
348        10.31124/advance.10096058
1792    10.31124/advance.10096058.v1
350        10.31124/advance.10245443
1793    10.31124/advance.10245443.v1
351        10.31124/advance.10247993
1796    10.31124/advance.10247993.v1
353        10.31124/advance.10260344
1794    10.31124/advance.10260344.v1
360        10.31124/advance.10279670
1795    10.31124/advance.10279670.v1
1798    10.31124/advance.10279670.v2
359        10.31124/advance.10315454
1797    10.31124/advance.10315454.v1
361        10.31124/advance.10605683
1800    10.31124/advance.10605683.v1
363        10.31124/advance.11106194
1801    10.31124/advance.11106194.v1
366        10.31124/advance.11289362
1799    10.31124/advance.11289362.v1
372        10.31124/advance.11298800
1802    10.31124/advance.11298800.v1
1009       10.31124/advance.11300885
1803    10.31124/advance.11300885.v1
364        10.31124/advance.11302673
1804    10.31124/advance.11302673.v1
375        10.31124/advance.11304956
1805    10.31124/advance.11304956.v1
1808    10.31124/advance.11304956.v2
695        10.31124/advance.11350199
1807    10.31124/advance.11350199.v1
371        10.31124/advance.11354120
1806    10.31124/advance.11354120.v1
376        10.31124/advance.11368469
1810    10.31124/advance.11368469.v1
Name: doi, dtype: object

In [22]:
# [./] matches either a dot or a slash
# v\d+ matches 'v' followed by one or more digits
# $ ensures this pattern is at the very end of the string
pattern = r'[./]v\d+$'
# pattern = r'v\d+$'
mask = df['doi'].str.contains(pattern, regex=True, na=False)
result = df[mask]
result

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
2,crossref::10.31124/advance.7038500.v1,Advance,crossref,10.31124/advance.7038500.v1,10.31124/advance.7038500.v1,https://doi.org/10.31124/advance.7038500.v1,https://advance.sagepub.com/articles/Unmet_nee...,https://advance.sagepub.com/articles/Unmet_nee...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Unmet needs of ageing transgender and non-bina...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>An view of literature on transgender a...,An view of literature on transgender and non-b...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038500.v1"", ""URL"": ...",10.31124/advance.7038500.v1,10.31124,10.31124,advance.7038500.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
4,crossref::10.31124/advance.7038503.v1,Advance,crossref,10.31124/advance.7038503.v1,10.31124/advance.7038503.v1,https://doi.org/10.31124/advance.7038503.v1,https://advance.sagepub.com/articles/A_TROG_ma...,https://advance.sagepub.com/articles/A_TROG_ma...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A TROG masked.docUsing T.R.O.G to improve psyc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A discussion on language from a theore...,A discussion on language from a theoretical pe...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038503.v1"", ""URL"": ...",10.31124/advance.7038503.v1,10.31124,10.31124,advance.7038503.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
5,crossref::10.31124/advance.7038506.v1,Advance,crossref,10.31124/advance.7038506.v1,10.31124/advance.7038506.v1,https://doi.org/10.31124/advance.7038506.v1,https://advance.sagepub.com/articles/Are_We_Th...,https://advance.sagepub.com/articles/Are_We_Th...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Are We There Yet? Understanding Cultural Issue...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A short opinion piece on the state of ...,A short opinion piece on the state of cultural...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038506.v1"", ""URL"": ...",10.31124/advance.7038506.v1,10.31124,10.31124,advance.7038506.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
11,crossref::10.31124/advance.7038512.v1,Advance,crossref,10.31124/advance.7038512.v1,10.31124/advance.7038512.v1,https://doi.org/10.31124/advance.7038512.v1,https://advance.sagepub.com/articles/Individua...,https://advance.sagepub.com/articles/Individua...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Individual differences play an important role ...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-05,2018-09-05,2018-09-05,2025-02-21,None,2018-09-05,None,2018-09-05,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>Exploring the personality types that u...,Exploring the personality types that underpin ...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038512.v1"", ""URL"": ...",10.31124/advance.7038512.v1,10.31124,10.31124,advance.7038512.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
13,crossref::10.31124/advance.7038497.v1,Advance,crossref,10.31124/advance.7038497.v1,10.31124/advance.7038497.v1,https://doi.org/10.31124/advance.7038497.v1,https://advance.sagepub.com/articles/A_Snapsho...,https://advance.sagepub.com/articles/A_Snapsho...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A Snapshot of Psycho-social issues in Camp Liv...,None,None,None,None,posted-content,other,other,None,True,2018-09-06,2018-09-06,2018-09-06,2025-02-21,None,2018-09-06,None,2018-09-06,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>Using survey data to measure the impac...,Using survey data to measure the impact of a d...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038497.v1"", ""URL"": ...",10.31124/advance.7038497.v1,10.31124,10.31124,advance.7038497.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4396,crossref::10.31124/advance.175033210.03003372/v2,Advance,crossref,10.31124/advance.175033210.03003372/v2,10.31124/advance.175033210.03003372/v2,https://doi.org/10.31124/advance.175033210.030...,https://advance.sagepub.com/users/835416/artic...,https://advance.sagepub.com/users/835416/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,When Language Dances: Micromovement in Experim...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-11-17,2025-11-17,2025-11-17,2025-11-17,None,2025-11-17,None,2025-11-17,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"PhD, Richard Wainwright,",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-0555-6...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,10.31124/advance.175033210.03003372/v1,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.175033210.03003372/v...",10.31124/advance.175033210.03003372/v2,10.31124,10.31124,advance.175033210.03003372/v2,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4397,crossref::10.31124/advance.175630073.36585408/v2,Advance,crossref,10.31124/advance.175630073.36585408/v2,10.31124/advance.175630073.36585408/v2,https://doi.org/10.31124/advance.175630073.365...,https://advance.sagepub.com/users/945637/artic...,https://advance.sagepub.com/users/945637/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Psychedelic Rejuvenation Hypothesis: A Framewo...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-11-17,2025-11-17,2025-11-17,2025-11-17,None,2025-11-17,None,2025-11-17,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Montgomery, Tony; Grant, DeMond M.",None,None,"[{""ORCID"": ""https://orcid.org/0009-0000-6154-1...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,10.31124/advance.175630073.36585408/v1,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.175630073.36585408/v...",10.31124/advance.175630073.36585408/v2,10.31124,10.31124,advance.175630073.36585408/v2,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4398,crossref::10.31124/advance.176488150.02208323/v1,Advance,crossref,10.31124/advance.176488150.02208323/v1,10.31124/advance.176488150.02208323/v1,https://doi.org/10.31124/advance.176488150.022...,https://advance.sagepub.com/users/906882/artic...,https://advance.sagepub.com/users/906882/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Hurting Diversity: Diversification of Militant...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-04,2025-12-04,2025-12-04,2025-12-04,None,2025-12-04,None,2025-12-04,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Kirisci, Mustafa; Kocaman, Ibrahim; Albayrak, ...",Desales University; Embry-Riddle Aeronautical ...,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8563-2...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.176488150.02208323/v...",10.31124/advance.176488150.02208323/v1,10.31124,10.31124,advance.176488150.02208323/v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4399,crossref::10.31124/advance.176488150.08867006/v1,Advance,crossref,10.31124/advance.176488150.08867006/v1,10.31124/advance.176488150.08867006/v1,https://doi.org/10.31124/advance.176488150.088...,https://advance.sagepub.com/users/930259/artic...,https://advance.sagepub.com/users/930259/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,Ethiopia's Political Transition and Reform und...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-04,2025-12-04,2025-12-04,2025-12-04,None,2025-12-04,None,2025-12-04,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Gebre, Abiyot Geneme",University of Kiel Institute of Social Sciences,None,"[{""ORCID"": ""https://orcid.org/0009-0008-6632-5...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.176488150.08867006/v...",10.31124/advance.176488150.08867006/v1,10.31124,10.31124,advance.176488150.08867006/v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users
4400,crossref::10.31124/advance.176488150.05947609/v1,Advance,crossref,10.31124/advance.176488150.05947609/v1,10.31124/advance.176488150.05947609/v1,https://doi.org/10.31124/advance.176488150.059...,https://advance.sagepub.com/users/914903/artic...,https://advance.sagepub.com/users/914903/artic...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,Preprints,None,External Support and Armed Groups’ Behavior: T...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-04,2025-12-04,2025-12-04,2025-12-04,None,2025-12-04,None,2025-12-04,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Youssef, Abboud Maksy",University of Geneva,None,"[{""ORCID"": ""https://orcid.org/0000-0002-7298-1...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.176488150.05947609/v...",10.31124/advance.176488150.05947609/v1,10.31124,10.31124,advance.176488150.05947609/v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/users

In [23]:
# [./] matches either a dot or a slash
# v\d+ matches 'v' followed by one or more digits
# $ ensures this pattern is at the very end of the string
pattern = r'[./]v\d+$'
# pattern = r'v\d+$'
mask = ~df['doi'].str.contains(pattern, regex=True, na=False)
result = df[mask]
result

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.31124/advance.7037639,Advance,crossref,10.31124/advance.7037639,10.31124/advance.7037639,https://doi.org/10.31124/advance.7037639,https://advance.sagepub.com/articles/The_Priva...,https://advance.sagepub.com/articles/The_Priva...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,The Privatization of Security and the Emergenc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2022-03-30,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;This study interrogates the p...,This study interrogates the participation of p...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Chinwokwu, Eke; Igbo, Emmanuel",None,None,"[{""affiliation"": [], ""family"": ""Chinwokwu"", ""g...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7037639"", ""URL"": ""ht...",10.31124/advance.7037639,10.31124,10.31124,advance.7037639,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
1,crossref::10.31124/advance.7038500,Advance,crossref,10.31124/advance.7038500,10.31124/advance.7038500,https://doi.org/10.31124/advance.7038500,https://advance.sagepub.com/articles/Unmet_nee...,https://advance.sagepub.com/articles/Unmet_nee...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Unmet needs of ageing transgender and non-bina...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>An view of literature on transgender a...,An view of literature on transgender and non-b...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038500"", ""URL"": ""ht...",10.31124/advance.7038500,10.31124,10.31124,advance.7038500,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
3,crossref::10.31124/advance.7038503,Advance,crossref,10.31124/advance.7038503,10.31124/advance.7038503,https://doi.org/10.31124/advance.7038503,https://advance.sagepub.com/articles/A_TROG_ma...,https://advance.sagepub.com/articles/A_TROG_ma...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,A TROG masked.docUsing T.R.O.G to improve psyc...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A discussion on language from a theore...,A discussion on language from a theoretical pe...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038503"", ""URL"": ""ht...",10.31124/advance.7038503,10.31124,10.31124,advance.7038503,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
6,crossref::10.31124/advance.7038506,Advance,crossref,10.31124/advance.7038506,10.31124/advance.7038506,https://doi.org/10.31124/advance.7038506,https://advance.sagepub.com/articles/Are_We_Th...,https://advance.sagepub.com/articles/Are_We_Th...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Are We There Yet? Understanding Cultural Issue...,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2025-02-21,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>A short opinion piece on the state of ...,A short opinion piece on the state of cultural...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Broadway-Horner, Matt",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8834-7...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7038506"", ""URL"": ""ht...",10.31124/advance.7038506,10.31124,10.31124,advance.7038506,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
7,crossref::10.31124/advance.7037660,Advance,crossref,10.31124/advance.7037660,10.31124/advance.7037660,https://doi.org/10.31124/advance.7037660,https://advance.sagepub.com/articles/review_ar...,https://advance.sagepub.com/articles/review_ar...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,review article on literary archeology.docx,None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-04,2018-09-04,2018-09-04,2022-03-29,None,2018-09-04,None,2018-09-04,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,"<jats:p>&lt;p&gt;In\nthis review article, I ha...","In this review article, I have located the tra...","[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Yi, Jiexin",None,None,"[{""affiliation"": [], ""family"": ""Yi"", ""given"": ...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7037660"", ""URL"": ""ht...",10.31124/advance.7037660,10.31124,10.31124,advance.7037660,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1766,crossref::10.31124/advance.21431079,Advance,crossref,10.31124/advance.21431079,10.31124/advance.21431079,https://doi.org/10.31124/advance.21431079,https://advance.sagepub.com/articles/preprint/...,https://advance.sagepub.com/articles/preprint/...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,None,None,"Mental Distress, Label Avoidance, and Use of a...",None,None,None,None,posted-content,preprint,preprint,None,True,2022-11-16,2022-11-16,2024-02-13,2025-05-14,None,2022-11-16,None,2022-11-16,None,2022,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt; &lt;/p&gt;\n&lt;p&gt;&lt;st...,Objectives To pilot test a mental health chatb...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Kosyluk, Kristin; Baeder, Tanner; Greene, Kara...",None,None,"[{""affiliation"": [], ""family"": ""Kosyluk"", ""giv...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-preprint-of"": [{""asserted-by"": ""subject"",...",,10.2196/45959,True,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.21431079"", ""URL"": ""h...",10.31124/advance.21431079,10.31124,10.31124,advance.21431079,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
1767,crossref::10.31124/advance.7091825,Advance,crossref,10.31124/advance.7091825,10.31124/advance.7091825,https://doi.org/10.31124/advance.7091825,https://advance.sagepub.com/articles/preprint/...,https://advance.sagepub.com/articles/preprint/...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,None,None,"Geography of Chinese rock and roll: cultural, ...",None,None,None,None,posted-content,preprint,preprint,None,True,2018-09-18,2018-09-18,2024-02-15,2024-03-04,None,2018-09-18,None,2018-09-18,None,2018,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;This chapter mines the litera...,This chapter mines the literature to bring out...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Wang, June; Chen, Li",None,None,"[{""affiliation"": [], ""family"": ""Wang"", ""given""...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-preprint-of"": [{""asserted-by"": ""subject"",...",,10.2139/ssrn.3798170,True,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.7091825"", ""URL"": ""ht...",10.31124/advance.7091825,10.31124,10.31124,advance.7091825,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/articles
2131,crossref::10.31124/advance.12721376,Advance,crossref,10.31124/advance.12721376,10.31124/advance.12721376,https://doi.org/10.31124/advance.12721376,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,Advance,None,None,Defining Friendship: An Age Old Question,None,None,None,None,posted-content,preprint,preprint,None,True,2020-07-27,2022-10-05,2024-02-22,2025-05-14,None,2022-10-05,None,2022-10-05,None,2022,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by-nc-nd/...,https://creativecommons.org/licenses/by-nc-nd/...,<jats:p>&lt;div&gt;This paper uses a dataset g...,This paper uses a dataset generated from keywo...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Langkamp, Christian",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2426-1...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.12721376"", ""URL"": ""h...",10.31124/advance.12721376,10.31124,10.31124,advance.12721376,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
2301,crossref::10.31124/advance.13336571,Advance,crossref,10.31124/advance.13336571,10.31124/advance.13336571,https://doi.org/10.31124/advance.13336571,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,Pilot Study Using AI for Large-scale Survey on...,None,None,None,None,posted-content,preprint,preprint,None,True,2021-01-04,2021-01-04,2024-02-22,2024-02-23,None,2021-01-04,None,2021-01-04,None,2021,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>The influence of genetic factors on pe...,The influence of genetic factors on personalit...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Kanazawa, Masayuki",None,None,"[{""affiliation"": [], ""family"": ""Kanazawa"", ""gi...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.13336571"", ""URL"": ""h...",10.31124/advance.13336571,10.31124,10.31124,advance.13336571,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
2473,crossref::10.31124/advance.14132306,Advance,crossref,10.31124/advance.14132306,10.31124/advance.14132306,https://doi.org/10.31124/advance.14132306,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,The Effect of Healthcare Education on Future D...,None,None,None,None,posted-content,preprint,preprint,None,True,2021-03-04,2021-03-09,2024-02-22,2024-07-17,None,2021-03-09,None,2021-03-09,None,2021,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;In competitive education test...,In competitive education test scores and scien...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Nowak, Ewa; Barciszewska, Anna-Maria; Lind, Ge...",None,None,"[{""affiliation"": [], ""family"": ""Nowak"", ""given...",None,None,None,None,None,None,None,None,1,None,None,1,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.14132306"", ""URL"": ""h...",10.31124/advance.14132306,10.31124,10.31124,advance.14132306,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi

In [24]:
pattern = "10.31124/advance.14132306"

mask = df['doi'].str.contains(pattern, regex=False, na=False)
result = df[mask]
result

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
2473,crossref::10.31124/advance.14132306,Advance,crossref,10.31124/advance.14132306,10.31124/advance.14132306,https://doi.org/10.31124/advance.14132306,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,The Effect of Healthcare Education on Future D...,None,None,None,None,posted-content,preprint,preprint,None,True,2021-03-04,2021-03-09,2024-02-22,2024-07-17,None,2021-03-09,None,2021-03-09,None,2021,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;In competitive education test...,In competitive education test scores and scien...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Nowak, Ewa; Barciszewska, Anna-Maria; Lind, Ge...",None,None,"[{""affiliation"": [], ""family"": ""Nowak"", ""given...",None,None,None,None,None,None,None,None,1,None,None,1,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.14132306"", ""URL"": ""h...",10.31124/advance.14132306,10.31124,10.31124,advance.14132306,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
2475,crossref::10.31124/advance.14132306.v1,Advance,crossref,10.31124/advance.14132306.v1,10.31124/advance.14132306.v1,https://doi.org/10.31124/advance.14132306.v1,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,The effect of healthcare education on students...,None,None,None,None,posted-content,preprint,preprint,None,True,2021-03-04,2021-03-04,2024-02-22,2024-02-23,None,2021-03-04,None,2021-03-04,None,2021,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;In competitive education test...,In competitive education test scores and scien...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Nowak, Ewa; Barciszewska, Anna-Maria; Lind, Ge...",None,None,"[{""affiliation"": [], ""family"": ""Nowak"", ""given...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.14132306.v1"", ""URL"":...",10.31124/advance.14132306.v1,10.31124,10.31124,advance.14132306.v1,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi
2477,crossref::10.31124/advance.14132306.v2,Advance,crossref,10.31124/advance.14132306.v2,10.31124/advance.14132306.v2,https://doi.org/10.31124/advance.14132306.v2,https://advance.sagepub.com/doi/full/10.31124/...,https://advance.sagepub.com/doi/full/10.31124/...,10.31124,179,None,None,crossref,SAGE Publications,None,None,None,None,The Effect of Healthcare Education on Future D...,None,None,None,None,posted-content,preprint,preprint,None,True,2021-03-09,2021-03-09,2024-02-22,2024-02-23,None,2021-03-09,None,2021-03-09,None,2021,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>&lt;p&gt;In competitive education test...,In competitive education test scores and scien...,"[{""URL"": ""https://ndownloader.figshare.com/fil...",None,"Nowak, Ewa; Barciszewska, Anna-Maria; Lind, Ge...",None,None,"[{""affiliation"": [], ""family"": ""Nowak"", ""given...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,63,None,"{""DOI"": ""10.31124/advance.14132306.v2"", ""URL"":...",10.31124/advance.14132306.v2,10.31124,10.31124,advance.14132306.v2,10.31124/advance,10.31124/advance,advance.sagepub.com,advance.sagepub.com/doi

In [25]:
advance_parent_df, advance_parent_summary = analyze_parent_data("Advance", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ADVANCE
=================================================================
  > Total Parent Groups:     2,336
  > Total Versions Found:    4,308
  > Unique Parent DOIs:      2,336
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Advance:
-----------------------------------
  1 version(s):     653 groups
  2 version(s):     1,477 groups
  3 version(s):     161 groups
  4 version(s):     33 groups
  5 version(s):     9 groups
  7 version(s):     1 groups
  8 version(s):     1 groups
  26 version(s):    1 groups

  Average versions per parent: 1.84

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Advance                  2271
SSRN                       28
Research Square             7
SocArXiv                    6
Preprints.org               5
Advance; ResearchGate       4
ResearchGate                3
AgEcon Search               2
arXiv                       2
Authorea Inc.               2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31124/advance    2336



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
advance.sagepub.com    2328
authorea.com              6
techrxiv.org              2


=================================================================
 COMPLETED: ADVANCE
=================================================================

# AfricArXiv

In [26]:
AfricArXiv_df, AfricArXiv_summary = get_server_data("AfricArXiv")

==================================================
 SERVER ANALYSIS: AFRICARXIV
==================================================
  > Files found:    2
  > Raw records:    2190
  > Cleaned shape:  (2190, 90)
  > Unique DOIs:    2190
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.60763/africarxiv    1689
10.31730/osf            496
10.31235/osf              5
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
africarxiv.ubuntunet.net    1689
osf.io                       501
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.60763    1689
10.31730     496
10.31235       5
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None     1689
15934     501
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
My University                                                  1423
Center for Open Science                                         502
Publisher                                                        52
University of Nairobi                                            29
Museum of One                                                    19
Wordworks                                                        11
Academia Kenya                                                    9
MUSEUM OF ONE                                                     8
HAQAA Initiative                                                  7
Liberty Community Trust, Wordworks, Book Dash and Nal'ibali       6
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    2190
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    2190
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None          1689
AfricArXiv     501
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2190
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
None              1288
posted-content     501
Text               163
JournalArticle     131
Other               70
Software             7
Dataset              6
Preprint             6
Dissertation         4
Book                 4
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None                1288
preprint             501
Article              219
Presentation          63
Other                 35
Preprint              20
Technical Report      13
Working Paper         11
Book                  10
Thesis                 7
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR AFRICARXIV
==================================================

In [27]:
AfricArXiv_parent_df, AfricArXiv_parent_summary = analyze_parent_data("AfricArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: AFRICARXIV
=================================================================
  > Total Parent Groups:     1,578
  > Total Versions Found:    2,107
  > Unique Parent DOIs:      1,578
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for AfricArXiv:
-----------------------------------
  1 version(s):     1,142 groups
  2 version(s):     391 groups
  3 version(s):     28 groups
  4 version(s):     10 groups
  6 version(s):     1 groups
  8 version(s):     3 groups
  9 version(s):     2 groups
  11 version(s):    1 groups

  Average versions per parent: 1.34

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
AfricArXiv                 1566
Open Science Framework        3
SSRN                          3
ResearchGate                  2
SocArXiv                      1
Advance                       1
Humanities Commons CORE       1
Zenodo                        1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.60763/africarxiv    1127
10.31730/osf            451



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
africarxiv.ubuntunet.net    1127
osf.io                       451


=================================================================
 COMPLETED: AFRICARXIV
=================================================================

# AgEcon Search

In [28]:
AgEcon_Search_df, AgEcon_Search_summary = get_server_data("AgEcon_Search")

==================================================
 SERVER ANALYSIS: AGECON_SEARCH
==================================================
  > Files found:    2
  > Raw records:    188173
  > Cleaned shape:  (188173, 90)
  > Unique DOIs:    188173
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.22004/ag      188172
10.22004/tind         1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
ageconsearch.umn.edu    188173
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.22004    188173
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    188173
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Unknown    188173
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    188173
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    188173
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    188173
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    188173
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Text              166567
Other              11808
JournalArticle      7584
Report              2214
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
Text                              167506
Journal Article                    14059
Conference Paper/ Presentation      3783
Report                              2214
Working or Discussion Paper          448
Thesis/ Dissertation                 135
Book/ Chapter                         28
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR AGECON_SEARCH
==================================================

In [29]:
# for x in AgEcon_Search_df.sample(1).iloc[0]:
#     print(x)

In [30]:
AgEcon_parent_df, AgEcon_parent_summary = analyze_parent_data("AgEcon Search", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: AGECON SEARCH
=================================================================
  > Total Parent Groups:     153,387
  > Total Versions Found:    167,422
  > Unique Parent DOIs:      153,387
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for AgEcon Search:
-----------------------------------
  1 version(s):     145,430 groups
  2 version(s):     6,904 groups
  3 version(s):     598 groups
  4 version(s):     142 groups
  5 version(s):     63 groups
  6 version(s):     49 groups
  7 version(s):     30 groups
  8 version(s):     21 groups
  9 version(s):     16 groups
  10 version(s):    14 groups
  11 version(s):    7 groups
  12 version(s):    11 groups
  13 version(s):    4 groups
  14 version(s):    9 groups
  15 version(s):    10 groups
  16 version(s):    3 groups
  17 version(s):    3 groups
  18 version(s):    7 groups
  19 version(s):    3 groups
  20 version(s):    2 groups
  21 version(s):    2 groups
  22 version(s):    4 groups
  23 version(s):    3 groups
  24 version(s):    3 groups
  25 version(s):    4 groups
  26 version(s):    2 groups
  27 version(s):    5 groups
  28 version(s):    2 groups
  29 version(s):    3 groups
  30 version(s):    2 groups
  31 version(s):    3 groups
  32 version(s):    1 groups
  33 version(s):    2 groups
  36 version(s):    1 groups
  39 version(s):    2 groups
  48 version(s):    1 groups
  57 version(s):    1 groups
  61 version(s):    2 groups
  62 version(s):    1 groups
  66 version(s):    2 groups
  68 version(s):    2 groups
  70 version(s):    1 groups
  71 version(s):    1 groups
  80 version(s):    1 groups
  86 version(s):    1 groups
  89 version(s):    1 groups
  98 version(s):    1 groups
  102 version(s):   1 groups
  106 version(s):   1 groups
  108 version(s):   1 groups
  118 version(s):   1 groups
  301 version(s):   1 groups
  390 version(s):   1 groups
  450 version(s):   1 groups

  Average versions per parent: 1.09

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
AgEcon Search                                         153072
SSRN                                                     241
RePEc: Research Papers in Economics                       30
arXiv                                                      8
AgEcon Search; RePEc: Research Papers in Economics         7
ResearchGate                                               6
HAL                                                        5
Research Square                                            5
Preprints.org                                              4
MetaArXiv                                                  2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.22004/ag    153387



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
ageconsearch.umn.edu    153387


=================================================================
 COMPLETED: AGECON SEARCH
=================================================================

In [31]:
AgEcon_Search_df[AgEcon_Search_df['type_backend_raw']=='Other']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
166567,datacite::10.22004/ag.econ.333722,AgEcon Search,datacite,10.22004/ag.econ.333722,10.22004/ag.econ.333722,https://doi.org/10.22004/ag.econ.333722,https://ageconsearch.umn.edu/record/333722,https://ageconsearch.umn.edu/record/333722,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Farmers' risk exposition and its drivers,None,None,None,en,Other,Working or Discussion Paper,Other,None,None,2023-04-06,None,None,None,2025-09-30,None,2023-04-06,None,None,2019,published_year,None,None,None,None,None,"[{""description"": ""The analysis of income risk ...",The analysis of income risk is the basis for f...,None,None,"Duden, C.; Offermann, F.",None,None,"[{""affiliation"": [], ""familyName"": ""Duden"", ""g...",[],None,[],None,None,"[{""subject"": ""Farm Management""}, {""subject"": ""...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.333722,10.22004,10.22004,ag.econ.333722,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
166568,datacite::10.22004/ag.econ.333733,AgEcon Search,datacite,10.22004/ag.econ.333733,10.22004/ag.econ.333733,https://doi.org/10.22004/ag.econ.333733,https://ageconsearch.umn.edu/record/333733,https://ageconsearch.umn.edu/record/333733,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Front matter,None,None,None,en,Other,Journal Article,Other,None,None,2023-04-06,None,None,None,2023-04-06,None,2023-04-06,None,None,2018,published_year,None,None,None,None,None,[],None,None,None,Australian Journal Of Agricultural And Resourc...,None,None,"[{""affiliation"": [], ""name"": ""Australian Journ...",[],None,[],None,None,"[{""subject"": ""Agricultural and Food Policy""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.333733,10.22004,10.22004,ag.econ.333733,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
166569,datacite::10.22004/ag.econ.333734,AgEcon Search,datacite,10.22004/ag.econ.333734,10.22004/ag.econ.333734,https://doi.org/10.22004/ag.econ.333734,https://ageconsearch.umn.edu/record/333734,https://ageconsearch.umn.edu/record/333734,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Effects of supermarket monopsony pricing on ag...,None,None,None,en,Other,Journal Article,Other,None,None,2023-04-06,None,None,None,2023-04-06,None,2023-04-06,None,None,2018,published_year,None,None,None,None,None,"[{""description"": ""Potential effects of alleged...",Potential effects of alleged monopsony pricing...,None,None,"Freebairn, John",None,None,"[{""affiliation"": [], ""familyName"": ""Freebairn""...",[],None,[],None,None,"[{""subject"": ""International Relations/Trade""},...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.333734,10.22004,10.22004,ag.econ.333734,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
166570,datacite::10.22004/ag.econ.333735,AgEcon Search,datacite,10.22004/ag.econ.333735,10.22004/ag.econ.333735,https://doi.org/10.22004/ag.econ.333735,https://ageconsearch.umn.edu/record/333735,https://ageconsearch.umn.edu/record/333735,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Testing vertical price transmission for Vietna...,None,None,None,en,Other,Journal Article,Other,None,None,2023-04-06,None,None,None,2023-04-06,None,2023-04-06,None,None,2018,published_year,None,None,None,None,None,"[{""description"": ""Vietnam has undergone market...",Vietnam has undergone market reforms over the ...,None,None,"Mai, Thang Chien; Shakur, Shamim; Cassells, Sue",None,None,"[{""affiliation"": [], ""familyName"": ""Mai"", ""giv...",[],None,[],None,None,"[{""subject"": ""Demand and Price Analysis""}, {""s...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.333735,10.22004,10.22004,ag.econ.333735,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
166571,datacite::10.22004/ag.econ.333736,AgEcon Search,datacite,10.22004/ag.econ.333736,10.22004/ag.econ.333736,https://doi.org/10.22004/ag.econ.333736,https://ageconsearch.umn.edu/record/333736,https://ageconsearch.umn.edu/record/333736,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,China feels the heat: negative impacts of high...,None,None,None,en,Other,Journal Article,Other,None,None,2023-04-06,None,None,None,2023-04-06,None,2023-04-06,None,None,2018,published_year,None,None,None,None,None,"[{""description"": ""We analysed a county-level d...",We analysed a county-level data set of single-...,None,None,"Chen, Xiaoguang; Chen, Shuai",None,None,"[{""affiliation"": [], ""familyName"": ""Chen"", ""gi...",[],None,[],None,None,"[{""subject"": ""Crop Production/Industries""}, {""...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.333736,10.22004,10.22004,ag.econ.333736,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188149,datacite::10.22004/ag.econ.386102,AgEcon Search,datacite,10.22004/ag.econ.386102,10.22004/ag.econ.386102,https://doi.org/10.22004/ag.econ.386102,https://ageconsearch.umn.edu/record/386102,https://ageconsearch.umn.edu/record/386102,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Who Uses H-2As? Examining Program Growth by Se...,None,None,None,en,Other,Conference Paper/ Presentation,Other,None,None,2025-12-23,None,None,None,2025-12-23,None,2025-12-23,None,None,2023,published_year,None,None,None,None,None,"[{""description"": ""Preview of Presentation: • A...",Preview of Presentation: • Agricultural Guest ...,None,None,"Simnitt, Skylar",None,None,"[{""affiliation"": [], ""familyName"": ""Simnitt"", ...",[],None,[],None,None,"[{""subject"": ""Agricultural and Food Policy""}, ...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.386102,10.22004,10.22004,ag.econ.386102,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
188150,datacite::10.22004/ag.econ.386103,AgEcon Search,datacite,10.22004/ag.econ.386103,10.22004/ag.econ.386103,https://doi.org/10.22004/ag.econ.386103,https://ageconsearch.umn.edu/record/386103,https://ageconsearch.umn.edu/record/386103,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,The Adverse Effects Wage Rate Used for the H-2...,None,None,None,en,Other,Conference Paper/ Presentation,Other,None,None,2025-12-23,None,None,None,2025-12-23,None,2025-12-23,None,None,2025,published_year,None,None,None,None,None,"[{""description"": ""[Contents]: The Adverse Effe...",[Contents]: The Adverse Effects Wage Rate --- ...,None,None,"Feather, Peter",None,None,"[{""affiliation"": [], ""familyName"": ""Feather"", ...",[],None,[],None,None,"[{""subject"": ""Agricultural and Food Policy""}, ...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.386103,10.22004,10.22004,ag.econ.386103,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
188151,datacite::10.22004/ag.econ.386104,AgEcon Search,datacite,10.22004/ag.econ.386104,10.22004/ag.econ.386104,https://doi.org/10.22004/ag.econ.386104,https://ageconsearch.umn.edu/record/386104,https://ageconsearch.umn.edu/record/386104,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Insights from ERS Research on the H-2A Program,None,None,None,en,Other,Conference Paper/ Presentation,Other,None,None,2025-12-23,None,None,None,2025-12-23,None,2025-12-23,None,None,2025,published_year,None,None,None,None,None,"[{""description"": ""Summary: • H-2A jobs certifi...",Summary: • H-2A jobs certified increased almos...,None,None,"Castillo, Marcelo",None,None,"[{""affiliation"": [], ""familyName"": ""Castillo"",...",[],None,[],None,None,"[{""subject"": ""Labor and Human Capital""}, {""sub...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.386104,10.22004,10.22004,ag.econ.386104,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
188152,datacite::10.22004/ag.econ.386105,AgEcon Search,datacite,10.22004/ag.econ.386105,10.22004/ag.econ.386105,https://doi.org/10.22004/ag.econ.386105,https://ageconsearch.umn.edu/record/386105,https://ageconsearch.umn.edu/record/386105,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Labor Contractors in U.S. Agriculture,None,None,None,en,Other,Conference Paper/ Presentation,Other,None,None,2025-12-23,None,None,None,2025-12-23,None,2025-12-23,None,None,2025,published_year,None,None,None,None,None,"[{""description"": ""Conclusions: • Increasing re...",Conclusions: • Increasing reliance on farm lab...,None,None,"Simnitt, Skyler",None,None,"[{""affiliation"": [], ""familyName"": ""Simnitt"", ...",[],None,[],None,None,"[{""subject"": ""Agricultural and Food Policy""}, ...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.386105,10.22004,10.22004,ag.econ.386105,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record
188153,datacite::10.22004/ag.econ.386106,AgEcon Search,datacite,10.22004/ag.econ.386106,10.22004/ag.econ.386106,https://doi.org/10.22004/ag.econ.386106,https://ageconsearch.umn.edu/record/386106,https://ageconsearch.umn.edu/record/386106,10.22004,None,tind.agecon,tind,datacite,Unknown,None,None,None,None,Sugar Beet Labor Conference,None,None,None,en,Other,Conference Paper/ Presentation,Other,None,None,2025-12-26,None,None,None,2025-12-26,None,2025-12-26,None,None,1939,published_year,None,None,None,None,None,"[{""description"": ""Excerpts: The Rocky Mountain...",Excerpts: The Rocky Mountain area states of Id...,None,None,"Region X, Farm Security Administration",None,None,"[{""affiliation"": [], ""familyName"": ""Region X"",...",[],None,[],None,None,"[{""subject"": ""Crop Production/Industries""}, {""...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id,0,"{""client"": {""data"": {""id"": ""tind.agecon"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.22004/ag.econ.386106,10.22004,10.22004,ag.econ.386106,10.22004/ag,10.22004/ag,ageconsearch.umn.edu,ageconsearch.umn.edu/record

# AgriRxiv

In [32]:
AgriRxiv_df, AgriRxiv_summary = get_server_data("AgriRxiv")

==================================================
 SERVER ANALYSIS: AGRIRXIV
==================================================
  > Files found:    1
  > Raw records:    818
  > Cleaned shape:  (818, 90)
  > Unique DOIs:    818
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31220/osf         391
10.31220/agrirxiv    380
10.31227/osf          22
10.31219/osf          10
10.31235/osf           9
10.31234/osf           5
10.31225/osf           1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
cabidigitallibrary.org    462
osf.io                    356
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31220    771
10.31227     22
10.31219     10
10.31235      9
10.31234      5
10.31225      1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
242      771
15934     47
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
CABI Publishing            771
Center for Open Science     47
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    818
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    818
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
agriRxiv    462
AgriXiv     356
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    818
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    818
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    818
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR AGRIRXIV
==================================================

In [33]:
AgriRxiv_parent_df, AgriRxiv_parent_summary = analyze_parent_data("AgriRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: AGRIRXIV
=================================================================
  > Total Parent Groups:     777
  > Total Versions Found:    909
  > Unique Parent DOIs:      777
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for AgriRxiv:
-----------------------------------
  1 version(s):     672 groups
  2 version(s):     90 groups
  3 version(s):     8 groups
  4 version(s):     4 groups
  5 version(s):     1 groups
  6 version(s):     2 groups

  Average versions per parent: 1.17

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
AgriRxiv                            713
Open Science Framework               18
AgriRxiv; IndiaRxiv                  10
IndiaRxiv                             5
AgriRxiv; Open Science Framework      5
AgEcon Search                         4
INA-Rxiv                              4
SSRN                                  3
Research Square                       3
PeerJ Preprints                       1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31220/osf         409
10.31220/agrirxiv    364
10.17605/osf           4



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
cabidigitallibrary.org    439
osf.io                    334
agrixiv.org                 4


=================================================================
 COMPLETED: AGRIRXIV
=================================================================

# AIJR Preprints

In [34]:
AIJR_Preprints_df, AIJR_Preprints_summary = get_server_data("AIJR_Preprints")

==================================================
 SERVER ANALYSIS: AIJR_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    143
  > Cleaned shape:  (143, 90)
  > Unique DOIs:    143
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.21467/preprints    143
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.aijr.org    143
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.21467    143
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
8901    143
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
AIJR Publisher    143
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    143
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    143
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    143
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    143
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    143
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    143
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR AIJR_PREPRINTS
==================================================

In [35]:
AIJR_parent_df, AIJR_parent_summary = analyze_parent_data("AIJR Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: AIJR PREPRINTS
=================================================================
  > Total Parent Groups:     141
  > Total Versions Found:    150
  > Unique Parent DOIs:      141
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for AIJR Preprints:
-----------------------------------
  1 version(s):     134 groups
  2 version(s):     5 groups
  3 version(s):     2 groups

  Average versions per parent: 1.06

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
AIJR Preprints                  134
ResearchGate                      3
ScienceOpen Preprints             1
AIJR Preprints; ResearchGate      1
AfricArXiv                        1
arXiv                             1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.21467/preprints    141



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.aijr.org    141


=================================================================
 COMPLETED: AIJR PREPRINTS
=================================================================

# AMRC Open Research

In [36]:
AMRC_Open_Research_df, AMRC_Open_Research_summary = get_server_data("AMRC_Open_Research")

==================================================
 SERVER ANALYSIS: AMRC_OPEN_RESEARCH
==================================================
  > Files found:    2
  > Raw records:    102
  > Cleaned shape:  (102, 90)
  > Unique DOIs:    102
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/amrcopenres      52
10.12688/healthopenres    50
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
healthopenresearch.org    62
amrcopenresearch.org      40
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    102
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    102
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    102
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
Health Open Research                             61
AMRC Open Research                               38
None                                              2
AMRC Open Research CrossMark Policy Statement     1
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    102
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    102
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2753-6416    62
2517-6900    39
None          1
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    99
journal             2
dataset             1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    102
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR AMRC_OPEN_RESEARCH
==================================================

In [37]:
AMRC_Open_Research_df.sort_values(by='title')

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
98,crossref::10.12688/healthopenres.13924.1,AMRC Open Research,crossref,10.12688/healthopenres.13924.1,10.12688/healthopenres.13924.1,https://doi.org/10.12688/healthopenres.13924.1,https://healthopenresearch.org/articles/7-17/v1,https://healthopenresearch.org/articles/7-17/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Health Open Research,None,None,2753-6416,A Protocol for Systematic Review of Prognostic...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-10-10,None,2025-10-10,2025-10-10,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background Survivors of adolescent and ...,Background Survivors of adolescent and young a...,"[{""URL"": ""https://healthopenresearch.org/artic...",https://healthopenresearch.org/articles/7-17/v...,"Guolla, Louise; Mbuagbaw, Lawrence; Ma, Jinhui...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-2199-6...",None,None,"[{""award"": [""CVG-186971""], ""award-info"": [{""aw...",CIHR Vanier Canada Graduate Scholarship,1.0,None,None,None,0,None,None,0,58,"[{""DOI"": ""10.1161/CIRCULATIONAHA.119.041403"", ...",None,,,False,None,,None,None,,None,None,https://doi.org/10.12688/healthopenres.crossma...,issn,0,None,"{""DOI"": ""10.12688/healthopenres.13924.1"", ""ISS...",10.12688/healthopenres.13924.1,10.12688,10.12688,healthopenres.13924.1,10.12688/healthopenres,10.12688/healthopenres,healthopenresearch.org,healthopenresearch.org/articles
17,crossref::10.12688/amrcopenres.12936.2,AMRC Open Research,crossref,10.12688/amrcopenres.12936.2,10.12688/amrcopenres.12936.2,https://doi.org/10.12688/amrcopenres.12936.2,https://amrcopenresearch.org/articles/2-29/v2,https://amrcopenresearch.org/articles/2-29/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,AMRC Open Research,None,None,2517-6900,A collaborative approach to exercise provision...,None,None,None,en,journal-article,None,journal-article,None,False,2021-04-01,None,2021-04-26,2026-02-27,None,2021-04-01,None,2021-04-01,2021-04-01,2021.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p>\n <ns3:bold>Backgro...,Background: Exercise has been shown to be bene...,"[{""URL"": ""https://amrcopenresearch.org/article...",https://amrcopenresearch.org/articles/2-29/v2/pdf,"Jones, Julie; Alexander, Lyndsay; Hancock, Eli...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-1943-1...",None,None,"[{""award"": [""F-1901""], ""award-info"": [{""award-...","Parkinson's UK; Chief Scientist Office, Scotland",2.0,None,None,None,1,None,None,1,62,"[{""DOI"": ""10.1002/mds.25945"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/amrcopenres.14059.r26662;10.21956/amr...,"[{""DOI"": ""10.12688/amrcopenres.12936.1"", ""labe...",None,https://doi.org/10.12688/amrcopenres.crossmark...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.12936.2"", ""ISSN""...",10.12688/amrcopenres.12936.2,10.12688,10.12688,amrcopenres.12936.2,10.12688/amrcopenres,10.12688/amrcopenres,amrcopenresearch.org,amrcopenresearch.org/articles
15,crossref::10.12688/amrcopenres.12936.1,AMRC Open Research,crossref,10.12688/amrcopenres.12936.1,10.12688/amrcopenres.12936.1,https://doi.org/10.12688/amrcopenres.12936.1,https://amrcopenresearch.org/articles/2-29/v1,https://amrcopenresearch.org/articles/2-29/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,AMRC Open Research,None,None,2517-6900,A collaborative approach to exercise provision...,None,None,None,en,journal-article,None,journal-article,None,False,2020-12-10,None,2021-04-01,2026-02-27,None,2020-12-10,None,2020-12-10,2020-12-10,2020.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p>\n <ns3:bold>Backgro...,Background: Exercise has been shown to be bene...,"[{""URL"": ""https://amrcopenresearch.org/article...",https://amrcopenresearch.org/articles/2-29/v1/pdf,"Jones, Julie; Alexander, Lyndsay; Hancock, Eli...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-1943-1...",None,None,"[{""award"": [""F-1901""], ""award-info"": [{""award-...","Chief Scientist Office, Scotland; Parkinson's UK",2.0,None,None,None,0,None,None,0,58,"[{""DOI"": ""10.1002/mds.25945"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/amrcopenres.14007.r26584;10.21956/amr...,None,10.12688/amrcopenres.12936.2,https://doi.org/10.12688/amrcopenres.crossmark...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.12936.1"", ""ISSN""...",10.12688/amrcopenres.12936.1,10.12688,10.12688,amrcopenres.12936.1,10.12688/amrcopenres,10.12688/amrcopenres,amrcopenresearch.org,amrcopenresearch.org/articles
30,crossref::10.12688/amrcopenres.13007.1,AMRC Open Research,crossref,10.12688/amrcopenres.13007.1,10.12688/amrcopenres.13007.1,https://doi.org/10.12688/amrcopenres.13007.1,https://amrcopenresearch.org/articles/3-19/v1,https://amrcopenresearch.org/articles/3-19/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,AMRC Open Research,None,None,2517-6900,A feasibility pilot study of the effects of ne...,None,None,None,en,journal-article,None,journal-article,None,False,2021-09-01,None,2022-04-08,2026-02-27,None,2021-09-01,None,2021-09-01,2021-09-01,2021.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p>\n <ns3:bold>Introdu...,Introduction: Dysphagia often occurs during Pa...,"[{""URL"": ""https://amrcopenresearch.org/article...",https://amrcopenresearch.org/articles/3-19/v1/pdf,"Sasegbon, Ayodele; Hammerbeck, Ulrike; Michou,...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2050-0...",None,None,"[{""DOI"": ""10.13039/501100000304"", ""award"": [""G...",Parkinson's UK,1.0,None,None,None,8,None,None,8,43,"[{""DOI"": ""10.1016/j.neuro.2016.04.003"", ""artic...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/amrcopenres.14082.r26775;10.21956/amr...,None,10.12688/amrcopenres.13007.2,https://doi.org/10.12688/amrcopenres.crossmark...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.13007.1"", ""ISSN""...",10.12688/amrcopenres.13007.1,10.12688,10.12688,amrcopenres.13007.1,10.12688/amrcopenres,10.12688/amrcopenres,amrcopenresearch.org,amrcopenresearch.org/articles
31,crossref::10.12688/amrcopenres.13007.2,AMRC Open Research,crossref,10.12688/amrcopenres.13007.2,10.12688/amrcopenres.13007.2,https://doi.org/10.12688/amrcopenres.13007.2,https://amrcopenresearch.org/articles/3-19/v2,https://amrcopenresearch.org/articles/3-19/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,AMRC Open Research,None,None,2517-6900,A feasibility pilot study of the effects of ne...,None,None,None,en,journal-article,None,journal-article,None,False,2022-04-08,None,2022-05-23,2026-02-27,None,2022-04-08,None,2022-04-08,2022-04-08,2022.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n <ns4:bold>Introdu...,Introduction: Dysphagia often occurs during Pa...,"[{""URL"": ""https://amrcopenresearch.org/article...",https://amrcopenresearch.org/articles/3-19/v2/pdf,"Sasegbon, Ayodele; Hammerbeck, Ulrike; Michou,...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2050-0...",None,None,"[{""DOI"": ""10.13039/501100000304"", ""award"": [""G...",Parkinson's UK,1.0,None,None,None,2,None,None,2,46,"[{""DOI"": ""10.1016/j.neuro.2016.04.003"", ""artic...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/amrcopenres.14146.r26969;10.21956/amr...,"[{""DOI"": ""10.12688/amrcopenres.13007.1"", ""labe...",None,https://doi.org/10.12688/amrcopenres.crossmark...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.13007.2"", ""ISSN""...",10.12688/amrcopenres.13007.2,10.12688,10.12688,amrcopenres.13007.2,10.12688/amrcopenres,10.12688/amrcopenres,amrcopenresearch.org,amrcopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,crossref::10.12688/amrcopenres.13023.1,AMRC Open Research,crossref,10.12688/amrcopenres.13023.1,10.12688/amrcopenres.13023.1,https://doi.org/10.12688/amrcopenres.13023.1,https://healthopenresearch.org/articles/3-23/v1,https://healthopenresearch.org/articles/3-23/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Health Open Research,None,None,2753-6416,What do we know about the impact of the Covid-...,None,None,None,en,journal-article,None,journal-article,None,False,2021-10-09,None,2024-04-11,2026-02-27,None,2021-10-06,None,2021-10-06,2021-10-06,2021.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p>Background Prior to undertaking a study...,Background Prior to undertaking a study lookin...,"[{""URL"": ""https://healthopenresearch.org/artic...",https://healthopenresearch.org/articles/3-23/v...,"MacArtney, John; Eccles, Abi; Fleming, Joanna;...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-0879-4...",None,None,"[{""DOI"": ""10.13039/501100000269"", ""award"": [""E...",Economic and Social Research Council,1.0,None,None,None,3,None,None,3,32,"[{""DOI"": ""10.7861/clinmedicine.18-1-6"", ""artic...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/amrcopenres.14098.r26821;10.21956/amr...,None,None,https://doi.org/10.12688/healthopenres.crossma...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.13023.1"", ""ISSN""...",10.12688/amrcopenres.13023.1,10.12688,10.12688,amrcopenres.13023.1,10.12688/amrcopenres,10.12688/amrcopenres,healthopenresearch.org,healthopenresearch.org/articles
40,crossref::10.12688/amrcopenres.12975.3,AMRC Open Research,crossref,10.12688/amrcopenres.12975.3,10.12688/amrcopenres.12975.3,https://doi.org/10.12688/amrcopenres.12975.3,https://healthopenresearch.org/articles/3-10/v3,https://healthopenresearch.org/articles/3-10/v3,10.12688,2560,None,None,crossref,F1000 Research Ltd,Health Open Research,None,None,2753-6416,What gives a stroke publication impact? Assess...,None,None,None,en,journal-article,None,journal-article,None,False,2022-11-23,None,2023-01-13,2026-02-27,None,2022-11-23,None,2022-11-23,2022-11-23,2022.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n <ns4:bold>Backgro...,Background : The ‘impact’ of a scientific pape...,"[{""URL"": ""https://healthopenresearch.org/artic...",https://healthopenresearch.org/articles/3-10/v...,"Wong, Li Siang; Drozdowska, Bogna A; Doherty, ...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2058-6...",None,None,"[{""DOI"": ""10.13039/501100000364"", ""award"": [""P...",Stroke Association; Chief Scientist Office,3.0,None,None,None,0,None,None,0,27,"[{""article-title"": ""Metrics"", ""journal-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/amrcopenres.14205.r27030,"[{""DOI"": ""10.12688/amrcopenres.12975.1"", ""labe...",None,https://doi.org/10.12688/healthopenres.crossma...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.12975.3"", ""ISSN""...",10.12688/amrcopenres.12975.3,10.12688,10.12688,amrcopenres.12975.3,10.12688/amrcopenres,10.12688/amrcopenres,healthopenresearch.org,healthopenresearch.org/articles
24,crossref::10.12688/amrcopenres.12975.1,AMRC Open Research,crossref,10.12688/amrcopenres.12975.1,10.12688/amrcopenres.12975.1,https://doi.org/10.12688/amrcopenres.12975.1,https://amrcopenresearch.org/articles/3-10/v1,https://amrcopenresearch.org/articles/3-10/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,AMRC Open Research,None,None,2517-6900,What gives a stroke publication impact? Assess...,None,None,None,en,journal-article,None,journal-article,None,False,2021-03-16,None,2021-12-13,2026-02-27,None,2021-03-16,None,2021-03-16,2021-03-16,2021.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p>\n <ns3:bold>Backgro...,Background : The ‘impact’ of a scientific pape...,"[{""URL"": ""https://amrcopenresearch.org/article...",https://amrcopenresearch.org/articles/3-10/v1/pdf,"Wong, Li Siang; Drozdowska, Bogna A; Doherty, ...",None,None,"[{""affiliation"": [], ""family"": ""Wong"", ""given""...",None,None,"[{""DOI"": ""10.13039/501100000364"", ""award"": [""P...",Stroke Association; Chief Scientist Office,3.0,None,None,None,0,None,None,0,26,"[{""article-title"": ""Metrics"", ""journal-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/amrcopenres.14046.r26636;10.21956/amr...,None,10.12688/amrcopenres.12975.2,https://doi.org/10.12688/amrcopenres.crossmark...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.12975.1"", ""ISSN""...",10.12688/amrcopenres.12975.1,10.12688,10.12688,amrcopenres.12975.1,10.12688/amrcopenres,10.12688/amrcopenres,amrcopenresearch.org,amrcopenresearch.org/articles
39,crossref::10.12688/amrcopenres.12975.2,AMRC Open Research,crossref,10.12688/amrcopenres.12975.2,10.12688/amrcopenres.12975.2,https://doi.org/10.12688/amrcopenres.12975.2,https://healthopenresearch.org/articles/3-10/v2,https://healthopenresearch.org/articles/3-10/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Health Open Research,None,None,2753-6416,What gives a stroke publication impact? Assess...,None,None,None,en,journal-article,None,journal-article,None,False,2021-12-13,None,2022-11-23,2026-02-27,None,2021-12-13,None,2021-12-13,2021-12-13,2021.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n <ns4:bold>Backgro...,Background : The ‘impact’ of a scientific pape...,"[{""URL"": ""https://healthopenresearch.org/artic...",https://healthopenresearch.org/articles/3-10/v...,"Wong, Li Siang; Drozdowska, Bogna A; Doherty, ...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2058-6...",None,None,"[{""DOI"": ""10.13039/501100000364"", ""award"": [""P...",Stroke Association; Chief Scientist Office,3.0,None,None,None,0,None,None,0,27,"[{""article-title"": ""Metrics"", ""journal-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/amrcopenres.14119.r26884;10.21956/amr...,"[{""DOI"": ""10.12688/amrcopenres.12975.1"", ""labe...",10.12688/amrcopenres.12975.3,https://doi.org/10.12688/healthopenres.crossma...,issn,0,None,"{""DOI"": ""10.12688/amrcopenres.12975.2"", ""ISSN""...",10.12688/amrcopenres.12975.2,10.12688,10.12688,amrcopenres.12975.2,10.12688/amrcopenres,10.12688/amrcopenres,healthopenresearch.org,healthopenresearch.org/articles
101,crossref::10.12688/amrcopenres.crossmark-policy,AMRC Open Research,crossref,10.12688/amrcopenres.crossmark-policy,10.12688/amrcopenres.crossmark-policy,https://doi.org/10.12688/amrcopenres.crossmark...,https://amrcopenresearch.org/about/policies,https://amrcopenresearch.org/about/policies,10.12688,2560,None,None,crossref,F1000 Research Ltd,AMRC Open Research CrossMark Policy Statement,None,None,None,None,None,None,None,None,dataset,None,dataset,None,False,2018-11-14,None,2018-11-14,2022-04-04,None,None,None,None,None,NaN,created_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,None,None,prefix/primary_domain,1,None,"{""DOI"": ""10.12688/amrcopenres.crossmark-policy...",10.12688/amrcopenres.crossmark-policy,10.12688,10.12688,amrcopenres.crossmark-policy,10.12688/amrcopenres,10.12688/amrcopenres,amrcopenresearch.org,amrcopenresearch.org/about

In [38]:
AMRC_parent_df, AMRC_parent_summary = analyze_parent_data("AMRC Open Research", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: AMRC OPEN RESEARCH
=================================================================
  > Total Parent Groups:     69
  > Total Versions Found:    99
  > Unique Parent DOIs:      69
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for AMRC Open Research:
-----------------------------------
  1 version(s):     43 groups
  2 version(s):     22 groups
  3 version(s):     4 groups

  Average versions per parent: 1.43

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
AMRC Open Research    69

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/healthopenres    35
10.12688/amrcopenres      34



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
healthopenresearch.org    41
amrcopenresearch.org      28


=================================================================
 COMPLETED: AMRC OPEN RESEARCH
=================================================================

# APSA Preprints

In [39]:
APSA_Preprints_df, APSA_Preprints_summary = get_server_data("APSA_Preprints")

==================================================
 SERVER ANALYSIS: APSA_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    1470
  > Cleaned shape:  (1470, 90)
  > Unique DOIs:    1470
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.33774/apsa-    1470
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.apsanet.org    1470
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.33774    1470
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
56    1470
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Cambridge University Press (CUP)    1470
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    1470
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1470
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Politics and International Relations    1470
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    1470
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    1470
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    1470
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR APSA_PREPRINTS
==================================================

In [40]:
APSA_parent_df, APSA_parent_summary = analyze_parent_data("APSA Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: APSA PREPRINTS
=================================================================
  > Total Parent Groups:     1,130
  > Total Versions Found:    1,497
  > Unique Parent DOIs:      1,130
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for APSA Preprints:
-----------------------------------
  1 version(s):     908 groups
  2 version(s):     149 groups
  3 version(s):     45 groups
  4 version(s):     14 groups
  5 version(s):     4 groups
  6 version(s):     3 groups
  7 version(s):     3 groups
  8 version(s):     1 groups
  9 version(s):     1 groups
  10 version(s):    1 groups
  14 version(s):    1 groups

  Average versions per parent: 1.32

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
APSA Preprints                  1089
SSRN                              27
SocArXiv                           4
Open Science Framework             3
Qeios                              1
Cambridge Open Engage              1
APSA Preprints; ResearchGate       1
Research Square                    1
Zenodo                             1
TechRxiv                           1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.33774/apsa-    1130



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.apsanet.org    1130


=================================================================
 COMPLETED: APSA PREPRINTS
=================================================================

# Arabixiv

In [41]:
Arabixiv_df, Arabixiv_summary = get_server_data("Arabixiv")

==================================================
 SERVER ANALYSIS: ARABIXIV
==================================================
  > Files found:    1
  > Raw records:    502
  > Cleaned shape:  (502, 90)
  > Unique DOIs:    502
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31221/osf    412
10.31219/osf     34
10.31227/osf     25
10.31234/osf     14
10.31235/osf      6
10.31223/osf      5
10.31220/osf      3
10.31228/osf      2
10.31225/osf      1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    502
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31221    412
10.31219     34
10.31227     25
10.31234     14
10.31235      6
10.31223      5
10.31220      3
10.31228      2
10.31225      1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    494
29705      5
242        3
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             494
California Digital Library (CDL)      5
CABI Publishing                       3
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    502
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    502
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Arabixiv    502
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    502
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    502
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    502
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ARABIXIV
==================================================

In [42]:
Arabixiv_parent_df, Arabixiv_parent_summary = analyze_parent_data("Arabixiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ARABIXIV
=================================================================
  > Total Parent Groups:     476
  > Total Versions Found:    585
  > Unique Parent DOIs:      476
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Arabixiv:
-----------------------------------
  1 version(s):     383 groups
  2 version(s):     78 groups
  3 version(s):     14 groups
  4 version(s):     1 groups

  Average versions per parent: 1.23

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Arabixiv                            457
Frenxiv                              11
Arabixiv; Open Science Framework      4
ResearchGate                          2
Arabixiv; Frenxiv; SocArXiv           1
Open Science Framework                1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31221/osf    471
10.17605/osf      5



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io          471
arabixiv.org      5


=================================================================
 COMPLETED: ARABIXIV
=================================================================

# ARPHA Preprints

In [43]:
ARPHA_df, ARPHA_summary = get_server_data("ARPHA_Preprints")

==================================================
 SERVER ANALYSIS: ARPHA_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    890
  > Cleaned shape:  (890, 90)
  > Unique DOIs:    890
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.3897/arphapreprints    890
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.arphahub.com    890
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.3897    890
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2258    890
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Pensoft Publishers    890
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    890
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
ARPHA Preprints    890
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Research Ideas and Outcomes             205
Biodiversity Data Journal               201
ZooKeys                                 108
NeoBiota                                 98
PhytoKeys                                66
Nature Conservation                      26
Metabarcoding and Metagenomics           26
One Ecosystem                            25
Population and Economics                 21
Neotropical Biology and Conservation     19
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    890
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    890
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    890
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ARPHA_PREPRINTS
==================================================

In [44]:
ARPHA_parent_df, ARPHA_parent_summary = analyze_parent_data("ARPHA Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ARPHA PREPRINTS
=================================================================
  > Total Parent Groups:     855
  > Total Versions Found:    881
  > Unique Parent DOIs:      855
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ARPHA Preprints:
-----------------------------------
  1 version(s):     830 groups
  2 version(s):     24 groups
  3 version(s):     1 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ARPHA Preprints    851
SSRN                 1
bioRxiv              1
Research Square      1
Zenodo               1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.3897/arphapreprints    855



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.arphahub.com    855


=================================================================
 COMPLETED: ARPHA PREPRINTS
=================================================================

# ART-Dok

In [45]:
ART_df, ART_summary = get_server_data("ART-Dok")

==================================================
 SERVER ANALYSIS: ART-DOK
==================================================
  > Files found:    2
  > Raw records:    9653
  > Cleaned shape:  (9653, 90)
  > Unique DOIs:    9653
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.11588/artdok    9653
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
archiv.ub.uni-heidelberg.de    9651
ub.uni-heidelberg.de              2
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.11588    9653
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    9653
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Heidelberg University Library        9644
None                                    5
Vandenhoeck & Ruprecht                  1
Muzeum Uniwersytetu Warszawskiego       1
Biblioteka Jagiellońska                 1
Deutscher Kunstverlag                   1
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    9653
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    9653
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    9653
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    9653
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Text          9640
Collection       7
None             6
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
BookSection    5260
Article        3051
Misc            652
Monograph       508
Thesis          169
Periodical        7
None              6
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ART-DOK
==================================================

In [46]:
ART_parent_df, ART_parent_summary = analyze_parent_data("ART-Dok", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ART-DOK
=================================================================
  > Total Parent Groups:     9,529
  > Total Versions Found:    9,654
  > Unique Parent DOIs:      9,529
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ART-Dok:
-----------------------------------
  1 version(s):     9,426 groups
  2 version(s):     91 groups
  3 version(s):     10 groups
  4 version(s):     1 groups
  12 version(s):    1 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ART-Dok                    9527
Humanities Commons CORE       2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.11588/artdok    9529



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
archiv.ub.uni-heidelberg.de    9527
ub.uni-heidelberg.de              2


=================================================================
 COMPLETED: ART-DOK
=================================================================

# arXiv

In [47]:
# arXiv_df, arXiv_summary = get_server_data("arXiv")

In [48]:
arXiv_parent_df, arXiv_parent_summary = analyze_parent_data("arXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ARXIV
=================================================================
  > Total Parent Groups:     2,857,685
  > Total Versions Found:    2,939,445
  > Unique Parent DOIs:      2,857,685
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for arXiv:
-----------------------------------
  1 version(s):     2,784,275 groups
  2 version(s):     66,944 groups
  3 version(s):     5,329 groups
  4 version(s):     772 groups
  5 version(s):     223 groups
  6 version(s):     74 groups
  7 version(s):     29 groups
  8 version(s):     13 groups
  9 version(s):     10 groups
  10 version(s):    2 groups
  11 version(s):    5 groups
  12 version(s):    4 groups
  13 version(s):    2 groups
  14 version(s):    1 groups
  19 version(s):    1 groups
  69 version(s):    1 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
arXiv                                         2821925
SSRN                                            10421
Research Square                                  4231
ResearchGate                                     4184
HAL; arXiv                                       3502
RePEc: Research Papers in Economics; arXiv       3088
HAL                                              2025
CERN document server; arXiv                      1055
bioRxiv                                          1029
TechRxiv                                          925

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.48550/arxiv    2857685



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
arxiv.org    2857685


=================================================================
 COMPLETED: ARXIV
=================================================================

# Authorea Inc.

In [49]:
Authorea_df, Authorea_summary = get_server_data("Authorea_Inc.")

==================================================
 SERVER ANALYSIS: AUTHOREA_INC.
==================================================
  > Files found:    1
  > Raw records:    65450
  > Cleaned shape:  (65450, 90)
  > Unique DOIs:    65450
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.22541/au          61998
10.22541/essoar       3325
10.1002/essoar         105
10.22541/21docs         17
10.22541/techrxiv        2
10.31124/advance         2
10.15200/winn            1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
authorea.com                    61424
essopenarchive.org               3594
techrxiv.org                      374
advance.sagepub.com                46
journal.sketchingscience.org        4
21docs.com                          4
cise@computer.org                   3
doi.org                             1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.22541    65342
10.1002       105
10.31124        2
10.15200        1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
311    65448
179        2
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Wiley                65448
SAGE Publications        2
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    65450
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
Authorea, Inc.    42596
Authorea Inc.     22854
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Preprints    65450
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    65450
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    65450
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    65450
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR AUTHOREA_INC.
==================================================

In [50]:
Authorea_parent_df, Authorea_parent_summary = analyze_parent_data("Authorea Inc.", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: AUTHOREA INC.
=================================================================
  > Total Parent Groups:     56,167
  > Total Versions Found:    60,446
  > Unique Parent DOIs:      56,167
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Authorea Inc.:
-----------------------------------
  1 version(s):     52,683 groups
  2 version(s):     2,976 groups
  3 version(s):     375 groups
  4 version(s):     90 groups
  5 version(s):     17 groups
  6 version(s):     10 groups
  7 version(s):     4 groups
  8 version(s):     2 groups
  9 version(s):     2 groups
  11 version(s):    1 groups
  12 version(s):    1 groups
  14 version(s):    1 groups
  15 version(s):    2 groups
  16 version(s):    1 groups
  17 version(s):    1 groups
  19 version(s):    1 groups

  Average versions per parent: 1.08

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Authorea Inc.                           55050
Research Square                           488
SSRN                                      212
arXiv                                      90
bioRxiv                                    74
Preprints.org                              31
Open Science Framework                     22
Earth and Space Science Open Archive       22
ScienceOpen Preprints                      17
medRxiv                                    15

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.22541/au          56153
10.22541/21docs         11
10.22541/techrxiv        2
10.15200/winn            1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
authorea.com                    55478
essopenarchive.org                365
techrxiv.org                      282
advance.sagepub.com                35
cise@computer.org                   3
journal.sketchingscience.org        2
21docs.com                          2


=================================================================
 COMPLETED: AUTHOREA INC.
=================================================================

In [51]:
Authorea_parent_df[Authorea_parent_df['primary_domain']=='techrxiv.org']

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
11183,crossref::10.22541/au.175649113.36750850/v1,crossref::10.22541/au.175649113.36750850/v1,Authorea Inc.,10.22541/au.175649113.36750850/v1,https://www.techrxiv.org/users/960820/articles...,Prediction of Overall Survival Status of Diffu...,"Ganapathy, Ananya",2025-08-29,2025,crossref::10.22541/au.175649113.36750850/v1,10.22541/au.175649113.36750850/v1,Authorea Inc. (1),1,2025-08-29,2025-08-29,Authorea Inc.,10.22541/au.175649113.36750850/v1,10.22541,10.22541,au.175649113.36750850/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
68488,crossref::10.22541/au.175192051.19091421/v1,crossref::10.22541/au.175192051.19091421/v1,Authorea Inc.,10.22541/au.175192051.19091421/v1,https://www.techrxiv.org/users/940424/articles...,The Yanomami People and the Favela: A Comparat...,"Paula, Abdon de",2025-07-07,2025,crossref::10.22541/au.175192051.19091421/v1,10.22541/au.175192051.19091421/v1,Authorea Inc. (1),1,2025-07-07,2025-07-07,Authorea Inc.,10.22541/au.175192051.19091421/v1,10.22541,10.22541,au.175192051.19091421/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
70326,crossref::10.22541/au.170379738.88140454/v1,crossref::10.22541/au.170379738.88140454/v1,Authorea Inc.,10.22541/au.170379738.88140454/v1,https://www.techrxiv.org/users/712087/articles...,Real-time Detection of Low-Rate DDoS Attacks i...,"Alashhab, Abdussalam Ahmed; Zahid, Mohd Soperi...",2023-12-28,2023,crossref::10.22541/au.170379738.88140454/v1,10.22541/au.170379738.88140454/v1,Authorea Inc. (1),1,2023-12-28,2023-12-28,Authorea Inc.,10.22541/au.170379738.88140454/v1,10.22541,10.22541,au.170379738.88140454/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
79897,crossref::10.22541/au.170216685.50804614/v1,crossref::10.22541/au.170216685.50804614/v1,Authorea Inc.,10.22541/au.170216685.50804614/v1,https://techrxiv.org/users/684836/articles/692...,Ayurveda for One Health,"Bansal, Abhishek",2023-12-10,2023,crossref::10.22541/au.170216685.50804614/v1,10.22541/au.170216685.50804614/v1,Authorea Inc. (1),1,2023-12-10,2023-12-10,Authorea Inc.,10.22541/au.170216685.50804614/v1,10.22541,10.22541,au.170216685.50804614/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
140826,crossref::10.22541/au.175950949.97637298/v1,crossref::10.22541/au.175950949.97637298/v1,Authorea Inc.,10.22541/au.175950949.97637298/v1,https://www.techrxiv.org/users/972385/articles...,Coordinated Aerial-Ground Swarm System for Pre...,"Mahmood, Ayan; Khalid, Ali; Saif, Muhammad",2025-10-03,2025,crossref::10.22541/au.175950949.97637298/v1,10.22541/au.175950949.97637298/v1,Authorea Inc. (1),1,2025-10-03,2025-10-03,Authorea Inc.,10.22541/au.175950949.97637298/v1,10.22541,10.22541,au.175950949.97637298/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7226091,crossref::10.22541/au.171804670.01201352/v1,crossref::10.22541/au.171804670.01201352/v1,Authorea Inc.,10.22541/au.171804670.01201352/v1,https://www.techrxiv.org/users/714701/articles...,Machine Learning-assisted Partially Blind Hand...,"Yazici, İbrahim; Gures, Emre",2024-06-10,2024,crossref::10.22541/au.171804670.01201352/v1,10.22541/au.171804670.01201352/v1,Authorea Inc. (1),1,2024-06-10,2024-06-10,Authorea Inc.,10.22541/au.171804670.01201352/v1,10.22541,10.22541,au.171804670.01201352/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
7243082,crossref::10.22541/au.171032701.12008685/v1,crossref::10.22541/au.171032701.12008685/v1,Authorea Inc.,10.22541/au.171032701.12008685/v1,https://www.techrxiv.org/users/693747/articles...,Reduced Sensor Lyapunov-Based Control for Acti...,"Liu, Yonglu; Yuan, Yinhao; Xu, Guo; Li, Liting...",2024-03-13,2024,crossref::10.22541/au.171032701.12008685/v1,10.22541/au.171032701.12008685/v1,Authorea Inc. (1),1,2024-03-13,2024-03-13,Authorea Inc.,10.22541/au.171032701.12008685/v1,10.22541,10.22541,au.171032701.12008685/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
7258674,crossref::10.22541/au.175615705.53181689/v1,crossref::10.22541/au.175615705.53181689/v1,Authorea Inc.,10.22541/au.175615705.53181689/v1,https://www.techrxiv.org/users/683174/articles...,Pixel-Based CF-mMIMO: Addressing the AP Cooper...,"Pereira-Ruisánchez, Dariel; Joham, Michael; Fr...",2025-08-25,2025,crossref::10.22541/au.175615705.53181689/v1,10.22541/au.175615705.53181689/v1,Authorea Inc. (1),1,2025-08-25,2025-08-25,Authorea Inc.,10.22541/au.175615705.53181689/v1,10.22541,10.22541,au.175615705.53181689/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
7275937,crossref::10.22541/au.174197372.24783722/v1,crossref::10.22541/au.174197372.24783722/v1,Authorea Inc.,10.22541/au.174197372.24783722/v1,https://www.techrxiv.org/users/743163/articles...,IEEE Journal of Selected Areas in Sensors CALL...,"Ranjha, Ali",2025-03-14,2025,crossref::10.22541/au.174197372.24783722/v1,10.22541/au.174197372.24783722/v1,Authorea Inc. (1),1,2025-03-14,2025-03-14,Authorea Inc.,10.22541/au.174197372.24783722/v1,10.22541,10.22541,au.174197372.24783722/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users
7340507,crossref::10.22541/au.175856329.91218062/v1,crossref::10.22541/au.175856329.91218062/v1,Authorea Inc.,10.22541/au.175856329.91218062/v1,https://www.techrxiv.org/users/777751/articles...,A Transformational Unification of Quantum Mech...,"Ngu, Alexander; Kosso, Amaya Odilon",2025-09-22,2025,crossref::10.22541/au.175856329.91218062/v1; c...,10.22541/au.175856329.91218062/v1; 10.22541/au...,Authorea Inc. (2),2,2025-09-22,2025-10-01,Authorea Inc.,10.22541/au.175856329.91218062/v1,10.22541,10.22541,au.175856329.91218062/v1,10.22541/au,10.22541/au,techrxiv.org,techrxiv.org/users

https://doi.org/10.22541/au.171804670.01201352/v1   ---> https://www.authorea.com/users/714701/articles/892429-machine-learning-assisted-partially-blind-handover-prediction-in-5g-network-systems

on Authorea

In [52]:
Authorea_parent_df[Authorea_parent_df['primary_domain']=='essopenarchive.org']

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
61432,crossref::10.22541/au.170052235.59584468/v1,crossref::10.22541/au.170052235.59584468/v1,Authorea Inc.,10.22541/au.170052235.59584468/v1,https://essopenarchive.org/users/700416/articl...,Kinetics of melt-rock and melt-rock-fluid inte...,"Borisova, Anastassia Y.; Schott, Jacques; Topl...",2023-11-20,2023,crossref::10.22541/au.170052235.59584468/v1,10.22541/au.170052235.59584468/v1,Authorea Inc. (1),1,2023-11-20,2023-11-20,Authorea Inc.,10.22541/au.170052235.59584468/v1,10.22541,10.22541,au.170052235.59584468/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
72467,crossref::10.22541/au.176583173.39004043/v1,crossref::10.22541/au.176583173.39004043/v1,Authorea Inc.,10.22541/au.176583173.39004043/v1,https://essopenarchive.org/users/995512/articl...,Europa Surface Spectrophotometry -- Preparing ...,"Benton, Zeina; Seelos, Frank; Itoh, Yuki; Step...",2025-12-15,2025,crossref::10.22541/au.176583173.39004043/v1,10.22541/au.176583173.39004043/v1,Authorea Inc. (1),1,2025-12-15,2025-12-15,Authorea Inc.,10.22541/au.176583173.39004043/v1,10.22541,10.22541,au.176583173.39004043/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
74890,crossref::10.22541/au.176046418.80101496/v1,crossref::10.22541/au.176046418.80101496/v1,Authorea Inc.,10.22541/au.176046418.80101496/v1,https://essopenarchive.org/users/975696/articl...,Data Centers Water Footprint: The Need for Mor...,"Privette, Ana Pinheiro; Barros, Ana P.; Cai, X...",2025-10-14,2025,crossref::10.22541/au.176046418.80101496/v1,10.22541/au.176046418.80101496/v1,Authorea Inc. (1),1,2025-10-14,2025-10-14,Authorea Inc.,10.22541/au.176046418.80101496/v1,10.22541,10.22541,au.176046418.80101496/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
75372,crossref::10.22541/au.168147732.23405579/v1,crossref::10.22541/au.168147732.23405579/v1,Authorea Inc.,10.22541/au.168147732.23405579/v1,https://essopenarchive.org/users/593062/articl...,Effect of seasonal freeze-thaw process on spat...,"Sun, Jingwei; Wang, Fugang; Ding, Lujiao; Wang...",2023-04-14,2023,crossref::10.22541/au.168147732.23405579/v1,10.22541/au.168147732.23405579/v1,Authorea Inc. (1),1,2023-04-14,2023-04-14,Authorea Inc.,10.22541/au.168147732.23405579/v1,10.22541,10.22541,au.168147732.23405579/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
79898,crossref::10.22541/au.170258901.13051548/v1,crossref::10.22541/au.170258901.13051548/v1,Authorea Inc.,10.22541/au.170258901.13051548/v1,https://essopenarchive.org/users/709109/articl...,Signal to Noise Ratio and Spectral Sampling Co...,"Perez-Lopez, Sebastian Alonso; Kremer, Christo...",2023-12-14,2023,crossref::10.22541/au.170258901.13051548/v1,10.22541/au.170258901.13051548/v1,Authorea Inc. (1),1,2023-12-14,2023-12-14,Authorea Inc.,10.22541/au.170258901.13051548/v1,10.22541,10.22541,au.170258901.13051548/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7274361,crossref::10.22541/au.176617599.93150350/v1,crossref::10.22541/au.176617599.93150350/v1,Authorea Inc.,10.22541/au.176617599.93150350/v1,https://essopenarchive.org/users/564073/articl...,Exploring\tWavefield-Based Location Imaging in...,"Komeazi, Abolfazl; Limberger, Fabian; Rümpker,...",2025-12-19,2025,crossref::10.22541/au.176617599.93150350/v1,10.22541/au.176617599.93150350/v1,Authorea Inc. (1),1,2025-12-19,2025-12-19,Authorea Inc.,10.22541/au.176617599.93150350/v1,10.22541,10.22541,au.176617599.93150350/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
7291762,crossref::10.22541/au.167701301.18502422/v1,crossref::10.22541/au.167701301.18502422/v1,Authorea Inc.,10.22541/au.167701301.18502422/v1,https://essopenarchive.org/users/532777/articl...,Quantifying photodegradation of peatland-deriv...,"Zhou, Yongli; Müller, Moritz; Cherukuru, Nagur...",2023-02-21,2023,crossref::10.22541/au.167701301.18502422/v1,10.22541/au.167701301.18502422/v1,Authorea Inc. (1),1,2023-02-21,2023-02-21,Authorea Inc.,10.22541/au.167701301.18502422/v1,10.22541,10.22541,au.167701301.18502422/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
7318952,crossref::10.22541/au.170602913.36073822/v1,crossref::10.22541/au.170602913.36073822/v1,Authorea Inc.,10.22541/au.170602913.36073822/v1,https://essopenarchive.org/users/601386/articl...,Deciphering the isotopic imprint of nitrate to...,"Hu, Yinchao; Yu, Zhongjie; Yang, Wendy H; Marg...",2024-01-23,2024,crossref::10.22541/au.170602913.36073822/v1,10.22541/au.170602913.36073822/v1,Authorea Inc. (1),1,2024-01-23,2024-01-23,Authorea Inc.,10.22541/au.170602913.36073822/v1,10.22541,10.22541,au.170602913.36073822/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
7323551,crossref::10.22541/au.174310328.89167578/v1,crossref::10.22541/au.174310328.89167578/v1,Authorea Inc.,10.22541/au.174310328.89167578/v1,https://essopenarchive.org/users/577336/articl...,Persistent Topographic Trapping of the Middle ...,"Taenzer, Lukas L.; Gawarkiewicz, Glen G; Plued...",2025-03-27,2025,crossref::10.22541/au.174310328.89167578/v1,10.22541/au.174310328.89167578/v1,Authorea Inc. (1),1,2025-03-27,2025-03-27,Authorea Inc.,10.22541/au.174310328.89167578/v1,10.22541,10.22541,au.174310328.89167578/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users
7328739,crossref::10.22541/au.173956919.97739303/v1,crossref::10.22541/au.173956919.97739303/v1,Authorea Inc.,10.22541/au.173956919.97739303/v1,https://essopenarchive.org/users/889292/articl...,From sea to summit: Investigating the explicit...,"Kropač, Elena; Mölg, Thomas; Cullen, Nicolas J.",2025-02-14,2025,crossref::10.22541/au.173956919.97739303/v1,10.22541/au.173956919.97739303/v1,Authorea Inc. (1),1,2025-02-14,2025-02-14,Authorea Inc.,10.22541/au.173956919.97739303/v1,10.22541,10.22541,au.173956919.97739303/v1,10.22541/au,10.22541/au,essopenarchive.org,essopenarchive.org/users

In [53]:
# Authorea_parent_df['parent_url'][7322807]

In [54]:
# https://doi.org/10.22541/au.176617599.93150350/v1  ---> https://www.authorea.com/users/564073/articles/1371863-exploring-wavefield-based-location-imaging-in-heterogeneous-media-a-borehole-das-example

# Beilstein Archives

In [55]:
Beilstein_df, Beilstein_summary = get_server_data("Beilstein_Archives")

==================================================
 SERVER ANALYSIS: BEILSTEIN_ARCHIVES
==================================================
  > Files found:    1
  > Raw records:    697
  > Cleaned shape:  (697, 90)
  > Unique DOIs:    697
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.3762/bxiv    697
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
beilstein-archives.org    697
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.3762    697
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2086    697
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Beilstein Institut    697
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    697
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    697
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
organic chemistry    394
nanotechnology       303
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    697
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    697
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    697
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR BEILSTEIN_ARCHIVES
==================================================

In [6]:
Beilstein_parent_df, Beilstein_parent_summary = analyze_parent_data("Beilstein Archives", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: BEILSTEIN ARCHIVES
=================================================================
  > Total Parent Groups:     694
  > Total Versions Found:    702
  > Unique Parent DOIs:      694
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Beilstein Archives:
-----------------------------------
  1 version(s):     687 groups
  2 version(s):     6 groups
  3 version(s):     1 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Beilstein Archives    687
arXiv                   5
SSRN                    1
ChemRxiv                1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.3762/bxiv    694



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
beilstein-archives.org    694


=================================================================
 COMPLETED: BEILSTEIN ARCHIVES
=================================================================

# BioHackrXiv

In [7]:
BioHackrXiv_df, BioHackrXiv_summary = get_server_data("BioHackrXiv")

==================================================
 SERVER ANALYSIS: BIOHACKRXIV
==================================================
  > Files found:    1
  > Raw records:    139
  > Cleaned shape:  (139, 90)
  > Unique DOIs:    139
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.37044/osf    139
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    139
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.37044    139
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    139
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    139
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    139
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    139
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
BioHackrXiv    139
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    139
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    139
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    139
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR BIOHACKRXIV
==================================================

In [8]:
BioHackrXiv_parent_df, BioHackrXiv_parent_summary = analyze_parent_data("BioHackrXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: BIOHACKRXIV
=================================================================
  > Total Parent Groups:     136
  > Total Versions Found:    140
  > Unique Parent DOIs:      136
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for BioHackrXiv:
-----------------------------------
  1 version(s):     132 groups
  2 version(s):     4 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
BioHackrXiv                  135
BioHackrXiv; ResearchGate      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.37044/osf    136



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    136


=================================================================
 COMPLETED: BIOHACKRXIV
=================================================================

# bioRxiv

In [ ]:
# bioRxiv_df, bioRxiv_summary = get_server_data("bioRxiv")

In [7]:
bioRxiv_parent_df, bioRxiv_parent_summary = analyze_parent_data("bioRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: BIORXIV
=================================================================
  > Total Parent Groups:     303,393
  > Total Versions Found:    331,893
  > Unique Parent DOIs:      303,393
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for bioRxiv:
-----------------------------------
  1 version(s):     285,068 groups
  2 version(s):     14,112 groups
  3 version(s):     1,318 groups
  4 version(s):     358 groups
  5 version(s):     2,055 groups
  6 version(s):     443 groups
  7 version(s):     34 groups
  8 version(s):     4 groups
  12 version(s):    1 groups

  Average versions per parent: 1.09

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
bioRxiv            285372
eLife                9497
Research Square      3755
SSRN                 2616
arXiv; bioRxiv        413
Authorea Inc.         395
arXiv                 393
F1000Research         163
HAL                    90
Preprints.org          85

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.1101/20    237512
10.1101/10       819
10.1101/32       801
10.1101/19       800
10.1101/45       798
10.1101/42       797
10.1101/58       796
10.1101/17       796
10.1101/15       794
10.1101/30       790



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
biorxiv.org    303393


=================================================================
 COMPLETED: BIORXIV
=================================================================

# BodoArXiv

In [8]:
BodoArXiv_df, BodoArXiv_summary = get_server_data("BodoArXiv")

==================================================
 SERVER ANALYSIS: BODOARXIV
==================================================
  > Files found:    1
  > Raw records:    165
  > Cleaned shape:  (165, 90)
  > Unique DOIs:    165
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.34055/osf    162
10.31219/osf      3
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    165
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.34055    162
10.31219      3
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    165
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    165
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    165
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    165
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
BodoArXiv    165
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    165
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    165
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    165
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR BODOARXIV
==================================================

In [9]:
BodoArXiv_parent_df, BodoArXiv_parent_summary = analyze_parent_data("BodoArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: BODOARXIV
=================================================================
  > Total Parent Groups:     149
  > Total Versions Found:    161
  > Unique Parent DOIs:      149
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for BodoArXiv:
-----------------------------------
  1 version(s):     139 groups
  2 version(s):     9 groups
  4 version(s):     1 groups

  Average versions per parent: 1.08

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
BodoArXiv      147
Law Archive      1
Zenodo           1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.34055/osf    146
10.31219/osf      3



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    149


=================================================================
 COMPLETED: BODOARXIV
=================================================================

# Cambridge Open Engage

In [10]:
Cambridge_df, Cambridge_summary = get_server_data("Cambridge_Open_Engage")

==================================================
 SERVER ANALYSIS: CAMBRIDGE_OPEN_ENGAGE
==================================================
  > Files found:    1
  > Raw records:    3090
  > Cleaned shape:  (3090, 90)
  > Unique DOIs:    3090
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.33774/coe-    3090
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
cambridge.org    3090
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.33774    3090
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
56    3090
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Cambridge University Press (CUP)    3090
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    3090
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    3090
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Mathematics                         789
Physics and Astronomy               463
Earth and Environmental Sciences    266
Economics                           175
Computer Science                    146
Language and Linguistics            121
Engineering                         104
Law                                 100
Psychology                           96
Life Sciences                        82
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    3090
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    3090
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    3090
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR CAMBRIDGE_OPEN_ENGAGE
==================================================

In [11]:
Cambridge_parent_df, Cambridge_parent_summary = analyze_parent_data("Cambridge Open Engage", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: CAMBRIDGE OPEN ENGAGE
=================================================================
  > Total Parent Groups:     1,875
  > Total Versions Found:    2,976
  > Unique Parent DOIs:      1,875
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Cambridge Open Engage:
-----------------------------------
  1 version(s):     1,430 groups
  2 version(s):     266 groups
  3 version(s):     96 groups
  4 version(s):     29 groups
  5 version(s):     15 groups
  6 version(s):     6 groups
  7 version(s):     5 groups
  8 version(s):     4 groups
  9 version(s):     2 groups
  10 version(s):    1 groups
  11 version(s):    3 groups
  12 version(s):    5 groups
  14 version(s):    1 groups
  15 version(s):    2 groups
  18 version(s):    2 groups
  19 version(s):    1 groups
  20 version(s):    2 groups
  22 version(s):    1 groups
  26 version(s):    1 groups
  27 version(s):    1 groups
  32 version(s):    1 groups
  65 version(s):    1 groups

  Average versions per parent: 1.59

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Cambridge Open Engage                  1802
SSRN                                     38
Open Science Framework                    5
Cambridge Open Engage; Zenodo             4
SocArXiv                                  4
Research Square                           4
arXiv                                     3
Preprints.org                             3
TechRxiv                                  2
Cambridge Open Engage; ResearchGate       2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.33774/coe-    1875



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
cambridge.org    1875


=================================================================
 COMPLETED: CAMBRIDGE OPEN ENGAGE
=================================================================

# CERN document server

In [6]:
CERN_df, CERN_summary = get_server_data("CERN_document_server")

==================================================
 SERVER ANALYSIS: CERN_DOCUMENT_SERVER
==================================================
  > Files found:    2
  > Raw records:    2631
  > Cleaned shape:  (2631, 90)
  > Unique DOIs:    2026
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.48550/arxiv         776
<NA>                   605
10.5170/cern-          117
10.18429/jacow-ipac     71
10.17181/cern           49
10.17181/d              16
10.17181/q              15
10.17181/c              14
10.17181/m              13
10.17181/n              13
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
cds.cern.ch        1727
repository.cern     903
new-cds.cern.ch       1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.17181    950
10.48550    776
None        605
10.5170     117
10.18429     96
10.1007      14
10.1393      10
10.18154      9
10.23732      8
10.1051       7
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    2631
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None                                   1681
CERN                                    722
Next Generation Triggers, CERN           74
CERN Document Server                     44
Next Generation Triggers                 14
CERN, CMS, Next Generation Triggers       8
University of Hyderabad                   6
TU Dresden                                6
CERN, Next Generation Triggers            4
University of Southampton                 4
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    2631
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    2631
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    2631
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2631
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
preprint           1681
Text                573
Report              226
Preprint            119
ConferencePaper      25
JournalArticle        7
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None                      1727
                           397
Thesis                     223
Technical note             138
Presentation                98
Poster                      26
Other                       13
Proposal                     4
Software documentation       3
Working paper                2
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR CERN_DOCUMENT_SERVER
==================================================

In [7]:
CERN_df, CERN_summary = get_server_data("CERN_document_server")

==================================================
 SERVER ANALYSIS: CERN_DOCUMENT_SERVER
==================================================
  > Files found:    2
  > Raw records:    2631
  > Cleaned shape:  (2631, 90)
  > Unique DOIs:    2026
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.48550/arxiv         776
<NA>                   605
10.5170/cern-          117
10.18429/jacow-ipac     71
10.17181/cern           49
10.17181/d              16
10.17181/q              15
10.17181/c              14
10.17181/m              13
10.17181/n              13
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
cds.cern.ch        1727
repository.cern     903
new-cds.cern.ch       1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.17181    950
10.48550    776
None        605
10.5170     117
10.18429     96
10.1007      14
10.1393      10
10.18154      9
10.23732      8
10.1051       7
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    2631
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None                                   1681
CERN                                    722
Next Generation Triggers, CERN           74
CERN Document Server                     44
Next Generation Triggers                 14
CERN, CMS, Next Generation Triggers       8
University of Hyderabad                   6
TU Dresden                                6
CERN, Next Generation Triggers            4
University of Southampton                 4
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    2631
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    2631
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    2631
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2631
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
preprint           1681
Text                573
Report              226
Preprint            119
ConferencePaper      25
JournalArticle        7
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None                      1727
                           397
Thesis                     223
Technical note             138
Presentation                98
Poster                      26
Other                       13
Proposal                     4
Software documentation       3
Working paper                2
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR CERN_DOCUMENT_SERVER
==================================================

In [8]:
CERN_parent_df, CERN_parent_summary = analyze_parent_data("CERN document server", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: CERN DOCUMENT SERVER
=================================================================
  > Total Parent Groups:     975
  > Total Versions Found:    1,670
  > Unique Parent DOIs:      697
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for CERN document server:
-----------------------------------
  1 version(s):     433 groups
  2 version(s):     458 groups
  3 version(s):     52 groups
  4 version(s):     15 groups
  5 version(s):     7 groups
  6 version(s):     5 groups
  7 version(s):     3 groups
  8 version(s):     1 groups
  11 version(s):    1 groups

  Average versions per parent: 1.71

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
CERN document server                                   797
arXiv                                                  170
HAL                                                      2
Munich Personal RePEc Archive                            2
CERN document server; arXiv                              1
CERN document server; Munich Personal RePEc Archive      1
viXra                                                    1
CERN document server; HAL                                1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>                   278
10.5170/cern-          108
10.18429/jacow-ipac     71
10.17181/cern           40
10.1007/jhep            10
10.18154/rwth-           9
10.1393/ncc              7
10.23732/cyrcp-          7
10.18429/jacow-ibic      7
10.17181/m               6



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
cds.cern.ch        588
repository.cern    387


=================================================================
 COMPLETED: CERN DOCUMENT SERVER
=================================================================

In [9]:
CERN_df_cds = CERN_df[CERN_df['backend']=='cds']
CERN_df_cds

Empty DataFrame
Columns: [record_id, server_name, backend, source_work_id, doi, doi_url, landing_page_url, url_best, prefix, member_id, client_id, provider_id, source_registry, publisher, container_title, institution_name, group_title, issn, title, original_title, short_title, subtitle, language, type_backend_raw, subtype_backend_raw, type_canonical, is_paratext, is_preprint_candidate, date_created, date_posted, date_deposited, date_indexed, date_updated, date_issued, date_registered, date_published, date_published_online, publication_year, date_published_source, date_posted_source, is_oa, oa_status, license, license_url_best, abstract_raw, abstract_text, links_json_best, fulltext_pdf_url, authors_flat, institutions_flat, countries_flat, authors_json, contributors_json, editors_json, funders_json, funders_flat, funders_count, subjects_json, concepts_json, topics_json, cited_by_count, cited_by_count_datacite, cited_by_count_openalex, is_referenced_by_count_crossref, reference_count, references_json, relations_json, has_preprint, is_preprint_of, has_published_version, published_version_ids_json, is_version_of, version_of_ids_json, version_label, has_review, update_to_json, parent_doi, update_policy, rule_tokens, rule_row_id, raw_relationships_json, raw_json, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

In [10]:
pattern = r'preprint'
# pattern = r'v\d+$'
mask = CERN_df_cds['raw_json'].str.contains(pattern, regex=True, na=False)
result = CERN_df_cds[mask]
result

Empty DataFrame
Columns: [record_id, server_name, backend, source_work_id, doi, doi_url, landing_page_url, url_best, prefix, member_id, client_id, provider_id, source_registry, publisher, container_title, institution_name, group_title, issn, title, original_title, short_title, subtitle, language, type_backend_raw, subtype_backend_raw, type_canonical, is_paratext, is_preprint_candidate, date_created, date_posted, date_deposited, date_indexed, date_updated, date_issued, date_registered, date_published, date_published_online, publication_year, date_published_source, date_posted_source, is_oa, oa_status, license, license_url_best, abstract_raw, abstract_text, links_json_best, fulltext_pdf_url, authors_flat, institutions_flat, countries_flat, authors_json, contributors_json, editors_json, funders_json, funders_flat, funders_count, subjects_json, concepts_json, topics_json, cited_by_count, cited_by_count_datacite, cited_by_count_openalex, is_referenced_by_count_crossref, reference_count, references_json, relations_json, has_preprint, is_preprint_of, has_published_version, published_version_ids_json, is_version_of, version_of_ids_json, version_label, has_review, update_to_json, parent_doi, update_policy, rule_tokens, rule_row_id, raw_relationships_json, raw_json, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

In [11]:
# for x in result.sample(1).iloc[0]:
#     print(x)

In [12]:
pattern = r'cerncds:BOOK'
# pattern = r'v\d+$'
mask = CERN_df_cds['raw_json'].str.contains(pattern, regex=True, na=False)
result = CERN_df_cds[mask]
result

Empty DataFrame
Columns: [record_id, server_name, backend, source_work_id, doi, doi_url, landing_page_url, url_best, prefix, member_id, client_id, provider_id, source_registry, publisher, container_title, institution_name, group_title, issn, title, original_title, short_title, subtitle, language, type_backend_raw, subtype_backend_raw, type_canonical, is_paratext, is_preprint_candidate, date_created, date_posted, date_deposited, date_indexed, date_updated, date_issued, date_registered, date_published, date_published_online, publication_year, date_published_source, date_posted_source, is_oa, oa_status, license, license_url_best, abstract_raw, abstract_text, links_json_best, fulltext_pdf_url, authors_flat, institutions_flat, countries_flat, authors_json, contributors_json, editors_json, funders_json, funders_flat, funders_count, subjects_json, concepts_json, topics_json, cited_by_count, cited_by_count_datacite, cited_by_count_openalex, is_referenced_by_count_crossref, reference_count, references_json, relations_json, has_preprint, is_preprint_of, has_published_version, published_version_ids_json, is_version_of, version_of_ids_json, version_label, has_review, update_to_json, parent_doi, update_policy, rule_tokens, rule_row_id, raw_relationships_json, raw_json, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

In [13]:
# for x in result.sample(1).iloc[0]:
#     print(x)

In [14]:
import json
import pandas as pd

def extract_set_specs(raw_json_str):
    """
    Safely parses the raw OAI-PMH JSON string and extracts 
    set_specs elements into a clean, flat string.
    """
    # Handle missing or null records safely
    if pd.isna(raw_json_str) or not isinstance(raw_json_str, str):
        return None
        
    try:
        # 1. Parse the JSON string into a dictionary
        data = json.loads(raw_json_str)
        
        # 2. Get the 'set_specs' list (fallback to empty list if key is missing)
        specs_list = data.get("set_specs", [])
        
        if not specs_list:
            return None
            
        # 3. Clean each item (remove whitespace) and filter out any empties
        cleaned_specs = [str(spec).strip() for spec in specs_list if spec]
        
        # 4. Join multiple sets with a semicolon for flat-field consistency
        return "; ".join(cleaned_specs)
        
    except (json.JSONDecodeError, TypeError, AttributeError):
        # Fallback if the string isn't valid JSON or format is unexpected
        return None

# --- Application to your DataFrame
# Create the flat string column
CERN_df_cds["set_specs_flat"] = CERN_df_cds["raw_json"].apply(extract_set_specs)

# --- Check your results
print("Total CERN_df_cds records :", len(CERN_df_cds))
print("Null count in new column:", CERN_df_cds["set_specs_flat"].isna().sum())
print("\nTop 10 CERN Collections found:")
print("-" * 35)
print(CERN_df_cds["set_specs_flat"].value_counts(dropna=False).head(60))

Total CERN_df_cds records : 0
Null count in new column: 0

Top 10 CERN Collections found:
-----------------------------------
Series([], Name: count, dtype: int64)

In [15]:
# Count individual collection frequencies across the entire server
individual_sets = (
    CERN_df_cds["set_specs_flat"]
    .dropna()
    .str.split("; ")
    .explode()
    .value_counts()
)

print("\nIndividual Set Specification Frequencies:")
print("-" * 35)
print(individual_sets)

Individual Set Specification Frequencies:
-----------------------------------
Series([], Name: count, dtype: int64)

In [16]:
CERN_df_cds['publication_year'].value_counts().reset_index().sort_values(by='publication_year')

Empty DataFrame
Columns: [publication_year, count]
Index: []

# ChemRxiv

In [25]:
ChemRxiv_df, ChemRxiv_summary = get_server_data("ChemRxiv")

==================================================
 SERVER ANALYSIS: CHEMRXIV
==================================================
  > Files found:    1
  > Raw records:    46475
  > Cleaned shape:  (46475, 90)
  > Unique DOIs:    46475
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.26434/chemrxiv-    35040
10.26434/chemrxiv     11435
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
chemrxiv.org    46475
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.26434    46475
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
316    46475
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
American Chemical Society (ACS)    46475
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    46475
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    46475
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Chemistry    46474
None             1
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    46475
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    46475
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    46475
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR CHEMRXIV
==================================================

In [26]:
ChemRxiv_parent_df, ChemRxiv_parent_summary = analyze_parent_data("ChemRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: CHEMRXIV
=================================================================
  > Total Parent Groups:     36,128
  > Total Versions Found:    46,790
  > Unique Parent DOIs:      36,128
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ChemRxiv:
-----------------------------------
  1 version(s):     28,095 groups
  2 version(s):     6,242 groups
  3 version(s):     1,341 groups
  4 version(s):     303 groups
  5 version(s):     83 groups
  6 version(s):     25 groups
  7 version(s):     14 groups
  8 version(s):     7 groups
  9 version(s):     5 groups
  10 version(s):    2 groups
  11 version(s):    2 groups
  12 version(s):    2 groups
  13 version(s):    2 groups
  14 version(s):    1 groups
  16 version(s):    1 groups
  23 version(s):    1 groups
  31 version(s):    1 groups
  36 version(s):    1 groups

  Average versions per parent: 1.30

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ChemRxiv                  35656
Research Square             191
SSRN                        152
arXiv                        51
ChemRxiv; arXiv              18
Authorea Inc.                15
ChemRxiv; ResearchGate        6
Preprints.org                 5
Zenodo                        5
ResearchGate                  4

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.26434/chemrxiv-    27281
10.26434/chemrxiv      8847



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
chemrxiv.org    36128


=================================================================
 COMPLETED: CHEMRXIV
=================================================================

# CogPrints

In [27]:
CogPrints_df, CogPrints_summary = get_server_data("CogPrints")

==================================================
 SERVER ANALYSIS: COGPRINTS
==================================================
  > Files found:    1
  > Raw records:    1537
  > Cleaned shape:  (1537, 90)
  > Unique DOIs:    39
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>               1498
10.48550/arxiv       14
10.5281/zenodo        7
10.13140/rg           7
10.13140/2            2
10.60692/cs           1
10.6084/m             1
10.60692/frxsy-       1
10.60692/ny           1
10.48456/tr-          1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
None             1041
cogprints.org     471
doi.org            25
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        1498
10.48550      14
10.13140       9
10.5281        7
10.60692       4
10.6084        1
10.48456       1
10.71910       1
10.18267       1
10.13016       1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    1537
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    1537
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    1537
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1537
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    1537
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    1537
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article         1313
book-chapter     105
preprint          52
other             28
dissertation      24
review            11
book               4
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    1537
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR COGPRINTS
==================================================

In [28]:
# CogPrints_df

In [29]:
CogPrints_parent_df, CogPrints_parent_summary = analyze_parent_data("CogPrints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: COGPRINTS
=================================================================
  > Total Parent Groups:     1,487
  > Total Versions Found:    1,505
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for CogPrints:
-----------------------------------
  1 version(s):     1,470 groups
  2 version(s):     16 groups
  3 version(s):     1 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
CogPrints          1472
arXiv                 9
SSRN                  2
PsyArXiv              1
viXra                 1
CogPrints; HAL        1
PhilSci-Archive       1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    1487



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
None             1030
cogprints.org     457


=================================================================
 COMPLETED: COGPRINTS
=================================================================

In [30]:
pattern = r'10.48550/arxiv'
# pattern = r'v\d+$'
mask = CogPrints_parent_df['parent_doi'].str.contains(pattern, regex=True, na=False)
result = CogPrints_parent_df[mask]
result

Empty DataFrame
Columns: [dup_group_id_full, parent_record_id, parent_server_name, parent_doi, parent_url, parent_title, parent_authors, parent_date_first_seen, parent_year_first_seen, version_record_ids, version_dois, servers_with_counts, total_versions, first_version_date, last_version_date, most_recent_version_servers, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

In [31]:
pattern = r'10.48550/arxiv.physics/0001050'
# pattern = r'v\d+$'
mask = full_parent_df['parent_doi'].str.contains(pattern, regex=True, na=False)
result = full_parent_df[mask]
result

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers
4244908,datacite::10.48550/arxiv.physics/0001050,datacite::10.48550/arxiv.physics/0001050,arXiv,10.48550/arxiv.physics/0001050,https://arxiv.org/abs/physics/0001050,Statistical mechanics of neocortical interacti...,"Ingber, Lester",2000-01-23,2000,datacite::10.48550/arxiv.physics/0001050,10.48550/arxiv.physics/0001050,arXiv (1),1,2000-01-23,2000-01-23,arXiv

# CoP

In [32]:
CoP_df, CoP_summary = get_server_data("CoP")

==================================================
 SERVER ANALYSIS: COP
==================================================
  > Files found:    1
  > Raw records:    30
  > Cleaned shape:  (30, 90)
  > Unique DOIs:    30
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31219/osf    30
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    30
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31219    30
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    30
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    30
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    30
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    30
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
CoP    30
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    30
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    30
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    30
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR COP
==================================================

In [33]:
CoP_parent_df, CoP_parent_summary = analyze_parent_data("CoP", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: COP
=================================================================
  > Total Parent Groups:     29
  > Total Versions Found:    30
  > Unique Parent DOIs:      29
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for CoP:
-----------------------------------
  1 version(s):     28 groups
  2 version(s):     1 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
CoP    29

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31219/osf    29



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    29


=================================================================
 COMPLETED: COP
=================================================================

# Covid-19 Preprints

In [34]:
Covid_df, Covid_summary = get_server_data("Covid-19_Preprints")

==================================================
 SERVER ANALYSIS: COVID-19_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    647
  > Cleaned shape:  (647, 90)
  > Unique DOIs:    647
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.21055/preprints-    647
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
covid19-preprints.microbe.ru    647
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.21055    647
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
8634    647
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Russian Research Anti-Plague Institute Microbe    647
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    647
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    647
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Еженедельные обзоры    470
Эпидемиология           94
Клиника и лечение       42
Диагностика             29
Профилактика            10
Обзоры                   2
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    647
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    647
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    647
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR COVID-19_PREPRINTS
==================================================

In [35]:
Covid_parent_df, Covid_parent_summary = analyze_parent_data("Covid-19 Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: COVID-19 PREPRINTS
=================================================================
  > Total Parent Groups:     293
  > Total Versions Found:    647
  > Unique Parent DOIs:      293
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Covid-19 Preprints:
-----------------------------------
  1 version(s):     262 groups
  2 version(s):     14 groups
  3 version(s):     2 groups
  4 version(s):     5 groups
  5 version(s):     1 groups
  6 version(s):     1 groups
  8 version(s):     1 groups
  9 version(s):     1 groups
  16 version(s):    1 groups
  21 version(s):    1 groups
  24 version(s):    1 groups
  33 version(s):    1 groups
  73 version(s):    1 groups
  136 version(s):   1 groups

  Average versions per parent: 2.21

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Covid-19 Preprints    292
PREPRINTS.RU            1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.21055/preprints-    293



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
covid19-preprints.microbe.ru    293


=================================================================
 COMPLETED: COVID-19 PREPRINTS
=================================================================

# CrimRxiv

In [36]:
CrimRxiv_df, CrimRxiv_summary = get_server_data("CrimRxiv")

==================================================
 SERVER ANALYSIS: CRIMRXIV
==================================================
  > Files found:    1
  > Raw records:    2838
  > Cleaned shape:  (2838, 90)
  > Unique DOIs:    2838
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.21428/cb          2827
10.21428/51bae76e      11
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
crimrxiv.com           2806
crimrxiv.pubpub.org      21
oqc.crimrxiv.com         11
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.21428    2838
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
9621    2838
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
PubPub    2838
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
CrimRxiv                        2678
None                             148
Open Qualitative Criminology      10
Criminology's Public Domain        2
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    2838
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    2838
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2838
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    2688
posted-content      140
peer-review           6
book-chapter          2
journal               1
component             1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None        2698
preprint     140
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR CRIMRXIV
==================================================

In [37]:
CrimRxiv_parent_df, CrimRxiv_parent_summary = analyze_parent_data("CrimRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: CRIMRXIV
=================================================================
  > Total Parent Groups:     2,570
  > Total Versions Found:    2,713
  > Unique Parent DOIs:      2,570
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for CrimRxiv:
-----------------------------------
  1 version(s):     2,443 groups
  2 version(s):     115 groups
  3 version(s):     10 groups
  4 version(s):     1 groups
  6 version(s):     1 groups

  Average versions per parent: 1.06

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
CrimRxiv                  2541
CrimRxiv; SocArXiv           8
CrimRxiv; arXiv              5
SSRN                         4
SocArXiv                     4
arXiv                        2
Open Science Framework       2
Research Square              2
CrimRxiv; ResearchGate       1
PsyArXiv                     1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.21428/cb          2566
10.21428/51bae76e       4



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
crimrxiv.com           2548
crimrxiv.pubpub.org      18
oqc.crimrxiv.com          4


=================================================================
 COMPLETED: CRIMRXIV
=================================================================

In [38]:
CrimRxiv_df[CrimRxiv_df['type_backend_raw']=='component']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
1707,crossref::10.21428/cb6ab371.b8929691/7cc1f2de,CrimRxiv,crossref,10.21428/cb6ab371.b8929691/7cc1f2de,10.21428/cb6ab371.b8929691/7cc1f2de,https://doi.org/10.21428/cb6ab371.b8929691/7cc...,https://www.crimrxiv.com/pub/pag3wtd8,https://www.crimrxiv.com/pub/pag3wtd8,10.21428,9621,None,None,crossref,PubPub,None,None,None,None,Open access to journal articles of the America...,None,None,None,None,component,None,component,None,False,2023-10-31,None,2023-10-31,2025-11-23,None,2023-10-31,None,2023-10-31,None,2023.0,issued_date,None,None,None,None,None,None,None,None,None,"Jacques, Scott",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-2089-4...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.b8929691/7cc1f2de"",...",10.21428/cb6ab371.b8929691/7cc1f2de,10.21428,10.21428,cb6ab371.b8929691/7cc1f2de,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub

In [39]:
CrimRxiv_df[CrimRxiv_df['type_backend_raw']=='book-chapter']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
2162,crossref::10.21428/cb6ab371.a4e2c432,CrimRxiv,crossref,10.21428/cb6ab371.a4e2c432,10.21428/cb6ab371.a4e2c432,https://doi.org/10.21428/cb6ab371.a4e2c432,https://www.crimrxiv.com/pub/g5531dv0,https://www.crimrxiv.com/pub/g5531dv0,10.21428,9621,None,None,crossref,PubPub,Criminology's Public Domain,None,None,None,Community Organization and Juvenile Delinquenc...,None,None,None,None,book-chapter,None,book-chapter,None,False,2024-11-03,None,2024-11-03,2024-11-03,None,2024-11-03,None,2024-11-03,2024-11-03,2024.0,issued_date,None,None,None,None,None,None,None,None,None,"Park, Robert E.",None,None,"[{""affiliation"": [], ""family"": ""Park"", ""given""...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.a4e2c432"", ""URL"": ""...",10.21428/cb6ab371.a4e2c432,10.21428,10.21428,cb6ab371.a4e2c432,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
2271,crossref::10.21428/cb6ab371.a03e79ee,CrimRxiv,crossref,10.21428/cb6ab371.a03e79ee,10.21428/cb6ab371.a03e79ee,https://doi.org/10.21428/cb6ab371.a03e79ee,https://www.crimrxiv.com/pub/1k60zvag,https://www.crimrxiv.com/pub/1k60zvag,10.21428,9621,None,None,crossref,PubPub,Criminology's Public Domain,None,None,None,An Essay [Excerpt] on Crimes and Punishments,None,None,None,None,book-chapter,None,book-chapter,None,False,2025-01-08,None,2025-01-08,2025-01-09,None,2025-01-08,None,2025-01-08,2025-01-08,2025.0,issued_date,None,None,None,None,None,None,None,None,None,"Beccaria, Cesare",None,None,"[{""affiliation"": [], ""family"": ""Beccaria"", ""gi...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.a03e79ee"", ""URL"": ""...",10.21428/cb6ab371.a03e79ee,10.21428,10.21428,cb6ab371.a03e79ee,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub

In [40]:
CrimRxiv_df[CrimRxiv_df['type_backend_raw']=='peer-review']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
1014,crossref::10.21428/cb6ab371.33c9e126,CrimRxiv,crossref,10.21428/cb6ab371.33c9e126,10.21428/cb6ab371.33c9e126,https://doi.org/10.21428/cb6ab371.33c9e126,https://www.crimrxiv.com/pub/s4okkv64,https://www.crimrxiv.com/pub/s4okkv64,10.21428,9621,None,None,crossref,PubPub,None,None,None,None,"Review 1 of ""Treating Criminal Justice-Involve...",None,None,None,None,peer-review,None,peer-review,None,False,2022-05-24,None,2022-05-24,2024-03-03,None,2022-05-24,None,2022-05-24,None,2022.0,issued_date,None,None,None,None,None,None,None,None,None,"Windle, James",None,None,"[{""affiliation"": [], ""family"": ""Windle"", ""give...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-review-of"": [{""asserted-by"": ""subject"", ""...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.33c9e126"", ""URL"": ""...",10.21428/cb6ab371.33c9e126,10.21428,10.21428,cb6ab371.33c9e126,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
1015,crossref::10.21428/cb6ab371.c4d02d0a,CrimRxiv,crossref,10.21428/cb6ab371.c4d02d0a,10.21428/cb6ab371.c4d02d0a,https://doi.org/10.21428/cb6ab371.c4d02d0a,https://www.crimrxiv.com/pub/frlqbegb,https://www.crimrxiv.com/pub/frlqbegb,10.21428,9621,None,None,crossref,PubPub,None,None,None,None,"Review 2 of ""Doing death work: A mixed method ...",None,None,None,None,peer-review,None,peer-review,None,False,2022-05-24,None,2022-05-24,2024-03-03,None,2022-05-24,None,2022-05-24,None,2022.0,issued_date,None,None,None,None,None,None,None,None,None,"Brondolo, Elizabeth",None,None,"[{""affiliation"": [], ""family"": ""Brondolo"", ""gi...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-review-of"": [{""asserted-by"": ""subject"", ""...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.c4d02d0a"", ""URL"": ""...",10.21428/cb6ab371.c4d02d0a,10.21428,10.21428,cb6ab371.c4d02d0a,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
1321,crossref::10.21428/cb6ab371.f514a7ba,CrimRxiv,crossref,10.21428/cb6ab371.f514a7ba,10.21428/cb6ab371.f514a7ba,https://doi.org/10.21428/cb6ab371.f514a7ba,https://www.crimrxiv.com/pub/19r39l3l,https://www.crimrxiv.com/pub/19r39l3l,10.21428,9621,None,None,crossref,PubPub,None,None,None,None,"Review of ""Ranking the openness of criminology...",None,None,None,None,peer-review,None,peer-review,None,False,2022-10-06,None,2022-10-06,2025-05-14,None,2022-10-06,None,2022-10-06,None,2022.0,issued_date,None,None,None,None,None,None,None,None,None,"Wheeler, Andrew",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-2255-1...",None,None,None,None,None,None,None,None,1,None,None,1,0,None,"{""is-review-of"": [{""asserted-by"": ""subject"", ""...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.f514a7ba"", ""URL"": ""...",10.21428/cb6ab371.f514a7ba,10.21428,10.21428,cb6ab371.f514a7ba,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
1330,crossref::10.21428/cb6ab371.e2488a45,CrimRxiv,crossref,10.21428/cb6ab371.e2488a45,10.21428/cb6ab371.e2488a45,https://doi.org/10.21428/cb6ab371.e2488a45,https://www.crimrxiv.com/pub/iumal68d,https://www.crimrxiv.com/pub/iumal68d,10.21428,9621,None,None,crossref,PubPub,None,None,None,None,"Review of ""Ranking the openness of criminology...",None,None,None,None,peer-review,None,peer-review,None,False,2022-10-10,None,2022-10-10,2025-05-14,None,2022-10-10,None,2022-10-10,None,2022.0,issued_date,None,None,None,None,None,None,None,None,None,"Burt, Callie",None,None,"[{""ORCID"": ""https://orcid.org/0000-0001-7191-9...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-review-of"": [{""asserted-by"": ""subject"", ""...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.e2488a45"", ""URL"": ""...",10.21428/cb6ab371.e2488a45,10.21428,10.21428,cb6ab371.e2488a45,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
2255,crossref::10.21428/cb6ab371.e42226cb,CrimRxiv,crossref,10.21428/cb6ab371.e42226cb,10.21428/cb6ab371.e42226cb,https://doi.org/10.21428/cb6ab371.e42226cb,https://www.crimrxiv.com/pub/8qb8nsfj,https://www.crimrxiv.com/pub/8qb8nsfj,10.21428,9621,None,None,crossref,PubPub,None,None,None,None,"Review of ""A plea for open access to qualitati...",None,None,None,None,peer-review,None,peer-review,None,False,2024-12-18,None,2024-12-27,2024-12-27,None,2024-12-18,None,2024-12-18,None,2024.0,issued_date,None,None,None,None,None,None,None,None,None,"Dickinson, Timothy",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3076-0...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-review-of"": [{""asserted-by"": ""subject"", ""...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.e42226cb"", ""URL"": ""...",10.21428/cb6ab371.e42226cb,10.21428,10.21428,cb6ab371.e42226cb,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
2260,crossref::10.21428/cb6ab371.2b7a7a53,CrimRxiv,crossref,10.21428/cb6ab371.2b7a7a53,10.21428/cb6ab371.2b7a7a53,https://doi.org/10.21428/cb6ab371.2b7a7a53,https://www.crimrxiv.com/pub/zkdkie05,https://www.crimrxiv.com/pub/zkdkie05,10.21428,9621,None,None,crossref,PubPub,None,None,None,None,"Review of ""Relative Openness in Peer Review: C...",None,None,None,None,peer-review,None,peer-review,None,False,2025-01-01,None,2025-01-01,2025-01-01,None,2025-01-01,None,2025-01-01,None,2025.0,issued_date,None,None,None,None,None,None,None,None,None,"Jacques, Scott",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-2089-4...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-review-of"": [{""asserted-by"": ""subject"", ""...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.2b7a7a53"", ""URL"": ""...",10.21428/cb6ab371.2b7a7a53,10.21428,10.21428,cb6ab371.2b7a7a53,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub

In [41]:
CrimRxiv_df[CrimRxiv_df['type_backend_raw']=='journal-article']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.21428/cb6ab371.30868967,CrimRxiv,crossref,10.21428/cb6ab371.30868967,10.21428/cb6ab371.30868967,https://doi.org/10.21428/cb6ab371.30868967,https://crimrxiv.pubpub.org/pub/tn1vo8l2,https://crimrxiv.pubpub.org/pub/tn1vo8l2,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,"Bentham, Not Epicurus: The Relevance of Pleasu...",None,None,None,en,journal-article,None,journal-article,None,False,2020-07-07,None,2020-07-07,2025-11-23,None,2020-07-07,None,2020-07-07,2020-07-07,2020.0,issued_date,None,None,None,None,None,None,None,None,None,"Jacques, Scott",Georgia State University,None,"[{""affiliation"": [{""name"": ""Georgia State Univ...",None,None,None,None,None,None,None,None,1,None,None,1,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.30868967"", ""URL"": ""...",10.21428/cb6ab371.30868967,10.21428,10.21428,cb6ab371.30868967,10.21428/cb,10.21428/cb,crimrxiv.pubpub.org,crimrxiv.pubpub.org/pub
1,crossref::10.21428/cb6ab371.aab5ffbe,CrimRxiv,crossref,10.21428/cb6ab371.aab5ffbe,10.21428/cb6ab371.aab5ffbe,https://doi.org/10.21428/cb6ab371.aab5ffbe,https://crimrxiv.pubpub.org/pub/oxbqg1op,https://crimrxiv.pubpub.org/pub/oxbqg1op,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,Proterrence &amp; Rule Illegitimacy in an Age ...,None,None,None,en,journal-article,None,journal-article,None,False,2020-07-07,None,2020-07-07,2022-04-05,None,2020-07-07,None,2020-07-07,2020-07-07,2020.0,issued_date,None,None,None,None,None,None,None,None,None,"Jacobs, Bruce; Jacques, Scott","University of Texas, Dallas; Georgia State Uni...",None,"[{""affiliation"": [{""name"": ""University of Texa...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.aab5ffbe"", ""URL"": ""...",10.21428/cb6ab371.aab5ffbe,10.21428,10.21428,cb6ab371.aab5ffbe,10.21428/cb,10.21428/cb,crimrxiv.pubpub.org,crimrxiv.pubpub.org/pub
2,crossref::10.21428/cb6ab371.9e0bdd09,CrimRxiv,crossref,10.21428/cb6ab371.9e0bdd09,10.21428/cb6ab371.9e0bdd09,https://doi.org/10.21428/cb6ab371.9e0bdd09,https://crimrxiv.pubpub.org/pub/zk9k26ba,https://crimrxiv.pubpub.org/pub/zk9k26ba,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,La cybercriminalité,None,None,None,en,journal-article,None,journal-article,None,False,2020-07-08,None,2020-07-08,2023-08-16,None,2020-07-08,None,2020-07-08,2020-07-08,2020.0,issued_date,None,None,None,None,None,None,None,None,None,"Décary-Hétu, David",None,None,"[{""affiliation"": [], ""family"": ""Décary-Hétu"", ...",None,None,None,None,None,None,None,None,1,None,None,1,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.9e0bdd09"", ""URL"": ""...",10.21428/cb6ab371.9e0bdd09,10.21428,10.21428,cb6ab371.9e0bdd09,10.21428/cb,10.21428/cb,crimrxiv.pubpub.org,crimrxiv.pubpub.org/pub
3,crossref::10.21428/cb6ab371.0bcce0c6,CrimRxiv,crossref,10.21428/cb6ab371.0bcce0c6,10.21428/cb6ab371.0bcce0c6,https://doi.org/10.21428/cb6ab371.0bcce0c6,https://crimrxiv.pubpub.org/pub/gf7zjbgf,https://crimrxiv.pubpub.org/pub/gf7zjbgf,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,Les sites de réseautage social et la présence ...,None,None,None,en,journal-article,None,journal-article,None,False,2020-07-08,None,2020-07-08,2022-04-05,None,2020-07-08,None,2020-07-08,2020-07-08,2020.0,issued_date,None,None,None,None,None,None,None,None,None,"Morselli, Carlo; Décary-Hétu, David",Université de Montréal,None,"[{""affiliation"": [{""name"": ""Université de Mont...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.0bcce0c6"", ""URL"": ""...",10.21428/cb6ab371.0bcce0c6,10.21428,10.21428,cb6ab371.0bcce0c6,10.21428/cb,10.21428/cb,crimrxiv.pubpub.org,crimrxiv.pubpub.org/pub
4,crossref::10.21428/cb6ab371.dc975be1,CrimRxiv,crossref,10.21428/cb6ab371.dc975be1,10.21428/cb6ab371.dc975be1,https://doi.org/10.21428/cb6ab371.dc975be1,https://crimrxiv.pubpub.org/pub/howtosubmityou...,https://crimrxiv.pubpub.org/pub/howtosubmityou...,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,How to Submit Your Paper,None,None,None,en,journal-article,None,journal-article,None,False,2020-07-10,None,2020-07-10,2022-04-05,None,2020-07-07,None,2020-07-07,2020-07-07,2020.0,issued_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.dc975be1"", ""URL"": ""...",10.21428/cb6ab371.dc975be1,10.21428,10.21428,cb6ab371.dc975be1,10.21428/cb,10.21428/cb,crimrxiv.pubpub.org,crimrxiv.pubpub.org/pub
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2832,crossref::10.21428/cb6ab371.51518bc8,CrimRxiv,crossref,10.21428/cb6ab371.51518bc8,10.21428/cb6ab371.51518bc8,https://doi.org/10.21428/cb6ab371.51518bc8,https://www.crimrxiv.com/pub/uaij3zjq,https://www.crimrxiv.com/pub/uaij3zjq,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,Big data policing door de ogen van politie: at...,None,None,None,en,journal-article,None,journal-article,None,False,2025-12-22,None,2025-12-22,2025-12-22,None,2025-12-22,None,2025-12-22,2025-12-22,2025.0,issued_date,None,None,None,None,None,None,None,None,None,"Hardyns, Wim; Khalfa, Robin",None,None,"[{""affiliation"": [], ""family"": ""Hardyns"", ""giv...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.51518bc8"", ""URL"": ""...",10.21428/cb6ab371.51518bc8,10.21428,10.21428,cb6ab371.51518bc8,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
2833,crossref::10.21428/cb6ab371.3f3662dd,CrimRxiv,crossref,10.21428/cb6ab371.3f3662dd,10.21428/cb6ab371.3f3662dd,https://doi.org/10.21428/cb6ab371.3f3662dd,https://www.crimrxiv.com/pub/54fdjjba,https://www.crimrxiv.com/pub/54fdjjba,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,"Justice: word, idea, practice",None,None,None,en,journal-article,None,journal-article,None,False,2025-12-22,None,2025-12-22,2025-12-22,None,2025-12-22,None,2025-12-22,2025-12-22,2025.0,issued_date,None,None,None,None,None,None,None,None,None,"Daly, Kathleen",None,None,"[{""affiliation"": [], ""family"": ""Daly"", ""given""...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,10.1111/1745-9125.70009,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.3f3662dd"", ""URL"": ""...",10.21428/cb6ab371.3f3662dd,10.21428,10.21428,cb6ab371.3f3662dd,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
2834,crossref::10.21428/cb6ab371.3e945a84,CrimRxiv,crossref,10.21428/cb6ab371.3e945a84,10.21428/cb6ab371.3e945a84,https://doi.org/10.21428/cb6ab371.3e945a84,https://www.crimrxiv.com/pub/tgjhzd1p,https://www.crimrxiv.com/pub/tgjhzd1p,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,The dynamics of criminal collaboration: Multip...,None,None,None,en,journal-article,None,journal-article,None,False,2025-12-22,None,2025-12-22,2025-12-22,None,2025-12-22,None,2025-12-22,2025-12-22,2025.0,issued_date,None,None,None,None,None,None,None,None,None,"Calderoni, Francesco; Lerner, Jürgen; Bright, ...",None,None,"[{""affiliation"": [], ""family"": ""Calderoni"", ""g...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,"{""is-version-of"": [{""asserted-by"": ""subject"", ...",,,False,None,10.1111/1745-9125.70026,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.3e945a84"", ""URL"": ""...",10.21428/cb6ab371.3e945a84,10.21428,10.21428,cb6ab371.3e945a84,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
2836,crossref::10.21428/cb6ab371.34cabd65,CrimRxiv,crossref,10.21428/cb6ab371.34cabd65,10.21428/cb6ab371.34cabd65,https://doi.org/10.21428/cb6ab371.34cabd65,https://www.crimrxiv.com/pub/558c41sk,https://www.crimrxiv.com/pub/558c41sk,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,"Less Law, More Justice: Rethinking Sentencing ...",None,None,None,en,journal-article,None,journal-article,None,False,2025-12-29,None,2025-12-29,2025-12-29,None,2025-12-29,None,2025-12-29,2025-12-29,2025.0,issued_date,None,None,None,None,None,None,None,None,None,"Love, Helene; Wiley, Stephanie",None,None,"[{""affiliation"": [], ""family"": ""Love"", ""given""...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.34cabd65"", ""URL"": ""...",10.21428/cb6ab371.34cabd65,10.21428,10.21428,cb6ab371.34cabd65,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub
2837,crossref::10.21428/cb6ab371.12735513,CrimRxiv,crossref,10.21428/cb6ab371.12735513,10.21428/cb6ab371.12735513,https://doi.org/10.21428/cb6ab371.12735513,https://www.crimrxiv.com/pub/lknnd7xd,https://www.crimrxiv.com/pub/lknnd7xd,10.21428,9621,None,None,crossref,PubPub,CrimRxiv,None,None,None,Police Officers With Supplemental Martial Arts...,None,None,None,en,journal-article,None,journal-article,None,False,2025-12-31,None,2025-12-31,2025-12-31,None,2025-12-31,None,2025-12-31,2025-12-31,2025.0,issued_date,None,None,None,None,None,None,None,None,None,"Del-Colle, Henrique Adam; Eleuterio-da-Rocha, Joe","Guatupê Military Police Academy, Military Poli...",None,"[{""affiliation"": [{""name"": ""Guatupê Military P...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,25,None,"{""DOI"": ""10.21428/cb6ab371.12735513"", ""URL"": ""...",10.21428/cb6ab371.12735513,10.21428,10.21428,cb6ab371.12735513,10.21428/cb,10.21428/cb,crimrxiv.com,crimrxiv.com/pub

# CrossAsia-Repository

In [42]:
CrossAsia_df, CrossAsia_summary = get_server_data("CrossAsia-Repository")

==================================================
 SERVER ANALYSIS: CROSSASIA-REPOSITORY
==================================================
  > Files found:    2
  > Raw records:    479
  > Cleaned shape:  (479, 90)
  > Unique DOIs:    479
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.48796/20    479
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
repository.crossasia.org    479
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.48796    479
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    479
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Fachinformationsdienst (FID) Asien                                                             428
CrossAsia-eBooks                                                                                21
Iudicium                                                                                        10
Vereinigung für sozialwissenschaftliche Japanforschung                                           7
Alliance for Research on East Asia (AREA) Ruhr                                                   5
CrossAsia Open Access Repository                                                                 3
Japanime Co. Ltd.                                                                                1
CrossAsia E-Publishing                                                                           1
Universität Leipzig, Ostasiatisches Institut Japanologie / CrossAsia Open Access Repository      1
Staatsbibliothek zu Berlin - Preußischer Kulturbesitz                                            1
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    479
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    479
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    479
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    479
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Text    479
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
article         225
blog_entry      154
chapter          42
collection       40
dissertation      5
poster            5
book              3
series            2
proceedings       1
speech            1
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR CROSSASIA-REPOSITORY
==================================================

In [43]:
CrossAsia_parent_df, CrossAsia_parent_summary = analyze_parent_data("CrossAsia-Repository", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: CROSSASIA-REPOSITORY
=================================================================
  > Total Parent Groups:     459
  > Total Versions Found:    479
  > Unique Parent DOIs:      459
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for CrossAsia-Repository:
-----------------------------------
  1 version(s):     455 groups
  2 version(s):     2 groups
  4 version(s):     1 groups
  16 version(s):    1 groups

  Average versions per parent: 1.04

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
CrossAsia-Repository    459

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.48796/20    459



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
repository.crossasia.org    459


=================================================================
 COMPLETED: CROSSASIA-REPOSITORY
=================================================================

In [44]:
CrossAsia_df[CrossAsia_df['subtype_backend_raw']=='blog_entry']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
40,datacite::10.48796/20240116-000,CrossAsia-Repository,datacite,10.48796/20240116-000,10.48796/20240116-000,https://doi.org/10.48796/20240116-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Im Banne Chinas: Der Sinologe Wolfgang Franke ...,None,None,None,de,Text,blog_entry,Text,None,None,2024-01-18,None,None,None,2025-02-17,None,2024-01-18,None,None,2024,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Der Sinologe und Historiker ...",Der Sinologe und Historiker Wolfgang Franke (*...,None,None,"Messingschlager, Stefan; Platzek, Antje",None,None,"[{""affiliation"": [], ""familyName"": ""Messingsch...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Franke, Wolfgang""}, {""subject"": ...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20240116-000,10.48796,10.48796,20240116-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
42,datacite::10.48796/20240326-000,CrossAsia-Repository,datacite,10.48796/20240326-000,10.48796/20240326-000,https://doi.org/10.48796/20240326-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Grundlagen und Konzept zur Erwerbung und Lizen...,None,None,None,de,Text,blog_entry,Text,None,None,2024-03-26,None,None,None,2025-02-17,None,2024-03-26,None,None,2024,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Die Staatsbibliothek zu Berl...",Die Staatsbibliothek zu Berlin (SBB) betreut s...,None,None,FID Asien,None,None,"[{""affiliation"": [], ""familyName"": ""FID Asien""...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Fachinformationsdienst""}, {""subj...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {}, ""content...",10.48796/20240326-000,10.48796,10.48796,20240326-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
247,datacite::10.48796/20240722-000,CrossAsia-Repository,datacite,10.48796/20240722-000,10.48796/20240722-000,https://doi.org/10.48796/20240722-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Launching a fieldwork-based project about rura...,None,None,None,en,Text,blog_entry,Text,None,None,2024-08-15,None,None,None,2024-08-16,None,2024-08-15,None,None,2021,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Reiher, Cornelia",None,None,"[{""affiliation"": [], ""familyName"": ""Reiher"", ""...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""Covid-19""}...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20240722-000,10.48796,10.48796,20240722-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
248,datacite::10.48796/20240806-001,CrossAsia-Repository,datacite,10.48796/20240806-001,10.48796/20240806-001,https://doi.org/10.48796/20240806-001,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Covid-19 and an immobile project on mobility,None,None,None,en,Text,blog_entry,Text,None,None,2024-08-15,None,None,None,2024-08-16,None,2024-08-15,None,None,2021,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Ngo, Tu",None,None,"[{""affiliation"": [], ""familyName"": ""Ngo"", ""giv...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""rural Japa...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20240806-001,10.48796,10.48796,20240806-001,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
249,datacite::10.48796/20240806-002,CrossAsia-Repository,datacite,10.48796/20240806-002,10.48796/20240806-002,https://doi.org/10.48796/20240806-002,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Rethinking fieldwork in urban-rural migration ...,None,None,None,en,Text,blog_entry,Text,None,None,2024-08-15,None,None,None,2024-08-16,None,2024-08-15,None,None,2021,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Durand, Maritchu",None,None,"[{""affiliation"": [], ""familyName"": ""Durand"", ""...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""rural Japa...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20240806-002,10.48796,10.48796,20240806-002,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,datacite::10.48796/20250222-000,CrossAsia-Repository,datacite,10.48796/20250222-000,10.48796/20250222-000,https://doi.org/10.48796/20250222-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Everyday mobilities of urban-rural migrants be...,None,None,None,en,Text,blog_entry,Text,None,None,2025-09-30,None,None,None,2025-09-30,None,2025-09-30,None,None,2025,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Reiher, Cornelia",None,None,"[{""affiliation"": [], ""familyName"": ""Reiher"", ""...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""rural Japa...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20250222-000,10.48796,10.48796,20250222-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
461,datacite::10.48796/20250308-000,CrossAsia-Repository,datacite,10.48796/20250308-000,10.48796/20250308-000,https://doi.org/10.48796/20250308-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Guest Contribution: Back to school in Otoyo: A...,None,None,None,en,Text,blog_entry,Text,None,None,2025-09-30,None,None,None,2025-09-30,None,2025-09-30,None,None,2025,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Olsson, Julia",None,None,"[{""affiliation"": [], ""familyName"": ""Olsson"", ""...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""rural Japa...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20250308-000,10.48796,10.48796,20250308-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
462,datacite::10.48796/20250322-000,CrossAsia-Repository,datacite,10.48796/20250322-000,10.48796/20250322-000,https://doi.org/10.48796/20250322-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Guest Contribution: How to get more toilets on...,None,None,None,en,Text,blog_entry,Text,None,None,2025-09-30,None,None,None,2025-09-30,None,2025-09-30,None,None,2025,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Goto-Spletzer, Signy",None,None,"[{""affiliation"": [], ""familyName"": ""Goto-Splet...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""rural Japa...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20250322-000,10.48796,10.48796,20250322-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
463,datacite::10.48796/20250405-000,CrossAsia-Repository,datacite,10.48796/20250405-000,10.48796/20250405-000,https://doi.org/10.48796/20250405-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,No homes for newcomers?: Vacant houses and the...,None,None,None,en,Text,blog_entry,Text,None,None,2025-09-30,None,None,None,2025-09-30,None,2025-09-30,None,None,2025,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Reiher, Cornelia",None,None,"[{""affiliation"": [], ""familyName"": ""Reiher"", ""...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""rural Japa...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20250405-000,10.48796,10.48796,20250405-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive
464,datacite::10.48796/20250503-000,CrossAsia-Repository,datacite,10.48796/20250503-000,10.48796/20250503-000,https://doi.org/10.48796/20250503-000,https://repository.crossasia.org/receive/cross...,https://repository.crossasia.org/receive/cross...,10.48796,None,shkl.lofhsj,shkl,datacite,Fachinformationsdienst (FID) Asien,None,None,None,None,Guest Contribution: Collaborative community pl...,None,None,None,en,Text,blog_entry,Text,None,None,2025-09-30,None,None,None,2025-09-30,None,2025-09-30,None,None,2025,published_year,None,None,None,CrossAsia Open Access Repository-Lizenz,https://repository.crossasia.org/content/right...,"[{""description"": ""Urban-rural migration and ru...",Urban-rural migration and rural revitalization...,None,None,"Bartzsch, Arne",None,None,"[{""affiliation"": [], ""familyName"": ""Bartzsch"",...","[{""affiliation"": [], ""contributorType"": ""Hosti...",None,[],None,None,"[{""subject"": ""Japan""}, {""subject"": ""rural Japa...",None,None,0,0,None,None,0,None,"[{""relatedIdentifier"": ""https://repository.cro...",,,False,None,,None,None,,None,None,None,client_id,3,"{""client"": {""data"": {""id"": ""shkl.lofhsj"", ""typ...","{""citationCount"": 0, ""container"": {""identifier...",10.48796/20250503-000,10.48796,10.48796,20250503-000,10.48796/20,10.48796/20,repository.crossasia.org,repository.crossasia.org/receive

# Digital Access to Scholarship at Harvard (DASH) (Harvard University)

In [45]:
DASH_df, DASH_summary = get_server_data("Digital_Access_to_Scholarship_at_Harvard_(DASH)_(H")

==================================================
 SERVER ANALYSIS: DIGITAL_ACCESS_TO_SCHOLARSHIP_AT_HARVARD_(DASH)_(H
==================================================
  > Files found:    1
  > Raw records:    9703
  > Cleaned shape:  (9703, 90)
  > Unique DOIs:    154
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>              9549
10.48550/arxiv      65
10.53901/tjbs        4
10.7916/d            4
10.15779/z           3
10.1901/jaba         2
10.1257/aer          2
10.1186/14           2
10.13140/rg          2
10.7448/ias          2
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
nrs.harvard.edu               8768
dash.harvard.edu               918
harvardlibrarybulletin.org       6
dissertations.umi.com            4
doi.org                          1
globalasia.org                   1
frstrategie.org                  1
iase-web.org                     1
ipres2023.us                     1
historytoday.com                 1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        9549
10.48550      65
10.1038        5
10.7916        5
10.17615       4
10.53901       4
10.2312        4
10.1093        3
10.15779       3
10.2307        3
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    9703
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    9703
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    9703
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    9703
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    9703
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    9703
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article     9190
preprint     513
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    9703
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR DIGITAL_ACCESS_TO_SCHOLARSHIP_AT_HARVARD_(DASH)_(H
==================================================

In [46]:
DASH_parent_df, DASH_parent_summary = analyze_parent_data("Digital Access to Scholarship at Harvard (DASH) (Harvard University)", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: DIGITAL ACCESS TO SCHOLARSHIP AT HARVARD (DASH) (HARVARD UNIVERSITY)
=================================================================
  > Total Parent Groups:     9,383
  > Total Versions Found:    9,554
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Digital Access to Scholarship at Harvard (DASH) (Harvard University):
-----------------------------------
  1 version(s):     9,224 groups
  2 version(s):     150 groups
  3 version(s):     6 groups
  4 version(s):     3 groups

  Average versions per parent: 1.02

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Digital Access to Scholarship at Harvard (DASH) (Harvard University)                                         9235
SSRN                                                                                                          117
arXiv                                                                                                          10
RePEc: Research Papers in Economics                                                                             7
Digital Access to Scholarship at Harvard (DASH) (Harvard University); RePEc: Research Papers in Economics       6
EconStor Preprints                                                                                              2
Humanities Commons CORE                                                                                         1
Open Science Framework                                                                                          1
Law Archive                                                                                                     1
Research Square                                                                                                 1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    9383



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
nrs.harvard.edu                8451
dash.harvard.edu                916
harvardlibrarybulletin.org        6
dissertations.umi.com             4
ipres2023.us                      1
historytoday.com                  1
frstrategie.org                   1
globalasia.org                    1
elischolar.library.yale.edu       1
iase-web.org                      1


=================================================================
 COMPLETED: DIGITAL ACCESS TO SCHOLARSHIP AT HARVARD (DASH) (HARVARD UNIVERSITY)
=================================================================

# DSpace@MIT

In [47]:
DSpace_df, DSpace_summary = get_server_data("DSpace@MIT")

==================================================
 SERVER ANALYSIS: DSPACE@MIT
==================================================
  > Files found:    1
  > Raw records:    12661
  > Cleaned shape:  (12661, 90)
  > Unique DOIs:    1308
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>               11353
10.48550/arxiv      1081
10.6084/m             17
10.3929/ethz-b-       16
10.17863/cam          13
10.5281/zenodo        12
10.1021/ja            10
10.13140/rg            8
10.1007/jhep           6
10.13016/m             6
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
hdl.handle.net                 12479
dspace.mit.edu                   117
mit.edu                           29
globalchange.mit.edu              20
orcid.org                          7
None                               3
jstor.org                          1
aclanthology.org                   1
arxiv.org                          1
convention2.allacademic.com        1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        11353
10.48550     1081
10.1021        44
10.3929        17
10.6084        17
10.17863       13
10.5281        12
10.13140       10
10.1007         7
10.17615        7
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    12661
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    12661
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    12661
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    12661
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    12661
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    12661
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article     12348
preprint      313
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    12661
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR DSPACE@MIT
==================================================

In [48]:
DSpace_parent_df, DSpace_parent_summary = analyze_parent_data("DSpace@MIT", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: DSPACE@MIT
=================================================================
  > Total Parent Groups:     10,420
  > Total Versions Found:    10,686
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for DSpace@MIT:
-----------------------------------
  1 version(s):     10,165 groups
  2 version(s):     244 groups
  3 version(s):     11 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
DSpace@MIT                                                              10244
arXiv                                                                     131
SSRN                                                                       26
RePEc: Research Papers in Economics                                         9
eLife                                                                       2
bioRxiv                                                                     2
DSpace@MIT; RePEc: Research Papers in Economics                             2
ResearchGate                                                                1
Digital Access to Scholarship at Harvard (DASH) (Harvard University)        1
Earth and Space Science Open Archive                                        1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    10420



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
hdl.handle.net                 10285
dspace.mit.edu                   101
globalchange.mit.edu              19
orcid.org                          7
None                               3
convention2.allacademic.com        1
aclanthology.org                   1
openwetware.org                    1
jstor.org                          1
hsdl.org                           1


=================================================================
 COMPLETED: DSPACE@MIT
=================================================================

# E-LIS Repository

In [49]:
E_LIS_df, E_LIS_summary = get_server_data("E-LIS_Repository")

==================================================
 SERVER ANALYSIS: E-LIS_REPOSITORY
==================================================
  > Files found:    1
  > Raw records:    9128
  > Cleaned shape:  (9128, 90)
  > Unique DOIs:    264
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>              8864
10.13140/rg         75
10.5281/zenodo      54
10.13140/2          16
10.11575/prism      16
10.26268/heal       13
10.48550/arxiv      10
10.6084/m            9
10.4403/jlis         7
10.35050/jipm        5
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
None                   8116
eprints.rclis.org       759
doi.org                 232
dialnet.unirioja.es       3
icono14.net               2
elar.urfu.ru              2
jipm.irandoc.ac.ir        2
openaccess.uoc.edu        1
rmlconsultores.com        1
scientificia.com          1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        8864
10.13140      91
10.5281       54
10.11575      16
10.26268      13
10.17613      13
10.48550      10
10.6084        9
10.4403        7
10.1344        6
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    9128
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    9128
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    9128
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    9128
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    9128
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    9128
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article     9077
preprint      51
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    9128
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR E-LIS_REPOSITORY
==================================================

In [50]:
E_LIS_parent_df, E_LIS_parent_summary = analyze_parent_data("E-LIS Repository", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: E-LIS REPOSITORY
=================================================================
  > Total Parent Groups:     8,794
  > Total Versions Found:    8,884
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for E-LIS Repository:
-----------------------------------
  1 version(s):     8,718 groups
  2 version(s):     66 groups
  3 version(s):     6 groups
  4 version(s):     4 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
E-LIS Repository                                           8773
SSRN                                                          6
Humanities Commons CORE                                       4
arXiv                                                         2
E-LIS Repository; Social Science Open Access Repository       2
Open Science Framework                                        1
engrXiv                                                       1
ResearchGate                                                  1
Zenodo                                                        1
SocArXiv                                                      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    8794



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
None                     8049
eprints.rclis.org         727
dialnet.unirioja.es         3
icono14.net                 2
elar.urfu.ru                2
openaccess.uoc.edu          1
hdl.handle.net              1
redc.revistas.csic.es       1
seer.ucp.br                 1
doi.org                     1


=================================================================
 COMPLETED: E-LIS REPOSITORY
=================================================================

# Earth and Space Science Open Archive

In [51]:
Earth_df, Earth_summary = get_server_data("Earth_and_Space_Science_Open_Archive")

==================================================
 SERVER ANALYSIS: EARTH_AND_SPACE_SCIENCE_OPEN_ARCHIVE
==================================================
  > Files found:    1
  > Raw records:    22748
  > Cleaned shape:  (22748, 90)
  > Unique DOIs:    22748
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.1002/essoar     12974
10.22541/essoar     9774
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
essopenarchive.org    22629
authorea.com             73
essoar.org               43
techrxiv.org              3
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.1002     12974
10.22541     9774
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
311    22748
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Wiley    22748
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    22748
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None                                    22091
Authorea, Inc.                            382
Earth and Space Science Open Archive      130
ESS Open Archive                          128
Authorea Inc.                              17
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None                           22089
Preprints                        527
Geophysics                        22
Atmospheric Sciences              17
Climatology (Global Change)       16
Hydrology                         15
Oceanography                      11
Geology                           11
Environmental Sciences             7
Solar System Physics               5
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    22748
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    22748
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    22728
other          20
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR EARTH_AND_SPACE_SCIENCE_OPEN_ARCHIVE
==================================================

In [52]:
Earth_parent_df, Earth_parent_summary = analyze_parent_data("Earth and Space Science Open Archive", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: EARTH AND SPACE SCIENCE OPEN ARCHIVE
=================================================================
  > Total Parent Groups:     19,185
  > Total Versions Found:    22,706
  > Unique Parent DOIs:      19,185
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Earth and Space Science Open Archive:
-----------------------------------
  1 version(s):     16,385 groups
  2 version(s):     2,251 groups
  3 version(s):     431 groups
  4 version(s):     88 groups
  5 version(s):     19 groups
  6 version(s):     7 groups
  7 version(s):     1 groups
  9 version(s):     1 groups
  10 version(s):    1 groups
  11 version(s):    1 groups

  Average versions per parent: 1.18

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Earth and Space Science Open Archive           18854
arXiv                                            105
EGUsphere                                         58
Research Square                                   47
SSRN                                              35
EarthArXiv                                        24
Authorea Inc.                                     16
Earth and Space Science Open Archive; arXiv       10
ResearchGate                                       6
Preprints.org                                      6

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.1002/essoar     10772
10.22541/essoar     8413



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
essopenarchive.org    19118
authorea.com             46
essoar.org               19
techrxiv.org              2


=================================================================
 COMPLETED: EARTH AND SPACE SCIENCE OPEN ARCHIVE
=================================================================

In [53]:
Earth_df[Earth_df['subtype_backend_raw']=='other']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.1002/essoar.10502642.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10502642.1,10.1002/essoar.10502642.1,https://doi.org/10.1002/essoar.10502642.1,http://www.essoar.org/doi/10.1002/essoar.10502...,http://www.essoar.org/doi/10.1002/essoar.10502...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Atmospheric Sciences,None,Ionosphere vertical TEC calculated from GNSS r...,None,None,None,None,posted-content,other,other,None,True,2020-04-07,2020-04-07,2020-04-07,2025-02-21,None,2020-04-07,None,2020-04-07,None,2020,issued_date,posted_date,None,None,None,None,None,None,None,None,"Morozova, Anna; Barlyaeva, Tatiana; Barata, Te...",CITEUC,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8552-8...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10502642.1"", ""URL"": ""h...",10.1002/essoar.10502642.1,10.1002,10.1002,essoar.10502642.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
1,crossref::10.1002/essoar.10503785.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10503785.1,10.1002/essoar.10503785.1,https://doi.org/10.1002/essoar.10503785.1,http://www.essoar.org/doi/10.1002/essoar.10503...,http://www.essoar.org/doi/10.1002/essoar.10503...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Education,None,Looking for technosignatures using the brain \...,None,None,None,None,posted-content,other,other,None,True,2020-07-31,2020-07-31,2020-07-31,2025-05-13,None,2020-07-31,None,2020-07-31,None,2020,issued_date,posted_date,None,None,None,None,None,None,None,None,"De la Torre, Gabriel",University of Cadiz,None,"[{""ORCID"": ""https://orcid.org/0000-0001-8636-5...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10503785.1"", ""URL"": ""h...",10.1002/essoar.10503785.1,10.1002,10.1002,essoar.10503785.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
3,crossref::10.1002/essoar.10504241.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10504241.1,10.1002/essoar.10504241.1,https://doi.org/10.1002/essoar.10504241.1,http://www.essoar.org/doi/10.1002/essoar.10504...,http://www.essoar.org/doi/10.1002/essoar.10504...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Oceanography,None,CMIP6 without the interpolation: Grid-native a...,None,None,None,None,posted-content,other,other,None,True,2020-09-10,2020-09-10,2020-09-10,2025-05-13,None,2020-09-10,None,2020-09-10,None,2020,issued_date,posted_date,None,None,None,None,None,None,None,None,"Busecke, Julius; Abernathey, Ryan",Princeton University; Columbia University,None,"[{""ORCID"": ""https://orcid.org/0000-0001-8571-8...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10504241.1"", ""URL"": ""h...",10.1002/essoar.10504241.1,10.1002,10.1002,essoar.10504241.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
8,crossref::10.1002/essoar.10506197.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10506197.1,10.1002/essoar.10506197.1,https://doi.org/10.1002/essoar.10506197.1,http://www.essoar.org/doi/10.1002/essoar.10506...,http://www.essoar.org/doi/10.1002/essoar.10506...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Geography,None,Urban Green Space and Land Surface Temperature...,None,None,None,None,posted-content,other,other,None,True,2021-02-12,2021-02-12,2021-02-12,2025-05-13,None,2021-02-12,None,2021-02-12,None,2021,issued_date,posted_date,None,None,None,None,None,None,None,None,"Verma, Ravi; Garg, Pradeep Kumar","Department of Civil Engineering, Indian Instit...",None,"[{""ORCID"": ""https://orcid.org/0000-0001-8556-0...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10506197.1"", ""URL"": ""h...",10.1002/essoar.10506197.1,10.1002,10.1002,essoar.10506197.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
10,crossref::10.1002/essoar.10500644.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500644.1,10.1002/essoar.10500644.1,https://doi.org/10.1002/essoar.10500644.1,http://www.essoar.org/doi/10.1002/essoar.10500...,http://www.essoar.org/doi/10.1002/essoar.10500...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Climatology (Global Change),None,The Climate Literacy and Energy Awareness Netw...,None,None,None,None,posted-content,other,other,None,True,2019-11-13,2019-01-21,2021-02-23,2022-04-01,None,2019-01-21,None,2019-01-21,None,2019,issued_date,posted_date,None,None,None,None,None,None,"[{""URL"": ""https://www.essoar.org/pdfjs/10.1002...",None,"Boyd, Kathryn; Gold, Anne; Niepold, Frank; Tay...",Cooperative Institute for Research in Environm...,None,"[{""affiliation"": [{""name"": ""Cooperative Instit...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10500644.1"", ""URL"": ""h...",10.1002/essoar.10500644.1,10.1002,10.1002,essoar.10500644.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
11,crossref::10.1002/essoar.10500599.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500599.1,10.1002/essoar.10500599.1,https://doi.org/10.1002/essoar.10500599.1,http://www.essoar.org/doi/10.1002/essoar.10500...,http://www.essoar.org/doi/10.1002/essoar.10500...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Atmospheric Sciences,None,Velocity of E region SuperDARN echoes and ExB ...,None,None,None,None,posted-content,other,other,None,True,2019-08-28,2019-01-18,2021-02-23,2025-02-21,None,2019-01-18,None,2019-01-18,None,2019,issued_date,posted_date,None,None,None,None,None,None,"[{""URL"": ""https://www.essoar.org/pdfjs/10.1002...",None,"Koustov, Alexandre; Luciuk, Michael; Gillies, Rob",University of Saskatchewan; University of Calgary,None,"[{""ORCID"": ""https://orcid.org/0000-0002-3604-4...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10500599.1"", ""URL"": ""h...",10.1002/essoar.10500599.1,10.1002,10.1002,essoar.10500599.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
12,crossref::10.1002/essoar.10500139.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500139.1,10.1002/essoar.10500139.1,https://doi.org/10.1002/essoar.10500139.1,http://www.essoar.org/doi/10.1002/essoar.10500...,http://www.essoar.org/doi/10.1002/essoar.10500...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Geophysics,None,Groundwater exploration in crystalline basemen...,None,None,None,None,posted-content,other,other,None,True,2019-08-28,2018-12-13,2021-02-23,2025-02-21,None,2018-12-13,None,2018-12-13,None,2018,issued_date,posted_date,None,None,None,None,None,None,"[{""URL"": ""https://www.essoar.org/pdfjs/10.1002...",None,"Aizebeokhai, Ahzegbobor P.; Oni, Adenifesimi A...","Covenant University, Ota, Nigeria",None,"[{""ORCID"": ""https://orcid.org/0000-0002-4243-5...",None,None,None,None,NaN,None,None,None,0,None,None,0,5,"[{""key"": ""p_1"", ""unstructured"": ""Aizebeokhai A...",None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10500139.1"", ""URL"": ""h...",10.1002/essoar.10500139.1,10.1002,10.1002,essoar.10500139.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
13,crossref::10.1002/essoar.10500573.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500573.1,10.1002/essoar.10500573.1,https://doi.org/10.1002/essoar.10500573.1,http://www.essoar.org/doi/10.1002/essoar.10500...,http://www.essoar.org/doi/10.1002/essoar.10500...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Geology,None,Seasonal to Interannual Storm Controls on Coas...,None,None,None,None,posted-content,other,other,None,True,2019-08-28,2019-01-20,2021-02-23,2025-02-21,None,2019-01-20,None,2019-01-20,None,2019,issued_date,posted_date,None,None,None,None,None,None,"[{""URL"": ""https://www.essoar.org/pdfjs/10.1002...",None,"Conlin, Matthew; Adams, Peter; Jaeger, John","Department of Geological Sciences, University ...",None,"[{""ORCID"": ""https://orcid.org/0000-0002-6495-4...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10500573.1"", ""URL"": ""h...",10.1002/essoar.10500573.1,10.1002,10.1002,essoar.10500573.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
14,crossref::10.1002/essoar.10500789.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10500789.1,10.1002/essoar.10500789.1,https://doi.org/10.1002/essoar.10500789.1,http://www.essoar.org/doi/10.1002/essoar.10500...,http://www.essoar.org/doi/10.1002/essoar.10500...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Hydrology,None,A Fully Coupled Surface Water Storage and Soil...,None,None,None,None,posted-content,other,other,None,True,2019-08-28,2019-02-15,2021-02-23,2025-02-21,None,2019-02-15,None,2019-02-15,None,2019,issued_date,posted_date,None,None,None,None,None,None,"[{""URL"": ""https://www.essoar.org/pdfjs/10.1002...",None,"Qi, Junyu; Zhang, Xuesong; Lee, Sangchul; Mogl...",a. Earth System Science Interdisciplinary Cent...,None,"[{""ORCID"": ""https://orcid.org/0000-0001-5316-4...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10500789.1"", ""URL"": ""h...",10.1002/essoar.10500789.1,10.1002,10.1002,essoar.10500789.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
23,crossref::10.1002/essoar.10508653.2,Earth and Space Science Open Archive,crossref,10.1002/essoar.10508653.2,10.1002/essoar.10508653.2,https://doi.org/10.1002/essoar.10508653.2,http://www.essoar.org/doi/10.1002/essoar.10508...,http://www.essoar.org/doi/10.1002/essoar.10508...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Climatology (Global Change),None,Parametric Study of Prompt Methane Release Imp...,None,None,None,None,posted-content,other,other,None,True,2021-11-12,2021-11-12,2021-11-12,2025-05-13,None,2021-11-12,None,2021-11-12,None,2021,issued_date,posted_date,None,None,None,None,None,None,None,None,"Sheaffer, PattiMichelle",The Aerospace Corp. (ret.),None,"[{""ORCID"": ""https://orcid.org/0000-0002-6722-3...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10508653.2"", ""URL"": ""h...",10.1002/essoar.10508653.2,10.1002,10.1002,essoar.10508653.2,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
28,crossref::10.1002/essoar.10509588.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10509588.1,10.1002/essoar.10509588.1,https://doi.org/10.1002/essoar.10509588.1,http://www.essoar.org/doi/10.1002/essoar.10509...,http://www.essoar.org/doi/10.1002/essoar.10509...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Geochemistry,None,Effects of differences in aboveground dead org...,None,None,None,None,posted-content,other,other,None,True,2021-12-18,2021-12-18,2021-12-18,2025-05-13,None,2021-12-18,None,2021-12-18,None,2021,issued_date,posted_date,None,None,None,None,None,None,None,None,"Abe, Hayato",Graduate School of Bioresource and Bioenvironm...,None,"[{""ORCID"": ""https://orcid.org/0000-0001-6092-0...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10509588.1"", ""URL"": ""h...",10.1002/essoar.10509588.1,10.1002,10.1002,essoar.10509588.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
32,crossref::10.1002/essoar.10511159.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10511159.1,10.1002/essoar.10511159.1,https://doi.org/10.1002/essoar.10511159.1,http://www.essoar.org/doi/10.1002/essoar.10511...,http://www.essoar.org/doi/10.1002/essoar.10511...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,"Agricultural, Veterinary and Food Sciences",None,PDF presented work MR20,None,None,None,None,posted-content,other,other,None,True,2022-04-22,2022-04-22,2022-04-22,2025-05-13,None,2022-04-22,None,2022-04-22,None,2022,issued_date,posted_date,None,None,None,None,None,None,None,None,"Suleiman, Rawan",qa,None,"[{""ORCID"": ""https://orcid.org/0000-0001-8980-4...",None,None,None,None,NaN,None,None,None,0,None,None,0,29,"[{""DOI"": ""10.3923/pjn.2011.1195.1202"", ""articl...",None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10511159.1"", ""URL"": ""h...",10.1002/essoar.10511159.1,10.1002,10.1002,essoar.10511159.1,10.1002/essoar,10.1002/essoar,essoar.org,essoar.org/doi
48,crossref::10.1002/essoar.10508653.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10508653.1,10.1002/essoar.10508653.1,https://doi.org/10.1002/essoar.10508653.1,https://essopenarchive.org/doi/full/10.1002/es...,https://essopenarchive.org/doi/full/10.1002/es...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Climatology (Global Change),None,Parametric Study of Prompt Methane Release Imp...,None,None,None,None,posted-content,other,other,None,True,2021-11-08,2021-11-08,2022-12-05,2025-05-13,None,2021-11-08,None,2021-11-08,None,2021,issued_date,posted_date,None,None,None,None,None,None,None,None,"Sheaffer, PattiMichelle",The Aerospace Corp. (ret.),None,"[{""ORCID"": ""https://orcid.org/0000-0002-6722-3...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10508653.1"", ""URL"": ""h...",10.1002/essoar.10508653.1,10.1002,10.1002,essoar.10508653.1,10.1002/essoar,10.1002/essoar,essopenarchive.org,essopenarchive.org/doi
56,crossref::10.1002/essoar.ac8d55d17e7c3489.fe8e...,Earth and Space Science Open Archive,crossref,10.1002/essoar.ac8d55d17e7c3489.fe8e1720af2543...,10.1002/essoar.ac8d55d17e7c3489.fe8e1720af2543...,https://doi.org/10.1002/essoar.ac8d55d17e7c348...,https://essopenarchive.org/doi/full/10.1002/es...,https://essopenarchive.org/doi/full/10.1002/es...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Oceanography,None,Southern Ocean Origin of Multidecadal Variabil...,None,None,None,None,posted-content,other,other,None,True,2019-11-13,2018-03-10,2022-12-05,2025-02-21,None,2018-03-10,None,2018-03-10,None,2018,issued_date,posted_date,None,None,None,None,None,None,"[{""URL"": ""https://www.essoar.org/pdfjs/10.1002...",None,"van Westen, René; Dijkstra, Henk",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8807-7...",None,None,None,None,NaN,None,None,None,0,None,None,0,3,"[{""article-title"": ""Multidecadal Variability o...",None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.ac8d55d17e7c3489.fe8e1...",10.1002/essoar.ac8d55d17e7c3489.fe8e1720af2543...,10.1002,10.1002,essoar.ac8d55d17e7c3489.fe8e1720af254321.1,10.1002/essoar,10.1002/essoar,essopenarchive.org,essopenarchive.org/doi
65,crossref::10.1002/essoar.10509843.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10509843.1,10.1002/essoar.10509843.1,https://doi.org/10.1002/essoar.10509843.1,https://essopenarchive.org/doi/full/10.1002/es...,https://essopenarchive.org/doi/full/10.1002/es...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Education,None,The Climate Literacy and Energy Awareness Netw...,None,None,None,None,posted-content,other,other,None,True,2021-12-25,2021-12-24,2022-12-05,2025-05-13,None,2021-12-24,None,2021-12-24,None,2021,issued_date,posted_date,None,None,None,None,None,None,None,None,"Boyd, Kathryn; Gold, Anne; Niepold, Frank; Och...",University of Colorado Boulder; NOAA Washingto...,None,"[{""ORCID"": ""https://orcid.org/0000-0002-7825-2...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10509843.1"", ""URL"": ""h...",10.1002/essoar.10509843.1,10.1002,10.1002,essoar.10509843.1,10.1002/essoar,10.1002/essoar,essopenarchive.org,essopenarchive.org/doi
68,crossref::10.1002/essoar.10510207.1,Earth and Space Science Open Archive,crossref,10.1002/essoar.10510207.1,10.1002/essoar.10510207.1,https://doi.org/10.1002/essoar.10510207.1,https://essopenarchive.org/doi/full/10.1002/es...,https://essopenarchive.org/doi/full/10.1002/es...,10.1002,311,None,None,crossref,Wiley,None,Earth and Space Science Open Archive,Geophysics,None,Lattice Boltzmann simulation of convection-dif...,None,None,None,None,posted-content,other,other,None,True,2022-01-19,2022-01-19,2022-12-05,2025-05-13,None,2022-01-19,None,2022-01-19,None,2022,issued_date,posted_date,None,None,None,None,None,None,None,None,"Mora, Peter; Morra, Gabriele; Patil, Shirish; ...",King Fahd University of Petroleum &amp; Minera...,None,"[{""ORCID"": ""https://orcid.org/0000-0001-5347-4...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,0,None,"{""DOI"": ""10.1002/essoar.10510207.1"", ""URL"": ""h...",10.1002/essoar.10510207.1,10.1002,10.1002,essoar.10510207.1,10.1002/essoar,10.1002/essoar,essopenarchive.org,essopenarchive.org/doi

types others seems to be abstract and not article
https://essopenarchive.org/doi/full/10.1002/essoar.10511112.1 
https://essopenarchive.org/doi/full/10.1002/essoar.10509431.1

In [54]:
Earth_parent_df[Earth_parent_df['primary_domain']=='techrxiv.org']

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
2467215,crossref::10.22541/essoar.170239691.10703830/v1,crossref::10.22541/essoar.170239691.10703830/v1,Earth and Space Science Open Archive,10.22541/essoar.170239691.10703830/v1,https://techrxiv.org/users/461179/articles/693...,bug test,"Asif, Usman",2023-12-12,2023,crossref::10.22541/essoar.170239691.10703830/v1,10.22541/essoar.170239691.10703830/v1,Earth and Space Science Open Archive (1),1,2023-12-12,2023-12-12,Earth and Space Science Open Archive,10.22541/essoar.170239691.10703830/v1,10.22541,10.22541,essoar.170239691.10703830/v1,10.22541/essoar,10.22541/essoar,techrxiv.org,techrxiv.org/users
6448262,crossref::10.22541/essoar.171007121.19572474/v1,crossref::10.22541/essoar.171007121.19572474/v1,Earth and Space Science Open Archive,10.22541/essoar.171007121.19572474/v1,https://www.techrxiv.org/users/715826/articles...,"Auto-WCEBleedGen Version V1 and V2: Challenge,...","Hub, Misa; Handa, Palak; Nautiyal, Divyansh; C...",2024-03-10,2024,crossref::10.22541/essoar.171007121.19572474/v1,10.22541/essoar.171007121.19572474/v1,Earth and Space Science Open Archive (1),1,2024-03-10,2024-03-10,Earth and Space Science Open Archive,10.22541/essoar.171007121.19572474/v1,10.22541,10.22541,essoar.171007121.19572474/v1,10.22541/essoar,10.22541/essoar,techrxiv.org,techrxiv.org/users

 10.22541/essoar.171007121.19572474/v1 on authorea instead of essoar or techrxiv
https://www.authorea.com/users/715826/articles/719344-auto-wcebleedgen-version-v1-and-v2-challenge-datasets-and-evaluation

In [55]:
Earth_parent_df[Earth_parent_df['primary_domain']=='authorea.com']

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
45930,crossref::10.22541/essoar.167458061.17750077/v1,crossref::10.22541/essoar.167458061.17750077/v1,Earth and Space Science Open Archive,10.22541/essoar.167458061.17750077/v1,https://www.authorea.com/users/354449/articles...,Convective self-compression of cratons and the...,"Paul, Jyotirmoy; Conrad, Clinton P; Becker, Th...",2023-01-24,2023,crossref::10.22541/essoar.167458061.17750077/v...,10.22541/essoar.167458061.17750077/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-01-24,2023-03-28,Earth and Space Science Open Archive,10.22541/essoar.167458061.17750077/v1,10.22541,10.22541,essoar.167458061.17750077/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
93451,crossref::10.22541/essoar.167048524.41438408/v1,crossref::10.22541/essoar.167048524.41438408/v1,Earth and Space Science Open Archive,10.22541/essoar.167048524.41438408/v1,https://www.authorea.com/users/549693/articles...,Quantifying site effects and their influence o...,"Chang, Hilary; Abercrombie, Rachel E.; Nakata,...",2022-12-08,2022,crossref::10.22541/essoar.167048524.41438408/v1,10.22541/essoar.167048524.41438408/v1,Earth and Space Science Open Archive (1),1,2022-12-08,2022-12-08,Earth and Space Science Open Archive,10.22541/essoar.167048524.41438408/v1,10.22541,10.22541,essoar.167048524.41438408/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
542600,crossref::10.22541/essoar.169705252.27888438/v1,crossref::10.22541/essoar.169705252.27888438/v1,Earth and Space Science Open Archive,10.22541/essoar.169705252.27888438/v1,https://www.authorea.com/users/671644/articles...,Simulation and Optimization of Maize Phyllotax...,"Xiang, Zhaocheng; Ge, Yufeng",2023-10-11,2023,crossref::10.22541/essoar.169705252.27888438/v...,10.22541/essoar.169705252.27888438/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-18,Earth and Space Science Open Archive,10.22541/essoar.169705252.27888438/v1,10.22541,10.22541,essoar.169705252.27888438/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
632649,crossref::10.22541/essoar.169705230.03901178/v1,crossref::10.22541/essoar.169705230.03901178/v1,Earth and Space Science Open Archive,10.22541/essoar.169705230.03901178/v1,https://www.authorea.com/users/671728/articles...,Low-Cost Photogrammetry Rig for 3D Crop Modell...,"Hrzich, Joe; Bidinosti, Christopher P.; Beck, ...",2023-10-11,2023,crossref::10.22541/essoar.169705230.03901178/v...,10.22541/essoar.169705230.03901178/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-14,Earth and Space Science Open Archive,10.22541/essoar.169705230.03901178/v1,10.22541,10.22541,essoar.169705230.03901178/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
816136,crossref::10.22541/essoar.169699689.90164121/v1,crossref::10.22541/essoar.169699689.90164121/v1,Earth and Space Science Open Archive,10.22541/essoar.169699689.90164121/v1,https://www.authorea.com/users/672042/articles...,Exploring Maize Stress Response Phenotypes via...,"Lima, Leonardo W.; Murphy, Katie; Quinones, Al...",2023-10-11,2023,crossref::10.22541/essoar.169699689.90164121/v...,10.22541/essoar.169699689.90164121/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-11,Earth and Space Science Open Archive,10.22541/essoar.169699689.90164121/v1,10.22541,10.22541,essoar.169699689.90164121/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1087617,crossref::10.22541/essoar.169705269.92949948/v1,crossref::10.22541/essoar.169705269.92949948/v1,Earth and Space Science Open Archive,10.22541/essoar.169705269.92949948/v1,https://www.authorea.com/users/671284/articles...,Field-based high throughput phenotyping of Fus...,"Cooper, Julian; Du, Chuan; Beaver, Zach; Zheng...",2023-10-11,2023,crossref::10.22541/essoar.169705269.92949948/v...,10.22541/essoar.169705269.92949948/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-19,Earth and Space Science Open Archive,10.22541/essoar.169705269.92949948/v1,10.22541,10.22541,essoar.169705269.92949948/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1109992,crossref::10.22541/essoar.169705293.33729377/v1,crossref::10.22541/essoar.169705293.33729377/v1,Earth and Space Science Open Archive,10.22541/essoar.169705293.33729377/v1,https://www.authorea.com/users/516614/articles...,Salt stress using Chenopodium quinoa as a mode...,"Acosta-Gamboa, Lucia; Czymmek, Kirk; Klebanovy...",2023-10-11,2023,crossref::10.22541/essoar.169705293.33729377/v...,10.22541/essoar.169705293.33729377/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-18,Earth and Space Science Open Archive,10.22541/essoar.169705293.33729377/v1,10.22541,10.22541,essoar.169705293.33729377/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1112008,crossref::10.22541/essoar.167079490.04584415/v1,crossref::10.22541/essoar.167079490.04584415/v1,Earth and Space Science Open Archive,10.22541/essoar.167079490.04584415/v1,https://www.authorea.com/users/564792/articles...,Abstract,"Ringuette, Rebecca",2022-12-11,2022,crossref::10.22541/essoar.167079490.04584415/v...,10.22541/essoar.167079490.04584415/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2022-12-11,2022-12-11,Earth and Space Science Open Archive,10.22541/essoar.167079490.04584415/v1,10.22541,10.22541,essoar.167079490.04584415/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1179470,crossref::10.22541/essoar.167016857.73309909.1,crossref::10.22541/essoar.167016857.73309909.1,Earth and Space Science Open Archive,10.22541/essoar.167016857.73309909.1,https://www.authorea.com/users/525275/articles...,Non-native hosts of an invasive seaweed holobi...,"Author, Albert",2022-12-04,2022,crossref::10.22541/essoar.167016857.73309909.1,10.22541/essoar.167016857.73309909.1,Earth and Space Science Open Archive (1),1,2022-12-04,2022-12-04,Earth and Space Science Open Archive,10.22541/essoar.167016857.73309909.1,10.22541,10.22541,essoar.167016857.73309909.1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1207897,crossref::10.22541/essoar.167898498.81970799/v1,crossref::10.22541/essoar.167898498.81970799/v1,Earth and Space Science Open Archive,10.22541/essoar.167898498.81970799/v1,https://www.authorea.com/users/226607/articles...,Impact of climate change on water sources and ...,"Berezowski, Tomasz; Partington, Daniel",2023-03-16,2023,crossref::10.22541/essoar.167898498.81970799/v1,10.22541/essoar.167898498.81970799/v1,Earth and Space Science Open Archive (1),1,2023-03-16,2023-03-16,Earth and Space Science Open Archive,10.22541/essoar.167898498.81970799/v1,10.22541,10.22541,essoar.167898498.81970799/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1244929,crossref::10.22541/essoar.169699698.84993834/v1,crossref::10.22541/essoar.169699698.84993834/v1,Earth and Space Science Open Archive,10.22541/essoar.169699698.84993834/v1,https://www.authorea.com/users/670301/articles...,Phenotypic Responses of Diverse Maize Inbred L...,"Quinones, Alejandra; Murphy, Katherine M.; Cas...",2023-10-11,2023,crossref::10.22541/essoar.169699698.84993834/v...,10.22541/essoar.169699698.84993834/v1; 10.2254...,Earth and Space Science Open Archive (3),3,2023-10-11,2023-10-18,Earth and Space Science Open Archive,10.22541/essoar.169699698.84993834/v1,10.22541,10.22541,essoar.169699698.84993834/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1570332,crossref::10.22541/essoar.167214301.16153548/v1,crossref::10.22541/essoar.167214301.16153548/v1,Earth and Space Science Open Archive,10.22541/essoar.167214301.16153548/v1,https://www.authorea.com/users/565535/articles...,Magnetic Mapping in the Inner Magnetosphere us...,"Rastaetter, Lutz; Ringuette, Rebecca; Zeeuw, D...",2022-12-27,2022,crossref::10.22541/essoar.167214301.16153548/v1,10.22541/essoar.167214301.16153548/v1,Earth and Space Science Open Archive (1),1,2022-12-27,2022-12-27,Earth and Space Science Open Archive,10.22541/essoar.167214301.16153548/v1,10.22541,10.22541,essoar.167214301.16153548/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1609374,crossref::10.22541/essoar.169705285.53298683/v1,crossref::10.22541/essoar.169705285.53298683/v1,Earth and Space Science Open Archive,10.22541/essoar.169705285.53298683/v1,https://www.authorea.com/users/670875/articles...,Physiological and Digital Phenotyping of Droug...,"Rathuge, Lakma; Eynck, Christina; Duddu, Hema;...",2023-10-11,2023,crossref::10.22541/essoar.169705285.53298683/v...,10.22541/essoar.169705285.53298683/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-18,Earth and Space Science Open Archive,10.22541/essoar.169705285.53298683/v1,10.22541,10.22541,essoar.169705285.53298683/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1678860,crossref::10.22541/essoar.169705307.73842540/v1,crossref::10.22541/essoar.169705307.73842540/v1,Earth and Space Science Open Archive,10.22541/essoar.169705307.73842540/v1,https://www.authorea.com/users/670405/articles...,Unlocking the Potential of High-Resolution Sat...,"Mazis, Anastasios; Barbeau, Adam; Linares, Jul...",2023-10-11,2023,crossref::10.22541/au.169843055.55730961/v1; c...,10.22541/au.169843055.55730961/v1; 10.22541/es...,Earth and Space Science Open Archive (2); Auth...,3,2023-10-11,2023-10-27,Authorea Inc.,10.22541/essoar.169705307.73842540/v1,10.22541,10.22541,essoar.169705307.73842540/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
1922012,crossref::10.22541/essoar.167458056.60231054/v1,crossref::10.22541/essoar.167458056.60231054/v1,Earth and Space Science Open Archive,10.22541/essoar.167458056.60231054/v1,https://www.authorea.com/users/579048/articles...,A grey area of research ethics: Public vs priv...,"Williams, Ryan",2023-01-24,2023,crossref::10.22541/essoar.167458056.60231054/v1,10.22541/essoar.167458056.60231054/v1,Earth and Space Science Open Archive (1),1,2023-01-24,2023-01-24,Earth and Space Science Open Archive,10.22541/essoar.167458056.60231054/v1,10.22541,10.22541,essoar.167458056.60231054/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2000288,crossref::10.22541/essoar.169699683.34657894/v1,crossref::10.22541/essoar.169699683.34657894/v1,Earth and Space Science Open Archive,10.22541/essoar.169699683.34657894/v1,https://www.authorea.com/users/671707/articles...,AICropCAM -- An Edge Imaging Platform with a S...,"Chamara, Nipuna; Bai, Geng(Frank); Ge, Yufeng",2023-10-11,2023,crossref::10.22541/essoar.169699683.34657894/v...,10.22541/essoar.169699683.34657894/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-11,Earth and Space Science Open Archive,10.22541/essoar.169699683.34657894/v1,10.22541,10.22541,essoar.169699683.34657894/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2123320,crossref::10.22541/essoar.168351206.68445909/v1,crossref::10.22541/essoar.168351206.68445909/v1,Earth and Space Science Open Archive,10.22541/essoar.168351206.68445909/v1,https://www.authorea.com/users/615369/articles...,A Deep Learning Based Proposed Framework of Pr...,"Steve, Michael; Hussain, Shafiq; Yen, Chin",2023-05-08,2023,crossref::10.22541/essoar.168351206.68445909/v1,10.22541/essoar.168351206.68445909/v1,Earth and Space Science Open Archive (1),1,2023-05-08,2023-05-08,Earth and Space Science Open Archive,10.22541/essoar.168351206.68445909/v1,10.22541,10.22541,essoar.168351206.68445909/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2247426,crossref::10.22541/essoar.169699691.10581758/v1,crossref::10.22541/essoar.169699691.10581758/v1,Earth and Space Science Open Archive,10.22541/essoar.169699691.10581758/v1,https://www.authorea.com/users/512022/articles...,Diurnal Variation of Canopy NDVI in Maize and ...,"Zhang, Junxiao; Bai, Geng(Frank); Chamara, Nip...",2023-10-11,2023,crossref::10.22541/essoar.169699691.10581758/v...,10.22541/essoar.169699691.10581758/v1; 10.2254...,Earth and Space Science Open Archive (3),3,2023-10-11,2023-10-18,Earth and Space Science Open Archive,10.22541/essoar.169699691.10581758/v1,10.22541,10.22541,essoar.169699691.10581758/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2353438,crossref::10.22541/essoar.167214515.55390432/v1,crossref::10.22541/essoar.167214515.55390432/v1,Earth and Space Science Open Archive,10.22541/essoar.167214515.55390432/v1,https://www.authorea.com/users/568618/articles...,Impacts of Satellite Reentry on Atmospheric Co...,"Ferreira, José P.; Huang, Ziyu; Nomura, Ken-ic...",2022-12-27,2022,crossref::10.22541/essoar.167214515.55390432/v1,10.22541/essoar.167214515.55390432/v1,Earth and Space Science Open Archive (1),1,2022-12-27,2022-12-27,Earth and Space Science Open Archive,10.22541/essoar.167214515.55390432/v1,10.22541,10.22541,essoar.167214515.55390432/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2443569,crossref::10.22541/essoar.169705244.47100685/v1,crossref::10.22541/essoar.169705244.47100685/v1,Earth and Space Science Open Archive,10.22541/essoar.169705244.47100685/v1,https://www.authorea.com/users/671711/articles...,Germination of Camelina sativa producing modif...,"Ballenger, Joe; Kenney, Sam; Gordon, Jared; Br...",2023-10-11,2023,crossref::10.22541/essoar.169705244.47100685/v...,10.22541/essoar.169705244.47100685/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-12,Earth and Space Science Open Archive,10.22541/essoar.169705244.47100685/v1,10.22541,10.22541,essoar.169705244.47100685/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2835017,crossref::10.22541/essoar.169699748.85334295/v1,crossref::10.22541/essoar.169699748.85334295/v1,Earth and Space Science Open Archive,10.22541/essoar.169699748.85334295/v1,https://www.authorea.com/users/671984/articles...,Winter Dormancy and Spring Growth in Winter Wheat,"Jamazlei, Adele; Sandhu, Karansher Singh; Cart...",2023-10-11,2023,crossref::10.22541/essoar.169699748.85334295/v...,10.22541/essoar.169699748.85334295/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-11,Earth and Space Science Open Archive,10.22541/essoar.169699748.85334295/v1,10.22541,10.22541,essoar.169699748.85334295/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2839264,crossref::10.22541/essoar.167979664.49865251/v1,crossref::10.22541/essoar.167979664.49865251/v1,Earth and Space Science Open Archive,10.22541/essoar.167979664.49865251/v1,https://www.authorea.com/users/596050/articles...,Radiative impacts of Californian marine low cl...,"Miyamoto, Ayumu; Nakamura, Hisashi; Xie, Shang...",2023-03-25,2023,crossref::10.22541/essoar.167979664.49865251/v...,10.22541/essoar.167979664.49865251/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-03-25,2023-08-08,Earth and Space Science Open Archive,10.22541/essoar.167979664.49865251/v1,10.22541,10.22541,essoar.167979664.49865251/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2864778,crossref::10.22541/essoar.169705248.88076354/v1,crossref::10.22541/essoar.169705248.88076354/v1,Earth and Space Science Open Archive,10.22541/essoar.169705248.88076354/v1,https://www.authorea.com/users/671696/articles...,Utilizing High-Throughput Phenotyping for Iden...,"Zubrod, Melinda; Herr, Andrew W; Spychalla, Pi...",2023-10-11,2023,crossref::10.22541/essoar.169705248.88076354/v...,10.22541/essoar.169705248.88076354/v1; 10.2254...,Earth and Space Science Open Archive (2),2,2023-10-11,2023-10-18,Earth and Space Science Open Archive,10.22541/essoar.169705248.88076354/v1,10.22541,10.22541,essoar.169705248.88076354/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
2884802,crossref::10.22541/essoar.167079456.68733298/v1,crossref::10.22541/essoar.167079456.68733298/v1,Earth and Space Science Open Archive,10.22541/essoar.167079456.68733298/v1,https://www.authorea.com/users/525475/articles...,Test Document,"Hanson, R. Brooks",2022-12-11,2022,crossref::10.22541/essoar.167079456.68733298/v1,10.22541/essoar.167079456.68733298/v1,Earth and Space Science Open Archive (1),1,2022-12-11,2022-12-11,Earth and Space Science Open Archive,10.22541/essoar.167079456.68733298/v1,10.22541,10.22541,essoar.167079456.68733298/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
3056697,crossref::10.22541/essoar.170800918.86740881/v1,crossref::10.22541/essoar.170800918.86740881/v1,Earth and Space Science Open Archive,10.22541/essoar.170800918.86740881/v1,https://www.authorea.com/users/441247/articles...,Toward field-scale groundwater pumping and imp...,"Ott, Thomas J; Majumdar, Sayantan; Huntington,...",2024-02-15,2024,crossref::10.22541/essoar.170800918.86740881/v1,10.22541/essoar.170800918.86740881/v1,Earth and Space Science Open Archive (1),1,2024-02-15,2024-02-15,Earth and Space Science Open Archive,10.22541/essoar.170800918.86740881/v1,10.22541,10.22541,essoar.170800918.86740881/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
3197422,crossref::10.22541/essoar.167979635.58663858/v1,crossref::10.22541/essoar.167979635.58663858/v1,Earth and Space Science Open Archive,10.22541/essoar.167979635.58663858/v1,https://www.authorea.com/users/433025/articles...,Spatial organisation affects the pathway to pr...,"Radtke, Jule; Vogel, Raphaela; Ament, Felix; N...",2023-03-25,2023,crossref::10.22541/essoar.167979635.58663858/v...,10.22541/essoar.167979635.58663858/v1; 10.2254...,Earth and Space Science Open Archive (3),3,2023-03-25,2023-09-19,Earth and Space Science Open Archive,10.22541/essoar.167979635.58663858/v1,10.22541,10.22541,essoar.167979635.58663858/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
3259321,crossref::10.22541/essoar.167458059.91056213/v1,crossref::10.22541/essoar.167458059.91056213/v1,Earth and Space Science Open Archive,10.22541/essoar.167458059.91056213/v1,https://www.authorea.com/users/568157/articles...,Prediction of rainfall response to the 21st-ce...,"Arthur, Frank; Boateng, Daniel; Baidu, Michael...",2023-01-24,2023,crossref::10.22541/essoar.167458059.91056213/v1,10.22541/essoar.167458059.91056213/v1,Earth and Space Science Open Archive (1),1,2023-01-24,2023-01-24,Earth and Space Science Open Archive,10.22541/essoar.167458059.91056213/v1,10.22541,10.22541,essoar.167458059.91056213/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users
3298714,crossref::10.22541/essoar.167458056.68381705/v1,crossref::10.22541/essoar.167458056.68381705/v1,Earth and Space Science Open Archive,10.22541/essoar.167458056.68381705/v1,https://www.authorea.com/users/579078/articles...,Analysis of Early-Warning Signals for Arctic S...,"Poltronieri, Anna; Bochow, Nils; Rypdal, Martin",2023-01-24,2023,crossref::10.22541/essoar.167458056.68381705/v1,10.22541/essoar.167458056.68381705/v1,Earth and Space Science Open Archive (1),1,2023-01-24,2023-01-24,Earth and Space Science Open Archive,10.22541/essoar.167458056.68381705/v1,10.22541,10.22541,essoar.167458056.68381705/v1,10.22541/essoar,10.22541/essoar,authorea.com,authorea.com/users

# EarthArXiv

In [56]:
EarthArXiv_df, EarthArXiv_summary = get_server_data("EarthArXiv")

==================================================
 SERVER ANALYSIS: EARTHARXIV
==================================================
  > Files found:    2
  > Raw records:    6537
  > Cleaned shape:  (6537, 90)
  > Unique DOIs:    6537
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31223/x      4691
10.31223/osf    1777
10.31227/osf      26
10.31219/osf      18
10.31234/osf       6
10.31225/osf       6
10.31220/osf       6
10.15697/fk        2
10.31235/osf       2
10.31228/osf       2
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
eartharxiv.org        6373
osf.io                 163
dev.eartharxiv.org       1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31223    6468
10.31227      26
10.31219      18
10.31234       6
10.31225       6
10.31220       6
10.15697       2
10.31235       2
10.31228       2
10.31230       1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
29705    6470
15934      61
242         6
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
California Digital Library (CDL)    6470
Center for Open Science               61
CABI Publishing                        6
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    6537
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    6537
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Physical Sciences and Mathematics      1885
Earth Sciences                         1324
Engineering                             460
Life Sciences                           230
Civil and Environmental Engineering     174
EarthArXiv                              163
Atmospheric Sciences                    151
Geophysics and Seismology               148
Climate                                 123
Education                               108
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    6537
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    6537
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    6537
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR EARTHARXIV
==================================================

In [57]:
EarthArXiv_parent_df, EarthArXiv_parent_summary = analyze_parent_data("EarthArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: EARTHARXIV
=================================================================
  > Total Parent Groups:     6,256
  > Total Versions Found:    6,821
  > Unique Parent DOIs:      6,256
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EarthArXiv:
-----------------------------------
  1 version(s):     5,718 groups
  2 version(s):     516 groups
  3 version(s):     18 groups
  4 version(s):     3 groups
  5 version(s):     1 groups

  Average versions per parent: 1.09

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EarthArXiv                              6015
EarthArXiv; Open Science Framework       125
Research Square                           23
SSRN                                      23
Earth and Space Science Open Archive      13
EarthArXiv; arXiv                         12
EGUsphere                                 11
arXiv                                     10
EarthArXiv; ResearchGate                   7
ResearchGate                               3

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31223/x      4443
10.31223/osf    1792
10.17605/osf      20
10.15697/fk        1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
eartharxiv.org        6093
osf.io                 162
dev.eartharxiv.org       1


=================================================================
 COMPLETED: EARTHARXIV
=================================================================

# EasyChair preprint

In [58]:
EasyChair_df, EasyChair_summary = get_server_data("EasyChair_preprint")

==================================================
 SERVER ANALYSIS: EASYCHAIR_PREPRINT
==================================================
  > Files found:    1
  > Raw records:    620
  > Cleaned shape:  (620, 90)
  > Unique DOIs:    620
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.29007/g    12
10.29007/h     9
10.29007/k     9
10.29007/t     8
10.29007/c     8
10.29007/m     7
10.29007/p     7
10.29007/z     7
10.29007/v     6
10.29007/x     6
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
easychair.org    620
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.29007    620
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
11545    620
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
EasyChair    620
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
EasyChair Preprints    620
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    620
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    620
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2516-2314    620
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
report-series    619
report             1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    620
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR EASYCHAIR_PREPRINT
==================================================

In [59]:
EasyChair_df

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.29007/hsh2,EasyChair preprint,crossref,10.29007/hsh2,10.29007/hsh2,https://doi.org/10.29007/hsh2,https://easychair.org/publications/preprint/1,https://easychair.org/publications/preprint/1,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,Unification with Abstraction and Theory Instan...,None,None,None,None,report-series,None,report-series,None,False,2018-01-12,None,2018-01-22,2022-04-05,None,2017-09-13,None,2017-09-13,None,2017,issued_date,None,None,None,None,None,<jats:p>This paper explores two new inference ...,This paper explores two new inference rules fo...,None,None,"Reger, Giles; Suda, Martin; Voronkov, Andrei",None,None,"[{""affiliation"": [], ""family"": ""Reger"", ""given...",None,None,None,None,None,None,None,None,2,None,None,2,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/hsh2"", ""ISSN"": [""2516-2314""]...",10.29007/hsh2,10.29007,10.29007,hsh2,10.29007/hsh,10.29007/hsh,easychair.org,easychair.org/publications
1,crossref::10.29007/g4bq,EasyChair preprint,crossref,10.29007/g4bq,10.29007/g4bq,https://doi.org/10.29007/g4bq,https://easychair.org/publications/preprint/WjKW,https://easychair.org/publications/preprint/WjKW,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,"Reconstructing Turing's ""paper machine""",None,None,None,None,report-series,None,report-series,None,False,2018-01-12,None,2018-01-22,2022-04-04,None,2017-09-14,None,2017-09-14,None,2017,issued_date,None,None,None,None,None,<jats:p>It is an amazing fact that the very fi...,It is an amazing fact that the very first ches...,None,None,"Kasparov, Garry; Friedel, Frederic",None,None,"[{""affiliation"": [], ""family"": ""Kasparov"", ""gi...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/g4bq"", ""ISSN"": [""2516-2314""]...",10.29007/g4bq,10.29007,10.29007,g4bq,10.29007/g,10.29007/g,easychair.org,easychair.org/publications
2,crossref::10.29007/pjn4,EasyChair preprint,crossref,10.29007/pjn4,10.29007/pjn4,https://doi.org/10.29007/pjn4,https://easychair.org/publications/preprint/N2sl,https://easychair.org/publications/preprint/N2sl,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,Computation of Some Integer Sequences in Maple,None,None,None,None,report-series,None,report-series,None,False,2018-01-12,None,2018-01-22,2024-07-11,None,2017-11-20,None,2017-11-20,None,2017,issued_date,None,None,None,None,None,<jats:p>We consider some integer sequences con...,We consider some integer sequences connected w...,None,None,"Fan, W.L.; Jeffrey, David J.; Postma, Erik",None,None,"[{""affiliation"": [], ""family"": ""Fan"", ""given"":...",None,None,None,None,None,None,None,None,7,None,None,7,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/pjn4"", ""ISSN"": [""2516-2314""]...",10.29007/pjn4,10.29007,10.29007,pjn4,10.29007/pjn,10.29007/pjn,easychair.org,easychair.org/publications
3,crossref::10.29007/g5sh,EasyChair preprint,crossref,10.29007/g5sh,10.29007/g5sh,https://doi.org/10.29007/g5sh,https://easychair.org/publications/preprint/rgjv,https://easychair.org/publications/preprint/rgjv,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,Giant photo-effect in proton transport through...,None,None,None,None,report-series,None,report-series,None,False,2018-01-12,None,2018-01-22,2022-04-03,None,2017-09-14,None,2017-09-14,None,2017,issued_date,None,None,None,None,None,<jats:p>Graphene has recently been shown to be...,Graphene has recently been shown to be permeab...,None,None,"Lozada-Hidalgo, Marcelo; Hu, Sheng; Zhang, She...",None,None,"[{""affiliation"": [], ""family"": ""Lozada-Hidalgo...",None,None,None,None,None,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/g5sh"", ""ISSN"": [""2516-2314""]...",10.29007/g5sh,10.29007,10.29007,g5sh,10.29007/g,10.29007/g,easychair.org,easychair.org/publications
4,crossref::10.29007/gpnx,EasyChair preprint,crossref,10.29007/gpnx,10.29007/gpnx,https://doi.org/10.29007/gpnx,https://easychair.org/publications/preprint/BdRC,https://easychair.org/publications/preprint/BdRC,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,Extending IFC for Fire Emergency Real-Time Man...,None,None,None,None,report-series,None,report-series,None,False,2018-01-22,None,2018-01-22,2025-11-27,None,2018-01-20,None,2018-01-20,None,2018,issued_date,None,None,None,None,None,<jats:p>The increasing complexity of buildings...,The increasing complexity of buildings has bro...,None,None,"Eftekharirad, Roshanak; Nik-Bakht, Mazdak; Ham...",None,None,"[{""affiliation"": [], ""family"": ""Eftekharirad"",...",None,None,None,None,None,None,None,None,6,None,None,6,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/gpnx"", ""ISSN"": [""2516-2314""]...",10.29007/gpnx,10.29007,10.29007,gpnx,10.29007/gpnx,10.29007/gpnx,easychair.org,easychair.org/publications
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,crossref::10.29007/gwn6,EasyChair preprint,crossref,10.29007/gwn6,10.29007/gwn6,https://doi.org/10.29007/gwn6,https://easychair.org/publications/preprint/ckKn,https://easychair.org/publications/preprint/ckKn,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,Move it or lose it: Exploring the relation of ...,None,None,None,None,report-series,None,report-series,None,False,2019-05-12,None,2019-05-12,2024-02-13,None,2019-05-12,None,2019-05-12,None,2019,issued_date,None,None,None,None,None,<jats:p>Introduction: Due to the increasing nu...,Introduction: Due to the increasing number of ...,None,None,"Kempe, Matthias; Goes, Floris",None,None,"[{""affiliation"": [], ""family"": ""Kempe"", ""given...",None,None,None,None,None,None,None,None,3,None,None,3,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/gwn6"", ""ISSN"": [""2516-2314""]...",10.29007/gwn6,10.29007,10.29007,gwn6,10.29007/gwn,10.29007/gwn,easychair.org,easychair.org/publications
616,crossref::10.29007/wp6k,EasyChair preprint,crossref,10.29007/wp6k,10.29007/wp6k,https://doi.org/10.29007/wp6k,https://easychair.org/publications/preprint/BSKN,https://easychair.org/publications/preprint/BSKN,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,Bridging Levels of Public Administration: How ...,None,None,None,None,report-series,None,report-series,None,False,2019-05-14,None,2019-05-14,2025-06-17,None,2019-05-14,None,2019-05-14,None,2019,issued_date,None,None,None,None,None,<jats:p>Scholars recognize three levels of ana...,Scholars recognize three levels of analysis in...,None,None,"Roberts, Alasdair",None,None,"[{""affiliation"": [], ""family"": ""Roberts"", ""giv...",None,None,None,None,None,None,None,None,2,None,None,2,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/wp6k"", ""ISSN"": [""2516-2314""]...",10.29007/wp6k,10.29007,10.29007,wp6k,10.29007/wp,10.29007/wp,easychair.org,easychair.org/publications
617,crossref::10.29007/djnw,EasyChair preprint,crossref,10.29007/djnw,10.29007/djnw,https://doi.org/10.29007/djnw,https://easychair.org/publications/preprint/PrNk,https://easychair.org/publications/preprint/PrNk,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,A Review on Optimization Methods to Enhance En...,None,None,None,None,report-series,None,report-series,None,False,2019-09-21,None,2019-09-21,2025-12-26,None,2019-09-20,None,2019-09-20,None,2019,issued_date,None,None,None,None,None,<jats:p>The aim of this paper is to make avail...,The aim of this paper is to make available of ...,None,None,"Srinivas, G Lakshmi; Mane, Ruturaj; Javed, Arshad",None,None,"[{""affiliation"": [], ""family"": ""Srinivas"", ""gi...",None,None,None,None,None,None,None,None,7,None,None,7,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/djnw"", ""ISSN"": [""2516-2314""]...",10.29007/djnw,10.29007,10.29007,djnw,10.29007/djnw,10.29007/djnw,easychair.org,easychair.org/publications
618,crossref::10.29007/9l79,EasyChair preprint,crossref,10.29007/9l79,10.29007/9l79,https://doi.org/10.29007/9l79,https://easychair.org/publications/preprint/VhBw,https://easychair.org/publications/preprint/VhBw,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,Experimental Validation of a Performance Model...,None,None,None,None,report-series,None,report-series,None,False,2020-01-11,None,2020-01-11,2025-11-01,None,2020-01-11,None,2020-01-11,None,2020,issued_date,None,None,None,None,None,"<jats:p>Ulva lactuca is a green alga, commonly...","Ulva lactuca is a green alga, commonly named a...",None,None,"Cartel, Juvyneil Echon",None,None,"[{""affiliation"": [], ""family"": ""Cartel"", ""give...",None,None,None,None,None,None,None,None,1,None,None,1,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/9l79"", ""ISSN"": [""2516-2314""]...",10.29007/9l79,10.29007,10.29007,9l79,10.29007/9l79,10.29007/9l79,easychair.org,easychair.org/publications
619,crossref::10.29007/qwpk,EasyChair preprint,crossref,10.29007/qwpk,10.29007/qwpk,https://doi.org/10.29007/qwpk,https://easychair.org/publications/preprint/PqCH,https://easychair.org/publications/preprint/PqCH,10.29007,11545,None,None,crossref,EasyChair,EasyChair Preprints,None,None,2516-2314,A Beamforming Method Based on Polarization Mat...,None,None,None,None,report-series,None,report-series,None,False,2020-09-26,None,2020-09-26,2025-11-13,None,2020-09-25,None,2020-09-25,None,2020,issued_date,None,None,None,None,None,<jats:p>By analyzing the polarization-sensitiv...,By analyzing the polarization-sensitive array ...,None,None,"Yang, Xiaohui; Gu, Jie; Jiang, Jingfei; Li, Yu...",None,None,"[{""affiliation"": [], ""family"": ""Yang"", ""given""...",None,None,None,None,None,None,None,None,103,None,None,103,0,None,None,,,False,None,,None,None,,None,NaN,None,issn,14,None,"{""DOI"": ""10.29007/qwpk"", ""ISSN"": [""2516-2314""]...",10.29007/qwpk,10.29007,10.29007,qwpk,10.29007/qwpk,10.29007/qwpk,easychair.org,easychair.org/publications

In [60]:
EasyChair_parent_df, EasyChair_parent_summary = analyze_parent_data("EasyChair preprint", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: EASYCHAIR PREPRINT
=================================================================
  > Total Parent Groups:     571
  > Total Versions Found:    606
  > Unique Parent DOIs:      571
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EasyChair preprint:
-----------------------------------
  1 version(s):     539 groups
  2 version(s):     29 groups
  3 version(s):     3 groups

  Average versions per parent: 1.06

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EasyChair preprint                  541
arXiv                                20
PeerJ Preprints                       3
ResearchGate                          2
EasyChair preprint; arXiv             2
EasyChair preprint; ResearchGate      2
HAL                                   1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.29007/g    10
10.29007/h     8
10.29007/k     8
10.29007/p     7
10.29007/z     7
10.29007/t     7
10.29007/m     7
10.29007/c     6
10.29007/x     6
10.29007/s     5



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
easychair.org    571


=================================================================
 COMPLETED: EASYCHAIR PREPRINT
=================================================================

# EcoEvoRxiv

In [61]:
EcoEvoRxiv_df, EcoEvoRxiv_summary = get_server_data("EcoEvoRxiv")

==================================================
 SERVER ANALYSIS: ECOEVORXIV
==================================================
  > Files found:    2
  > Raw records:    2886
  > Cleaned shape:  (2886, 90)
  > Unique DOIs:    2886
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.32942/x      1948
10.32942/osf     935
10.31219/osf       3
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
ecoevorxiv.org    2838
osf.io              48
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.32942    2883
10.31219       3
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
29705    2862
15934      24
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
California Digital Library (CDL)    2862
Center for Open Science               24
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    2886
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    2886
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Life Sciences                        1421
Ecology and Evolutionary Biology      388
Biodiversity                          255
Social and Behavioral Sciences         87
Behavior and Ethology                  83
Biology                                69
Physical Sciences and Mathematics      54
EcoEvoRxiv                             48
Animal Sciences                        45
Medicine and Health Sciences           36
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2886
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    2886
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    2886
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ECOEVORXIV
==================================================

In [62]:
EcoEvoRxiv_parent_df, EcoEvoRxiv_parent_summary = analyze_parent_data("EcoEvoRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ECOEVORXIV
=================================================================
  > Total Parent Groups:     2,795
  > Total Versions Found:    2,896
  > Unique Parent DOIs:      2,795
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EcoEvoRxiv:
-----------------------------------
  1 version(s):     2,721 groups
  2 version(s):     62 groups
  3 version(s):     6 groups
  4 version(s):     2 groups
  5 version(s):     3 groups
  10 version(s):    1 groups

  Average versions per parent: 1.04

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EcoEvoRxiv                                         2752
Authorea Inc.                                        15
Research Square                                       7
SSRN                                                  5
eLife                                                 4
Open Science Framework                                2
EcoEvoRxiv; Zenodo                                    2
HAL                                                   1
EcoEvoRxiv; RePEc: Research Papers in Economics       1
EGUsphere                                             1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.32942/x      1879
10.32942/osf     914
10.31219/osf       2



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
ecoevorxiv.org    2749
osf.io              46


=================================================================
 COMPLETED: ECOEVORXIV
=================================================================

# EconStor Preprints

In [63]:
EconStor_df, EconStor_summary = get_server_data("EconStor_Preprints")

/tmp/ipykernel_3012/1196196344.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  raw_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)

==================================================
 SERVER ANALYSIS: ECONSTOR_PREPRINTS
==================================================
  > Files found:    3
  > Raw records:    71761
  > Cleaned shape:  (71761, 90)
  > Unique DOIs:    6867
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>                     64686
10.18723/diw               588
10.13140/rg                465
10.2373/18                 429
10.1007/s                  377
10.5282/ubm                376
10.34989/swp-              292
10.24406/publica-fhg-      262
10.3929/ethz-a-            242
10.17192/es                232
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
hdl.handle.net           71010
ideas.repec.org            371
econpapers.repec.org       176
econstor.eu                 71
budrich-journals.de         55
zenodo.org                  11
journal-alm.org              7
eprints.lincoln.ac.uk        4
bnarchives.yorku.ca          4
frankfurter-hefte.de         3
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        64676
10.18723      588
10.13140      489
10.5282       443
10.34989      437
10.2373       429
10.1007       381
10.3929       369
10.24406      266
10.4419       234
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    71761
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    71761
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    71761
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    71761
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    71761
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    71761
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
preprint        36052
article         33542
other             840
book              534
book-chapter      240
review            223
report            199
dissertation       82
editorial          24
paratext           20
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    71761
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ECONSTOR_PREPRINTS
==================================================

In [64]:
EconStor_parent_df, EconStor_parent_summary = analyze_parent_data("EconStor Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ECONSTOR PREPRINTS
=================================================================
  > Total Parent Groups:     62,784
  > Total Versions Found:    69,018
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EconStor Preprints:
-----------------------------------
  1 version(s):     57,156 groups
  2 version(s):     5,127 groups
  3 version(s):     422 groups
  4 version(s):     63 groups
  5 version(s):     14 groups
  8 version(s):     1 groups
  12 version(s):    1 groups

  Average versions per parent: 1.10

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EconStor Preprints                                           57507
SSRN                                                          4269
RePEc: Research Papers in Economics                            544
AgEcon Search                                                  194
EconStor Preprints; RePEc: Research Papers in Economics        166
ResearchGate                                                    23
EconStor Preprints; Social Science Open Access Repository       21
Social Science Open Access Repository                           12
arXiv                                                           11
HAL                                                             11

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    62784



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
hdl.handle.net          62205
ideas.repec.org           319
econpapers.repec.org      134
econstor.eu                64
budrich-journals.de         7
journal-alm.org             7
bnarchives.yorku.ca         3
frankfurter-hefte.de        3
bpb.de                      2
ssrn.com                    2


=================================================================
 COMPLETED: ECONSTOR PREPRINTS
=================================================================

# ECSarXiv

In [65]:
ECSarXiv_df, ECSarXiv_summary = get_server_data("ECSarXiv")

==================================================
 SERVER ANALYSIS: ECSARXIV
==================================================
  > Files found:    1
  > Raw records:    314
  > Cleaned shape:  (314, 90)
  > Unique DOIs:    314
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.1149/osf    314
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    314
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.1149    314
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
77    314
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
The Electrochemical Society    314
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    314
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    314
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
ECSarXiv    314
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    314
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    314
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    314
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ECSARXIV
==================================================

In [66]:
ECSarXiv_parent_df, ECSarXiv_parent_summary = analyze_parent_data("ECSarXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ECSARXIV
=================================================================
  > Total Parent Groups:     299
  > Total Versions Found:    334
  > Unique Parent DOIs:      299
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ECSarXiv:
-----------------------------------
  1 version(s):     265 groups
  2 version(s):     33 groups
  3 version(s):     1 groups

  Average versions per parent: 1.12

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ECSarXiv                                     289
ECSarXiv; Open Science Framework               4
Preprints.org                                  1
SSRN                                           1
engrXiv                                        1
ECSarXiv; arXiv                                1
ECSarXiv; Open Science Framework; engrXiv      1
arXiv                                          1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.1149/osf     298
10.17605/osf      1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io          298
ecsarxiv.org      1


=================================================================
 COMPLETED: ECSARXIV
=================================================================

# EdArXiv

In [67]:
EdArXiv_df, EdArXiv_summary = get_server_data("EdArXiv")

==================================================
 SERVER ANALYSIS: EDARXIV
==================================================
  > Files found:    1
  > Raw records:    2547
  > Cleaned shape:  (2547, 90)
  > Unique DOIs:    2547
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.35542/osf    2547
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    2547
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.35542    2547
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    2547
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    2547
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    2547
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    2547
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
EdArXiv    2547
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2547
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    2547
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    2547
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR EDARXIV
==================================================

In [68]:
EdArXiv_parent_df, EdArXiv_parent_summary = analyze_parent_data("EdArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: EDARXIV
=================================================================
  > Total Parent Groups:     2,153
  > Total Versions Found:    2,474
  > Unique Parent DOIs:      2,153
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EdArXiv:
-----------------------------------
  1 version(s):     1,911 groups
  2 version(s):     192 groups
  3 version(s):     38 groups
  4 version(s):     2 groups
  5 version(s):     7 groups
  6 version(s):     1 groups
  7 version(s):     1 groups
  9 version(s):     1 groups

  Average versions per parent: 1.15

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EdArXiv                                         2077
Thesis Commons                                    11
EdArXiv; ResearchGate                              9
SSRN                                               9
arXiv                                              8
Open Science Framework                             8
EdArXiv; arXiv                                     5
Research Square                                    3
Law Archive                                        2
EdArXiv; RePEc: Research Papers in Economics       2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.35542/osf    2153



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    2153


=================================================================
 COMPLETED: EDARXIV
=================================================================

# EGUsphere

In [69]:
EGUsphere_df, EGUsphere_summary = get_server_data("EGUsphere")

==================================================
 SERVER ANALYSIS: EGUSPHERE
==================================================
  > Files found:    1
  > Raw records:    15253
  > Cleaned shape:  (15253, 90)
  > Unique DOIs:    15253
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.5194/egusphere-    15249
10.5194/amt-              3
10.5194/hess-             1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
egusphere.copernicus.org          15252
oscar-egusphere.copernicus.org        1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.5194    15253
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
3145    15253
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Copernicus GmbH    15253
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    15253
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    15253
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None                                                                                                                        322
Atmospheric sciences                                                                                                        297
Climate and Earth system modeling                                                                                           282
Gases/Atmospheric Modelling and Data Analysis/Troposphere/Chemistry (chemical composition and reactions)                    244
Aerosols/Field Measurements/Troposphere/Chemistry (chemical composition and reactions)                                      233
Gases/Field Measurements/Troposphere/Chemistry (chemical composition and reactions)                                         177
Clouds and Precipitation/Atmospheric Modelling and Data Analysis/Troposphere/Physics (physical properties and processes)    173
Aerosols/Atmospheric Modelling and Data Analysis/Troposphere/Physics (physical properties and processes)                    167
Aerosols/Field Measurements/Troposphere/Physics (physical properties and processes)                                         155
Catchment hydrology/Modelling approaches                                                                                    141
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    15253
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    15253
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    10458
other        4795
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR EGUSPHERE
==================================================

In [70]:
pattern = r'10.5194/amt-|10.5194/hess-'
# pattern = r'v\d+$'
mask = EGUsphere_df['doi'].str.contains(pattern, regex=True, na=False)
result = EGUsphere_df[mask]
result

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
263,crossref::10.5194/amt-2022-295,EGUsphere,crossref,10.5194/amt-2022-295,10.5194/amt-2022-295,https://doi.org/10.5194/amt-2022-295,https://egusphere.copernicus.org/preprints/202...,https://egusphere.copernicus.org/preprints/202...,10.5194,3145,None,None,crossref,Copernicus GmbH,None,None,Gases/In Situ Measurement/Instruments and Plat...,None,Temperature dependent sensitivity of iodide ch...,None,None,None,None,posted-content,preprint,preprint,None,True,2022-05-11,2022-05-11,2023-03-21,2026-02-28,None,2022-05-11,None,2022-05-11,None,2022,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>Abstract. Iodide chemical ionization m...,Abstract. Iodide chemical ionization mass spec...,None,None,"Robinson, Michael A.; Neuman, J. Andrew; Huey,...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-0977-9...",None,None,"[{""DOI"": ""10.13039/100004800"", ""award"": [""20RD...",California Air Resources Board; NOAA Center fo...,2.0,None,None,None,1,None,None,1,0,None,"{""has-comment"": [{""asserted-by"": ""subject"", ""i...",,10.5194/amt-15-4295-2022,True,None,,None,None,10.5194/amt-2022-295-rc1;10.5194/amt-2022-295-rc2,None,NaN,None,prefix/primary_domain,2,None,"{""DOI"": ""10.5194/amt-2022-295"", ""URL"": ""https:...",10.5194/amt-2022-295,10.5194,10.5194,amt-2022-295,10.5194/amt-,10.5194/amt-,egusphere.copernicus.org,egusphere.copernicus.org/preprints
264,crossref::10.5194/amt-2022-295-supplement,EGUsphere,crossref,10.5194/amt-2022-295-supplement,10.5194/amt-2022-295-supplement,https://doi.org/10.5194/amt-2022-295-supplement,https://egusphere.copernicus.org/preprints/202...,https://egusphere.copernicus.org/preprints/202...,10.5194,3145,None,None,crossref,Copernicus GmbH,None,None,Gases/In Situ Measurement/Instruments and Plat...,None,"Supplementary material to ""Temperature depende...",None,None,None,None,posted-content,other,other,None,True,2022-05-11,2022-05-11,2023-03-21,2026-02-28,None,2022-05-11,None,2022-05-11,None,2022,issued_date,posted_date,None,None,None,None,None,None,None,None,"Robinson, Michael A.; Neuman, J. Andrew; Huey,...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-0977-9...",None,None,None,None,NaN,None,None,None,1,None,None,1,0,None,"{""is-supplement-to"": [{""asserted-by"": ""subject...",,,False,None,,None,None,,None,NaN,None,prefix/primary_domain,2,None,"{""DOI"": ""10.5194/amt-2022-295-supplement"", ""UR...",10.5194/amt-2022-295-supplement,10.5194,10.5194,amt-2022-295-supplement,10.5194/amt-,10.5194/amt-,egusphere.copernicus.org,egusphere.copernicus.org/preprints
9390,crossref::10.5194/amt-2024-3967,EGUsphere,crossref,10.5194/amt-2024-3967,10.5194/amt-2024-3967,https://doi.org/10.5194/amt-2024-3967,https://egusphere.copernicus.org/preprints/202...,https://egusphere.copernicus.org/preprints/202...,10.5194,3145,None,None,crossref,Copernicus GmbH,None,None,"Others (Wind, Precipitation, Temperature, etc....",None,High-resolution maps of Arctic surface skin te...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-03-19,2025-03-19,2025-09-24,2026-02-28,None,2025-03-19,None,2025-03-19,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>Abstract. Two retrieval methods for th...,Abstract. Two retrieval methods for the determ...,None,None,"Müller, Joshua Jeremias; Schäfer, Michael; Ros...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0001-6584-2...",None,None,"[{""DOI"": ""10.13039/501100001659"", ""award"": [""2...",Deutsche Forschungsgemeinschaft; Universität L...,3.0,None,None,None,0,None,None,0,0,None,"{""has-comment"": [{""asserted-by"": ""subject"", ""i...",,10.5194/amt-18-4695-2025,True,None,,None,None,10.5194/amt-2024-3967-rc1;10.5194/amt-2024-396...,None,NaN,None,prefix/primary_domain,2,None,"{""DOI"": ""10.5194/amt-2024-3967"", ""URL"": ""https...",10.5194/amt-2024-3967,10.5194,10.5194,amt-2024-3967,10.5194/amt-,10.5194/amt-,egusphere.copernicus.org,egusphere.copernicus.org/preprints
10688,crossref::10.5194/hess-2024-3989,EGUsphere,crossref,10.5194/hess-2024-3989,10.5194/hess-2024-3989,https://doi.org/10.5194/hess-2024-3989,https://egusphere.copernicus.org/preprints/202...,https://egusphere.copernicus.org/preprints/202...,10.5194,3145,None,None,crossref,Copernicus GmbH,None,None,Water Resources Management/Uncertainty analysis,None,Error-correction across gauged and ungauged lo...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-01-30,2025-01-30,2025-11-11,2026-02-28,None,2025-01-30,None,2025-01-30,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<jats:p>Abstract. Forecasting river discharge ...,Abstract. Forecasting river discharge is essen...,None,None,"Matthews, Gwyneth; Cloke, Hannah L.; Dance, Sa...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-4776-8...",None,None,"[{""DOI"": ""10.13039/501100013341"", ""award"": [""N...",National Centre for Earth Observation; Natural...,5.0,None,None,None,1,None,None,1,0,None,"{""has-comment"": [{""asserted-by"": ""subject"", ""i...",,10.5194/hess-29-6157-2025,True,None,,None,None,10.5194/hess-2024-3989-rc1;10.5194/hess-2024-3...,None,NaN,None,prefix/primary_domain,2,None,"{""DOI"": ""10.5194/hess-2024-3989"", ""URL"": ""http...",10.5194/hess-2024-3989,10.5194,10.5194,hess-2024-3989,10.5194/hess-,10.5194/hess-,egusphere.copernicus.org,egusphere.copernicus.org/preprints

https://doi.org/10.5194/amt-2024-3967 it seems like when publish, the doi change to have the same patterns as the journal doi

In [71]:
EGUsphere_parent_df, EGUsphere_parent_summary = analyze_parent_data("EGUsphere", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: EGUSPHERE
=================================================================
  > Total Parent Groups:     10,181
  > Total Versions Found:    10,300
  > Unique Parent DOIs:      10,181
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EGUsphere:
-----------------------------------
  1 version(s):     10,069 groups
  2 version(s):     106 groups
  3 version(s):     5 groups
  4 version(s):     1 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EGUsphere                               10144
arXiv                                      20
Research Square                             6
Earth and Space Science Open Archive        3
EarthArXiv                                  3
ResearchGate                                1
SSRN                                        1
Preprints.org                               1
EGUsphere; arXiv                            1
Zenodo                                      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.5194/egusphere-    10178
10.5194/amt-              2
10.5194/hess-             1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
egusphere.copernicus.org          10180
oscar-egusphere.copernicus.org        1


=================================================================
 COMPLETED: EGUSPHERE
=================================================================

# Electron Colloquium Comput Complex

In [72]:
Electron_df, Electron_summary = get_server_data("Electron_Colloquium_Comput_Complex")

==================================================
 SERVER ANALYSIS: ELECTRON_COLLOQUIUM_COMPUT_COMPLEX
==================================================
  > Files found:    1
  > Raw records:    227
  > Cleaned shape:  (227, 90)
  > Unique DOIs:    0
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>    227
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
dblp.uni-trier.de      221
eccc.weizmann.ac.il      6
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None    227
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    227
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    227
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    227
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    227
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    227
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    227
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article    227
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    227
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ELECTRON_COLLOQUIUM_COMPUT_COMPLEX
==================================================

In [73]:
Electron_parent_df, Electron_parent_summary = analyze_parent_data("Electron Colloquium Comput Complex", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ELECTRON COLLOQUIUM COMPUT COMPLEX
=================================================================
  > Total Parent Groups:     139
  > Total Versions Found:    170
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Electron Colloquium Comput Complex:
-----------------------------------
  1 version(s):     109 groups
  2 version(s):     29 groups
  3 version(s):     1 groups

  Average versions per parent: 1.22

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Electron Colloquium Comput Complex    110
arXiv                                  29

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    139



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
dblp.uni-trier.de      134
eccc.weizmann.ac.il      5


=================================================================
 COMPLETED: ELECTRON COLLOQUIUM COMPUT COMPLEX
=================================================================

# eLife

In [74]:
elife_df, elife_summary = get_server_data("eLife")

==================================================
 SERVER ANALYSIS: ELIFE
==================================================
  > Files found:    2
  > Raw records:    29901
  > Cleaned shape:  (29901, 90)
  > Unique DOIs:    29901
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.7554/elife    29901
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
elifesciences.org    29901
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.7554    29901
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
4374    29901
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
eLife Sciences Publications, Ltd    29901
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
eLife    21412
None      8489
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None     28656
eLife     1245
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None     29876
elife       25
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2050-084X    21413
None          8488
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    21412
posted-content      8488
journal                1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None        21413
preprint     8488
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ELIFE
==================================================

In [75]:
elife_df[elife_df['type_backend_raw']=='journal-article']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.7554/elife.02516,eLife,crossref,10.7554/elife.02516,10.7554/elife.02516,https://doi.org/10.7554/elife.02516,http://elifesciences.org/lookup/doi/10.7554/eL...,http://elifesciences.org/lookup/doi/10.7554/eL...,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,Correction: A diversity of localized timescale...,None,None,None,en,journal-article,None,journal-article,None,False,2014-08-22,None,2014-08-22,2026-03-17,None,2014-02-18,None,2014-02-18,2014-02-18,2014.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/3.0/,http://creativecommons.org/licenses/by/3.0/,None,None,None,None,"Chaudhuri, Rishidev; Bernacchia, Alberto; Wang...",None,None,"[{""affiliation"": [], ""family"": ""Chaudhuri"", ""g...",None,None,None,None,NaN,None,None,None,18,None,None,18,0,None,None,,,False,None,,None,None,,None,None,None,issn,0,None,"{""DOI"": ""10.7554/elife.02516"", ""ISSN"": [""2050-...",10.7554/elife.02516,10.7554,10.7554,elife.02516,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/lookup
1,crossref::10.7554/elife.08172,eLife,crossref,10.7554/elife.08172,10.7554/elife.08172,https://doi.org/10.7554/elife.08172,http://elifesciences.org/content/4/e08127,http://elifesciences.org/content/4/e08127,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,The number of olfactory stimuli that humans ca...,None,None,None,None,journal-article,None,journal-article,None,False,2015-07-07,None,2015-07-07,2022-04-05,None,2015-07-07,None,2015-07-07,2015-07-07,2015.0,issued_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,None,None,issn,0,None,"{""DOI"": ""10.7554/elife.08172"", ""ISSN"": [""2050-...",10.7554/elife.08172,10.7554,10.7554,elife.08172,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/content
3,crossref::10.7554/elife.43558,eLife,crossref,10.7554/elife.43558,10.7554/elife.43558,https://doi.org/10.7554/elife.43558,https://elifesciences.org/articles/43558,https://elifesciences.org/articles/43558,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,Rapid task-dependent tuning of the mouse olfac...,None,None,None,en,journal-article,None,journal-article,None,False,2019-02-06,None,2019-02-06,2026-04-14,None,2019-02-06,None,2019-02-06,2019-02-06,2019.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Adapting neural representation to rapi...,Adapting neural representation to rapidly chan...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/43558/e...,"Koldaeva, Anzhelika; Schaefer, Andreas T; Fuku...","Sensory and Behavioural Neuroscience Unit, Oki...",None,"[{""affiliation"": [{""name"": ""Sensory and Behavi...",None,None,"[{""DOI"": ""10.13039/501100004199"", ""doi-asserte...",Okinawa Institute of Science and Technology Gr...,5.0,None,None,None,46,None,None,46,33,"[{""DOI"": ""10.1016/j.neuron.2004.11.017"", ""arti...","{""has-preprint"": [{""asserted-by"": ""object"", ""i...",10.1101/467530,,False,None,,None,None,,None,None,None,issn,0,None,"{""DOI"": ""10.7554/elife.43558"", ""ISSN"": [""2050-...",10.7554/elife.43558,10.7554,10.7554,elife.43558,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles
4,crossref::10.7554/elife.62018,eLife,crossref,10.7554/elife.62018,10.7554/elife.62018,https://doi.org/10.7554/elife.62018,https://elifesciences.org/articles/62018,https://elifesciences.org/articles/62018,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,Re-assessment of the involvement of Snord115 i...,None,None,None,en,journal-article,None,journal-article,None,False,2020-10-02,None,2020-10-02,2025-07-30,None,2020-10-02,None,2020-10-02,2020-10-02,2020.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p><jats:italic>SNORD115</jats:italic> ha...,SNORD115 has been proposed to promote the acti...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/62018/e...,"Hebras, Jade; Marty, Virginie; Personnaz, Jean...","LBME, CNRS, Toulouse, France; I2MC-U1048, Inse...",None,"[{""affiliation"": [{""name"": ""LBME, CNRS, Toulou...",None,None,"[{""name"": ""Fundation for Prader-Willi research...",Fundation for Prader-Willi research; Fondation...,3.0,None,None,None,1,None,None,1,0,None,"{""is-supplemented-by"": [{""asserted-by"": ""subje...",,,False,None,,None,None,,None,None,https://doi.org/10.7554/elife.62018,issn,0,None,"{""DOI"": ""10.7554/elife.62018"", ""ISSN"": [""2050-...",10.7554/elife.62018,10.7554,10.7554,elife.62018,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles
5,crossref::10.7554/elife.59046,eLife,crossref,10.7554/elife.59046,10.7554/elife.59046,https://doi.org/10.7554/elife.59046,https://elifesciences.org/articles/57974,https://elifesciences.org/articles/57974,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,Breaking antimicrobial resistance by disruptin...,None,None,None,en,journal-article,None,journal-article,None,False,2022-01-13,None,2022-01-14,2025-07-30,None,2022-01-13,None,2022-01-13,2022-01-13,2022.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Antimicrobial resistance in Gram-negat...,Antimicrobial resistance in Gram-negative bact...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/57974/e...,"Furniss, R Christopher D; Kaderabkova, Nikol; ...","Department of Life Sciences, Imperial College ...",None,"[{""affiliation"": [{""name"": ""Department of Life...",None,None,"[{""DOI"": ""10.13039/501100000265"", ""award"": [""M...",Medical Research Council; Swiss National Scien...,12.0,None,None,None,4,None,None,4,0,None,None,,,False,None,,None,None,,None,None,https://doi.org/10.7554/elife.59046,issn,0,None,"{""DOI"": ""10.7554/elife.59046"", ""ISSN"": [""2050-...",10.7554/elife.59046,10.7554,10.7554,elife.59046,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21408,crossref::10.7554/elife.96987,eLife,crossref,10.7554/elife.96987,10.7554/elife.96987,https://doi.org/10.7554/elife.96987,https://elifesciences.org/articles/96987,https://elifesciences.org/articles/96987,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,JAK-STAT pathway activation compromises nephro...,None,None,None,en,journal-article,None,journal-article,None,False,2024-05-01,None,2025-12-31,2026-03-07,None,2025-12-31,None,2025-12-31,2025-12-31,2025.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>\n Chronic kidney d...,Chronic kidney disease is a major health issue...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/96987/e...,"Zhao, Yunpo; Duan, Jianli; Seah, Hannah; van d...","Center for Precision Disease Modeling, Departm...",None,"[{""ORCID"": ""https://orcid.org/0000-0002-7942-3...",None,None,"[{""award"": [""R01-DK098410""], ""award-info"": [{""...",None,NaN,None,None,None,2,None,None,2,85,"[{""DOI"": ""10.20945/2359-3997000000149"", ""artic...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.1101/2024.03.07.583967,,False,None,10.7554/elife.96987.1;10.7554/elife.96987.2,None,None,,None,None,https://doi.org/10.7554/elife.96987,issn,0,None,"{""DOI"": ""10.7554/elife.96987"", ""ISSN"": [""2050-...",10.7554/elife.96987,10.7554,10.7554,elife.96987,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles
21409,crossref::10.7554/elife.96987.3,eLife,crossref,10.7554/elife.96987.3,10.7554/elife.96987.3,https://doi.org/10.7554/elife.96987.3,https://elifesciences.org/articles/96987,https://elifesciences.org/articles/96987,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,JAK-STAT pathway activation compromises nephro...,None,None,None,en,journal-article,None,journal-article,None,False,2025-12-17,None,2025-12-31,2026-02-28,None,2025-12-31,None,2025-12-31,2025-12-31,2025.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>\n Chronic kidney d...,Chronic kidney disease is a major health issue...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/96987/e...,"Zhao, Yunpo; Duan, Jianli; Seah, Hannah; van d...","Center for Precision Disease Modeling, Departm...",None,"[{""ORCID"": ""https://orcid.org/0000-0002-7942-3...",None,None,"[{""award"": [""R01-DK098410""], ""award-info"": [{""...",None,NaN,None,None,None,0,None,None,0,85,"[{""DOI"": ""10.20945/2359-3997000000149"", ""artic...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.1101/2024.03.07.583967,,False,None,10.7554/elife.96987.1;10.7554/elife.96987.2,None,None,10.7554/elife.96987.3.sa1;10.7554/elife.96987....,None,None,https://doi.org/10.7554/elife.96987.3,issn,0,None,"{""DOI"": ""10.7554/elife.96987.3"", ""ISSN"": [""205...",10.7554/elife.96987.3,10.7554,10.7554,elife.96987.3,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles
21410,crossref::10.7554/elife.106658.3,eLife,crossref,10.7554/elife.106658.3,10.7554/elife.106658.3,https://doi.org/10.7554/elife.106658.3,https://elifesciences.org/articles/106658,https://elifesciences.org/articles/106658,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,Coordinated spinal locomotor network dynamics ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-12-31,None,2025-12-31,2026-02-28,None,2025-12-31,None,2025-12-31,2025-12-31,2025.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Even without detailed instruction from...,Even without detailed instruction from the bra...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/106658/...,"Wandler, F David; Lemberger, Benjamin K; McLea...","Institute of Neuroscience, University of Orego...",None,"[{""affiliation"": [{""id"": [{""asserted-by"": ""pub...",None,None,"[{""award"": [""U01-NS136458""], ""award-info"": [{""...",None,NaN,None,None,None,0,None,None,0,55,"[{""DOI"": ""10.7554/eLife.94349.2"", ""article-tit...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.1101/2024.12.20.629829,,False,None,10.7554/elife.106658.1;10.7554/elife.106658.2,None,None,10.7554/elife.106658.3.sa4;10.7554/elife.10665...,None,None,https://doi.org/10.7554/elife.106658.3,issn,0,None,"{""DOI"": ""10.7554/elife.106658.3"", ""ISSN"": [""20...",10.7554/elife.106658.3,10.7554,10.7554,elife.106658.3,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles
21411,crossref::10.7554/elife.106658,eLife,crossref,10.7554/elife.106658,10.7554/elife.106658,https://doi.org/10.7554/elife.106658,https://elifesciences.org/articles/106658,https://elifesciences.org/articles/106658,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,Coordinated spinal locomotor network dynamics ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-06-06,None,2025-12-31,2025-12-31,None,2025-12-31,None,2025-12-31,2025-12-31,2025.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Even without detailed instruction from...,Even without detailed instruction from the bra...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/106658/...,"Wandler, F David; Lemberger, Benjamin K; McLea...","Institute of Neuroscience, University of Orego...",None,"[{""affiliation"": [{""id"": [{""asserted-by"": ""pub...",None,None,"[{""award"": [""U01-NS136458""], ""award-info"": [{""...",None,NaN,None,None,None,1,None,None,1,55,"[{""DOI"": ""10.7554/eLife.94349.2"", ""article-tit...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.1101/2024.12.20.629829,,False,None,10.7554/elife.106658.1;10.7554/elife.106658.2,None,None,,None,None,https://doi.org/10.7554/elife.106658,issn,0,None,"{""DOI"": ""10.7554/elife.106658"", ""ISSN"": [""2050...",10.7554/elife.106658,10.7554,10.7554,elife.106658,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles
21412,crossref::10.7554/elife.101496,eLife,crossref,10.7554/elife.101496,10.7554/elife.101496,https://doi.org/10.7554/elife.101496,https://elifesciences.org/articles/101496,https://elifesciences.org/articles/101496,10.7554,4374,None,None,crossref,"eLife Sciences Publications, Ltd",eLife,None,None,2050-084X,Specific proteolysis mediated by a p97-directe...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-25,None,2025-12-31,2026-02-28,None,2025-11-26,None,2025-11-26,2025-11-26,2025.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>\n The p97 protein ...,The p97 protein is a member of the AAA+ family...,"[{""URL"": ""https://cdn.elifesciences.org/articl...",https://cdn.elifesciences.org/articles/101496/...,"Salinas-Rebolledo, Constanza; Blesa, Javier; V...","Institute of Medicine, Faculty of Medicine, Un...",None,"[{""ORCID"": ""https://orcid.org/0000-0002-6220-5...",None,None,None,None,NaN,None,None,None,0,None,None,0,99,"[{""DOI"": ""10.1038/s41598-020-57938-3"", ""articl...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.1101/2024.03.08.584142,,False,None,,None,None,10.7554/elife.101496.sa2;10.7554/elife.101496....,None,None,https://doi.org/10.7554/elife.101496,issn,0,None,"{""DOI"": ""10.7554/elife.101496"", ""ISSN"": [""2050...",10.7554/elife.101496,10.7554,10.7554,elife.101496,10.7554/elife,10.7554/elife,elifesciences.org,elifesciences.org/articles

In [76]:
eLife_parent_df, eLife_parent_summary = analyze_parent_data("eLife", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ELIFE
=================================================================
  > Total Parent Groups:     9,439
  > Total Versions Found:    9,710
  > Unique Parent DOIs:      9,439
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for eLife:
-----------------------------------
  1 version(s):     9,183 groups
  2 version(s):     246 groups
  3 version(s):     7 groups
  4 version(s):     1 groups
  5 version(s):     2 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
eLife                                                                   9424
arXiv                                                                      7
medRxiv                                                                    1
Digital Access to Scholarship at Harvard (DASH) (Harvard University)       1
HAL; eLife                                                                 1
arXiv; eLife                                                               1
HAL                                                                        1
CrimRxiv                                                                   1
bioRxiv                                                                    1
Authorea Inc.                                                              1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.7554/elife    9439



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
elifesciences.org    9439


=================================================================
 COMPLETED: ELIFE
=================================================================

# ELPUB (Universitat Wuppertal)

In [77]:
ELPUB_df, ELPUB_summary = get_server_data("ELPUB_(Universitat_Wuppertal)")

==================================================
 SERVER ANALYSIS: ELPUB_(UNIVERSITAT_WUPPERTAL)
==================================================
  > Files found:    2
  > Raw records:    41
  > Cleaned shape:  (41, 90)
  > Unique DOIs:    41
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.25926/x          2
10.25926/7qdf       1
10.25926/wrn        1
10.25926/xdz        1
10.25926/cfrc-ad    1
10.25926/fjtg-wr    1
10.25926/fjdf-ae    1
10.25926/790c       1
10.25926/9bys       1
10.25926/2bhg       1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
elpub.bib.uni-wuppertal.de    41
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.25926    41
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    41
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
University of Wuppertal            39
Bergische Universität Wuppertal     2
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    41
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    41
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    41
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    41
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
JournalArticle    41
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None                    37
                         2
Accepted manuscript      1
accepted manuscript      1
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ELPUB_(UNIVERSITAT_WUPPERTAL)
==================================================

/tmp/ipykernel_3012/1196196344.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  raw_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)

In [78]:
ELPUB_parent_df, ELPUB_parent_summary = analyze_parent_data("ELPUB (Universitat Wuppertal)", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ELPUB (UNIVERSITAT WUPPERTAL)
=================================================================
  > Total Parent Groups:     41
  > Total Versions Found:    41
  > Unique Parent DOIs:      41
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ELPUB (Universitat Wuppertal):
-----------------------------------
  1 version(s):     41 groups

  Average versions per parent: 1.00

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ELPUB (Universitat Wuppertal)    41

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.25926/x          2
10.25926/0qp3       1
10.25926/nrcz-jr    1
10.25926/nf         1
10.25926/z          1
10.25926/pdf        1
10.25926/9k6n       1
10.25926/cfrc-ad    1
10.25926/hk         1
10.25926/ysd        1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
elpub.bib.uni-wuppertal.de    41


=================================================================
 COMPLETED: ELPUB (UNIVERSITAT WUPPERTAL)
=================================================================

# EmeRI

In [79]:
EmeRI_df, EmeRI_summary = get_server_data("EmeRI")

==================================================
 SERVER ANALYSIS: EMERI
==================================================
  > Files found:    1
  > Raw records:    8
  > Cleaned shape:  (8, 90)
  > Unique DOIs:    8
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.21452/15    6
10.21452/23    2
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.ibict.br    8
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.21452    8
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
8875    8
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
ABEC Publicacoes    8
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    8
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
EMERI    8
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Archival science, Museology\nInformation science, Library science    4
Psychology                                                           2
Information science, Library science                                 2
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    8
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    8
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    8
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR EMERI
==================================================

In [80]:
EmeRI_parent_df, EmeRI_parent_summary = analyze_parent_data("EmeRI", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: EMERI
=================================================================
  > Total Parent Groups:     8
  > Total Versions Found:    8
  > Unique Parent DOIs:      8
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EmeRI:
-----------------------------------
  1 version(s):     8 groups

  Average versions per parent: 1.00

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EmeRI    8

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.21452/15    6
10.21452/23    2



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.ibict.br    8


=================================================================
 COMPLETED: EMERI
=================================================================

# Encyclopedia

In [81]:
Encyclopedia_df, Encyclopedia_summary = get_server_data("Encyclopedia")

==================================================
 SERVER ANALYSIS: ENCYCLOPEDIA
==================================================
  > Files found:    1
  > Raw records:    166
  > Cleaned shape:  (166, 90)
  > Unique DOIs:    166
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.32545/encyclopedia    166
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
encyclopedia.pub    166
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.32545    166
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
1968    166
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
MDPI AG    166
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    166
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    166
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
MEDICINE &amp; PHARMACOLOGY           31
BIOLOGY &amp; LIFE SCIENCES           22
ENGINEERING                           22
MATERIALS SCIENCE                     17
MATHEMATICS &amp; COMPUTER SCIENCE     9
SOCIAL SCIENCES                        9
CHEMISTRY                              8
PHYSICAL SCIENCES                      7
EARTH SCIENCES                         5
BEHAVIORAL SCIENCES                    4
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    166
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    166
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    166
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ENCYCLOPEDIA
==================================================

In [82]:
Encyclopedia_parent_df, Encyclopedia_parent_summary = analyze_parent_data("Encyclopedia", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ENCYCLOPEDIA
=================================================================
  > Total Parent Groups:     161
  > Total Versions Found:    167
  > Unique Parent DOIs:      161
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Encyclopedia:
-----------------------------------
  1 version(s):     155 groups
  2 version(s):     6 groups

  Average versions per parent: 1.04

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Encyclopedia     160
Preprints.org      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.32545/encyclopedia    161



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
encyclopedia.pub    161


=================================================================
 COMPLETED: ENCYCLOPEDIA
=================================================================

# EnerarXiv

In [83]:
EnerarXiv_df, EnerarXiv_summary = get_server_data("EnerarXiv")

==================================================
 SERVER ANALYSIS: ENERARXIV
==================================================
  > Files found:    1
  > Raw records:    204
  > Cleaned shape:  (204, 90)
  > Unique DOIs:    204
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.46855/20    204
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
enerarxiv.org    204
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.46855    204
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
26239    204
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Applied Energy Innovation Institute (AEii)    204
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    204
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    204
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
RENEWABLE ENERGY                                 68
INTELLIGENT ENERGY SYSTEMS                       40
SUSTAINABILITY OF ENERGY SYSTEMS                 38
CLEAN ENERGY CONVERSION                          20
MITIGATION TECHNOLOGIES                          14
ENERGY STORAGE                                   13
ENERGY SHARING IN THE PEER-TO-PEER NETWORK        7
COVID-19: IMPACTS ON ENERGY &amp; ENVIRONMENT     2
CONFERENCE                                        2
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    204
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    204
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    204
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ENERARXIV
==================================================

In [84]:
EnerarXiv_parent_df, EnerarXiv_parent_summary = analyze_parent_data("EnerarXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ENERARXIV
=================================================================
  > Total Parent Groups:     191
  > Total Versions Found:    196
  > Unique Parent DOIs:      191
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for EnerarXiv:
-----------------------------------
  1 version(s):     187 groups
  2 version(s):     3 groups
  3 version(s):     1 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
EnerarXiv                  188
arXiv                        1
SSRN                         1
EnerarXiv; ResearchGate      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.46855/20    191



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
enerarxiv.org    191


=================================================================
 COMPLETED: ENERARXIV
=================================================================

# engrXiv

In [85]:
engrXiv_df, engrXiv_summary = get_server_data("engrXiv")

==================================================
 SERVER ANALYSIS: ENGRXIV
==================================================
  > Files found:    2
  > Raw records:    4929
  > Cleaned shape:  (4929, 90)
  > Unique DOIs:    4929
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31224/osf    1909
10.31224/43       85
10.31224/30       82
10.31224/36       81
10.31224/40       80
10.31224/34       80
10.31224/42       79
10.31224/31       78
10.31224/25       78
10.31224/38       77
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
engrxiv.org    4839
osf.io           90
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31224    4642
10.31219      73
10.31234      68
10.31227      53
10.31235      39
10.31228      26
10.31223       9
10.31230       6
10.31220       5
10.31225       4
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
33966    4621
15934     294
29705       9
242         5
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Open Engineering Inc                4621
Center for Open Science              294
California Digital Library (CDL)       9
CABI Publishing                        5
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    4929
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    4929
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None       2767
engrXiv    2162
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    4929
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    4929
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    4929
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ENGRXIV
==================================================

In [86]:
engrXiv_parent_df, engrXiv_parent_summary = analyze_parent_data("engrXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ENGRXIV
=================================================================
  > Total Parent Groups:     4,519
  > Total Versions Found:    5,028
  > Unique Parent DOIs:      4,519
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for engrXiv:
-----------------------------------
  1 version(s):     4,077 groups
  2 version(s):     394 groups
  3 version(s):     37 groups
  4 version(s):     6 groups
  5 version(s):     3 groups
  6 version(s):     1 groups
  7 version(s):     1 groups

  Average versions per parent: 1.11

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
engrXiv                            4238
Open Science Framework               66
SSRN                                 48
Open Science Framework; engrXiv      41
arXiv                                26
TechRxiv                             24
arXiv; engrXiv                       16
Preprints.org                        12
Research Square                      11
ResearchGate; engrXiv                 8

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31224/osf    2067
10.31224/43       76
10.31224/30       75
10.31224/34       75
10.31224/40       74
10.31224/33       73
10.31224/26       72
10.31224/36       72
10.31224/25       72
10.31224/22       70



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
engrxiv.org    4433
osf.io           86


=================================================================
 COMPLETED: ENGRXIV
=================================================================

# F1000Research

In [87]:
F1000Research_df, F1000Research_summary = get_server_data("F1000Research")

==================================================
 SERVER ANALYSIS: F1000RESEARCH
==================================================
  > Files found:    1
  > Raw records:    16873
  > Cleaned shape:  (16873, 90)
  > Unique DOIs:    16873
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/f      16859
10.3410/f           7
<NA>                4
10.3410/10          1
10.3410/12          1
10.3410/http        1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
f1000research.com        16867
                             2
someurl.com                  2
xy.net                       1
researchdev.f1000.com        1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    16863
10.3410        10
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    16863
4950       10
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd      16863
Faculty Opinions Ltd        9
H1 Connect                  1
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
F1000Research     16831
f1000research        23
F1000 Research       10
F1000research         6
None                  3
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    16873
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    16873
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2046-1402    16873
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    16870
journal                3
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    16873
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR F1000RESEARCH
==================================================

In [88]:
F1000Research_parent_df, F1000Research_parent_summary = analyze_parent_data("F1000Research", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: F1000RESEARCH
=================================================================
  > Total Parent Groups:     10,640
  > Total Versions Found:    16,273
  > Unique Parent DOIs:      10,640
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for F1000Research:
-----------------------------------
  1 version(s):     6,408 groups
  2 version(s):     3,177 groups
  3 version(s):     812 groups
  4 version(s):     176 groups
  5 version(s):     48 groups
  6 version(s):     10 groups
  7 version(s):     5 groups
  8 version(s):     2 groups
  9 version(s):     1 groups
  11 version(s):    1 groups

  Average versions per parent: 1.53

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
F1000Research           10622
F1000Research; arXiv        4
ResearchGate                3
SSRN                        2
arXiv                       2
Research Square             2
searchRxiv                  1
Authorea Inc.               1
F1000Research; SSRN         1
bioRxiv                     1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/f    10638
10.3410/f         2



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
f1000research.com    10640


=================================================================
 COMPLETED: F1000RESEARCH
=================================================================

# FocUS Archive

In [89]:
FocUS_df, FocUS_summary = get_server_data("FocUS_Archive")

==================================================
 SERVER ANALYSIS: FOCUS_ARCHIVE
==================================================
  > Files found:    1
  > Raw records:    83
  > Cleaned shape:  (83, 90)
  > Unique DOIs:    83
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31225/osf    70
10.31227/osf     9
10.31219/osf     3
10.31234/osf     1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    83
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31225    70
10.31227     9
10.31219     3
10.31234     1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    83
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    83
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    83
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    83
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
FocUS Archive    83
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    83
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    83
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    83
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR FOCUS_ARCHIVE
==================================================

In [90]:
FocUS_parent_df, FocUS_parent_summary = analyze_parent_data("FocUS Archive", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: FOCUS ARCHIVE
=================================================================
  > Total Parent Groups:     79
  > Total Versions Found:    119
  > Unique Parent DOIs:      79
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for FocUS Archive:
-----------------------------------
  1 version(s):     43 groups
  2 version(s):     34 groups
  3 version(s):     1 groups
  5 version(s):     1 groups

  Average versions per parent: 1.51

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
FocUS Archive                            43
FocUS Archive; Open Science Framework    36

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31225/osf    79



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    79


=================================================================
 COMPLETED: FOCUS ARCHIVE
=================================================================

# Frenxiv

In [91]:
Frenxiv_df, Frenxiv_summary = get_server_data("Frenxiv")

==================================================
 SERVER ANALYSIS: FRENXIV
==================================================
  > Files found:    1
  > Raw records:    179
  > Cleaned shape:  (179, 90)
  > Unique DOIs:    179
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31226/osf    178
10.31227/osf      1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    179
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31226    178
10.31227      1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    179
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    179
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    179
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    179
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Frenxiv    179
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    179
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    179
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    179
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR FRENXIV
==================================================

In [92]:
Frenxiv_parent_df, Frenxiv_parent_summary = analyze_parent_data("Frenxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: FRENXIV
=================================================================
  > Total Parent Groups:     102
  > Total Versions Found:    116
  > Unique Parent DOIs:      102
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Frenxiv:
-----------------------------------
  1 version(s):     88 groups
  2 version(s):     14 groups

  Average versions per parent: 1.14

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Frenxiv                   94
SSRN                       4
Open Science Framework     2
Frenxiv; ResearchGate      1
EdArXiv                    1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31226/osf    102



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    102


=================================================================
 COMPLETED: FRENXIV
=================================================================

# Gates Open Research

In [93]:
Gates_df, Gates_summary = get_server_data("Gates_Open_Research")

==================================================
 SERVER ANALYSIS: GATES_OPEN_RESEARCH
==================================================
  > Files found:    1
  > Raw records:    863
  > Cleaned shape:  (863, 90)
  > Unique DOIs:    863
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/gatesopenres    863
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
gatesopenresearch.org    863
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    863
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    863
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    863
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
Gates Open Research    862
None                     1
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    863
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    863
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2572-4754    863
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    862
journal              1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    863
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR GATES_OPEN_RESEARCH
==================================================

In [94]:
Gates_parent_df, Gates_parent_summary = analyze_parent_data("Gates Open Research", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: GATES OPEN RESEARCH
=================================================================
  > Total Parent Groups:     502
  > Total Versions Found:    817
  > Unique Parent DOIs:      502
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Gates Open Research:
-----------------------------------
  1 version(s):     236 groups
  2 version(s):     222 groups
  3 version(s):     39 groups
  4 version(s):     5 groups

  Average versions per parent: 1.63

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Gates Open Research    501
VeriXiv                  1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/gatesopenres    502



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
gatesopenresearch.org    502


=================================================================
 COMPLETED: GATES OPEN RESEARCH
=================================================================

In [95]:
Gates_parent_df

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
24274,crossref::10.12688/gatesopenres.13123.1,crossref::10.12688/gatesopenres.13123.1,Gates Open Research,10.12688/gatesopenres.13123.1,https://gatesopenresearch.org/articles/4-71/v1,Introducing a drift and diffusion framework fo...,"Lewis, Fraser I; Guga, Godfrey; Mdoe, Paschal;...",2020-06-29,2020,crossref::10.12688/gatesopenres.13123.1; cross...,10.12688/gatesopenres.13123.1; 10.12688/gateso...,Gates Open Research (2),2,2020-06-29,2020-11-26,Gates Open Research,10.12688/gatesopenres.13123.1,10.12688,10.12688,gatesopenres.13123.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
39601,crossref::10.12688/gatesopenres.13457.1,crossref::10.12688/gatesopenres.13457.1,Gates Open Research,10.12688/gatesopenres.13457.1,https://gatesopenresearch.org/articles/5-174/v1,A Randomized controlled trial of the Effect of...,"Harding, Rebecca; Ataide, Ricardo; Mwangi, Mar...",2021-12-07,2021,crossref::10.12688/gatesopenres.13457.1; cross...,10.12688/gatesopenres.13457.1; 10.12688/gateso...,Gates Open Research (2),2,2021-12-07,2022-04-14,Gates Open Research,10.12688/gatesopenres.13457.1,10.12688,10.12688,gatesopenres.13457.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
61653,crossref::10.12688/gatesopenres.12799.2,crossref::10.12688/gatesopenres.12799.2,Gates Open Research,10.12688/gatesopenres.12799.2,https://gatesopenresearch.org/articles/2-13/v2,A sulfur-free peptide mimic of surfactant prot...,"Walther, Frans J.; Gupta, Monik; Gordon, Larry...",2018-07-10,2018,crossref::10.12688/gatesopenres.12799.2,10.12688/gatesopenres.12799.2,Gates Open Research (1),1,2018-07-10,2018-07-10,Gates Open Research,10.12688/gatesopenres.12799.2,10.12688,10.12688,gatesopenres.12799.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
68519,crossref::10.12688/gatesopenres.14591.1,crossref::10.12688/gatesopenres.14591.1,Gates Open Research,10.12688/gatesopenres.14591.1,https://gatesopenresearch.org/articles/7-75/v1,Using responsive feedback from routine monitor...,"Meekers, Dominique; Olutola, Olaniyi; Abu Turk...",2023-05-19,2023,crossref::10.12688/gatesopenres.14591.1; cross...,10.12688/gatesopenres.14591.1; 10.12688/gateso...,Gates Open Research (2),2,2023-05-19,2023-11-16,Gates Open Research,10.12688/gatesopenres.14591.1,10.12688,10.12688,gatesopenres.14591.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
75609,crossref::10.12688/gatesopenres.12854.1,crossref::10.12688/gatesopenres.12854.1,Gates Open Research,10.12688/gatesopenres.12854.1,https://gatesopenresearch.org/articles/2-38/v1,Evaluation of a multi-level intervention to im...,"Ingabire, Rosine; Nyombayire, Julien; Hoagland...",2018-08-20,2018,crossref::10.12688/gatesopenres.12854.1; cross...,10.12688/gatesopenres.12854.1; 10.12688/gateso...,Gates Open Research (3),3,2018-08-20,2019-02-04,Gates Open Research,10.12688/gatesopenres.12854.1,10.12688,10.12688,gatesopenres.12854.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7265036,crossref::10.12688/gatesopenres.12954.1,crossref::10.12688/gatesopenres.12954.1,Gates Open Research,10.12688/gatesopenres.12954.1,https://gatesopenresearch.org/articles/3-1466/v1,"Knowledge, perception and experience of sexual...","Sule, Aisha I.; Titiloye, Musibau A.; Arulogun...",2019-05-15,2019,crossref::10.12688/gatesopenres.12954.1,10.12688/gatesopenres.12954.1,Gates Open Research (1),1,2019-05-15,2019-05-15,Gates Open Research,10.12688/gatesopenres.12954.1,10.12688,10.12688,gatesopenres.12954.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
7286719,crossref::10.12688/gatesopenres.13184.1,crossref::10.12688/gatesopenres.13184.1,Gates Open Research,10.12688/gatesopenres.13184.1,https://gatesopenresearch.org/articles/4-158/v1,Using developmental evaluation to implement an...,"Fogarty, Linda; Musau, Abednego; Kabue, Mark; ...",2020-10-15,2020,crossref::10.12688/gatesopenres.13184.1,10.12688/gatesopenres.13184.1,Gates Open Research (1),1,2020-10-15,2020-10-15,Gates Open Research,10.12688/gatesopenres.13184.1,10.12688,10.12688,gatesopenres.13184.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
7297717,crossref::10.12688/gatesopenres.13654.1,crossref::10.12688/gatesopenres.13654.1,Gates Open Research,10.12688/gatesopenres.13654.1,https://gatesopenresearch.org/articles/6-117/v1,Higher mortality associated with the SARS-CoV-...,"Hussey, Hannah; Davies, Mary-Ann; Heekes, Alex...",2022-08-31,2022,crossref::10.12688/gatesopenres.13654.1,10.12688/gatesopenres.13654.1,Gates Open Research (1),1,2022-08-31,2022-08-31,Gates Open Research,10.12688/gatesopenres.13654.1,10.12688,10.12688,gatesopenres.13654.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
7314338,crossref::10.12688/gatesopenres.15270.1,crossref::10.12688/gatesopenres.15270.1,Gates Open Research,10.12688/gatesopenres.15270.1,https://gatesopenresearch.org/articles/8-17/v1,Methods employed in a 2021 population-based se...,"Hossain, Md Shajib; Ali, Asma; Clary, Caitlin ...",2024-03-01,2024,crossref::10.12688/gatesopenres.15270.1,10.12688/gatesopenres.15270.1,Gates Open Research (1),1,2024-03-01,2024-03-01,Gates Open Research,10.12688/gatesopenres.15270.1,10.12688,10.12688,gatesopenres.15270.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
7346865,crossref::10.12688/gatesopenres.13459.1,crossref::10.12688/gatesopenres.13459.1,Gates Open Research,10.12688/gatesopenres.13459.1,https://gatesopenresearch.org/articles/5-179/v1,The impact of ear growth on identification rat...,"Simukanga, Alinani; Kobayashi, Misaki; Etter, ...",2021-12-15,2021,crossref::10.12688/gatesopenres.13459.1,10.12688/gatesopenres.13459.1,Gates Open Research (1),1,2021-12-15,2021-12-15,Gates Open Research,10.12688/gatesopenres.13459.1,10.12688,10.12688,gatesopenres.13459.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [96]:
Gates_parent_df[Gates_parent_df['most_recent_version_servers']=='VeriXiv']

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
7235707,crossref::10.12688/gatesopenres.16360.1,crossref::10.12688/gatesopenres.16360.1,Gates Open Research,10.12688/gatesopenres.16360.1,https://gatesopenresearch.org/articles/9-65/v1,Driving innovation from discovery to access: M...,"Palmer, Shaun; Clark, Rebecca A.; Connell, Bri...",2025-01-01,2025,crossref::10.12688/gatesopenres.16360.1; cross...,10.12688/gatesopenres.16360.1; 10.12688/verixi...,Gates Open Research (1); VeriXiv (1),2,2025-01-01,2025-05-23,VeriXiv,10.12688/gatesopenres.16360.1,10.12688,10.12688,gatesopenres.16360.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [97]:
Gates_df.drop_duplicates('record_id')

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.12688/gatesopenres.12803.2,Gates Open Research,crossref,10.12688/gatesopenres.12803.2,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.12803.2,https://gatesopenresearch.org/articles/2-11/v2,https://gatesopenresearch.org/articles/2-11/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-12,None,2018-07-12,2025-02-21,None,2018-07-12,None,2018-07-12,2018-07-12,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,2,None,None,2,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12803.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.2"", ""ISSN...",10.12688/gatesopenres.12803.2,10.12688,10.12688,gatesopenres.12803.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
1,crossref::10.12688/gatesopenres.12803.1,Gates Open Research,crossref,10.12688/gatesopenres.12803.1,10.12688/gatesopenres.12803.1,https://doi.org/10.12688/gatesopenres.12803.1,https://gatesopenresearch.org/articles/2-11/v1,https://gatesopenresearch.org/articles/2-11/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-02-22,None,2018-07-12,2025-02-21,None,2018-02-22,None,2018-02-22,2018-02-22,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,3,None,None,3,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13867.r26331;10.21956/ga...,None,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.1"", ""ISSN...",10.12688/gatesopenres.12803.1,10.12688,10.12688,gatesopenres.12803.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
2,crossref::10.12688/gatesopenres.12816.1,Gates Open Research,crossref,10.12688/gatesopenres.12816.1,10.12688/gatesopenres.12816.1,https://doi.org/10.12688/gatesopenres.12816.1,https://gatesopenresearch.org/articles/2-24/v1,https://gatesopenresearch.org/articles/2-24/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-04-26,None,2018-07-19,2025-02-21,None,2018-04-26,None,2018-04-26,2018-04-26,2018.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/3.0/igo/,https://creativecommons.org/licenses/by/3.0/igo/,<ns4:p><ns4:bold>Background</ns4:bold>: the Po...,Background : the Portfolio-To-Impact (P2I) mod...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""award"": [""OPP1151682""], ""award-info"": [{""aw...",Bill and Melinda Gates Foundation; Swiss Agenc...,3.0,None,None,None,2,None,None,2,15,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13883.r26392;10.21956/ga...,None,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.1"", ""ISSN...",10.12688/gatesopenres.12816.1,10.12688,10.12688,gatesopenres.12816.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
3,crossref::10.12688/gatesopenres.12816.2,Gates Open Research,crossref,10.12688/gatesopenres.12816.2,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.12816.2,https://gatesopenresearch.org/articles/2-24/v2,https://gatesopenresearch.org/articles/2-24/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-19,None,2018-07-20,2025-11-01,None,2018-07-19,None,2018-07-19,2018-07-19,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background: </ns4:bold>The Po...,Background: The Portfolio-To-Impact (P2I) Mode...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""name"": ""The Special Programme for Research ...",The Special Programme for Research and Trainin...,3.0,None,None,None,17,None,None,17,16,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13921.r26569,"[{""DOI"": ""10.12688/gatesopenres.12816.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.2"", ""ISSN...",10.12688/gatesopenres.12816.2,10.12688,10.12688,gatesopenres.12816.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
4,crossref::10.12688/gatesopenres.12832.2,Gates Open Research,crossref,10.12688/gatesopenres.12832.2,10.12688/gatesopenres.12832.2,https://doi.org/10.12688/gatesopenres.12832.2,https://gatesopenresearch.org/articles/2-31/v2,https://gatesopenresearch.org/articles/2-31/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"DataPackageR: Reproducible data preprocessing,...",None,None,None,en,journal-article,None,journal-article,None,False,2018-07-10,None,2018-07-24,2025-11-21,None,2018-07-10,None,2018-07-10,2018-07-10,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n A central tenet o...,A central tenet of reproducible research is th...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Finak, Greg; Mayer, Bryan; Fulp, William; Obre...",None,None,"[{""affiliation"": [], ""family"": ""Finak"", ""given...",None,None,"[{""DOI"": ""10.13039/100000057"", ""award"": [""R01 ...",National Institute of General Medical Sciences...,2.0,None,None,None,3,None,None,3,39,"[{""DOI"": ""10.1373/clinchem.2010.158618"", ""arti...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13917.r26579;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12832.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12832.2"", ""ISSN...",10.12688/gatesopenres.12832.2,10.12688,10.12688,gatesopenres.12832.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,crossref::10.12688/gatesopenres.16362.1,Gates Open Research,crossref,10.12688/gatesopenres.16362.1,10.12688/gatesopenres.16362.1,https://doi.org/10.12688/gatesopenres.16362.1,https://gatesopenresearch.org/articles/9-69/v1,https://gatesopenresearch.org/articles/9-69/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Mycobacterium tuberculosis growth inhibition b...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-09-09,None,2025-09-09,2025-09-09,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background There ...,Background There is a concern that SARS-CoV-2 ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-69/v1...,"Shaw, Jane A; Petersen, Caleb; Hiemstra, Andri...",None,None,"[{""affiliation"": [], ""family"": ""Shaw"", ""given""...",None,None,"[{""DOI"": ""10.13039/100000060"", ""award"": [""75N9...",National Institute of Allergy and Infectious D...,3.0,None,None,None,0,None,None,0,44,"[{""DOI"": ""10.1056/NEJMoa2119658"", ""article-tit...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.514.3,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16362.1"", ""ISSN...",10.12688/gatesopenres.16362.1,10.12688,10.12688,gatesopenres.16362.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
859,crossref::10.12688/gatesopenres.16361.1,Gates Open Research,crossref,10.12688/gatesopenres.16361.1,10.12688/gatesopenres.16361.1,https://doi.org/10.12688/gatesopenres.16361.1,https://gatesopenresearch.org/articles/9-64/v1,https://gatesopenresearch.org/articles/9-64/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Maximising power with the minimum number of mo...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-08-27,None,2025-08-27,2025-08-27,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Power calculations are an essential com...,Power calculations are an essential component ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-64/v1...,"Harvey, Gemma Francesca; Mechan, Frank; Prauli...",None,None,"[{""ORCID"": ""https://orcid.org/0009-0008-6041-3...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,13,"[{""DOI"": ""10.1038/nature15535"", ""article-title...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.953.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16361.1"", ""ISSN...",10.12688/gatesopenres.16361.1,10.12688,10.12688,gatesopenres.16361.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
860,crossref::10.12688/gatesopenres.15431.1,Gates Open Research,crossref,10.12688/gatesopenres.15431.1,10.12688/gatesopenres.15431.1,https://doi.org/10.12688/gatesopenres.15431.1,https://gatesopenresearch.org/articles/9-7/v1,https://gatesopenresearch.org/articles/9-7/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A new application programming interface (API) ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-03-11,None,2025-11-21,2025-11-21,None,2025-03-11,None,2025-03-11,2025-03-11,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background The escalating threat of AMR...,Background The escalating threat of AMR demand...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-7/v1/pdf,"Pillonetto, Marcelo; Kraft, Leticia; Ellen, St...",None,None,"[{""affiliation"": [], ""family"": ""Pillonetto"", ""...",None,None,"[{""award"": [""51618.554.31977.10122018""], ""awar...",Programa grand challenges explorations-brazil:...,1.0,None,None,None,0,None,None,0,19,"[{""article-title"": ""Usability and feasibility ...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16783.r39769;10.21956/ga...,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15431.1"", ""ISSN...",10.12688/gatesopenres.15431.1,10.12688,10.12688,gatesopenres.15431.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
861,crossref::10.12688/gatesopenres,Gates Open Research,crossref,10.12688/gatesopenres,10.12688/gatesopenres,https://doi.org/10.12688/gatesopenres,http://www.gatesopenresearch.org,http://www.gatesopenresearch.org,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,None,2572-4754,Gates Open Research,None,Gates Open Res,None,en,journal,None,journal,None,False,2017-11-06,None,2025-12-17,2025-12-17,None,None,None,None,None,NaN,created_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,13,None,None,13,0,None,None,,,False,None,,None,None,,None,None,None,issn,49,None,"{""DOI"": ""10.12688/gatesopenres"", ""ISSN"": [""257...",10.12688/gatesopenres,10.12688,10.12688,gatesopenres,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org
862,crossref::10.12688/gatesopenres.15991.2,Gates Open Research,crossref,10.12688/gatesopenres.15991.2,10.12688/gatesopenres.15991.2,https://doi.org/10.12688/gatesopenres.15991.2,https://gatesopenresearch.org/articles/8-95/v2,https://gatesopenresearch.org/articles/8-95/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"Single-blinded, stratified, dose ranging trial...",None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-12-17,2025-12-17,None,2025-09-17,None,2025-09-17,2025-09-17,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background Vitami...,Background Vitamin B12 is an essential cofacto...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-95/v2...,"Lweno, Omar; Reynolds, Victoria S.; Barberio, ...",None,None,"[{""affiliation"": [], ""family"": ""Lweno"", ""given...",None,None,"[{""award"": [""INV-016930""], ""award-info"": [{""aw...",Gates Foundation,1.0,None,None,None,0,None,None,0,37,"[{""DOI"": ""10.1093/jn/nxy201"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,10.12688/gatesopenres.15991.1,None,New version,10.21956/gatesopenres.17759.r39860,"[{""DOI"": ""10.12688/gatesopenres.15991.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15991.2"", ""ISSN...",10.12688/gatesopenres.15991.2,10.12688,10.12688,gatesopenres.15991.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [98]:
dup_ti = Gates_df.drop_duplicates('title')

In [99]:
duplicates = dup_ti[dup_ti.duplicated('authors_flat')].sort_values(by='authors_flat')
print(len(duplicates))
duplicates

43

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
128,crossref::10.12688/gatesopenres.12755.1,Gates Open Research,crossref,10.12688/gatesopenres.12755.1,10.12688/gatesopenres.12755.1,https://doi.org/10.12688/gatesopenres.12755.1,https://gatesopenresearch.org/articles/1-6/v1,https://gatesopenresearch.org/articles/1-6/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Evaluating integrated development: are we aski...,None,None,None,en,journal-article,None,journal-article,None,False,2017-11-06,None,2019-10-10,2025-11-16,None,2017-11-06,None,2017-11-06,2017-11-06,2017.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> Emergi...,Background: Emerging global transformations - ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/1-6/v1/pdf,"Ahner-McHaffie, Tessa W; Guest, Greg; Petruney...",None,None,"[{""affiliation"": [], ""family"": ""Ahner-McHaffie...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation; FHI Foundation,2.0,None,None,None,2,None,None,2,32,"[{""DOI"": ""10.1136/bmj.g5785"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13815.r26084;10.21956/ga...,None,10.12688/gatesopenres.12755.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12755.1"", ""ISSN...",10.12688/gatesopenres.12755.1,10.12688,10.12688,gatesopenres.12755.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
245,crossref::10.12688/gatesopenres.12870.2,Gates Open Research,crossref,10.12688/gatesopenres.12870.2,10.12688/gatesopenres.12870.2,https://doi.org/10.12688/gatesopenres.12870.2,https://gatesopenresearch.org/articles/2-52/v2,https://gatesopenresearch.org/articles/2-52/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Characterization of fecal sludge as biomass fe...,None,None,None,en,journal-article,None,journal-article,None,False,2020-01-24,None,2020-07-23,2025-06-13,None,2020-01-24,None,2020-01-24,2020-01-24,2020.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns5:p><ns5:bold>Background</ns5:bold>: Transf...,Background : Transformative sanitation technol...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/2-52/v2...,"Barani, Viswa; Hegarty-Craver, Meghan; Rosario...",None,None,"[{""affiliation"": [], ""family"": ""Barani"", ""give...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""4395...",Bill and Melinda Gates Foundation,1.0,None,None,None,3,None,None,3,22,"[{""DOI"": ""10.1016/j.energy.2017.06.010"", ""arti...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.14273.r28501;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12870.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12870.2"", ""ISSN...",10.12688/gatesopenres.12870.2,10.12688,10.12688,gatesopenres.12870.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
250,crossref::10.12688/gatesopenres.12902.3,Gates Open Research,crossref,10.12688/gatesopenres.12902.3,10.12688/gatesopenres.12902.3,https://doi.org/10.12688/gatesopenres.12902.3,https://gatesopenresearch.org/articles/3-7/v3,https://gatesopenresearch.org/articles/3-7/v3,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Knowledge and factors influencing long-acting ...,None,None,None,en,journal-article,None,journal-article,None,False,2020-05-20,None,2020-07-30,2025-09-09,None,2020-05-20,None,2020-05-20,2020-05-20,2020.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns5:p><ns5:bold>Background:</ns5:bold> Approx...,Background: Approximately 48% of unintended pr...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/3-7/v3/pdf,"Bolarinwa, Obasanjo Afolabi; Olagunju, Olaleka...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-9208-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,7,None,None,7,28,"[{""article-title"": ""Adolescents and Long-Actin...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.14330.r28863;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12902.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12902.3"", ""ISSN...",10.12688/gatesopenres.12902.3,10.12688,10.12688,gatesopenres.12902.3,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
812,crossref::10.12688/gatesopenres.15078.3,Gates Open Research,crossref,10.12688/gatesopenres.15078.3,10.12688/gatesopenres.15078.3,https://doi.org/10.12688/gatesopenres.15078.3,https://gatesopenresearch.org/articles/8-1/v3,https://gatesopenresearch.org/articles/8-1/v3,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Toward person-centred measures of contraceptiv...,None,None,None,en,journal-article,None,journal-article,None,False,2025-02-28,None,2025-02-28,2025-02-28,None,2025-02-28,None,2025-02-28,2025-02-28,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns4:p>Background Understanding people’s inter...,Background Understanding people’s interest in ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-1/v3/pdf,"Boydell, Victoria; Wright, Kelsey Quinn; Elnak...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0001-5051-9...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,0,None,None,0,36,"[{""DOI"": ""10.2307/2134309"", ""article-title"": ""...","{""has-version"": [{""asserted-by"": ""subject"", ""i...",,,False,None,10.12688/gatesopenres.15078.2;10.12688/gatesop...,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.15078.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15078.3"", ""ISSN...",10.12688/gatesopenres.15078.3,10.12688,10.12688,gatesopenres.15078.3,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
811,crossref::10.12688/gatesopenres.15078.1,Gates Open Research,crossref,10.12688/gatesopenres.15078.1,10.12688/gatesopenres.15078.1,https://doi.org/10.12688/gatesopenres.15078.1,https://gatesopenresearch.org/articles/8-1/v1,https://gatesopenresearch.org/articles/8-1/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Toward person-centred measures of contraceptiv...,None,None,None,en,journal-article,None,journal-article,None,False,2024-01-03,None,2025-02-28,2025-11-21,None,2024-01-03,None,2024-01-03,2024-01-03,2024.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns4:p>Background Understanding people’s motiv...,Background Understanding people’s motivation a...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-1/v1/pdf,"Boydell, Victoria; Wright, Kelsey Quinn; Elnak...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0001-5051-9...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,1,None,None,1,37,"[{""DOI"": ""10.2307/2134309"", ""article-title"": ""...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16413.r36251;10.21956/ga...,None,10.12688/gatesopenres.15078.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15078.1"", ""ISSN...",10.12688/gatesopenres.15078.1,10.12688,10.12688,gatesopenres.15078.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
723,crossref::10.12688/gatesopenres.14590.2,Gates Open Research,crossref,10.12688/gatesopenres.14590.2,10.12688/gatesopenres.14590.2,https://doi.org/10.12688/gatesopenres.14590.2,https://gatesopenresearch.org/articles/7-61/v2,https://gatesopenresearch.org/articles/7-61/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Contraceptive access and use before and during...,None,None,None,en,journal-article,None,journal-article,None,False,2024-07-18,None,2024-07-27,2025-09-20,None,2024-07-18,None,2024-07-18,2024-07-18,2024.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p>Background The COVID-19 pandemic affect...,Background The COVID-19 pandemic affected glob...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/7-61/v2...,"Callahan, Rebecca L.; Cartwright, Alice F.; Be...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0001-5808-0...",None,None,"[{""DOI"": ""10.13039/501100001322"", ""doi-asserte...",South African Medical Research Council; United...,4.0,None,None,None,2,None,None,2,24,"[{""DOI"": ""10.1136/bmjopen-2022-070085"", ""artic...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,10.12688/gatesopenres.14590.1,None,New version,10.21956/gatesopenres.17563.r37482,"[{""DOI"": ""10.12688/gatesopenres.14590.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.14590.2"", ""ISSN...",10.12688/gatesopenres.14590.2,10.12688,10.12688,gatesopenres.14590.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
130,crossref::10.12688/gatesopenres.12759.1,Gates Open Research,crossref,10.12688/gatesopenres.12759.1,10.12688/gatesopenres.12759.1,https://doi.org/10.12688/gatesopenres.12759.1,https://gatesopenresearch.org/articles/1-2/v1,https://gatesopenresearch.org/articles/1-2/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Air sampling during flow cytometric analysis o...,None,None,None,en,journal-article,None,journal-article,None,False,2017-11-06,None,2019-10-10,2025-02-21,None,2017-11-06,None,2017-11-06,2017-11-06,2017.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>This study investigated airborne bacter...,This study investigated airborne bacteria in a...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/1-2/v1/pdf,"Carson, Christine F; Inglis, Timothy JJ",None,None,"[{""affiliation"": [], ""family"": ""Carson"", ""give...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation; Department ...,3.0,None,None,None,1,None,None,1,17,"[{""DOI"": ""10.1177/25.7.330729"", ""article-title...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13819.r26113;10.21956/ga...,None,10.12688/gatesopenres.12759.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12759.1"", ""ISSN...",10.12688/gatesopenres.12759.1,10.12688,10.12688,gatesopenres.12759.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
187,crossref::10.12688/gatesopenres.12935.2,Gates Open Research,crossref,10.12688/gatesopenres.12935.2,10.12688/gatesopenres.12935.2,https://doi.org/10.12688/gatesopenres.12935.2,https://gatesopenresearch.org/articles/3-1092/v2,https://gatesopenresearch.org/articles/3-1092/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Comparing simulated client experiences with ph...,None,None,None,en,journal-article,None,journal-article,None,False,2019-12-18,None,2020-02-10,2025-02-21,None,2019-12-18,None,2019-12-18,2019-12-18,2019.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background</ns4:bold>: The qu...,Background : The quality of family planning se...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/3-1092/...,"Diamond-Smith, Nadia; Treleaven, Emily; Omolua...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8711-3...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation; Children's ...,2.0,None,None,None,1,None,None,1,20,"[{""DOI"": ""10.1111/j.1728-4465.2003.00227.x"", ""...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.14249.r28389;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12935.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12935.2"", ""ISSN...",10.12688/gatesopenres.12935.2,10.12688,10.12688,gatesopenres.12935.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
781,crossref::10.12688/gatesopenres.15189.1,Gates Open Research,crossref,10.12688/gatesopenres.15189.1,10.12688/gatesopenres.15189.1,https://doi.org/10.12688/gatesopenres.15189.1,https://gatesopenresearch.org/articles/8-18/v1,https://gatesopenresearch.org/articles/8-18/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Developing a framework for understanding polic...,None,None,None,en,journal-article,None,journal-article,None,False,2024-03-01,None,2024-12-04,2025-11-21,None,2024-03-01,None,2024-03-01,2024-03-01,2024.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns7:p>Faced with declining donor funding for ...,"Faced with declining donor funding for HIV, lo...","[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-18/v1...,"Gantayat, Nishan; Baer, James; Gangaramany, Al...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3258-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,0,None,None,0,39,"[{""article-title"": ""Donor Government Funding f...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16533.r36109;10.21956/ga...,None,10.12688/gatesopenres.15189.3,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15189.1"", ""ISSN...",10.12688/gatesopenres.15189.1,10.12688,10.12688,gatesopenres.15189.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
427,crossref::10.12688/gatesopenres.12997.3,Gates Open Research,crossref,10.12688/gatesopenres.12997.3,10.12688/gatesopenres.12997.3,https://doi.org/10.12688/gatesopenres.12997.3,https://gatesopenresearch.org/articles/3-1473/v3,https://gatesopenresearch.org/articles/3-1473/v3,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Potential for Improving Intrauterine Device (I...,None,None,None,en,journal-article,None,journal-article,None,False,2020-03-04,None,2022-04-01,2025-02-21,None,2020-03-04,None,2020-03-04,2020-03-04,2020.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p><ns3:bold>Background: </ns3:bold>To acc...,Background: To accelerate progress toward Fami...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/3-1473/...,"Gehani, Manish; Pal, Manoj; Arya, Anupama; Sin...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-5894-4...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,2,None,None,2,25,"[{""article-title"": ""World Population Prospects...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.14295.r28648,"[{""DOI"": ""10.12688/gatesopenres.12997.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12997.3"", ""ISSN...",10.12688/gatesopenres.12997.3,10.12688,10.12688,gatesopenres.12997.3,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
426,crossref::10.12688/gatesopenres.12997.1,Gates Open Research,crossref,10.12688/gatesopenres.12997.1,10.12688/gatesopenres.12997.1,https://doi.org/10.12688/gatesopenres.12997.1,https://gatesopenresearch.org/articles/3-1473/v1,https://gatesopenresearch.org/articles/3-1473/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Could trained providers provide better quality...,None,None,None,en,journal-article,None,journal-article,None,False,2019-05-24,None,2022-04-01,2025-02-21,None,2019-05-24,None,2019-05-24,2019-05-24,2019.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns3:p><ns3:bold>Background: </ns3:bold>For ac...,Background: For accelerating its progress towa...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/3-1473/...,"Gehani, Manish; Pal, Manoj; Arya, Anupama; Sin...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-5894-4...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,0,None,None,0,25,"[{""article-title"": ""World Population Prospects...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.14105.r27248;10.21956/ga...,None,10.12688/gatesopenres.12997.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12997.1"", ""ISSN...",10.12688/gatesopenres.12997.1,10.12688,10.12688,gatesopenres.12997.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [100]:
Gates_df

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.12688/gatesopenres.12803.2,Gates Open Research,crossref,10.12688/gatesopenres.12803.2,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.12803.2,https://gatesopenresearch.org/articles/2-11/v2,https://gatesopenresearch.org/articles/2-11/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-12,None,2018-07-12,2025-02-21,None,2018-07-12,None,2018-07-12,2018-07-12,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,2,None,None,2,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12803.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.2"", ""ISSN...",10.12688/gatesopenres.12803.2,10.12688,10.12688,gatesopenres.12803.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
1,crossref::10.12688/gatesopenres.12803.1,Gates Open Research,crossref,10.12688/gatesopenres.12803.1,10.12688/gatesopenres.12803.1,https://doi.org/10.12688/gatesopenres.12803.1,https://gatesopenresearch.org/articles/2-11/v1,https://gatesopenresearch.org/articles/2-11/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-02-22,None,2018-07-12,2025-02-21,None,2018-02-22,None,2018-02-22,2018-02-22,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,3,None,None,3,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13867.r26331;10.21956/ga...,None,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.1"", ""ISSN...",10.12688/gatesopenres.12803.1,10.12688,10.12688,gatesopenres.12803.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
2,crossref::10.12688/gatesopenres.12816.1,Gates Open Research,crossref,10.12688/gatesopenres.12816.1,10.12688/gatesopenres.12816.1,https://doi.org/10.12688/gatesopenres.12816.1,https://gatesopenresearch.org/articles/2-24/v1,https://gatesopenresearch.org/articles/2-24/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-04-26,None,2018-07-19,2025-02-21,None,2018-04-26,None,2018-04-26,2018-04-26,2018.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/3.0/igo/,https://creativecommons.org/licenses/by/3.0/igo/,<ns4:p><ns4:bold>Background</ns4:bold>: the Po...,Background : the Portfolio-To-Impact (P2I) mod...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""award"": [""OPP1151682""], ""award-info"": [{""aw...",Bill and Melinda Gates Foundation; Swiss Agenc...,3.0,None,None,None,2,None,None,2,15,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13883.r26392;10.21956/ga...,None,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.1"", ""ISSN...",10.12688/gatesopenres.12816.1,10.12688,10.12688,gatesopenres.12816.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
3,crossref::10.12688/gatesopenres.12816.2,Gates Open Research,crossref,10.12688/gatesopenres.12816.2,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.12816.2,https://gatesopenresearch.org/articles/2-24/v2,https://gatesopenresearch.org/articles/2-24/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-19,None,2018-07-20,2025-11-01,None,2018-07-19,None,2018-07-19,2018-07-19,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background: </ns4:bold>The Po...,Background: The Portfolio-To-Impact (P2I) Mode...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""name"": ""The Special Programme for Research ...",The Special Programme for Research and Trainin...,3.0,None,None,None,17,None,None,17,16,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13921.r26569,"[{""DOI"": ""10.12688/gatesopenres.12816.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.2"", ""ISSN...",10.12688/gatesopenres.12816.2,10.12688,10.12688,gatesopenres.12816.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
4,crossref::10.12688/gatesopenres.12832.2,Gates Open Research,crossref,10.12688/gatesopenres.12832.2,10.12688/gatesopenres.12832.2,https://doi.org/10.12688/gatesopenres.12832.2,https://gatesopenresearch.org/articles/2-31/v2,https://gatesopenresearch.org/articles/2-31/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"DataPackageR: Reproducible data preprocessing,...",None,None,None,en,journal-article,None,journal-article,None,False,2018-07-10,None,2018-07-24,2025-11-21,None,2018-07-10,None,2018-07-10,2018-07-10,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n A central tenet o...,A central tenet of reproducible research is th...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Finak, Greg; Mayer, Bryan; Fulp, William; Obre...",None,None,"[{""affiliation"": [], ""family"": ""Finak"", ""given...",None,None,"[{""DOI"": ""10.13039/100000057"", ""award"": [""R01 ...",National Institute of General Medical Sciences...,2.0,None,None,None,3,None,None,3,39,"[{""DOI"": ""10.1373/clinchem.2010.158618"", ""arti...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13917.r26579;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12832.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12832.2"", ""ISSN...",10.12688/gatesopenres.12832.2,10.12688,10.12688,gatesopenres.12832.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,crossref::10.12688/gatesopenres.16362.1,Gates Open Research,crossref,10.12688/gatesopenres.16362.1,10.12688/gatesopenres.16362.1,https://doi.org/10.12688/gatesopenres.16362.1,https://gatesopenresearch.org/articles/9-69/v1,https://gatesopenresearch.org/articles/9-69/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Mycobacterium tuberculosis growth inhibition b...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-09-09,None,2025-09-09,2025-09-09,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background There ...,Background There is a concern that SARS-CoV-2 ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-69/v1...,"Shaw, Jane A; Petersen, Caleb; Hiemstra, Andri...",None,None,"[{""affiliation"": [], ""family"": ""Shaw"", ""given""...",None,None,"[{""DOI"": ""10.13039/100000060"", ""award"": [""75N9...",National Institute of Allergy and Infectious D...,3.0,None,None,None,0,None,None,0,44,"[{""DOI"": ""10.1056/NEJMoa2119658"", ""article-tit...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.514.3,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16362.1"", ""ISSN...",10.12688/gatesopenres.16362.1,10.12688,10.12688,gatesopenres.16362.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
859,crossref::10.12688/gatesopenres.16361.1,Gates Open Research,crossref,10.12688/gatesopenres.16361.1,10.12688/gatesopenres.16361.1,https://doi.org/10.12688/gatesopenres.16361.1,https://gatesopenresearch.org/articles/9-64/v1,https://gatesopenresearch.org/articles/9-64/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Maximising power with the minimum number of mo...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-08-27,None,2025-08-27,2025-08-27,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Power calculations are an essential com...,Power calculations are an essential component ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-64/v1...,"Harvey, Gemma Francesca; Mechan, Frank; Prauli...",None,None,"[{""ORCID"": ""https://orcid.org/0009-0008-6041-3...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,13,"[{""DOI"": ""10.1038/nature15535"", ""article-title...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.953.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16361.1"", ""ISSN...",10.12688/gatesopenres.16361.1,10.12688,10.12688,gatesopenres.16361.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
860,crossref::10.12688/gatesopenres.15431.1,Gates Open Research,crossref,10.12688/gatesopenres.15431.1,10.12688/gatesopenres.15431.1,https://doi.org/10.12688/gatesopenres.15431.1,https://gatesopenresearch.org/articles/9-7/v1,https://gatesopenresearch.org/articles/9-7/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A new application programming interface (API) ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-03-11,None,2025-11-21,2025-11-21,None,2025-03-11,None,2025-03-11,2025-03-11,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background The escalating threat of AMR...,Background The escalating threat of AMR demand...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-7/v1/pdf,"Pillonetto, Marcelo; Kraft, Leticia; Ellen, St...",None,None,"[{""affiliation"": [], ""family"": ""Pillonetto"", ""...",None,None,"[{""award"": [""51618.554.31977.10122018""], ""awar...",Programa grand challenges explorations-brazil:...,1.0,None,None,None,0,None,None,0,19,"[{""article-title"": ""Usability and feasibility ...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16783.r39769;10.21956/ga...,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15431.1"", ""ISSN...",10.12688/gatesopenres.15431.1,10.12688,10.12688,gatesopenres.15431.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
861,crossref::10.12688/gatesopenres,Gates Open Research,crossref,10.12688/gatesopenres,10.12688/gatesopenres,https://doi.org/10.12688/gatesopenres,http://www.gatesopenresearch.org,http://www.gatesopenresearch.org,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,None,2572-4754,Gates Open Research,None,Gates Open Res,None,en,journal,None,journal,None,False,2017-11-06,None,2025-12-17,2025-12-17,None,None,None,None,None,NaN,created_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,13,None,None,13,0,None,None,,,False,None,,None,None,,None,None,None,issn,49,None,"{""DOI"": ""10.12688/gatesopenres"", ""ISSN"": [""257...",10.12688/gatesopenres,10.12688,10.12688,gatesopenres,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org
862,crossref::10.12688/gatesopenres.15991.2,Gates Open Research,crossref,10.12688/gatesopenres.15991.2,10.12688/gatesopenres.15991.2,https://doi.org/10.12688/gatesopenres.15991.2,https://gatesopenresearch.org/articles/8-95/v2,https://gatesopenresearch.org/articles/8-95/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"Single-blinded, stratified, dose ranging trial...",None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-12-17,2025-12-17,None,2025-09-17,None,2025-09-17,2025-09-17,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background Vitami...,Background Vitamin B12 is an essential cofacto...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-95/v2...,"Lweno, Omar; Reynolds, Victoria S.; Barberio, ...",None,None,"[{""affiliation"": [], ""family"": ""Lweno"", ""given...",None,None,"[{""award"": [""INV-016930""], ""award-info"": [{""aw...",Gates Foundation,1.0,None,None,None,0,None,None,0,37,"[{""DOI"": ""10.1093/jn/nxy201"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,10.12688/gatesopenres.15991.1,None,New version,10.21956/gatesopenres.17759.r39860,"[{""DOI"": ""10.12688/gatesopenres.15991.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15991.2"", ""ISSN...",10.12688/gatesopenres.15991.2,10.12688,10.12688,gatesopenres.15991.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [101]:
Gates_df

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.12688/gatesopenres.12803.2,Gates Open Research,crossref,10.12688/gatesopenres.12803.2,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.12803.2,https://gatesopenresearch.org/articles/2-11/v2,https://gatesopenresearch.org/articles/2-11/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-12,None,2018-07-12,2025-02-21,None,2018-07-12,None,2018-07-12,2018-07-12,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,2,None,None,2,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12803.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.2"", ""ISSN...",10.12688/gatesopenres.12803.2,10.12688,10.12688,gatesopenres.12803.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
1,crossref::10.12688/gatesopenres.12803.1,Gates Open Research,crossref,10.12688/gatesopenres.12803.1,10.12688/gatesopenres.12803.1,https://doi.org/10.12688/gatesopenres.12803.1,https://gatesopenresearch.org/articles/2-11/v1,https://gatesopenresearch.org/articles/2-11/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-02-22,None,2018-07-12,2025-02-21,None,2018-02-22,None,2018-02-22,2018-02-22,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,3,None,None,3,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13867.r26331;10.21956/ga...,None,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.1"", ""ISSN...",10.12688/gatesopenres.12803.1,10.12688,10.12688,gatesopenres.12803.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
2,crossref::10.12688/gatesopenres.12816.1,Gates Open Research,crossref,10.12688/gatesopenres.12816.1,10.12688/gatesopenres.12816.1,https://doi.org/10.12688/gatesopenres.12816.1,https://gatesopenresearch.org/articles/2-24/v1,https://gatesopenresearch.org/articles/2-24/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-04-26,None,2018-07-19,2025-02-21,None,2018-04-26,None,2018-04-26,2018-04-26,2018.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/3.0/igo/,https://creativecommons.org/licenses/by/3.0/igo/,<ns4:p><ns4:bold>Background</ns4:bold>: the Po...,Background : the Portfolio-To-Impact (P2I) mod...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""award"": [""OPP1151682""], ""award-info"": [{""aw...",Bill and Melinda Gates Foundation; Swiss Agenc...,3.0,None,None,None,2,None,None,2,15,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13883.r26392;10.21956/ga...,None,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.1"", ""ISSN...",10.12688/gatesopenres.12816.1,10.12688,10.12688,gatesopenres.12816.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
3,crossref::10.12688/gatesopenres.12816.2,Gates Open Research,crossref,10.12688/gatesopenres.12816.2,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.12816.2,https://gatesopenresearch.org/articles/2-24/v2,https://gatesopenresearch.org/articles/2-24/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-19,None,2018-07-20,2025-11-01,None,2018-07-19,None,2018-07-19,2018-07-19,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background: </ns4:bold>The Po...,Background: The Portfolio-To-Impact (P2I) Mode...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""name"": ""The Special Programme for Research ...",The Special Programme for Research and Trainin...,3.0,None,None,None,17,None,None,17,16,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13921.r26569,"[{""DOI"": ""10.12688/gatesopenres.12816.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.2"", ""ISSN...",10.12688/gatesopenres.12816.2,10.12688,10.12688,gatesopenres.12816.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
4,crossref::10.12688/gatesopenres.12832.2,Gates Open Research,crossref,10.12688/gatesopenres.12832.2,10.12688/gatesopenres.12832.2,https://doi.org/10.12688/gatesopenres.12832.2,https://gatesopenresearch.org/articles/2-31/v2,https://gatesopenresearch.org/articles/2-31/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"DataPackageR: Reproducible data preprocessing,...",None,None,None,en,journal-article,None,journal-article,None,False,2018-07-10,None,2018-07-24,2025-11-21,None,2018-07-10,None,2018-07-10,2018-07-10,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n A central tenet o...,A central tenet of reproducible research is th...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Finak, Greg; Mayer, Bryan; Fulp, William; Obre...",None,None,"[{""affiliation"": [], ""family"": ""Finak"", ""given...",None,None,"[{""DOI"": ""10.13039/100000057"", ""award"": [""R01 ...",National Institute of General Medical Sciences...,2.0,None,None,None,3,None,None,3,39,"[{""DOI"": ""10.1373/clinchem.2010.158618"", ""arti...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13917.r26579;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12832.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12832.2"", ""ISSN...",10.12688/gatesopenres.12832.2,10.12688,10.12688,gatesopenres.12832.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,crossref::10.12688/gatesopenres.16362.1,Gates Open Research,crossref,10.12688/gatesopenres.16362.1,10.12688/gatesopenres.16362.1,https://doi.org/10.12688/gatesopenres.16362.1,https://gatesopenresearch.org/articles/9-69/v1,https://gatesopenresearch.org/articles/9-69/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Mycobacterium tuberculosis growth inhibition b...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-09-09,None,2025-09-09,2025-09-09,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background There ...,Background There is a concern that SARS-CoV-2 ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-69/v1...,"Shaw, Jane A; Petersen, Caleb; Hiemstra, Andri...",None,None,"[{""affiliation"": [], ""family"": ""Shaw"", ""given""...",None,None,"[{""DOI"": ""10.13039/100000060"", ""award"": [""75N9...",National Institute of Allergy and Infectious D...,3.0,None,None,None,0,None,None,0,44,"[{""DOI"": ""10.1056/NEJMoa2119658"", ""article-tit...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.514.3,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16362.1"", ""ISSN...",10.12688/gatesopenres.16362.1,10.12688,10.12688,gatesopenres.16362.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
859,crossref::10.12688/gatesopenres.16361.1,Gates Open Research,crossref,10.12688/gatesopenres.16361.1,10.12688/gatesopenres.16361.1,https://doi.org/10.12688/gatesopenres.16361.1,https://gatesopenresearch.org/articles/9-64/v1,https://gatesopenresearch.org/articles/9-64/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Maximising power with the minimum number of mo...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-08-27,None,2025-08-27,2025-08-27,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Power calculations are an essential com...,Power calculations are an essential component ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-64/v1...,"Harvey, Gemma Francesca; Mechan, Frank; Prauli...",None,None,"[{""ORCID"": ""https://orcid.org/0009-0008-6041-3...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,13,"[{""DOI"": ""10.1038/nature15535"", ""article-title...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.953.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16361.1"", ""ISSN...",10.12688/gatesopenres.16361.1,10.12688,10.12688,gatesopenres.16361.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
860,crossref::10.12688/gatesopenres.15431.1,Gates Open Research,crossref,10.12688/gatesopenres.15431.1,10.12688/gatesopenres.15431.1,https://doi.org/10.12688/gatesopenres.15431.1,https://gatesopenresearch.org/articles/9-7/v1,https://gatesopenresearch.org/articles/9-7/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A new application programming interface (API) ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-03-11,None,2025-11-21,2025-11-21,None,2025-03-11,None,2025-03-11,2025-03-11,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background The escalating threat of AMR...,Background The escalating threat of AMR demand...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-7/v1/pdf,"Pillonetto, Marcelo; Kraft, Leticia; Ellen, St...",None,None,"[{""affiliation"": [], ""family"": ""Pillonetto"", ""...",None,None,"[{""award"": [""51618.554.31977.10122018""], ""awar...",Programa grand challenges explorations-brazil:...,1.0,None,None,None,0,None,None,0,19,"[{""article-title"": ""Usability and feasibility ...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16783.r39769;10.21956/ga...,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15431.1"", ""ISSN...",10.12688/gatesopenres.15431.1,10.12688,10.12688,gatesopenres.15431.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
861,crossref::10.12688/gatesopenres,Gates Open Research,crossref,10.12688/gatesopenres,10.12688/gatesopenres,https://doi.org/10.12688/gatesopenres,http://www.gatesopenresearch.org,http://www.gatesopenresearch.org,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,None,2572-4754,Gates Open Research,None,Gates Open Res,None,en,journal,None,journal,None,False,2017-11-06,None,2025-12-17,2025-12-17,None,None,None,None,None,NaN,created_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,13,None,None,13,0,None,None,,,False,None,,None,None,,None,None,None,issn,49,None,"{""DOI"": ""10.12688/gatesopenres"", ""ISSN"": [""257...",10.12688/gatesopenres,10.12688,10.12688,gatesopenres,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org
862,crossref::10.12688/gatesopenres.15991.2,Gates Open Research,crossref,10.12688/gatesopenres.15991.2,10.12688/gatesopenres.15991.2,https://doi.org/10.12688/gatesopenres.15991.2,https://gatesopenresearch.org/articles/8-95/v2,https://gatesopenresearch.org/articles/8-95/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"Single-blinded, stratified, dose ranging trial...",None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-12-17,2025-12-17,None,2025-09-17,None,2025-09-17,2025-09-17,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background Vitami...,Background Vitamin B12 is an essential cofacto...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-95/v2...,"Lweno, Omar; Reynolds, Victoria S.; Barberio, ...",None,None,"[{""affiliation"": [], ""family"": ""Lweno"", ""given...",None,None,"[{""award"": [""INV-016930""], ""award-info"": [{""aw...",Gates Foundation,1.0,None,None,None,0,None,None,0,37,"[{""DOI"": ""10.1093/jn/nxy201"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,10.12688/gatesopenres.15991.1,None,New version,10.21956/gatesopenres.17759.r39860,"[{""DOI"": ""10.12688/gatesopenres.15991.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15991.2"", ""ISSN...",10.12688/gatesopenres.15991.2,10.12688,10.12688,gatesopenres.15991.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [102]:
pattern = "has-preprint"

mask = Gates_df['relations_json'].str.contains(pattern, regex=False, na=False)
result = Gates_df[mask]
print(result.shape)
result

(28, 90)

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
788,crossref::10.12688/gatesopenres.16311.1,Gates Open Research,crossref,10.12688/gatesopenres.16311.1,10.12688/gatesopenres.16311.1,https://doi.org/10.12688/gatesopenres.16311.1,https://gatesopenresearch.org/articles/8-143/v1,https://gatesopenresearch.org/articles/8-143/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,An exploration of unusual antimicrobial resist...,None,None,None,en,journal-article,None,journal-article,None,False,2024-12-23,None,2024-12-23,2025-11-21,None,2024-12-23,None,2024-12-23,2024-12-23,2024.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Typhoid fever is ...,Typhoid fever is a significant public health p...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-143/v...,"Zuza, Allan; Wailan, Alexander M.; Anscombe, C...",None,None,"[{""affiliation"": [], ""family"": ""Zuza"", ""given""...",None,None,"[{""DOI"": ""10.13039/100010269"", ""award"": [""2173...",Wellcome Trust; Biotechnology and Biological S...,4.0,None,None,None,0,None,None,0,47,"[{""DOI"": ""10.1016/S1473-3099(18)30685-6"", ""art...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.77.2,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16311.1"", ""ISSN...",10.12688/gatesopenres.16311.1,10.12688,10.12688,gatesopenres.16311.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
799,crossref::10.12688/gatesopenres.16313.1,Gates Open Research,crossref,10.12688/gatesopenres.16313.1,10.12688/gatesopenres.16313.1,https://doi.org/10.12688/gatesopenres.16313.1,https://gatesopenresearch.org/articles/9-1/v1,https://gatesopenresearch.org/articles/9-1/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Automated post-run analysis of arrayed quantit...,None,None,None,en,journal-article,None,journal-article,None,False,2025-01-20,None,2025-01-20,2026-01-05,None,2025-01-20,None,2025-01-20,2025-01-20,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns4:p>Background The TaqMan Array Card (TAC) ...,Background The TaqMan Array Card (TAC) is an a...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-1/v1/pdf,"Brintz, Ben J.; Operario, Darwin J.; Brown, Da...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-4695-0...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,1,None,None,1,13,"[{""DOI"": ""10.1136/bmjgh-2022-009548"", ""article...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.123.2,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16313.1"", ""ISSN...",10.12688/gatesopenres.16313.1,10.12688,10.12688,gatesopenres.16313.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
813,crossref::10.12688/gatesopenres.16314.1,Gates Open Research,crossref,10.12688/gatesopenres.16314.1,10.12688/gatesopenres.16314.1,https://doi.org/10.12688/gatesopenres.16314.1,https://gatesopenresearch.org/articles/9-6/v1,https://gatesopenresearch.org/articles/9-6/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Design and validation of a low-cost sugar-feed...,None,None,None,en,journal-article,None,journal-article,None,False,2025-03-03,None,2025-03-03,2025-08-06,None,2025-03-03,None,2025-03-03,2025-03-03,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns4:p>BackgroundThe emergence of insecticide ...,BackgroundThe emergence of insecticide resista...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-6/v1/pdf,"Stavrou–Dowd, Zachary Thomas; Rose, Clair; Aco...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-0323-8...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation; Jean Clayto...,2.0,None,None,None,1,None,None,1,32,"[{""DOI"": ""10.1186/1756-3305-5-69"", ""article-ti...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.54.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16314.1"", ""ISSN...",10.12688/gatesopenres.16314.1,10.12688,10.12688,gatesopenres.16314.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
814,crossref::10.12688/gatesopenres.16315.1,Gates Open Research,crossref,10.12688/gatesopenres.16315.1,10.12688/gatesopenres.16315.1,https://doi.org/10.12688/gatesopenres.16315.1,https://gatesopenresearch.org/articles/9-5/v1,https://gatesopenresearch.org/articles/9-5/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A comparison of acceptability of contraceptive...,None,None,None,en,journal-article,None,journal-article,None,False,2025-03-03,None,2025-03-03,2025-03-04,None,2025-03-03,None,2025-03-03,2025-03-03,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns4:p>BackgroundExpanding contraceptive optio...,BackgroundExpanding contraceptive options coul...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-5/v1/pdf,"Polis, Chelsea B.; Obare, Francis O.; Bruce, I...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-1031-7...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""[INV...",Bill & Melinda Gates Foundation,1.0,None,None,None,0,None,None,0,36,"[{""DOI"": ""10.1016/S2214-109X(20)30315-6"", ""art...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.471.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16315.1"", ""ISSN...",10.12688/gatesopenres.16315.1,10.12688,10.12688,gatesopenres.16315.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
817,crossref::10.12688/gatesopenres.16346.1,Gates Open Research,crossref,10.12688/gatesopenres.16346.1,10.12688/gatesopenres.16346.1,https://doi.org/10.12688/gatesopenres.16346.1,https://gatesopenresearch.org/articles/9-17/v1,https://gatesopenresearch.org/articles/9-17/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Estimated Modern Use: Employing A Service Stat...,None,None,None,en,journal-article,None,journal-article,None,False,2025-05-07,None,2025-05-07,2025-10-09,None,2025-05-07,None,2025-05-07,2025-05-07,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,"<ns3:p>Estimated Modern Use (EMU) is a novel, ...","Estimated Modern Use (EMU) is a novel, service...","[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-17/v1...,"Bietsch, Kristin; Reeves, Margaret; Williamson...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6264-8...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,1,None,None,1,10,"[{""DOI"": ""10.1016/S0140-6736(12)62204-1"", ""art...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.617.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16346.1"", ""ISSN...",10.12688/gatesopenres.16346.1,10.12688,10.12688,gatesopenres.16346.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
818,crossref::10.12688/gatesopenres.16348.1,Gates Open Research,crossref,10.12688/gatesopenres.16348.1,10.12688/gatesopenres.16348.1,https://doi.org/10.12688/gatesopenres.16348.1,https://gatesopenresearch.org/articles/9-16/v1,https://gatesopenresearch.org/articles/9-16/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Surgical Complications of Typhoid Fever: First...,None,None,None,en,journal-article,None,journal-article,None,False,2025-05-07,None,2025-05-07,2025-12-19,None,2025-05-07,None,2025-05-07,2025-05-07,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Typhoid intestinal perforation (TIP) is...,Typhoid intestinal perforation (TIP) is a life...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-16/v1...,"Adamou, Harissou; Maman Bachir, Abdoulaye; San...",None,None,"[{""affiliation"": [], ""family"": ""Adamou"", ""give...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,3,None,None,3,12,"[{""DOI"": ""10.1016/S0140-6736(24)00769-4"", ""art...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.387.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16348.1"", ""ISSN...",10.12688/gatesopenres.16348.1,10.12688,10.12688,gatesopenres.16348.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
819,crossref::10.12688/gatesopenres.16347.1,Gates Open Research,crossref,10.12688/gatesopenres.16347.1,10.12688/gatesopenres.16347.1,https://doi.org/10.12688/gatesopenres.16347.1,https://gatesopenresearch.org/articles/9-36/v1,https://gatesopenresearch.org/articles/9-36/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"Mapping the impact, sustainability and pedagog...",None,None,None,en,journal-article,None,journal-article,None,False,2025-05-16,None,2025-05-16,2025-05-17,None,2025-05-16,None,2025-05-16,2025-05-16,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>RationaleVirtual exchanges are emerging...,RationaleVirtual exchanges are emerging as inn...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-36/v1...,"Brady Bates, Oisin; Nicholas Grecu, Alexandru;...",None,None,"[{""affiliation"": [], ""family"": ""Brady Bates"", ...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,0,None,None,0,25,"[{""DOI"": ""10.11124/JBIES-20-00167"", ""article-t...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.726.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16347.1"", ""ISSN...",10.12688/gatesopenres.16347.1,10.12688,10.12688,gatesopenres.16347.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
820,crossref::10.12688/gatesopenres.16349.1,Gates Open Research,crossref,10.12688/gatesopenres.16349.1,10.12688/gatesopenres.16349.1,https://doi.org/10.12688/gatesopenres.16349.1,https://gatesopenresearch.org/articles/9-40/v1,https://gatesopenresearch.org/articles/9-40/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Foot-and-mouth disease (FMD) vaccine market su...,None,None,None,en,journal-article,None,journal-article,None,False,2025-05-20,None,2025-05-20,2025-12-30,None,2025-05-20,None,2025-05-20,2025-05-20,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,"<ns3:p>Globally, the annual economic impact of...","Globally, the annual economic impact of foot-a...","[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-40/v1...,"Sopeju, Adebayo Emmanuel; Onoja, Grace; Abiodu...",None,None,"[{""affiliation"": [], ""family"": ""Sopeju"", ""give...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,1,None,None,1,17,"[{""DOI"": ""10.4314/NJHBS.V4I2.11550"", ""article-...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.15.2,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16349.1"", ""ISSN...",10.12688/gatesopenres.16349.1,10.12688,10.12688,gatesopenres.16349.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
826,crossref::10.12688/gatesopenres.16350.1,Gates Open Research,crossref,10.12688/gatesopenres.16350.1,10.12688/gatesopenres.16350.1,https://doi.org/10.12688/gatesopenres.16350.1,https://gatesopenresearch.org/articles/9-47/v1,https://gatesopenresearch.org/articles/9-47/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Knowledge Exchange is Essential to Contracepti...,None,None,None,en,journal-article,None,journal-article,None,False,2025-06-19,None,2025-06-19,2025-06-20,None,2025-06-19,None,2025-06-19,2025-06-19,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>The field of contraceptive research and...,The field of contraceptive research and develo...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-47/v1...,"Hoppes, Emily; Fratus, Audrey; Leavitt, Gracie...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-0178-4...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""[INV...",Bill and Melinda Gates Foundation,1.0,None,None,None,0,None,None,0,14,"[{""DOI"": ""10.1186/1471-2458-14-443"", ""article-...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.489.2,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16350.1"", ""ISSN...",10.12688/gatesopenres.16350.1,10.12688,10.12688,gatesopenres.16350.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
830,crossref::10.12688/gatesopenres.16352.1,Gates Open Research,crossref,10.12688/gatesopenres.16352.1,10.12688/gatesopenres.16352.1,https://doi.org/10.12688/gatesopenres.16352.1,https://gatesopenresearch.org/articles/9-48/v1,https://gatesopenresearch.org/articles/9-48/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,PRIORITY IR: Protocol for implementation resea...,None,None,None,en,journal-article,None,journal-article,None,False,2025-07-15,None,2025-07-15,2025-08-02,None,2025-07-15,None,2025-07-15,2025-07-15,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background Anemia among women of reprod...,Background Anemia among women of reproductive ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-48/v1...,"Flax, Valerie L.; Rizvi, Narjis; Charantimath,...",None,None,"[{""affiliation"": [], ""family"": ""Flax"", ""given""...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,0,None,None,0,22,"[{""DOI"": ""10.1016/S2214-109X(22)00084-5"", ""art...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.540.3,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16352.1"", ""ISSN...",10.12688/gatesopenres.16352.1,10.12688,10.12688,gatesopenres.16352.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
833,crossref::10.12688/gatesopenres.16355.1,Gates Open Research,crossref,10.12688/gatesopenres.16355.1,10.12688/gatesopenres.16355.1,https://doi.org/10.12688/gatesopenres.16355.1,https://gatesopenresearch.org/articles/9-49/v1,https://gatesopenresearch.org/articles/9-49/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,An expanded method for malaria parasite geneti...,None,None,None,en,journal-article,None,journal-article,None,False,2025-07-24,None,2025-07-24,2025-08-02,None,2025-07-24,None,2025-07-24,2025-07-24,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Malaria causes around 250 million cases...,Malaria causes around 250 million cases and ov...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-49/v1...,"Harrott, Alexandria J. R.; Morang'a, Collins M...",None,None,"[{""affiliation"": [], ""family"": ""Harrott"", ""giv...",None,None,"[{""DOI"": ""10.13039/501100000272"", ""doi-asserte...",National Institute for Health and Care Researc...,7.0,None,None,None,0,None,None,0,26,"[{""article-title"": ""Strategy to respond to ant...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.630.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16355.1"", ""ISSN...",10.12688/gatesopenres.16355.1,10.12688,10.12688,gatesopenres.16355.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [103]:
Gates_df['has_preprint'].value_counts().reset_index().sort_values(by='has_preprint')

               has_preprint  count
0                              835
18  10.12688/verixiv.1078.1      1
26  10.12688/verixiv.1155.1      1
25  10.12688/verixiv.1161.1      1
15  10.12688/verixiv.1179.2      1
2    10.12688/verixiv.123.2      1
20  10.12688/verixiv.1323.2      1
8     10.12688/verixiv.15.2      1
19  10.12688/verixiv.1752.1      1
17  10.12688/verixiv.1808.1      1
21   10.12688/verixiv.244.3      1
14   10.12688/verixiv.245.2      1
24   10.12688/verixiv.247.1      1
6    10.12688/verixiv.387.1      1
4    10.12688/verixiv.471.1      1
9    10.12688/verixiv.489.2      1
16   10.12688/verixiv.497.3      1
27   10.12688/verixiv.514.3      1
3     10.12688/verixiv.54.1      1
10   10.12688/verixiv.540.3      1
23   10.12688/verixiv.558.3      1
5    10.12688/verixiv.617.1      1
11   10.12688/verixiv.630.1      1
7    10.12688/verixiv.726.1      1
1     10.12688/verixiv.77.2      1
13    10.12688/verixiv.83.2      1
22   10.12688/verixiv.888.2      1
28   10.12688/verixiv.953.1      1
12   10.12688/verixiv.989.1      1

In [104]:
pattern = "has-review"

mask = Gates_df['relations_json'].str.contains(pattern, regex=False, na=False)
result = Gates_df[mask]
print(result.shape)
result

(735, 90)

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
1,crossref::10.12688/gatesopenres.12803.1,Gates Open Research,crossref,10.12688/gatesopenres.12803.1,10.12688/gatesopenres.12803.1,https://doi.org/10.12688/gatesopenres.12803.1,https://gatesopenresearch.org/articles/2-11/v1,https://gatesopenresearch.org/articles/2-11/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-02-22,None,2018-07-12,2025-02-21,None,2018-02-22,None,2018-02-22,2018-02-22,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,3,None,None,3,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13867.r26331;10.21956/ga...,None,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.1"", ""ISSN...",10.12688/gatesopenres.12803.1,10.12688,10.12688,gatesopenres.12803.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
2,crossref::10.12688/gatesopenres.12816.1,Gates Open Research,crossref,10.12688/gatesopenres.12816.1,10.12688/gatesopenres.12816.1,https://doi.org/10.12688/gatesopenres.12816.1,https://gatesopenresearch.org/articles/2-24/v1,https://gatesopenresearch.org/articles/2-24/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-04-26,None,2018-07-19,2025-02-21,None,2018-04-26,None,2018-04-26,2018-04-26,2018.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/3.0/igo/,https://creativecommons.org/licenses/by/3.0/igo/,<ns4:p><ns4:bold>Background</ns4:bold>: the Po...,Background : the Portfolio-To-Impact (P2I) mod...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""award"": [""OPP1151682""], ""award-info"": [{""aw...",Bill and Melinda Gates Foundation; Swiss Agenc...,3.0,None,None,None,2,None,None,2,15,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13883.r26392;10.21956/ga...,None,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.1"", ""ISSN...",10.12688/gatesopenres.12816.1,10.12688,10.12688,gatesopenres.12816.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
3,crossref::10.12688/gatesopenres.12816.2,Gates Open Research,crossref,10.12688/gatesopenres.12816.2,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.12816.2,https://gatesopenresearch.org/articles/2-24/v2,https://gatesopenresearch.org/articles/2-24/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-19,None,2018-07-20,2025-11-01,None,2018-07-19,None,2018-07-19,2018-07-19,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background: </ns4:bold>The Po...,Background: The Portfolio-To-Impact (P2I) Mode...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""name"": ""The Special Programme for Research ...",The Special Programme for Research and Trainin...,3.0,None,None,None,17,None,None,17,16,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13921.r26569,"[{""DOI"": ""10.12688/gatesopenres.12816.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.2"", ""ISSN...",10.12688/gatesopenres.12816.2,10.12688,10.12688,gatesopenres.12816.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
4,crossref::10.12688/gatesopenres.12832.2,Gates Open Research,crossref,10.12688/gatesopenres.12832.2,10.12688/gatesopenres.12832.2,https://doi.org/10.12688/gatesopenres.12832.2,https://gatesopenresearch.org/articles/2-31/v2,https://gatesopenresearch.org/articles/2-31/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"DataPackageR: Reproducible data preprocessing,...",None,None,None,en,journal-article,None,journal-article,None,False,2018-07-10,None,2018-07-24,2025-11-21,None,2018-07-10,None,2018-07-10,2018-07-10,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n A central tenet o...,A central tenet of reproducible research is th...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Finak, Greg; Mayer, Bryan; Fulp, William; Obre...",None,None,"[{""affiliation"": [], ""family"": ""Finak"", ""given...",None,None,"[{""DOI"": ""10.13039/100000057"", ""award"": [""R01 ...",National Institute of General Medical Sciences...,2.0,None,None,None,3,None,None,3,39,"[{""DOI"": ""10.1373/clinchem.2010.158618"", ""arti...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13917.r26579;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12832.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12832.2"", ""ISSN...",10.12688/gatesopenres.12832.2,10.12688,10.12688,gatesopenres.12832.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
5,crossref::10.12688/gatesopenres.12752.1,Gates Open Research,crossref,10.12688/gatesopenres.12752.1,10.12688/gatesopenres.12752.1,https://doi.org/10.12688/gatesopenres.12752.1,https://gatesopenresearch.org/articles/1-3/v1,https://gatesopenresearch.org/articles/1-3/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Pre-exposure prophylaxis for HIV-negative pers...,None,None,None,en,journal-article,None,journal-article,None,False,2017-11-06,None,2018-07-31,2025-12-15,None,2017-11-06,None,2017-11-06,2017-11-06,2017.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Introduction</ns4:bold>: Pre-...,Introduction : Pre-exposure prophylaxis (PrEP)...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Heffron, Renee; Ngure, Kenneth; Odoyo, Josephi...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0001-6039-0...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation; United Stat...,4.0,None,None,None,58,None,None,58,21,"[{""DOI"": ""10.1056/NEJMoa1108524"", ""article-tit...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13812.r26099;10.21956/ga...,None,10.12688/gatesopenres.12752.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12752.1"", ""ISSN...",10.12688/gatesopenres.12752.1,10.12688,10.12688,gatesopenres.12752.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,crossref::10.12688/gatesopenres.15992.1,Gates Open Research,crossref,10.12688/gatesopenres.15992.1,10.12688/gatesopenres.15992.1,https://doi.org/10.12688/gatesopenres.15992.1,https://gatesopenresearch.org/articles/8-101/v1,https://gatesopenresearch.org/articles/8-101/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Effects of a single oral dose of azithromycin ...,None,None,None,en,journal-article,None,journal-article,None,False,2024-09-24,None,2025-09-24,2025-11-21,None,2024-09-24,None,2024-09-24,2024-09-24,2024.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background The Az...,Background The Azithromycin Prevention in Labo...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-101/v...,"Kim, Jean H.; Babineau, Denise; Moore, Janet L...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-2207-6...",None,None,"[{""DOI"": ""10.13039/100000009"", ""award"": [""MCCL...",Foundation for the National Institutes of Heal...,2.0,None,None,None,1,None,None,1,21,"[{""DOI"": ""10.1007/s40261-022-01203-0"", ""articl...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.17351.r38173,None,10.12688/gatesopenres.15992.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15992.1"", ""ISSN...",10.12688/gatesopenres.15992.1,10.12688,10.12688,gatesopenres.15992.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
850,crossref::10.12688/gatesopenres.15272.1,Gates Open Research,crossref,10.12688/gatesopenres.15272.1,10.12688/gatesopenres.15272.1,https://doi.org/10.12688/gatesopenres.15272.1,https://gatesopenresearch.org/articles/8-33/v1,https://gatesopenresearch.org/articles/8-33/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Correlates of early sex debut among adolescent...,None,None,None,en,journal-article,None,journal-article,None,False,2024-04-24,None,2025-11-21,2025-11-21,None,2024-04-24,None,2024-04-24,2024-04-24,2024.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background Early sexual debut among ado...,Background Early sexual debut among adolescent...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-33/v1...,"Kiiru, Samuel; Thiongo, Mary; Gichangi, Peter",None,None,"[{""ORCID"": ""https://orcid.org/0009-0004-7416-0...",None,None,"[{""award"": [""OPP1198333""], ""award-info"": [{""aw...",Gates Foundation,2.0,None,None,None,0,None,None,0,32,"[{""DOI"": ""10.1111/j.1365-3156.2012.03005.x"", ""...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16620.r39840,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15272.1"", ""ISSN...",10.12688/gatesopenres.15272.1,10.12688,10.12688,gatesopenres.15272.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
851,crossref::10.12688/gatesopenres.14265.1,Gates Open Research,crossref,10.12688/gatesopenres.14265.1,10.12688/gatesopenres.14265.1,https://doi.org/10.12688/gatesopenres.14265.1,https://gatesopenresearch.org/articles/7-51/v1,https://gatesopenresearch.org/articles/7-51/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Using the HIV Prevention Self-Assessment Tools...,None,None,None,en,journal-article,None,journal-article,None,False,2023-03-23,None,2025-11-21,2025-11-21,None,2023-03-23,None,2023-03-23,2023-03-23,2023.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n <ns3:bold>Backgro...,Background: The HIV Prevention Self-Assessment...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/7-51/v1...,"Emmanuel, Faran; Lunika, Lulama; Swart-Van Bil...",None,None,"[{""affiliation"": [], ""family"": ""Emmanuel"", ""gi...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,25,"[{""article-title"": ""Political Declaration on H...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.15575.r35318;10.21956/ga...,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.14265.1"", ""ISSN...",10.12688/gatesopenres.14265.1,10.12688,10.12688,gatesopenres.14265.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
860,crossref::10.12688/gatesopenres.15431.1,Gates Open Research,crossref,10.12688/gatesopenres.15431.1,10.12688/gatesopenres.15431.1,https://doi.org/10.12688/gatesopenres.15431.1,https://gatesopenresearch.org/articles/9-7/v1,https://gatesopenresearch.org/articles/9-7/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A new application programming interface (API) ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-03-11,None,2025-11-21,2025-11-21,None,2025-03-11,None,2025-03-11,2025-03-11,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background The escalating threat of AMR...,Background The escalating threat of AMR demand...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-7/v1/pdf,"Pillonetto, Marcelo; Kraft, Leticia; Ellen, St...",None,None,"[{""affiliation"": [], ""family"": ""Pillonetto"", ""...",None,None,"[{""award"": [""51618.554.31977.10122018""], ""awar...",Programa grand challenges explorations-brazil:...,1.0,None,None,None,0,None,None,0,19,"[{""article-title"": ""Usability and feasibility ...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16783.r39769;10.21956/ga...,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15431.1"", ""ISSN...",10.12688/gatesopenres.15431.1,10.12688,10.12688,gatesopenres.15431.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
862,crossref::10.12688/gatesopenres.15991.2,Gates Open Research,crossref,10.12688/gatesopenres.15991.2,10.12688/gatesopenres.15991.2,https://doi.org/10.12688/gatesopenres.15991.2,https://gatesopenresearch.org/articles/8-95/v2,https://gatesopenresearch.org/articles/8-95/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"Single-blinded, stratified, dose ranging trial...",None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-12-17,2025-12-17,None,2025-09-17,None,2025-09-17,2025-09-17,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background Vitami...,Background Vitamin B12 is an essential cofacto...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-95/v2...,"Lweno, Omar; Reynolds, Victoria S.; Barberio, ...",None,None,"[{""affiliation"": [], ""family"": ""Lweno"", ""given...",None,None,"[{""award"": [""INV-016930""], ""award-info"": [{""aw...",Gates Foundation,1.0,None,None,None,0,None,None,0,37,"[{""DOI"": ""10.1093/jn/nxy201"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,10.12688/gatesopenres.15991.1,None,New version,10.21956/gatesopenres.17759.r39860,"[{""DOI"": ""10.12688/gatesopenres.15991.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15991.2"", ""ISSN...",10.12688/gatesopenres.15991.2,10.12688,10.12688,gatesopenres.15991.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [105]:
pattern = "has-review"

mask = ~Gates_df['relations_json'].str.contains(pattern, regex=False, na=False)
result = Gates_df[mask]
print(result.shape)
result

(128, 90)

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.12688/gatesopenres.12803.2,Gates Open Research,crossref,10.12688/gatesopenres.12803.2,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.12803.2,https://gatesopenresearch.org/articles/2-11/v2,https://gatesopenresearch.org/articles/2-11/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-12,None,2018-07-12,2025-02-21,None,2018-07-12,None,2018-07-12,2018-07-12,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,2,None,None,2,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12803.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.2"", ""ISSN...",10.12688/gatesopenres.12803.2,10.12688,10.12688,gatesopenres.12803.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
6,crossref::10.12688/gatesopenres.12817.2,Gates Open Research,crossref,10.12688/gatesopenres.12817.2,10.12688/gatesopenres.12817.2,https://doi.org/10.12688/gatesopenres.12817.2,https://gatesopenresearch.org/articles/2-23/v2,https://gatesopenresearch.org/articles/2-23/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Developing new health technologies for neglect...,None,None,None,en,journal-article,None,journal-article,None,False,2018-08-22,None,2018-08-22,2025-11-01,None,2018-08-22,None,2018-08-22,2018-08-22,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background</ns4:bold>: Fundin...,Background : Funding for neglected disease pro...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Young, Ruth; Bekele, Tewodros; Gunn, Alexander...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-8787-2...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,4,None,None,4,22,"[{""DOI"": ""10.1016/S0140-6736(13)62105-4"", ""art...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12817.1"", ""lab...",10.12688/gatesopenres.12817.3,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12817.2"", ""ISSN...",10.12688/gatesopenres.12817.2,10.12688,10.12688,gatesopenres.12817.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
8,crossref::10.12688/gatesopenres.12842.2,Gates Open Research,crossref,10.12688/gatesopenres.12842.2,10.12688/gatesopenres.12842.2,https://doi.org/10.12688/gatesopenres.12842.2,https://gatesopenresearch.org/articles/2-35/v2,https://gatesopenresearch.org/articles/2-35/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Market penetration of Xpert MTB/RIF in high tu...,None,None,None,en,journal-article,None,journal-article,None,False,2018-09-18,None,2018-09-18,2025-02-21,None,2018-09-18,None,2018-09-18,2018-09-18,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background: </ns4:bold>Xpert®...,"Background: Xpert® MTB/RIF, a rapid tuberculos...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Cazabon, Danielle; Pande, Tripti; Kik, Sandra;...",None,None,"[{""affiliation"": [], ""family"": ""Cazabon"", ""giv...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...","Bill and Melinda Gates Foundation; FIND, Genev...",3.0,None,None,None,7,None,None,7,16,"[{""article-title"": ""Global Tuberculosis Report...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12842.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12842.2"", ""ISSN...",10.12688/gatesopenres.12842.2,10.12688,10.12688,gatesopenres.12842.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
10,crossref::10.12688/gatesopenres.12782.2,Gates Open Research,crossref,10.12688/gatesopenres.12782.2,10.12688/gatesopenres.12782.2,https://doi.org/10.12688/gatesopenres.12782.2,https://gatesopenresearch.org/articles/2-1/v2,https://gatesopenresearch.org/articles/2-1/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Characterizing performance improvement in prim...,None,None,None,en,journal-article,None,journal-article,None,False,2018-10-04,None,2018-10-04,2025-02-21,None,2018-10-04,None,2018-10-04,2018-10-04,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background</ns4:bold>. Evalua...,Background . Evaluations of performance measur...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/2-1/v2/pdf,"Munar, Wolfgang; Wahid, Syed S.; Curry, Leslie",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-9234-9...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,1,None,None,1,114,"[{""DOI"": ""10.1016/j.socscimed.2009.11.025"", ""a...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12782.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12782.2"", ""ISSN...",10.12688/gatesopenres.12782.2,10.12688,10.12688,gatesopenres.12782.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
14,crossref::10.12688/gatesopenres.12749.2,Gates Open Research,crossref,10.12688/gatesopenres.12749.2,10.12688/gatesopenres.12749.2,https://doi.org/10.12688/gatesopenres.12749.2,https://gatesopenresearch.org/articles/1-7/v2,https://gatesopenresearch.org/articles/1-7/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A superhydrophobic cone to facilitate the xeno...,None,None,None,en,journal-article,None,journal-article,None,False,2018-04-27,None,2018-11-09,2025-06-12,None,2018-04-27,None,2018-04-27,2018-04-27,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background: </ns4:bold>Molecu...,"Background: Molecular xenomonitoring (MX), the...","[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/1-7/v2/pdf,"Cook, Darren A.N.; Pilotte, Nils; Minetti, Cor...",None,None,"[{""affiliation"": [], ""family"": ""Cook"", ""given""...",None,None,"[{""DOI"": ""10.13039/501100000265"", ""award"": [""M...",Medical Research Council; Bill and Melinda Gat...,2.0,None,None,None,6,None,None,6,32,"[{""DOI"": ""10.1093/trstmh/trv070"", ""article-tit...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12749.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12749.2"", ""ISSN...",10.12688/gatesopenres.12749.2,10.12688,10.12688,gatesopenres.12749.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,crossref::10.12688/gatesopenres.16369.1,Gates Open Research,crossref,10.12688/gatesopenres.16369.1,10.12688/gatesopenres.16369.1,https://doi.org/10.12688/gatesopenres.16369.1,https://gatesopenresearch.org/articles/9-91/v1,https://gatesopenresearch.org/articles/9-91/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Evaluation of an ultra-portable pocket-sized d...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-10-24,None,2025-10-24,2025-10-24,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n The sweetpotato (...,The sweetpotato ( Ipomoea batatas ) is an impo...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-91/v1...,"Fuentes, Segundo; Ogero, Kwame; Perez, Ana; Kr...",None,None,"[{""affiliation"": [], ""family"": ""Fuentes"", ""giv...",None,None,"[{""DOI"": ""10.13039/100000865"", ""doi-asserted-b...",Gates Foundation; the CGIAR initiative on Plan...,2.0,None,None,None,0,None,None,0,27,"[{""DOI"": ""10.2144/000112149"", ""article-title"":...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.1161.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16369.1"", ""ISSN...",10.12688/gatesopenres.16369.1,10.12688,10.12688,gatesopenres.16369.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
857,crossref::10.12688/gatesopenres.16367.1,Gates Open Research,crossref,10.12688/gatesopenres.16367.1,10.12688/gatesopenres.16367.1,https://doi.org/10.12688/gatesopenres.16367.1,https://gatesopenresearch.org/articles/9-81/v1,https://gatesopenresearch.org/articles/9-81/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Prevalence of Molecular Markers of Resistance ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-10-08,None,2025-10-08,2025-10-08,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background Monito...,Background Monitoring parasite resistance to a...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-81/v1...,"Chen, Haily; Owusu-Kyei, Kwabena; Fombah, Augu...",None,None,"[{""affiliation"": [], ""family"": ""Chen"", ""given""...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Gates Foundation; Departament d’Universitats i...,2.0,None,None,None,0,None,None,0,46,"[{""article-title"": ""WHO Malaria Guidelines: Tr...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.1155.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16367.1"", ""ISSN...",10.12688/gatesopenres.16367.1,10.12688,10.12688,gatesopenres.16367.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
858,crossref::10.12688/gatesopenres.16362.1,Gates Open Research,crossref,10.12688/gatesopenres.16362.1,10.12688/gatesopenres.16362.1,https://doi.org/10.12688/gatesopenres.16362.1,https://gatesopenresearch.org/articles/9-69/v1,https://gatesopenresearch.org/articles/9-69/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Mycobacterium tuberculosis growth inhibition b...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-09-09,None,2025-09-09,2025-09-09,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background There ...,Background There is a concern that SARS-CoV-2 ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-69/v1...,"Shaw, Jane A; Petersen, Caleb; Hiemstra, Andri...",None,None,"[{""affiliation"": [], ""family"": ""Shaw"", ""given""...",None,None,"[{""DOI"": ""10.13039/100000060"", ""award"": [""75N9...",National Institute of Allergy and Infectious D...,3.0,None,None,None,0,None,None,0,44,"[{""DOI"": ""10.1056/NEJMoa2119658"", ""article-tit...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.514.3,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16362.1"", ""ISSN...",10.12688/gatesopenres.16362.1,10.12688,10.12688,gatesopenres.16362.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
859,crossref::10.12688/gatesopenres.16361.1,Gates Open Research,crossref,10.12688/gatesopenres.16361.1,10.12688/gatesopenres.16361.1,https://doi.org/10.12688/gatesopenres.16361.1,https://gatesopenresearch.org/articles/9-64/v1,https://gatesopenresearch.org/articles/9-64/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Maximising power with the minimum number of mo...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-08-27,None,2025-08-27,2025-08-27,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Power calculations are an essential com...,Power calculations are an essential component ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-64/v1...,"Harvey, Gemma Francesca; Mechan, Frank; Prauli...",None,None,"[{""ORCID"": ""https://orcid.org/0009-0008-6041-3...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,13,"[{""DOI"": ""10.1038/nature15535"", ""article-title...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.953.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16361.1"", ""ISSN...",10.12688/gatesopenres.16361.1,10.12688,10.12688,gatesopenres.16361.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
861,crossref::10.12688/gatesopenres,Gates Open Research,crossref,10.12688/gatesopenres,10.12688/gatesopenres,https://doi.org/10.12688/gatesopenres,http://www.gatesopenresearch.org,http://www.gatesopenresearch.org,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,None,2572-4754,Gates Open Research,None,Gates Open Res,None,en,journal,None,journal,None,False,2017-11-06,None,2025-12-17,2025-12-17,None,None,None,None,None,NaN,created_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,13,None,None,13,0,None,None,,,False,None,,None,None,,None,None,None,issn,49,None,"{""DOI"": ""10.12688/gatesopenres"", ""ISSN"": [""257...",10.12688/gatesopenres,10.12688,10.12688,gatesopenres,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org

In [106]:
Gates_df

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.12688/gatesopenres.12803.2,Gates Open Research,crossref,10.12688/gatesopenres.12803.2,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.12803.2,https://gatesopenresearch.org/articles/2-11/v2,https://gatesopenresearch.org/articles/2-11/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-12,None,2018-07-12,2025-02-21,None,2018-07-12,None,2018-07-12,2018-07-12,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,2,None,None,2,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...",None,,,False,None,,None,New version,,"[{""DOI"": ""10.12688/gatesopenres.12803.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.2"", ""ISSN...",10.12688/gatesopenres.12803.2,10.12688,10.12688,gatesopenres.12803.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
1,crossref::10.12688/gatesopenres.12803.1,Gates Open Research,crossref,10.12688/gatesopenres.12803.1,10.12688/gatesopenres.12803.1,https://doi.org/10.12688/gatesopenres.12803.1,https://gatesopenresearch.org/articles/2-11/v1,https://gatesopenresearch.org/articles/2-11/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A demographic dividend of the FP2020 Initiativ...,None,None,None,en,journal-article,None,journal-article,None,False,2018-02-22,None,2018-07-12,2025-02-21,None,2018-02-22,None,2018-02-22,2018-02-22,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background:</ns4:bold> The de...,"Background: The demographic dividend, defined ...","[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Li, Qingfeng; Rimon, Jose G.",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-6390-6...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""OPP1...",Bill and Melinda Gates Foundation,1.0,None,None,None,3,None,None,3,22,"[{""DOI"": ""10.1016/S0140-6736(06)69480-4"", ""art...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13867.r26331;10.21956/ga...,None,10.12688/gatesopenres.12803.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12803.1"", ""ISSN...",10.12688/gatesopenres.12803.1,10.12688,10.12688,gatesopenres.12803.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
2,crossref::10.12688/gatesopenres.12816.1,Gates Open Research,crossref,10.12688/gatesopenres.12816.1,10.12688/gatesopenres.12816.1,https://doi.org/10.12688/gatesopenres.12816.1,https://gatesopenresearch.org/articles/2-24/v1,https://gatesopenresearch.org/articles/2-24/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-04-26,None,2018-07-19,2025-02-21,None,2018-04-26,None,2018-04-26,2018-04-26,2018.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/3.0/igo/,https://creativecommons.org/licenses/by/3.0/igo/,<ns4:p><ns4:bold>Background</ns4:bold>: the Po...,Background : the Portfolio-To-Impact (P2I) mod...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""award"": [""OPP1151682""], ""award-info"": [{""aw...",Bill and Melinda Gates Foundation; Swiss Agenc...,3.0,None,None,None,2,None,None,2,15,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.13883.r26392;10.21956/ga...,None,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.1"", ""ISSN...",10.12688/gatesopenres.12816.1,10.12688,10.12688,gatesopenres.12816.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
3,crossref::10.12688/gatesopenres.12816.2,Gates Open Research,crossref,10.12688/gatesopenres.12816.2,10.12688/gatesopenres.12816.2,https://doi.org/10.12688/gatesopenres.12816.2,https://gatesopenresearch.org/articles/2-24/v2,https://gatesopenresearch.org/articles/2-24/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Funding global health product R&amp;D: the Por...,None,None,None,en,journal-article,None,journal-article,None,False,2018-07-19,None,2018-07-20,2025-11-01,None,2018-07-19,None,2018-07-19,2018-07-19,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p><ns4:bold>Background: </ns4:bold>The Po...,Background: The Portfolio-To-Impact (P2I) Mode...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Terry, Robert F; Yamey, Gavin; Miyazaki-Krause...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0003-3849-7...",None,None,"[{""name"": ""The Special Programme for Research ...",The Special Programme for Research and Trainin...,3.0,None,None,None,17,None,None,17,16,"[{""article-title"": ""Research and Development t...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13921.r26569,"[{""DOI"": ""10.12688/gatesopenres.12816.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12816.2"", ""ISSN...",10.12688/gatesopenres.12816.2,10.12688,10.12688,gatesopenres.12816.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
4,crossref::10.12688/gatesopenres.12832.2,Gates Open Research,crossref,10.12688/gatesopenres.12832.2,10.12688/gatesopenres.12832.2,https://doi.org/10.12688/gatesopenres.12832.2,https://gatesopenresearch.org/articles/2-31/v2,https://gatesopenresearch.org/articles/2-31/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"DataPackageR: Reproducible data preprocessing,...",None,None,None,en,journal-article,None,journal-article,None,False,2018-07-10,None,2018-07-24,2025-11-21,None,2018-07-10,None,2018-07-10,2018-07-10,2018.0,issued_date,None,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns4:p>\n A central tenet o...,A central tenet of reproducible research is th...,"[{""URL"": ""https://gatesopenresearch.org/articl...",None,"Finak, Greg; Mayer, Bryan; Fulp, William; Obre...",None,None,"[{""affiliation"": [], ""family"": ""Finak"", ""given...",None,None,"[{""DOI"": ""10.13039/100000057"", ""award"": [""R01 ...",National Institute of General Medical Sciences...,2.0,None,None,None,3,None,None,3,39,"[{""DOI"": ""10.1373/clinchem.2010.158618"", ""arti...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,New version,10.21956/gatesopenres.13917.r26579;10.21956/ga...,"[{""DOI"": ""10.12688/gatesopenres.12832.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.12832.2"", ""ISSN...",10.12688/gatesopenres.12832.2,10.12688,10.12688,gatesopenres.12832.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,crossref::10.12688/gatesopenres.16362.1,Gates Open Research,crossref,10.12688/gatesopenres.16362.1,10.12688/gatesopenres.16362.1,https://doi.org/10.12688/gatesopenres.16362.1,https://gatesopenresearch.org/articles/9-69/v1,https://gatesopenresearch.org/articles/9-69/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Mycobacterium tuberculosis growth inhibition b...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-09-09,None,2025-09-09,2025-09-09,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background There ...,Background There is a concern that SARS-CoV-2 ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-69/v1...,"Shaw, Jane A; Petersen, Caleb; Hiemstra, Andri...",None,None,"[{""affiliation"": [], ""family"": ""Shaw"", ""given""...",None,None,"[{""DOI"": ""10.13039/100000060"", ""award"": [""75N9...",National Institute of Allergy and Infectious D...,3.0,None,None,None,0,None,None,0,44,"[{""DOI"": ""10.1056/NEJMoa2119658"", ""article-tit...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.514.3,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16362.1"", ""ISSN...",10.12688/gatesopenres.16362.1,10.12688,10.12688,gatesopenres.16362.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
859,crossref::10.12688/gatesopenres.16361.1,Gates Open Research,crossref,10.12688/gatesopenres.16361.1,10.12688/gatesopenres.16361.1,https://doi.org/10.12688/gatesopenres.16361.1,https://gatesopenresearch.org/articles/9-64/v1,https://gatesopenresearch.org/articles/9-64/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,Maximising power with the minimum number of mo...,None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-11-21,2025-11-21,None,2025-08-27,None,2025-08-27,2025-08-27,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Power calculations are an essential com...,Power calculations are an essential component ...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-64/v1...,"Harvey, Gemma Francesca; Mechan, Frank; Prauli...",None,None,"[{""ORCID"": ""https://orcid.org/0009-0008-6041-3...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,13,"[{""DOI"": ""10.1038/nature15535"", ""article-title...","{""has-preprint"": [{""asserted-by"": ""subject"", ""...",10.12688/verixiv.953.1,,False,None,,None,None,,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.16361.1"", ""ISSN...",10.12688/gatesopenres.16361.1,10.12688,10.12688,gatesopenres.16361.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
860,crossref::10.12688/gatesopenres.15431.1,Gates Open Research,crossref,10.12688/gatesopenres.15431.1,10.12688/gatesopenres.15431.1,https://doi.org/10.12688/gatesopenres.15431.1,https://gatesopenresearch.org/articles/9-7/v1,https://gatesopenresearch.org/articles/9-7/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,A new application programming interface (API) ...,None,None,None,en,journal-article,None,journal-article,None,False,2025-03-11,None,2025-11-21,2025-11-21,None,2025-03-11,None,2025-03-11,2025-03-11,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>Background The escalating threat of AMR...,Background The escalating threat of AMR demand...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/9-7/v1/pdf,"Pillonetto, Marcelo; Kraft, Leticia; Ellen, St...",None,None,"[{""affiliation"": [], ""family"": ""Pillonetto"", ""...",None,None,"[{""award"": [""51618.554.31977.10122018""], ""awar...",Programa grand challenges explorations-brazil:...,1.0,None,None,None,0,None,None,0,19,"[{""article-title"": ""Usability and feasibility ...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/gatesopenres.16783.r39769;10.21956/ga...,None,None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15431.1"", ""ISSN...",10.12688/gatesopenres.15431.1,10.12688,10.12688,gatesopenres.15431.1,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles
861,crossref::10.12688/gatesopenres,Gates Open Research,crossref,10.12688/gatesopenres,10.12688/gatesopenres,https://doi.org/10.12688/gatesopenres,http://www.gatesopenresearch.org,http://www.gatesopenresearch.org,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,None,2572-4754,Gates Open Research,None,Gates Open Res,None,en,journal,None,journal,None,False,2017-11-06,None,2025-12-17,2025-12-17,None,None,None,None,None,NaN,created_date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,13,None,None,13,0,None,None,,,False,None,,None,None,,None,None,None,issn,49,None,"{""DOI"": ""10.12688/gatesopenres"", ""ISSN"": [""257...",10.12688/gatesopenres,10.12688,10.12688,gatesopenres,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org
862,crossref::10.12688/gatesopenres.15991.2,Gates Open Research,crossref,10.12688/gatesopenres.15991.2,10.12688/gatesopenres.15991.2,https://doi.org/10.12688/gatesopenres.15991.2,https://gatesopenresearch.org/articles/8-95/v2,https://gatesopenresearch.org/articles/8-95/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,Gates Open Research,None,None,2572-4754,"Single-blinded, stratified, dose ranging trial...",None,None,None,en,journal-article,None,journal-article,None,False,2025-11-21,None,2025-12-17,2025-12-17,None,2025-09-17,None,2025-09-17,2025-09-17,2025.0,issued_date,None,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,<ns3:p>\n Background Vitami...,Background Vitamin B12 is an essential cofacto...,"[{""URL"": ""https://gatesopenresearch.org/articl...",https://gatesopenresearch.org/articles/8-95/v2...,"Lweno, Omar; Reynolds, Victoria S.; Barberio, ...",None,None,"[{""affiliation"": [], ""family"": ""Lweno"", ""given...",None,None,"[{""award"": [""INV-016930""], ""award-info"": [{""aw...",Gates Foundation,1.0,None,None,None,0,None,None,0,37,"[{""DOI"": ""10.1093/jn/nxy201"", ""article-title"":...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,10.12688/gatesopenres.15991.1,None,New version,10.21956/gatesopenres.17759.r39860,"[{""DOI"": ""10.12688/gatesopenres.15991.1"", ""lab...",None,https://doi.org/10.12688/gatesopenres.crossmar...,issn,49,None,"{""DOI"": ""10.12688/gatesopenres.15991.2"", ""ISSN...",10.12688/gatesopenres.15991.2,10.12688,10.12688,gatesopenres.15991.2,10.12688/gatesopenres,10.12688/gatesopenres,gatesopenresearch.org,gatesopenresearch.org/articles

In [107]:
Gates_df['funders_flat']

0                      Bill and Melinda Gates Foundation
1                      Bill and Melinda Gates Foundation
2      Bill and Melinda Gates Foundation; Swiss Agenc...
3      The Special Programme for Research and Trainin...
4      National Institute of General Medical Sciences...
                             ...
858    National Institute of Allergy and Infectious D...
859                                     Gates Foundation
860    Programa grand challenges explorations-brazil:...
861                                                 None
862                                     Gates Foundation
Name: funders_flat, Length: 863, dtype: object

In [108]:
# Optional: Group similar names together
df_funders = Gates_df['funders_flat'].dropna().str.split(';').explode().str.strip()

# # Normalize common variants
# df_funders = df_funders.replace({
#     "Gates Foundation": "Bill and Melinda Gates Foundation"
# })

final_counts = df_funders.value_counts().to_frame()
final_counts.head(10)

                                                    count
funders_flat
Bill and Melinda Gates Foundation                     703
Gates Foundation                                       52
National Institutes of Health                          42
United States Agency for International Development     36
Wellcome Trust                                         28
Medical Research Council                               26
South African Medical Research Council                 17
Department for International Development, UK Go...     14
Bill & Melinda Gates Foundation                        11
Children's Investment Fund Foundation                  10

# HAL

In [109]:
# HAL_df, HAL_summary = get_server_data("HAL")

In [110]:
HAL_parent_df, HAL_parent_summary = analyze_parent_data("HAL", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: HAL
=================================================================
  > Total Parent Groups:     1,030,229
  > Total Versions Found:    1,052,746
  > Unique Parent DOIs:      27,498
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for HAL:
-----------------------------------
  1 version(s):     1,009,984 groups
  2 version(s):     18,605 groups
  3 version(s):     1,302 groups
  4 version(s):     220 groups
  5 version(s):     58 groups
  6 version(s):     24 groups
  7 version(s):     17 groups
  8 version(s):     4 groups
  9 version(s):     3 groups
  10 version(s):    3 groups
  11 version(s):    3 groups
  12 version(s):    2 groups
  14 version(s):    1 groups
  17 version(s):    1 groups
  18 version(s):    2 groups

  Average versions per parent: 1.02

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
HAL                                         1026395
arXiv                                          1582
ResearchGate                                    553
SSRN                                            500
RePEc: Research Papers in Economics             339
AgEcon Search                                   282
HAL; RePEc: Research Papers in Economics        147
HAL; Munich Personal RePEc Archive              109
Munich Personal RePEc Archive                   108
bioRxiv                                          36

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>                   1002738
10.13140/rg               3004
10.5281/zenodo            2548
10.15122/isbn             2067
10.48611/isbn              732
10.48465/fa                676
10.13140/2                 617
10.1016/j                  300
10.14758/set-revue         280
10.18429/jacow-ipac        268



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
hal.science                 573114
hal.inrae.fr                123447
hal.archives-ouvertes.fr     52914
hal.univ-lorraine.fr         24583
theses.hal.science           21476
inria.hal.science            12104
sciencespo.hal.science       11491
hal.parisnanterre.fr          8626
hal.univ-lille.fr             7970
univ-lyon3.hal.science        7885


=================================================================
 COMPLETED: HAL
=================================================================

# HANS Publication PrePrints

In [111]:
HANS_df, HANS_summary = get_server_data("HANS_Publication_PrePrints")

==================================================
 SERVER ANALYSIS: HANS_PUBLICATION_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    75
  > Cleaned shape:  (75, 90)
  > Unique DOIs:    75
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12677/hanspreprints    75
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
hanspub.org    75
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12677    75
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
4945    75
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Hans Publishers    75
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
HANS Publication PrePrints    75
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    75
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    75
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2472-1638; 2472-162X    75
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    75
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    75
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR HANS_PUBLICATION_PREPRINTS
==================================================

In [112]:
HANS_parent_df, HANS_parent_summary = analyze_parent_data("HANS Publication PrePrints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: HANS PUBLICATION PREPRINTS
=================================================================
  > Total Parent Groups:     75
  > Total Versions Found:    75
  > Unique Parent DOIs:      75
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for HANS Publication PrePrints:
-----------------------------------
  1 version(s):     75 groups

  Average versions per parent: 1.00

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
HANS Publication PrePrints    75

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12677/hanspreprints    75



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
hanspub.org    75


=================================================================
 COMPLETED: HANS PUBLICATION PREPRINTS
=================================================================

# HRB Open Research

In [113]:
HRB_df, HRB_summary = get_server_data("HRB_Open_Research")

==================================================
 SERVER ANALYSIS: HRB_OPEN_RESEARCH
==================================================
  > Files found:    1
  > Raw records:    1012
  > Cleaned shape:  (1012, 90)
  > Unique DOIs:    1012
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/hrbopenres    1012
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
hrbopenresearch.org    1012
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    1012
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    1012
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    1012
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
HRB Open Research    1012
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1012
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    1012
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2515-4826    1012
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    1012
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    1012
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR HRB_OPEN_RESEARCH
==================================================

In [114]:
HRB_parent_df, HRB_parent_summary = analyze_parent_data("HRB Open Research", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: HRB OPEN RESEARCH
=================================================================
  > Total Parent Groups:     647
  > Total Versions Found:    1,007
  > Unique Parent DOIs:      647
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for HRB Open Research:
-----------------------------------
  1 version(s):     342 groups
  2 version(s):     254 groups
  3 version(s):     47 groups
  4 version(s):     4 groups

  Average versions per parent: 1.56

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
HRB Open Research    646
SSRN                   1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/hrbopenres    647



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
hrbopenresearch.org    647


=================================================================
 COMPLETED: HRB OPEN RESEARCH
=================================================================

# Humanities Commons CORE

In [115]:
CORE_df, CORE_summary = get_server_data("Humanities_Commons_CORE")

==================================================
 SERVER ANALYSIS: HUMANITIES_COMMONS_CORE
==================================================
  > Files found:    2
  > Raw records:    29584
  > Cleaned shape:  (29584, 90)
  > Unique DOIs:    29584
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.17613/m    2950
10.17613/j     289
10.17613/s     279
10.17613/e     273
10.17613/b     272
10.17613/r     270
10.17613/z     270
10.17613/y     270
10.17613/w     267
10.17613/t     266
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
works.hcommons.org    20522
hcommons.org           9062
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.17613    29584
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    29584
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
unknown                                     9892
Humanities Commons                          9053
Knowledge Commons                           2573
Routledge                                    306
Michigan State University College of Law     188
Brill                                        141
SLS Working Papers                           136
Academia.edu                                 133
Ian Willis                                   124
Oxford University Press                      121
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    29584
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    29584
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    29584
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    29584
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Text                    23550
Other                    5349
ConferenceProceeding      685
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
Book section          5663
Article               3751
Essay                 3712
                      2466
Presentation          1934
Online publication    1289
Abstract              1263
Blog Post             1252
Thesis                1036
Syllabus              1010
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR HUMANITIES_COMMONS_CORE
==================================================

In [116]:
CORE_parent_df, CORE_parent_summary = analyze_parent_data("Humanities Commons CORE", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: HUMANITIES COMMONS CORE
=================================================================
  > Total Parent Groups:     16,685
  > Total Versions Found:    29,313
  > Unique Parent DOIs:      16,685
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Humanities Commons CORE:
-----------------------------------
  1 version(s):     5,298 groups
  2 version(s):     10,710 groups
  3 version(s):     318 groups
  4 version(s):     288 groups
  5 version(s):     21 groups
  6 version(s):     26 groups
  7 version(s):     4 groups
  8 version(s):     9 groups
  9 version(s):     2 groups
  10 version(s):    3 groups
  12 version(s):    3 groups
  14 version(s):    2 groups
  16 version(s):    1 groups

  Average versions per parent: 1.76

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Humanities Commons CORE            16631
SSRN                                  16
HAL; Humanities Commons CORE           8
Open Science Framework                 8
SocArXiv                               7
Zenodo                                 2
AfricArXiv                             2
ResearchGate                           2
Humanities Commons CORE; Zenodo        2
Authorea Inc.                          1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.17613/m    2764
10.17613/j     156
10.17613/a     148
10.17613/g     148
10.17613/s     147
10.17613/b     140
10.17613/n     137
10.17613/d     137
10.17613/t     136
10.17613/c     135



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
hcommons.org          8572
works.hcommons.org    8113


=================================================================
 COMPLETED: HUMANITIES COMMONS CORE
=================================================================

# IACR Cryptology ePrint Archive

In [117]:
IACR_df, IACR_summary = get_server_data("IACR_Cryptology_ePrint_Archive")

==================================================
 SERVER ANALYSIS: IACR_CRYPTOLOGY_EPRINT_ARCHIVE
==================================================
  > Files found:    1
  > Raw records:    11904
  > Cleaned shape:  (11904, 90)
  > Unique DOIs:    208
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>                  11696
10.48550/arxiv           72
10.13140/rg              28
10.60882/cispa           25
10.5281/zenodo           18
10.1007/97               11
10.3929/ethz-b-           5
10.7916/d                 3
10.4230/dagsemproc        3
10.3217/jucs-             3
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
eprint.iacr.org         8228
dblp.uni-trier.de       3493
csrc.nist.gov             15
cacr.uwaterloo.ca         12
researchgate.net           7
caislab.kaist.ac.kr        6
131002.net                 6
cr.yp.to                   6
apps.dtic.mil              5
people.csail.mit.edu       5
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        11696
10.48550       72
10.13140       30
10.60882       25
10.5281        18
10.1007        12
10.3929         7
10.1145         4
10.4230         3
10.7916         3
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    11904
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    11904
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    11904
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    11904
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    11904
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    11904
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
preprint    11598
article       304
review          2
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    11904
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR IACR_CRYPTOLOGY_EPRINT_ARCHIVE
==================================================

In [118]:
IACR_parent_df, IACR_parent_summary = analyze_parent_data("IACR Cryptology ePrint Archive", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: IACR CRYPTOLOGY EPRINT ARCHIVE
=================================================================
  > Total Parent Groups:     10,430
  > Total Versions Found:    10,679
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for IACR Cryptology ePrint Archive:
-----------------------------------
  1 version(s):     10,196 groups
  2 version(s):     224 groups
  3 version(s):     8 groups
  5 version(s):     1 groups
  6 version(s):     1 groups

  Average versions per parent: 1.02

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
IACR Cryptology ePrint Archive                                   10307
arXiv                                                              110
HAL                                                                  5
ResearchGate                                                         3
SSRN                                                                 2
IACR Cryptology ePrint Archive; Munich Personal RePEc Archive        1
HAL; IACR Cryptology ePrint Archive                                  1
EasyChair preprint                                                   1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    10430



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
eprint.iacr.org         7938
dblp.uni-trier.de       2316
csrc.nist.gov             15
cacr.uwaterloo.ca         12
researchgate.net           7
caislab.kaist.ac.kr        6
131002.net                 6
cr.yp.to                   6
apps.dtic.mil              5
people.csail.mit.edu       5


=================================================================
 COMPLETED: IACR CRYPTOLOGY EPRINT ARCHIVE
=================================================================

# INA-Rxiv

In [119]:
INA_df, INA_summary = get_server_data("INA-Rxiv")

==================================================
 SERVER ANALYSIS: INA-RXIV
==================================================
  > Files found:    1
  > Raw records:    17837
  > Cleaned shape:  (17837, 90)
  > Unique DOIs:    17837
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31227/osf    15764
10.31219/osf      784
10.31234/osf      448
10.31228/osf      227
10.31235/osf      219
10.31223/osf      183
10.31230/osf       60
10.31220/osf       55
10.31229/osf       48
10.31225/osf       44
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    17837
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31227    15764
10.31219      784
10.31234      448
10.31228      227
10.31235      219
10.31223      183
10.31230       60
10.31220       55
10.31229       48
10.31225       44
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    17599
29705      183
242         55
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             17599
California Digital Library (CDL)      183
CABI Publishing                        55
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    17837
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    17837
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
INA-Rxiv    17837
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    17837
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    17837
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    17837
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR INA-RXIV
==================================================

In [120]:
INA_parent_df, INA_parent_summary = analyze_parent_data("INA-Rxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: INA-RXIV
=================================================================
  > Total Parent Groups:     15,055
  > Total Versions Found:    20,750
  > Unique Parent DOIs:      15,055
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for INA-Rxiv:
-----------------------------------
  1 version(s):     11,033 groups
  2 version(s):     3,072 groups
  3 version(s):     711 groups
  4 version(s):     134 groups
  5 version(s):     42 groups
  6 version(s):     23 groups
  7 version(s):     7 groups
  8 version(s):     6 groups
  9 version(s):     5 groups
  10 version(s):    5 groups
  12 version(s):    3 groups
  13 version(s):    2 groups
  14 version(s):    1 groups
  17 version(s):    1 groups
  18 version(s):    2 groups
  19 version(s):    1 groups
  20 version(s):    2 groups
  21 version(s):    1 groups
  22 version(s):    1 groups
  27 version(s):    1 groups
  50 version(s):    1 groups
  56 version(s):    1 groups

  Average versions per parent: 1.38

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
INA-Rxiv                                            12091
INA-Rxiv; Open Science Framework                     2694
Open Science Framework                                200
INA-Rxiv; Open Science Framework; ResearchGate         10
Thesis Commons                                          9
ResearchGate                                            9
EdArXiv                                                 7
INA-Rxiv; Zenodo                                        4
SSRN                                                    4
INA-Rxiv; Open Science Framework; Thesis Commons        3

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31227/osf    15055



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    15055


=================================================================
 COMPLETED: INA-RXIV
=================================================================

# IndiaRxiv

In [121]:
IndiaRxiv_df, IndiaRxiv_summary = get_server_data("IndiaRxiv")

==================================================
 SERVER ANALYSIS: INDIARXIV
==================================================
  > Files found:    2
  > Raw records:    142
  > Cleaned shape:  (142, 90)
  > Unique DOIs:    142
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.35543/osf          135
10.35543/indiarxiv      7
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io             135
ops.iihr.res.in      7
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.35543    142
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
34961    98
15934    44
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Open Access India          98
Center for Open Science    44
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None                                                  141
IndiaRxiv - Preprints Repository Service for India      1
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    142
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
IndiaRxiv    135
None           7
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None         141
2583-0007      1
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content     141
journal-article      1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    141
None          1
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR INDIARXIV
==================================================

In [122]:
IndiaRxiv_parent_df, IndiaRxiv_parent_summary = analyze_parent_data("IndiaRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: INDIARXIV
=================================================================
  > Total Parent Groups:     103
  > Total Versions Found:    110
  > Unique Parent DOIs:      103
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for IndiaRxiv:
-----------------------------------
  1 version(s):     96 groups
  2 version(s):     7 groups

  Average versions per parent: 1.07

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
IndiaRxiv          98
ChemRxiv            1
arXiv               1
engrXiv             1
Research Square     1
Thesis Commons      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.35543/osf          97
10.35543/indiarxiv     6



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io             97
ops.iihr.res.in     6


=================================================================
 COMPLETED: INDIARXIV
=================================================================

# JMIR Preprints

In [17]:
JMIR_df, JMIR_summary = get_server_data("JMIR_Preprints")

==================================================
 SERVER ANALYSIS: JMIR_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    37631
  > Cleaned shape:  (37631, 90)
  > Unique DOIs:    37631
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.2196/preprints    37630
10.2196/iproc            1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.jmir.org    37631
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.2196    37631
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
1010    37631
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
JMIR Publications Inc.    37631
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    37631
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    37631
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Journal of Medical Internet Research    10728
JMIR Research Protocols                  5024
JMIR Formative Research                  4031
JMIR mHealth and uHealth                 2960
JMIR Public Health and Surveillance      2171
JMIR Medical Informatics                 1810
JMIR Mental Health                       1756
JMIR Human Factors                       1058
JMIR Medical Education                    899
JMIR Serious Games                        762
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    37631
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    37631
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    37631
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR JMIR_PREPRINTS
==================================================

In [18]:
JMIR_parent_df, JMIR_parent_summary = analyze_parent_data("JMIR Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: JMIR PREPRINTS
=================================================================
  > Total Parent Groups:     35,807
  > Total Versions Found:    37,218
  > Unique Parent DOIs:      35,807
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for JMIR Preprints:
-----------------------------------
  1 version(s):     34,506 groups
  2 version(s):     1,234 groups
  3 version(s):     59 groups
  4 version(s):     5 groups
  5 version(s):     2 groups
  37 version(s):    1 groups

  Average versions per parent: 1.04

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
JMIR Preprints              35450
Research Square               107
medRxiv                        86
arXiv                          53
SSRN                           35
Preprints.org                  16
PsyArXiv                       13
JMIR Preprints; PsyArXiv        7
JMIR Preprints; arXiv           5
bioRxiv                         4

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.2196/preprints    35806
10.2196/iproc            1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.jmir.org    35807


=================================================================
 COMPLETED: JMIR PREPRINTS
=================================================================

# Jxiv

In [19]:
Jxiv_df, Jxiv_summary = get_server_data("Jxiv")

==================================================
 SERVER ANALYSIS: JXIV
==================================================
  > Files found:    1
  > Raw records:    902
  > Cleaned shape:  (902, 90)
  > Unique DOIs:    902
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.51094/jxiv    902
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
jxiv.jst.go.jp    902
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.51094    902
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    902
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Jxiv, JST Preprint Server    902
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    902
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    902
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    902
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    902
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
info:eu-repo/semantics/preprint    902
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
application/pdf                                                      901
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet      1
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR JXIV
==================================================

In [20]:
Jxiv_parent_df, Jxiv_parent_summary = analyze_parent_data("Jxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: JXIV
=================================================================
  > Total Parent Groups:     757
  > Total Versions Found:    772
  > Unique Parent DOIs:      757
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Jxiv:
-----------------------------------
  1 version(s):     746 groups
  2 version(s):     10 groups
  6 version(s):     1 groups

  Average versions per parent: 1.02

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Jxiv               753
SSRN                 2
Research Square      2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.51094/jxiv    757



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
jxiv.jst.go.jp    757


=================================================================
 COMPLETED: JXIV
=================================================================

# Keldysh Institute Preprints

In [21]:
Keldysh_df, Keldysh_summary = get_server_data("Keldysh_Institute_Preprints")

==================================================
 SERVER ANALYSIS: KELDYSH_INSTITUTE_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    1258
  > Cleaned shape:  (1258, 90)
  > Unique DOIs:    1258
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.20948/prepr-       1257
10.20948/preprints       1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
keldysh.ru            1257
library.keldysh.ru       1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.20948    1258
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
8521    1258
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Keldysh Institute of Applied Mathematics    1258
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
Keldysh Institute Preprints    1257
None                              1
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1258
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    1258
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2071-2898; 2071-2901    1258
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    1257
journal               1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    1258
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR KELDYSH_INSTITUTE_PREPRINTS
==================================================

In [22]:
Keldysh_parent_df, Keldysh_parent_summary = analyze_parent_data("Keldysh Institute Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: KELDYSH INSTITUTE PREPRINTS
=================================================================
  > Total Parent Groups:     1,193
  > Total Versions Found:    1,257
  > Unique Parent DOIs:      1,193
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Keldysh Institute Preprints:
-----------------------------------
  1 version(s):     1,135 groups
  2 version(s):     54 groups
  3 version(s):     3 groups
  5 version(s):     1 groups

  Average versions per parent: 1.05

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Keldysh Institute Preprints    1185
arXiv                             8

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.20948/prepr-       1192
10.20948/preprints       1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
keldysh.ru            1192
library.keldysh.ru       1


=================================================================
 COMPLETED: KELDYSH INSTITUTE PREPRINTS
=================================================================

# LatArXiv

In [23]:
LatArXiv_df, LatArXiv_summary = get_server_data("LatArXiv")

==================================================
 SERVER ANALYSIS: LATARXIV
==================================================
  > Files found:    1
  > Raw records:    125
  > Cleaned shape:  (125, 90)
  > Unique DOIs:    125
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.62059/latarxiv    125
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.latarxiv.org    125
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.62059    125
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
48409    125
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Paideia Studio (publications)    125
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    125
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    125
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    125
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    125
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    125
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    125
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR LATARXIV
==================================================

In [24]:
LatArXiv_parent_df, LatArXiv_parent_summary = analyze_parent_data("LatArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: LATARXIV
=================================================================
  > Total Parent Groups:     115
  > Total Versions Found:    118
  > Unique Parent DOIs:      115
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for LatArXiv:
-----------------------------------
  1 version(s):     112 groups
  2 version(s):     3 groups

  Average versions per parent: 1.03

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
LatArXiv            114
SciELO Preprints      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.62059/latarxiv    115



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.latarxiv.org    115


=================================================================
 COMPLETED: LATARXIV
=================================================================

# Law Archive

In [25]:
Law_Archive_df, Law_Archive_summary = get_server_data("Law_Archive")

==================================================
 SERVER ANALYSIS: LAW_ARCHIVE
==================================================
  > Files found:    1
  > Raw records:    1808
  > Cleaned shape:  (1808, 90)
  > Unique DOIs:    1808
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31228/osf    837
10.31219/osf    470
10.31227/osf    241
10.31234/osf    175
10.31235/osf     38
10.31231/osf     17
10.31223/osf     12
10.31224/osf      6
10.31230/osf      6
10.31229/osf      3
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    1808
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31228    837
10.31219    470
10.31227    241
10.31234    175
10.31235     38
10.31231     17
10.31223     12
10.31224      6
10.31230      6
10.31229      3
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    1794
29705      12
33966       2
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             1794
California Digital Library (CDL)      12
Open Engineering Inc                   2
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    1808
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1808
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Law Archive    1387
LawArXiv        421
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    1808
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    1808
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    1808
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR LAW_ARCHIVE
==================================================

In [26]:
Law_Archive_parent_df, Law_Archive_parent_summary = analyze_parent_data("Law Archive", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: LAW ARCHIVE
=================================================================
  > Total Parent Groups:     1,344
  > Total Versions Found:    2,212
  > Unique Parent DOIs:      1,344
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Law Archive:
-----------------------------------
  1 version(s):     634 groups
  2 version(s):     578 groups
  3 version(s):     124 groups
  4 version(s):     4 groups
  5 version(s):     2 groups
  11 version(s):    1 groups
  13 version(s):    1 groups

  Average versions per parent: 1.65

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Law Archive                            681
Law Archive; Open Science Framework    471
Open Science Framework                 144
SSRN                                    32
arXiv                                    5
EdArXiv                                  3
CrimRxiv                                 2
Law Archive; arXiv                       2
EdArXiv; Law Archive                     2
Open Science Framework; SocArXiv         1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31228/osf    1095
10.31219/osf     249



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    1344


=================================================================
 COMPLETED: LAW ARCHIVE
=================================================================

# LIS Scholarship Archive

In [27]:
LIS_df, LIS_summary = get_server_data("LIS_Scholarship_Archive")

==================================================
 SERVER ANALYSIS: LIS_SCHOLARSHIP_ARCHIVE
==================================================
  > Files found:    1
  > Raw records:    397
  > Cleaned shape:  (397, 90)
  > Unique DOIs:    397
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31229/osf    290
10.31219/osf     44
10.31227/osf     21
10.31228/osf      9
10.31235/osf      7
10.31234/osf      7
10.31223/osf      7
10.31230/osf      5
10.31225/osf      3
10.31220/osf      2
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    397
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31229    290
10.31219     44
10.31227     21
10.31228      9
10.31235      7
10.31234      7
10.31223      7
10.31230      5
10.31225      3
10.31220      2
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    388
29705      7
242        2
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             388
California Digital Library (CDL)      7
CABI Publishing                       2
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    397
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    397
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
LIS Scholarship Archive    397
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    397
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    397
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    397
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR LIS_SCHOLARSHIP_ARCHIVE
==================================================

In [28]:
LIS_parent_df, LIS_parent_summary = analyze_parent_data("LIS Scholarship Archive", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: LIS SCHOLARSHIP ARCHIVE
=================================================================
  > Total Parent Groups:     328
  > Total Versions Found:    488
  > Unique Parent DOIs:      328
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for LIS Scholarship Archive:
-----------------------------------
  1 version(s):     201 groups
  2 version(s):     97 groups
  3 version(s):     27 groups
  4 version(s):     3 groups

  Average versions per parent: 1.49

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
LIS Scholarship Archive                            217
LIS Scholarship Archive; Open Science Framework     96
Open Science Framework                               3
Thesis Commons                                       3
Frenxiv                                              2
LIS Scholarship Archive; ResearchGate                1
SSRN                                                 1
Zenodo                                               1
EdArXiv; LIS Scholarship Archive                     1
EdArXiv                                              1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31229/osf    328



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    328


=================================================================
 COMPLETED: LIS SCHOLARSHIP ARCHIVE
=================================================================

# LSE Research Online Documents on Economics

In [29]:
LSE_df, LSE_summary = get_server_data("LSE_Research_Online_Documents_on_Economics")

==================================================
 SERVER ANALYSIS: LSE_RESEARCH_ONLINE_DOCUMENTS_ON_ECONOMICS
==================================================
  > Files found:    1
  > Raw records:    119
  > Cleaned shape:  (119, 90)
  > Unique DOIs:    12
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>           107
10.5089/97       3
10.1429/85       2
10.7208/97       1
10.2760/27       1
10.1425/84       1
10.60692/b       1
10.13140/rg      1
10.7916/d        1
10.1108/s        1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
ideas.repec.org          74
eprints.lse.ac.uk        24
cep.lse.ac.uk             5
sticerd.lse.ac.uk         3
elibrary.imf.org          2
foundation.org.uk         1
cris.unibo.it             1
europepmc.org             1
carnegieendowment.org     1
dialnet.unirioja.es       1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        107
10.5089       3
10.1429       2
10.7208       1
10.2760       1
10.1425       1
10.60692      1
10.13140      1
10.7916       1
10.1108       1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    119
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    119
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    119
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    119
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    119
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    119
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article     117
review        1
preprint      1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    119
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR LSE_RESEARCH_ONLINE_DOCUMENTS_ON_ECONOMICS
==================================================

In [30]:
LSE_parent_df, LSE_parent_summary = analyze_parent_data("LSE Research Online Documents on Economics", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: LSE RESEARCH ONLINE DOCUMENTS ON ECONOMICS
=================================================================
  > Total Parent Groups:     110
  > Total Versions Found:    144
  > Unique Parent DOIs:      11
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for LSE Research Online Documents on Economics:
-----------------------------------
  1 version(s):     86 groups
  2 version(s):     15 groups
  3 version(s):     8 groups
  4 version(s):     1 groups

  Average versions per parent: 1.31

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
LSE Research Online Documents on Economics                        86
SSRN                                                              14
RePEc: Research Papers in Economics                                9
EconStor Preprints; LSE Research Online Documents on Economics     1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>          99
10.5089/97     3
10.1429/85     2
10.1108/s      1
10.7208/97     1
10.60692/b     1
10.2760/27     1
10.1425/84     1
10.7916/d      1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
ideas.repec.org          67
eprints.lse.ac.uk        24
cep.lse.ac.uk             4
sticerd.lse.ac.uk         3
elibrary.imf.org          2
carnegieendowment.org     1
files.lsecities.net       1
bura.brunel.ac.uk         1
discovery.ucl.ac.uk       1
foundation.org.uk         1


=================================================================
 COMPLETED: LSE RESEARCH ONLINE DOCUMENTS ON ECONOMICS
=================================================================

# MarXiv

In [31]:
MarXiv_df, MarXiv_summary = get_server_data("MarXiv")

==================================================
 SERVER ANALYSIS: MARXIV
==================================================
  > Files found:    1
  > Raw records:    508
  > Cleaned shape:  (508, 90)
  > Unique DOIs:    508
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31230/osf    317
10.31227/osf     60
10.31219/osf     57
10.31235/osf     23
10.31228/osf     19
10.31234/osf     13
10.31223/osf      9
10.31220/osf      5
10.31225/osf      5
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    508
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31230    317
10.31227     60
10.31219     57
10.31235     23
10.31228     19
10.31234     13
10.31223      9
10.31220      5
10.31225      5
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    494
29705      9
242        5
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             494
California Digital Library (CDL)      9
CABI Publishing                       5
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    508
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    508
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
MarXiv    508
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    508
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    508
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    508
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR MARXIV
==================================================

In [32]:
MarXiv_parent_df, MarXiv_parent_summary = analyze_parent_data("MarXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: MARXIV
=================================================================
  > Total Parent Groups:     509
  > Total Versions Found:    672
  > Unique Parent DOIs:      509
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for MarXiv:
-----------------------------------
  1 version(s):     360 groups
  2 version(s):     135 groups
  3 version(s):     14 groups

  Average versions per parent: 1.32

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
MarXiv                            489
MarXiv; Open Science Framework     17
INA-Rxiv                            1
Open Science Framework              1
EdArXiv                             1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31230/osf    476
10.17605/osf     33



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io        476
marxiv.org     33


=================================================================
 COMPLETED: MARXIV
=================================================================

# MediArXiv

In [33]:
MediArXiv_df, MediArXiv_summary = get_server_data("MediArXiv")

==================================================
 SERVER ANALYSIS: MEDIARXIV
==================================================
  > Files found:    1
  > Raw records:    309
  > Cleaned shape:  (309, 90)
  > Unique DOIs:    309
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.33767/osf    306
10.31219/osf      3
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    309
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.33767    306
10.31219      3
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    309
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    309
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    309
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    309
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
MediArXiv    309
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    309
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    309
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    309
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR MEDIARXIV
==================================================

In [34]:
MediArXiv_parent_df, MediArXiv_parent_summary = analyze_parent_data("MediArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: MEDIARXIV
=================================================================
  > Total Parent Groups:     277
  > Total Versions Found:    299
  > Unique Parent DOIs:      277
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for MediArXiv:
-----------------------------------
  1 version(s):     260 groups
  2 version(s):     13 groups
  3 version(s):     3 groups
  4 version(s):     1 groups

  Average versions per parent: 1.08

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
MediArXiv                  270
SSRN                         2
Zenodo                       1
SocArXiv                     1
Humanities Commons CORE      1
arXiv                        1
APSA Preprints               1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.33767/osf    274
10.31219/osf      3



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    277


=================================================================
 COMPLETED: MEDIARXIV
=================================================================

# medRxiv

In [35]:
medRxiv_df, medRxiv_summary = get_server_data("medRxiv")

==================================================
 SERVER ANALYSIS: MEDRXIV
==================================================
  > Files found:    1
  > Raw records:    75743
  > Cleaned shape:  (75743, 90)
  > Unique DOIs:    75743
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.1101/20    74951
10.1101/19      792
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
medrxiv.org    75743
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.1101    75743
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
246    75743
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Cold Spring Harbor Laboratory    75743
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    75743
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
medRxiv    75743
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Infectious Diseases (except HIV/AIDS)    11979
Epidemiology                             10670
Public and Global Health                  6950
Neurology                                 4778
Genetic and Genomic Medicine              4624
Psychiatry and Clinical Psychology        3917
Cardiovascular Medicine                   3329
Health Informatics                        2944
Oncology                                  2382
Radiology and Imaging                     1584
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    75743
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    75743
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    75743
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR MEDRXIV
==================================================

In [36]:
medRxiv_parent_df, medRxiv_parent_summary = analyze_parent_data("medRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: MEDRXIV
=================================================================
  > Total Parent Groups:     74,055
  > Total Versions Found:    78,040
  > Unique Parent DOIs:      74,055
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for medRxiv:
-----------------------------------
  1 version(s):     70,734 groups
  2 version(s):     2,928 groups
  3 version(s):     246 groups
  4 version(s):     38 groups
  5 version(s):     94 groups
  6 version(s):     15 groups

  Average versions per parent: 1.05

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
medRxiv                   70925
Research Square            1194
SSRN                        693
eLife                       388
JMIR Preprints              305
Authorea Inc.                94
arXiv                        62
Wellcome Open Research       53
Preprints.org                39
F1000Research                38

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.1101/20    73277
10.1101/19      778



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
medrxiv.org    74055


=================================================================
 COMPLETED: MEDRXIV
=================================================================

# MetaArXiv

In [37]:
MetaArXiv_df, MetaArXiv_summary = get_server_data("MetaArXiv")

==================================================
 SERVER ANALYSIS: METAARXIV
==================================================
  > Files found:    1
  > Raw records:    880
  > Cleaned shape:  (880, 90)
  > Unique DOIs:    880
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31222/osf    851
10.31219/osf     11
10.31227/osf      7
10.31234/osf      4
10.31235/osf      4
10.31231/osf      1
10.31223/osf      1
10.31228/osf      1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    880
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31222    851
10.31219     11
10.31227      7
10.31234      4
10.31235      4
10.31231      1
10.31223      1
10.31228      1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    879
29705      1
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             879
California Digital Library (CDL)      1
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    880
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    880
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
MetaArXiv    880
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    880
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    880
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    880
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR METAARXIV
==================================================

In [38]:
MetaArXiv_parent_df, MetaArXiv_parent_summary = analyze_parent_data("MetaArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: METAARXIV
=================================================================
  > Total Parent Groups:     705
  > Total Versions Found:    907
  > Unique Parent DOIs:      705
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for MetaArXiv:
-----------------------------------
  1 version(s):     547 groups
  2 version(s):     124 groups
  3 version(s):     26 groups
  4 version(s):     6 groups
  5 version(s):     2 groups

  Average versions per parent: 1.29

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
MetaArXiv                            633
SSRN                                  14
MetaArXiv; Open Science Framework     10
Open Science Framework                10
SocArXiv                               6
eLife                                  5
Frenxiv                                4
Research Square                        3
Thesis Commons                         3
medRxiv                                2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31222/osf    705



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    705


=================================================================
 COMPLETED: METAARXIV
=================================================================

# MindRxiv

In [39]:
MindRxiv_df, MindRxiv_summary = get_server_data("MindRxiv")

==================================================
 SERVER ANALYSIS: MINDRXIV
==================================================
  > Files found:    1
  > Raw records:    335
  > Cleaned shape:  (335, 90)
  > Unique DOIs:    335
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31231/osf    258
10.31227/osf     38
10.31219/osf     15
10.31234/osf      7
10.31228/osf      5
10.31235/osf      5
10.31229/osf      4
10.31223/osf      2
10.31225/osf      1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    335
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31231    258
10.31227     38
10.31219     15
10.31234      7
10.31228      5
10.31235      5
10.31229      4
10.31223      2
10.31225      1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    333
29705      2
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             333
California Digital Library (CDL)      2
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    335
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    335
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
MindRxiv    335
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    335
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    335
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    335
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR MINDRXIV
==================================================

In [40]:
MindRxiv_parent_df, MindRxiv_parent_summary = analyze_parent_data("MindRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: MINDRXIV
=================================================================
  > Total Parent Groups:     281
  > Total Versions Found:    402
  > Unique Parent DOIs:      281
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for MindRxiv:
-----------------------------------
  1 version(s):     198 groups
  2 version(s):     45 groups
  3 version(s):     38 groups

  Average versions per parent: 1.43

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
MindRxiv                            245
MindRxiv; Open Science Framework     32
MindRxiv; PsyArXiv                    1
SSRN                                  1
EdArXiv; MindRxiv                     1
Open Science Framework                1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31231/osf    281



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    281


=================================================================
 COMPLETED: MINDRXIV
=================================================================

# MNI Open Research

In [41]:
MNI_df, MNI_summary = get_server_data("MNI_Open_Research")

==================================================
 SERVER ANALYSIS: MNI_OPEN_RESEARCH
==================================================
  > Files found:    1
  > Raw records:    20
  > Cleaned shape:  (20, 90)
  > Unique DOIs:    20
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/mniopenres    20
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
mniopenresearch.org    20
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    20
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    20
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    20
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
MNI Open Research    19
None                  1
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    20
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    20
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2515-5059    20
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    19
journal             1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    20
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR MNI_OPEN_RESEARCH
==================================================

In [42]:
MNI_parent_df, MNI_parent_summary = analyze_parent_data("MNI Open Research", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: MNI OPEN RESEARCH
=================================================================
  > Total Parent Groups:     13
  > Total Versions Found:    19
  > Unique Parent DOIs:      13
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for MNI Open Research:
-----------------------------------
  1 version(s):     7 groups
  2 version(s):     6 groups

  Average versions per parent: 1.46

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
MNI Open Research    13

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/mniopenres    13



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
mniopenresearch.org    13


=================================================================
 COMPLETED: MNI OPEN RESEARCH
=================================================================

# Munich Personal RePEc Archive

In [43]:
Munich_df, Munich_summary = get_server_data("Munich_Personal_RePEc_Archive")

/tmp/ipykernel_2758/1196196344.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  raw_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)

==================================================
 SERVER ANALYSIS: MUNICH_PERSONAL_REPEC_ARCHIVE
==================================================
  > Files found:    7
  > Raw records:    68692
  > Cleaned shape:  (68692, 90)
  > Unique DOIs:    1427
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>              67264
10.13140/rg         476
10.48550/arxiv      333
10.5281/zenodo      100
10.13140/2           60
10.22004/ag          25
10.6084/m            15
10.17605/osf         12
10.17192/es           7
10.1108/ijse-         7
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
theses.fr                    50259
None                         16501
doi.org                        899
escholarship.org               449
arxiv.org                      191
library.tue.nl                 120
hdl.handle.net                  70
eprints.iisc.ac.in              48
eref.uni-bayreuth.de            30
repositorio.banrep.gov.co       24
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        67263
10.13140      536
10.48550      333
10.5281       100
10.1111        39
10.1108        35
10.22004       25
10.6084        15
10.1080        15
10.57938       12
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    68692
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    68692
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    68692
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    68692
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    68692
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    68692
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
preprint    68692
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    68692
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR MUNICH_PERSONAL_REPEC_ARCHIVE
==================================================

In [44]:
Munich_parent_df, Munich_parent_summary = analyze_parent_data("Munich Personal RePEc Archive", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: MUNICH PERSONAL REPEC ARCHIVE
=================================================================
  > Total Parent Groups:     66,342
  > Total Versions Found:    68,859
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Munich Personal RePEc Archive:
-----------------------------------
  1 version(s):     63,971 groups
  2 version(s):     2,255 groups
  3 version(s):     100 groups
  4 version(s):     10 groups
  5 version(s):     3 groups
  7 version(s):     1 groups
  8 version(s):     2 groups

  Average versions per parent: 1.04

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Munich Personal RePEc Archive                                         64032
SSRN                                                                   1784
HAL; Munich Personal RePEc Archive                                      219
arXiv                                                                    90
RePEc: Research Papers in Economics                                      80
HAL                                                                      54
AgEcon Search                                                            33
Munich Personal RePEc Archive; RePEc: Research Papers in Economics       19
EconStor Preprints                                                        7
Social Science Open Access Repository                                     6

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    66342



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
theses.fr                    49660
None                         15891
escholarship.org               413
library.tue.nl                  97
hdl.handle.net                  64
eprints.iisc.ac.in              43
arxiv.org                       42
eref.uni-bayreuth.de            27
repositorio.banrep.gov.co       24
irihs.ihs.ac.at                 13


=================================================================
 COMPLETED: MUNICH PERSONAL REPEC ARCHIVE
=================================================================

# National Bureau of Economic Research

In [45]:
National_Bureau_df, National_Bureau_summary = get_server_data("National_Bureau_of_Economic_Research")

==================================================
 SERVER ANALYSIS: NATIONAL_BUREAU_OF_ECONOMIC_RESEARCH
==================================================
  > Files found:    5
  > Raw records:    1856
  > Cleaned shape:  (1856, 90)
  > Unique DOIs:    28
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>                      1828
10.7916/d                    9
10.7208/97                   5
10.5089/97                   3
10.1007/s                    3
10.17863/cam                 2
10.1002/10                   1
10.23668/psycharchives       1
10.13140/2                   1
10.57912/23                  1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
ideas.repec.org                  1337
eric.ed.gov                       485
econpapers.repec.org                7
ecsocman.hse.ru                     4
nber.org                            3
healthpolicy.fsi.stanford.edu       2
elibrary.imf.org                    2
europepmc.org                       2
iris.unive.it                       1
cir.nii.ac.jp                       1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        1828
10.7916        9
10.7208        5
10.5089        3
10.1007        3
10.17863       2
10.13140       2
10.1002        1
10.23668       1
10.57912       1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    1856
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    1856
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    1856
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1856
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    1856
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    1856
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article     1849
review         3
book           2
preprint       2
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    1856
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR NATIONAL_BUREAU_OF_ECONOMIC_RESEARCH
==================================================

In [46]:
National_Bureau_parent_df, National_Bureau_parent_summary = analyze_parent_data("National Bureau of Economic Research", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: NATIONAL BUREAU OF ECONOMIC RESEARCH
=================================================================
  > Total Parent Groups:     1,663
  > Total Versions Found:    2,265
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for National Bureau of Economic Research:
-----------------------------------
  1 version(s):     1,131 groups
  2 version(s):     474 groups
  3 version(s):     48 groups
  4 version(s):     8 groups
  5 version(s):     2 groups

  Average versions per parent: 1.36

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
National Bureau of Economic Research                                         1146
SSRN                                                                          381
RePEc: Research Papers in Economics                                            91
National Bureau of Economic Research; RePEc: Research Papers in Economics      28
AgEcon Search                                                                   5
Digital Access to Scholarship at Harvard (DASH) (Harvard University)            4
EconStor Preprints                                                              3
DSpace@MIT                                                                      2
RePEc: Research Papers in Economics; SSRN                                       1
HAL; National Bureau of Economic Research                                       1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    1663



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
ideas.repec.org                        1233
eric.ed.gov                             406
econpapers.repec.org                      6
healthpolicy.fsi.stanford.edu             2
ecsocman.hse.ru                           2
europepmc.org                             2
cir.nii.ac.jp                             1
ccrc.tc.columbia.edu                      1
fsi-live.s3.us-west-1.amazonaws.com       1
scholar.harvard.edu                       1


=================================================================
 COMPLETED: NATIONAL BUREAU OF ECONOMIC RESEARCH
=================================================================

# Nature Precedings

In [47]:
Nature_df, Nature_summary = get_server_data("Nature_Precedings")

==================================================
 SERVER ANALYSIS: NATURE_PRECEDINGS
==================================================
  > Files found:    1
  > Raw records:    5210
  > Cleaned shape:  (5210, 90)
  > Unique DOIs:    5210
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.1038/npre    5210
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
nature.com               3312
precedings.nature.com    1898
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.1038    5210
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
297    5210
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Springer Science and Business Media LLC    5210
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
Nature Precedings    5172
None                   38
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    5210
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    5210
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
1756-0357    5210
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    5172
journal              38
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    5210
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR NATURE_PRECEDINGS
==================================================

In [48]:
Nature_parent_df, Nature_parent_summary = analyze_parent_data("Nature Precedings", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: NATURE PRECEDINGS
=================================================================
  > Total Parent Groups:     3,153
  > Total Versions Found:    5,187
  > Unique Parent DOIs:      3,153
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Nature Precedings:
-----------------------------------
  1 version(s):     1,394 groups
  2 version(s):     1,576 groups
  3 version(s):     120 groups
  4 version(s):     51 groups
  5 version(s):     7 groups
  6 version(s):     2 groups
  10 version(s):    3 groups

  Average versions per parent: 1.65

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Nature Precedings                         3111
arXiv                                       23
Nature Precedings; arXiv                     8
SSRN                                         3
F1000Research                                2
bioRxiv                                      2
DSpace@MIT                                   1
viXra                                        1
Open Science Framework; Thesis Commons       1
PeerJ Preprints                              1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.1038/npre    3153



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
precedings.nature.com    1627
nature.com               1526


=================================================================
 COMPLETED: NATURE PRECEDINGS
=================================================================

# NewAddictionsX

In [49]:
NewAddictionsX_df, NewAddictionsX_summary = get_server_data("NewAddictionsX")

==================================================
 SERVER ANALYSIS: NEWADDICTIONSX
==================================================
  > Files found:    1
  > Raw records:    7
  > Cleaned shape:  (7, 90)
  > Unique DOIs:    7
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31219/osf    7
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    7
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31219    7
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    7
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    7
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    7
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    7
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
NewAddictionsX    7
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    7
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    7
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    7
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR NEWADDICTIONSX
==================================================

In [50]:
NewAddictionsX_parent_df, NewAddictionsX_parent_summary = analyze_parent_data("NewAddictionsX", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: NEWADDICTIONSX
=================================================================
  > Total Parent Groups:     4
  > Total Versions Found:    7
  > Unique Parent DOIs:      4
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for NewAddictionsX:
-----------------------------------
  1 version(s):     2 groups
  2 version(s):     1 groups
  3 version(s):     1 groups

  Average versions per parent: 1.75

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
NewAddictionsX    4

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31219/osf    4



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    4


=================================================================
 COMPLETED: NEWADDICTIONSX
=================================================================

# NutriXiv

In [51]:
NutriXiv_df, NutriXiv_summary = get_server_data("NutriXiv")

==================================================
 SERVER ANALYSIS: NUTRIXIV
==================================================
  > Files found:    1
  > Raw records:    94
  > Cleaned shape:  (94, 90)
  > Unique DOIs:    94
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31232/osf    70
10.31219/osf    12
10.31228/osf     6
10.31227/osf     5
10.31235/osf     1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    94
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31232    70
10.31219    12
10.31228     6
10.31227     5
10.31235     1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    94
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    94
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    94
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    94
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
NutriXiv    94
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    94
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    94
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    94
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR NUTRIXIV
==================================================

In [52]:
NutriXiv_parent_df, NutriXiv_parent_summary = analyze_parent_data("NutriXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: NUTRIXIV
=================================================================
  > Total Parent Groups:     83
  > Total Versions Found:    111
  > Unique Parent DOIs:      83
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for NutriXiv:
-----------------------------------
  1 version(s):     63 groups
  2 version(s):     16 groups
  3 version(s):     2 groups
  4 version(s):     1 groups
  6 version(s):     1 groups

  Average versions per parent: 1.34

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
NutriXiv                            66
NutriXiv; Open Science Framework    14
SSRN                                 1
IndiaRxiv                            1
Research Square                      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31232/osf    83



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    83


=================================================================
 COMPLETED: NUTRIXIV
=================================================================

# Open Research Africa

In [53]:
openra_df, openra_summary = get_server_data("Open_Research_Africa")

==================================================
 SERVER ANALYSIS: OPEN_RESEARCH_AFRICA
==================================================
  > Files found:    1
  > Raw records:    288
  > Cleaned shape:  (288, 90)
  > Unique DOIs:    288
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/aasopenres       222
10.12688/openresafrica     66
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
aasopenresearch.org       176
openresearchafrica.org    112
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    288
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    288
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    288
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
AAS Open Research       175
Open Research Africa    112
None                      1
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    288
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    288
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2515-9321    176
2752-6925    112
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    287
journal              1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    288
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR OPEN_RESEARCH_AFRICA
==================================================

In [54]:
openra_parent_df, openra_parent_summary = analyze_parent_data("Open Research Africa", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: OPEN RESEARCH AFRICA
=================================================================
  > Total Parent Groups:     180
  > Total Versions Found:    276
  > Unique Parent DOIs:      180
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Open Research Africa:
-----------------------------------
  1 version(s):     99 groups
  2 version(s):     66 groups
  3 version(s):     15 groups

  Average versions per parent: 1.53

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Open Research Africa    179
F1000Research             1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/aasopenres       134
10.12688/openresafrica     46



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
aasopenresearch.org       112
openresearchafrica.org     68


=================================================================
 COMPLETED: OPEN RESEARCH AFRICA
=================================================================

# Open Research Europe

In [55]:
openre_df, openre_summary = get_server_data("Open_Research_Europe")

==================================================
 SERVER ANALYSIS: OPEN_RESEARCH_EUROPE
==================================================
  > Files found:    1
  > Raw records:    1877
  > Cleaned shape:  (1877, 90)
  > Unique DOIs:    1877
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/openreseurope    1877
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
open-research-europe.ec.europa.eu    1877
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    1877
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    1877
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    1877
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
Open Research Europe    1877
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1877
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    1877
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2732-5121    1877
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    1877
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    1877
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR OPEN_RESEARCH_EUROPE
==================================================

In [56]:
openre_parent_df, openre_parent_summary = analyze_parent_data("Open Research Europe", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: OPEN RESEARCH EUROPE
=================================================================
  > Total Parent Groups:     1,115
  > Total Versions Found:    1,776
  > Unique Parent DOIs:      1,115
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Open Research Europe:
-----------------------------------
  1 version(s):     563 groups
  2 version(s):     455 groups
  3 version(s):     86 groups
  4 version(s):     10 groups
  5 version(s):     1 groups

  Average versions per parent: 1.59

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Open Research Europe    1110
arXiv                      3
SSRN                       1
Zenodo                     1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/openreseurope    1115



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
open-research-europe.ec.europa.eu    1115


=================================================================
 COMPLETED: OPEN RESEARCH EUROPE
=================================================================

# Open Science Framework

In [57]:
osf_df, osf_summary = get_server_data("Open_Science_Framework")

/tmp/ipykernel_2758/1196196344.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  raw_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)

==================================================
 SERVER ANALYSIS: OPEN_SCIENCE_FRAMEWORK
==================================================
  > Files found:    3
  > Raw records:    119481
  > Cleaned shape:  (119481, 90)
  > Unique DOIs:    119481
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31219/osf    101598
10.17605/osf     15829
10.31227/osf       649
10.31234/osf       434
10.31235/osf       421
10.31228/osf       213
10.31223/osf       110
10.31220/osf        56
10.31229/osf        55
10.31224/osf        47
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io               112545
doi.org                4615
psyarxiv.com           1327
eartharxiv.org          262
thesiscommons.org       216
marxiv.org              158
engrxiv.org             137
arabixiv.org             82
mindrxiv.org             46
agrixiv.org              40
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31219    101598
10.17605     15829
10.31227       649
10.31234       434
10.31235       421
10.31228       213
10.31223       110
10.31220        56
10.31229        55
10.31224        47
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    103473
None      15829
29705       110
242          56
33966        13
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science    103473
INA-Rxiv                     3127
Open Science Framework       2706
SocArXiv                     2405
PsyArXiv                     2229
OSF                          1496
OSF Registries               1438
LawArXiv                      757
EarthArXiv                    394
Thesis Commons                286
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    119481
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    119481
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Open Science Framework    103652
None                       15829
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    119481
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    103652
Text               12892
JournalArticle      2046
Preprint             719
Journal              172
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint                 103652
Preprint                  12892
Project                    1442
Pre-registration           1434
ProjectComponent             54
RegistrationComponent         7
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR OPEN_SCIENCE_FRAMEWORK
==================================================

In [58]:
osf_df['primary_domain'].value_counts()

primary_domain
osf.io               112545
doi.org                4615
psyarxiv.com           1327
eartharxiv.org          262
thesiscommons.org       216
marxiv.org              158
engrxiv.org             137
arabixiv.org             82
mindrxiv.org             46
agrixiv.org              40
paleorxiv.org            30
ecsarxiv.org             12
ezid.cdlib.org           11
Name: count, dtype: int64

In [59]:
osf_parent_df, osf_parent_summary = analyze_parent_data("Open Science Framework", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: OPEN SCIENCE FRAMEWORK
=================================================================
  > Total Parent Groups:     94,335
  > Total Versions Found:    110,556
  > Unique Parent DOIs:      94,335
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Open Science Framework:
-----------------------------------
  1 version(s):     83,245 groups
  2 version(s):     8,579 groups
  3 version(s):     1,634 groups
  4 version(s):     516 groups
  5 version(s):     158 groups
  6 version(s):     69 groups
  7 version(s):     42 groups
  8 version(s):     26 groups
  9 version(s):     20 groups
  10 version(s):    8 groups
  11 version(s):    7 groups
  12 version(s):    4 groups
  13 version(s):    3 groups
  14 version(s):    4 groups
  15 version(s):    3 groups
  17 version(s):    2 groups
  19 version(s):    1 groups
  20 version(s):    1 groups
  21 version(s):    1 groups
  22 version(s):    1 groups
  25 version(s):    1 groups
  28 version(s):    1 groups
  30 version(s):    1 groups
  36 version(s):    1 groups
  38 version(s):    1 groups
  47 version(s):    1 groups
  97 version(s):    1 groups
  107 version(s):   2 groups
  115 version(s):   1 groups
  210 version(s):   1 groups

  Average versions per parent: 1.17

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Open Science Framework                  91980
SSRN                                      516
arXiv                                     143
INA-Rxiv                                  127
PsyArXiv                                  125
Open Science Framework; ResearchGate      119
Open Science Framework; Zenodo            113
INA-Rxiv; Open Science Framework          100
ResearchGate                               91
SocArXiv                                   79

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31219/osf    91251
10.17605/osf     3084



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io            94104
doi.org             230
ezid.cdlib.org        1


=================================================================
 COMPLETED: OPEN SCIENCE FRAMEWORK
=================================================================

In [60]:
osf_parent_df[osf_parent_df['primary_domain']=='agrixiv.org']

Empty DataFrame
Columns: [dup_group_id_full, parent_record_id, parent_server_name, parent_doi, parent_url, parent_title, parent_authors, parent_date_first_seen, parent_year_first_seen, version_record_ids, version_dois, servers_with_counts, total_versions, first_version_date, last_version_date, most_recent_version_servers, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

In [61]:
osf_parent_df[osf_parent_df['primary_domain']=='engrxiv.org']

Empty DataFrame
Columns: [dup_group_id_full, parent_record_id, parent_server_name, parent_doi, parent_url, parent_title, parent_authors, parent_date_first_seen, parent_year_first_seen, version_record_ids, version_dois, servers_with_counts, total_versions, first_version_date, last_version_date, most_recent_version_servers, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

https://engrxiv.org/n7ajq  /  https://engrxiv.org/index.php/engrxiv/preprint/view/102 

10.17605/osf.io/n7ajq == https://doi.org/10.31224/osf.io/n7ajq

In [62]:
osf_parent_df[osf_parent_df['primary_domain']=='arabixiv.org']

Empty DataFrame
Columns: [dup_group_id_full, parent_record_id, parent_server_name, parent_doi, parent_url, parent_title, parent_authors, parent_date_first_seen, parent_year_first_seen, version_record_ids, version_dois, servers_with_counts, total_versions, first_version_date, last_version_date, most_recent_version_servers, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

In [63]:
osf_parent_df[osf_parent_df['primary_domain']=='thesiscommons.org']

Empty DataFrame
Columns: [dup_group_id_full, parent_record_id, parent_server_name, parent_doi, parent_url, parent_title, parent_authors, parent_date_first_seen, parent_year_first_seen, version_record_ids, version_dois, servers_with_counts, total_versions, first_version_date, last_version_date, most_recent_version_servers, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

# Organic Eprints

In [64]:
Organic_Eprints_df, Organic_Eprints_summary = get_server_data("Organic_Eprints")

==================================================
 SERVER ANALYSIS: ORGANIC_EPRINTS
==================================================
  > Files found:    1
  > Raw records:    13983
  > Cleaned shape:  (13983, 90)
  > Unique DOIs:    252
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>              13704
10.5281/zenodo       35
10.3220/rep          30
10.13140/rg          29
10.15454/1           22
10.5169/seals-       14
10.22004/ag          13
10.13140/2           10
10.3920/97            4
10.5073/jfk           3
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
None             12257
orgprints.org     1441
doi.org            260
                    24
bioaktuell.ch        1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        13704
10.17180       71
10.13140       39
10.15454       36
10.5281        35
10.3220        32
10.5169        14
10.22004       13
10.3920         4
10.5073         3
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    13983
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    13983
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    13983
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    13983
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    13983
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    13983
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article     13453
preprint      530
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    13983
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ORGANIC_EPRINTS
==================================================

In [65]:
Organic_parent_df, Organic_parent_summary = analyze_parent_data("Organic Eprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ORGANIC EPRINTS
=================================================================
  > Total Parent Groups:     13,510
  > Total Versions Found:    13,731
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Organic Eprints:
-----------------------------------
  1 version(s):     13,304 groups
  2 version(s):     192 groups
  3 version(s):     13 groups
  4 version(s):     1 groups

  Average versions per parent: 1.02

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Organic Eprints         13471
AgEcon Search              22
HAL                        10
HAL; Organic Eprints        7

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    13510



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
None             12079
orgprints.org     1406
                    24
bioaktuell.ch        1


=================================================================
 COMPLETED: ORGANIC EPRINTS
=================================================================

# Oroboros Instruments

In [66]:
Oroboros_Instruments_df, Oroboros_Instruments_summary = get_server_data("Oroboros_Instruments")

==================================================
 SERVER ANALYSIS: OROBOROS_INSTRUMENTS
==================================================
  > Files found:    2
  > Raw records:    95
  > Cleaned shape:  (95, 90)
  > Unique DOIs:    95
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.26124/mitofit    67
10.26124/bec        19
10.26124/becprep     9
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
wiki.oroboros.at                    37
bioenergetics-communications.org    28
mitofit.org                         27
mitoeagle.org                        3
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.26124    95
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    95
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
MitoFit Preprints                49
MitoFit Preprint Archives        18
Bioenergetics Communications     14
BEC preprints                     9
Bioenergetics Communication       4
Bionenergetics Communications     1
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    95
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    95
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    95
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    95
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Preprint          57
JournalArticle    18
DataPaper         13
Text               7
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None                        63
Preprint                    19
                            10
Consortium communication     1
CreativeWork                 1
Editorial                    1
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR OROBOROS_INSTRUMENTS
==================================================

/tmp/ipykernel_2758/1196196344.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  raw_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)

In [67]:
Oroboros_parent_df, Oroboros_parent_summary = analyze_parent_data("Oroboros Instruments", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: OROBOROS INSTRUMENTS
=================================================================
  > Total Parent Groups:     68
  > Total Versions Found:    89
  > Unique Parent DOIs:      68
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Oroboros Instruments:
-----------------------------------
  1 version(s):     52 groups
  2 version(s):     14 groups
  3 version(s):     1 groups
  6 version(s):     1 groups

  Average versions per parent: 1.31

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Oroboros Instruments    68

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.26124/mitofit    45
10.26124/bec        15
10.26124/becprep     8



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
wiki.oroboros.at                    30
bioenergetics-communications.org    23
mitofit.org                         15


=================================================================
 COMPLETED: OROBOROS INSTRUMENTS
=================================================================

# PaleorXiv

In [68]:
PaleorXiv_df, PaleorXiv_summary = get_server_data("PaleorXiv")

==================================================
 SERVER ANALYSIS: PALEORXIV
==================================================
  > Files found:    1
  > Raw records:    287
  > Cleaned shape:  (287, 90)
  > Unique DOIs:    287
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31233/osf    202
10.31227/osf     23
10.31219/osf     18
10.31231/osf     17
10.31235/osf      8
10.31228/osf      5
10.31229/osf      5
10.31234/osf      3
10.31223/osf      3
10.31230/osf      2
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    287
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31233    202
10.31227     23
10.31219     18
10.31231     17
10.31235      8
10.31228      5
10.31229      5
10.31234      3
10.31223      3
10.31230      2
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    284
29705      3
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             284
California Digital Library (CDL)      3
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    287
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    287
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
PaleorXiv    287
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    287
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    287
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    287
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PALEORXIV
==================================================

In [69]:
PaleorXiv_parent_df, PaleorXiv_parent_summary = analyze_parent_data("PaleorXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PALEORXIV
=================================================================
  > Total Parent Groups:     243
  > Total Versions Found:    362
  > Unique Parent DOIs:      243
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for PaleorXiv:
-----------------------------------
  1 version(s):     150 groups
  2 version(s):     72 groups
  3 version(s):     17 groups
  4 version(s):     3 groups
  5 version(s):     1 groups

  Average versions per parent: 1.49

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
PaleorXiv                            191
Open Science Framework; PaleorXiv     51
Preprints.org                          1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31233/osf    243



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    243


=================================================================
 COMPLETED: PALEORXIV
=================================================================

# PeerJ Preprints

In [70]:
PeerJ_df, PeerJ_summary = get_server_data("PeerJ_Preprints")

==================================================
 SERVER ANALYSIS: PEERJ_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    6446
  > Cleaned shape:  (6446, 90)
  > Unique DOIs:    6446
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.7287/peerj    6446
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
peerj.com    6446
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.7287    6446
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
4443    6446
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
PeerJ    6446
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    6446
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    6446
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
PeerJ Preprints    4240
PeerJ PrePrints    2206
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    6446
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    6446
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    6446
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PEERJ_PREPRINTS
==================================================

In [71]:
PeerJ_parent_df, PeerJ_parent_summary = analyze_parent_data("PeerJ Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PEERJ PREPRINTS
=================================================================
  > Total Parent Groups:     5,141
  > Total Versions Found:    6,440
  > Unique Parent DOIs:      5,141
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for PeerJ Preprints:
-----------------------------------
  1 version(s):     4,216 groups
  2 version(s):     686 groups
  3 version(s):     161 groups
  4 version(s):     46 groups
  5 version(s):     22 groups
  6 version(s):     5 groups
  7 version(s):     3 groups
  12 version(s):    2 groups

  Average versions per parent: 1.25

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
PeerJ Preprints           5082
arXiv                       20
F1000Research               11
Open Science Framework       3
bioRxiv                      3
Zenodo                       3
MarXiv                       2
ResearchGate                 2
HAL                          2
PeerJ Preprints; arXiv       2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.7287/peerj    5141



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
peerj.com    5141


=================================================================
 COMPLETED: PEERJ PREPRINTS
=================================================================

# PhilSci-Archive

In [72]:
PhilSci_df, PhilSci_summary = get_server_data("PhilSci-Archive")

==================================================
 SERVER ANALYSIS: PHILSCI-ARCHIVE
==================================================
  > Files found:    1
  > Raw records:    2362
  > Cleaned shape:  (2362, 90)
  > Unique DOIs:    195
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>              2167
10.48550/arxiv     146
10.13140/rg         18
10.6084/m            5
10.5281/zenodo       3
10.17863/cam         2
10.2143/lea          2
10.22381/rcp         1
10.24338/abs-        1
10.25455/wgtn        1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
None                        1676
philsci-archive.pitt.edu     505
doi.org                      181
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        2167
10.48550     146
10.13140      19
10.6084        5
10.5281        3
10.17863       2
10.2143        2
10.22381       1
10.25455       1
10.24338       1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    2362
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    2362
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    2362
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    2362
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    2362
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2362
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article     2129
preprint     233
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    2362
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PHILSCI-ARCHIVE
==================================================

In [73]:
PhilSci_parent_df, PhilSci_parent_summary = analyze_parent_data("PhilSci-Archive", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PHILSCI-ARCHIVE
=================================================================
  > Total Parent Groups:     2,129
  > Total Versions Found:    2,165
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for PhilSci-Archive:
-----------------------------------
  1 version(s):     2,097 groups
  2 version(s):     29 groups
  3 version(s):     2 groups
  4 version(s):     1 groups

  Average versions per parent: 1.02

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
PhilSci-Archive    2108
arXiv                18
bioRxiv               1
ResearchGate          1
HAL                   1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    2129



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
None                        1645
philsci-archive.pitt.edu     484


=================================================================
 COMPLETED: PHILSCI-ARCHIVE
=================================================================

# PoolText

In [74]:
PoolText_df, PoolText_summary = get_server_data("PoolText")

==================================================
 SERVER ANALYSIS: POOLTEXT
==================================================
  > Files found:    1
  > Raw records:    79
  > Cleaned shape:  (79, 90)
  > Unique DOIs:    79
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31923/pooltext-preprint-    78
10.31923/55                     1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
content.pooltext.com    79
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31923    79
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
16838    79
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
PoolText, Inc    79
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    79
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    79
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Anesthesiology and Pain Medicine     9
Medicine (other/miscellaneous)       9
Cardiology                           6
Orthopaedics &amp; Traumatology      4
Gastroenterology &amp; Hepatology    4
Emergency Medicine                   4
Oncology                             4
Family Practice                      3
Psychiatry and Mental Health         3
Obstetrics and Gynecology            3
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    79
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    79
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    79
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR POOLTEXT
==================================================

In [75]:
PoolText_parent_df, PoolText_parent_summary = analyze_parent_data("PoolText", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: POOLTEXT
=================================================================
  > Total Parent Groups:     79
  > Total Versions Found:    79
  > Unique Parent DOIs:      79
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for PoolText:
-----------------------------------
  1 version(s):     79 groups

  Average versions per parent: 1.00

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
PoolText    79

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31923/pooltext-preprint-    78
10.31923/55                     1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
content.pooltext.com    79


=================================================================
 COMPLETED: POOLTEXT
=================================================================

# prepare@u

In [76]:
prepare_df, prepare_summary = get_server_data("prepare@u")

==================================================
 SERVER ANALYSIS: PREPARE@U
==================================================
  > Files found:    1
  > Raw records:    227
  > Cleaned shape:  (227, 90)
  > Unique DOIs:    227
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.36375/prepare    227
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprint.prepare.org.in    223
prepare.enggtalks.com        2
prepare.org.in               2
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.36375    227
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
22141    227
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
CALNESTOR Knowledge Solutions Private Limited    227
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None                            226
PREPARE@U - Preprint Archive      1
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    227
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
prepare@u    225
None           2
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    227
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content     225
journal-article      1
journal              1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    225
None          2
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PREPARE@U
==================================================

In [77]:
prepare_parent_df, prepare_parent_summary = analyze_parent_data("prepare@u", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PREPARE@U
=================================================================
  > Total Parent Groups:     224
  > Total Versions Found:    227
  > Unique Parent DOIs:      224
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for prepare@u:
-----------------------------------
  1 version(s):     221 groups
  2 version(s):     3 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
prepare@u          223
Research Square      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.36375/prepare    224



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprint.prepare.org.in    220
prepare.org.in               2
prepare.enggtalks.com        2


=================================================================
 COMPLETED: PREPARE@U
=================================================================

# Preprints.org

In [78]:
Preprints_df, Preprints_summary = get_server_data("Preprints.org")

==================================================
 SERVER ANALYSIS: PREPRINTS.ORG
==================================================
  > Files found:    1
  > Raw records:    115815
  > Cleaned shape:  (115815, 90)
  > Unique DOIs:    115815
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.20944/preprints    115815
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.org    115815
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.20944    115815
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
1968    115815
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
MDPI AG    115815
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    115815
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    115815
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Biology and Life Sciences           15972
Medicine and Pharmacology           14771
Engineering                         11446
Computer Science and Mathematics    10739
Environmental and Earth Sciences     6110
Physical Sciences                    5490
Public Health and Healthcare         5434
Chemistry and Materials Science      5334
MEDICINE &amp; PHARMACOLOGY          5180
ENGINEERING                          4914
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    115815
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    115815
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    115815
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PREPRINTS.ORG
==================================================

In [79]:
Preprints_parent_df, Preprints_parent_summary = analyze_parent_data("Preprints.org", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PREPRINTS.ORG
=================================================================
  > Total Parent Groups:     103,649
  > Total Versions Found:    115,070
  > Unique Parent DOIs:      103,649
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Preprints.org:
-----------------------------------
  1 version(s):     95,681 groups
  2 version(s):     6,404 groups
  3 version(s):     1,011 groups
  4 version(s):     276 groups
  5 version(s):     105 groups
  6 version(s):     53 groups
  7 version(s):     28 groups
  8 version(s):     16 groups
  9 version(s):     14 groups
  10 version(s):    8 groups
  11 version(s):    12 groups
  12 version(s):    9 groups
  13 version(s):    4 groups
  14 version(s):    3 groups
  15 version(s):    2 groups
  16 version(s):    1 groups
  17 version(s):    3 groups
  18 version(s):    2 groups
  20 version(s):    1 groups
  21 version(s):    2 groups
  22 version(s):    1 groups
  23 version(s):    5 groups
  26 version(s):    3 groups
  36 version(s):    1 groups
  39 version(s):    1 groups
  55 version(s):    1 groups
  98 version(s):    1 groups
  99 version(s):    1 groups

  Average versions per parent: 1.11

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Preprints.org                  102104
arXiv                             454
Research Square                   284
SSRN                              237
Preprints.org; ResearchGate        60
Preprints.org; arXiv               54
ResearchGate                       52
TechRxiv                           47
Authorea Inc.                      44
Open Science Framework             34

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.20944/preprints    103649



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.org    103649


=================================================================
 COMPLETED: PREPRINTS.ORG
=================================================================

# PREPRINTS.RU

In [80]:
PREPRINTS_df, PREPRINTS_summary = get_server_data("PREPRINTS.RU")

==================================================
 SERVER ANALYSIS: PREPRINTS.RU
==================================================
  > Files found:    1
  > Raw records:    1415
  > Cleaned shape:  (1415, 90)
  > Unique DOIs:    1415
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.24108/preprints-    1415
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.ru    1415
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.24108    1415
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
10196    1415
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
NPG Publishing    1415
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    1415
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1415
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Физика, химия                            281
Математика, информатика, кибернетика     276
Промышленность, технологии               146
Гуманитарные науки                       142
Экономика и управление                   119
Медицина, фармакология                   105
Биология, ботаника, генетика              85
Образование, науковедение, педагогика     55
Науки о земле                             41
Сельское хозяйство                        39
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    1415
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    1415
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    1415
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PREPRINTS.RU
==================================================

In [81]:
PREPRINTS_parent_df, PREPRINTS_parent_summary = analyze_parent_data("PREPRINTS.RU", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PREPRINTS.RU
=================================================================
  > Total Parent Groups:     1,346
  > Total Versions Found:    1,415
  > Unique Parent DOIs:      1,346
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for PREPRINTS.RU:
-----------------------------------
  1 version(s):     1,295 groups
  2 version(s):     42 groups
  3 version(s):     4 groups
  4 version(s):     2 groups
  5 version(s):     2 groups
  6 version(s):     1 groups

  Average versions per parent: 1.05

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
PREPRINTS.RU                  1334
PREPRINTS.RU; Zenodo             3
SSRN                             2
PREPRINTS.RU; ResearchGate       1
engrXiv                          1
AfricArXiv; PREPRINTS.RU         1
Advance                          1
Open Science Framework           1
Covid-19 Preprints               1
Cambridge Open Engage            1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.24108/preprints-    1346



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.ru    1346


=================================================================
 COMPLETED: PREPRINTS.RU
=================================================================

# Prepublicaciones OpenCiencia

In [82]:
OpenCiencia_df, OpenCiencia_summary = get_server_data("Prepublicaciones_OpenCiencia")

==================================================
 SERVER ANALYSIS: PREPUBLICACIONES_OPENCIENCIA
==================================================
  > Files found:    1
  > Raw records:    8
  > Cleaned shape:  (8, 90)
  > Unique DOIs:    8
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.47073/preprints    8
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
prepublicaciones.org    8
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.47073    8
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
28319    8
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Centro de Investigacion sobre Desarrollo Humano y Sociedad (Coideso)    8
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    8
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    8
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    8
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    8
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    8
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    8
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PREPUBLICACIONES_OPENCIENCIA
==================================================

In [83]:
OpenCiencia_parent_df, OpenCiencia_parent_summary = analyze_parent_data("Prepublicaciones OpenCiencia", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PREPUBLICACIONES OPENCIENCIA
=================================================================
  > Total Parent Groups:     7
  > Total Versions Found:    8
  > Unique Parent DOIs:      7
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Prepublicaciones OpenCiencia:
-----------------------------------
  1 version(s):     6 groups
  2 version(s):     1 groups

  Average versions per parent: 1.14

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Prepublicaciones OpenCiencia    7

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.47073/preprints    7



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
prepublicaciones.org    7


=================================================================
 COMPLETED: PREPUBLICACIONES OPENCIENCIA
=================================================================

# PropylaeumDok

In [8]:
PropylaeumDok_df, PropylaeumDok_summary = get_server_data("PropylaeumDok")

==================================================
 SERVER ANALYSIS: PROPYLAEUMDOK
==================================================
  > Files found:    2
  > Raw records:    6750
  > Cleaned shape:  (6750, 90)
  > Unique DOIs:    6750
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.11588/propylaeumdok    6750
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
archiv.ub.uni-heidelberg.de    6750
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.11588    6750
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    6750
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Heidelberg University Library    6749
None                                1
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    6750
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    6750
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    6750
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    6750
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Text          6586
Collection     134
Film            29
None             1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
BookSection    3100
Article        2634
Misc            653
Monograph       144
Periodical      134
Thesis           51
Video            29
Preprint          4
None              1
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PROPYLAEUMDOK
==================================================

In [9]:
PropylaeumDok_parent_df, PropylaeumDok_parent_summary = analyze_parent_data("PropylaeumDok", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PROPYLAEUMDOK
=================================================================
  > Total Parent Groups:     6,664
  > Total Versions Found:    6,748
  > Unique Parent DOIs:      6,664
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for PropylaeumDok:
-----------------------------------
  1 version(s):     6,608 groups
  2 version(s):     46 groups
  3 version(s):     5 groups
  4 version(s):     2 groups
  5 version(s):     1 groups
  6 version(s):     1 groups
  14 version(s):    1 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
PropylaeumDok    6664

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.11588/propylaeumdok    6664



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
archiv.ub.uni-heidelberg.de    6664


=================================================================
 COMPLETED: PROPYLAEUMDOK
=================================================================

In [10]:
PropylaeumDok_df[PropylaeumDok_df['type_backend_raw']=='Film']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
757,datacite::10.11588/propylaeumdok.00000379,PropylaeumDok,datacite,10.11588/propylaeumdok.00000379,10.11588/propylaeumdok.00000379,https://doi.org/10.11588/propylaeumdok.00000379,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Bau und Te...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000379,10.11588,10.11588,propylaeumdok.00000379,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
758,datacite::10.11588/propylaeumdok.00000380,PropylaeumDok,datacite,10.11588/propylaeumdok.00000380,10.11588/propylaeumdok.00000380,https://doi.org/10.11588/propylaeumdok.00000380,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Becher aus...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000380,10.11588,10.11588,propylaeumdok.00000380,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
763,datacite::10.11588/propylaeumdok.00000381,PropylaeumDok,datacite,10.11588/propylaeumdok.00000381,10.11588/propylaeumdok.00000381,https://doi.org/10.11588/propylaeumdok.00000381,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Heidelberg...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000381,10.11588,10.11588,propylaeumdok.00000381,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
764,datacite::10.11588/propylaeumdok.00000382,PropylaeumDok,datacite,10.11588/propylaeumdok.00000382,10.11588/propylaeumdok.00000382,https://doi.org/10.11588/propylaeumdok.00000382,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Gefäßdrehe...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000382,10.11588,10.11588,propylaeumdok.00000382,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
765,datacite::10.11588/propylaeumdok.00000383,PropylaeumDok,datacite,10.11588/propylaeumdok.00000383,10.11588/propylaeumdok.00000383,https://doi.org/10.11588/propylaeumdok.00000383,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Unterschie...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000383,10.11588,10.11588,propylaeumdok.00000383,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
766,datacite::10.11588/propylaeumdok.00000384,PropylaeumDok,datacite,10.11588/propylaeumdok.00000384,10.11588/propylaeumdok.00000384,https://doi.org/10.11588/propylaeumdok.00000384,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Fayence im...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000384,10.11588,10.11588,propylaeumdok.00000384,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
767,datacite::10.11588/propylaeumdok.00000385,PropylaeumDok,datacite,10.11588/propylaeumdok.00000385,10.11588/propylaeumdok.00000385,https://doi.org/10.11588/propylaeumdok.00000385,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,"Experimente zur Keramikherstellung: Wülsten, B...",None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000385,10.11588,10.11588,propylaeumdok.00000385,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
768,datacite::10.11588/propylaeumdok.00000386,PropylaeumDok,datacite,10.11588/propylaeumdok.00000386,10.11588/propylaeumdok.00000386,https://doi.org/10.11588/propylaeumdok.00000386,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Brand bema...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000386,10.11588,10.11588,propylaeumdok.00000386,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
769,datacite::10.11588/propylaeumdok.00000387,PropylaeumDok,datacite,10.11588/propylaeumdok.00000387,10.11588/propylaeumdok.00000387,https://doi.org/10.11588/propylaeumdok.00000387,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Brand im K...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000387,10.11588,10.11588,propylaeumdok.00000387,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
770,datacite::10.11588/propylaeumdok.00000393,PropylaeumDok,datacite,10.11588/propylaeumdok.00000393,10.11588/propylaeumdok.00000393,https://doi.org/10.11588/propylaeumdok.00000393,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Testbrand ...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000393,10.11588,10.11588,propylaeumdok.00000393,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
809,datacite::10.11588/propylaeumdok.00000444,PropylaeumDok,datacite,10.11588/propylaeumdok.00000444,10.11588/propylaeumdok.00000444,https://doi.org/10.11588/propylaeumdok.00000444,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Verschiede...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000444,10.11588,10.11588,propylaeumdok.00000444,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
810,datacite::10.11588/propylaeumdok.00000441,PropylaeumDok,datacite,10.11588/propylaeumdok.00000441,10.11588/propylaeumdok.00000441,https://doi.org/10.11588/propylaeumdok.00000441,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Pithosbau ...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000441,10.11588,10.11588,propylaeumdok.00000441,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
811,datacite::10.11588/propylaeumdok.00000443,PropylaeumDok,datacite,10.11588/propylaeumdok.00000443,10.11588/propylaeumdok.00000443,https://doi.org/10.11588/propylaeumdok.00000443,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Herstellun...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000443,10.11588,10.11588,propylaeumdok.00000443,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
812,datacite::10.11588/propylaeumdok.00000442,PropylaeumDok,datacite,10.11588/propylaeumdok.00000442,10.11588/propylaeumdok.00000442,https://doi.org/10.11588/propylaeumdok.00000442,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Pithosbau ...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000442,10.11588,10.11588,propylaeumdok.00000442,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
813,datacite::10.11588/propylaeumdok.00000445,PropylaeumDok,datacite,10.11588/propylaeumdok.00000445,10.11588/propylaeumdok.00000445,https://doi.org/10.11588/propylaeumdok.00000445,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,Experimente zur Keramikherstellung: Impression...,None,None,None,None,Film,Video,Film,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2009.0,published_year,None,None,None,None,None,[],None,None,None,"Hampe, Roland; Winter, Adam",None,None,"[{""affiliation"": [], ""familyName"": ""Hampe"", ""g...",[],None,[],None,None,"[{""subject"": ""Plastic arts Sculpture""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000445,10.11588,10.11588,propylaeumdok.00000445,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok

In [11]:
PropylaeumDok_df[PropylaeumDok_df['type_backend_raw']=='Collection']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
523,datacite::10.11588/propylaeumdok.00000139,PropylaeumDok,datacite,10.11588/propylaeumdok.00000139,10.11588/propylaeumdok.00000139,https://doi.org/10.11588/propylaeumdok.00000139,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,OCCIDENT & ORIENT: Newsletter of the German Pr...,None,None,None,None,Collection,Periodical,Collection,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2008.0,published_year,None,None,None,None,None,[],None,None,None,Deutsches Evangelisches Institut Für Altertums...,None,None,"[{""affiliation"": [], ""name"": ""Deutsches Evange...",[],None,[],None,None,"[{""subject"": ""Palästina, Israel (Altertum)""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000139,10.11588,10.11588,propylaeumdok.00000139,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
524,datacite::10.11588/propylaeumdok.00000140,PropylaeumDok,datacite,10.11588/propylaeumdok.00000140,10.11588/propylaeumdok.00000140,https://doi.org/10.11588/propylaeumdok.00000140,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,OCCIDENT & ORIENT: Newsletter of the German Pr...,None,None,None,None,Collection,Periodical,Collection,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2008.0,published_year,None,None,None,None,None,[],None,None,None,Deutsches Evangelisches Institut Für Altertums...,None,None,"[{""affiliation"": [], ""name"": ""Deutsches Evange...",[],None,[],None,None,"[{""subject"": ""Palästina, Israel (Altertum)""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000140,10.11588,10.11588,propylaeumdok.00000140,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
532,datacite::10.11588/propylaeumdok.00000147,PropylaeumDok,datacite,10.11588/propylaeumdok.00000147,10.11588/propylaeumdok.00000147,https://doi.org/10.11588/propylaeumdok.00000147,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,OCCIDENT & ORIENT: Newsletter of the German Pr...,None,None,None,None,Collection,Periodical,Collection,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2008.0,published_year,None,None,None,None,None,[],None,None,None,Deutsches Evangelisches Institut Für Altertums...,None,None,"[{""affiliation"": [], ""name"": ""Deutsches Evange...",[],None,[],None,None,"[{""subject"": ""Palästina, Israel (Altertum)""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000147,10.11588,10.11588,propylaeumdok.00000147,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
534,datacite::10.11588/propylaeumdok.00000148,PropylaeumDok,datacite,10.11588/propylaeumdok.00000148,10.11588/propylaeumdok.00000148,https://doi.org/10.11588/propylaeumdok.00000148,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,OCCIDENT & ORIENT: Newsletter of the German Pr...,None,None,None,None,Collection,Periodical,Collection,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2008.0,published_year,None,None,None,None,None,[],None,None,None,Deutsches Evangelisches Institut Für Altertums...,None,None,"[{""affiliation"": [], ""name"": ""Deutsches Evange...",[],None,[],None,None,"[{""subject"": ""Palästina, Israel (Altertum)""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000148,10.11588,10.11588,propylaeumdok.00000148,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
535,datacite::10.11588/propylaeumdok.00000149,PropylaeumDok,datacite,10.11588/propylaeumdok.00000149,10.11588/propylaeumdok.00000149,https://doi.org/10.11588/propylaeumdok.00000149,http://archiv.ub.uni-heidelberg.de/propylaeumd...,http://archiv.ub.uni-heidelberg.de/propylaeumd...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,OCCIDENT & ORIENT: Newsletter of the German Pr...,None,None,None,None,Collection,Periodical,Collection,None,None,2017-02-23,None,None,None,2020-12-10,None,2017-02-23,None,None,2008.0,published_year,None,None,None,None,None,[],None,None,None,Deutsches Evangelisches Institut Für Altertums...,None,None,"[{""affiliation"": [], ""name"": ""Deutsches Evange...",[],None,[],None,None,"[{""subject"": ""Palästina, Israel (Altertum)""}]",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00000149,10.11588,10.11588,propylaeumdok.00000149,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5534,datacite::10.11588/propylaeumdok.00005670,PropylaeumDok,datacite,10.11588/propylaeumdok.00005670,10.11588/propylaeumdok.00005670,https://doi.org/10.11588/propylaeumdok.00005670,https://archiv.ub.uni-heidelberg.de/propylaeum...,https://archiv.ub.uni-heidelberg.de/propylaeum...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,DGUF-Newsletter vom 14.02.2022,None,None,None,None,Collection,Periodical,Collection,None,None,2023-02-09,None,None,None,2023-02-09,None,2023-02-09,None,None,2023.0,published_year,None,None,None,None,None,[],None,None,None,Deutsche Gesellschaft Für Ur- Und Frühgeschich...,None,None,"[{""affiliation"": [], ""name"": ""Deutsche Gesells...",[],None,[],None,None,"[{""subject"": ""Alte Geschichte, Vor- und Frühge...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00005670,10.11588,10.11588,propylaeumdok.00005670,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
5557,datacite::10.11588/propylaeumdok.00005697,PropylaeumDok,datacite,10.11588/propylaeumdok.00005697,10.11588/propylaeumdok.00005697,https://doi.org/10.11588/propylaeumdok.00005697,https://archiv.ub.uni-heidelberg.de/propylaeum...,https://archiv.ub.uni-heidelberg.de/propylaeum...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,LUX. das magazin des lvr-landesmuseums bonn,None,None,None,None,Collection,Periodical,Collection,None,None,2023-04-27,None,None,None,2023-04-27,None,2023-04-27,None,None,2023.0,published_year,None,None,None,None,None,[],None,None,None,LVR-LandesMuseum Bonn,None,None,"[{""affiliation"": [], ""name"": ""LVR-LandesMuseum...",[],None,[],None,None,"[{""subject"": ""Alte Geschichte, Vor- und Frühge...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00005697,10.11588,10.11588,propylaeumdok.00005697,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
5697,datacite::10.11588/propylaeumdok.00005881,PropylaeumDok,datacite,10.11588/propylaeumdok.00005881,10.11588/propylaeumdok.00005881,https://doi.org/10.11588/propylaeumdok.00005881,https://archiv.ub.uni-heidelberg.de/propylaeum...,https://archiv.ub.uni-heidelberg.de/propylaeum...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,LUX. das magazin des lvr-landesmuseums bonn 2/...,None,None,None,None,Collection,Periodical,Collection,None,None,2023-10-17,None,None,None,2023-10-17,None,2023-10-17,None,None,2023.0,published_year,None,None,None,None,None,[],None,None,None,LVR-LandesMuseum Bonn,None,None,"[{""affiliation"": [], ""name"": ""LVR-LandesMuseum...",[],None,[],None,None,"[{""subject"": ""Alte Geschichte, Vor- und Frühge...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00005881,10.11588,10.11588,propylaeumdok.00005881,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
6071,datacite::10.11588/propylaeumdok.00006274,PropylaeumDok,datacite,10.11588/propylaeumdok.00006274,10.11588/propylaeumdok.00006274,https://doi.org/10.11588/propylaeumdok.00006274,https://archiv.ub.uni-heidelberg.de/propylaeum...,https://archiv.ub.uni-heidelberg.de/propylaeum...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,LUX. das magazin des lvr-landesmuseums bonn 1/...,None,None,None,None,Collection,Periodical,Collection,None,None,2024-06-10,None,None,None,2024-06-10,None,2024-06-10,None,None,2024.0,published_year,None,None,None,None,None,[],None,None,None,LVR-LandesMuseum Bonn,None,None,"[{""affiliation"": [], ""name"": ""LVR-LandesMuseum...",[],None,[],None,None,"[{""subject"": ""Alte Geschichte, Vor- und Frühge...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00006274,10.11588,10.11588,propylaeumdok.00006274,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok
6349,datacite::10.11588/propylaeumdok.00006551,PropylaeumDok,datacite,10.11588/propylaeumdok.00006551,10.11588/propylaeumdok.00006551,https://doi.org/10.11588/propylaeumdok.00006551,https://archiv.ub.uni-heidelberg.de/propylaeum...,https://archiv.ub.uni-heidelberg.de/propylaeum...,10.11588,None,gesis.ubhd,gesis,datacite,Heidelberg University Library,None,None,None,None,LUX. das magazin des lvr-landesmuseums bonn 2/...,None,None,None,None,Collection,Periodical,Collection,None,None,2024-11-19,None,None,None,2024-11-19,None,2024-11-19,None,None,2024.0,published_year,None,None,None,None,None,[],None,None,None,LVR-LandesMuseum Bonn,None,None,"[{""affiliation"": [], ""name"": ""LVR-LandesMuseum...",[],None,[],None,None,"[{""subject"": ""Alte Geschichte, Vor- und Frühge...",None,None,0,0,None,None,0,None,[],,,False,None,,None,None,,None,None,None,client_id/doi_prefix_first_token,8,"{""client"": {""data"": {""id"": ""gesis.ubhd"", ""type...","{""citationCount"": 0, ""container"": {}, ""content...",10.11588/propylaeumdok.00006551,10.11588,10.11588,propylaeumdok.00006551,10.11588/propylaeumdok,10.11588/propylaeumdok,archiv.ub.uni-heidelberg.de,archiv.ub.uni-heidelberg.de/propylaeumdok

# PsyArXiv

In [12]:
PsyArXiv_df, PsyArXiv_summary = get_server_data("PsyArXiv")

==================================================
 SERVER ANALYSIS: PSYARXIV
==================================================
  > Files found:    1
  > Raw records:    56866
  > Cleaned shape:  (56866, 90)
  > Unique DOIs:    56866
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31234/osf    54938
10.31219/osf      568
10.31227/osf      531
10.31235/osf      339
10.31228/osf      181
10.31223/osf       52
10.31225/osf       47
10.31230/osf       46
10.31229/osf       46
10.31224/osf       42
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    56866
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31234    54938
10.31219      568
10.31227      531
10.31235      339
10.31228      181
10.31223       52
10.31225       47
10.31230       46
10.31229       46
10.31224       42
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    56765
29705       52
242         34
33966       15
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             56765
California Digital Library (CDL)       52
CABI Publishing                        34
Open Engineering Inc                   15
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    56866
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    56866
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
PsyArXiv    56866
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    56866
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    56866
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    56866
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR PSYARXIV
==================================================

In [13]:
PsyArXiv_parent_df, PsyArXiv_parent_summary = analyze_parent_data("PsyArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: PSYARXIV
=================================================================
  > Total Parent Groups:     48,701
  > Total Versions Found:    59,523
  > Unique Parent DOIs:      48,701
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for PsyArXiv:
-----------------------------------
  1 version(s):     40,523 groups
  2 version(s):     6,500 groups
  3 version(s):     1,243 groups
  4 version(s):     255 groups
  5 version(s):     99 groups
  6 version(s):     36 groups
  7 version(s):     16 groups
  8 version(s):     7 groups
  9 version(s):     3 groups
  10 version(s):    4 groups
  12 version(s):    4 groups
  14 version(s):    1 groups
  15 version(s):    1 groups
  16 version(s):    1 groups
  17 version(s):    1 groups
  18 version(s):    2 groups
  21 version(s):    1 groups
  24 version(s):    1 groups
  25 version(s):    1 groups
  37 version(s):    1 groups
  52 version(s):    1 groups

  Average versions per parent: 1.22

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
PsyArXiv                            46790
Open Science Framework; PsyArXiv      433
Open Science Framework                417
SSRN                                  275
Research Square                       200
PsyArXiv; ResearchGate                 99
arXiv                                  70
PsyArXiv; arXiv                        59
eLife                                  50
ResearchGate                           50

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31234/osf    48584
10.17605/osf      116
10.31219/osf        1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io          48585
psyarxiv.com      116


=================================================================
 COMPLETED: PSYARXIV
=================================================================

# Qeios

In [14]:
Qeios_df, Qeios_summary = get_server_data("Qeios")

==================================================
 SERVER ANALYSIS: QEIOS
==================================================
  > Files found:    1
  > Raw records:    5650
  > Cleaned shape:  (5650, 90)
  > Unique DOIs:    5650
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.32388/i    66
10.32388/g    54
10.32388/h    51
10.32388/a    49
10.32388/p    48
10.32388/j    48
10.32388/r    48
10.32388/n    48
10.32388/z    47
10.32388/o    46
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
qeios.com    5650
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.32388    5650
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
17262    5650
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Qeios Ltd    5650
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    5650
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
Qeios                  4462
None                   1186
Independent Scholar       2
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    5650
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    5650
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    5650
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    5650
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR QEIOS
==================================================

In [15]:
Qeios_parent_df, Qeios_parent_summary = analyze_parent_data("Qeios", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: QEIOS
=================================================================
  > Total Parent Groups:     3,256
  > Total Versions Found:    5,135
  > Unique Parent DOIs:      3,256
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Qeios:
-----------------------------------
  1 version(s):     2,084 groups
  2 version(s):     829 groups
  3 version(s):     210 groups
  4 version(s):     54 groups
  5 version(s):     37 groups
  6 version(s):     12 groups
  7 version(s):     10 groups
  8 version(s):     4 groups
  9 version(s):     4 groups
  11 version(s):    3 groups
  12 version(s):    3 groups
  13 version(s):    3 groups
  14 version(s):    1 groups
  15 version(s):    2 groups

  Average versions per parent: 1.58

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Qeios                     3190
SSRN                        19
arXiv                        9
ResearchGate                 7
Research Square              6
Qeios; ResearchGate          5
Open Science Framework       4
Preprints.org                3
AfricArXiv                   2
PsyArXiv                     2

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.32388/a    32
10.32388/r    30
10.32388/n    29
10.32388/g    27
10.32388/p    27
10.32388/k    26
10.32388/w    25
10.32388/i    25
10.32388/o    25
10.32388/z    25



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
qeios.com    3256


=================================================================
 COMPLETED: QEIOS
=================================================================

# RePEc: Research Papers in Economics

In [16]:
# RePEc_df, RePEc_summary = get_server_data("RePEc_Research_Papers_in_Economics")

In [17]:
RePEc_parent_df, RePEc_parent_summary = analyze_parent_data("RePEc: Research Papers in Economics", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: REPEC: RESEARCH PAPERS IN ECONOMICS
=================================================================
  > Total Parent Groups:     369,997
  > Total Versions Found:    430,371
  > Unique Parent DOIs:      20,673
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for RePEc: Research Papers in Economics:
-----------------------------------
  1 version(s):     315,721 groups
  2 version(s):     49,392 groups
  3 version(s):     4,096 groups
  4 version(s):     611 groups
  5 version(s):     116 groups
  6 version(s):     25 groups
  7 version(s):     12 groups
  8 version(s):     6 groups
  9 version(s):     4 groups
  10 version(s):    4 groups
  11 version(s):    4 groups
  14 version(s):    1 groups
  18 version(s):    1 groups
  22 version(s):    1 groups
  27 version(s):    1 groups
  28 version(s):    1 groups
  43 version(s):    1 groups

  Average versions per parent: 1.16

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
RePEc: Research Papers in Economics                        320176
SSRN                                                        31489
AgEcon Search                                               15513
arXiv                                                         695
HAL                                                           590
ResearchGate                                                  393
HAL; RePEc: Research Papers in Economics                      279
EconStor Preprints; RePEc: Research Papers in Economics       243
EconStor Preprints                                            242
Munich Personal RePEc Archive                                  58

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>              349326
10.22004/ag         6336
10.13140/rg         1619
10.5089/97           589
10.5281/zenodo       487
10.34989/swp-        430
10.7208/97           295
10.17863/cam         270
10.1142/97           199
10.5282/ubm          194



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
econpapers.repec.org       213170
ideas.repec.org             41706
None                        36192
ageconsearch.umn.edu         5112
econstor.eu                  3775
doi.org                      2470
sciencedirect.com            2431
repositorio.cepal.org        1932
basepub.dauphine.fr          1251
mpra.ub.uni-muenchen.de      1169


=================================================================
 COMPLETED: REPEC: RESEARCH PAPERS IN ECONOMICS
=================================================================

# Research Square

In [18]:
# Research_Square_df, Research_Square_summary = get_server_data("Research_Square")

In [19]:
Research_Square_parent_df, Research_Square_parent_summary = analyze_parent_data("Research Square", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: RESEARCH SQUARE
=================================================================
  > Total Parent Groups:     389,983
  > Total Versions Found:    439,160
  > Unique Parent DOIs:      389,983
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Research Square:
-----------------------------------
  1 version(s):     355,085 groups
  2 version(s):     25,294 groups
  3 version(s):     6,449 groups
  4 version(s):     2,253 groups
  5 version(s):     610 groups
  6 version(s):     174 groups
  7 version(s):     66 groups
  8 version(s):     24 groups
  9 version(s):     11 groups
  10 version(s):    5 groups
  11 version(s):    2 groups
  12 version(s):    2 groups
  13 version(s):    1 groups
  14 version(s):    1 groups
  17 version(s):    1 groups
  21 version(s):    1 groups
  24 version(s):    2 groups
  25 version(s):    1 groups
  47 version(s):    1 groups

  Average versions per parent: 1.13

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Research Square           385800
SSRN                        1472
arXiv                        863
Authorea Inc.                600
bioRxiv                      234
JMIR Preprints               154
Preprints.org                153
medRxiv                      102
Research Square; arXiv        62
F1000Research                 58

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.21203/rs    389983



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
researchsquare.com                     389390
protocols.io                              583
protocolexchange.researchsquare.com        10


=================================================================
 COMPLETED: RESEARCH SQUARE
=================================================================

# ResearchGate

In [20]:
ResearchGate_df, ResearchGate_summary = get_server_data("ResearchGate")

==================================================
 SERVER ANALYSIS: RESEARCHGATE
==================================================
  > Files found:    1
  > Raw records:    181231
  > Cleaned shape:  (181231, 90)
  > Unique DOIs:    181231
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.13140/rg    181188
10.13140/2         43
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
researchgate.net    178343
rgdoi.net             2888
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.13140    181231
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    181231
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Unpublished                                                180824
Plekhanov Russian University of Economics                      21
Flora Montiberica.org                                          11
RAYHANS                                                         9
Academy of Military Science and Technology                      9
Ediciones Berea                                                 7
Universidad Técnica Federico Santa María                        7
Elsevier                                                        6
Mohamed bin Zayed University of Artificial Intelligence         6
Laboratorium Pendidikan Fisika UIN Sunan Gunung Djati           5
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    181231
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    181231
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    181231
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    181231
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Text    181231
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
Preprint    181231
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR RESEARCHGATE
==================================================

In [21]:
ResearchGate_parent_df, ResearchGate_parent_summary = analyze_parent_data("ResearchGate", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: RESEARCHGATE
=================================================================
  > Total Parent Groups:     167,312
  > Total Versions Found:    180,737
  > Unique Parent DOIs:      167,312
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ResearchGate:
-----------------------------------
  1 version(s):     157,458 groups
  2 version(s):     8,116 groups
  3 version(s):     1,231 groups
  4 version(s):     241 groups
  5 version(s):     97 groups
  6 version(s):     43 groups
  7 version(s):     44 groups
  8 version(s):     16 groups
  9 version(s):     13 groups
  10 version(s):    9 groups
  11 version(s):    7 groups
  12 version(s):    4 groups
  13 version(s):    5 groups
  14 version(s):    1 groups
  15 version(s):    2 groups
  17 version(s):    4 groups
  18 version(s):    2 groups
  19 version(s):    1 groups
  20 version(s):    1 groups
  21 version(s):    3 groups
  22 version(s):    1 groups
  23 version(s):    1 groups
  25 version(s):    1 groups
  27 version(s):    1 groups
  31 version(s):    1 groups
  32 version(s):    2 groups
  34 version(s):    1 groups
  38 version(s):    1 groups
  40 version(s):    1 groups
  47 version(s):    1 groups
  51 version(s):    1 groups
  55 version(s):    1 groups
  107 version(s):   1 groups

  Average versions per parent: 1.08

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ResearchGate              159643
SSRN                        2335
ResearchGate; arXiv         1611
arXiv                       1430
ResearchGate; Zenodo         320
Preprints.org                289
Open Science Framework       249
Research Square              196
Zenodo                       174
medRxiv                      154

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.13140/rg    167271
10.13140/2         41



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
researchgate.net    166134
rgdoi.net             1178


=================================================================
 COMPLETED: RESEARCHGATE
=================================================================

# ResearchHub

In [22]:
ResearchHub_df, ResearchHub_summary = get_server_data("ResearchHub")

==================================================
 SERVER ANALYSIS: RESEARCHHUB
==================================================
  > Files found:    1
  > Raw records:    1636
  > Cleaned shape:  (1636, 90)
  > Unique DOIs:    1636
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.55277/researchhub    1554
10.55277/rhj              81
10.55277/pvtglk            1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
researchhub.com                1513
staging.researchhub.com         100
staging-web.researchhub.com      23
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.55277    1636
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
33940    1636
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
ResearchHub Technologies, Inc.    1636
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    1636
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1636
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    1636
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    1636
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
report    1636
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    1636
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR RESEARCHHUB
==================================================

In [23]:
ResearchHub_parent_df, ResearchHub_parent_summary = analyze_parent_data("ResearchHub", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: RESEARCHHUB
=================================================================
  > Total Parent Groups:     1,375
  > Total Versions Found:    1,619
  > Unique Parent DOIs:      1,375
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ResearchHub:
-----------------------------------
  1 version(s):     1,260 groups
  2 version(s):     71 groups
  3 version(s):     17 groups
  4 version(s):     8 groups
  5 version(s):     4 groups
  6 version(s):     7 groups
  7 version(s):     3 groups
  8 version(s):     3 groups
  10 version(s):    1 groups
  17 version(s):    1 groups

  Average versions per parent: 1.18

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ResearchHub                  1356
ResearchHub; Zenodo             9
Zenodo                          4
Authorea Inc.                   2
ResearchGate; ResearchHub       2
SocArXiv                        1
EarthArXiv                      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.55277/researchhub    1374
10.55277/pvtglk            1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
researchhub.com                1306
staging.researchhub.com          47
staging-web.researchhub.com      22


=================================================================
 COMPLETED: RESEARCHHUB
=================================================================

# SAE Mobilus®

In [24]:
SAE_df, SAE_summary = get_server_data("SAE_Mobilus®")

==================================================
 SERVER ANALYSIS: SAE_MOBILUS®
==================================================
  > Files found:    1
  > Raw records:    105
  > Cleaned shape:  (105, 90)
  > Unique DOIs:    105
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.47953/sae-pp-    105
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
saemobilus.sae.org    105
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.47953    105
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2796    105
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
SAE International    105
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    105
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    105
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Ground Vehicle    95
Aerospace         10
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    105
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    105
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    105
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SAE_MOBILUS®
==================================================

In [25]:
SAE_parent_df, SAE_parent_summary = analyze_parent_data("SAE Mobilus®", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SAE MOBILUS®
=================================================================
  > Total Parent Groups:     104
  > Total Versions Found:    108
  > Unique Parent DOIs:      104
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for SAE Mobilus®:
-----------------------------------
  1 version(s):     100 groups
  2 version(s):     4 groups

  Average versions per parent: 1.04

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
SAE Mobilus®    101
arXiv             2
SSRN              1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.47953/sae-pp-    104



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
saemobilus.sae.org    104


=================================================================
 COMPLETED: SAE MOBILUS®
=================================================================

# SciELO Preprints

In [26]:
SciELO_df, SciELO_summary = get_server_data("SciELO_Preprints")

==================================================
 SERVER ANALYSIS: SCIELO_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    4141
  > Cleaned shape:  (4141, 90)
  > Unique DOIs:    4141
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.1590/scielopreprints        3939
10.1590/16                       87
10.1590/s                        39
10.1590/22                       29
10.1590/25                       22
10.1590/01                        9
10.1590/23                        3
10.1590/19                        3
10.1590/26                        3
10.1590/scielopreprintstest       2
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
preprints.scielo.org            4136
homolog-preprints.scielo.org       4
preprints-bolha.scielo.org         1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.1590    4141
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
530    4141
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
FapUNIFESP (SciELO)    4141
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    4141
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    4141
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    4141
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    4141
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    4141
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    4141
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SCIELO_PREPRINTS
==================================================

In [27]:
SciELO_parent_df, SciELO_parent_summary = analyze_parent_data("SciELO Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SCIELO PREPRINTS
=================================================================
  > Total Parent Groups:     4,084
  > Total Versions Found:    4,142
  > Unique Parent DOIs:      4,084
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for SciELO Preprints:
-----------------------------------
  1 version(s):     4,038 groups
  2 version(s):     37 groups
  3 version(s):     7 groups
  4 version(s):     1 groups
  5 version(s):     1 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
SciELO Preprints                  4066
ResearchGate; SciELO Preprints       3
Research Square                      3
Zenodo                               2
medRxiv                              2
SciELO Preprints; Zenodo             2
Qeios; SciELO Preprints              1
SSRN                                 1
PsyArXiv                             1
Preprints.org                        1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.1590/scielopreprints        3882
10.1590/16                       87
10.1590/s                        39
10.1590/22                       29
10.1590/25                       22
10.1590/01                        9
10.1590/26                        3
10.1590/19                        3
10.1590/23                        3
10.1590/scielopreprintstest       2



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
preprints.scielo.org            4081
homolog-preprints.scielo.org       2
preprints-bolha.scielo.org         1


=================================================================
 COMPLETED: SCIELO PREPRINTS
=================================================================

# ScienceOpen Preprints

In [28]:
ScienceOpen_df, ScienceOpen_summary = get_server_data("ScienceOpen_Preprints")

==================================================
 SERVER ANALYSIS: SCIENCEOPEN_PREPRINTS
==================================================
  > Files found:    1
  > Raw records:    2970
  > Cleaned shape:  (2970, 90)
  > Unique DOIs:    2970
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.14293/s     1386
10.14293/pr    1068
10.14293/p      516
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
scienceopen.com    2970
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.14293    2970
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
5403    2970
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
ScienceOpen    2970
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    2970
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
ScienceOpen    2970
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    2970
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    2970
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    2970
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    1961
other       1009
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SCIENCEOPEN_PREPRINTS
==================================================

In [29]:
ScienceOpen_df[ScienceOpen_df['subtype_backend_raw']=='other']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
1,crossref::10.14293/s2199-1006.1.sor-.ppzm4he.v1,ScienceOpen Preprints,crossref,10.14293/s2199-1006.1.sor-.ppzm4he.v1,10.14293/s2199-1006.1.sor-.ppzm4he.v1,https://doi.org/10.14293/s2199-1006.1.sor-.ppz...,https://scienceopen.com/document?vid=e8537577-...,https://scienceopen.com/document?vid=e8537577-...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,Towards exploring adaptive and associatively r...,None,None,None,None,posted-content,other,other,None,True,2020-08-04,2019-01-10,2020-09-08,2025-05-14,None,2019-01-10,None,2019-01-10,None,2019,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<ns7:p>This poster presents an initial set of ...,This poster presents an initial set of observa...,"[{""URL"": ""https://scienceopen.com/document?vid...",None,"Olteteanu, Ana-Maria; Dyer, Jonathan",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-0639-7...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/s2199-1006.1.sor-.ppzm4he.v1...",10.14293/s2199-1006.1.sor-.ppzm4he.v1,10.14293,10.14293,s2199-1006.1.sor-.ppzm4he.v1,10.14293/s,10.14293/s,scienceopen.com,scienceopen.com/document
6,crossref::10.14293/s2199-1006.1.sor-.ppsvskm.v1,ScienceOpen Preprints,crossref,10.14293/s2199-1006.1.sor-.ppsvskm.v1,10.14293/s2199-1006.1.sor-.ppsvskm.v1,https://doi.org/10.14293/s2199-1006.1.sor-.pps...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,Stealth Adapted Coronaviruses Resulting from t...,None,None,None,None,posted-content,other,other,None,True,2021-05-10,2021-05-08,2023-03-17,2023-03-17,None,2021-05-08,None,2021-05-08,None,2021,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>The continuing emergence of variant fo...,The continuing emergence of variant forms of t...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Martin, W John","Institute of Progressive Medicine, 1634 Spruce...",None,"[{""affiliation"": [{""name"": ""Institute of Progr...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/s2199-1006.1.sor-.ppsvskm.v1...",10.14293/s2199-1006.1.sor-.ppsvskm.v1,10.14293,10.14293,s2199-1006.1.sor-.ppsvskm.v1,10.14293/s,10.14293/s,scienceopen.com,scienceopen.com/hosted-document
72,crossref::10.14293/s2199-1006.1.sor-.pptzsif.v1,ScienceOpen Preprints,crossref,10.14293/s2199-1006.1.sor-.pptzsif.v1,10.14293/s2199-1006.1.sor-.pptzsif.v1,https://doi.org/10.14293/s2199-1006.1.sor-.ppt...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,MENTAL ILLNESS: AN INVISIBLE TRAUMA,None,None,None,None,posted-content,other,other,None,True,2021-06-22,2021-06-21,2023-05-25,2026-02-27,None,2021-06-21,None,2021-06-21,None,2021,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,"<jats:p>Mental disease, often known as mental ...","Mental disease, often known as mental health p...","[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Khanam, Sofia","Department of Pharmacology, Calcutta Institute...",None,"[{""ORCID"": ""https://orcid.org/0000-0002-5201-7...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,"{""has-review"": [{""asserted-by"": ""object"", ""id""...",,,False,None,,None,None,10.14293/p2199-8442.1.sop-life.pptzsif.v1.reapoa,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/s2199-1006.1.sor-.pptzsif.v1...",10.14293/s2199-1006.1.sor-.pptzsif.v1,10.14293,10.14293,s2199-1006.1.sor-.pptzsif.v1,10.14293/s,10.14293/s,scienceopen.com,scienceopen.com/hosted-document
73,crossref::10.14293/p2199-8442.1.sop-chem.pmugh...,ScienceOpen Preprints,crossref,10.14293/p2199-8442.1.sop-chem.pmugh7.v1,10.14293/p2199-8442.1.sop-chem.pmugh7.v1,https://doi.org/10.14293/p2199-8442.1.sop-chem...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,Taming Super Lewis Acids for Catalysis: The Fa...,None,None,None,None,posted-content,other,other,None,True,2014-09-29,2014-09-29,2023-05-25,2025-12-31,None,2014-09-29,None,2014-09-29,None,2014,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Tricoordinate silicon cations are exce...,Tricoordinate silicon cations are exceptionall...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Oestreich, Martin; Klare, Hendrik; Müther, Kri...",None,None,"[{""affiliation"": [], ""family"": ""Oestreich"", ""g...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/p2199-8442.1.sop-chem.pmugh7...",10.14293/p2199-8442.1.sop-chem.pmugh7.v1,10.14293,10.14293,p2199-8442.1.sop-chem.pmugh7.v1,10.14293/p,10.14293/p,scienceopen.com,scienceopen.com/hosted-document
74,crossref::10.14293/p2199-8442.1.sop-chem.pzood...,ScienceOpen Preprints,crossref,10.14293/p2199-8442.1.sop-chem.pzoodj.v1,10.14293/p2199-8442.1.sop-chem.pzoodj.v1,https://doi.org/10.14293/p2199-8442.1.sop-chem...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,Bis(Silylene) Pincer Type Ligands: A Silicon S...,None,None,None,None,posted-content,other,other,None,True,2014-09-29,2014-09-29,2023-05-25,2025-12-31,None,2014-09-29,None,2014-09-29,None,2014,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Silylenes have shown coordination stre...,Silylenes have shown coordination strength wit...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Gallego, Daniel",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-5005-9...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/p2199-8442.1.sop-chem.pzoodj...",10.14293/p2199-8442.1.sop-chem.pzoodj.v1,10.14293,10.14293,p2199-8442.1.sop-chem.pzoodj.v1,10.14293/p,10.14293/p,scienceopen.com,scienceopen.com/hosted-document
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2947,crossref::10.14293/p2199-8442.1.sop-.peorly.v1,ScienceOpen Preprints,crossref,10.14293/p2199-8442.1.sop-.peorly.v1,10.14293/p2199-8442.1.sop-.peorly.v1,https://doi.org/10.14293/p2199-8442.1.sop-.peo...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,Uncovering Metabolic Responses to Flavescence ...,None,None,None,None,posted-content,other,other,None,True,2026-01-14,2025-12-23,2026-01-14,2026-01-15,None,2025-12-23,None,2025-12-23,None,2025,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>\n Flavescence dorée ...,Flavescence dorée (FD) is a serious grapevine ...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Locatelli, Amelia; Magrin, Davide; Stefano, Si...",Istituto di Ricerche Farmacologiche Mario Negr...,None,"[{""affiliation"": [{""name"": ""Istituto di Ricerc...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/p2199-8442.1.sop-.peorly.v1""...",10.14293/p2199-8442.1.sop-.peorly.v1,10.14293,10.14293,p2199-8442.1.sop-.peorly.v1,10.14293/p,10.14293/p,scienceopen.com,scienceopen.com/hosted-document
2948,crossref::10.14293/p2199-8442.1.sop-.pt46uq.v1,ScienceOpen Preprints,crossref,10.14293/p2199-8442.1.sop-.pt46uq.v1,10.14293/p2199-8442.1.sop-.pt46uq.v1,https://doi.org/10.14293/p2199-8442.1.sop-.pt4...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,A High-Resolution Mass Spectrometry Approach t...,None,None,None,None,posted-content,other,other,None,True,2026-01-14,2025-12-23,2026-01-14,2026-01-15,None,2025-12-23,None,2025-12-23,None,2025,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>\n <jats:italic>Sorgh...,Sorghum (L. Moench ) subsp. bicolor (hereafter...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Magrin, Davide; Locatelli, Amelia; Morabito, A...","Department of Environmental Health Sciences, M...",None,"[{""affiliation"": [{""name"": ""Department of Envi...",None,None,None,None,NaN,None,None,None,0,None,None,0,0,None,None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/p2199-8442.1.sop-.pt46uq.v1""...",10.14293/p2199-8442.1.sop-.pt46uq.v1,10.14293,10.14293,p2199-8442.1.sop-.pt46uq.v1,10.14293/p,10.14293/p,scienceopen.com,scienceopen.com/hosted-document
2966,crossref::10.14293/p2199-8442.1.sop-.p33zzs.v1,ScienceOpen Preprints,crossref,10.14293/p2199-8442.1.sop-.p33zzs.v1,10.14293/p2199-8442.1.sop-.p33zzs.v1,https://doi.org/10.14293/p2199-8442.1.sop-.p33...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,The Influence of fMRI-Guided Neuromodulation o...,None,None,None,None,posted-content,other,other,None,True,2026-02-19,2025-12-23,2026-02-19,2026-02-19,None,2025-12-23,None,2025-12-23,None,2025,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Some powerful tools to treat refractor...,Some powerful tools to treat refractory neurol...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Zhang, Ben; Trusova, Antonina; Shah, Rehan; Ak...",Milpitas High School; San Diego Mesa College; ...,None,"[{""ORCID"": ""https://orcid.org/0009-0005-7223-8...",None,None,None,None,NaN,None,None,None,0,None,None,0,10,"[{""DOI"": ""10.1016/j.clinph.2009.08.016"", ""arti...",None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/p2199-8442.1.sop-.p33zzs.v1""...",10.14293/p2199-8442.1.sop-.p33zzs.v1,10.14293,10.14293,p2199-8442.1.sop-.p33zzs.v1,10.14293/p,10.14293/p,scienceopen.com,scienceopen.com/hosted-document
2967,crossref::10.14293/p2199-8442.1.sop-.pwloae.v1,ScienceOpen Preprints,crossref,10.14293/p2199-8442.1.sop-.pwloae.v1,10.14293/p2199-8442.1.sop-.pwloae.v1,https://doi.org/10.14293/p2199-8442.1.sop-.pwl...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,How do cardiovascular conditions and changes i...,None,None,None,None,posted-content,other,other,None,True,2026-02-19,2025-12-30,2026-02-19,2026-02-19,None,2025-12-30,None,2025-12-30,None,2025,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Cardiovascular dysfunction—particularl...,Cardiovascular dysfunction—particularly hypert...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Gali, Hanisha; Inigo, Jenica; Prakash, Janani;...",The Ohio State University; Green Level High Sc...,None,"[{""affiliation"": [{""name"": ""The Ohio State Uni...",None,None,None,None,NaN,None,None,None,0,None,None,0,5,"[{""DOI"": ""10.3390/biology13100764"", ""article-t...",None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/p2199-8442.1.sop-.pwloae.v1""...",10.14293/p2199-8442.1.sop-.pwloae.v1,10.14293,10.14293,p2199-8442.1.sop-.pwloae.v1,10.14293/p,10.14293/p,scienceopen.com,scienceopen.com/hosted-document
2968,crossref::10.14293/p2199-8442.1.sop-.pnu4hc.v1,ScienceOpen Preprints,crossref,10.14293/p2199-8442.1.sop-.pnu4hc.v1,10.14293/p2199-8442.1.sop-.pnu4hc.v1,https://doi.org/10.14293/p2199-8442.1.sop-.pnu...,https://scienceopen.com/hosted-document?doi=10...,https://scienceopen.com/hosted-document?doi=10...,10.14293,5403,None,None,crossref,ScienceOpen,None,ScienceOpen,None,None,Identifying Reliable Neuroimaging Biomarkers ...,None,None,A Bibliometric and Literature Review Approach,None,posted-content,other,other,None,True,2026-02-19,2025-12-23,2026-02-19,2026-02-19,None,2025-12-23,None,2025-12-23,None,2025,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,<jats:p>Major depressive disorder (MDD) is a l...,Major depressive disorder (MDD) is a leading g...,"[{""URL"": ""https://scienceopen.com/hosted-docum...",None,"Zhang, Ben; Serafin, Dilayla; Palem, Yasash; D...",Milpitas High School; Florida International Un...,None,"[{""ORCID"": ""https://orcid.org/0009-0005-7223-8...",None,None,None,None,NaN,None,None,None,0,None,None,0,3,"[{""DOI"": ""10.1176/appi.ajp.2012.11071105"", ""ar...",None,,,False,None,,None,None,,None,NaN,None,doi_prefix_first_token/prefix,1,None,"{""DOI"": ""10.14293/p2199-8442.1.sop-.pnu4hc.v1""...",10.14293/p2199-8442.1.sop-.pnu4hc.v1,10.14293,10.14293,p2199-8442.1.sop-.pnu4hc.v1,10.14293/p,10.14293/p,scienceopen.com,scienceopen.com/hosted-document

In [30]:
ScienceOpen_parent_df, ScienceOpen_parent_summary = analyze_parent_data("ScienceOpen Preprints", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SCIENCEOPEN PREPRINTS
=================================================================
  > Total Parent Groups:     1,624
  > Total Versions Found:    2,027
  > Unique Parent DOIs:      1,624
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for ScienceOpen Preprints:
-----------------------------------
  1 version(s):     1,342 groups
  2 version(s):     207 groups
  3 version(s):     49 groups
  4 version(s):     16 groups
  5 version(s):     5 groups
  6 version(s):     2 groups
  7 version(s):     2 groups
  9 version(s):     1 groups

  Average versions per parent: 1.25

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
ScienceOpen Preprints                   1474
SSRN                                      33
Preprints.org                             17
Open Science Framework                    13
ResearchGate                              10
Authorea Inc.                             10
Research Square                            9
arXiv                                      8
Authorea Inc.; ScienceOpen Preprints       6
Zenodo                                     5

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.14293/pr    859
10.14293/s     765



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
scienceopen.com    1624


=================================================================
 COMPLETED: SCIENCEOPEN PREPRINTS
=================================================================

# Sciencepaper Online

In [31]:
Sciencepaper_df, Sciencepaper_summary = get_server_data("Sciencepaper_Online")

==================================================
 SERVER ANALYSIS: SCIENCEPAPER_ONLINE
==================================================
  > Files found:    1
  > Raw records:    99
  > Cleaned shape:  (99, 90)
  > Unique DOIs:    99
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.61951/sciencepaperonline    99
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
paper.edu.cn    99
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.61951    99
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
48263    99
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Scientific Research and Development in Higher Education Institutes, Ministry of Education    99
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    99
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
Sciencepaper Online    99
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Metadata Quality    99
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    99
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    99
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    99
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SCIENCEPAPER_ONLINE
==================================================

In [32]:
Sciencepaper_parent_df, Sciencepaper_parent_summary = analyze_parent_data("Sciencepaper Online", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SCIENCEPAPER ONLINE
=================================================================
  > Total Parent Groups:     97
  > Total Versions Found:    97
  > Unique Parent DOIs:      97
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Sciencepaper Online:
-----------------------------------
  1 version(s):     97 groups

  Average versions per parent: 1.00

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Sciencepaper Online    97

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.61951/sciencepaperonline    97



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
paper.edu.cn    97


=================================================================
 COMPLETED: SCIENCEPAPER ONLINE
=================================================================

# searchRxiv

In [33]:
searchRxiv_df, searchRxiv_summary = get_server_data("searchRxiv")

==================================================
 SERVER ANALYSIS: SEARCHRXIV
==================================================
  > Files found:    2
  > Raw records:    1234
  > Cleaned shape:  (1234, 90)
  > Unique DOIs:    1234
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.1079/searchrxiv    1234
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
cabidigitallibrary.org    1234
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.1079    1234
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
242    1234
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
CABI Publishing    1234
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None          1232
searchRxiv       2
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    1234
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
searchRxiv    1232
None             2
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None         1232
2791-1977       2
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content     1232
journal-article       2
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
other    1232
None        2
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SEARCHRXIV
==================================================

In [34]:
searchRxiv_parent_df, searchRxiv_parent_summary = analyze_parent_data("searchRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SEARCHRXIV
=================================================================
  > Total Parent Groups:     529
  > Total Versions Found:    1,221
  > Unique Parent DOIs:      529
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for searchRxiv:
-----------------------------------
  1 version(s):     368 groups
  2 version(s):     28 groups
  3 version(s):     26 groups
  4 version(s):     27 groups
  5 version(s):     20 groups
  6 version(s):     18 groups
  7 version(s):     16 groups
  8 version(s):     9 groups
  9 version(s):     6 groups
  10 version(s):    2 groups
  11 version(s):    4 groups
  14 version(s):    2 groups
  15 version(s):    1 groups
  21 version(s):    1 groups
  37 version(s):    1 groups

  Average versions per parent: 2.31

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
searchRxiv         518
Research Square      6
JMIR Preprints       3
PsyArXiv             1
Zenodo               1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.1079/searchrxiv    529



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
cabidigitallibrary.org    529


=================================================================
 COMPLETED: SEARCHRXIV
=================================================================

# SocArXiv

In [35]:
SocArXiv_df, SocArXiv_summary = get_server_data("SocArXiv")

==================================================
 SERVER ANALYSIS: SOCARXIV
==================================================
  > Files found:    1
  > Raw records:    21541
  > Cleaned shape:  (21541, 90)
  > Unique DOIs:    21541
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31235/osf    19755
10.31219/osf      594
10.31234/osf      385
10.31227/osf      357
10.31228/osf      133
10.31223/osf      103
10.31224/osf       95
10.31231/osf       35
10.31229/osf       30
10.31225/osf       29
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    21541
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31235    19755
10.31219      594
10.31234      385
10.31227      357
10.31228      133
10.31223      103
10.31224       95
10.31231       35
10.31229       30
10.31225       29
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    21392
29705      103
33966       33
242         13
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             21392
California Digital Library (CDL)      103
Open Engineering Inc                   33
CABI Publishing                        13
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    21541
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    21541
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
SocArXiv    21541
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    21541
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    21541
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    21541
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SOCARXIV
==================================================

In [36]:
SocArXiv_parent_df, SocArXiv_parent_summary = analyze_parent_data("SocArXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SOCARXIV
=================================================================
  > Total Parent Groups:     18,026
  > Total Versions Found:    23,686
  > Unique Parent DOIs:      18,026
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for SocArXiv:
-----------------------------------
  1 version(s):     13,586 groups
  2 version(s):     3,439 groups
  3 version(s):     846 groups
  4 version(s):     117 groups
  5 version(s):     27 groups
  6 version(s):     4 groups
  7 version(s):     3 groups
  8 version(s):     2 groups
  10 version(s):    2 groups

  Average versions per parent: 1.31

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
SocArXiv                            14741
SSRN                                 1108
Open Science Framework; SocArXiv     1026
Open Science Framework                868
CrimRxiv                               43
arXiv                                  38
SocArXiv; arXiv                        26
Research Square                        22
ResearchGate; SocArXiv                 22
Humanities Commons CORE                13

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31235/osf    18025
10.31219/osf        1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io    18026


=================================================================
 COMPLETED: SOCARXIV
=================================================================

# Social Science Open Access Repository

In [37]:
Social_Science_Open_Access_Repository_df, Social_Science_Open_Access_Repository_summary = get_server_data("Social_Science_Open_Access_Repository")

==================================================
 SERVER ANALYSIS: SOCIAL_SCIENCE_OPEN_ACCESS_REPOSITORY
==================================================
  > Files found:    1
  > Raw records:    27201
  > Cleaned shape:  (27201, 90)
  > Unique DOIs:    6679
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>                      20522
10.12759/hsr               1411
10.21241/ssoar              815
10.23668/psycharchives      437
10.14765/zzf                365
10.17169/fqs-               296
10.5281/zenodo              216
10.15464/isi                202
10.14764/10                 194
10.11588/iqas               189
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
ssoar.info                     26545
wbv.de                           267
publikationen.soziologie.de      135
doi.org                          111
hdl.handle.net                    31
journals.sub.uni-hamburg.de       21
uni-graz.at                       12
verbraucherzentrale.nrw            7
aseas.univie.ac.at                 6
verbraucherforschung.nrw           5
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        20522
10.12759     1411
10.21241      815
10.23668      437
10.18449      391
10.14765      365
10.17169      318
10.11588      314
10.3278       285
10.5281       216
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    27201
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    27201
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    27201
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    27201
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    27201
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    27201
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
article         25627
preprint          908
book-chapter      207
book              174
other             169
review             33
report             32
editorial          27
dissertation       23
dataset             1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    27201
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SOCIAL_SCIENCE_OPEN_ACCESS_REPOSITORY
==================================================

In [38]:
ssoar_parent_df, ssoar_parent_summary = analyze_parent_data("Social Science Open Access Repository", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SOCIAL SCIENCE OPEN ACCESS REPOSITORY
=================================================================
  > Total Parent Groups:     26,905
  > Total Versions Found:    27,266
  > Unique Parent DOIs:      6,581
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Social Science Open Access Repository:
-----------------------------------
  1 version(s):     26,597 groups
  2 version(s):     274 groups
  3 version(s):     24 groups
  4 version(s):     2 groups
  5 version(s):     7 groups
  6 version(s):     1 groups

  Average versions per parent: 1.01

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Social Science Open Access Repository                                         26741
SSRN                                                                             80
RePEc: Research Papers in Economics                                              17
RePEc: Research Papers in Economics; Social Science Open Access Repository       13
ResearchGate                                                                     12
EconStor Preprints; Social Science Open Access Repository                         9
HAL; Social Science Open Access Repository                                        6
Humanities Commons CORE                                                           6
AgEcon Search                                                                     4
EconStor Preprints                                                                3

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>                      20324
10.12759/hsr               1398
10.21241/ssoar              798
10.23668/psycharchives      436
10.14765/zzf                365
10.17169/fqs-               295
10.5281/zenodo              205
10.15464/isi                202
10.14764/10                 192
10.11588/iqas               189



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
ssoar.info                     26253
wbv.de                           267
publikationen.soziologie.de      135
doi.org                          111
hdl.handle.net                    28
journals.sub.uni-hamburg.de       21
uni-graz.at                       12
verbraucherzentrale.nrw            7
aseas.univie.ac.at                 6
verbraucherforschung.nrw           5


=================================================================
 COMPLETED: SOCIAL SCIENCE OPEN ACCESS REPOSITORY
=================================================================

In [39]:
Social_Science_Open_Access_Repository_df['doi_prefix_first_token'].value_counts()

doi_prefix_first_token
10.12759/hsr              1411
10.21241/ssoar             815
10.23668/psycharchives     437
10.14765/zzf               365
10.17169/fqs-              296
                          ...
10.18449/2020s26             1
10.18449/2021c14             1
10.18449/2020c44             1
10.18449/2019s15             1
10.60922/226h                1
Name: count, Length: 722, dtype: int64

In [40]:
Social_Science_Open_Access_Repository_df[Social_Science_Open_Access_Repository_df['doi_prefix_first_token']=='10.60922/226h']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
11749,openalex::W3136189946,Social Science Open Access Repository,openalex,https://openalex.org/W3136189946,10.60922/226h-hc50,https://doi.org/10.60922/226h-hc50,https://www.ssoar.info/ssoar/handle/document/7...,https://www.ssoar.info/ssoar/handle/document/7...,10.60922,None,None,None,openalex,None,None,None,None,None,Einsamkeit steigt in der Corona-Pandemie bei M...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2021-02-01,None,2021,openalex.publication_date,None,True,green,None,None,"{""2014"": [51], ""2017."": [53], ""2020"": [2], ""46...",Seit März 2020 haben die Maßnahmen zur Eindämm...,None,https://www.ssoar.info/ssoar/handle/document/7...,Oliver Huxhold; Clemens Tesch‐Römer,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Gynecology"", ""id"": ""https:/...","[{""display_name"": ""COVID-19 and Mental Health""...",2,None,2,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""2014"": [51], ""20...",10.60922/226h-hc50,10.60922,10.60922,226h-hc50,10.60922/226h,10.60922/226h,ssoar.info,ssoar.info/ssoar

In [41]:
Social_Science_Open_Access_Repository_df[Social_Science_Open_Access_Repository_df['doi_prefix_first_token']=='10.23668/psycharchives']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
162,openalex::W2247431608,Social Science Open Access Repository,openalex,https://openalex.org/W2247431608,10.23668/psycharchives.13780,https://doi.org/10.23668/psycharchives.13780,http://www.ssoar.info/ssoar/handle/document/2824,http://www.ssoar.info/ssoar/handle/document/2824,10.23668,None,None,None,openalex,None,None,None,None,None,Die Psychologie der Metapher und die (vermitte...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2001-01-01,None,2001,openalex.publication_date,None,True,green,None,None,"{""\""hervorzubringen\"""": [46], ""Allerdings"": [2...","Es werden Überlegungen angestellt zur Frage, w...",None,http://www.ssoar.info/ssoar/handle/document/2824,Anil Jain,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Philosophy"", ""id"": ""https:/...","[{""display_name"": ""Language, Metaphor, and Cog...",31,None,31,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""\""hervorzubringe...",10.23668/psycharchives.13780,10.23668,10.23668,psycharchives.13780,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
232,openalex::W965965652,Social Science Open Access Repository,openalex,https://openalex.org/W965965652,10.23668/psycharchives.13449,https://doi.org/10.23668/psycharchives.13449,http://www.ssoar.info/ssoar/handle/document/3377,http://www.ssoar.info/ssoar/handle/document/3377,10.23668,None,None,None,openalex,None,None,None,None,None,Buchbesprechung zu: Gerhard Kleining: Lehrbuch...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2000-01-01,None,2000,openalex.publication_date,None,True,green,None,None,"{""None."": [0]}",None.,None,http://www.ssoar.info/ssoar/handle/document/3377,Christoph Klotter,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Philosophy"", ""id"": ""https:/...","[{""display_name"": ""Sociology and Education Stu...",81,None,81,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""None."": [0]}, ""a...",10.23668/psycharchives.13449,10.23668,10.23668,psycharchives.13449,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
420,openalex::W1521498110,Social Science Open Access Repository,openalex,https://openalex.org/W1521498110,10.23668/psycharchives.8801,https://doi.org/10.23668/psycharchives.8801,http://www.ssoar.info/ssoar/handle/document/4977,http://www.ssoar.info/ssoar/handle/document/4977,10.23668,None,None,None,openalex,None,None,None,None,None,Denkverbote gibt es nicht! Vorschlag zur inter...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1998-01-01,None,1998,openalex.publication_date,None,True,green,None,None,"{""\""Zustand"": [84], ""Als"": [73], ""Anhang"": [90...",Im Bereich qualitativer Sozialforschung liegen...,None,https://hdl.handle.net/20.500.11780/153,Eva Jaeggi; Angelika Faas; Katja Mruck,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Political science"", ""id"": ""...","[{""display_name"": ""Sociology and Education Stu...",25,None,25,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""\""Zustand"": [84]...",10.23668/psycharchives.8801,10.23668,10.23668,psycharchives.8801,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
574,openalex::W1005388835,Social Science Open Access Repository,openalex,https://openalex.org/W1005388835,10.23668/psycharchives.13426,https://doi.org/10.23668/psycharchives.13426,http://www.ssoar.info/ssoar/handle/document/3353,http://www.ssoar.info/ssoar/handle/document/3353,10.23668,None,None,None,openalex,None,None,None,None,None,Buchbesprechung zu: Hans Thomae: Das Individuu...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1998-01-01,None,1998,openalex.publication_date,None,True,green,None,None,"{""None."": [0]}",None.,None,http://www.ssoar.info/ssoar/handle/document/3353,Wolfgang Hegener,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Philosophy"", ""id"": ""https:/...","[{""display_name"": ""Critical Theory and Philoso...",52,None,52,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""None."": [0]}, ""a...",10.23668/psycharchives.13426,10.23668,10.23668,psycharchives.13426,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
706,openalex::W2228048313,Social Science Open Access Repository,openalex,https://openalex.org/W2228048313,10.23668/psycharchives.13292,https://doi.org/10.23668/psycharchives.13292,http://www.ssoar.info/ssoar/handle/document/2059,http://www.ssoar.info/ssoar/handle/document/2059,10.23668,None,None,None,openalex,None,None,None,None,None,"Buchbesprechung zu: Richard Rorty: Kontingenz,...",None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1994-01-01,None,1994,openalex.publication_date,None,True,green,None,None,"{""None."": [0]}",None.,None,http://www.ssoar.info/ssoar/handle/document/2059,Thomas Leithäuser,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Philosophy"", ""id"": ""https:/...","[{""display_name"": ""Pragmatism in Philosophy an...",22,None,22,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""None."": [0]}, ""a...",10.23668/psycharchives.13292,10.23668,10.23668,psycharchives.13292,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27087,openalex::W984680515,Social Science Open Access Repository,openalex,https://openalex.org/W984680515,10.23668/psycharchives.13787,https://doi.org/10.23668/psycharchives.13787,http://www.ssoar.info/ssoar/handle/document/2831,http://www.ssoar.info/ssoar/handle/document/2831,10.23668,None,None,None,openalex,None,None,None,None,None,Psychisches Erleben von gesellschaftlicher Aus...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2001-01-01,None,2001,openalex.publication_date,None,True,green,None,None,"{""An-sich-selbst-Verzweifelns"": [76], ""Anerken...","Auf der Grundlage eines Interviews, das Pierre...",None,http://www.ssoar.info/ssoar/handle/document/2831,Eva Puschmann; Eva Sabel,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Political science"", ""id"": ""...","[{""display_name"": ""Psychoanalysis and Social C...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""An-sich-selbst-V...",10.23668/psycharchives.13787,10.23668,10.23668,psycharchives.13787,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
27089,openalex::W984871001,Social Science Open Access Repository,openalex,https://openalex.org/W984871001,10.23668/psycharchives.13318,https://doi.org/10.23668/psycharchives.13318,http://www.ssoar.info/ssoar/handle/document/2171,http://www.ssoar.info/ssoar/handle/document/2171,10.23668,None,None,None,openalex,None,None,None,None,None,Geh nicht nach Haus: Laudatio zur Ehrenpromoti...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1993-01-01,None,1993,openalex.publication_date,None,True,green,None,None,"{""None."": [0]}",None.,None,http://www.ssoar.info/ssoar/handle/document/2171,Thomas Leithäuser,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Philosophy"", ""id"": ""https:/...","[{""display_name"": ""Linguistic research and ana...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""None."": [0]}, ""a...",10.23668/psycharchives.13318,10.23668,10.23668,psycharchives.13318,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
27104,openalex::W987434198,Social Science Open Access Repository,openalex,https://openalex.org/W987434198,10.23668/psycharchives.13408,https://doi.org/10.23668/psycharchives.13408,http://www.ssoar.info/ssoar/handle/document/3284,http://www.ssoar.info/ssoar/handle/document/3284,10.23668,None,None,None,openalex,None,None,None,None,None,Buchbesprechung zu: Klaus Weber (Hrsg.). Unter...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2000-01-01,None,2000,openalex.publication_date,None,True,green,None,None,"{""None."": [0]}",None.,None,http://www.ssoar.info/ssoar/handle/document/3284,Lothar Schon,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Philosophy"", ""id"": ""https:/...","[{""display_name"": ""German legal, social, and p...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""None."": [0]}, ""a...",10.23668/psycharchives.13408,10.23668,10.23668,psycharchives.13408,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
27131,openalex::W990194860,Social Science Open Access Repository,openalex,https://openalex.org/W990194860,10.23668/psycharchives.13904,https://doi.org/10.23668/psycharchives.13904,http://www.ssoar.info/ssoar/handle/document/3999,http://www.ssoar.info/ssoar/handle/document/3999,10.23668,None,None,None,openalex,None,None,None,None,None,Angst vor dem Satan - die fundamentalistische ...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1998-01-01,None,1998,openalex.publication_date,None,True,green,None,None,"{""\""Boston"": [9], ""\""Psychotechniken\"""": [25],...",Vorgestellt wird eine derzeit sehr einflußreic...,None,http://www.ssoar.info/ssoar/handle/document/3999,Frank Nordhausen,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Theology"", ""id"": ""https://o...","[{""display_name"": ""Psychoanalysis and Social C...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""\""Boston"": [9], ...",10.23668/psycharchives.13904,10.23668,10.23668,psycharchives.13904,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar
27170,openalex::W994952700,Social Science Open Access Repository,openalex,https://openalex.org/W994952700,10.23668/psycharchives.13299,https://doi.org/10.23668/psycharchives.13299,http://www.ssoar.info/ssoar/handle/document/2083,http://www.ssoar.info/ssoar/handle/document/2083,10.23668,None,None,None,openalex,None,None,None,None,None,Im Gespräch: Anna Rosmus mit Angelika Faas und...,None,None,None,de,article,None,article,False,False,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1994-01-01,None,1994,openalex.publication_date,None,True,green,None,None,"{""None."": [0]}",None.,None,http://www.ssoar.info/ssoar/handle/document/2083,Thomas Krauß; Angelika Faas,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,NaN,None,"[{""display_name"": ""Art"", ""id"": ""https://openal...","[{""display_name"": ""German Literature and Cultu...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,16,None,"{""abstract_inverted_index"": {""None."": [0]}, ""a...",10.23668/psycharchives.13299,10.23668,10.23668,psycharchives.13299,10.23668/psycharchives,10.23668/psycharchives,ssoar.info,ssoar.info/ssoar

# SportRxiv

In [42]:
SportRxiv_df, SportRxiv_summary = get_server_data("SportRxiv")

==================================================
 SERVER ANALYSIS: SPORTRXIV
==================================================
  > Files found:    2
  > Raw records:    878
  > Cleaned shape:  (878, 90)
  > Unique DOIs:    878
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.51224/srxiv    492
10.31236/osf      350
10.31227/osf       12
10.31234/osf        6
10.31231/osf        6
10.31219/osf        5
10.31223/osf        4
10.31235/osf        2
10.31229/osf        1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
sportrxiv.org    492
osf.io           386
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.51224    492
10.31236    350
10.31227     12
10.31234      6
10.31231      6
10.31219      5
10.31223      4
10.31235      2
10.31229      1
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
7569     492
15934    382
29705      4
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
University of Ottawa Library        492
Center for Open Science             382
California Digital Library (CDL)      4
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    878
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    878
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None         492
SportRxiv    386
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    878
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    878
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    878
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR SPORTRXIV
==================================================

In [43]:
SportRxiv_parent_df, SportRxiv_parent_summary = analyze_parent_data("SportRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SPORTRXIV
=================================================================
  > Total Parent Groups:     847
  > Total Versions Found:    898
  > Unique Parent DOIs:      847
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for SportRxiv:
-----------------------------------
  1 version(s):     800 groups
  2 version(s):     43 groups
  3 version(s):     4 groups

  Average versions per parent: 1.06

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
SportRxiv                            810
Open Science Framework; SportRxiv     28
JMIR Preprints                         2
Research Square                        2
arXiv                                  2
Open Science Framework                 1
ResearchGate; SportRxiv                1
SSRN                                   1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.51224/srxiv    480
10.31236/osf      366
10.31236/srxiv      1



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
sportrxiv.org    481
osf.io           366


=================================================================
 COMPLETED: SPORTRXIV
=================================================================

# SSRN

In [44]:
# SSRN_df, SSRN_summary = get_server_data("SSRN")

In [45]:
SSRN_parent_df, SSRN_parent_summary = analyze_parent_data("SSRN", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: SSRN
=================================================================
  > Total Parent Groups:     1,120,944
  > Total Versions Found:    1,235,560
  > Unique Parent DOIs:      1,120,944
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for SSRN:
-----------------------------------
  1 version(s):     1,022,779 groups
  2 version(s):     85,658 groups
  3 version(s):     10,164 groups
  4 version(s):     1,749 groups
  5 version(s):     349 groups
  6 version(s):     104 groups
  7 version(s):     53 groups
  8 version(s):     29 groups
  9 version(s):     15 groups
  10 version(s):    8 groups
  11 version(s):    3 groups
  12 version(s):    4 groups
  13 version(s):    7 groups
  14 version(s):    3 groups
  15 version(s):    1 groups
  16 version(s):    4 groups
  17 version(s):    1 groups
  19 version(s):    1 groups
  20 version(s):    1 groups
  21 version(s):    1 groups
  22 version(s):    2 groups
  24 version(s):    2 groups
  28 version(s):    1 groups
  30 version(s):    1 groups
  31 version(s):    1 groups
  32 version(s):    1 groups
  43 version(s):    1 groups
  164 version(s):   1 groups

  Average versions per parent: 1.10

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
SSRN                                         1085149
arXiv                                           9443
RePEc: Research Papers in Economics             5765
Research Square                                 4131
AgEcon Search                                   3135
ResearchGate                                    2109
RePEc: Research Papers in Economics; SSRN       1468
bioRxiv                                         1395
Zenodo                                           974
Open Science Framework                           803

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.2139/ssrn    1120944



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
ssrn.com           1120932
papers.ssrn.com          9
doi.org                  2
crossref.org             1


=================================================================
 COMPLETED: SSRN
=================================================================

# TechRxiv

In [46]:
TechRxiv_df, TechRxiv_summary = get_server_data("TechRxiv")

==================================================
 SERVER ANALYSIS: TECHRXIV
==================================================
  > Files found:    1
  > Raw records:    29418
  > Cleaned shape:  (29418, 90)
  > Unique DOIs:    29418
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.36227/techrxiv    29418
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
techrxiv.org             29088
techrxiv.figshare.com      324
essopenarchive.org           5
figshare.com                 1
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.36227    29418
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
263    29418
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Institute of Electrical and Electronics Engineers (IEEE)    29418
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    29418
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
TechRxiv          15026
Techrxiv          10126
None               3562
Authorea, Inc.      703
figshare              1
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None         18589
Preprints    10829
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    29418
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    29418
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    29418
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR TECHRXIV
==================================================

In [47]:
TechRxiv_parent_df, TechRxiv_parent_summary = analyze_parent_data("TechRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: TECHRXIV
=================================================================
  > Total Parent Groups:     16,216
  > Total Versions Found:    27,311
  > Unique Parent DOIs:      16,216
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for TechRxiv:
-----------------------------------
  1 version(s):     7,677 groups
  2 version(s):     6,764 groups
  3 version(s):     1,291 groups
  4 version(s):     336 groups
  5 version(s):     79 groups
  6 version(s):     38 groups
  7 version(s):     9 groups
  8 version(s):     11 groups
  9 version(s):     4 groups
  10 version(s):    2 groups
  11 version(s):    2 groups
  12 version(s):    2 groups
  13 version(s):    1 groups

  Average versions per parent: 1.68

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
TechRxiv                  15748
arXiv                       209
SSRN                         93
Research Square              48
TechRxiv; arXiv              39
Authorea Inc.                18
ResearchGate                 13
Preprints.org                12
Open Science Framework       10
ResearchGate; TechRxiv        5

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.36227/techrxiv    16216



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
techrxiv.org             16069
techrxiv.figshare.com      143
essopenarchive.org           4


=================================================================
 COMPLETED: TECHRXIV
=================================================================

In [48]:
TechRxiv_parent_df[TechRxiv_parent_df['primary_domain']=='figshare.com']

Empty DataFrame
Columns: [dup_group_id_full, parent_record_id, parent_server_name, parent_doi, parent_url, parent_title, parent_authors, parent_date_first_seen, parent_year_first_seen, version_record_ids, version_dois, servers_with_counts, total_versions, first_version_date, last_version_date, most_recent_version_servers, doi_lc, prefix_lc, doi_prefix_from_text, doi_suffix, doi_prefix_first_token, doi_prefix_bucket_2d, primary_domain, primary_domain_extend]
Index: []

https://doi.org/10.36227/techrxiv.12480425.v1 on techrxiv 

10.36227/techrxiv.12480425 on figshare

In [49]:
TechRxiv_parent_df[TechRxiv_parent_df['primary_domain']=='essopenarchive.org']

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
2600119,crossref::10.36227/techrxiv.171207488.83541017/v1,crossref::10.36227/techrxiv.171207488.83541017/v1,TechRxiv,10.36227/techrxiv.171207488.83541017/v1,https://essopenarchive.org/users/556129/articl...,Effective media models for wave propagation in...,"Fu, Li-Yun; Yang, Haidi; Fu, Bo-Ye; Müller, To...",2024-04-02,2024,crossref::10.36227/techrxiv.171207488.83541017/v1,10.36227/techrxiv.171207488.83541017/v1,TechRxiv (1),1,2024-04-02,2024-04-02,TechRxiv,10.36227/techrxiv.171207488.83541017/v1,10.36227,10.36227,techrxiv.171207488.83541017/v1,10.36227/techrxiv,10.36227/techrxiv,essopenarchive.org,essopenarchive.org/users
4814340,crossref::10.36227/techrxiv.171043391.14447454/v1,crossref::10.36227/techrxiv.171043391.14447454/v1,TechRxiv,10.36227/techrxiv.171043391.14447454/v1,https://essopenarchive.org/users/524243/articl...,Geodetic anomaly detection and analysis in the...,"Giudicepietro, Flora; Casu, Francesco; Bonano,...",2024-03-14,2024,crossref::10.36227/techrxiv.171043391.14447454...,10.36227/techrxiv.171043391.14447454/v1; 10.36...,TechRxiv (2),2,2024-03-14,2024-04-08,TechRxiv,10.36227/techrxiv.171043391.14447454/v1,10.36227,10.36227,techrxiv.171043391.14447454/v1,10.36227/techrxiv,10.36227/techrxiv,essopenarchive.org,essopenarchive.org/users
5914615,crossref::10.36227/techrxiv.20128406.v1,crossref::10.36227/techrxiv.20128406.v1,TechRxiv,10.36227/techrxiv.20128406.v1,https://essopenarchive.org/users/535193/articl...,Automatic Detection of InSAR Surface Deformati...,"Staniewicz, Scott; Chen, Jingyi",2023-10-30,2023,crossref::10.36227/techrxiv.20128406.v1; cross...,10.36227/techrxiv.20128406.v1; 10.36227/techrx...,TechRxiv (2),2,2023-10-30,2024-03-18,TechRxiv,10.36227/techrxiv.20128406.v1,10.36227,10.36227,techrxiv.20128406.v1,10.36227/techrxiv,10.36227/techrxiv,essopenarchive.org,essopenarchive.org/users
6135961,crossref::10.36227/techrxiv.171470721.15780746/v1,crossref::10.36227/techrxiv.171470721.15780746/v1,TechRxiv,10.36227/techrxiv.171470721.15780746/v1,https://essopenarchive.org/users/523866/articl...,A Fast Three-dimensional Imaging Scheme of Air...,"Tang, Rongjiang; Gan, Lu; Li, Fusheng; Shen, F...",2024-05-03,2024,crossref::10.36227/techrxiv.171470721.15780746/v1,10.36227/techrxiv.171470721.15780746/v1,TechRxiv (1),1,2024-05-03,2024-05-03,TechRxiv,10.36227/techrxiv.171470721.15780746/v1,10.36227,10.36227,techrxiv.171470721.15780746/v1,10.36227/techrxiv,10.36227/techrxiv,essopenarchive.org,essopenarchive.org/users

all essopenarchive.org are on techrxiv

# Therapoid

In [50]:
Therapoid_df, Therapoid_summary = get_server_data("Therapoid")

==================================================
 SERVER ANALYSIS: THERAPOID
==================================================
  > Files found:    1
  > Raw records:    7
  > Cleaned shape:  (7, 90)
  > Unique DOIs:    7
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.24973/20    7
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
therapoid.net    7
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.24973    7
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
10597    7
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Therapoid            6
Open Therapeutics    1
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    7
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    7
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
ACME Project                                                                                                     1
None                                                                                                             1
How storytelling can help drive system change...                                                                 1
An Introduction to Therapoid and the ‘Bitcoin of Science’                                                        1
Blockchain for open scientific collaboration and impact - Article in AESIS General Newsletter November 2022      1
Blockchain for open scientific collaboration and impact (published in AESIS General Newsletter November 2022)    1
On Flores Island, do "ape-men" still exist? https://www.sapiens.org/biology/flores-island-ape-men/               1
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    7
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    7
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
other       5
preprint    2
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR THERAPOID
==================================================

In [51]:
Therapoid_parent_df, Therapoid_parent_summary = analyze_parent_data("Therapoid", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: THERAPOID
=================================================================
  > Total Parent Groups:     6
  > Total Versions Found:    7
  > Unique Parent DOIs:      6
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Therapoid:
-----------------------------------
  1 version(s):     5 groups
  2 version(s):     1 groups

  Average versions per parent: 1.17

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Therapoid    6

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.24973/20    6



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
therapoid.net    6


=================================================================
 COMPLETED: THERAPOID
=================================================================

# Thesis Commons

In [52]:
Thesis_df, Thesis_summary = get_server_data("Thesis_Commons")

==================================================
 SERVER ANALYSIS: THESIS_COMMONS
==================================================
  > Files found:    1
  > Raw records:    3959
  > Cleaned shape:  (3959, 90)
  > Unique DOIs:    3959
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.31237/osf    3663
10.31227/osf     103
10.31231/osf      45
10.31219/osf      38
10.31228/osf      30
10.31234/osf      18
10.31230/osf      18
10.31235/osf      14
10.31223/osf      10
10.31220/osf      10
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
osf.io    3959
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.31237    3663
10.31227     103
10.31231      45
10.31219      38
10.31228      30
10.31234      18
10.31230      18
10.31235      14
10.31223      10
10.31220      10
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
15934    3939
242        10
29705      10
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Center for Open Science             3939
CABI Publishing                       10
California Digital Library (CDL)      10
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    3959
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    3959
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Thesis Commons    3959
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    3959
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    3959
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    3959
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR THESIS_COMMONS
==================================================

In [53]:
Thesis_parent_df, Thesis_parent_summary = analyze_parent_data("Thesis Commons", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: THESIS COMMONS
=================================================================
  > Total Parent Groups:     3,220
  > Total Versions Found:    4,327
  > Unique Parent DOIs:      3,220
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Thesis Commons:
-----------------------------------
  1 version(s):     2,734 groups
  2 version(s):     393 groups
  3 version(s):     57 groups
  4 version(s):     14 groups
  5 version(s):     5 groups
  6 version(s):     1 groups
  7 version(s):     3 groups
  8 version(s):     2 groups
  9 version(s):     1 groups
  11 version(s):    1 groups
  13 version(s):    1 groups
  14 version(s):    1 groups
  16 version(s):    2 groups
  29 version(s):    1 groups
  46 version(s):    1 groups
  100 version(s):   1 groups
  108 version(s):   1 groups
  150 version(s):   1 groups

  Average versions per parent: 1.34

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Thesis Commons                            3070
Open Science Framework; Thesis Commons      59
Open Science Framework                      16
EdArXiv; Thesis Commons                     11
SSRN                                         8
EdArXiv                                      8
INA-Rxiv                                     7
SocArXiv                                     5
PsyArXiv                                     5
ResearchGate; Thesis Commons                 3

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.31237/osf    3212
10.17605/osf       8



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
osf.io               3212
thesiscommons.org       8


=================================================================
 COMPLETED: THESIS COMMONS
=================================================================

# UCL Open Environment

In [54]:
UCL_df, UCL_summary = get_server_data("UCL_Open_Environment")

==================================================
 SERVER ANALYSIS: UCL_OPEN_ENVIRONMENT
==================================================
  > Files found:    2
  > Raw records:    369
  > Cleaned shape:  (369, 90)
  > Unique DOIs:    369
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.14324/11                317
10.14324/ucloepreprints     51
10.14324/ucloe               1
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
journals.uclpress.co.uk    364
ucl.scienceopen.com          5
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.14324    369
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
5433    369
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
UCL Press    369
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None                    232
UCL Open Environment    137
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None           191
ScienceOpen    178
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None                              315
UCL Open Environment               41
UCL Open Environment Preprints     13
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None         232
2632-0886    137
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content     232
journal-article    136
journal-issue        1
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    232
None        137
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR UCL_OPEN_ENVIRONMENT
==================================================

/tmp/ipykernel_3327/1196196344.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  raw_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)

In [55]:
UCL_parent_df, UCL_parent_summary = analyze_parent_data("UCL Open Environment", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: UCL OPEN ENVIRONMENT
=================================================================
  > Total Parent Groups:     173
  > Total Versions Found:    366
  > Unique Parent DOIs:      173
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for UCL Open Environment:
-----------------------------------
  1 version(s):     85 groups
  2 version(s):     15 groups
  3 version(s):     48 groups
  4 version(s):     22 groups
  5 version(s):     2 groups
  9 version(s):     1 groups

  Average versions per parent: 2.12

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
UCL Open Environment    173

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.14324/11                150
10.14324/ucloepreprints     23



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
journals.uclpress.co.uk    171
ucl.scienceopen.com          2


=================================================================
 COMPLETED: UCL OPEN ENVIRONMENT
=================================================================

# UnisaRxiv

In [56]:
UnisaRxiv_df, UnisaRxiv_summary = get_server_data("UnisaRxiv")

==================================================
 SERVER ANALYSIS: UNISARXIV
==================================================
  > Files found:    1
  > Raw records:    126
  > Cleaned shape:  (126, 90)
  > Unique DOIs:    126
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.25159/unisarxiv    126
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
scienceopen.com    126
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.25159    126
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
10792    126
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
UNISA Press    126
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    126
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
ScienceOpen    126
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    126
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    126
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    126
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    126
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR UNISARXIV
==================================================

In [57]:
UnisaRxiv_parent_df, UnisaRxiv_parent_summary = analyze_parent_data("UnisaRxiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: UNISARXIV
=================================================================
  > Total Parent Groups:     120
  > Total Versions Found:    125
  > Unique Parent DOIs:      120
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for UnisaRxiv:
-----------------------------------
  1 version(s):     116 groups
  2 version(s):     3 groups
  3 version(s):     1 groups

  Average versions per parent: 1.04

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
UnisaRxiv       117
SSRN              1
ResearchGate      1
AfricArXiv        1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.25159/unisarxiv    120



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
scienceopen.com    120


=================================================================
 COMPLETED: UNISARXIV
=================================================================

# VeriXiv

In [58]:
VeriXiv_df, VeriXiv_summary = get_server_data("VeriXiv")

==================================================
 SERVER ANALYSIS: VERIXIV
==================================================
  > Files found:    1
  > Raw records:    504
  > Cleaned shape:  (504, 90)
  > Unique DOIs:    504
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/verixiv    504
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
verixiv.org    504
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    504
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    504
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    504
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    504
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    504
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
Gates Foundation    504
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    504
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
posted-content    504
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
preprint    504
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR VERIXIV
==================================================

In [59]:
VeriXiv_parent_df, VeriXiv_parent_summary = analyze_parent_data("VeriXiv", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: VERIXIV
=================================================================
  > Total Parent Groups:     425
  > Total Versions Found:    507
  > Unique Parent DOIs:      425
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for VeriXiv:
-----------------------------------
  1 version(s):     368 groups
  2 version(s):     38 groups
  3 version(s):     13 groups
  4 version(s):     6 groups

  Average versions per parent: 1.19

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
VeriXiv                399
Gates Open Research     24
AgEcon Search            1
Research Square          1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/verixiv    425



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
verixiv.org    425


=================================================================
 COMPLETED: VERIXIV
=================================================================

In [60]:
VeriXiv_parent_df[VeriXiv_parent_df['most_recent_version_servers']=='Research Square']

,dup_group_id_full,parent_record_id,parent_server_name,parent_doi,parent_url,parent_title,parent_authors,parent_date_first_seen,parent_year_first_seen,version_record_ids,version_dois,servers_with_counts,total_versions,first_version_date,last_version_date,most_recent_version_servers,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
7125739,crossref::10.12688/verixiv.2010.1,crossref::10.12688/verixiv.2010.1,VeriXiv,10.12688/verixiv.2010.1,https://verixiv.org/articles/2-286/v1,Maternal screening coverage and determinants d...,"Adelabu, Yusuf; Saalu, Tersur T.; Afolabi, Bos...",2025-09-15,2025,crossref::10.12688/verixiv.2010.1; crossref::1...,10.12688/verixiv.2010.1; 10.21203/rs.3.rs-7490...,Research Square (1); VeriXiv (1),2,2025-09-15,2025-09-17,Research Square,10.12688/verixiv.2010.1,10.12688,10.12688,verixiv.2010.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles

In [61]:
VeriXiv_df

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
0,crossref::10.12688/verixiv.83.1,VeriXiv,crossref,10.12688/verixiv.83.1,10.12688/verixiv.83.1,https://doi.org/10.12688/verixiv.83.1,https://verixiv.org/articles/1-14/v1,https://verixiv.org/articles/1-14/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,Developing a male-specific counselling curricu...,None,None,None,None,posted-content,preprint,preprint,None,True,2024-10-10,2024-10-10,2024-10-11,2025-11-21,None,2024-10-10,None,2024-10-10,None,2024,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Mphande, Misheck; Robson, Isabella; Hubbard, J...",None,None,"[{""affiliation"": [], ""family"": ""Mphande"", ""giv...",None,None,"[{""DOI"": ""10.13039/100000061"", ""award"": [""K01-...",Fogarty International Center; Bill and Melinda...,3.0,None,None,None,0,None,None,0,63,"[{""DOI"": ""10.1080/17441690902942464"", ""article...",None,,,False,None,,None,None,,None,None,None,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.83.1"", ""URL"": ""https...",10.12688/verixiv.83.1,10.12688,10.12688,verixiv.83.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
1,crossref::10.12688/verixiv.197.1,VeriXiv,crossref,10.12688/verixiv.197.1,10.12688/verixiv.197.1,https://doi.org/10.12688/verixiv.197.1,https://verixiv.org/articles/1-15/v1,https://verixiv.org/articles/1-15/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,Discovery of a picomolar antiplasmodial pyrazo...,None,None,None,None,posted-content,preprint,preprint,None,True,2024-10-16,2024-10-16,2024-10-18,2025-07-23,None,2024-10-16,None,2024-10-16,None,2024,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Tchatat Tali, Mariscal Brice; Dize, Darline; Y...",None,None,"[{""affiliation"": [], ""family"": ""Tchatat Tali"",...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,1.0,None,None,None,1,None,None,1,65,"[{""DOI"": ""10.1021/jm990002y"", ""article-title"":...",None,,,False,None,,None,None,,None,None,None,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.197.1"", ""URL"": ""http...",10.12688/verixiv.197.1,10.12688,10.12688,verixiv.197.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
2,crossref::10.12688/verixiv.77.1,VeriXiv,crossref,10.12688/verixiv.77.1,10.12688/verixiv.77.1,https://doi.org/10.12688/verixiv.77.1,https://verixiv.org/articles/1-9/v1,https://verixiv.org/articles/1-9/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,An exploration of unusual antimicrobial resist...,None,None,None,None,posted-content,preprint,preprint,None,True,2024-09-18,2024-09-17,2024-10-21,2025-11-21,None,2024-09-17,None,2024-09-17,None,2024,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,None,None,"[{""URL"": ""https://verixiv.org/articles/1-9/v1/...",https://verixiv.org/articles/1-9/v1/pdf,"Zuza, Allan; Wailan, Alexander M.; Anscombe, C...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-2772-5...",None,None,"[{""DOI"": ""10.13039/100010269"", ""award"": [""2173...",Wellcome Trust; Biotechnology and Biological S...,7.0,None,None,None,0,None,None,0,40,"[{""DOI"": ""10.1016/S1473-3099(18)30685-6"", ""art...",None,,,False,None,,None,None,,None,None,https://doi.org/10.12688/verixiv.crossmark-policy,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.77.1"", ""URL"": ""https...",10.12688/verixiv.77.1,10.12688,10.12688,verixiv.77.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
3,crossref::10.12688/verixiv.15.1,VeriXiv,crossref,10.12688/verixiv.15.1,10.12688/verixiv.15.1,https://doi.org/10.12688/verixiv.15.1,https://verixiv.org/articles/1-1/v1,https://verixiv.org/articles/1-1/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,Foot-and-mouth disease (FMD) vaccine market su...,None,None,None,None,posted-content,preprint,preprint,None,True,2024-08-20,2024-08-20,2024-10-21,2025-11-21,None,2024-08-20,None,2024-08-20,None,2024,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,None,None,"[{""URL"": ""https://verixiv.org/articles/1-1/v1/...",https://verixiv.org/articles/1-1/v1/pdf,"Sopeju, Adebayo Emmanuel; Onoja, Grace; Abiodu...",None,None,"[{""affiliation"": [], ""family"": ""Sopeju"", ""give...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation,2.0,None,None,None,0,None,None,0,17,"[{""DOI"": ""10.4314/NJHBS.V4I2.11550"", ""article-...",None,,,False,None,,None,None,,None,None,https://doi.org/10.12688/verixiv.crossmark-policy,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.15.1"", ""URL"": ""https...",10.12688/verixiv.15.1,10.12688,10.12688,verixiv.15.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
4,crossref::10.12688/verixiv.31.1,VeriXiv,crossref,10.12688/verixiv.31.1,10.12688/verixiv.31.1,https://doi.org/10.12688/verixiv.31.1,https://verixiv.org/articles/1-5/v1,https://verixiv.org/articles/1-5/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,How to estimate causal effects associated with...,None,None,None,None,posted-content,preprint,preprint,None,True,2024-08-22,2024-08-21,2024-10-21,2025-11-21,None,2024-08-21,None,2024-08-21,None,2024,issued_date,posted_date,None,None,http://creativecommons.org/licenses/by/4.0/,http://creativecommons.org/licenses/by/4.0/,None,None,"[{""URL"": ""https://verixiv.org/articles/1-5/v1/...",https://verixiv.org/articles/1-5/v1/pdf,"Godoy Garraza, Lucas; Speizer, Ilene S.; Alkem...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0001-8426-9...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Bill and Melinda Gates Foundation; Children’s ...,3.0,None,None,None,0,None,None,0,25,"[{""DOI"": ""10.1111/sifp.12027"", ""article-title""...",None,,,False,None,,None,None,,None,10.12688/verixiv.31.2,https://doi.org/10.12688/verixiv.crossmark-policy,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.31.1"", ""URL"": ""https...",10.12688/verixiv.31.1,10.12688,10.12688,verixiv.31.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,crossref::10.12688/verixiv.2585.1,VeriXiv,crossref,10.12688/verixiv.2585.1,10.12688/verixiv.2585.1,https://doi.org/10.12688/verixiv.2585.1,https://verixiv.org/articles/2-434/v1,https://verixiv.org/articles/2-434/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,Structural basis for synergistic antibody prot...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-29,2025-12-29,2025-12-29,2025-12-29,None,2025-12-29,None,2025-12-29,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Williams, Barnabas G.; Barrett, Jordan R.; Bar...",None,None,"[{""ORCID"": ""https://orcid.org/0000-0002-3078-8...",None,None,"[{""DOI"": ""10.13039/100014013"", ""award"": [""MR/V...",UK Research and Innovation; Medical Research C...,12.0,None,None,None,0,None,None,0,59,"[{""DOI"": ""10.1016/S0140-6736(23)02743-5"", ""art...",None,,,False,None,,None,None,,None,None,None,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.2585.1"", ""URL"": ""htt...",10.12688/verixiv.2585.1,10.12688,10.12688,verixiv.2585.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
500,crossref::10.12688/verixiv.2092.1,VeriXiv,crossref,10.12688/verixiv.2092.1,10.12688/verixiv.2092.1,https://doi.org/10.12688/verixiv.2092.1,https://verixiv.org/articles/2-307/v1,https://verixiv.org/articles/2-307/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,Assessing Barriers to the Effective Utilizatio...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-09-26,2025-09-26,2025-12-30,2025-12-30,None,2025-09-26,None,2025-09-26,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Sopeju, Adebayo Emmanuel; Onoja, Grace; Ayinla...",None,None,"[{""affiliation"": [], ""family"": ""Sopeju"", ""give...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,49,"[{""DOI"": ""10.37745/ijaerds.15vol9n23246"", ""art...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/verixiv.2152.r4591,None,None,None,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.2092.1"", ""URL"": ""htt...",10.12688/verixiv.2092.1,10.12688,10.12688,verixiv.2092.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
501,crossref::10.12688/verixiv.1789.2,VeriXiv,crossref,10.12688/verixiv.1789.2,10.12688/verixiv.1789.2,https://doi.org/10.12688/verixiv.1789.2,https://verixiv.org/articles/2-243/v2,https://verixiv.org/articles/2-243/v2,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,Physiological Maturity Determination of Wild B...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-11-21,2025-10-24,2025-12-31,2025-12-31,None,2025-10-24,None,2025-10-24,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Sahromi, Sahromi; Widjaya, Aulia Hasan; Latifa...",None,None,"[{""affiliation"": [], ""family"": ""Sahromi"", ""giv...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation; RIIM Batch 2 under LPDP and ...,2.0,None,None,None,0,None,None,0,42,"[{""article-title"": ""Data iklim Kabupaten Bogor...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,10.12688/verixiv.1789.1,None,None,10.21956/verixiv.2339.r4940,None,None,None,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.1789.2"", ""URL"": ""htt...",10.12688/verixiv.1789.2,10.12688,10.12688,verixiv.1789.2,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
502,crossref::10.12688/verixiv.1584.1,VeriXiv,crossref,10.12688/verixiv.1584.1,10.12688/verixiv.1584.1,https://doi.org/10.12688/verixiv.1584.1,https://verixiv.org/articles/2-403/v1,https://verixiv.org/articles/2-403/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,High Spatial Resolution Building Characteristi...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-12-04,2025-12-04,2026-01-02,2026-01-02,None,2025-12-04,None,2025-12-04,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Priyatikanto, Rhorom; Chamberlain, Heather; Bo...",None,None,"[{""affiliation"": [], ""family"": ""Priyatikanto"",...",None,None,None,None,NaN,None,None,None,0,None,None,0,47,"[{""DOI"": ""10.1146/annurev-environ-012220-01082...","{""has-review"": [{""asserted-by"": ""subject"", ""id...",,,False,None,,None,None,10.21956/verixiv.1629.r5278,None,None,None,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.1584.1"", ""URL"": ""htt...",10.12688/verixiv.1584.1,10.12688,10.12688,verixiv.1584.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles
503,crossref::10.12688/verixiv.1044.1,VeriXiv,crossref,10.12688/verixiv.1044.1,10.12688/verixiv.1044.1,https://doi.org/10.12688/verixiv.1044.1,https://verixiv.org/articles/2-233/v1,https://verixiv.org/articles/2-233/v1,10.12688,2560,None,None,crossref,F1000 Research Ltd,None,None,Gates Foundation,None,Service Delivery Redesign for Improved Materna...,None,None,None,None,posted-content,preprint,preprint,None,True,2025-08-18,2025-08-18,2026-01-05,2026-01-05,None,2025-08-18,None,2025-08-18,None,2025,issued_date,posted_date,None,None,https://creativecommons.org/licenses/by/4.0/,https://creativecommons.org/licenses/by/4.0/,None,None,None,None,"Ariff, Shabina; Alam, Ridwa; Hussain, Amber; S...",None,None,"[{""affiliation"": [], ""family"": ""Ariff"", ""given...",None,None,"[{""DOI"": ""10.13039/100000865"", ""award"": [""INV-...",Gates Foundation,1.0,None,None,None,0,None,None,0,22,"[{""DOI"": ""10.1016/S0140-6736(15)00838-7"", ""art...",None,,,False,None,,None,None,,None,None,None,prefix/primary_domain,40,None,"{""DOI"": ""10.12688/verixiv.1044.1"", ""URL"": ""htt...",10.12688/verixiv.1044.1,10.12688,10.12688,verixiv.1044.1,10.12688/verixiv,10.12688/verixiv,verixiv.org,verixiv.org/articles

In [62]:
VeriXiv_df['funders_flat'].value_counts()

funders_flat
Bill and Melinda Gates Foundation                                                                                                                                                                                                                                                          261
Gates Foundation                                                                                                                                                                                                                                                                            93
Bill and Melinda Gates Foundation; African Economic Research Consortium                                                                                                                                                                                                                      4
Bill and Melinda Gates Foundation; Children’s Investment Fund Foundation                                                                                                                                                                                                                     4
Bill and Melinda Gates Foundation; Children's Investment Fund Foundation                                                                                                                                                                                                                     4
                                                                                                                                                                                                                                                                                          ...
Bill and Melinda Gates Foundation; Helium Health and Solina Centre for International Development and Research                                                                                                                                                                                1
Biotechnology and Biological Sciences Research Council; Wellcome Trust                                                                                                                                                                                                                       1
Gates Foundation; Science Foundation Ireland and Irish Aid                                                                                                                                                                                                                                   1
UK Research and Innovation; Medical Research Council; Horizon 2020; Bill and Melinda Gates Foundation; Novo Nordisk; Professor Ronald A. Milligan Endowed Fellowship in the Skaggs Graduate School of Chemical and Biological Sciences; Novo Nordisk Foundation Postdoctoral Fellowship      1
Gates Foundation; RIIM Batch 2 under LPDP and Deputy of Research and Innovation Facilitation BRIN                                                                                                                                                                                            1
Name: count, Length: 126, dtype: int64

In [63]:
# Optional: Group similar names together
df_funders = VeriXiv_df['funders_flat'].dropna().str.split(';').explode().str.strip()

# # Normalize common variants
# df_funders = df_funders.replace({
#     "Gates Foundation": "Bill and Melinda Gates Foundation"
# })

final_counts = df_funders.value_counts().to_frame()
final_counts.head(10)

                                                    count
funders_flat
Bill and Melinda Gates Foundation                     366
Gates Foundation                                      120
Wellcome Trust                                          9
Biotechnology and Biological Sciences Research ...      8
Children's Investment Fund Foundation                   7
National Institute of Allergy and Infectious Di...      7
European and Developing Countries Clinical Tria...      6
Consortium pour la recherche économique en Afrique      6
Wellcome                                                6
African Economic Research Consortium                    5

# viXra

In [64]:
viXra_df, viXra_summary = get_server_data("viXra")

==================================================
 SERVER ANALYSIS: VIXRA
==================================================
  > Files found:    1
  > Raw records:    25570
  > Cleaned shape:  (25570, 90)
  > Unique DOIs:    2646
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
<NA>              22924
10.5281/zenodo      989
10.13140/rg         989
10.6084/m           225
10.48550/arxiv      136
10.13140/2           36
10.1016/j            23
10.17605/osf         13
10.18147/smn         11
10.1007/s            10
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
vixra.org                     25200
rxiv.org                         75
fs.gallup.unm.edu                67
philpapers.org                   25
gallup.unm.edu                   23
s3-eu-west-1.amazonaws.com       10
deepblue.lib.umich.edu           10
zenodo.org                       10
redshift.vif.com                  9
researchgate.net                  8
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
None        22924
10.13140     1025
10.5281       989
10.6084       225
10.48550      136
10.1016        41
10.1007        15
10.1111        14
10.17605       13
10.18147       11
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    25570
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
None    25570
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    25570
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    25570
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    25570
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    25570
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
preprint    25243
article       266
review         54
book            7
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    25570
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR VIXRA
==================================================

In [65]:
viXra_parent_df, viXra_parent_summary = analyze_parent_data("viXra", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: VIXRA
=================================================================
  > Total Parent Groups:     22,570
  > Total Versions Found:    23,011
  > Unique Parent DOIs:      0
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for viXra:
-----------------------------------
  1 version(s):     22,228 groups
  2 version(s):     287 groups
  3 version(s):     37 groups
  4 version(s):     8 groups
  5 version(s):     3 groups
  6 version(s):     3 groups
  7 version(s):     3 groups
  12 version(s):    1 groups

  Average versions per parent: 1.02

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
viXra                     22382
arXiv                        85
ResearchGate                 57
SSRN                         18
Zenodo                        8
HAL                           4
Open Science Framework        4
Preprints.org                 3
bioRxiv                       3
engrXiv                       1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
<NA>    22570



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
vixra.org                 22319
rxiv.org                     67
fs.gallup.unm.edu            27
philpapers.org               21
deepblue.lib.umich.edu        9
redshift.vif.com              8
citeseerx.ist.psu.edu         8
researchgate.net              7
imechanica.org                7
article.aascit.org            6


=================================================================
 COMPLETED: VIXRA
=================================================================

In [66]:
viXra_df[viXra_df['doi_prefix_first_token']=='10.5281/zenodo']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
1,openalex::W2868542249,viXra,openalex,https://openalex.org/W2868542249,10.5281/zenodo.3843259,https://doi.org/10.5281/zenodo.3843259,https://vixra.org/pdf/1807.0120v1.pdf,https://vixra.org/pdf/1807.0120v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,"Putrescine, Cadaverine, Spermine and Spermidin...",None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2018-07-01,None,2018,openalex.publication_date,None,True,green,None,None,"{""(EPPSI)"": [16], ""(NPM)"": [25], ""(NPME)"": [34...","In the current study, we study Putrescine, Cad...",None,None,Alireza Heidari; Ricardo Gobato,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Cadaverine"", ""id"": ""https:/...","[{""display_name"": ""Advanced biosensing and bio...",96,None,96,None,65,"[""https://openalex.org/W2919873033"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(EPPSI)"": [16], ...",10.5281/zenodo.3843259,10.5281,10.5281,zenodo.3843259,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
6,openalex::W3003001456,viXra,openalex,https://openalex.org/W3003001456,10.5281/zenodo.3871965,https://doi.org/10.5281/zenodo.3871965,https://vixra.org/pdf/2001.0191v1.pdf,https://vixra.org/pdf/2001.0191v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,Pros and Cons of Livermorium Nanoparticles for...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2020-01-11,None,2020,openalex.publication_date,None,True,green,None,None,"{""(emission"": [13], ""(non–emission"": [20], ""3D...",When Livermorium nanoparticles are subjected t...,None,None,Alireza Heidari; Katrina Schmitt; Maria Hender...,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Nanoparticle"", ""id"": ""https...","[{""display_name"": ""Spectroscopy Techniques in ...",31,None,31,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(emission"": [13]...",10.5281/zenodo.3871965,10.5281,10.5281,zenodo.3871965,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
7,openalex::W2127088805,viXra,openalex,https://openalex.org/W2127088805,10.5281/zenodo.23153,https://doi.org/10.5281/zenodo.23153,https://vixra.org/abs/1411.0488,https://vixra.org/abs/1411.0488,10.5281,None,None,None,openalex,None,None,None,None,None,Neutrosophic Soft Relations And Some Properties,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2014-09-13,None,2014,openalex.publication_date,None,True,green,None,None,"{""Finally"": [78], ""In"": [0], ""It"": [21], ""Then...","In this work, we rst de ne a relation on neutr...",None,None,İrfan Deli̇; Said Broumi,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Soft set"", ""id"": ""https://o...","[{""display_name"": ""Fuzzy and Soft Set Theory"",...",77,None,77,None,25,"[""https://openalex.org/W2076245459"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Finally"": [78], ...",10.5281/zenodo.23153,10.5281,10.5281,zenodo.23153,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/abs
8,openalex::W1596962267,viXra,openalex,https://openalex.org/W1596962267,10.5281/zenodo.9659,https://doi.org/10.5281/zenodo.9659,https://vixra.org/pdf/1403.0847v1.pdf,https://vixra.org/pdf/1403.0847v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,Smarandache Algebraic Structures,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2004-07-20,None,2004,openalex.publication_date,None,True,green,None,None,"{""A"": [0], ""Especially"": [14], ""Smarandache"": ...",A few notions are introduced in algebra in ord...,None,None,Raul Padilla,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Algebraic number"", ""id"": ""h...","[{""display_name"": ""Fuzzy and Soft Set Theory"",...",72,None,72,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""A"": [0], ""Especi...",10.5281/zenodo.9659,10.5281,10.5281,zenodo.9659,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
9,openalex::W2575174071,viXra,openalex,https://openalex.org/W2575174071,10.5281/zenodo.3130624,https://doi.org/10.5281/zenodo.3130624,https://vixra.org/pdf/1701.0160v1.pdf,https://vixra.org/pdf/1701.0160v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,Selection of lead-zinc flotation circuit desig...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2019-05-22,None,2019,openalex.publication_date,None,True,green,None,None,"{""An"": [57], ""Collective"": [54], ""Collective-S...","In this paper, selection of adequate circuit d...",None,None,Edmundas Kazimieras Zavadskas; Romualdas Baušy...,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Selection (genetic algorith...","[{""display_name"": ""Water Quality Monitoring an...",47,None,47,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""An"": [57], ""Coll...",10.5281/zenodo.3130624,10.5281,10.5281,zenodo.3130624,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24954,openalex::W864222750,viXra,openalex,https://openalex.org/W864222750,10.5281/zenodo.9227,https://doi.org/10.5281/zenodo.9227,https://vixra.org/pdf/1004.0095v1.pdf,https://vixra.org/pdf/1004.0095v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,Notion Of Neutrosophic Risk And Financial Mark...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2002-05-01,None,2002,openalex.publication_date,None,True,green,None,None,"{""Presenting"": [0], ""an"": [1], ""application"": ...",Presenting an application of the neutrosophic ...,None,None,Bhattacharya Sukanto,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Financial market"", ""id"": ""h...","[{""display_name"": ""Complex Systems and Time Se...",0,None,0,None,17,"[""https://openalex.org/W2017680376"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Presenting"": [0]...",10.5281/zenodo.9227,10.5281,10.5281,zenodo.9227,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
24971,openalex::W8697984,viXra,openalex,https://openalex.org/W8697984,10.5281/zenodo.9324,https://doi.org/10.5281/zenodo.9324,https://vixra.org/pdf/1403.0801v1.pdf,https://vixra.org/pdf/1403.0801v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,The Monotony Of Smarandache Functions Of First...,None,None,None,en,preprint,None,preprint,False,True,2016-06-24T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2003-05-18,None,2003,openalex.publication_date,None,True,green,None,None,"{""Smarandache"": [0], ""are"": [4], ""defined"": [5...",Smarandache functions offirst kind are defined...,None,None,Ion Balacenoiu,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Mathematics"", ""id"": ""https:...","[{""display_name"": ""Advanced Mathematical Theor...",0,None,0,None,1,"[""https://openalex.org/W2290220327""]",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Smarandache"": [0...",10.5281/zenodo.9324,10.5281,10.5281,zenodo.9324,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
25158,openalex::W923647939,viXra,openalex,https://openalex.org/W923647939,10.5281/zenodo.8785,https://doi.org/10.5281/zenodo.8785,https://vixra.org/pdf/1109.0029v1.pdf,https://vixra.org/pdf/1109.0029v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,"Research On Some Smarandache Problems, Vol. 7",None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2011-04-30,None,2011,openalex.publication_date,None,True,green,None,None,"{""Chinese"": [14], ""Smarandache"": [10, 29, 33],...",This book includes part of the research result...,None,None,Huaning Liu; Jing Gao,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Zhàng"", ""id"": ""https://open...","[{""display_name"": ""Advanced Mathematical Theor...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Chinese"": [14], ...",10.5281/zenodo.8785,10.5281,10.5281,zenodo.8785,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
25203,openalex::W93563694,viXra,openalex,https://openalex.org/W93563694,10.5281/zenodo.9282,https://doi.org/10.5281/zenodo.9282,https://vixra.org/pdf/1403.0694v1.pdf,https://vixra.org/pdf/1403.0694v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,Examples Of Smarandache Magic Squares,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1997-03-09,None,1997,openalex.publication_date,None,True,green,None,None,"{""-"": [6], ""2"": [22], ""A"": [30], ""As"": [0], ""I...",As a generalization of the XVI-th - XVII-th ce...,None,None,Michael R. Mudge,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Magic square"", ""id"": ""https...","[{""display_name"": ""Advanced Mathematical Theor...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""-"": [6], ""2"": [2...",10.5281/zenodo.9282,10.5281,10.5281,zenodo.9282,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf
25367,openalex::W967902929,viXra,openalex,https://openalex.org/W967902929,10.5281/zenodo.57706,https://doi.org/10.5281/zenodo.57706,https://vixra.org/pdf/1404.0220v1.pdf,https://vixra.org/pdf/1404.0220v1.pdf,10.5281,None,None,None,openalex,None,None,None,None,None,K-Divisibility And K-Strong Divisibility Seque...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,1997-07-12,None,1997,openalex.publication_date,None,True,green,None,None,"{""Of"": [0], ""S("": [14], ""Smarandache"": [12], ""...","Of course, it is easy to show that the results...",None,None,Florentín Smarandache,None,None,"[{""affiliations"": [{""institution_ids"": [], ""ra...",None,None,[],None,None,None,"[{""display_name"": ""Divisibility rule"", ""id"": ""...","[{""display_name"": ""Advanced Mathematical Theor...",0,None,0,None,2,"[""https://openalex.org/W2316969487"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Of"": [0], ""S("": ...",10.5281/zenodo.57706,10.5281,10.5281,zenodo.57706,10.5281/zenodo,10.5281/zenodo,vixra.org,vixra.org/pdf

In [67]:
viXra_df[viXra_df['doi_prefix_first_token']=='10.13140/rg']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
3,openalex::W2842105084,viXra,openalex,https://openalex.org/W2842105084,10.13140/rg.2.2.22315.75047,https://doi.org/10.13140/rg.2.2.22315.75047,https://vixra.org/pdf/1807.0123v1.pdf,https://vixra.org/pdf/1807.0123v1.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,Using the Quantum Chemistry for Genesis of a N...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2018-01-01,None,2018,openalex.publication_date,None,True,gold,None,None,"{""(3df,"": [238], ""(Hartree-Fock)"": [108], ""3pd...",Preliminary bibliographic studies did not reve...,None,None,Ricardo Gobato; Alireza Heidari; Abhijit Mitra,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Basis set"", ""id"": ""https://...","[{""display_name"": ""History and advancements in...",70,None,70,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(3df,"": [238], ""...",10.13140/rg.2.2.22315.75047,10.13140,10.13140,rg.2.2.22315.75047,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
5,openalex::W3093092331,viXra,openalex,https://openalex.org/W3093092331,10.13140/rg.2.2.27971.84008,https://doi.org/10.13140/rg.2.2.27971.84008,https://vixra.org/pdf/2010.0063v1.pdf,https://vixra.org/pdf/2010.0063v1.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,Vortex Cotes's spiral in an extratropical cycl...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2020-01-01,None,2020,openalex.publication_date,None,True,gold,None,None,"{""(159.99"": [150], ""(31.998"": [159], ""-30◦C,"":...",Ae extratropical cyclone” is an at- mospheric ...,None,None,Ricardo Gobato; Alireza Heidari; Abhijit Mitra...,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Extratropical cyclone"", ""id...","[{""display_name"": ""Environmental and biologica...",36,None,36,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(159.99"": [150],...",10.13140/rg.2.2.27971.84008,10.13140,10.13140,rg.2.2.27971.84008,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
21,openalex::W2900877152,viXra,openalex,https://openalex.org/W2900877152,10.13140/rg.2.2.22927.94885,https://doi.org/10.13140/rg.2.2.22927.94885,https://vixra.org/pdf/1811.0283v1.pdf,https://vixra.org/pdf/1811.0283v1.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,To divide by zero is to multiply by zero,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2019-01-01,None,2019,openalex.publication_date,None,True,gold,None,None,None,None,None,None,Hiroshi Okumura,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Zero (linguistics)"", ""id"": ...","[{""display_name"": ""Mathematical and Theoretica...",16,None,16,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": null, ""apc_list"": ...",10.13140/rg.2.2.22927.94885,10.13140,10.13140,rg.2.2.22927.94885,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
23,openalex::W254493469,viXra,openalex,https://openalex.org/W254493469,10.13140/rg.2.2.27523.66087,https://doi.org/10.13140/rg.2.2.27523.66087,https://vixra.org/pdf/1501.0013v1.pdf,https://vixra.org/pdf/1501.0013v1.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,Criticality and dark matter,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2014-01-01,None,2014,openalex.publication_date,None,True,gold,None,None,"{""I"": [42], ""Kahler"": [14], ""Quantum"": [0], ""S...",Quantum criticality is one of the corner stone...,None,None,Matti Pitkänen,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Criticality"", ""id"": ""https:...","[{""display_name"": ""Quantum Mechanics and Appli...",14,None,14,None,43,"[""https://openalex.org/W105991558"", ""https://o...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""I"": [42], ""Kahle...",10.13140/rg.2.2.27523.66087,10.13140,10.13140,rg.2.2.27523.66087,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
27,openalex::W2988568021,viXra,openalex,https://openalex.org/W2988568021,10.13140/rg.2.2.14287.43683/2,https://doi.org/10.13140/rg.2.2.14287.43683/2,https://vixra.org/pdf/1911.0064v2.pdf,https://vixra.org/pdf/1911.0064v2.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,"Space, and the Redshift Effect",None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2019-01-01,None,2019,openalex.publication_date,None,True,gold,None,None,"{""11"": [19], ""12"": [22], ""Following"": [0], ""Fo...",Following on from the previous series of paper...,None,None,Stephen H. Jarvis,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Cosmology"", ""id"": ""https://...","[{""display_name"": ""Space Science and Extraterr...",11,None,11,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""11"": [19], ""12"":...",10.13140/rg.2.2.14287.43683/2,10.13140,10.13140,rg.2.2.14287.43683/2,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25380,openalex::W969709865,viXra,openalex,https://openalex.org/W969709865,10.13140/rg.2.1.3568.5848,https://doi.org/10.13140/rg.2.1.3568.5848,https://www.vixra.org/abs/1503.0234,https://www.vixra.org/abs/1503.0234,10.13140,None,None,None,openalex,None,None,None,None,None,Three conjectures on probably infinite sequenc...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2015-01-01,None,2015,openalex.publication_date,None,True,gold,None,None,"{""(1)"": [8], ""(2)"": [41], ""(3)"": [73], ""2,"": [...","In this paper I present three conjectures, i.e...",None,None,Marius Coman,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Concatenation (mathematics)...","[{""display_name"": ""Advanced Mathematical Theor...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(1)"": [8], ""(2)""...",10.13140/rg.2.1.3568.5848,10.13140,10.13140,rg.2.1.3568.5848,10.13140/rg,10.13140/rg,vixra.org,vixra.org/abs
25404,openalex::W971881409,viXra,openalex,https://openalex.org/W971881409,10.13140/rg.2.1.4678.9201,https://doi.org/10.13140/rg.2.1.4678.9201,https://vixra.org/pdf/1309.0003v4.pdf,https://vixra.org/pdf/1309.0003v4.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,Linkage of Classical (3 Dimensional) and QM ge...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2015-01-01,None,2015,openalex.publication_date,None,True,gold,None,None,"{""(CM)"": [9, 25], ""(QM)"": [5], ""(Quantum"": [94...",Hopf mapping from 2 dimensions (QM) to 3 dimen...,None,None,Andrew Beckwith,University of Houston,US,"[{""affiliations"": [{""institution_ids"": [""https...",None,None,[],None,None,None,"[{""display_name"": ""Formalism (music)"", ""id"": ""...","[{""display_name"": ""Cosmology and Gravitation T...",0,None,0,None,10,"[""https://openalex.org/W2010410320"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(CM)"": [9, 25], ...",10.13140/rg.2.1.4678.9201,10.13140,10.13140,rg.2.1.4678.9201,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
25465,openalex::W983039221,viXra,openalex,https://openalex.org/W983039221,10.13140/rg.2.2.29266.79041,https://doi.org/10.13140/rg.2.2.29266.79041,http://www.vixra.org/pdf/1503.0004v1.pdf,http://www.vixra.org/pdf/1503.0004v1.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,Ionization chamber noise fluctuations during l...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2020-01-01,None,2020,openalex.publication_date,None,True,gold,None,None,"{""(3"": [95], ""15.04.2014"": [17], ""20"": [112], ...",Dynamics of intervals between moments of an io...,None,None,A. D. Skorbun; M. V. Efetov; G. I. Odinokin; O...,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Eclipse"", ""id"": ""https://op...","[{""display_name"": ""Nuclear Physics and Applica...",0,None,0,None,1,"[""https://openalex.org/W2540244290""]",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(3"": [95], ""15.0...",10.13140/rg.2.2.29266.79041,10.13140,10.13140,rg.2.2.29266.79041,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
25523,openalex::W99304111,viXra,openalex,https://openalex.org/W99304111,10.13140/rg.2.1.1539.6003,https://doi.org/10.13140/rg.2.1.1539.6003,https://vixra.org/pdf/1304.0017v1.pdf,https://vixra.org/pdf/1304.0017v1.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,Four conjectures regarding Fermat pseudoprimes...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2015-01-01,None,2015,openalex.publication_date,None,True,gold,None,None,"{""+"": [41, 52], ""1)],"": [46], ""1],"": [38, 42],...",There are already known some relations between...,None,None,Marius Coman,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Fermat's Last Theorem"", ""id...","[{""display_name"": ""Analytic Number Theory Rese...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""+"": [41, 52], ""1...",10.13140/rg.2.1.1539.6003,10.13140,10.13140,rg.2.1.1539.6003,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf
25552,openalex::W998010466,viXra,openalex,https://openalex.org/W998010466,10.13140/rg.2.2.36331.69924,https://doi.org/10.13140/rg.2.2.36331.69924,https://vixra.org/pdf/1409.0185v1.pdf,https://vixra.org/pdf/1409.0185v1.pdf,10.13140,None,None,None,openalex,None,None,None,None,None,"TGD view about homeopathy, water memory, and e...",None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2014-01-01,None,2014,openalex.publication_date,None,True,gold,None,None,"{""\r\n\r\nIn"": [94], ""(later"": [201, 214], ""2-...",This article represents a brief sketch of TGD ...,None,None,Matti Pitkänen,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Theoretical physics"", ""id"":...","[{""display_name"": ""Biofield Effects and Biophy...",0,None,0,None,8,"[""https://openalex.org/W2628962296"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""\r\n\r\nIn"": [94...",10.13140/rg.2.2.36331.69924,10.13140,10.13140,rg.2.2.36331.69924,10.13140/rg,10.13140/rg,vixra.org,vixra.org/pdf

In [68]:
viXra_df[viXra_df['doi_prefix_first_token']=='10.6084/m']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
13,openalex::W1508236978,viXra,openalex,https://openalex.org/W1508236978,10.6084/m9.figshare.6205535,https://doi.org/10.6084/m9.figshare.6205535,https://vixra.org/pdf/1508.0285v1.pdf,https://vixra.org/pdf/1508.0285v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,"Neutrosophic Sets and Systems, 20/2018",None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2018-01-01,None,2018,openalex.publication_date,None,True,green,None,None,"{""1995"": [25], ""Sets"": [1], ""Systems”"": [3], ""...",“Neutrosophic Sets and Systems” has been creat...,None,None,Florentín Smarandache; Mumtaz Ali,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Indeterminacy (philosophy)""...","[{""display_name"": ""Advanced Mathematical Theor...",25,None,25,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""1995"": [25], ""Se...",10.6084/m9.figshare.6205535,10.6084,10.6084,m9.figshare.6205535,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
71,openalex::W2801841746,viXra,openalex,https://openalex.org/W2801841746,10.6084/m9.figshare.6205448,https://doi.org/10.6084/m9.figshare.6205448,https://vixra.org/pdf/1804.0434v1.pdf,https://vixra.org/pdf/1804.0434v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,NC-VIKOR Based MAGDM Strategy under Neutrosoph...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2018-01-01,None,2018,openalex.publication_date,None,True,green,None,None,"{""Neutrosophic"": [0], ""and"": [8], ""consists"": ...",Neutrosophic cubic set consists of interval ne...,None,None,Surapati Pramanik; Shyamal Dalapati; Shariful ...,Indian Institute of Engineering Science and Te...,IN,"[{""affiliations"": [{""institution_ids"": [], ""ra...",None,None,[],None,None,None,"[{""display_name"": ""Set (abstract data type)"", ...","[{""display_name"": ""Multi-Criteria Decision Mak...",7,None,7,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Neutrosophic"": [...",10.6084/m9.figshare.6205448,10.6084,10.6084,m9.figshare.6205448,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
89,openalex::W2953040890,viXra,openalex,https://openalex.org/W2953040890,10.6084/m9.figshare.5028353,https://doi.org/10.6084/m9.figshare.5028353,https://vixra.org/pdf/1609.0062v1.pdf,https://vixra.org/pdf/1609.0062v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Optimization of Supercritical Fluid Consecutiv...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2017-01-01,None,2017,openalex.publication_date,None,True,green,None,None,"{""(2"": [21], ""1st"": [31], ""2nd"": [41], ""A"": [9...","In this study, supercritical fluid extraction ...",None,None,Oier Aizpurua‐Olaizola; Markel Ormazabal; Asie...,University of the Basque Country,ES,"[{""affiliations"": [{""institution_ids"": [""https...",None,None,[],None,None,None,"[{""display_name"": ""Polyphenol"", ""id"": ""https:/...","[{""display_name"": ""Analytical Chemistry and Ch...",14,None,14,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(2"": [21], ""1st""...",10.6084/m9.figshare.5028353,10.6084,10.6084,m9.figshare.5028353,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
112,openalex::W2611341713,viXra,openalex,https://openalex.org/W2611341713,10.6084/m9.figshare.7048325.v1,https://doi.org/10.6084/m9.figshare.7048325.v1,https://vixra.org/pdf/1705.0076v1.pdf,https://vixra.org/pdf/1705.0076v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Neutrosophic Integer Programming Problems,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2018-01-01,None,2018,openalex.publication_date,None,True,green,None,None,"{""In"": [0], ""The"": [20], ""a"": [16], ""acceptanc...","In this chapter, we introduce the integer prog...",None,None,Mohamed Abdel-Baset; Mai Mohamed; Abdel-Nasser...,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Indeterminacy (philosophy)""...","[{""display_name"": ""Optimization and Mathematic...",5,None,5,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""In"": [0], ""The"":...",10.6084/m9.figshare.7048325.v1,10.6084,10.6084,m9.figshare.7048325.v1,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
122,openalex::W2953393170,viXra,openalex,https://openalex.org/W2953393170,10.6084/m9.figshare.9759812.v1,https://doi.org/10.6084/m9.figshare.9759812.v1,https://vixra.org/pdf/1907.0026v1.pdf,https://vixra.org/pdf/1907.0026v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Is There Glue in Cuprate Superconductors? The ...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2019-01-01,None,2019,openalex.publication_date,None,True,green,None,None,"{""100"": [96], ""2007:"": [8], ""250"": [91], ""360""...",P. W. Anderson raised an important question in...,None,None,Tiege Zhou,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Cuprate"", ""id"": ""https://op...","[{""display_name"": ""Physics of Superconductivit...",4,None,4,None,29,"[""https://openalex.org/W2884784531"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""100"": [96], ""200...",10.6084/m9.figshare.9759812.v1,10.6084,10.6084,m9.figshare.9759812.v1,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24354,openalex::W62916722,viXra,openalex,https://openalex.org/W62916722,10.6084/m9.figshare.6198839.v1,https://doi.org/10.6084/m9.figshare.6198839.v1,https://vixra.org/pdf/1309.0145v6.pdf,https://vixra.org/pdf/1309.0145v6.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Two Hundred Conjectures and One Hundred and Fi...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-10-10T17:16:08.811792,None,None,2013-09-01,None,2013,openalex.publication_date,None,True,green,None,None,"{""\""little\"""": [66], ""&lt;br&gt;"": [105], ""(56...",Prime numbers have always fascinated mankind. ...,None,None,Marius Coman,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Fermat's Last Theorem"", ""id...","[{""display_name"": ""Advanced Mathematical Theor...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""\""little\"""": [66...",10.6084/m9.figshare.6198839.v1,10.6084,10.6084,m9.figshare.6198839.v1,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
24638,openalex::W751895103,viXra,openalex,https://openalex.org/W751895103,10.6084/m9.figshare.1378992,https://doi.org/10.6084/m9.figshare.1378992,https://vixra.org/pdf/1507.0057v1.pdf,https://vixra.org/pdf/1507.0057v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Comparative Study Among Different Dyeing Metho...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2015-01-01,None,2015,openalex.publication_date,None,True,green,None,None,"{""Among"": [2], ""Comparative"": [0], ""Different""...",Comparative Study Among Different Dyeing Metho...,None,None,Elias Khalil,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Dyeing"", ""id"": ""https://ope...","[{""display_name"": ""Dyeing and Modifying Textil...",0,None,0,None,3,"[""https://openalex.org/W1993520727"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Among"": [2], ""Co...",10.6084/m9.figshare.1378992,10.6084,10.6084,m9.figshare.1378992,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
24696,openalex::W77188360,viXra,openalex,https://openalex.org/W77188360,10.6084/m9.figshare.3486131.v1,https://doi.org/10.6084/m9.figshare.3486131.v1,https://vixra.org/pdf/1404.0231v1.pdf,https://vixra.org/pdf/1404.0231v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Integer Number Solutions of Linear Systems,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-10-10T17:16:08.811792,None,None,2016-01-01,None,2016,openalex.publication_date,None,False,closed,None,None,None,None,None,None,Florentín Smarandache,None,None,"[{""affiliations"": [{""institution_ids"": [], ""ra...",None,None,[],None,None,None,"[{""display_name"": ""Integer (computer science)""...",[],0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": null, ""apc_list"": ...",10.6084/m9.figshare.3486131.v1,10.6084,10.6084,m9.figshare.3486131.v1,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
25190,openalex::W93338619,viXra,openalex,https://openalex.org/W93338619,10.6084/m9.figshare.729275,https://doi.org/10.6084/m9.figshare.729275,https://vixra.org/pdf/1306.0205v1.pdf,https://vixra.org/pdf/1306.0205v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Relation Between Medieval Renaissance and Toda...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2013-01-01,None,2013,openalex.publication_date,None,True,gold,None,None,"{""Intellectual"": [86], ""Less"": [30], ""Nazism"":...",Time has shown us how zero control by a handfu...,None,None,Subhajit Ganguly,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""The Renaissance"", ""id"": ""ht...","[{""display_name"": ""Medieval Philosophy and The...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Intellectual"": [...",10.6084/m9.figshare.729275,10.6084,10.6084,m9.figshare.729275,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf
25415,openalex::W974091649,viXra,openalex,https://openalex.org/W974091649,10.6084/m9.figshare.6199046.v1,https://doi.org/10.6084/m9.figshare.6199046.v1,https://vixra.org/pdf/1010.0060v1.pdf,https://vixra.org/pdf/1010.0060v1.pdf,10.6084,None,None,None,openalex,None,None,None,None,None,Let’s Flying by Wing,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-10-10T17:16:08.811792,None,None,2018-04-29,None,2018,openalex.publication_date,None,True,green,None,None,"{""By"": [28], ""Smarandache’s"": [88], ""This"": [0...","This book is for students and young scholar, w...",None,None,Linfan Mao,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Mathematics education"", ""id...","[{""display_name"": ""Advanced Mathematical Theor...",0,None,0,None,19,"[""https://openalex.org/W2121152126"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""By"": [28], ""Smar...",10.6084/m9.figshare.6199046.v1,10.6084,10.6084,m9.figshare.6199046.v1,10.6084/m,10.6084/m,vixra.org,vixra.org/pdf

In [69]:
viXra_df[viXra_df['doi_prefix_first_token']=='10.48550/arxiv']

,record_id,server_name,backend,source_work_id,doi,doi_url,landing_page_url,url_best,prefix,member_id,client_id,provider_id,source_registry,publisher,container_title,institution_name,group_title,issn,title,original_title,short_title,subtitle,language,type_backend_raw,subtype_backend_raw,type_canonical,is_paratext,is_preprint_candidate,date_created,date_posted,date_deposited,date_indexed,date_updated,date_issued,date_registered,date_published,date_published_online,publication_year,date_published_source,date_posted_source,is_oa,oa_status,license,license_url_best,abstract_raw,abstract_text,links_json_best,fulltext_pdf_url,authors_flat,institutions_flat,countries_flat,authors_json,contributors_json,editors_json,funders_json,funders_flat,funders_count,subjects_json,concepts_json,topics_json,cited_by_count,cited_by_count_datacite,cited_by_count_openalex,is_referenced_by_count_crossref,reference_count,references_json,relations_json,has_preprint,is_preprint_of,has_published_version,published_version_ids_json,is_version_of,version_of_ids_json,version_label,has_review,update_to_json,parent_doi,update_policy,rule_tokens,rule_row_id,raw_relationships_json,raw_json,doi_lc,prefix_lc,doi_prefix_from_text,doi_suffix,doi_prefix_first_token,doi_prefix_bucket_2d,primary_domain,primary_domain_extend
20,openalex::W2951522206,viXra,openalex,https://openalex.org/W2951522206,10.48550/arxiv.1511.03095,https://doi.org/10.48550/arxiv.1511.03095,https://vixra.org/pdf/1511.0232v1.pdf,https://vixra.org/pdf/1511.0232v1.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,Generalized Multiple Importance Sampling,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2015-11-10,None,2015,openalex.publication_date,None,True,green,None,None,"{""(MIS)"": [61], ""All"": [126], ""Finally,"": [143...",Importance Sampling methods are broadly used t...,None,None,Vı́ctor Elvira; Luca Martino; David Luengo; Mó...,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Weighting"", ""id"": ""https://...","[{""display_name"": ""Advanced Statistical Method...",17,None,17,None,21,"[""https://openalex.org/W3098203061"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(MIS)"": [61], ""A...",10.48550/arxiv.1511.03095,10.48550,10.48550,arxiv.1511.03095,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf
29,openalex::W2951328659,viXra,openalex,https://openalex.org/W2951328659,10.48550/arxiv.1609.07731,https://doi.org/10.48550/arxiv.1609.07731,https://vixra.org/pdf/1512.0420v3.pdf,https://vixra.org/pdf/1512.0420v3.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,Cooperative Parallel Particle Filters for onli...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2016-09-25,None,2016,openalex.publication_date,None,True,green,None,None,"{""Bayesian"": [12], ""Carlo"": [5], ""For"": [52], ...",We design a sequential Monte Carlo scheme for ...,None,None,Luca Martino; Jesse Read; Vı́ctor Elvira; Fran...,Universidade de São Paulo; Aalto University; C...,BR; FI; FR; ES,"[{""affiliations"": [{""institution_ids"": [""https...",None,None,[],None,None,None,"[{""display_name"": ""Particle filter"", ""id"": ""ht...","[{""display_name"": ""Target Tracking and Data Fu...",9,None,9,None,35,"[""https://openalex.org/W2160337655"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Bayesian"": [12],...",10.48550/arxiv.1609.07731,10.48550,10.48550,arxiv.1609.07731,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf
141,openalex::W2950625612,viXra,openalex,https://openalex.org/W2950625612,10.48550/arxiv.math/0404520,https://doi.org/10.48550/arxiv.math/0404520,https://vixra.org/pdf/1109.0041v1.pdf,https://vixra.org/pdf/1109.0041v1.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,A Geometric Interpretation of the Neutrosophic...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2004-04-29,None,2004,openalex.publication_date,None,True,green,None,None,"{""(IFS),"": [9], ""(NS)."": [19], ""Also,"": [24], ...",In this paper we generalize the intuitionistic...,None,None,Florentín Smarandache,None,None,"[{""affiliations"": [{""institution_ids"": [], ""ra...",None,None,[],None,None,None,"[{""display_name"": ""Interpretation (philosophy)...","[{""display_name"": ""Fuzzy and Soft Set Theory"",...",8,None,8,None,8,"[""https://openalex.org/W2058080862"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(IFS),"": [9], ""(...",10.48550/arxiv.math/0404520,10.48550,10.48550,arxiv.math/0404520,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf
153,openalex::W2952155628,viXra,openalex,https://openalex.org/W2952155628,10.48550/arxiv.1302.3901,https://doi.org/10.48550/arxiv.1302.3901,https://vixra.org/pdf/1302.0055v2.pdf,https://vixra.org/pdf/1302.0055v2.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,Enhanced secure key exchange systems based on ...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2013-02-15,None,2013,openalex.publication_date,None,True,green,None,None,"{""\""intelligent\"""": [49], ""\""intelligent-keyed...",We introduce seven new versions of the Kirchho...,None,None,László B. Kish,Texas A&M University,US,"[{""affiliations"": [{""institution_ids"": [""https...",None,None,[],None,None,None,"[{""display_name"": ""Key exchange"", ""id"": ""https...","[{""display_name"": ""Advanced Statistical Modeli...",6,None,6,None,22,"[""https://openalex.org/W2127744385"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""\""intelligent\""""...",10.48550/arxiv.1302.3901,10.48550,10.48550,arxiv.1302.3901,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf
175,openalex::W2951800506,viXra,openalex,https://openalex.org/W2951800506,10.48550/arxiv.1508.02984,https://doi.org/10.48550/arxiv.1508.02984,https://vixra.org/pdf/1508.0079v1.pdf,https://vixra.org/pdf/1508.0079v1.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,Cable Capacitance Attack against the KLJN Secu...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2015-08-11,None,2015,openalex.publication_date,None,True,green,None,None,"{""(KLJN)"": [5], ""(cable)"": [86], ""(capacitance...",The security of the Kirchhoff-law-Johnson-(lik...,None,None,Hsien-Pu Chen; Elias Gonzalez; Yessica Sáez; L...,Texas A&M University,US,"[{""affiliations"": [{""institution_ids"": [""https...",None,None,[],None,None,None,"[{""display_name"": ""Capacitance"", ""id"": ""https:...","[{""display_name"": ""Advanced Statistical Modeli...",4,None,4,None,56,"[""https://openalex.org/W2143255200"", ""https://...",None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(KLJN)"": [5], ""(...",10.48550/arxiv.1508.02984,10.48550,10.48550,arxiv.1508.02984,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22228,openalex::W3156946587,viXra,openalex,https://openalex.org/W3156946587,10.48550/arxiv.2103.10864,https://doi.org/10.48550/arxiv.2103.10864,https://vixra.org/abs/2104.0075,https://vixra.org/abs/2104.0075,10.48550,None,None,None,openalex,None,None,None,None,None,Thermodynamic and vortic fine structures of re...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2021-02-23,None,2021,openalex.publication_date,None,True,green,None,None,"{""$\\mathbb{E}^d$"": [78], ""$d$-dimensional"": [...",A two-component-two-dimensional coupled with o...,None,None,Jian-Zhou Zhu,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Schur decomposition"", ""id"":...","[{""display_name"": ""Fluid Dynamics and Turbulen...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""$\\mathbb{E}^d$""...",10.48550/arxiv.2103.10864,10.48550,10.48550,arxiv.2103.10864,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/abs
22609,openalex::W3184228777,viXra,openalex,https://openalex.org/W3184228777,10.48550/arxiv.2107.07418,https://doi.org/10.48550/arxiv.2107.07418,https://vixra.org/pdf/2107.0111v1.pdf,https://vixra.org/pdf/2107.0111v1.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,The theorem on the magnetic field of rotating ...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2021-07-11,None,2021,openalex.publication_date,None,True,green,None,None,"{""."": [85, 121], ""Biot-Savart"": [10], ""In"": [8...",The method of retarded potentials is used to d...,None,None,Sergey G. Fedosın,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Physics"", ""id"": ""https://op...","[{""display_name"": ""Geomagnetism and Paleomagne...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""."": [85, 121], ""...",10.48550/arxiv.2107.07418,10.48550,10.48550,arxiv.2107.07418,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf
23079,openalex::W3208924596,viXra,openalex,https://openalex.org/W3208924596,10.48550/arxiv.2110.11230,https://doi.org/10.48550/arxiv.2110.11230,https://vixra.org/pdf/2110.0142v1.pdf,https://vixra.org/pdf/2110.0142v1.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,"Logic, Philosophy and Physics: a critical comm...",None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2021-09-16,None,2021,openalex.publication_date,None,True,green,None,None,"{""Cauchy's"": [190], ""Heisenberg"": [186], ""Howe...",I provide a critical commentary regarding the ...,None,None,Abhishek Majhi,Indian Statistical Institute,IN,"[{""affiliations"": [{""institution_ids"": [""https...",None,None,[],None,None,None,"[{""display_name"": ""Physicist"", ""id"": ""https://...","[{""display_name"": ""Philosophy and History of S...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""Cauchy's"": [190]...",10.48550/arxiv.2110.11230,10.48550,10.48550,arxiv.2110.11230,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf
23114,openalex::W3210643645,viXra,openalex,https://openalex.org/W3210643645,10.48550/arxiv.2110.03514,https://doi.org/10.48550/arxiv.2110.03514,https://vixra.org/abs/2110.0143,https://vixra.org/abs/2110.0143,10.48550,None,None,None,openalex,None,None,None,None,None,A logico-linguistic inquiry into the foundatio...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2021-09-16,None,2021,openalex.publication_date,None,True,green,None,None,"{""$[L],"": [60], ""$q$"": [82], ""(involving"": [15...","Physical dimensions are {\it not numbers}, but...",None,None,Abhishek Majhi,None,None,"[{""affiliations"": [], ""author"": {""display_name...",None,None,[],None,None,None,"[{""display_name"": ""Fallacy"", ""id"": ""https://op...","[{""display_name"": ""Philosophy and History of S...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""$[L],"": [60], ""$...",10.48550/arxiv.2110.03514,10.48550,10.48550,arxiv.2110.03514,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/abs
23221,openalex::W3216756055,viXra,openalex,https://openalex.org/W3216756055,10.48550/arxiv.2109.13737,https://doi.org/10.48550/arxiv.2109.13737,https://vixra.org/pdf/2111.0169v1.pdf,https://vixra.org/pdf/2111.0169v1.pdf,10.48550,None,None,None,openalex,None,None,None,None,None,Evolving Evolutionary Algorithms using Multi E...,None,None,None,en,preprint,None,preprint,False,True,2025-10-10T00:00:00,None,None,None,2025-11-06T06:51:31.235846,None,None,2021-08-22,None,2021,openalex.publication_date,None,True,green,None,None,"{""(EA)"": [23], ""(MEP)"": [56], ""(i.e."": [5], ""A...",Finding the optimal parameter setting (i.e. th...,None,None,Mihai Oltean; Crina Groşan,Babeș-Bolyai University,RO,"[{""affiliations"": [{""institution_ids"": [""https...",None,None,[],None,None,None,"[{""display_name"": ""Evolutionary algorithm"", ""i...","[{""display_name"": ""Evolutionary Algorithms and...",0,None,0,None,0,[],None,None,None,None,None,None,None,None,None,None,None,None,source_id,10,None,"{""abstract_inverted_index"": {""(EA)"": [23], ""(M...",10.48550/arxiv.2109.13737,10.48550,10.48550,arxiv.2109.13737,10.48550/arxiv,10.48550/arxiv,vixra.org,vixra.org/pdf

# Wellcome Open Research

In [70]:
Wellcome_df, Wellcome_summary = get_server_data("Wellcome_Open_Research")

==================================================
 SERVER ANALYSIS: WELLCOME_OPEN_RESEARCH
==================================================
  > Files found:    1
  > Raw records:    4727
  > Cleaned shape:  (4727, 90)
  > Unique DOIs:    4727
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.12688/wellcomeopenres    4727
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
wellcomeopenresearch.org    4727
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.12688    4727
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
2560    4727
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
F1000 Research Ltd    4727
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
Wellcome Open Research    4727
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    4727
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    4727
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
2398-502X    4727
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
journal-article    4727
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
None    4727
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR WELLCOME_OPEN_RESEARCH
==================================================

In [71]:
Wellcome_parent_df, Wellcome_parent_summary = analyze_parent_data("Wellcome Open Research", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: WELLCOME OPEN RESEARCH
=================================================================
  > Total Parent Groups:     3,276
  > Total Versions Found:    4,480
  > Unique Parent DOIs:      3,276
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Wellcome Open Research:
-----------------------------------
  1 version(s):     2,264 groups
  2 version(s):     858 groups
  3 version(s):     122 groups
  4 version(s):     27 groups
  5 version(s):     4 groups
  6 version(s):     1 groups

  Average versions per parent: 1.37

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Wellcome Open Research    3274
Authorea Inc.                1
medRxiv                      1

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.12688/wellcomeopenres    3276



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
wellcomeopenresearch.org    3276


=================================================================
 COMPLETED: WELLCOME OPEN RESEARCH
=================================================================

# Zenodo

In [72]:
Zenodo_df, Zenodo_summary = get_server_data("Zenodo")

==================================================
 SERVER ANALYSIS: ZENODO
==================================================
  > Files found:    1
  > Raw records:    166786
  > Cleaned shape:  (166786, 90)
  > Unique DOIs:    166786
--------------------------------------------------

TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
------------------------------
doi_prefix_first_token
10.5281/zenodo    166786
Name: count, dtype: int64



TOP VALUES FOR: PRIMARY_DOMAIN
------------------------------
primary_domain
zenodo.org    166786
Name: count, dtype: int64



TOP VALUES FOR: PREFIX
------------------------------
prefix
10.5281    166786
Name: count, dtype: int64



TOP VALUES FOR: MEMBER_ID
------------------------------
member_id
None    166786
Name: count, dtype: int64



TOP VALUES FOR: PUBLISHER
------------------------------
publisher
Zenodo                                                                            163441
The Five Principles of Organized Complexity.                                         385
Landon Puritz                                                                        126
C Valdepenas                                                                         102
Інститут педагогічної освіти і освіти дорослих імені Івана Зязюна НАПН України        79
Langaa RPCIG                                                                          68
QNFO                                                                                  62
Zeksel Sergey Borisovich                                                              55
Ricardo Miguel Machado Fernandes                                                      54
Self-published                                                                        52
Name: count, dtype: int64



TOP VALUES FOR: CONTAINER_TITLE
------------------------------
container_title
None    166786
Name: count, dtype: int64



TOP VALUES FOR: INSTITUTION_NAME
------------------------------
institution_name
None    166786
Name: count, dtype: int64



TOP VALUES FOR: GROUP_TITLE
------------------------------
group_title
None    166786
Name: count, dtype: int64



TOP VALUES FOR: ISSN
------------------------------
issn
None    166786
Name: count, dtype: int64



TOP VALUES FOR: TYPE_BACKEND_RAW
------------------------------
type_backend_raw
Preprint    159058
Text          7728
Name: count, dtype: int64



TOP VALUES FOR: SUBTYPE_BACKEND_RAW
------------------------------
subtype_backend_raw
            149959
None          9099
Preprint      7728
Name: count, dtype: int64


==================================================
 END OF SUMMARY FOR ZENODO
==================================================

In [73]:
Zenodo_parent_df, Zenodo_parent_summary = analyze_parent_data("Zenodo", full_parent_df)

=================================================================
 CONSOLIDATED ANALYSIS: ZENODO
=================================================================
  > Total Parent Groups:     67,908
  > Total Versions Found:    161,491
  > Unique Parent DOIs:      67,908
-----------------------------------------------------------------

 VERSIONING DISTRIBUTION for Zenodo:
-----------------------------------
  1 version(s):     6,942 groups
  2 version(s):     48,920 groups
  3 version(s):     6,665 groups
  4 version(s):     2,732 groups
  5 version(s):     942 groups
  6 version(s):     539 groups
  7 version(s):     290 groups
  8 version(s):     204 groups
  9 version(s):     122 groups
  10 version(s):    109 groups
  11 version(s):    71 groups
  12 version(s):    66 groups
  13 version(s):    35 groups
  14 version(s):    41 groups
  15 version(s):    18 groups
  16 version(s):    22 groups
  17 version(s):    20 groups
  18 version(s):    14 groups
  19 version(s):    12 groups
  20 version(s):    15 groups
  21 version(s):    5 groups
  22 version(s):    10 groups
  23 version(s):    11 groups
  24 version(s):    6 groups
  25 version(s):    3 groups
  26 version(s):    3 groups
  27 version(s):    4 groups
  28 version(s):    4 groups
  29 version(s):    7 groups
  30 version(s):    1 groups
  31 version(s):    3 groups
  32 version(s):    3 groups
  33 version(s):    2 groups
  34 version(s):    2 groups
  35 version(s):    2 groups
  36 version(s):    5 groups
  37 version(s):    2 groups
  38 version(s):    1 groups
  39 version(s):    3 groups
  41 version(s):    1 groups
  42 version(s):    1 groups
  43 version(s):    2 groups
  44 version(s):    4 groups
  45 version(s):    3 groups
  47 version(s):    3 groups
  48 version(s):    1 groups
  49 version(s):    2 groups
  51 version(s):    1 groups
  53 version(s):    1 groups
  54 version(s):    1 groups
  57 version(s):    1 groups
  58 version(s):    1 groups
  59 version(s):    1 groups
  62 version(s):    1 groups
  65 version(s):    1 groups
  66 version(s):    1 groups
  67 version(s):    1 groups
  70 version(s):    1 groups
  75 version(s):    1 groups
  76 version(s):    2 groups
  77 version(s):    1 groups
  78 version(s):    1 groups
  81 version(s):    1 groups
  84 version(s):    2 groups
  86 version(s):    1 groups
  88 version(s):    1 groups
  94 version(s):    1 groups
  115 version(s):   1 groups
  119 version(s):   1 groups
  128 version(s):   1 groups
  135 version(s):   1 groups
  159 version(s):   1 groups
  162 version(s):   1 groups
  167 version(s):   1 groups
  177 version(s):   1 groups
  210 version(s):   1 groups
  261 version(s):   1 groups
  286 version(s):   1 groups
  569 version(s):   1 groups
  702 version(s):   1 groups

  Average versions per parent: 2.38

 MOST RECENT DESTINATIONS (Migration):
-----------------------------------
most_recent_version_servers
Zenodo                    66163
ResearchGate                285
arXiv                       248
Open Science Framework      244
HAL; Zenodo                 152
SSRN                        147
Preprints.org               111
bioRxiv                      65
Authorea Inc.                65
TechRxiv                     55

 TOP VALUES FOR: DOI_PREFIX_FIRST_TOKEN
-----------------------------------
doi_prefix_first_token
10.5281/zenodo    67908



 TOP VALUES FOR: PRIMARY_DOMAIN
-----------------------------------
primary_domain
zenodo.org    67908


=================================================================
 COMPLETED: ZENODO
=================================================================